- bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
> [bsp][stm32][driver] remove extra brackets

- bsp/stm32/stm32f072-st-nucleo/README.md
- bsp/stm32/stm32f072-st-nucleo/README_zh.md
[
add English version readme for the stm32f072 nucleo board
]
> 【English readme】[bsp][stm32][f072-nucleo] add English version readme

- bsp/stm32/stm32f091-st-nucleo/README.md
[
update readme document of stm32f091 Nucleo board 
]
> 【English readme】[bsp][stm32][f091] update readme

- bsp/stm32/stm32f411-st-nucleo/README.md
- bsp/stm32/stm32f411-st-nucleo/README_zh.md
[
[bsp][stm32][f411] add English version readme
]
> 【English readme】[bsp][stm32][f411] add English version readme

- components/drivers/touch/touch.h
[
完善TOUCH设备命令，增加：
```
#define  RT_TOUCH_CTRL_POWER_ON          (8)   /* Touch Power On */
#define  RT_TOUCH_CTRL_POWER_OFF         (9)   /* Touch Power Off */
#define  RT_TOUCH_CTRL_GET_STATUS        (10)  /* Get Touch Power Status */
```
这样上层应用可以通过CONTROL命令，开关TOUCH设备，获取电源状态等
]
> [componets/drivers/touch]完善Touch设备命令

- components/dfs/filesystems/romfs/dfs_romfs.c
- components/dfs/filesystems/romfs/dfs_romfs.h
Signed-off-by: yangfasheng <yangfasheng@rt-thread.com>
[
修改代码以支持打包 BIN 文件时设置的地址与实际挂载文件系统的地址不一致的情况
]
> [components][dfs][filesystems][romfs]支持 BIN 文件打包地址与实际挂载地址不一致

- libcpu/aarch64/common/cpu.c
- libcpu/arc/em/cpuport.c
- libcpu/arm/AT91SAM7S/cpu.c
- libcpu/arm/AT91SAM7X/cpu.c
- libcpu/arm/am335x/cpu.c
- libcpu/arm/arm926/cpuport.c
- libcpu/arm/armv6/cpuport.c
- libcpu/arm/cortex-a/cpu.c
- libcpu/arm/cortex-m3/cpuport.c
- libcpu/arm/cortex-m33/cpuport.c
- libcpu/arm/cortex-m4/cpuport.c
- libcpu/arm/cortex-m7/cpuport.c
- libcpu/arm/cortex-r4/cpu.c
- libcpu/arm/dm36x/cpuport.c
- libcpu/arm/lpc214x/cpuport.c
- libcpu/arm/lpc24xx/cpu.c
- libcpu/arm/realview-a8-vmm/cpu.c
- libcpu/arm/s3c24x0/cpu.c
- libcpu/arm/s3c44b0/cpu.c
- libcpu/arm/sep4020/cpu.c
- libcpu/arm/zynq7000/cpu.c
- libcpu/avr32/uc3/cpu.c
- libcpu/mips/gs232/cpuport.c
- libcpu/risc-v/common/cpuport.c
- libcpu/risc-v/nuclei/cpuport.c
- libcpu/risc-v/t-head/e906/cpuport.c
- libcpu/rx/cpuport.c
- libcpu/ti-dsp/c28x/cpuport.c
- libcpu/unicore32/sep6200/cpu.c
- libcpu/xilinx/microblaze/cpu.c
[
重启与关机函数：rt_hw_cpu_shutdown、rt_hw_cpu_reset，增加 WEAK属性。
方便设备管理层调用，用户可以重新实现，而不用更改cpuport.c。
Apollo3平台验证通过
]
> [libcpu][update]重启与关机函数：rt_hw_cpu_shutdown、rt_hw_cpu_reset，补充WEAK属性

- components/drivers/pm/pm.c
[
1、优化PM组件电源模式选择问题，每次request/release后，决策更新下一次的睡眠模式。保证业务请求的最高功耗模式有效。
2、解决 https://github.com/RT-Thread/rt-thread/issues/3641 提及的问题
验证平台：STM32L4、Apollo3
]
> [components][PM][Update]优化PM电源模式选择问题

- bsp/stm32/libraries/HAL_Drivers/drv_sdio.c
[
修复 stm32 drv_sdio.c 使用 C 库 memcpy 函数时，会导致非对其访问 。
https://github.com/RT-Thread/rt-thread/issues/3583
]
> [fix] fix sdio non-aligned access problem

- bsp/nrf5x/libraries/drivers/SConscript
- bsp/nrf5x/libraries/drivers/drv_i2c.c
- bsp/nrf5x/libraries/drivers/drv_i2c.h
- bsp/nrf5x/nrf52832/board/Kconfig
- bsp/nrf5x/nrf52832/board/sdk_config.h
- bsp/nrf5x/nrf52840/board/Kconfig
- bsp/nrf5x/nrf52840/board/sdk_config.h
[
添加I2C驱动
已在nRF52840-DK完成驱动LM75测试
已在具有nRF52832硬件设备上完成SPL06-001气压计的驱动测试
]
> [bsp/nrf5x]support for i2c

- bsp/qemu-vexpress-gemini/drivers/vbus_hw.h
[
Added define __VBUS_HW_H__
]
> [bsp/drivers]Update vbus_hw.h

- bsp/imxrt/libraries/drivers/drv_can.h
[
DRV_SPI_H__ change to DRV_CAN_H__
]
> [bsp/driver]Update drv_can.h

- bsp/qemu-vexpress-a9/qemu-nographic.sh
- components/finsh/msh.c
- components/lwp/arch/arm/cortex-a/arch_user_space_init.c
- components/lwp/arch/arm/cortex-a/arch_user_stack.c
- components/lwp/arch/arm/cortex-a/lwp_arch.h
- components/lwp/arch/arm/cortex-a/lwp_gcc.S
- components/lwp/lwp_syscall.c
- libcpu/arm/cortex-a/trap.c
sync rt-smart version from gitee.
> sync rt-smart version from gitee.

- bsp/allwinner_tina/drivers/spi/drv_spi.c
[修改allwinner_tina分支spi 板级驱动判断 spi mode 条件错误的问题]
> [bsp][allwinner_tina]fixed spi driver bug

- bsp/stm32/libraries/HAL_Drivers/drv_sdio.c
[
拼写错误
rthw_sd_delect -> rthw_sd_detect
]
> [bsp][stm32]Fixed spelling errors in drv_sdio.c

- components/dfs/filesystems/devfs/devfs.c
Device file system should be registered
[
修改一处注释错误
]
> Modify comment error

- bsp/thead-smart/README.md
[ Update README.md for markdown format. ]
> [BSP] Update README.md for thread-smart

- bsp/stm32/libraries/STM32MPxx_HAL/SConscript
- bsp/stm32/stm32mp157a-st-ev1/board/CubeMX_Config/CM4/Inc/stm32mp1xx_hal_conf.h
- bsp/stm32/stm32mp157a-st-ev1/board/CubeMX_Config/CM4/Src/stm32mp1xx_hal_msp.c
- bsp/stm32/stm32mp157a-st-ev1/board/Kconfig
- bsp/stm32/stm32mp157a-st-ev1/board/SConscript
- bsp/stm32/stm32mp157a-st-ev1/board/board.h
- bsp/stm32/stm32mp157a-st-ev1/board/linker_scripts/link.icf
- bsp/stm32/stm32mp157a-st-ev1/board/ports/OpenAMP/drv_openamp.c
- bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_emmc.c
- bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_emmc.h
- bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_pmic.c
- bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_sdcard.c
- bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_sound.c
- bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_wm8994.c
- bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_wm8994.h
- bsp/stm32/stm32mp157a-st-ev1/board/ports/eth/drv_eth.c
- bsp/stm32/stm32mp157a-st-ev1/board/ports/eth/drv_eth.h
[
添加 STM32MP157A 高级外设驱动代码 ：ETH，SDMMC(SD_CARD, EMMC)，SAI(WM8994)（待更新）。
所有驱动代码已在 STM32MP157A-EV1 开发板上测试完成。
]
> [add] complicated dirvers for STM32MP157A-EV1 board

- bsp/allwinner_tina/drivers/drv_uart.c
[修改allwinner_tina串口1 rx/tx 引脚对应错误的问题]
> [bsp][allwinner_tina]fixed uart1 gpio rx/tx pin;

- components/drivers/src/workqueue.c
> [components][workqueue] Modify system work queue initialization level

- bsp/nrf5x/libraries/drivers/drv_adc.c
- bsp/nrf5x/libraries/drivers/drv_adc.h
[
#define ADC_NAME adc updated to header file.
]
> #define ADC_NAME adc updated to header file.

- components/drivers/include/drivers/alarm.h
- components/drivers/rtc/alarm.c
- components/drivers/rtc/soft_rtc.c
[
* 1、alarm开启、停止返回值问题修复，优化alarm_dump。
* 2、soft_rtc增加alarm功能
* 3、alarm获取时间的函数更改为不带时区的函数，兼容win32。
验证平台：模拟器、Apollo3验证通过
]
> [RTC alarm]alarm功能优化，SOFT_RTC增加alarm功能

- components/drivers/usb/usbdevice/class/audio_mic.c
- components/drivers/usb/usbdevice/class/audio_speaker.c
- components/drivers/usb/usbdevice/class/cdc_vcom.c
- components/drivers/usb/usbdevice/class/hid.c
- components/drivers/usb/usbdevice/class/mstorage.c
- components/drivers/usb/usbdevice/class/winusb.c
[
1. delete '#include <rtservice.h>', because rtthread.h had include rtservice.h;
2. delete '#include <rtthread.h>', because rtdevice.h had include rtthread.h.
]
> [components / drivers]update audio_mic.c

- components/drivers/audio/audio.c
- components/drivers/audio/audio_pipe.c
- components/drivers/audio/audio_pipe.h
[
fixed re-include '.h' file of  audio
]
> [components/drivers]fixed re-include '.h' file of audio

- bsp/stm32/libraries/STM32F0xx_HAL/STM32F0xx_HAL_Driver/Inc/stm32f0xx_hal.h
- bsp/stm32/libraries/STM32F1xx_HAL/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal.h
- bsp/stm32/libraries/STM32F2xx_HAL/STM32F2xx_HAL_Driver/Inc/stm32f2xx_hal.h
- bsp/stm32/libraries/STM32F4xx_HAL/STM32F4xx_HAL_Driver/Inc/stm32f4xx_hal.h
- bsp/stm32/libraries/STM32F7xx_HAL/STM32F7xx_HAL_Driver/Inc/stm32f7xx_hal.h
- bsp/stm32/libraries/STM32G0xx_HAL/STM32G0xx_HAL_Driver/Inc/stm32g0xx_hal.h
- bsp/stm32/libraries/STM32G4xx_HAL/STM32G4xx_HAL_Driver/Inc/stm32g4xx_hal.h
- bsp/stm32/libraries/STM32H7xx_HAL/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal.h
- bsp/stm32/libraries/STM32L0xx_HAL/STM32L0xx_HAL_Driver/Inc/stm32l0xx_hal.h
- bsp/stm32/libraries/STM32L4xx_HAL/STM32L4xx_HAL_Driver/Inc/stm32l4xx_hal.h
[
stm32f072-st-nucleo
stm32f103-atk-nano
stm32f401-st-nucleo
stm32f746-st-disco
stm32g070-st-nucleo
stm32g431-st-nucleo
stm32h743-atk-apollo
stm32l4r5-st-nucleo
stm32l010-st-nucleo
stm32l412-st-nucleo
stm32mp157a-st-discovery
stm32wb55-st-nucleo
以上 BSP 均 scons 编译通过
以上 BSP 均 MDK 编译通过
]
> [bsp][stm32][libraries] Remove #include <rtthread.h>

- components/net/lwip-1.4.1/src/netif/ethernetif.c
[
Add dhcp start or stop function to start or stop dhcp.
]
> [net/lwip1.4.1]Update ethernetif.c

- components/net/lwip-2.1.2/src/netif/ethernetif.c
[
Add dhcp start or stop function to start or stop dhcp.
]
> [net/lwip2.1.2]Update ethernetif.c

- src/scheduler.c
[
系统 kernel 里不应该包含 设备框架 或 组件 的配置宏
移除内核中的 RT_USING_FINSH，移除 remove list_thread()。
]
> [src][scheduler] remove RT_USING_FINSH in kernel, remove list_thread()

- .github/workflows/action.yml
[
- simplified ci file, clearer matrix structure;
- separation install arm and mips toolchains to decrease time;  
]
> [update] ci

- components/net/at/at_socket/at_socket.c
- components/net/netdev/src/netdev.c
- components/net/sal_socket/src/sal_socket.c
2、sal socket在支持多网卡时，sal_getaddrinfo从A网卡获取的地址信息，在sal_freeaddrinfo释放时必须由A网卡进行释放
[
]
The following content must not be changed in the submitted PR message. …
> fix at socket and sal_socket bug

- .github/workflows/action.yml
- components/net/netdev/src/netdev.c
[
modefy NETDEV_IFCONFIG_IEMI_MAX_LEN -> NETDEV_IFCONFIG_IMEI_MAX_LEN.
]
> [IMEI] Incorrect macro definition name and update jobs name.

- components/drivers/Kconfig
- components/drivers/i2c/i2c-bit-ops.c
- components/drivers/include/drivers/i2c.h
> [dirver/i2c] i2c driver support bus lock, STOP control

- components/drivers/audio/audio_pipe.c
[
Header files are repeatedly included. compile will failed, Has been tested with IAR and Eclipse.
change header file reference, compile success.
]
> [Audio] Header files are repeatedly included

- components/drivers/serial/serial.c
[
示例代码：
#include <sys/ioctl.h>
#include <unistd.h>
struct winsize window;
window.ws_col = 10;
window.ws_row = 10;
ioctl(STDOUT_FILENO, TIOCSWINSZ, &window);
已经在潘多拉板子测试通过
]
> [ioctl] add TIOCSWINSZ

- components/libc/compilers/armlibc/sys/unistd.h
- components/libc/compilers/common/sys/time.h
- components/libc/compilers/dlib/sys/unistd.h
补充 https://github.com/RT-Thread/rt-thread/issues/3938 所提到的缺失的结构体
> [bug][keil][libc]修复开启pthread功能后keil报错的问题

- .github/workflows/action.yml
- bsp/stm32/libraries/STM32MPxx_HAL/SConscript
- bsp/stm32/stm32mp157a-st-discovery/board/CubeMX_Config/CM4/Src/stm32mp1xx_hal_msp.c
- bsp/stm32/stm32mp157a-st-discovery/board/board.h
- bsp/stm32/stm32mp157a-st-discovery/board/linker_scripts/link.sct
- bsp/stm32/stm32mp157a-st-discovery/template.uvoptx
- bsp/stm32/stm32mp157a-st-discovery/template.uvprojx
- bsp/stm32/stm32mp157a-st-ev1/board/CubeMX_Config/CM4/Src/stm32mp1xx_hal_msp.c
- bsp/stm32/stm32mp157a-st-ev1/board/Kconfig
- bsp/stm32/stm32mp157a-st-ev1/board/board.c
- bsp/stm32/stm32mp157a-st-ev1/board/board.h
- bsp/stm32/stm32mp157a-st-ev1/board/linker_scripts/link.sct
- bsp/stm32/stm32mp157a-st-ev1/template.uvoptx
- bsp/stm32/stm32mp157a-st-ev1/template.uvprojx
[
modify link script file, all changes have been test on the stm32mp1 development board.
]
> [update] stm32mp1 mdk link script file

- components/net/netdev/src/netdev.c
[
It's better use RT_NAME_MAX here.
]
> Fix possible array out of bounds

- bsp/nuclei/README.md
- bsp/nuclei/gd32vf103_rvstar/README.md
- bsp/nuclei/gd32vf103_rvstar/SConstruct
- bsp/nuclei/hbird_eval/README.md
- bsp/nuclei/hbird_eval/SConstruct
* Update `scons --run=upload` command script to fix upload message not correct issue.
Although the program elf is uploaded successfully, the upload message is
still "Remote communication error.“, but actually upload works.
After fix, it will be "[Inferior 1 (Remote target) detached]"
* Update documentation for `rvstar` and `hbird-eval` get started with RT-Thread
* Checked latest nuclei-sdk 0.3.0 release with latest rt-thread source code, it works
> bsp/nuclei: Update upload command and document

- components/drivers/sensors/sensor.c
- components/drivers/sensors/sensor.h
- components/drivers/sensors/sensor_cmd.c
[
sensor框架增加TOF sensor类型，已在VL53L0X TOF传感器软件包上测试使用。
]
> [sensor] support TOF sensor class 

- bsp/stm32/libraries/HAL_Drivers/drv_crypto.c
[
解决当不启用 **HASH2_DMA_IN**，**CRYP2_IN_DMA**，**CRYP2_OUT_DMA** 时导致的编译错误。
已在STM32H743芯片上测试并通过编译
]
> [FIX] fix build problem in drv_crypto.c

- bsp/bluetrum/ab32vg1-ab-prougen/.config
- bsp/bluetrum/ab32vg1-ab-prougen/link.lds
- bsp/bluetrum/ab32vg1-ab-prougen/rtconfig.h
- bsp/bluetrum/libcpu/cpu/context_gcc.S
- bsp/bluetrum/libcpu/cpu/cpuport.c
[
修复上下文切换的问题
已在 ab32vg1-ab-prougen 上验证
]
> [bsp][bluetrum] fix context switch error

- tools/menuconfig.py
[
優化通過備份 .config 文件爲 .config.old，使用 diff 工具對比 .config 文件是否發生變化，而不再根據 .config 文件的時間戳對比 .config 文件是否發生變化：
實際的使用場景：當通過 menuconfig 修改了配置選項 重新生成了 .config 後可以正常產生 rtconfig.h 頭文件，
但是如果通過 git checkout .config 回退到初始的 .config 或者其他方式手動修改了 .config 文件，在這些
場景，即使執行了 scons --menuconfig， 也不會更新 rtconfig.h 頭文件，除非強制 添加 --useconfig .config 來強制更新 rtconfig.h ，因爲更新的前提是通過 scons --menuconfig 配置時候手動對選項進行了修改。該 patch 通過備份最近一次的 .config 文件爲 .config.old，然後通過 diff 工具來對比 .config 文件是否發生改動，也可以方便後期對比 .config 配置選項的差異。
在 ART-Pi 板卡測試通過，測試開發環境(Fedora 32 (Thirty Two) x86_64)
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to …
> [tools] 完善 scons --menuconfig 更新 rtconfig.h 文件的邏輯

- bsp/stm32/libraries/HAL_Drivers/drv_common.c
- src/scheduler.c
[
更新 void HAL_Delay(__IO uint32_t Delay) 函数
stm32f407-atk-explorer 上跑以太网例程 ok
]
> [BSP][STM32] update void HAL_Delay(__IO uint32_t Delay)

- src/memheap.c
在memheap.c中增加获取内存信息的接口rt_memory_info()
> add rt_memory_info() for memheap.c

- bsp/bluetrum/ab32vg1-ab-prougen/.config
- bsp/bluetrum/ab32vg1-ab-prougen/link.lds
- bsp/bluetrum/ab32vg1-ab-prougen/makefile.targets
- bsp/bluetrum/ab32vg1-ab-prougen/pre_build.sh
- bsp/bluetrum/libcpu/cpu/context_gcc.S
- bsp/bluetrum/libcpu/cpu/cpuport.c
[
更新了一下链接文件，避免一些奇怪的问题
整理了一下 `context_gcc.S` 的格式
在 `ab32vg1-ab-prougen` 上测试
]
> [bsp][bluetrum] update link.lds

- components/drivers/include/drivers/pm.h
- components/drivers/pm/pm.c
[
【Update PM2.0】更新RT-Thread PM 2.0框架。
更新说明：
1、丰富request/release接口，增加module_id
2、初始化时的电源模式，依旧有引用计数，无request则进入深睡眠【DEEPSLEEP】
3、增加延时睡眠的接口，方便用户延时睡眠的操作。
4、优化电源模式的选择
验证平台： STM32L4、Apollo3+ 验证通过。
其他补充：
https://club.rt-thread.org/ask/article/2282.html
]
> [update][PM]更新RT-Thread PM2.0框架

- bsp/qemu-vexpress-a9/SConscript
- bsp/qemu-vexpress-a9/applications/SConscript
- bsp/qemu-vexpress-a9/applications/lcd_init.c
- bsp/qemu-vexpress-a9/applications/main.c
- bsp/qemu-vexpress-a9/applications/mnt.c
- bsp/qemu-vexpress-a9/drivers/audio/drv_ac97.c
- bsp/qemu-vexpress-a9/drivers/audio/drv_ac97.h
- bsp/qemu-vexpress-a9/drivers/audio/drv_pl041.c
- bsp/qemu-vexpress-a9/drivers/audio/drv_pl041.h
- bsp/qemu-vexpress-a9/drivers/automac.h
- bsp/qemu-vexpress-a9/drivers/board.h
- bsp/qemu-vexpress-a9/drivers/drv_clcd.c
- bsp/qemu-vexpress-a9/drivers/drv_clcd.h
- bsp/qemu-vexpress-a9/drivers/drv_keyboard.c
- bsp/qemu-vexpress-a9/drivers/drv_keyboard.h
- bsp/qemu-vexpress-a9/drivers/drv_mouse.c
- bsp/qemu-vexpress-a9/drivers/drv_mouse.h
- bsp/qemu-vexpress-a9/drivers/drv_sdio.c
- bsp/qemu-vexpress-a9/drivers/drv_sdio.h
- bsp/qemu-vexpress-a9/drivers/drv_smc911x.c
- bsp/qemu-vexpress-a9/drivers/realview.h
- bsp/qemu-vexpress-a9/drivers/serial.c
- bsp/qemu-vexpress-a9/drivers/serial.h
- bsp/qemu-vexpress-a9/qemu-nographic.sh
- src/device.c
- src/thread.c
Use object_find to implement thread_find/device_find and add license info in vexpress-a9 BSP. Verified on qemu-vexpress-a9 BSP.
> Use object_find to implement thread_find/device_find

- bsp/stm32/stm32f767-fire-challenger/rtconfig.py
[修改stm32f767-fire-challenger rtconfig.py python文件空格和tab混用的问题]
> [bsp][stm32][stm32f767-fire-challenger]修改python 空格和tab混用的问题

- components/net/Kconfig
- components/net/netdev/src/netdev.c
- components/net/sal_socket/src/sal_socket.c
[
[add] a new function to manage internet check.
You can chose whether open the fucntion that check internet status or not by yourself.
* have tested on qemu - A9
* have tested on stm32f407-atk
]
> [add] a new function to manage internet check.

- src/SConscript
[
signal.c 改为可移除的 如果定义RT_USING_SIGNALS就添加到工程中 反之则移除
另外 https://github.com/RT-Thread/rt-thread/blob/master/src/SConscript#L9 这个是不是已经过时了？ src中并没有module.c文件
]
> [kernel] update sconscript

- src/SConscript
> [kernel] [script] remove module.c

- src/ipc.c
[
消息队列可以发送FIFO LIFO 但是邮箱目前只能发FIFO
因此补充增加邮箱紧急发送邮件功能 即LIFO功能
基于rt_mb_send_wait()函数改编
主要改动为此部分
```c
/* rewind to the previous position */
if(mb->out_offset > 0)
{
mb->out_offset --;
}
else
{
mb->out_offset = mb->size - 1;
}
/* set ptr */
mb->msg_pool[mb->out_offset] = value;
```
并移除了阻塞部分的代码。
附测试例程，已经在潘多拉测试过[mailbox_sample.zip](https://github.com/RT-Thread/rt-thread/files/5760944/mailbox_sample.zip)
] …
> [kernel] add rt_mb_urgent()

- libcpu/arm/arm926/start_gcc.S
[
For [Issue: 4232](https://github.com/RT-Thread/rt-thread/issues/4232).
I don't know which one platform will be affected after applying.
]
> [libcpu/arm/arm926/start_gcc.S] Remove platform-specific code in common.

- bsp/stm32/stm32f401-st-nucleo/README.md
- bsp/stm32/stm32mp157a-st-discovery/README.md
- bsp/stm32/stm32mp157a-st-ev1/README.md
> [readme] update

- bsp/imxrt/libraries/drivers/drv_uart.c
> fix imxrt uart2 wrong configure

- .gitignore
- bsp/stm32/stm32f103-blue-pill/README.md
[
.gitignore文件内增加dist文件夹，防止导出dist后，一git蹦出一堆文件
顺便到更新了一下bluepill的图片文件名
]
> [.gitignore] 将dist文件夹滤掉

- components/utilities/ulog/ulog.c
- components/utilities/ulog/ulog.h
- components/utilities/ulog/ulog_def.h
[
- 添加指定后端的日志过滤接口
- 添加异步日志输出控制接口
- 修改 ulog 锁功能实现，mutex -> sem
- 改动已经在 ART-PI、qemu 环境下验证
]
> [ulog] Add backend filtering interface, add async log output control interface, ulog mutex change to semaphore

- bsp/stm32/libraries/HAL_Drivers/config/mp1/dma_config.h
- bsp/stm32/libraries/HAL_Drivers/drv_usart.c
- bsp/stm32/stm32mp157a-st-ev1/board/Kconfig
- bsp/stm32/stm32mp157a-st-ev1/board/ports/dma_sample.c
[
update dma sample, add uart dma rx sample.
]
> [update] stm32mp1 uart dma sample.

- tools/eclipse.py
- tools/rt_studio.py
[ 
1. 当 bsp 中已经包含 makefile.targets 文件时，保留该文件
2. 当 bsp 中没有 makefile.targets文件时，使用模板生成
3. 当 bsp 中含有 uvprojx, uvproj  文件时，从 uvprojx, uvproj 文件中分析 device name 信息；优先使用 uvprojx 文件
4. 当 bsp 中没有 uvprojx, uvproj 文件时，设置 device name 信息为 unknown
]
> fixbug:keep makefile.targets while it has existed

- bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
[
https://gitee.com/rtthread/rt-thread/issues/I2E9I4
Fix the pwm clock frequency doubling problem.
已在 F4 上进行测试
]
> [PWM] Fix the pwm clock frequency doubling problem.

- bsp/ls2kdev/drivers/board.c
- bsp/ls2kdev/rtconfig.h
[
bsp:ls2k:make set console device more flexible
]
> bsp:ls2k:make set console device more flexible

- components/utilities/ulog/ulog.c
[
- 添加 LOG_RAW 日志打印缓冲区，修复打印长度限制导致日志显示不全问题；
- 该修改已经在 ART-PI 和 QEMU 中验证；
]
> [utilities][ulog] Add LOG_RAW ringbuffer to fix printing line limit issue

- bsp/bluetrum/ab32vg1-ab-prougen/.config
- bsp/bluetrum/ab32vg1-ab-prougen/board/Kconfig
- bsp/bluetrum/ab32vg1-ab-prougen/link.lds
- bsp/bluetrum/libraries/hal_drivers/SConscript
- bsp/bluetrum/libraries/hal_drivers/config/adc_config.h
- bsp/bluetrum/libraries/hal_drivers/drv_adc.c
- bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/SConscript
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/include/ab32vg1_hal_adc.h
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/include/ab32vg1_hal_conf.h
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/include/ab32vg1_hal_rtc.h
- bsp/bluetrum/libraries/hal_libraries/bmsis/include/ab32vg1.h
[
添加  adc 和 rtc 驱动
已在 ab32vg1-ab-prougen 上验证
]
> [bsp][bluetrum] add adc and rtc support

- src/kservice.c
[
rt_kprintf
rt_memcpy
rt_memset
rt_memcmp
]
> [kernel][kservice] add RT_WEAK for several functions

- components/drivers/sdio/sdio.c
[
对 /pull/4163 做了整理后的 PR
已在 ART-Pi 上测试
]
> [sdio] free memory and enhance performance

- .github/workflows/action.yml
> [action.yml] 移除gkipc BSP 防止该BSP无人维护导致CI报错

- include/libc/libc_ioctl.h
- include/rtdef.h
- src/components.c
[
添加对 TASKING 工具链的支持。
本地测试正常。
]
> [toolchain] Added support for the TASKING toolchain.

- bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
[
PWMN_CMD_DISABLE  的配置和 PWMN_CMD_ENABLE  重复了
]
> [bsp][stm32] fix PWMN_CMD_DISABLE config

- bsp/raspberry-pi/raspi4-32/driver/touch/drv_xpt2046.c
[
This is device xpt2046, so  device name xpt2049 is error  , changed xpt2049 -> xpt2046.
]
> [bsp] mini optimized the drv_xpt2046.c

- components/libc/compilers/newlib/libc.h
- components/libc/compilers/newlib/syscalls.c
[
1. 删除_gettimeofday_r() 和 _times_r()接口函数的实现, 该功能已经由common/time.c内的函数替代，无需实现
2. 移除libc.c libc.h无用代码
involved #3938
GCC编译通过
]
> [libc][newlib]remove _gettimeofday_r() and _times_r()

- bsp/dm365/applications/board.c
- bsp/fh8620/platform/fh8620/iot_cam/startup.c
- bsp/imxrt/libraries/drivers/drv_lcd.c
- bsp/imxrt/libraries/drivers/drv_sdio.c
- bsp/lpc43xx/M0/applications/vbus_drv.c
- bsp/lpc43xx/M4/applications/application.c
- bsp/lpc43xx/M4/applications/vbus_drv.c
- bsp/lpc43xx/drivers/drv_emac.c
- bsp/mini2440/drivers/board.c
- bsp/sep6200/application/startup.c
- components/finsh/finsh_api.h
- components/net/at/include/at.h
- components/utilities/utest/utest.h
- components/vmm/vmm.c
- components/vmm/vmm_context.c
- include/rtdef.h
- include/rtm.h
- libcpu/arm/realview-a8-vmm/interrupt.c
- libcpu/arm/zynq7000/mmu.c
[
与catch2(https://github.com/catchorg/Catch2)中SECTION冲突. 因此修改为RT_SECTION
]
> SECTION改为RT_SECTION

- bsp/bluetrum/ab32vg1-ab-prougen/board/ports/audio/drv_sound.c
[
1. "tx_fifo = rt_calloc(1, TX_FIFO_SIZE); "  , so deleted the line "rt_memset(tx_fifo, 0, TX_FIFO_SIZE);"
2. "rx_fifo = rt_calloc(1, TX_FIFO_SIZE); "  , so deleted the line "rt_memset(rx_fifo, 0, TX_FIFO_SIZE);"
]
> [bsp]Mini optimized the drv_sound.c

- bsp/fh8620/drivers/i2c.c
[
Fixed the stack overflow bug in i2c.c
]
> [bsp]Fixed the stack overflow bug in i2c.c

- components/libc/compilers/dlib/syscall_remove.c
- components/libc/compilers/newlib/syscalls.c
> [libc][iar][gcc] 优化remove函数

- bsp/at32/Libraries/AT32_Std_Driver/AT32F4xx_StdPeriph_Driver/inc/at32f4xx_ertc.h
- bsp/at32/Libraries/rt_drivers/SConscript
- bsp/at32/Libraries/rt_drivers/drv_can.c
- bsp/at32/Libraries/rt_drivers/drv_can.h
- bsp/at32/Libraries/rt_drivers/drv_flash.c
- bsp/at32/Libraries/rt_drivers/drv_flash.h
- bsp/at32/at32f403a-start/README.md
- bsp/at32/at32f403a-start/board/Kconfig
- bsp/at32/at32f403a-start/board/board.h
- bsp/at32/at32f403a-start/board/msp/at32_msp.c
- bsp/at32/at32f403a-start/board/msp/at32_msp.h
- bsp/at32/at32f407-start/README.md
- bsp/at32/at32f407-start/board/Kconfig
- bsp/at32/at32f407-start/board/board.h
- bsp/at32/at32f407-start/board/msp/at32_msp.c
- bsp/at32/at32f407-start/board/msp/at32_msp.h
[
1. add can and flash drivers
2. fixed c++ compiler error
]
- [x ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
> 1.add can and on-chip-flash drivers 2.fixed c++ compiler error

- bsp/nrf5x/README.md
- bsp/nrf5x/nrf52832/board/board.h
- bsp/nrf5x/nrf52840/board/Kconfig
- bsp/nrf5x/nrf52840/board/board.c
- bsp/nrf5x/nrf52840/board/board.h
> [bsp/nrf5x] add the FAQ about hardfault

- bsp/stm32/stm32f429-atk-apollo/board/ports/sdcard_port.c
[
add the error state return value . 
]
> Fixed the return value bug in sdcard_port.c

- bsp/stm32/stm32f429-armfly-v6/board/ports/spi_flash_init.c
> Mini optimized the spi_flash_init.c

- src/ipc.c
[
IAR 上 `void *` 隐式转换会报错
将隐式转换改成强制转换
]
> [ipc] fix IAR Compilation error

- bsp/imxrt/libraries/MIMXRT1050/SConscript
- bsp/imxrt/libraries/drivers/drv_pwm.c
[
爲RT1052移植QTMR的PWM
Port QTMR to drv_pwm
已經在自製的imxrt1052 板子進行了對QTMR PWM驅動測試
Had tested QTMR PWM with a custom made imxrt1052 board
]
> 爲RT1052移植QTMR的PWM

- bsp/stm32/libraries/HAL_Drivers/drv_qspi.c
> [bsp][stm32][qspi]修复拼写错误

- bsp/raspberry-pico/drivers/drv_uart.c
> [bsp][raspberry-pico] Fixed failure to start without connecting to UART

- components/libc/compilers/common/stdlib.c
- src/thread.c
[
1. rt_thread_control() 关闭线程后增加rt_schedule调度
2. 整理rt_thread_control()函数格式 - 调整缩进，为每个case加花括号以示分割
3. 精简__rt_libc_exit()函数
]
> [kernel]  rt_thread_control() 关闭线程后增加rt_schedule调度

- libcpu/arm/cortex-m33/trustzone.c
[
CM33 libcpu 有几个 trustzone 相关的 API 需要外部提供。目前大部分场景，未使用 trustzone 的功能。特加一个宏将该部分函数打桩，解决链接报错
在 NXP 平台编译验证
]
> [libcpu][cm33] 安全相关的函数使用宏进行隔离

- components/libc/compilers/armlibc/syscalls.c
> [libc][armlibc] add multithreaded protection

- components/libc/compilers/newlib/syscalls.c
> [libc]fix bug of _isatty_r()

- bsp/stm32/libraries/HAL_Drivers/drv_dac.c
[
HAL_DAC_Start和HAL_DAC_Stop的第二个形参也是DAC_CHANNEL_1或者DAC_CHANNEL_2
]
> fix stm32 drv_dac.c some bugs

- components/libc/Kconfig
- components/libc/getline/README.md
- components/libc/getline/posix_getline.c
- components/libc/getline/posix_getline.h
> [libc][getline] 删除不必要的声明信息

- bsp/allwinner_tina/libcpu/interrupt.c
- bsp/allwinner_tina/libcpu/interrupt.h
[
Use structure to handle the registers access, which simplified the code and make the logic more explicate and self-describe. No real logic change.
]
> Cleanup Interrupt for F1S

- components/utilities/ulog/ulog.c
…hexdump
[
添加 LOG_HEX 打印 hex 格式数据时支持时间戳打印
stm32f103rct6 板卡测试过
]
> [components][ulog] Add support with timestamp print in function ulog_hexdump

- components/drivers/include/ipc/workqueue.h
- components/drivers/src/workqueue.c
[
1. 当前工作队列部分代码比较冗余，需要适当合并优化。
2. 有些地方临界区保护不够完整。
此 PR 优化代码体积，提高稳定性
使用完整的测试用例进行测试，并在实际产品中应用
]
> 优化工作队列体积，临界区保护更加完善

- bsp/fh8620/libraries/driverlib/fh_mmc.c
[
Deleted the un-reach code line 'break;'
]
> [bsp] Mini optimized the fh_mmc.c

- components/drivers/Kconfig
- components/drivers/usb/usbhost/class/hid.c
- components/drivers/usb/usbhost/class/hid.h
- components/drivers/usb/usbhost/class/umouse.c
[
修改了rt thread的usb host hid和umouse驅動，令其符合當前usb host的驅動
已經在自製的imxrt1052 板子進行了測試
]
> 修復usb host hid和umouse驅動

- bsp/nrf5x/nrf52832/.gitignore
- bsp/nrf5x/nrf52832/.vscode/launch.json
- bsp/nrf5x/nrf52832/.vscode/tasks.json
- bsp/nrf5x/nrf52832/README.md
- bsp/nrf5x/nrf52832/rtconfig.py
> [ADD]vscode support for nrf52832

- components/finsh/msh_file.c
[
添加 mount/umount 命令，方便调试
在 qemu 上进行测试
]
> [finsh] add mount/umount cmd

- bsp/smartfusion2/project.uvopt
- bsp/smartfusion2/project.uvoptx
- bsp/smartfusion2/project.uvproj
- bsp/smartfusion2/project.uvprojx
- bsp/smartfusion2/template.uvopt
- bsp/smartfusion2/template.uvproj
- bsp/smartfusion2/template.uvprojx
[
https://github.com/RT-Thread/rt-thread/pull/4303
上述pr在keil4上依然报错，未联系上该pr作者进行近一步修改，所以在此更新。
本pr增加了c99 配置  并更新了 keil4 keil5 工程。
]
> [bsp][samrtfusion2]add C99 support and update project files

- bsp/maxim/MAX32660_EVSYS/rtconfig.py
- bsp/maxim/tools/sdk_dist.py
> [bsp/max32660] add the scons --dist

- tools/building.py
1. 删除src 列表中的重复元素，避免导出为 MDK 工程时由于重复的文件被添加前缀，导致编译失败。
> [tools]修复由于 sconscript 文件 src 列表含有重复的文件，导致的导出 mdk 工程构建失败的问题

- components/libc/compilers/common/time.c
> [libc] remove difftime()

- examples/file/listdir.c
- examples/file/readspeed.c
- examples/file/readwrite.c
- examples/file/seekdir.c
- examples/file/writespeed.c
- examples/kernel/tc_comm.h
- examples/kernel/timer_control.c
- examples/kernel/timer_timeout.c
- examples/libc/dirent.c
- examples/libc/env.c
- examples/libc/ex1.c
- examples/libc/ex6.c
- examples/libc/ex7.c
- examples/libc/file.c
- examples/libc/memory.c
- examples/libc/mq.c
- examples/libc/printf.c
- examples/libc/rand.c
- examples/libc/sem.c
- examples/libc/time.c
- examples/network/tcpsendpacket.c
- examples/pm/timer_app.c
- examples/pm/wakeup_app.c
- examples/test/dhry.h
- examples/test/dhry_1.c
- examples/test/dhry_2.c
- examples/test/hwtimer_test.c
- examples/test/net_test.c
- examples/test/rtc_test.c
- examples/ulog/ulog_example.c
1. 将源文件编码统一为UTF-8
2. 将TAB键替换为空格
3. 将每行末尾多余的空格删除，并统一换行符为'\n'
4. 将RT-Thread版权信息的截至年份修改至今年
> [example] 格式化整理

- src/clock.c
- src/components.c
- src/cpu.c
- src/device.c
- src/idle.c
- src/ipc.c
- src/irq.c
- src/kservice.c
- src/mem.c
- src/memheap.c
- src/mempool.c
- src/object.c
- src/scheduler.c
- src/signal.c
- src/slab.c
- src/thread.c
- src/timer.c
> [kernel]auto formatted

- bsp/gd32103c-eval/Kconfig
- bsp/gd32103c-eval/README.md
- bsp/gd32103c-eval/drivers/SConscript
- bsp/gd32103c-eval/drivers/drv_iwdt.c
[
添加看门狗驱动
在 GD32103C-EVAL 板卡测试通过
]
> [bsp][gd32103c-eval] Add watchdog driver

- bsp/gd32103c-eval/Kconfig
- bsp/gd32103c-eval/README.md
- bsp/gd32103c-eval/drivers/SConscript
- bsp/gd32103c-eval/drivers/drv_rtc.c
[
添加 GD32103C 内置 RTC 驱动。
在 GD32103C-EVAL 板卡完成测试。
]
> [bsp][gd32103c-eval] Add internal rtc driver

- components/libc/compilers/common/sys/time.h
> [libc][time][bug] 修复ARM6报错的问题

- bsp/stm32/stm32f091-st-nucleo/board/Kconfig
- bsp/stm32/stm32f103-atk-nano/board/Kconfig
- bsp/stm32/stm32f103-atk-warshipv3/board/Kconfig
- bsp/stm32/stm32f103-blue-pill/board/Kconfig
- bsp/stm32/stm32f103-fire-arbitrary/board/Kconfig
- bsp/stm32/stm32f103-hw100k-ibox/board/Kconfig
- bsp/stm32/stm32f407-atk-explorer/board/Kconfig
- bsp/stm32/stm32f411-atk-nano/board/Kconfig
- bsp/stm32/stm32f411-st-nucleo/board/Kconfig
- bsp/stm32/stm32f413-st-nucleo/board/Kconfig
- bsp/stm32/stm32f429-armfly-v6/board/Kconfig
- bsp/stm32/stm32f429-atk-apollo/board/Kconfig
- bsp/stm32/stm32f429-fire-challenger/board/Kconfig
- bsp/stm32/stm32f767-atk-apollo/board/Kconfig
- bsp/stm32/stm32f767-fire-challenger/board/Kconfig
- bsp/stm32/stm32g070-st-nucleo/board/Kconfig
- bsp/stm32/stm32h743-atk-apollo/board/Kconfig
- bsp/stm32/stm32l412-st-nucleo/board/Kconfig
- bsp/stm32/stm32l432-st-nucleo/board/Kconfig
- bsp/stm32/stm32l433-st-nucleo/board/Kconfig
- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
- bsp/stm32/stm32l476-st-nucleo/board/Kconfig
- bsp/stm32/stm32l496-ali-developer/board/Kconfig
- bsp/stm32/stm32l4r5-st-nucleo/board/Kconfig
- bsp/stm32/stm32wb55-st-nucleo/board/Kconfig
[
删除RTC对libc的依赖
在libc调整之后，RTC已经不需要LIBC了
#3938
]
> [stm32]删除RTC对libc的依赖

- bsp/maxim/MAX32660_EVSYS/board/board.c
- bsp/maxim/MAX32660_EVSYS/rtconfig.py
> [bsp/max32660]add the fixed code

- components/drivers/serial/serial.c
[
目前已经实现TIOCSWINSZ指令，但是没有实现TIOCGWINSZ指令。缺失的TIOCGWINSZ指令已经开始对下游软件包产生影响。因此先返回固定的24*80 终端长宽数据，待终端参数返回问题解决之后，再动态获取终端窗口的实时数据。先解决有无的问题，在解决好不好的问题。
]
> [ioctl] 增加TIOCGWINSZ功能

- bsp/bluetrum/ab32vg1-ab-prougen/board/board.c
- bsp/bluetrum/ab32vg1-ab-prougen/board/board.h
- bsp/bluetrum/ab32vg1-ab-prougen/board/ports/audio/drv_sound.c
- bsp/bluetrum/libcpu/cpu/cpuport.c
- bsp/bluetrum/libcpu/cpu/interrupt.c
- bsp/bluetrum/libraries/hal_drivers/config/adc_config.h
- bsp/bluetrum/libraries/hal_drivers/config/tim_config.h
- bsp/bluetrum/libraries/hal_drivers/drv_adc.c
- bsp/bluetrum/libraries/hal_drivers/drv_common.h
- bsp/bluetrum/libraries/hal_drivers/drv_gpio.c
- bsp/bluetrum/libraries/hal_drivers/drv_gpio.h
- bsp/bluetrum/libraries/hal_drivers/drv_hwtimer.c
- bsp/bluetrum/libraries/hal_drivers/drv_log.h
- bsp/bluetrum/libraries/hal_drivers/drv_sdio.c
- bsp/bluetrum/libraries/hal_drivers/drv_sdio.h
- bsp/bluetrum/libraries/hal_drivers/drv_soft_i2c.c
- bsp/bluetrum/libraries/hal_drivers/drv_usart.c
- bsp/bluetrum/libraries/hal_drivers/drv_usart.h
- bsp/bluetrum/libraries/hal_drivers/drv_wdt.c
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/include/ab32vg1_hal_adc.h
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/include/ab32vg1_hal_gpio.h
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/include/ab32vg1_hal_gpio_ex.h
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/include/ab32vg1_hal_uart.h
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/source/ab32vg1_hal_gpio.c
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/source/ab32vg1_hal_sd.c
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/source/ab32vg1_hal_uart.c
- bsp/bluetrum/libraries/hal_libraries/bmsis/include/ab32vg1.h
[
自动化扫描bsp/bluetrum/：
1)将源文件编码统一为UTF-8
2)将TAB键替换为空格
3)将每行末尾多余的空格删除，并统一换行符为'\n'
]
> [bluetrum] auto formatted

- bsp/bluetrum/ab32vg1-ab-prougen/board/board.h
- bsp/bluetrum/libraries/hal_drivers/drv_wdt.c
- bsp/bluetrum/libraries/hal_drivers/drv_wdt.h
> [ab32vg1] 增加看门狗溢出时间宏定义

- include/rtdef.h
Signed-off-by: yangfasheng <yangfasheng@live.com>
[
调整图形设备驱动相关定义
在**湃心OS**上验证通过
]
> 【更新】调整图形设备驱动相关定义

- bsp/w60x/drivers/board.c
- bsp/w60x/drivers/drv_crypto.c
- bsp/w60x/drivers/drv_rtc.c
- bsp/w60x/drivers/drv_soft_i2c.c
- bsp/w60x/drivers/drv_soft_i2c.h
- bsp/w60x/drivers/drv_standby.c
- bsp/w60x/drivers/drv_uart.c
- bsp/w60x/drivers/pin_config.h
- bsp/w60x/oneshot/oneshot.c
- bsp/w60x/oneshot/oneshot.h
- bsp/w60x/oneshot/oneshot_demo.c
> [w60x][drivers] auto formatted

- bsp/x86/drivers/console.c
- bsp/x86/drivers/dma.h
- bsp/x86/drivers/floppy.c
- bsp/x86/drivers/include/bsp.h
- bsp/x86/drivers/include/grub.h
- bsp/x86/drivers/include/i386.h
- bsp/x86/drivers/keyboard.c
- bsp/x86/drivers/keyboard.h
- bsp/x86/drivers/keymap.h
- bsp/x86/drivers/serial.c
- bsp/x86/src/hello.c
> [x86][drivers] auto formatted

- bsp/bluetrum/libraries/hal_drivers/drv_common.h
- bsp/bluetrum/libraries/hal_drivers/drv_gpio.h
Signed-off-by: JiangYangJie <JiangYangJie@126.com>
[
实现获取PIN的函数，用于软件IIC获取PIN。
AB32VG1 RISC-V开发板 测试成功
]
> [ab32vg1] add GET_PIN(PORTx,PIN)

- bsp/bluetrum/ab32vg1-ab-prougen/README.md
> [ab32vg1] update readme

- src/Kconfig
- src/memheap.c
Signed-off-by: WillianChan <chentingwei@rt-thread.com>
[
添加内存堆跟踪和内存堆检查。
add memory heap track and memory heap check.
]
> [kernel][memheap]add memory heap track and memory heap check.

- components/libc/compilers/common/sys/time.h
[
simulator 编译出错，结构体定义冲突
使用宏限定部分结构体定义
在 simulator 上编译通过，并成功运行
]
> [libc] Fix Win32 compilation errors

- tools/eclipse.py
> [update] eclipse.py, to compatible with tricore.

- bsp/frdm-k64f/applications/startup.c
- bsp/mb9bf500r/startup.c
- include/rtthread.h
- src/device.c
> [kernel][device] remove rt_device_init_all()

- include/rtdef.h
[
增加对 TASKING  工具链更多 attributes  的支持
参考：[User Guide - v6.3r1 TriCore C Compiler](https://www.tasking.com/support/tricore/ctc_user_guide_v6.3r1.pdf)
]
> [toolchain] TASKING toolchain attributes update.

- src/kservice.c
[
Fix code comment error for function rt_memset().
]
> Fix code comment error for function rt_memset().

- bsp/maxim/MAX32660_EVSYS/README.md
- bsp/maxim/MAX32660_EVSYS/board/Kconfig
- bsp/maxim/libraries/HAL_Drivers/SConscript
- bsp/maxim/libraries/HAL_Drivers/drv_rtc.c
[
修改bsp/max32660, 添加硬件rtc设备支持, 以stm32 rtc设备实现为模版, 使用maxim sdk实现.
已在max32660 evsys上进行测试.
]
> [bsp/max32660] add onchip rtc support

- include/rtdef.h
[
修改 TASKING toolchain 中 `__attribute__((aligned(n)))` 为 `__attribute__((__align(n)))`。两者在手册注明均可用，但 `aligned(n)`  实测不可用，会有如下 warning:
```
ctc W576: unknown attribute "aligned" ignored	
```
]
> [toolchain] fix TASKING toolchain attributes .

- tools/eclipse.py
[
修改 eclipse.py, 兼容 tasking 编译器。
]
> [update] eclipse.py, 兼容 tasking.

- bsp/raspberry-pico/README.md
- bsp/raspberry-pico/drivers/board.c
- bsp/raspberry-pico/drivers/board.h
- bsp/raspberry-pico/drivers/drv_uart.c
- bsp/raspberry-pico/libraries/pico-sdk/src/rp2_common/pico_runtime/runtime.c
- bsp/raspberry-pico/link.ld
[
- [Fix] the problem of startup failure.
- [bsp][raspberry-pico]All memory is used for heap.
- [bsp][raspberry-pico]add uart1 support.
The test has been completed on the actual board.
]
> Optimize pico bsp

- components/finsh/shell.c
[
为了在 tricore 上开启 finsh，在 shell.c 中添加 `defined(__TASKING__) `
]
> [components][finsh] add support for tasking toolchain

- components/drivers/src/pipe.c
[
1. pipe name depend on RT_NAME_MAX
2. format function name
]
> pipe name depend on RT_NAME_MAX

- bsp/nuvoton/libraries/m2354/rtt_port/SConscript
- bsp/nuvoton/libraries/m480/rtt_port/SConscript
> [bsp][nuvoton] update to compatible with Python 3.

- libcpu/arm/am335x/context_iar.S
- libcpu/arm/zynqmp-r5/armv7.h
- libcpu/c-sky/ck802/contex_ck802_gcc.S
- libcpu/c-sky/ck802/core_ck802.c
- libcpu/c-sky/ck802/core_ck802.h
- libcpu/c-sky/ck802/stack_ck802.c
- libcpu/mips/common/mips_cache.c
- libcpu/mips/common/mips_cache.h
- libcpu/mips/common/mips_cfg.h
- libcpu/mips/common/mips_types.h
- libcpu/unicore32/sep6200/context_gcc.S
- libcpu/unicore32/sep6200/cpu.c
- libcpu/unicore32/sep6200/interrupt.c
- libcpu/unicore32/sep6200/sep6200.h
- libcpu/unicore32/sep6200/serial.c
- libcpu/unicore32/sep6200/serial.h
- libcpu/unicore32/sep6200/stack.c
- libcpu/unicore32/sep6200/start_gcc.S
- libcpu/unicore32/sep6200/trace.c
- libcpu/unicore32/sep6200/trap.c
[
将 libcpu 文件夹中，属于 rt-thread 版权部分的 GPL 许可改为 Apache2.0 许可
]
> [libcpu]update GPL license to Apache-2.0

- components/net/lwip-2.0.2/src/apps/tftp/tftp_port.c
- components/net/lwip-2.1.2/src/apps/tftp/tftp_port.c
[
将组件中，rt-thread 版权下为 GPL 许可的文件，改为 apache 许可
]
> [components]update GPL license to Apache-2.0

- bsp/allwinner_tina/applications/main.c
- bsp/allwinner_tina/drivers/board.c
- bsp/allwinner_tina/drivers/board.h
- bsp/allwinner_tina/drivers/drv_clock.c
- bsp/allwinner_tina/drivers/drv_clock.h
- bsp/allwinner_tina/drivers/drv_gpio.c
- bsp/allwinner_tina/drivers/drv_gpio.h
- bsp/allwinner_tina/drivers/drv_sdio.c
- bsp/allwinner_tina/drivers/drv_sdio.h
- bsp/allwinner_tina/drivers/drv_uart.c
- bsp/allwinner_tina/drivers/drv_uart.h
- bsp/allwinner_tina/drivers/spi/drv_spi.c
- bsp/allwinner_tina/drivers/spi/drv_spi.h
- bsp/allwinner_tina/drivers/spi/drv_spi_flash.c
- bsp/allwinner_tina/libcpu/cpu.c
- bsp/allwinner_tina/libcpu/cpuport.c
- bsp/allwinner_tina/libcpu/interrupt.c
- bsp/allwinner_tina/libcpu/interrupt.h
- bsp/allwinner_tina/libcpu/mmu.c
- bsp/allwinner_tina/libcpu/mmu.h
- bsp/allwinner_tina/libcpu/rt_low_level_init.c
- bsp/allwinner_tina/libcpu/stack.c
- bsp/allwinner_tina/libcpu/trap.c
> [allwinner_tina] manual & auto formatted

- bsp/taihu/applications/application.c
- bsp/taihu/applications/board.c
- bsp/taihu/applications/board.h
- bsp/taihu/applications/startup.c
- bsp/taihu/rtconfig.h
> [taihu] auto formatted

- bsp/apollo2/applications/main.c
- bsp/apollo2/board/adc.c
- bsp/apollo2/board/adc.h
- bsp/apollo2/board/board.c
- bsp/apollo2/board/board.h
- bsp/apollo2/board/flash.c
- bsp/apollo2/board/flash.h
- bsp/apollo2/board/gpio.c
- bsp/apollo2/board/gpio.h
- bsp/apollo2/board/i2c.c
- bsp/apollo2/board/i2c.h
- bsp/apollo2/board/led.c
- bsp/apollo2/board/led.h
- bsp/apollo2/board/pdm.c
- bsp/apollo2/board/pdm.h
- bsp/apollo2/board/pwm.c
- bsp/apollo2/board/pwm.h
- bsp/apollo2/board/rtc.c
- bsp/apollo2/board/rtc.h
- bsp/apollo2/board/smbus.c
- bsp/apollo2/board/smbus.h
- bsp/apollo2/board/spi.c
- bsp/apollo2/board/spi.h
- bsp/apollo2/board/uart.c
- bsp/apollo2/board/uart.h
> [apollo2] auto & manual formatted

- components/libc/pthreads/pthread.c
很多 pthread.c 的代码在拿到 `_pthread_get_data` 返回的结构体指针后没有检查是否为 nullptr 就进行了 dereference。
在 stm32f746 上测试通过
> [pthread] Enhance robustness for pthread

- bsp/stm32/stm32mp157a-st-discovery/board/ports/OpenAMP/libmetal/lib/include/metal/system/generic/alloc.h
- bsp/stm32/stm32mp157a-st-discovery/board/ports/OpenAMP/libmetal/lib/system/generic/alloc.h
- bsp/stm32/stm32mp157a-st-ev1/board/ports/OpenAMP/libmetal/lib/include/metal/system/generic/alloc.h
- bsp/stm32/stm32mp157a-st-ev1/board/ports/OpenAMP/libmetal/lib/system/generic/alloc.h
[
修改 openamp malloc 函数，减少对 libc 的依赖。
]
> [update] stm32mp1 opemamp malloc -> rt_malloc.

- bsp/rx/applications/startup.c
- bsp/rx/drivers/board.c
- bsp/rx/drivers/board.h
- bsp/rx/drivers/uart.c
- bsp/rx/rtconfig.h
> [rx] auto formatted

- bsp/amebaz/applications/main.c
- bsp/amebaz/applications/smartconfig_app.c
- bsp/amebaz/drivers/board.c
- bsp/amebaz/drivers/board.h
- bsp/amebaz/drivers/drv_uart.c
- bsp/amebaz/drivers/drv_uart.h
- bsp/amebaz/drivers/wlan/drv_wifi.c
- bsp/amebaz/drivers/wlan/drv_wifi.h
- bsp/amebaz/drivers/wlan/drv_wlan.c
- bsp/amebaz/drivers/wlan/drv_wlan.h
> [amebaz] auto & manual formatted

- bsp/stm32/libraries/STM32WBxx_HAL/SConscript
- bsp/stm32/stm32wb55-st-nucleo/board/board.c
1. 增加hsem.c文件，支持CPU1和CPU2通讯
2. 修改board.c文件时钟配置，启动RTC时钟
> [BSP][STM32WB55] change some file to support ble stack.

- .github/workflows/file_check.yml
- tools/file_check.py
[
添加 CI ：检查 PR 中 .c/.h 文件的格式与 license.
]
> [add] .c/.h file format check and license check.

- bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
> [ab32] rt_rtc_control->ab32_rtc_control

- bsp/stm32/stm32mp157a-st-discovery/board/ports/drv_sdio.c
[
修改 sdio 配置，在 production mode 下正常使用 wifi .
]
> [update] stm32mp1 wifi sdio.

- components/drivers/include/drivers/sensor.h
[
- 取消 spo2 传感器的百分制单位。
- 使用已有的千分制单位作为 spo2 的标准单位。
]
> [fix] fix measurement unit of "percentage" to "permillage" for accuracy.

- libcpu/arm/cortex-a/cp15.h
- libcpu/arm/cortex-a/gic.c
- libcpu/arm/cortex-a/gic.h
- libcpu/arm/cortex-a/gtimer.c
- libcpu/arm/cortex-a/gtimer.h
- libcpu/arm/cortex-a/interrupt.c
- libcpu/arm/cortex-a/interrupt.h
> [Cortex-A]add gic&gtimer interface

- tools/file_check.py
[
提高ci检查正确率。之前检查编码格式时，会有几率出错。
]
> [update] file_check.py, Improve compatibility.

- tools/auto-ci.py
- tools/buildbot.py
- tools/building.py
- tools/clang-analyze.py
- tools/eclipse.py
- tools/keil.py
- tools/mkromfs.py
- tools/ses.py
- tools/ua.py
- tools/vs.py
- tools/vs2012.py
- tools/win32spawn.py
[
tools 下面的 py 脚本，在 python3 环境上运行的不好。
修复明显的兼容性问题。
]
> [tools] Python 3 compatibility support

- bsp/stm32/stm32l476-st-nucleo/project.uvprojx
[
更新project.uvprojx，修复工程文件中还包含了components中已经删除了的文件，造成编译错误
]
> [BSP][STM32]fixed project.uvprojx in stm32l476-st-nucleo

- components/net/lwip-2.0.2/src/apps/tftp/tftp_port.c
- components/net/lwip-2.1.2/src/apps/tftp/tftp_port.c
[
[lts-3.1.x][components]update GPL license to Apache-2.0
]
> [lts-3.1.x][components]update GPL license to Apache-2.0

- tools/file_check.py
[
修复格式检查文件夹无法忽略的 bug，已在本地仓库测试完成。
]
> [update] ignore dir path check.

- bsp/bluetrum/ab32vg1-ab-prougen/applications/main.c
> [ab32vg1] optimize main function

- bsp/simulator/drivers/drv_rtc.c
> [bsp/simulator] Add windows rtc driver.

- bsp/simulator/drivers/drv_rtc.c
- components/libc/compilers/common/time.c
- include/rtdef.h
> Add feature of millisecond time

- src/irq.c
> [kernel][irq] 优化DEBUG打印输出位置，防止造成歧义

- components/utilities/ymodem/ry_sy.c
[
sy命令是需要指定带传输文件的路径的，但是如果用户直接敲sy命令，后面没有跟任何文件名，目前程序不会报错，导致后面会出问题。加一个参数判断，如果文件路径参数不合法 直接拦截。
]
> [ymodem] Check the file path's legitimacy of 'sy' command

- tools/cmake.py
[
修改 cmake.py， 添加以下功能：
- C++ 支持
- 修改  cmake.py `PROJECT` 的位置
- 添加 lib 库  
]
> [update] cmake.py, add c++ support and libpath.

- tools/cmake.py
> [update] cmake.py, delete extra code.

- bsp/stm32/libraries/HAL_Drivers/drv_wdt.c
[
有人在论坛上提出的bug: https://blog.csdn.net/wusheng1989/article/details/111995869
手头没有L0板子，麻烦帮忙测试一下
]
> [bug][stm32][wdg] 修复没有考虑到L0芯片的问题

- bsp/qemu-vexpress-a9/drivers/drv_smc911x.c
- bsp/qemu-vexpress-a9/drivers/drv_smc911x.h
> [bsp][qemu]更换 smc911 驱动头文件

- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
- bsp/stm32/stm32l475-atk-pandora/board/SConscript
- bsp/stm32/stm32l475-atk-pandora/board/ports/drv_key.c
- bsp/stm32/stm32l475-atk-pandora/board/ports/drv_sdcard.c
- components/drivers/misc/pin.c
> [stm32 pandora] implement drv_key and modify drv_sdcard

- components/libc/compilers/common/sys/time.h
- components/utilities/ulog/ulog.c
> [ulog] Fix thread info show when kernel not startup.

- components/libc/libdl/arch/riscv.c
- components/libc/libdl/dlelf.c
- components/libc/libdl/dlelf.h
- components/libc/libdl/dlmodule.c
[ADD]riscv.c  dlmodule can support riscv architecture
[CHG]dlelf.c  support distinguishing  32-bit ELF format and 64-bit ELF format
[
dlmodule可以支持risc-v 架构的芯片，本地已经验证，用户态在文件系统可以直接执行.mo 文件以及调用.so 的函数库，且.mo文件也可以调用.so的函数。该实验是在K210的板子进行实验。另外需要修改编译配置文件以及链接文件。
]
> dlmodule can support riscv architecture

- bsp/bluetrum/libraries/hal_drivers/drv_usart.c
[
uart1、uart2中断接收还存在问题，默认不开启
AB32VG1 RISC-V开发板 测试成功
]
> fix bluetrum uart1 and uart2 cannot recv data

- components/drivers/touch/touch.c
[
1. Extend original class implementation to catch more controlling commands.
2. This modification is for H/W ADC touching platform.
]
> [components/drivers/touch] Bypass controlling commands in touch class to device driver.

- bsp/Copyright_Notice.md
> [bsp]add copyright notice

- tools/file_check.py
[
更新 file_check.py，修改文件格式检查逻辑错误。
]
> [update] file_check.py

- src/kservice.c
[
- fix rt_kprintf %s percision print error.
]
> fixed rt_kprintf %s precision print error.

- include/rtdef.h
- src/Kconfig
> Update the version number to 4.0.4

- components/libc/pthreads/posix_types.h
- components/net/lwip-2.1.2/src/arch/include/arch/cc.h
> [bug][libc]修复因libc移除sys/errno.h文件导致的报错

- bsp/stm32/stm32f407-atk-explorer/board/Kconfig
[
补充配置之后，用户可以一键配置network，不需要再进入到component里去设置其他的选项了，比如自动选定硬件校验和。
F407探索者测试通过
]
> [bsp-stm32f407-explorer] 完善F407探索者网络部分board配置

- bsp/stm32/stm32f407-atk-explorer/board/ports/drv_sdcard.c
[
在潘多拉也有相同的问题，已经合并：https://github.com/RT-Thread/rt-thread/pull/4389
已经在探索者上测试通过
]
> [bsp][stm32f407-explorer] fix a bug that cannot use fatfs in the main thread at starting up

- bsp/nuvoton/numaker-m2354/README.md
- bsp/nuvoton/numaker-m2354/rtconfig.py
- libcpu/arm/cortex-m23/SConscript
[
Append CM23 rvds.S including for armclang platform.
]
> [libcpu][arm][cortex-m23]Correct rvds.S including for armclang platform.

- bsp/stm32/stm32f407-atk-explorer/applications/SConscript
- bsp/stm32/stm32f407-atk-explorer/board/SConscript
[
1.[bug][bsp][stm32f407-explorer] 修复sdcard驱动没有加入工程的问题
2.[sconscript] application文件夹增加工程文件路径向下扫描功能. 用户在加入自己的工程文件夹时，只要该文件内含有Sconscript，就可以被自动探测到，无需手动修改application下的sconscript手动添加。
]
> [bsp][stm32f407-explorer] 修复drv_sdcard.c没有被包含到工程的bug

- components/libc/Kconfig
> [POSIX] beautify libc Kconfig

- components/libc/compilers/common/SConscript
- components/libc/compilers/common/none-gcc/SConscript
[
https://github.com/RT-Thread/rt-thread/issues/4688
]
> [libc][bug] 修复在simulator win32平台下，none-gcc文件夹路径没有添加到工程的bug

- bsp/simulator/drivers/sdl_fb.c
- bsp/simulator/drivers/sst25vfxx_mtd_sim.c
> [bsp][simulator]format codes to prevent being given a CI error

- bsp/simulator/drivers/sd_sim.c
[
涉及issue：https://gitee.com/rtthread/rt-thread/issues/I3I2TD
]
> [bug][bsp][simulator] 修复sd_sim.c编译报错的问题，使用rt_dgb代替老旧的debug输出方式

- tools/building.py
- tools/menuconfig.py
[
完善了 testcase 相关脚本处理逻辑，如果路径文件存在则正常运行；如果不存在，则从正常的工作流程中排除。
已在本地测试完成。
]
> 【修复】studio 生成工程报错的问题。

- tools/file_check.py
[
【完善】file_check.py 中检查变更文件的逻辑。
解决 https://github.com/RT-Thread/rt-thread/pull/4695 中的问题。
]
> 【完善】file_check.py 中检查变更文件的逻辑

- components/finsh/cmd.c
> 移除cmd.c首行空白行

- components/utilities/ulog/ulog.c
- components/utilities/ulog/ulog.h
> [ulog] Add output locker enabled API

- components/dfs/Kconfig
- components/dfs/filesystems/devfs/devfs.c
> [dfs] 将文件系统默认最大数量以及最大类型改为4

- src/slab.c
> 注释错误，此处的场景是zone满了，不是空了

- src/idle.c
_has_defunct_thread函数增加条件编译，防止没有开启heap时报警
[
] …
> [kernel][idle] _has_defunct_thread函数增加条件编译

- src/timer.c
> [src]移除 C99 依赖

- src/timer.c
> [lts-3.1.x][src]移除 c99 依赖

- bsp/qemu-riscv-virt64/README_ZH.md
> [bsp][qemu-riscv-virt64]add English README.md

- tools/building.py
+ 执行scons --dist-ide 命令时，如果没有指定 project-name ，使用默认工程名：dist_ide_project
+ 执行scons --dist-ide 命令时，如果没有指定 project-path   ，使用默认工程路径：./dist_ide_project
> dev:[tools] add default project name and project path while --dist-ide

- bsp/stm32/libraries/HAL_Drivers/drv_usbd.c
- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
[
在潘多拉开发板上添加 usb 音频的配置项。开启即可作为 usb扬声器、麦克风使用。
已在pandora上测试完成。
]
> 在潘多拉开发板上添加 usb 扬声器、麦克风选项

- ChangeLog.md
> [lts-3.1.x]update ChangeLog.md

- src/ipc.c
- src/thread.c
[
- 提高内核稳定性：线程脱离临界区没有做保护，发生线程切换，会变成孤立任务
- 添加断言：IPC 挂起任务，default 直接 break 了，若发生踩内存，将导致任务被挂起，无法恢复
]
> [kernel] Improve kernel stability

- include/rtthread.h
- src/ipc.c
[
增加rt_mutex_trytake
使用RT_WAITING_NO代替数字0，提高代码可读性
]
> [kernel] 增加rt_mutex_trytake

- src/scheduler.c
> [kernel][注释] 明确rt_schedule的调度时刻

- src/thread.c
> [kernel][thread.c] 规范内部函数命名方式

- src/clock.c
[
- 修复tick中断里对任务状态修改未加保护而引起的中断抢占安全性问题。此问题将在合适的时机下导致任务沦为僵尸态任务。
]
> fix rt_tick_increase critical code protection

- src/clock.c
- src/idle.c
在rt_thread_idle_entry函数中，调用回调函数时先判断回调函数是否为空（if (idle_hook_list[i] != RT_NULL)），然后执行这个回调函数。但是如果非常的赶巧，在判断之后，用户在其他线程中把回调撤销掉了（即改成了NULL），此时，如果继续执行这个回调函数会引发灾难性后果，因为直接访问了一个非法的地址NULL。
虽然这个问题，非常非常的凑巧，800年遇不到一会，但是一旦遇到就是直接死机。
在STM32F407探索者测试通过
https://github.com/RT-Thread/rt-thread/issues/4753
https://github.com/RT-Thread/rt-thread/pull/4754
> [bug][kernel] 保持空闲任务钩子函数调用的原子性

- src/clock.c
[
rt_tick变量，即在中断中使用，又在线程中使用，属于中断-线程共享变量。需要增加volatile修饰。
]
> [kernel] 对rt_tick变量增加volatile修饰，防止编译器优化时出现问题

- src/clock.c
- src/components.c
- src/cpu.c
- src/device.c
- src/idle.c
> [kernel]补充endif后缀注释

- components/finsh/msh_file.c
[
增加tail命令，与cat命令相互补充，有时文件过长用cat命令不合适
命令格式与Linux相同
tail test.c 显示test.c后10行内容
tail -n 20 test.c 显示test.c后20行内容
tail -n +20 test.c 显示从正数第20行开始显示test.c内容
]
> [msh] implement tail command

- tools/mkdist.py
[
[tools] update eclipse project after dist.
]
> [tools] update eclipse project after dist.

- tools/makefile.py
- tools/rtthread.mk
[
1. 修复 ab32vg1 不能直接在 linux 命令行下编译的问题 #4748 
在 AB32VG1 平台的 BSP 目录编译通过
]
> [tools] Optimization the EXTERN_LIB variable use

- src/kservice.c
- src/memheap.c
[
rt_malloc_align,rt_free_align可能存在于其他的内存算法中，由用户进行选择。
]
> [src] add RT_WEAK for rt_malloc_align,rt_free_align

- examples/file/listdir.c
[
重新解决冲突，以及源码格式问题。
源自：https://gitee.com/rtthread/rt-thread/pulls/48/files
合并后，请关闭gitee的pr
]
> [example] 解决潜在内存问题

- bsp/k210/driver/board.c
…e ,rt_hw_us_delay this function will be called in unistd.c file
[
add void rt_hw_us_delay(rt_uint32_t usec) funciton in board.c ，the function will delay for some us ,the function can be called in usleep in unistd.c when using POSIX interface
It has been verified in KD233 development board.
]
> update board.c in k210 bsp

- bsp/zynqmp-r5-axu4ev/drivers/Zynq_HAL_Driver/sleep.h
- bsp/zynqmp-r5-axu4ev/drivers/Zynq_HAL_Driver/xil_assert.h
- bsp/zynqmp-r5-axu4ev/drivers/Zynq_HAL_Driver/xil_cache.h
- bsp/zynqmp-r5-axu4ev/drivers/Zynq_HAL_Driver/xil_printf.h
- bsp/zynqmp-r5-axu4ev/drivers/Zynq_HAL_Driver/xil_types.h
- bsp/zynqmp-r5-axu4ev/drivers/Zynq_HAL_Driver/xplatform_info.h
- bsp/zynqmp-r5-axu4ev/drivers/drv_eth.c
- bsp/zynqmp-r5-axu4ev/drivers/zynqmp-r5.h
[
修复使用xil_cache.h可能找不到函数定义的问题。
在AXU4EV开发板上进行测试。
]
> [bsp][zynqmp-r5-axu4ev]修复使用xil_cache.h可能找不到函数定义的问题

- src/ipc.c
- src/irq.c
- src/kservice.c
- src/mem.c
- src/memheap.c
- src/mempool.c
- src/object.c
- src/scheduler.c
- src/signal.c
- src/slab.c
- src/thread.c
- src/timer.c
> [kernel] 补充endif后缀注释

- components/libc/compilers/common/unistd.c
> [update] usleep supports calling in interrupts.

- bsp/imxrt/imxrt1064-nxp-evk/board/Kconfig
- bsp/imxrt/imxrt1064-nxp-evk/board/board.c
- bsp/imxrt/libraries/drivers/drv_i2c.c
[
1. 完善了i2c, uart, LCD的kconfig文件
2. 修复了I2C的imxrt_i2c_mst_xfer函数读取数据前会多进行一次写地址的操作
在imxrt1064-nxp-evk的开发板上已经测试
]
> [BSP][IMXRT]modify kconfig for i2c, uart, LCD, and fixed i2c read bug in drv_i2c.c

- tools/cmake.py
[
修改 cmake.py，支持 windows 操作系统。已测试。
]
> [update] support windows cmake tool.

- .github/workflows/action_utest.yml
- examples/utest/configs/kernel/config_riscv64.h
[
[ci] add riscv64 autotest.
]
> [ci] add riscv64 autotest.

- bsp/nrf5x/nrf52832/board/Kconfig
> [bsp/nrf5x] modify nrf52832 default memory config

- include/rtthread.h
[
https://club.rt-thread.org/ask/question/431614.html
rt_sscanf一直没有实现，放在,h会造成用户误解。
]
> [rtthread.h] 移除rt_sscanf声明

- bsp/stm32/libraries/HAL_Drivers/drv_eth.c
- components/net/lwip-1.4.1/src/arch/include/arch/cc.h
- components/net/lwip-2.0.2/src/arch/include/arch/cc.h
- components/net/lwip-2.1.2/src/arch/include/arch/cc.h
[
lwip提供的临界区保护接口**必须要用关中断保护**，因为lwip内部的memp.c也就是lwip的内存池会在网卡接收中断中接收数据。这是一个中断-线程的临界区，因此要用关中断保护。
STM32F407探路者测试通过
]
- [xx] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
> [bug][lwip] 修复lwip临界区保护的bug

- bsp/qemu-vexpress-a9/drivers/board.c
- bsp/qemu-vexpress-a9/drivers/drv_smc911x.c
- components/libc/compilers/common/SConscript
- components/libc/compilers/common/delay.c
- components/libc/compilers/common/delay.h
[
https://github.com/RT-Thread/rt-thread/pull/4666
]
> implement delay.c/.h

- bsp/stm32/libraries/HAL_Drivers/drv_lcd.c
> [bsp][stm32] fix LTDC_IRQHandler irq enter bug.

- components/libc/compilers/newlib/syscalls.c
> [libc][syscall]整理函数格式

- tools/cmake.py
> [cmake] fix path issue.

- bsp/stm32/stm32f412-st-nucleo/rtconfig.py
- bsp/stm32/stm32h750-artpi-h750/rtconfig.py
- bsp/stm32/stm32l475-atk-pandora/rtconfig.py
- libcpu/arm/cortex-m7/SConscript
- tools/building.py
- tools/cmake.py
[
添加支持 armclang 的 cmake 工程。
已在 f412-nucleo、art-pi 开发板上做了验证。
]
> add scons --target=cmake-armclang

- components/net/at/include/at.h
> [components][net][at] indent using 4 spaces

- libcpu/arm/cortex-a/start_gcc.S
[
`stack_start` `stack_top` 作为全局变量，分配在 `bss` 段, 给他初始化值为 0。
在 qemu-a9 上测试通过。  
]
> Adjust the stack_top to bss

- components/finsh/cmd.c
list-thread命令针对多核添加bind core显示
> list-thread命令针对多核添加bind core显示

- include/rtthread.h
- libcpu/arm/cortex-a/cache.c
- src/Kconfig
- src/idle.c
- src/scheduler.c
- src/thread.c
添加dcache invalidate/dcache clean&invalidate接口
> 添加dcache invalidate/dcache clean&invalidate接口

- tools/building.py
This request fixes a typo and nothing more.
> Fix a minor typo

- include/rtdef.h
- include/rtthread.h
- libcpu/arm/cortex-a/interrupt.c
- libcpu/arm/cortex-a/start_gcc.S
- libcpu/arm/cortex-a/trap.c
- src/irq.c
- src/scheduler.c
- src/thread.c
修改irq handle接口rt_hw_trap_irq，支持核间IPI中断处理
> 修改irq handle接口rt_hw_trap_irq，支持核间IPI中断处理

- bsp/stm32/stm32f103-blue-pill/README.md
> [bsp][stm32 bluepill] 更新readme

- src/ipc.c
[
优化ipc文件的相关函数名注释说明。
本次提交不改动任何代码，仅仅优化注释说明。
]
> [comment] Optimize the comment for ipc

- components/dfs/src/dfs_file.c
[
[devfs] F_GETFL/F_SETFL 应交由底层驱动处理
]
> [devfs] F_GETFL/F_SETFL should be handled by the drivers.

- components/drivers/serial/serial_v2.c
[
串口V2版本支持device ops的功能。已经在STM32L475-Pandora平台测试通过
]
> [serial_v2] Serial_v2 support device ops feature

- components/drivers/sdio/mmc.c
[
修改mmc初始化错误，将card-》csd写成card-》cid,内核代码在art-pi smart上测试通过
]
> 修改mmc初始化，将card-》resp_csd写成card->resp_cid

- components/drivers/sdio/mmc.c
[
修改mmc初始化错误，将card-》csd写成card-》cid,内核代码在art-pi smart上测试通过
]
> 修改mmc初始化错误，将card-》csd写成card-》cid

- components/libc/pthreads/semaphore.c
[
修复 #4784 bug错误，该bug为检查变量错误，已修复为对正确的变量进行检查.
在STM32F4进行了测试.
Fixed #4784
]
- [*] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [*] 没有垃圾代码，代码尽量精简，不包含`#if …
> Fix the sem init check bug in pthread. 

- examples/kernel/event_simple.c
- examples/kernel/mbox_send_wait.c
- examples/kernel/mbox_simple.c
- examples/kernel/messageq_simple.c
- examples/kernel/mutex_priority.c
- examples/kernel/mutex_simple.c
- examples/kernel/semaphore_buffer_worker.c
- examples/kernel/semaphore_dynamic.c
- examples/kernel/semaphore_producer_consumer.c
- examples/kernel/semaphore_static.c
- examples/kernel/tc_comm.c
- examples/kernel/timer_timeout.c
- examples/pm/wakeup_app.c
[
全部为例程代码，对RTT实际代码没有影响。防止例程中大量使用FIFO flag对用户造成误导。
形成今天这种局面，例程与手册的错误引导功不可没，需要改掉、
]
> [example] replace RT_IPC_FLAG_FIFO with RT_IPC_FLAG_PRIO

- components/net/sal_socket/include/socket/netdb.h
> [SAL] 修复一处笔误

- bsp/stm32/stm32f407-atk-explorer/board/Kconfig
[
related issue: #4893
文件系统选定由menuconfig菜单结构 改为 menu菜单结构
]
> [stm32-stm32f407-atk-explorer] 优化文件系统选项Kconfig

- bsp/stm32/libraries/HAL_Drivers/drv_eth.c
- bsp/stm32/libraries/HAL_Drivers/drv_eth.h
- components/net/lwip-1.4.1/src/lwipopts.h
- components/net/lwip-1.4.1/src/netif/ethernetif.c
- components/net/lwip-2.0.2/src/lwipopts.h
- components/net/lwip-2.0.2/src/netif/ethernetif.c
- components/net/lwip-2.0.3/src/lwipopts.h
- components/net/lwip-2.0.3/src/netif/ethernetif.c
- components/net/lwip-2.1.2/src/lwipopts.h
- components/net/lwip-2.1.2/src/netif/ethernetif.c
- src/Kconfig
- src/kservice.c
[
MEMCPY 和 SMEMCPY是LWIP官方定义的内存拷贝宏，用户可以在lwipopts.h中重新实现
在lwipopts.h中增加如下代码：
```c
#ifdef RT_USING_ASM_MEMCPY
#define MEMCPY(dst,src,len)             rt_memcpy(dst,src,len)
#else
#define MEMCPY(dst,src,len)             memcpy(dst,src,len)
#endif /* RT_USING_ASM_MEMCPY */
#define SMEMCPY(dst,src,len)            MEMCPY(dst,src,len)
```
判断是否开启汇编加速功能，如果没有开启则沿用memcpy，如果开启，则使用汇编版本的rt_memcpy
在开启汇编加速后，可以保证整个LWIP内核以及网卡驱动全部加速。
]
我在这个拉取/合并请求中已经考虑了 As …
> [stm32][eth] beautify codes

- src/cpu.c
- src/object.c
- src/signal.c
- src/thread.c
[
内核最后一批
related : https://github.com/RT-Thread/rt-thread/pull/4760
]
> [kernel] Standardize internal functions' name

- bsp/stm32/stm32f407-atk-explorer/board/Kconfig
- bsp/stm32/stm32f407-atk-explorer/board/SConscript
- bsp/stm32/stm32f407-atk-explorer/board/ports/drv_filesystem.c
- bsp/stm32/stm32f407-atk-explorer/board/ports/fal_cfg.h
- bsp/stm32/stm32f407-atk-explorer/board/ports/fal_spi_flash_sfud_port.c
- bsp/stm32/stm32f407-atk-explorer/board/ports/spi_flash_init.c
> [stm32f407-explorer] 优化FAL相关设置

- bsp/mm32f327x/drivers/Kconfig
- bsp/mm32f327x/drivers/SConscript
- bsp/mm32f327x/drivers/drv_flash.c
- bsp/mm32f327x/drivers/drv_flash.h
- bsp/mm32f327x/drivers/fal_cfg.h
[
为mm32f327x BSP添加片上Flash驱动。
]
> add on-chip flash driver for mm32f327x

- components/libc/compilers/newlib/syscalls.c
> [newlib] fix compile error when closing RT_USING_CONSOLE

- include/rtdef.h
> Add device type USBOTG to redef.h

- bsp/nrf5x/libraries/drivers/drv_wdt.c
refer to issue: https://github.com/RT-Thread/rt-thread/issues/4558
[
当前存在的问题，  参考issue： #https://github.com/RT-Thread/rt-thread/issues/4558
根据官方提供的 [wdt sample](https://github.com/RT-Thread-packages/peripheral-sample/blob/master/iwdg_sample.c),
修改drv_wdt.c驱动
]
> [bsp/nrf52x] optimize drv_wdt.c

- components/finsh/cmd.c
[
#4941 只增加了枚举类型，没有增加字符串描述，导致编译警告。
]
> [kernel][device] fix the compiled warning of PR #4941

- components/drivers/src/ringbuffer.c
[
代替 @heyuanjie87 提交此pr
https://gitee.com/heyuanjie87/rt-thread.lab/blob/master/components/drivers/src/ringbuffer.c
]
> [ringbuffer] rt_ringbuffer_data_len采用局部变量承接，防止出现资源竞争

- components/utilities/utest/utest.c
[
utest add fail_list 用于收集错误，资源占用也不大，一个测试用例占用1个bit，120个测试用例也才占用15个字节。
已在 qemu 和 art-pi 上进行了测试。如图，测试完成后会自动收集并打印测试结果。
]
> [add] utest add fail_list 用于收集错误

- src/timer.c
> [kernel][timer] standardize internal functions' name

- components/drivers/serial/serial.c
[
增加ioctl函数获取终端如putty窗口大小功能。
开启RT_USING_POSIX_TERMIOS 即可使用（需要开libc 开dfs 然后再libc下选定使用termios）
测试例程：
```c
#include <sys/ioctl.h>
#include <unistd.h>
static void test(int argc, char* argv[])
{
struct winsize window;
ioctl(STDOUT_FILENO, TIOCGWINSZ, &window);
rt_kprintf("ws_col:%d,ws_row:%d\n",window.ws_col,window.ws_row);
}
MSH_CMD_EXPORT(test, test)
```
演示视频：
https://user-images.githubusercontent.com/34888354/130356580-cad4387d-641f-454d-bcd9-8acb5d76bacd.mp4
]
必须选择一项 …
> [ioctl] implement function of getting window's size(TIOCGWINSZ)

- bsp/stm32/stm32f407-atk-explorer/board/ports/drv_filesystem.c
[
这个线程在此bsp并没有实际意义，实际测试证明在初始化之后，即便插上sd卡，也无法通过sdcard线程完成对sd卡的初始化，因为底层就已经初始化失败，sdcard线程初始化sd卡是没有意义的。
后续考虑采用工作队列的方式，而不是通过sdcard线程的方式。
]
> [stm32-f407-explorer] remove sdcard thread

- examples/utest/testcases/kernel/Kconfig
- examples/utest/testcases/kernel/SConscript
- examples/utest/testcases/kernel/timer_tc.c
[
```c
msh >utest_run
[I/utest] [==========] [ utest    ] loop 1/1
[I/utest] [==========] [ utest    ] started
[I/utest] [----------] [ testcase ] (testcases.kernel.timer_tc) started
[D/utest] [    OK    ] [ unit     ] (test_static_timer_init:167) is passed
[D/utest] [    OK    ] [ unit     ] (test_static_timer_init:167) is passed
[D/utest] [    OK    ] [ unit     ] (test_static_timer_init:167) is passed
[D/utest] [    OK    ] [ unit     ] (test_static_timer_init:167) is passed
[D/utest] [    OK    ] [ unit     ] (test_static_timer_control:258) is passed
[D/utest] [    OK    ] [ unit     ] (test_dynamic_timer_create:393) is passed
[D/utest] [    OK    ] [ unit     ] (test_dynamic_timer_create:393) is passed
[D/utest] [    OK    ] [ unit     ] (test_dynamic_timer_create:393) is passed …
```
> [add] [testcase] add timer testcase src code and Kconfig 

- .github/workflows/action_utest.yml
- components/utilities/utest/utest.c
- examples/utest/configs/kernel/irq.conf
- examples/utest/configs/kernel/timer.conf
- examples/utest/testcases/kernel/timer_tc.c
> 添加更多的测试用例到 Autotest CI

- bsp/k210/README.md
- bsp/k210/link.lds
- bsp/k210/rtconfig.py
[
K210的BSP需要结合嘉楠官方的SDK使用，最新的SDK使用了C++17，因此需要修改BSP中的链接脚本，将C++对象的构造函数链接到固定段，以及rtconfig.py中加入 -std=gnu++17 -Wno-multichar 的编译参数以支持C++17特性，当前已通过scons构建并生成对应的ELF文件
]
> update bsp k210

- bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f7.c
> 修改扇区计算错误的bug

- bsp/stm32/libraries/STM32WBxx_HAL/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb30xx_cm4.s
- bsp/stm32/libraries/STM32WBxx_HAL/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb35xx_cm4.s
- bsp/stm32/libraries/STM32WBxx_HAL/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb50xx_cm4.s
- bsp/stm32/libraries/STM32WBxx_HAL/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb55xx_cm4.s
- bsp/stm32/libraries/STM32WBxx_HAL/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/startup_stm32wb5mxx_cm4.s
[
fix:Support for GCC compile startup
]
> fix:Support for GCC compile startup

- src/irq.c
- src/timer.c
> [src/timer_irq] add the fixed comment

- bsp/ft2004/drivers/ft2004_cpu.S
> 修正ft2004 env 编译出错问题

- bsp/stm32/stm32f407-atk-explorer/board/Kconfig
[
移除PKG_USING_RT_MEMCPY_CM软件包的默认选择：这个会在发版本之前刷bsp工程打来麻烦，留给用户自行选择，不再自动选择。
移除文件系统RT_USING_SYSTEM_WORKQUEUE：这个功能没有用到，予以移除
]
> [bsp][stm32][f407-explorer] 优化board kconfig配置

- bsp/allwinner_tina/libcpu/trap.c
- bsp/bluetrum/ab32vg1-ab-prougen/board/board.c
- bsp/dm365/platform/trap.c
- bsp/imx6sx/cortex-a9/cpu/trap.c
- bsp/qemu-vexpress-gemini/cpu/trap.c
- bsp/raspberry-pi/raspi2/cpu/trap.c
- bsp/raspberry-pi/raspi3-32/cpu/trap.c
- components/finsh/Kconfig
- components/finsh/SConscript
- components/finsh/msh.c
- libcpu/aarch64/cortex-a53/trap.c
- libcpu/aarch64/cortex-a72/trap.c
- libcpu/arm/am335x/trap.c
- libcpu/arm/arm926/trap.c
- libcpu/arm/cortex-a/trap.c
- libcpu/arm/cortex-m0/cpuport.c
- libcpu/arm/cortex-m23/cpuport.c
- libcpu/arm/cortex-m3/cpuport.c
- libcpu/arm/cortex-m33/cpuport.c
- libcpu/arm/cortex-m4/cpuport.c
- libcpu/arm/cortex-m7/cpuport.c
- libcpu/arm/cortex-r4/trap.c
- libcpu/arm/realview-a8-vmm/trap.c
- libcpu/arm/s3c24x0/trap.c
- libcpu/arm/zynqmp-r5/trap.c
- libcpu/risc-v/k210/interrupt.c
- libcpu/risc-v/virt64/interrupt.c
- libcpu/rx/cpuport.c
- src/memheap.c
[
finsh组件可以选择是否包含cmd.c文件，内置命令例如list_thread等。
因为cmd.c的命令非常的占用ROM，大约在5-6kb左右。
用户在优化时可以选择将其关闭以节省ROM
该选项默认y，即和之前一样，包含cmd.c
]
> [finsh] finsh组件可以选择是否包含内置命令

- .github/PULL_REQUEST_TEMPLATE.md
[
根据 2021/08/28 会议的建议
在PR模版增加提示用户使用源码格式化工具，防止用户提交代码后CI因格式问题报错
]
> PR template 增加格式化代码工具使用提示

- bsp/nrf5x/nrf52840/board/Kconfig
[fix the ble_nano_33 uart config]
> [bsp/nrf52840]fix the board uart config

- .ignore_format.yml
- bsp/hk32/.ignore_format.yml
[
在bsp目录下增减忽略检查库文件，相对的将根目录下忽略检查库文件中的路径删除
]
> 【修改】bsp目录下增加忽略检查库文件

- src/signal.c
[
[add] a comment for the signal
]
> [add] a comment for the signal

- bsp/at91sam9260/platform/interrupt.c
- bsp/at91sam9260/platform/reset.c
- bsp/at91sam9g45/platform/interrupt.c
- bsp/at91sam9g45/platform/reset.c
- bsp/beaglebone/applications/board.c
- bsp/dm365/drivers/davinci_emac.c
- bsp/dm365/platform/interrupt.c
- bsp/dm365/platform/reset.c
- bsp/fm33lc026/libraries/HAL_Drivers/drv_common.c
- bsp/hk32/hk32f030c8-mini/board/board.c
- bsp/mb9bf506r/drivers/nand.c
- bsp/nuvoton/libraries/n9h30/rtt_port/drv_sys.c
- bsp/nuvoton/libraries/nuc980/rtt_port/drv_sys.c
- bsp/nv32f100x/board/src/board.c
- bsp/qemu-vexpress-a9/drivers/audio/drv_ac97.c
- bsp/qemu-vexpress-a9/drivers/audio/drv_pl041.c
- bsp/simulator/drivers/board.c
- bsp/w60x/drivers/drv_standby.c
- components/drivers/can/can.c
- components/drivers/rtc/alarm.c
- components/drivers/wlan/wlan_cmd.c
- components/net/lwip-1.4.1/src/apps/ping/ping.c
- components/net/lwip-2.0.2/src/apps/ping/ping.c
- components/net/lwip-2.0.3/src/apps/ping/ping.c
- components/net/lwip-2.1.2/src/apps/ping/ping.c
- components/net/netdev/src/netdev.c
- components/vbus/vbus.c
- examples/file/readspeed.c
- examples/file/readwrite.c
- examples/file/writespeed.c
> [finsh] 修复由于移除finsh导致__cmd_xxx命令无法使用的问题

- components/finsh/Kconfig
[
在移除finsh的cstyle功能时，FINSH_USING_MSH定义也被移除，导致部分采用FINSH_USING_MSH定义来判断FInsh是否开启的软件包命令无法导出：
因此，恢复FINSH_USING_MSH，到v4.1将finsh转为msh的时候，再一起移除掉。届时，所有软件包跟着做一次版本大升级。
]
> [finsh] 恢复FINSH_USING_MSH定义以保持兼容性

- .gitignore
[
将dist_ide_project目录纳入到git忽略索引中。
否则，dist出来的工程也会被git探测到，呼啦啦一堆文件冒出来，提pr的时候很不方便。
相关pr: https://github.com/RT-Thread/rt-thread/pull/4241
]
> [.gitignore] 增加dist_ide_project目录（studio dist出来的独立工程目录）

- components/finsh/finsh.h
> [msh] add comments

- bsp/stm32/libraries/HAL_Drivers/drv_usart.c
- components/drivers/include/drivers/serial.h
[
在 Serial 驱动设备里添加了硬件控制流 CTS/RTS 的功能，并且修改了 STM32 上硬件控制流的配置流程，这样在需要串口 CTS/RTS 的功能时也能够使用，默认为未开启。
已经成功在 ART-Pi 上测试。
]
> serial: add CTS/RTS flowcontrol.

- components/drivers/serial/serial.c
[
经查证，TIOCSWINSZ 和 TIOCGWINSZ不属于TERMIOS的范畴。当时归类错误，使用上述两个命令并不依赖RT_USING_POSIX_TERMIOS。
]
> [serial] 优化RT_USING_POSIX_TERMIOS预编译

- components/libc/compilers/armlibc/libc.c
- components/libc/compilers/armlibc/mem_std.c
- components/libc/compilers/dlib/libc.c
[
related pr: https://github.com/RT-Thread/rt-thread/pull/5044
]
> [remove rtlibc] 修复keil编译不过的问题

- components/net/at/include/at.h
- components/net/at/src/at_cli.c
- components/net/sal_socket/include/sal_netdb.h
- components/net/sal_socket/include/sal_socket.h
- components/net/sal_socket/include/socket/netdb.h
> [remove rtlibc]修复缺失的头文件导致的报错

- components/dfs/include/dfs.h
- components/dfs/include/dfs_posix.h
- components/dfs/src/dfs_posix.c
- components/libc/compilers/common/none-gcc/sys/types.h
- components/libc/compilers/common/none-gcc/sys/unistd.h
- components/libc/compilers/common/sys/statfs.h
- components/libc/compilers/common/sys/vfs.h
[
在dfs_posix.h中声明的函数实际上是unix标准头文件的好几个头文件的大杂烩，在早期libc不健全的时候采用这种方式很正确。目前libc已经完善，为了标准化头文件，让linux的程序可以无缝移植到rtt，因此将dfs_posix.h的函数转移到对应的标准头文件中。dfs_posix.h将继续保留，以保持兼容，下个版本将予以移除，后续编程不建议再包含dfs_posix.h，使用unistd.h fcntl.h等标准头文件替代。
GCC KEIL IAR 编译通过
]
> [libc标准化] 将dfs_posix.h的函数声明转移到unix标准头文件中

- src/thread.c
> [update] src/thread.c function description.

- src/device.c
- src/idle.c
- src/mem.c
- src/memheap.c
- src/mempool.c
- src/object.c
- src/scheduler.c
- src/slab.c
> [kernel]Normalized kernel API annotation

- src/kservice.c
> [kservice] 完善 API 注释

- src/clock.c
- src/ipc.c
- src/kservice.c
- src/memheap.c
- src/signal.c
> [update] functions annotation.

- components/libc/compilers/common/sys/time.h
- components/libc/compilers/common/time.c
> [libc][time] 修复数据类型报警

- components/dfs/Kconfig
- components/dfs/filesystems/.ignore_format.yml
- components/dfs/filesystems/elmfat/dfs_elm.c
- components/dfs/filesystems/elmfat/ffconf.h
[
[fatfs] 修改互斥保护超时时间 ,防止因一些正常复杂耗时操作（有可能在大容量tf卡上触发），导致fatfs认为 timeout failure。
[dfs][filesystems] 增加format_ignore文件，排除fatfs格式检查
此问题由 @majianjia 发现
]
> [fatfs] 修改互斥保护超时时间, 并将超时时间改为Kconfig可配置

- bsp/hc32f4a0/SConstruct
- bsp/hc32f4a0/rtconfig.py
[
修正了bsp/hc32f4a0的scons构建脚本里的语法错误，现在可以在Ubuntu20.04下正常使用scons进行编译
]
> 修正了bsp/hc32f4a0的scons构建脚本里的语法错误

- bsp/mm32f327x/.ignore_format.yml
> [bsp][mm32f327]修复.ignore_format路径错误

- bsp/ls2kdev/drivers/drv_spi.c
[
环境：ubuntu 20.04.3 LTS (Focal Fossa)
Linux boat 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
问题：
在按照bsp的readme设置好工具链后使用scons 进行编译，报以下错误
```
CC build/drivers/drv_spi.o
drivers/drv_spi.c:23:22: error: unknown type name 'uint8_t'
static void spi_init(uint8_t spre_spr, uint8_t copl, uint8_t cpha)
^
drivers/drv_spi.c:23:40: error: unknown type name 'uint8_t'
static void spi_init(uint8_t spre_spr, uint8_t copl, uint8_t cpha)
^
drivers/drv_spi.c:23:54: error: unknown type name 'uint8_t'
static void spi_init(uint8_t spre_spr, uint8_t copl, uint8_t cpha)
^
drivers/drv_spi.c:33:25: error: unknown type name 'uint8_t'
static void spi_set_csn(uint8_t val) 
^
```
添加缺失的stdint.h头文件
]
以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检 …
> [bsp] Fix missing header file applications in ls2k

- .github/workflows/action.yml
- bsp/bluetrum/libraries/hal_drivers/drv_common.c
- bsp/bluetrum/libraries/hal_drivers/drv_usart.c
> [ab32vg1] 修复NULL和uint8报错

- bsp/stm32/stm32f103-blue-pill/README.md
> [bsp][stm32][bluepill] update readme

- bsp/at32/Libraries/rt_drivers/drv_gpio.c
[
[update][bsp][at32][driver]Optimized the pin-index algorithm
]
> [update][bsp][at32][driver]Optimized the pin-index algorithm

- components/drivers/sensors/sensor_cmd.c
[
fix sensor_cmd.c build error.
]
> fix sensor_cmd.c build error.

- bsp/bluetrum/ab32vg1-ab-prougen/applications/blehr_app.c
- bsp/bluetrum/ab32vg1-ab-prougen/board/Kconfig
- bsp/bluetrum/ab32vg1-ab-prougen/board/board.c
- bsp/bluetrum/ab32vg1-ab-prougen/link.lds
- bsp/bluetrum/libraries/hal_drivers/drv_gpio.c
- bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/SConscript
- bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/source/ab32vg1_hal_gpio.c
- bsp/bluetrum/libraries/hal_libraries/bmsis/source/startup.S
> [bsp/bluetrum] add ble support

- bsp/thead-smart/gcc_csky.ld
Correct startup segment description error in link script
[
改正链接文件中关于启动文件所在段的描述
在E907平台验证
]
> [fix][bsp/thead-smart/gcc_csky.ld]

- .github/workflows/action.yml
- .github/workflows/action_utest.yml
[
[update] ci toolchain download using github link.
]
> [update] ci toolchain download using github link.

- bsp/stm32/stm32l475-atk-pandora/board/ports/lvgl/lv_port_disp.c
> [bsp][stm32l475] update lvgl driver

- components/net/lwip-2.1.2/src/arch/sys_arch.c
- components/net/lwip-2.1.2/src/lwipopts.h
- components/net/lwip-2.1.2/src/netif/ethernetif.c
- components/net/netdev/src/netdev.c
[
解决 netdev 无法通过指定网卡进行ping 操作。
通过增加 lwip 2.1.2 下的 钩子函数 LWIP_HOOK_IP4_ROUTE_SRC 区分指定的网卡。
已经测试
在 art-pi 下多网卡 （wifi，eth）过协议栈 lwip2.1.2，进行测试；
在 qemu-vexpress-a9 单网卡下通过指定 网卡，进行测试；
#5024
]
> ping cmd with specified netif in lwip-2.1.2

- include/rtdef.h
- src/Kconfig
> [master] modify version to v4.1.0

- bsp/gd32450z-eval/Libraries/CMSIS/GD/GD32F4xx/Source/ARM/startup_gd32f4xx.s
- bsp/gd32450z-eval/Libraries/CMSIS/GD/GD32F4xx/Source/GCC/startup_gd32f4xx.S
- bsp/gd32450z-eval/Libraries/CMSIS/GD/GD32F4xx/Source/IAR/startup_gd32f4xx.s
[
fix mistakes about vector table in startup_gd32f4xx.s.
在gd32f450vet6芯片上验证成功。
]
> [fix] fix bugs about startup_gd32f4xx

- components/finsh/cmd.c
- src/timer.c
完善 list_timer 格式，增加单次或周期性模式的展示
> Update Timer cmd

- bsp/nrf5x/nrf52840/board/Kconfig
[
- nrf52840 添加hwtimer驱动配置   -> 测试TIMER0~TIMER4工作正常
- 修改部分配置，适配tinyusb软件包 ， MDK环境下，nrf52840 开发版测试CDC正常工作，可以串口回显
]
> [bsp/nrf5x] add hwtimer config & tinyusb config

- bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
- bsp/ck802/libraries/include/drv_rtc.h
- bsp/ft2004/libraries/bsp/ft_i2c/ft_i2c_selftest.c
- bsp/imxrt/libraries/drivers/drv_rtc.c
- bsp/lpc5410x/Libraries/lpc_chip/chip_common/rtc_ut.h
- bsp/raspberry-pi/raspi3-64/driver/drv_rtc.h
- bsp/swm320-lq100/applications/main.c
- bsp/swm320/applications/main.c
- components/drivers/include/drivers/alarm.h
- components/drivers/rtc/rtc.c
- examples/kernel/event_simple.c
> modify time.h to sys/time.h

- bsp/stm32/stm32l496-st-nucleo/board/Kconfig
[
增加I2C配置文件，menuconfig可配，使用MPU6050测试工作正常，测试流程参考： https://github.com/supperthomas/task_issue/issues/6
]
> [bsp/stm32/stm32l496] add I2C config

- src/Kconfig
- src/kservice.c
[
- 优化RT_PRINTF_LONGLONG，减少重复代码
- 整理Kconfig(缩进问题)
- 将RT_PRINTF_LONGLONG放到Kservice optimization 目录下
]
> [kservice] 优化RT_PRINTF_LONGLONG，减少重复代码

- bsp/nrf5x/libraries/drivers/drv_i2c.c
[
- fix nrf5x i2c驱动bug，目前在nrf52832平台测试，使用MPU6050软件包设备读写正常（之前读写异常）
]
> [bsp/nrf5x] fix i2c driver bug

- components/drivers/src/dataqueue.c
[
Add dataqueue.c function annotatio
增加 components\drivers\src\dataqueue.c 函数注释
]
> Add dataqueue.c function annotation

- bsp/stm32/stm32f103-blue-pill/README.md
> [stm32][bluepill] update readme

- components/drivers/cputime/cputime.c
- components/drivers/cputime/cputime_cortexm.c
- components/drivers/include/drivers/cputime.h
[
当前cputime为32位，频率稍高，很容易溢出。
32位最大值为`0xFFFFFFFF=4 294 967 295`。
- 当计数频率为1Ghz时，4.3秒溢出。
- 当计数频率为100Mhz时，43秒溢出。
- 当计数频率为10Mhz时，429秒溢出。
64位最大值为`0xFFFFFFFFFFFFFFFF=18 446 744 073 709 551 615`。
- 当计数频率为1Ghz时，584年溢出。
]
> cputime数据类型修改为64位

- tools/buildbot.py
> [tools] add function to auto-update rtconfig.h

- bsp/qemu-vexpress-a9/README.md
- bsp/qemu-vexpress-a9/drivers/drv_smc911x.c
- components/drivers/mtd/mtd_nand.c
- components/lwp/lwp_syscall.h
[
本次PR主要修改了 bsp/qemu-vexpress-a9 的两个问题：
1 修复了 bsp/qemu-vexpress-a9 若干代码编译报警告（-Wimplicit-function-declaration）的问题；
2 补充了 bsp/qemu-vexpress-a9 下的 README 文档，主要新增了启动脚本在Windows下和Linux下运行的补充说明，在Windows的env环境下和Linux命令行环境下，均验证通过。
]
> 【PR】修改bsp/qemu-vexpress-a9的若干问题

- bsp/stm32/stm32f469-st-disco/board/ports/lvgl/lv_demo.c
- bsp/stm32/stm32f469-st-disco/board/ports/lvgl/lv_port_disp.c
- bsp/stm32/stm32f469-st-disco/board/ports/lvgl/lv_port_indev.c
- bsp/stm32/stm32l475-atk-pandora/board/ports/lvgl/lv_demo.c
> [stm32][f469]update lvgl demo

- README.md
- README_zh.md
> [update] README.md add cortex-m33

- bsp/qemu-vexpress-a9/Kconfig
- bsp/qemu-vexpress-a9/drivers/Kconfig
- bsp/qemu-vexpress-a9/qemu.sh
> [qemu] update Kconfig

- include/rtdef.h
- src/Kconfig
- src/kservice.c
>  [4.0.x] update release version to 4.0.5

- bsp/stm32/libraries/HAL_Drivers/drv_rtc.c
> [bsp][stm32] Modify variable name p_tm to tm

- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
- bsp/stm32/stm32l475-atk-pandora/board/ports/arduino/SConscript
> [stm32l475] 修正port/arduino的宏定义

- bsp/stm32/libraries/HAL_Drivers/drv_common.c
> [stm32][drv_common] add LOG_E for Error_Handler

- bsp/stm32/libraries/HAL_Drivers/config/h7/spi_config.h
- bsp/stm32/libraries/HAL_Drivers/drv_spi.c
[
1.使能DMA时钟的条件编译中加入了STM32H7。
2.添加STM32H7 "spi_config" 中的request字段。
3.DMA初始化FiFo相关的初始化的条件编译选项中加入STM32H7。
在STM32H750VBT6测试通过。
]
> 完善了STM32H7系列SPI使用DMA的驱动

- bsp/stm32/stm32f411-st-nucleo/README_zh.md
[
[bsp][stm32f411][docs] 修正了 bsp/stm32/stm32f411-st-nucleo/README_zh.md 中的MCU名称错误
]
> [bsp][stm32f411][docs]fix doc error

- bsp/stm32/stm32l475-atk-pandora/board/ports/arduino/SConscript
- bsp/stm32/stm32l475-atk-pandora/board/ports/arduino/arduino_pinout.c
- bsp/stm32/stm32l475-atk-pandora/board/ports/arduino/arduino_pinout.h
> [l475][arduino] 增加ADC PWM管脚定义

- components/drivers/src/waitqueue.c
[
Add waitqueue.c function annotatio
增加 components\drivers\src\waitqueue.c 函数注释
]
> Add waitqueue.c function annotation

- bsp/qemu-vexpress-a9/drivers/Kconfig
- bsp/qemu-vexpress-a9/drivers/lvgl/lv_conf.h
> [qemu][lvgl] update player demo configuration

- bsp/qemu-vexpress-a9/drivers/Kconfig
- bsp/qemu-vexpress-a9/drivers/audio/drv_ac97.c
- bsp/qemu-vexpress-a9/drivers/audio/drv_ac97.h
- bsp/qemu-vexpress-a9/drivers/audio/drv_pl041.c
- bsp/qemu-vexpress-a9/drivers/audio/drv_pl041.h
- bsp/qemu-vexpress-a9/drivers/audio/drv_sound.c
- bsp/qemu-vexpress-a9/drivers/audio/drv_sound.h
- bsp/qemu-vexpress-a9/drivers/board.c
- bsp/qemu-vexpress-a9/drivers/board.h
- bsp/qemu-vexpress-a9/drivers/drv_clcd.c
- bsp/qemu-vexpress-a9/drivers/drv_clcd.h
- bsp/qemu-vexpress-a9/drivers/drv_keyboard.c
- bsp/qemu-vexpress-a9/drivers/drv_keyboard.h
- bsp/qemu-vexpress-a9/drivers/drv_mouse.c
- bsp/qemu-vexpress-a9/drivers/drv_mouse.h
- bsp/qemu-vexpress-a9/drivers/drv_sdio.c
- bsp/qemu-vexpress-a9/drivers/drv_sdio.h
- bsp/qemu-vexpress-a9/drivers/drv_timer.c
- bsp/qemu-vexpress-a9/drivers/drv_timer.h
- bsp/qemu-vexpress-a9/drivers/lvgl/lv_conf.h
- bsp/qemu-vexpress-a9/drivers/lvgl/lv_port_disp.c
- bsp/qemu-vexpress-a9/drivers/realview.h
- bsp/qemu-vexpress-a9/drivers/secondary_cpu.c
- bsp/qemu-vexpress-a9/drivers/serial.c
- bsp/qemu-vexpress-a9/drivers/serial.h
- bsp/qemu-vexpress-a9/drivers/vexpress_a9.h
> [qemu][lvgl] 优化lvgl显示驱动

- bsp/simulator/applications/platform.c
> [vs simulator] remove the error prompt for v4.1.0

- bsp/stm32/stm32f469-st-disco/board/ports/lvgl/lv_port_disp.c
> [update] stm32f469 lvgl demo

- src/ipc.c
> [update] Correct some code comments

- components/drivers/i2c/i2c_dev.c
- components/drivers/include/drivers/i2c.h
- components/drivers/include/drivers/i2c_dev.h
[
优化I2C驱动框架，主要是因为I2C驱动框架中，有部分字段目前理解范围内，没有使用到，容易造成一些干扰
讨论细节，查看论坛链接： https://club.rt-thread.org/ask/question/433847.html
]
> [drivers/i2c] optimize i2c driver framework

- components/drivers/include/drivers/serial_v2.h
- components/drivers/include/ipc/ringblk_buf.h
- components/drivers/sensors/sensor.c
- components/drivers/serial/serial_v2.c
- components/drivers/src/ringblk_buf.c
- components/drivers/usb/usbdevice/class/hid.c
[
- ringblk_buf 关闭全局中断查找末尾节点，效率较低，且关闭中断时间还比较长。
- 优化末尾节点查找方式，每次都更新末尾节点，就不需要通过遍历链表的方式找尾节点，时间复杂度 01
- 在实际项目中测试验证
]
> [components][src] Optimize interrupt disable time

- bsp/essemi/es32f369x/drivers/drv_gpio.c
- bsp/essemi/es32f369x/drivers/drv_uart.c
- bsp/essemi/es32f369x/libraries/CMSIS/Device/EastSoft/ES32F36xx/Include/es32f36xx.h
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Include/ald_adc.h
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Include/ald_i2c.h
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Include/ald_qspi.h
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/ald_adc.c
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/ald_cmu.c
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/ald_crc.c
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/ald_i2c.c
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/ald_nand.c
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/ald_pis.c
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/ald_qspi.c
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/ald_wdt.c
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/utils.c
[
驱动修改
drv_gpio.c    在es32f3_pin_detach_irq中,修复bug：管脚映射错误。
drv_uart.c    修改宏错误
库修改
es32f3xxx.h    修复MSC的FLASHADDR寄存器位域错误。
ald_adc.h      增加ald_adc_offset_adjust函数声明。
ald_i2c.h      增加I2C的fifo复位接口。
ald_qspi.h     删除冗余程序。
ald_adc.c      增加校准接口ald_adc_offset_adjust。
ald_cmu.c      增加类型转换。
ald_crc.c      修复ald_crc_init初始化函数中的移位错误。
ald_i2c.c      修复ald_i2c_reset函数中的置位错误。
ald_nand.c     修订nand的page大小判断:由65535改为65536。
ald_pis.c      增加类型转换。
ald_qspi.c     修订冗余程序。
ald_wdt.c      1. 修复ald_iwdt_clear_flag_status函数清中断标志位时未解锁的错误。
2. 喂狗函数中，喂狗后增加延时。
utils.c        sys_cfg函数中读取0x803D0寄存器。 …
> [essemi][es32f369x] fix bugs and update libraries.

- components/net/lwip-1.4.1/src/lwipopts.h
- components/net/lwip-2.0.2/src/lwipopts.h
- components/net/lwip-2.0.3/src/lwipopts.h
- components/net/lwip-2.1.2/src/lwipopts.h
- src/Kconfig
- src/kservice.c
[
出于newlib memcpy memset安全原因，这些宏被移除
]
> [kservice] remove RT_USING_ASM_MEMCPY RT_USING_ASM_MEMSET

- bsp/stm32/stm32l496-ali-developer/board/SConscript
- bsp/stm32/stm32l496-ali-developer/rtconfig.py
- components/drivers/spi/SConscript
- components/libc/compilers/common/nogcc/SConscript
- components/libc/compilers/gcc/newlib/SConscript
- libcpu/arm/cortex-m4/SConscript
- tools/building.py
[
add clang-arm support.| 已在 aliosthing-develolperKit 测试完成。
]
> add clang-arm support.

- bsp/acm32f4xx-nucleo/rtconfig.py
- bsp/gd32e230k-start/rtconfig.py
- bsp/stm32/stm32l552-st-nucleo/rtconfig.py
- bsp/stm32/stm32u575-st-nucleo/rtconfig.py
[
Improve armclang support.|完善 armclang 支持
]
> Improve armclang support.|完善 armclang 支持

- components/cplusplus/cpp11/armclang/thread.cpp
- components/libc/compilers/common/nogcc/sys/errno.h
[
1. 修复armclang cpp11 内存泄漏
2. 修复编译警告问题
]
> [Fix] armclang cpp11 memory leak and compilation warning 

- include/rtthread.h
- src/kservice.c
[
void *rt_memmove(void *dest, const void *src, rt_ubase_t n);
rt_int32_t rt_memcmp(const void *cs, const void *ct, rt_ubase_t count);
char *rt_strncpy(char *dest, const char *src, rt_ubase_t n);
rt_int32_t rt_strncmp(const char *cs, const char *ct, rt_ubase_t count);
这四个函数
rt_ubase_t 改 rt_size_t 
以符合标准c库的类型
]
> [kservice] implement rt_strcpy()

- bsp/gd32450z-eval/Libraries/CMSIS/GD/GD32F4xx/Source/ARM/startup_gd32f4xx.s
- bsp/gd32450z-eval/Libraries/CMSIS/GD/GD32F4xx/Source/GCC/startup_gd32f4xx.S
- bsp/gd32450z-eval/Libraries/CMSIS/GD/GD32F4xx/Source/IAR/startup_gd32f4xx.s
- bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_l4.c
- bsp/stm32/libraries/HAL_Drivers/drv_wdt.c
- components/net/at/src/at_cli.c
- components/net/lwip-1.4.1/src/arch/include/arch/cc.h
- components/net/lwip-1.4.1/src/arch/include/arch/sys_arch.h
- components/net/lwip-1.4.1/src/lwipopts.h
- components/net/lwip-2.0.2/src/arch/include/arch/cc.h
- components/net/lwip-2.0.2/src/arch/include/arch/sys_arch.h
- components/net/lwip-2.0.2/src/lwipopts.h
- components/net/lwip-2.0.3/src/arch/include/arch/cc.h
- components/net/lwip-2.0.3/src/arch/include/arch/sys_arch.h
- components/net/lwip-2.0.3/src/lwipopts.h
- components/net/lwip-2.1.2/src/arch/include/arch/cc.h
- components/net/lwip-2.1.2/src/arch/include/arch/sys_arch.h
- components/net/lwip-2.1.2/src/arch/sys_arch.c
- components/net/lwip-2.1.2/src/lwipopts.h
> 按照 v4.0.5 计划同步内容

- tools/buildbot.py
> [update] windows tools

- components/finsh/msh_file.c
[
之前tail是根据\n确认行数的。没有考虑最后一行没有\n的问题。
]
> fix cmd: tail

- bsp/stm32/stm32l496-ali-developer/board/SConscript
- bsp/stm32/stm32l496-ali-developer/rtconfig.py
- components/drivers/spi/SConscript
- components/libc/compilers/common/nogcc/SConscript
- components/libc/compilers/gcc/newlib/SConscript
- libcpu/arm/cortex-m4/SConscript
- tools/building.py
Reverts RT-Thread/rt-thread#5412
> Revert "add clang-arm support."

- bsp/at32/Libraries/rt_drivers/drv_gpio.c
- bsp/lpc2148/drivers/serial.c
- bsp/lpc2478/drivers/serial.c
- bsp/mini4020/drivers/board.c
- bsp/mini4020/drivers/sdcard.c
- include/rtdef.h
[
此前实现的RT_UNUSED很有问题，很多编译平台都用不了 在keil AC5下会直接报错
本pr给出一种通用的不依赖编译平台的解决方案
]
> [rtdef] re-implement RT_UNUSED

- bsp/simulator/template_vs2012.vcxproj
[
vs是默认采用中文GB2312编码，会导致一堆乱七八糟的问题，例如汉字注释乱码，编译报错等等。
目前将生成工程默认采用utf-8编码格式
]
> [simulator] 支持utf-8格式

- bsp/fm33lc026/board/Kconfig
- bsp/stm32/stm32f207-st-nucleo/board/Kconfig
[
除了 #5435 之外 对整个仓库进行了排查 发现还有两处
]
> [kconfig] 修复kconfig路径

- bsp/simulator/applications/lvgl/lv_conf.h
- bsp/stm32/stm32l475-atk-pandora/applications/arduino/SConscript
- bsp/stm32/stm32l475-atk-pandora/applications/arduino/arduino_pinout.h
[
修复一些注释错误
simulator的lvgl配置暂时屏蔽掉文件系统（因为lvgl社区最新版代码存在bug，临时退到8.1）
]
> [lvgl][simulator]&[l475][arduino] 细节修改

- bsp/essemi/es32f365x/drivers/ES/es_conf_info_map.h
[
更新es32f365x的管脚描述，64pin更改为100pin。
]
- [v] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [v] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [v] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [v] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is …
> [bsp][essemi]update es32f365x information.

- ChangeLog.md
> add change log for 4.0.5

- ChangeLog.md
Reverts RT-Thread/rt-thread#5441
> Revert "add change log for 4.0.5"

- ChangeLog.md
> add change log for v4.0.5

- src/thread.c
[
若suspend函数挂起的线程不是当前线程，则直接断言掉
]
> [kernel] rt_thread_suspend增加断言

- .github/workflows/action.yml
> [CI]fix the install error of env tools

- include/rtthread.h
[
Add function declarations to avoid compilation warnings.
]
> [include/rtthread.h] Add function declarations to avoid compilation warnings.

- components/libc/compilers/common/nogcc/sys/errno.h
- components/libc/compilers/common/sys/time.h
> [libc] 处理在win32平台下的编译问题

- examples/utest/configs/kernel/irq.conf
- include/rtdef.h
- src/Kconfig
- Backward compatible with existing function-pointer based hooking method
- Using RT_USING_HOOK as an on/off switch
- Introducing a new low-overhead macro-based hooking method
[
过去的HOOK方式要么全开，要么全关，缺乏精细控制能力。同时，原有的HOOK方式在开启的状态下，强迫用户使用函数指针来进行HOOK。函数指针只在运行时刻需要动态修改HOOK内容时才有好处，其余时刻只会增大调用开销。实际上，大部分时候，HOOK的对象在编译时刻就已经确定了，因此强迫用户使用运行时刻的Hook方式是不妥的。
新的方式主体是“插入宏”，它允许用户精细的决定对应的HOOK究竟实现成什么形式。
以上内容在Cortex-M3 FVP上测试通过。
]
我在这个拉取/合并请求中已经考虑了 As part of this …
> Improving hooking methods

- components/libc/compilers/armlibc/syscalls.c
- components/libc/compilers/common/compiler_private.h
- components/libc/compilers/common/time.c
> [libc]修理一些细节问题

- bsp/stm32/stm32l475-atk-pandora/applications/lvgl/lv_port_disp.c
> [lvgl][l475] use single buffer instead of double buffers

- components/finsh/msh.c
- include/rtdef.h
- include/rtthread.h
- src/kservice.c
- src/memheap.c
[
修复 memheap 在 64 位下存在的潜在风险
1. 使用 MDK/IRA/GCC/GCC64/WIN32/WIN64 工具链编译，无警告
2. 在 QEMU/QEMU64  WIN32/WIN64 等环境正常运行
]
> [memheap] Fix 64 bit potential risk

- bsp/n32g452xx/Libraries/rt_drivers/SConscript
- bsp/n32g452xx/Libraries/rt_drivers/drv_gpio.c
- bsp/n32g452xx/Libraries/rt_drivers/drv_gpio.h
- bsp/n32g452xx/Libraries/rt_drivers/drv_pwm.c
- bsp/n32g452xx/Libraries/rt_drivers/drv_usart.c
- bsp/n32g452xx/Libraries/rt_drivers/drv_usart.h
- bsp/n32g452xx/n32g452xx-mini-system/board/Kconfig
[
[bsp/n32g452xx] Unified header file definition. "GPIO_H__" to "DRV_GPIO_H". "USART_H" to "DRV_USART_H"
[bsp/n32g452xx] In drv_pwm.c, variable meaning is different with RT-Thread interface definition. Fixed and tested.
[bsp/n32g452xx] Add support for UART4/UART5.
[bsp/n32g452xx] In drv_gpio.c Modify "N32F10X_PIN_NUMBERS" to "N32G45X_PIN_NUMBERS".
]
> [bsp/n32g452xx] Fix some error and inappropriate definition.

- components/dfs/filesystems/elmfat/dfs_elm.c
- components/dfs/filesystems/ramfs/dfs_ramfs.c
- components/dfs/filesystems/romfs/dfs_romfs.c
- components/dfs/src/dfs.c
- components/dfs/src/dfs_file.c
- components/dfs/src/dfs_fs.c
- components/dfs/src/dfs_posix.c
- components/drivers/audio/audio.c
- components/drivers/misc/rt_drv_pwm.c
- components/drivers/rtc/soft_rtc.c
- components/drivers/spi/enc28j60.c
- components/drivers/spi/sfud/src/sfud.c
- components/drivers/spi/spi_msd.c
- components/drivers/spi/spi_wifi_rw009.c
- components/drivers/src/ringbuffer.c
- components/drivers/usb/usbdevice/class/rndis.c
- components/finsh/msh.c
- components/finsh/msh_file.c
- components/finsh/shell.c
- components/net/at/at_socket/at_socket.c
- components/net/at/src/at_cli.c
- components/net/at/src/at_server.c
- components/utilities/utest/utest.c
- components/utilities/zmodem/rz.c
- components/utilities/zmodem/sz.c
- include/rtthread.h
- src/Kconfig
- src/kservice.c
[
编译器内置memset memcpy，尤其是在newlib下，其只考虑速度，没有考虑内存安全性，很容易导致在非地址对齐的情况下拷贝直接死机。为保证rt-thread核心组件的安全可靠，需要使用rt_xxx代替
]
> [core] 使用rt_memcpy rt_memset代替memcpy memset

- bsp/simulator/template_vs2012.vcxproj
> [simulator] 消除““Gm”选项已否决，并将在将来的版本中移除”的警告

- src/idle.c
> [kernel]Delete an extra semicolon

- tools/eclipse.py
[
解决的问题：
进入bsp/allwinner_tina目录下后，执行scons --project-name=tina --target=eclipse，执行过程中eclipse.py文件报错，write argument require str ,not bytes.
解决的方案：
增加.decode('utf-8')，将转换出来的bytes类型转换为str，是参数符合write接口要求
测试场景：
进入bsp/allwinner_tina目录下执行scons --project-name=tina --target=eclipse，获得所需的.project文件及.cproject文件
]
- [*] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback …
> tools: fix generate .project file error.

- bsp/n32g452xx/Libraries/rt_drivers/drv_can.c
- bsp/n32g452xx/Libraries/rt_drivers/drv_can.h
[
添加 N32G45x 系列芯片的 CAN驱动
已经在 N32G457VEL7 芯片上测试成功，收发数据正常
测试硬件
开发板型号 N32G45XVL-STB
CAN1可以收发
CAN2可以收发
]
> [bsp/n32g452xx] add can drivers 

- bsp/stm32/libraries/HAL_Drivers/drv_lcd_mipi.c
- bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_conf.h
- bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_demo.c
- bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_disp.c
[
使用 DMA2D 外设 1/4面积来刷新屏幕，buffer 采用内部RAM，帧率达到平均25fps
]
> Refresh using dma2d,screen refresh average 25fps

- src/thread.c
[
经过查找资料，虽然freertos ucos都实现了递归挂起和解挂，支持在A线程下挂起B线程。但是目前rtt的处理方法是最正确的，即极大的限制suspend和resume函数的使用空间，尤其是suspend函数，以确保实时性，以及防止死锁（其实不算是死锁）的发生。
https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.suspend?view=net-6.0#remarks
本PR针对suspend和resume函数注释进行了详细描述，提示用户使用的限制条件
]
> [kernel] rt_thread_suspend/resume增加注释

- include/rtdef.h
[
该状态在内核以及整个rtt中没有任何使用，予以移除，防止歧义。
]
> [kernel] remove RT_THREAD_BLOCK

- bsp/qemu-vexpress-a9/applications/main.c
- bsp/qemu-vexpress-a9/drivers/drv_clcd.c
- bsp/stm32/libraries/HAL_Drivers/drv_lcd.c
> [qmeu] chore

- bsp/stm32/stm32l475-atk-pandora/board/ports/audio/drv_es8388.c
> [l475][audio] 消除编译错误

- components/utilities/ymodem/ry_sy.c
- components/utilities/ymodem/ymodem.h
> [ymodem] silent warnings

- bsp/stm32/stm32f407-atk-explorer/board/Kconfig
- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
[
https://github.com/RT-Thread/packages/pull/1165
]
> [stm32][at esp8266][kconfig] 增加esp8266配置选项接管

- src/idle.c
> [kernel][pm] beautify code

- components/dfs/src/dfs_posix.c
- components/libc/compilers/common/extension/fcntl.h
> [dfs][posix] add creat()

- .github/workflows/action_tools.yml
- .github/workflows/action_utest.yml
- tools/eclipse.py
[
Fix bug with missing brackets in eclipse.py 已在 F407上进行了测试。
]
> [tool] Fix bug with missing brackets in eclipse.py

- bsp/stm32/stm32l475-atk-pandora/board/ports/fal/SConscript
- components/drivers/spi/SConscript
- 删除啰嗦的代码
related: https://github.com/RT-Thread/rt-thread/issues/3046
[
]
The following content must not be changed in the submitted PR message. Otherwise, the PR …
> [sconscript.platform] 优化针对编译器判断

- components/net/Kconfig
> [lwip]Improve lwip support for 64-bit architecture

- components/libc/compilers/common/time.c
> [remove] useless variable.

- examples/network/tcpclient.c
- examples/network/tcpserver.c
- examples/network/udpclient.c
- examples/network/udpserver.c
tcpclient.c udpserver.c and udpclient.c
[
Improve and add comments in example/networks folder including tcpserver.c udpserver.c tcpclient.c and udpclient.c.
Comments in those files are added with English .
]
- [√] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- …
> improve and add comments

- components/net/lwip-1.4.1/src/arch/include/arch/cc.h
- components/net/lwip-2.0.3/src/arch/include/arch/cc.h
- components/net/lwip-2.1.2/src/arch/include/arch/cc.h
- libcpu/Kconfig
- src/Kconfig
- 之前RT_USING_BIG_ENDIAN的命名并不合理，予以替换为ARCH_CPU_BIG_ENDIAN
- 删除一处多余重复的ARCH_CPU_64BIT定义
- 整理了libcpu/Kconfig的格式
[
]
The following content must not be changed in the …
> [Kconfig][libcpu] 增加ARCH_CPU_BIG_ENDIAN

- bsp/imxrt/libraries/drivers/drv_can.c
- bsp/imxrt/libraries/drivers/drv_can.h
- bsp/imxrt/libraries/drivers/drv_eth.c
- bsp/imxrt/libraries/drivers/drv_gpio.c
- bsp/imxrt/libraries/drivers/drv_gpio.h
- bsp/imxrt/libraries/drivers/drv_i2c.c
- bsp/imxrt/libraries/drivers/drv_mdio.c
- bsp/imxrt/libraries/drivers/drv_mdio.h
- bsp/imxrt/libraries/drivers/drv_pulse_encoder.c
- bsp/imxrt/libraries/drivers/drv_sai.c
- bsp/imxrt/libraries/drivers/drv_sai.h
- bsp/imxrt/libraries/drivers/drv_sdram.c
- bsp/imxrt/libraries/drivers/drv_sdram.h
- bsp/imxrt/libraries/drivers/drv_spi.c
- bsp/imxrt/libraries/drivers/drv_spi.h
- bsp/imxrt/libraries/drivers/drv_uart.c
- bsp/imxrt/libraries/drivers/usb/device/usb_device.h
[
https://github.com/RT-Thread/rt-thread/pull/5564
在其基础上整理代码格式
合并此pr，5564也会自动合并。
]
> #5564 format codes

- ChangeLog.md
> [UPDATE] v4.1.0 released log.

- include/rtdef.h
> remove outdated comment

- bsp/stm32/stm32f103-blue-pill/rtconfig.py
- bsp/stm32/stm32f302-st-nucleo/rtconfig.py
- bsp/stm32/stm32l010-st-nucleo/rtconfig.py
- bsp/stm32/stm32l053-st-nucleo/board/Kconfig
- bsp/stm32/stm32l053-st-nucleo/rtconfig.py
> [stm32]小ROMbsp 默认为-O2

- components/drivers/misc/dac.c
> 修改dac.c函数名称错误

- bsp/stm32/libraries/STM32F7xx_HAL/SConscript
…DC/MIPI-DSI
Signed-off-by: WillianChan <chentingwei@rt-thread.com>
[
stm32f7xx 系列是 ST 第二款支持 MIPI-DSI 外设的系列芯片，当该系列 bsp 使用 LTDC/MIPI-DSI 外设时，添加 HAL 库文件 stm32f7xx_hal_dsi.c，确保使用 HAL 库进行屏幕驱动开发可行性。
Add stm32f7xx_hal_dsi.c when using LTDC/MIPI-DSI.
]
> [bsp][stm32][stm32f769-st-disco]add stm32f7xx_hal_dsi.c when using LTDC/MIPI-DSI

- components/utilities/var_export/var_export.c
- components/utilities/var_export/var_export.h
- components/utilities/var_export/var_export_cmd.c
Signed-off-by: WillianChan <chentingwei@rt-thread.com>
[
调整编译器宏的顺序，避免在 MDK AC6 环境下选中 `__GNUC__` 的情况。
Adjust the order of compiler macros, avoid selecting `__GNUC__` in an MDK AC6 environment.
]
> [fix][components][utilities]adjust the order of compiler macros

- components/libc/compilers/armlibc/README.md
- components/libc/posix/libdl/dlmodule.c
> [dmodule] 补充头文件

- bsp/qemu-vexpress-a9/qemu.sh
> [bsp] Fix a typo in qemu.sh

- components/drivers/include/ipc/pipe.h
[
related: https://github.com/RT-Thread/rt-thread/issues/3910
]
> [pipe.h] 移除多余的头文件，防止形成头文件递归包含

- bsp/stm32/libraries/HAL_Drivers/config/f1/pwm_config.h
- bsp/stm32/libraries/STM32F1xx_HAL/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_rcc_ex.h
[
1. 修复在 stm32f103c 平台放开 PWM6 ～ PWM13 时，编译不通过问题
在 32f103rct6 测试通过
]
> [bsp][stm32] Add support with pwm6 to pwm13

- bsp/n32g452xx/Libraries/rt_drivers/drv_spi.c
- bsp/n32g452xx/Libraries/rt_drivers/drv_spi.h
[
add drv_spi.c
在 N32G45XVL-STB 测试 spi 屏幕通过
]
> [bsp/n32g452xx] add drv_spi.c

- components/drivers/ipc/pipe.c
- components/libc/posix/io/mman/mman.c
> [fix] add the header file to avoid compiler error.

- include/rtdef.h
- libcpu/sim/win32/startup.c
[
* 优化RT-Thread simulator 模拟器自动初始化，排序执行上更准确
* 方便用户导出自定义的初始化接口，如
```c
/* board init routines will be called in board_init() function */
#define PW_INIT_BOARD_EXPORT(fn)       INIT_EXPORT(fn, "1.1")
```
* 用户自己定义的：PW_INIT_BOARD_EXPORT(func) 可以参与正常的排序并执行
* RT-Thread bsp simulator，创建多个初始化的函数，验证初始化函数的执行次序
* 验证通过
]
> 优化bsp/simulator自动初始化

- bsp/apm32/apm32f103xe-minibroard/README.md
update readme picture name
[
] …
> update readme picture name

- src/thread.c
> [kernel][thread.c] remove duplicated clear to 0

- components/net/lwip/Kconfig
[
已经在env和studio上均测试构建工程通过
related: https://github.com/RT-Thread/packages/pull/1197
]
> [lwip] add lwip latest version

- components/finsh/cmd.c
> [update] remove extra code.

- bsp/stm32/stm32f469-st-disco/README.md
- bsp/stm32/stm32f469-st-disco/README_zh.md
> [bsp][stm32f469-st-disco] 增加英文readme

- bsp/imxrt/imxrt1060-nxp-evk/board/board.c
- bsp/imxrt/imxrt1060-nxp-evk/board/linker_scripts/link.lds
- bsp/imxrt/imxrt1060-nxp-evk/rtconfig.py
- bsp/imxrt/libraries/drivers/SConscript
> [bsp][imxrt1060]fix gcc can't runing issue.

- components/finsh/shell.c
[
删除局部变量 device，防止 shell device 被中途修改
]
> [update] fix finsh bug

- components/finsh/shell.c
- tools/cmake.py
- tools/vsc.py
> [update] 通过 SCons生成 CMakefile.txt 使用相对路径

- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
- bsp/stm32/stm32l475-atk-pandora/board/ports/lcd/drv_lcd.c
- bsp/stm32/stm32l475-atk-pandora/board/ports/lcd/drv_lcd.h
[
支持潘多拉板子 LCD背光亮度可调 新增lcd_display_brightness函数
https://user-images.githubusercontent.com/34888354/159149800-f59cfc21-f9e3-4293-9892-4bf5b1f5cea8.mp4
]
> [stm32 pandora] support backlight with brightness adjustable

- tools/eclipse.py
[
allow users to set specific link scripts.
has tested on studio.
]
> [tools] allow users to set specific link scripts.

- components/libc/compilers/newlib/legacy/_select/SConscript
> [libc] fix a typo

- tools/rt_studio.py
拉取/合并请求描述：(PR description)
[
scons --dist-ide 生成工程时，修改工程中 projcfg.ini 模板
studio 在导入 bsp 时，调用了 scons --dist-ide 命令, 但自动生成的 projcfg.ini 不符合实际需求, 更新后方便后续维护
]
当前拉取/合并请求的状态 Intent for your PR
代码质量 Code Quality：
已经仔细查看过代码改动的对比 Already check the difference between PR and old code
> update the template for projcfg.ini in rt-studio

- src/kservice.c
[
修复 64 位编译器编译警告，使用 qemu-virt64-aarch64 平台进行测试
]
> [kservice] Fix 64 bit compilation warning

- bsp/gd32303e-eval/Kconfig
- bsp/gd32303e-eval/drivers/SConscript
- bsp/gd32303e-eval/drivers/drv_soft_spi.c
- bsp/gd32303e-eval/drivers/drv_soft_spi.h
- components/drivers/Kconfig
- components/drivers/spi/SConscript
- components/drivers/spi/spi-bit-ops.c
- components/drivers/spi/spi-bit-ops.h
[
基于SPI总线驱动框架添加模拟SPI总线扩展，已在GD32F303x系列MCU上验证，本次一并提供了drv_soft_spi驱动参考
]
> [components][drivers][spi]: 基于SPI总线驱动框架添加模拟SPI总线扩展

- components/drivers/ipc/ringbuffer.c
> [ringbuffer] 消除c99

- bsp/ft32/libraries/FT32F0xx/CMSIS/FT32F0xx/source/system_ft32f0xx.c
修改上一个 pull request 中审查过程编译不通过的问题（文件名大小写不兼容），修改system_ft32f0xx.c文件中“#include "FT32f0xx.h"”为“#include "ft32f0xx.h"”。
> modify system_ft32f0xx

- bsp/at32/Libraries/rt_drivers/drv_soft_i2c.c
- bsp/at32/Libraries/rt_drivers/drv_usart.c
- bsp/bluetrum/libraries/hal_drivers/drv_soft_i2c.c
- bsp/gd32/libraries/gd32_drivers/drv_soft_i2c.c
- bsp/gd32vf103v-eval/drivers/drv_usart.c
- bsp/hk32/libraries/rt_drivers/drv_soft_i2c.c
- bsp/hk32/libraries/rt_drivers/drv_usart.c
- bsp/n32g452xx/Libraries/rt_drivers/drv_soft_i2c.c
- bsp/renesas/libraries/HAL_Drivers/drv_soft_i2c.c
- bsp/stm32/libraries/HAL_Drivers/drv_pulse_encoder.c
- bsp/stm32/libraries/HAL_Drivers/drv_soft_i2c.c
- bsp/stm32/stm32l4r9-st-eval/board/ports/drv_touch_ft.c
- bsp/tm4c123bsp/libraries/Drivers/drv_spi.c
- components/drivers/spi/spi-bit-ops.h
[
文件中使用了非ascii的utf符号，有潜在引发乱码的风险
]
> format code

- bsp/stm32/stm32f072-st-nucleo/applications/arduino/SConscript
- bsp/stm32/stm32f072-st-nucleo/board/Kconfig
- bsp/stm32/stm32l475-atk-pandora/applications/arduino/SConscript
- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
https://github.com/RT-Thread/packages/pull/1224
> [stm32 pandora][arduino] 增加依赖项

- components/dfs/src/dfs.c
> list_fd 显示完整路径

- components/utilities/ulog/ulog.c
[
Fixed the issue LOG_HEX no output at asyn mode. https://github.com/RT-Thread/rt-thread/issues/5714
Has been tested on qemu-a9.
]
> Fixed the issue LOG_HEX no output at asyn mode.

- bsp/at32/libraries/f403a_407/.ignore_format.yml
> [at] add ingore_format.yml

- bsp/qemu-vexpress-a9/drivers/Kconfig
- bsp/stm32/stm32f407-atk-explorer/board/Kconfig
- components/libc/posix/Kconfig
- components/net/sal/Kconfig
[
修复sal和dfs同时开启导致socket描述符和dfs描述符不统一的问题，在开启POSIX的情况下，将网络socket开启权限交由POSIX一侧控制。POSIX相关的内容交由POSIX目录下统一选择，方便熟悉POSIX但是不熟悉RT-Thread的用户快速将RT-thread使用起来。
]
> [posix] add RT_USING_POSIX_SOCKET

- components/drivers/include/ipc/workqueue.h
- include/rtdef.h
- include/rthw.h
[
[update] Fix some spelling mistakes.
]
> [update] Fix some spelling mistakes.

- components/libc/posix/io/poll/poll.c
[
论坛报告的bug，代替提交pr
提出：https://club.rt-thread.org/ask/question/431345.html
解决：https://club.rt-thread.org/ask/question/431438.html
related: https://github.com/RT-Thread/rt-thread/issues/4757
]
> [poll][select] 修复select死循环的问题

- components/net/lwip/port/sys_arch.c
> [lwip] delete useless RTM export

- ChangeLog.md
> [update] ChangeLog for RT-Thread_v4.1.0

- .github/workflows/action.yml
- .github/workflows/action_tools.yml
- .github/workflows/action_utest.yml
- .github/workflows/file_check.yml
[
[ci] update action use python@v3
]
> [ci] update action use python@v3

- libcpu/Kconfig
> [libcpu] Add CM33

- components/drivers/include/drivers/sensor.h
- components/drivers/sensors/sensor.c
- components/drivers/sensors/sensor_cmd.c
> [sensor]Add blood pressure sensor type

- bsp/stm32/stm32f072-st-nucleo/board/Kconfig
- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
> [arduino] 非必要功能使用弱依赖

- components/drivers/include/ipc/workqueue.h
- components/fal/src/fal_partition.c
- components/fal/src/fal_rtt.c
- components/libc/compilers/common/extension/fcntl.h
- components/libc/compilers/common/extension/sys/select.h
- components/libc/compilers/common/extension/sys/stat.h
- components/libc/compilers/common/extension/sys/types.h
- components/libc/compilers/common/extension/sys/unistd.h
- components/libc/compilers/common/sys/ioctl.h
- components/libc/compilers/common/sys/statfs.h
- components/utilities/var_export/var_export.c
[
1. 修复 C++ 编译报错
2. 修复部分 VC 编译警告
]
> [compilers] Fix c/c++ compilation warnings and errors

- components/drivers/hwcrypto/hw_symmetric.h
[
密钥的长度及向量的长度，正常情况下不会超过 65536，一般为  128  256  等
所以不需要使用 u32 进行存储，优化内存占用
]
> [hwcrypto]Optimize memory usage

- components/utilities/Kconfig
- components/utilities/ulog/SConscript
- components/utilities/ulog/backend/file_be.c
- components/utilities/ulog/backend/ulog_be.h
- components/utilities/ulog/syslog/syslog.c
- components/utilities/ulog/ulog.c
- components/utilities/ulog/ulog.h
[
添加文件后端，支持设置文件数量，文件大小，自动回滚功能
]
> [components][ulog] Add file backend

- components/drivers/include/drivers/alarm.h
- components/drivers/include/drivers/dac.h
- components/drivers/include/drivers/hwtimer.h
- components/drivers/include/drivers/i2c_dev.h
- components/drivers/include/drivers/pm.h
- components/drivers/include/drivers/rt_drv_pwm.h
- components/drivers/include/drivers/rtc.h
- components/drivers/include/drivers/sensor.h
- components/drivers/include/drivers/watchdog.h
- components/drivers/misc/adc.c
- components/drivers/misc/dac.c
- components/drivers/misc/pin.c
- components/drivers/misc/rt_drv_pwm.c
- components/drivers/rtc/alarm.c
- components/drivers/touch/touch.h
- components/drivers/watchdog/watchdog.c
- include/rtdef.h
[
1. 细化杂项设备，方便后续通过类型查找设备句柄
2. 细化设备 CTRL 值，每个设备 CTRL 值都不一样，防止冲突
]
> [device]Detailed classification of devices types

- components/finsh/cmd.c
[
[finsh]fix list_device crash.
has been tested by stm32-l496-ali-developer.
]
> [finsh]fix list_device crash.

- components/fal/inc/fal.h
> [update] support fal api for c++

- components/libc/compilers/newlib/SConscript
> [libc] improve sconscript

- src/ipc.c
Add descriptions for rt_mq_recv and rt_sem_take timeout parameters
[
]
The following content must not be changed in the submitted PR message. Otherwise, the PR …
> correct the descriptions of functions

- bsp/stm32/libraries/HAL_Drivers/drv_spi.c
[
1.在STM32F4上使用SPI2时发现CLK与设置的一直不一样，查看数据手册发现，SPI2使用APB1作为输入时钟
另外，我查看了STM32G，STM32F1, STM32F4, STM32L4, STM32H7发现SPI输入CLK是有规律的：
默认 SPI1, SPI4, SPI5挂在APB2上，一般是高速SPI；SPI2, SPI3挂在APB1上 ,一般属于低速SPI; SPI6(目前只在高系列H7上看到)挂到APB4上。STM32G0，STM32F比较特殊，只有一个APB。
2.另外为了兼容多个SPI 总线，根据spi_drv->config->Instance选择APB
]
> [bsp/stm32] select the input clk of spi based on SPI instances

- bsp/airm2m/air105/libraries/HAL_Driver/Src/core_i2c.c
- bsp/airm2m/air105/libraries/rt_drivers/drv_i2c.c
> fix:修复i2c异常问题

- components/drivers/hwcrypto/hw_crc.c
[
fix comment on return value of `rt_hwcrypto_crc_update`
]
> fix comment

- include/rtthread.h
> attach #5815

- components/drivers/include/drivers/dac.h
- components/drivers/misc/dac.c
[
Correct data type of the value returned.
]
> Fix return value of rt_dac_write function.

- tools/iar.py
- tools/mkromfs.py
[
修复 python3 运行报错
1. 使用  Python 2.7.10 运行通过
2. 使用 Python 3.10.2 运行通过
]
> [tools] Add Python 3 compatibility patch

- components/fal/src/fal_partition.c
> [components][fal] Compact code

- components/libc/posix/io/termios/termios.c
- components/libc/posix/io/termios/termios.h
> [libc][io] Remove definitions that are not in use

- libcpu/arm/cortex-a/gic.c
- libcpu/arm/cortex-a/gic.h
> [libcpu][arm] Fix compilation warning

- bsp/stm32/libraries/HAL_Drivers/drv_rtc.c
- components/drivers/rtc/rtc.c
[
https://club.rt-thread.org/ask/question/435398.html
该问题点在于.tm_min成员变量要求0-11 并非1-12，因此出现了这个问题
顺带修复了stm32 rtc驱动警告的问题，以及参数检查时，第60秒闰秒没有考虑到的问题。
]
> [bug] 修正rtc对时间参数范围的处理 | fix a bug of rtc

- components/finsh/cmd.c
[
增强系统稳定性，CMD 与 rtdef 两边类型对应不上时，设备类型打印 Unknown, 不至于系统宕机
]
> [finsh][cmd] Enhance system robustness

- components/libc/compilers/common/time.c
> [libc][time] Fix bug

- bsp/n32g452xx/Libraries/rt_drivers/drv_spi.c
[
在N32G45x的BSP中drv_spi.c中的spixfer函数，添加超时检测功能，避免读写数据中发生异常造成卡死现象。
本代码已有N32G455REL7芯片上测试通过。
]
> [bsp/n32g45x] drv_spi.c中添加超时检测避免卡死

- components/net/lwip/lwip-2.0.3/src/apps/ping/ping.c
> [lwip] Fix compilation warning

- include/rtdef.h
- src/Kconfig
> modify version to v4.1.1

- bsp/ft2004/ft_aarch32.lds
- bsp/qemu-vexpress-a9/link.lds
- bsp/qemu-vexpress-gemini/vexpress.lds
- bsp/qemu-virt64-aarch64/link.lds
- bsp/raspberry-pi/raspi2/link.lds
- bsp/raspberry-pi/raspi3-32/link.lds
- bsp/raspberry-pi/raspi3-64/link.lds
- bsp/raspberry-pi/raspi4-32/link.lds
- bsp/raspberry-pi/raspi4-64/link.lds
- bsp/rm48x50/rm48x50.ld
- bsp/rockchip/rk3568/link.lds
- bsp/zynqmp-r5-axu4ev/zynqmp-r5.ld
- libcpu/arm/cortex-a/start_gcc.S
[
- 提交原因：
在GCC4.7及以上的版本，C++全局构造函数已从`.ctors`移动到`.init_array`中， 原Cortex-A启动代码中，对C++全局构造函数的初始化方式已不适用。
- 测试结果：
已经在全志cortex-A7平台上测试。
]
> 修复Cortex-A平台在GCC4.7及以上版本，对C++全局构造函数初始化的问题

- src/ipc.c
- src/timer.c
correct descriptions in ipc.c and timer.c
[
] …
> correct descriptions

- tools/building.py
- tools/options.py
[
原因:
scons附加的命令行参数散落在python文件各处,不是很清晰
方案:
新建一份python文件集中汇总命令行参数
]
> Decouple the addition of command line arguments

- components/libc/compilers/common/extension/fcntl/octal/SConscript
> [libc] 优化armcc armclang处理

- bsp/gd32/libraries/gd32_drivers/drv_spi.c
[
related:
https://github.com/RT-Thread/rt-thread/pull/5729
]
> [gd32] format code attach #5729

- tools/building.py
[
get option的逻辑漏掉了针对windows平台的处理，遂补上。
]
> Fix bugs for processing command line parameters

- bsp/stm32/libraries/HAL_Drivers/drv_dac.c
- components/drivers/include/drivers/dac.h
- components/drivers/misc/adc.c
- components/drivers/misc/dac.c
[
https://github.com/RT-Thread/rt-thread/issues/5817
]
> [dac] add get resolution method

- components/drivers/hwtimer/hwtimer.c
- components/drivers/include/drivers/usb_common.h
> [drivers] Fix compilation warning

- libcpu/arm/cortex-a/trap.c
[
添加 `rt_hw_exception_install` 函数
]
> [libcpu][arm] Add exception install function

- bsp/qemu-vexpress-a9/drivers/drv_mouse.c
[
qemu-vexpress-a9的编译选项有-Wall -Werror，当有warning时，编译会通不过，在drv_mouse.c中存在未使用的变量以及未声明的函数，对这两处warning做了修复，并在这个BSP中做了测试。
]
> [BSP][qemu-vexpress-a9]fixed some warning

- bsp/at32/libraries/f435_437/rt_drivers/drv_adc.c
[
[bsp/at32] update at32f435_437 adc driver
]
> [bsp/at32] update at32f435_437 adc driver

- bsp/stm32/libraries/HAL_Drivers/drv_spi.c
[
在 #5707 基础上解决 #5873 bug
已在pandora, stm32f4disc1上测试
]
> [bsp/stm32] judge the SPI instances before operating

- components/drivers/ipc/waitqueue.c
- components/libc/compilers/common/time.c
- src/idle.c
- src/ipc.c
- src/kservice.c
- src/mempool.c
- src/scheduler.c
- src/thread.c
- src/timer.c
[
根据要求  移除掉register关键字 https://github.com/RT-Thread/rt-thread/pull/5800#issuecomment-1100524185
]
> [kernel] remove the register keyword

- src/scheduler.c
> [kernel] rename _rt_scheduler_stack_check as _scheduler_stack_check

- src/thread.c
> [kernel] update comments for rt_thread_suspend

- bsp/stm32/stm32f072-st-nucleo/applications/arduino_pinout/pins_arduino.h
- bsp/stm32/stm32f072-st-nucleo/board/Kconfig
- bsp/stm32/stm32f401-st-nucleo/applications/arduino_main.cpp
- bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/README.md
- bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/pins_arduino.h
- bsp/stm32/stm32f401-st-nucleo/applications/main.c
- bsp/stm32/stm32f401-st-nucleo/board/Kconfig
- bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/README.md
- bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/pins_arduino.h
- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
> [arduino] update

- components/libc/posix/libdl/dlmodule.c
> [fix] fix dlmodule compile 'SEEK_END' undeclared eror

- tools/building.py
- tools/xmake.lua
- tools/xmake.py
[
- set toolchain dir:
- generate xmake.lua file:
- build project:
]
> [update] support command: scons --target=xmake

- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/SConscript
- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/demo/SConscript
- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/demo/lv_demo.c
- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/lv_conf.h
- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/lv_port_disp.c
- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/squareline/SConscript
- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/squareline/ui/README.md
- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/squareline/ui/SConscript
- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/squareline/ui/lv_ui_entry.c
- bsp/imxrt/imxrt1060-nxp-evk/board/Kconfig
[
根据LVGL请求，使用IMXRT1060来进行测试。
后续，将LVGL 线程抽出来，放到LVGL仓库中去。
]
> [imxrt1060] prepare to support SquareLine Studio

- bsp/stm32/libraries/HAL_Drivers/drv_spi.c
[
此处逻辑有错误，RT_SPI_NO_CS和选择软、硬片选没有关系。
]
> [stm32][spi] remove hardware NSS

- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/lv_port_indev.c
- bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/lv_port_indev.h
- bsp/raspberry-pico/applications/lvgl/lv_port_indev.c
- bsp/raspberry-pico/applications/lvgl/lv_port_indev.h
- bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_indev.c
- bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_indev.h
- bsp/stm32/stm32l475-atk-pandora/applications/lvgl/lv_port_indev.c
- bsp/stm32/stm32l475-atk-pandora/applications/lvgl/lv_port_indev.h
> [lvgl] beautify code

- tools/cmake.py
tools/cmake: Add CMAKE_EXPORT_COMPILE_COMMANDS ON
Signed-off-by: SunJ <jsun@bouffalolab.com>
[
why：
我使用cmake编译，vim阅读代码，每次都要手动开启cmake编译数据库太鸡儿麻烦
测试：
stm32/stm32h743-st-nucleo
]
> cmake默认开启生成编译数据库

- components/drivers/hwtimer/hwtimer.c
[
如果读取定时器数据是在其他中断中完成，例如外部中断，且该中断的优先级高于硬件定时器的优先级。可能会导致硬件定时器的中断函数只执行了一半，那边就去读取数据了，数据可能会出问题。
]
> [hwtimer] add disable interrupt protection for hwtimer_isr function

- .github/workflows/action.yml
> [nxp] add ci check

- components/drivers/include/drivers/sensor.h
Melexis is the fourth largest automotive sensor manufacturer in the world.
www.melexis.com
[
]
The following content must not be changed in the submitted PR …
> Add RT_SENSOR_VENDOR_MELEXIS in sensor.h

- components/libc/compilers/common/stdlib.c
- components/libc/posix/pthreads/pthread.c
- components/libc/posix/pthreads/pthread_barrier.c
- examples/utest/testcases/cpp11/thread_tc.cpp
- src/idle.c
[
* have tested base on 'sigle core' and 'double core' mode.
* have tested base on qemu-vexpress-a9
]
> [pthread]Modify the recycle logic about resource of pthread.

- README.md
- README_de.md
- README_es.md
- README_zh.md
> update readme for languages choices

- components/net/at/at_socket/at_socket.c
[
* code ```node = rt_slist_next(node)``` is risk, because the memory of 'node' had freed.
* tested on stm32f407atk
]
> [bug] use pointer that memory had freed.

- include/rtservice.h
close https://github.com/RT-Thread/rt-thread/issues/5981
> [include] fix comment for rt_container_of

- components/utilities/ulog/backend/file_be.c
> [ulog] Optimize unnecessary refresh

- components/libc/compilers/common/time.c
[
revert https://github.com/RT-Thread/rt-thread/pull/4422
该函数在vs simulator上缺失
已经在vs keil iar gcc上编译测试通过
]
> [libc] revert back difftime

- src/timer.c
> [kernel][timer] fixed bug

- bsp/stm32/libraries/HAL_Drivers/drv_rtc.c
[
https://club.rt-thread.org/ask/question/8ae91c5e0a577a1d.html
]
> [STM32][RTC] add support for STM32L0 series.

- bsp/qemu-vexpress-a9/applications/mnt.c
[
https://github.com/RT-Thread/rt-thread/issues/5999
]
> [bsp/qemu-vexpress-a9] add remount operation to avoid dfs_mout fail

- bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/pins_arduino.c
- bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/pins_arduino.h
- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
- bsp/stm32/stm32l475-atk-pandora/board/ports/lcd/drv_lcd.c
- components/drivers/include/drivers/adc.h
- components/drivers/include/drivers/rt_drv_pwm.h
> [arduino] add comment

- bsp/essemi/es32f369x/libraries/CMSIS/Device/EastSoft/ES32F36xx/Startup/gcc/startup_es32f36xx.S
- bsp/essemi/es32f369x/libraries/CMSIS/Device/EastSoft/ES32F36xx/Startup/iar/startup_es32f36xx.s
- bsp/essemi/es32f369x/libraries/CMSIS/Device/EastSoft/ES32F36xx/Startup/keil/startup_es32f36xx.s
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/ald_acmp.c
- bsp/essemi/es32f369x/libraries/ES32F36xx_ALD_StdPeriph_Driver/Source/ald_adc.c
[
更新es32f36xx的库。
]
- [v] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [v] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [v] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [v] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- …
> [bsp][essemi] update es32f36xx libraries.

- include/rtthread.h
- src/kservice.c
> attach: remove strnlen #6026

- .gitignore
[
将source insight4 的工程文件，加入忽略列表
]
> [.gitignore] add source insight projects in .gitignore

- bsp/hc32/ev_hc32f460_lqfp100_v2/board/Kconfig
- bsp/hc32/libraries/hc32_drivers/drv_soft_i2c.h
[
1.添加HC32F460系列的soft_i2c的外设驱动支持；
2.修改drv_soft_i2c.h中其他I2Cx_BUS_CONFIG的pin名称错误；
3.该PR已在 ev_hc32f460_lqfp100_v2开发板测试通过，测试用开发板上oled接口，即i2c2，驱动oled正常显示。
]
> [bsp][hc32]添加HC32F460系列模拟I2C外设驱动支持

- bsp/hc32/ev_hc32f460_lqfp100_v2/board/Kconfig
- bsp/hc32/ev_hc32f460_lqfp100_v2/board/board_config.c
- bsp/hc32/ev_hc32f460_lqfp100_v2/board/board_config.h
- bsp/hc32/ev_hc32f460_lqfp100_v2/board/config/adc_config.h
- bsp/hc32/ev_hc32f460_lqfp100_v2/board/drv_config.h
- bsp/hc32/libraries/hc32_drivers/SConscript
- bsp/hc32/libraries/hc32_drivers/drv_adc.c
[
添加HC32F460系列ADC外设驱动支持
已在ev_hc32f460_lqfp100_v2开发板进行测试，运行正常。
ADC12_IN10、ADC1_IN12、ADC1_IN13配置为ADC1的CH10、CH12、CH13通道。
ADC12_IN11配置为ADC2的CH7通道。
]
> 添加HC32F460系列ADC外设驱动支持

- src/kservice.c
> [kservice] add NULL check for rt_free and rt_free_align.

- bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c
[
手动处理PR https://gitee.com/rtthread/rt-thread/pulls/65/files
手头没有板子 谁来帮忙测一下这个PR
]
> [stm32][hwtimer] add H7 support

- bsp/hc32/ev_hc32f4a0_lqfp176/board/Kconfig
- bsp/hc32/libraries/hc32_drivers/drv_adc.c
- bsp/hc32/libraries/hc32_drivers/drv_can.c
[
[what]
1.修正 adc bug: Internal trigger1的common trigger使能错误
2.修正 can bug: Filter 的ID 类型设置错误
[how]
1. adc: 使用 internal trigger1的common trigger 配置项来配置
2. can: 根据传递的 ide 参数值设置正确的 low level ID类型到low level driver
[test]
已在EV_F4A0_LQ176_V05上完成上述修改的相关测试
]
> fix bugs of hc32 driver adc and can

- tools/building.py
- tools/options.py
> [fix][building.py]修复动态模块的option的bug

- bsp/simulator/applications/mnt.c
> [simulator] improve init process

- bsp/stm32/libraries/HAL_Drivers/SConscript
- bsp/stm32/libraries/HAL_Drivers/drv_soft_spi.c
- bsp/stm32/libraries/HAL_Drivers/drv_soft_spi.h
- bsp/stm32/stm32f407-atk-explorer/board/Kconfig
- bsp/stm32/stm32f407-atk-explorer/board/SConscript
- bsp/stm32/stm32f407-atk-explorer/board/ports/soft_spi_flash_init.c
- components/drivers/spi/spi-bit-ops.h
[
完成stm32软件模拟spi适配，在 stm32f407-atk-explorer 板子完成测试。
]
> [stm32][soft spi] implement soft spi

- bsp/hc32/ev_hc32f460_lqfp100_v2/board/board.h
- bsp/hc32/ev_hc32f4a0_lqfp176/board/board.h
[
把编译器宏定义从“#ifdef __CC_ARM”修改为“#ifdef __ARMCC_VERSION”，用于支持MDK AC6编译器。
在MDK V5.31.0.0 ArmClang V6.14上编译通过。
]
> [bsp][hc32]support MDK AC6 compiler

- bsp/stm32/stm32f072-st-nucleo/applications/arduino_main.cpp
- bsp/stm32/stm32f072-st-nucleo/applications/arduino_pinout/pins_arduino.h
- bsp/stm32/stm32f072-st-nucleo/board/Kconfig
- bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/README.md
- bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/pins_arduino.c
- bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/pins_arduino.h
- bsp/stm32/stm32f401-st-nucleo/board/Kconfig
[
移除硬件定时器依赖
取消stm32f401 spi的支持
更换f401 arduino默认例程
]
> [arduino] use perf_counter to instead of hwtimer

- components/drivers/include/ipc/ringbuffer.h
- components/drivers/ipc/ringbuffer.c
[
https://github.com/RT-Thread/rt-thread/issues/6073
]
> [fingbuffer] fix a typo

- tools/eclipse.py
增强 eclipse 工程对于 静态链接库 的导入功能
- 取消库文件名的前缀必须为 lib 的限制
- 简化库导入写法，支持 group 中传入整个库完整路径，例如: `LIBS = Glob('*.a')`
> [tools][target][eclipse] Update the libs import for eclipse project.

- bsp/qemu-virt64-aarch64/applications/graphic.c
- bsp/qemu-virt64-aarch64/driver/virtio/virtio.c
[
1.修改 VirtIO Queue内存初始化时内存对齐的填充，避免在系统或者设备驱动重启时，没有完整清理数据而可能导致未知的错误。
2.在graphic.c中添加点击事件功能用例，便于其他开发者调试UI类项目。
]
> [bsp/qemu-virt64-aarch64] Fixup VirtIO queue align size

- components/libc/compilers/armlibc/syscalls.c
[
现在针对libc的utest测试用例不完全，边界行为没有充分试出来，因此返回值处理比较谨慎，之前遇到过返回-1导致printf等标准输入输出不工作的问题。因此只更改此处，其他地方依然保持返回0作为错误返回。
]
> fix the error return in armlibc

- components/drivers/include/drivers/spi.h
- components/drivers/spi/device_driver_list.txt
- components/drivers/spi/spi_core.c
rt_spi_sendrecv8()存在可能未初始化值返回的情况
[
#6008
]
> [spi] fix issue report #6008

- components/drivers/hwtimer/hwtimer.c
- components/drivers/include/drivers/hwtimer.h
- components/drivers/include/drivers/mtd_nand.h
- components/drivers/include/drivers/mtd_nor.h
- components/drivers/include/drivers/pulse_encoder.h
- components/drivers/include/drivers/rt_drv_pwm.h
- components/drivers/include/drivers/rt_inputcapture.h
- components/drivers/misc/pulse_encoder.c
- components/drivers/misc/rt_drv_pwm.c
- components/drivers/misc/rt_inputcapture.c
- components/drivers/mtd/mtd_nand.c
- components/drivers/mtd/mtd_nor.c
https://github.com/RT-Thread/rt-thread/issues/3910
> [rtdevices] eliminate recursion

- components/libc/compilers/newlib/syscalls.c
> [libc][newlib] format

- bsp/imxrt/libraries/drivers/drv_gpio.c
[
为imxrt系列BSP对接rt_pin_get() api。
]
> Implement api docking of rt_pin_get.

- documentation/contribution_guide/coding_style_en.md
Fresh eyes on the English coding style guide.
Remove "speed bumps" to a native English reader to improve acceptance.
[
]
The following content must not be changed …
> Update English coding style for more idiomatic use

- bsp/qemu-vexpress-a9/README.md
> chore: improve qemu readme

- components/finsh/shell.c
> [finsh]修复使用finsh_set_prompt重定向了msh提示符的名称后，路径功能没有的问题

- components/finsh/cmd.c
> List command 

- bsp/stm32/libraries/HAL_Drivers/drv_rtc.c
[
- 适配STM32 RTC Alarm驱动
- 在STM32L4、STM32H7等平台测试通过
]
> [BSP][STM32] RTC Alarm驱动适配

- bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
> [bsp/stm32]优化功能(drv_pwm)：设置PWM频率和脉宽时不破坏上一个PWM周期

- bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
- components/drivers/include/drivers/rt_drv_pwm.h
- components/drivers/misc/rt_drv_pwm.c
> [rt_drv_pwm]增加API：增加单独设置PWM频率和脉宽的函数

- components/net/at/Kconfig
- components/net/at/at_socket/at_socket.c
- components/net/at/at_socket/at_socket.h
- components/net/sal/impl/af_inet_at.c
[
* tested base on stm32f407 + esp8266
]
> [add] implement about "AT server".

- bsp/essemi/es32f369x/drivers/ES/es_conf_info_map.h
- bsp/essemi/es32f369x/drivers/drv_pwm.c
[
1. 将管脚从64pin改为100pin。（100pin兼容64pin）
2. 修复pwm驱动中的bug：注册设备时，名字错误。
]
- [v] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [v] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [v] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [v] 没有垃圾代码，代码尽量精简，不包含`#if …
> [bsp][essemi]fix bug.

- bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
防止后续维护出现没有全面修改的问题
attach：https://github.com/RT-Thread/rt-thread/pull/6130
在合并过程中，已经发现了这种顾头不顾腚的问题，在review PR的时候一定要对这种问题予以警觉，否则随着时间的推移，顾头不顾腚的问题很快就会引发一些列的问题：
已经在RTduino上测试过
> [stm32] 合并获取定时器时钟频率公共部分

- components/libc/posix/ipc/semaphore.c
[
* have tested on qemu-a9
* have tested on stm32f411-nucleo
------
When the  posix semaphore is static object,  it can't release it's memory. Only dynamic object can release it's memory.
That's means the memory when you use "sem_open" to create posix semaphore, it's memory can be released.
]
> [fix] memory leak when the value of posix semaphore is zero.

- bsp/simulator/applications/lvgl/win32drv.c
https://github.com/lvgl/lv_drivers/commit/b69dca2ade845532a971bc935b7127cbda19ec9b
https://github.com/lvgl/lv_drivers/commit/0b01584e299e9a7bb880678c33d4da6fe472fc9e
https://github.com/lvgl/lv_drivers/pull/212
https://github.com/lvgl/lv_drivers/pull/216
[
And confirm in which case or board has been …
> [simulator][lvgl]同步lvgl win32 driver

- components/drivers/include/drivers/alarm.h
- components/drivers/rtc/alarm.c
> chore: fix a typo

- documentation/thread/thread.md
[
Even though the documentation is good, it contains many spelling mistakes, which especially for people for whom English is not a native language, can be confusing to read. I fixed many of these in the documentation file for the thread functionality in RT-Thread, which I believe is one of the more important parts of the documentation. Most of the fixes are simple - regarding definite/indefinite articles. No code was changed.
] …
> Documentation grammar fixes and edits for clarity

- bsp/at32/libraries/rt_drivers/drv_emac.c
[
[bsp/at32] optimize code to improve network throughput performance
]
> optimize code to improve network throughput performance

- bsp/essemi/es32f369x/applications/arduino_pinout/README.md
- bsp/essemi/es32f369x/applications/arduino_pinout/examples/arduino_examples.cpp
- bsp/essemi/es32f369x/drivers/drv_i2c.c
[
给essemi的bsp es32f369x的i2c修复了一个bug，在Wire.write的prefix为空的时候无法正常发送。
完善了文档。
在ES32F3696LX开发板上测试
]
> Bsp essemi

- bsp/stm32/stm32f469-st-disco/applications/SConscript
> attach #6162

- documentation/introduction/introduction.md
> correct the license description

- components/libc/compilers/common/ctime.c
> [libc] 修复difftime函数在IAR下的编译错误

- bsp/at32/libraries/rt_drivers/drv_wdt.c
- bsp/n32/libraries/.ignore_format.yml
- bsp/n32/libraries/n32_drivers/SConscript
- bsp/n32/libraries/n32_drivers/drv_adc.c
- bsp/n32/libraries/n32_drivers/drv_can.c
- bsp/n32/libraries/n32_drivers/drv_can.h
- bsp/n32/libraries/n32_drivers/drv_dac.c
- bsp/n32/libraries/n32_drivers/drv_gpio.c
- bsp/n32/libraries/n32_drivers/drv_hwtimer.c
- bsp/n32/libraries/n32_drivers/drv_i2c.c
- bsp/n32/libraries/n32_drivers/drv_rtc.c
- bsp/n32/libraries/n32_drivers/drv_spi.c
- bsp/n32/libraries/n32_drivers/drv_usart.c
- bsp/n32/libraries/n32_drivers/drv_wdt.c
> attach #6166

- bsp/qemu-virt64-aarch64/README.md
- bsp/qemu-virt64-aarch64/README_zh.md
- bsp/qemu-virt64-aarch64/applications/graphic.c
- bsp/qemu-virt64-aarch64/driver/drv_rtc.c
- bsp/qemu-virt64-aarch64/driver/virtio/virtio_gpu.c
- bsp/qemu-virt64-aarch64/driver/virtio/virtio_net.c
- bsp/qemu-virt64-aarch64/driver/virtio/virtio_net.h
[
1.RTC补充硬件alarm功能。
2.VirtIO-GPU修复因cpu乱序执行导致buffer没有正确初始化的问题；添加cursor用例代码。
3.VirtIO-NET修改发送网络包时包分离代码，防止丢失包数据；更新代码到VirtIO v1.0版本；支持tap模式访问外网。
]
> [bsp/qemu-virt64-aarch64] Update drivers' code

- tools/utils.py
https://github.com/RT-Thread/rt-thread/issues/6143
> 修复 工程include path 重排序问题 #6143 report

- tools/menuconfig.py
[
For developers creating new packages this small change may be handy. They can fork the packages repository and define a envvar,  RTT_PACKAGE_URL, to point to its forked repository.
] …
> allow setting optional url for packages via envvar.

- components/utilities/var_export/var_export.c
- components/utilities/var_export/var_export.h
> [components][var_export] 添加获取长度及二分查找功能

- bsp/raspberry-pi/raspi3-32/cpu/trap.c
[
树莓派3B中的__rtt_ffs接口存在问题，导致寻找最高优先级线程不对。
demo板代码中最高优先级线程main_thread_entry的优先级为10，但是该接口获取highest_ready_priority为9。
启动时优先级为9的线程队列为空，导致代码跑飞报undefined instruction 异常。
修改后已在树莓派3B中验证，rt thread正常运行
]
> [bsp/raspi3-32] fix some bug of funtion '__rt_ffs'

- bsp/simulator/drivers/sdl_fb.c
[
[ISSUE: a lock problem](https://github.com/RT-Thread/rt-thread/issues/5715)
]
> [fix] pthread_mutex_destroy can't work.

- bsp/imxrt/imxrt1170-nxp-evk/applications/main.c
- bsp/imxrt/imxrt1170-nxp-evk/board/MCUX_Config/pin_mux.c
- bsp/imxrt/imxrt1170-nxp-evk/project.uvprojx
- bsp/imxrt/imxrt1170-nxp-evk/xip/SConscript
[
[fix]mimxrt1170 Qspi flash bootup problems by loss of external flash conf and ivt header.
[add]green light instead printf on main.c.
]
> [fix]mimxrt1170 Qspi flash bootup problems

- documentation/doxygen/Doxyfile
- documentation/doxygen/readme.md
> [document] Fix the doxygen file

- components/utilities/ymodem/ymodem.h
[
https://github.com/RT-Thread/rt-thread/issues/4397
]
> [ymodem] move error codes to rym_code to silence warnings

- bsp/stm32/libraries/HAL_Drivers/drv_usart.c
https://github.com/RT-Thread/rt-thread/issues/6106
https://github.com/RT-Thread/rt-thread/issues/4467#issuecomment-850814143
[
]
The following content must not be …
> [stm32][drv_serial] 修复recv_len意外为负（即很大正数）的问题

- bsp/imxrt/imxrt1021-nxp-evk/applications/SConscript
- bsp/imxrt/imxrt1052-atk-commander/applications/SConscript
- bsp/imxrt/imxrt1052-fire-pro/applications/SConscript
- bsp/imxrt/imxrt1052-nxp-evk/applications/SConscript
- bsp/imxrt/imxrt1052-seeed-ArchMix/applications/SConscript
- bsp/imxrt/imxrt1060-nxp-evk/applications/SConscript
- bsp/imxrt/imxrt1064-nxp-evk/applications/SConscript
- bsp/imxrt/imxrt1170-nxp-evk/applications/SConscript
[
当前的Sconsript脚本只能编译applications文件夹下面的.c文件，不支持编译目录下的子文件夹。
]
> [bsp][imxrt]优化imxrt的BSP下面的applications的Sconsript脚本

- components/libc/compilers/common/cstdlib.c
attach #6229
[
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please …
> [exit] 修复_exit函数条件分支未覆盖所有情况的问题

- bsp/raspberry-pico/board/board.c
> [bsp][raspberry-pi]Fix the issue of inaccurate system tick.

- bsp/gd32450z-eval/drivers/drv_usart.c
https://club.rt-thread.org/ask/question/32d3a440402902f7.html
[
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be …
> [gd32] 修复串口引脚定义错误的问题

- tools/building.py
[
自动生成的`.sconsign.dblite`，在不同python版本下，并不兼容。
因此建议`scons -c`时一并清理掉，不然会报错，且不容易看出问题。
`ValueError : unsupported pickle protocol: 4/5`
]
> [tools] remove .sconsign.dblite when scons clean.

- .gitignore
- bsp/stm32/stm32l475-atk-pandora/README.md
- components/drivers/spi/sfud/inc/sfud_flash_def.h
[
stm32l475-atk-pandora 有些版本的外部flash的型号是NM25Q128EVB,但不支持.
这个pr实现NM25Q128EVB的支持.
* 编译环境: gcc 10.2.1
* 硬件: 正点原子 STM32L4 Pandora (带NM25Q128EVB)
]
> [bsp]stm32l475-atk-pandora support NM25Q128EVB

- components/drivers/spi/sfud/inc/sfud_flash_def.h
- components/drivers/spi/sfud/src/sfud.c
https://github.com/armink/SFUD/pull/72
[
] …
> [sfud] 同步上游

- components/drivers/serial/serial_v2.c
由于在旧版本的串口驱动中没有 `transmit` 函数，目前对于使用 V2 驱动调用旧版本驱动设备的情况没有很好的提示，请见：https://github.com/RT-Thread/rt-thread/discussions/6224#discussioncomment-3372398
**目前暂时通过添加 assert 来解决，后续可以考虑更好的解决方式**。 
> add assert for serial v2

- components/drivers/spi/sfud/inc/sfud_flash_def.h
> [sfud] keep macros in order attach #6255

- libcpu/arm/cortex-m7/cpu_cache.c
[
- clean_invalid must be set at the same time then call clean_invalid, or call clean/invalid
- tested on stm32h750-artpi
]
> [libcpu][arm] fix rt_hw_cpu_dcache_ops clean invalid bug

- .github/workflows/action.yml
> ci: restrict rt-thread organization

- bsp/simulator/rtconfig.py
- bsp/stm32/libraries/HAL_Drivers/drv_common.c
- src/kservice.c
> typo in code

- src/scheduler.c
[
refer to [关于时间片调度算法issue的分析与解决]( https://club.rt-thread.org/ask/article/b3b36a52556382b2.html)
之前提的一个 PR #5954, 记得当时群里好像讨论SMP兼容，最后不了了之。
但这个时间片也算一个严重bug，时间片和延时设置不好，会严重影响同优先级任务调度，一直放着也不好。
再基于第2套方案提交一个PR, 改动较小，这个合并了，我把 #5954 关了
测试:
]
> [kernel/schedule] fix the time slice issue

- examples/utest/testcases/kernel/thread_tc.c
> [utestcases] add timeslice_test

- examples/utest/testcases/kernel/thread_tc.c
[
[ci] Test with time slice off by default
]
> [ci] Test with time slice off by default

- components/drivers/include/drivers/serial.h
- components/drivers/include/drivers/serial_v2.h
> 针对 TAMAGAWA 的 Smart-Abs 设备 TS5705N50添加 2.5M 波特率

- components/libc/compilers/armlibc/syscalls.c
> [armlibc] solve the compiling error

- documentation/memory/memory.md
[
Even though the documentation is good, it contains many spelling mistakes, which especially for people for whom English is not a native language, can be confusing to read. I fixed many of these in the documentation file for the memory management functionality of RT-Thread, which I believe is one of the more important parts of the documentation. Most of the fixes are simple - regarding definite/indefinite articles. No code was changed.
]
- …
> More documentation edits and grammar fixes

- documentation/at/at.md
- documentation/device/adc/adc.md
- documentation/device/hwtimer/hwtimer.md
- documentation/device/i2c/i2c.md
- documentation/device/pin/pin.md
- documentation/device/pwm/pwm.md
- documentation/device/rtc/rtc.md
- documentation/device/sensor/sensor.md
[
Even though the documentation is good, it contains many spelling mistakes, which especially for people for whom English is not a native language, can be confusing to read. I fixed many of these in multiple documentation files for the "devices" functionality of RT-Thread. Most of the fixes are simple - regarding definite/indefinite articles. No code was changed.
]
- [ x ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into …
> Documentation edits and fixes for "devices"

- bsp/n32g452xx/Libraries/rt_drivers/drv_can.c
1.完善can驱动中断处理
2.优化can波特率采样率，采样点在75%以上
3.增加新的can驱动宏定义支持，避免编译错误
[
代码已经在N32G45XVL-STB开发板测试，运行稳定
测试代码位置 https://gitee.com/cazure/n32g457vel7-usb2can
]
> [n32g45x] bsp 完善can驱动中断处理

- bsp/at32/libraries/rt_drivers/drv_flash.c
> [fal] PKG_USING_FAL -> RT_USING_FAL

- bsp/essemi/es32f369x/drivers/Kconfig
- bsp/stm32/stm32f072-st-nucleo/board/Kconfig
- bsp/stm32/stm32f103-blue-pill/board/Kconfig
- bsp/stm32/stm32f401-st-nucleo/board/Kconfig
- bsp/stm32/stm32f469-st-disco/board/Kconfig
- bsp/stm32/stm32l475-atk-pandora/board/Kconfig
> [rtduino] remove libraries dependencies

- ChangeLog.md
[
Changelog for RT-ThreadV4.1.1
]
> [update] changelog for RT-Thread_v4.1.1

- libcpu/risc-v/SConscript
- libcpu/risc-v/ch32v3/SConscript
- libcpu/risc-v/ch32v3/context_gcc.S
- libcpu/risc-v/ch32v3/cpuport.c
- libcpu/risc-v/ch32v3/cpuport.h
- libcpu/risc-v/ch32v3/interrupt_gcc.S
> [libcpu]支持risc-v的ch32v3

- src/components.c
- src/idle.c
main线程栈指定对齐字节数
这些变量名称起的太随意了
[
] …
> [kernel] 优化内置线程命名

- .github/workflows/action_tools.yml
- tools/building.py
- tools/iar.py
- tools/keil.py
[
优化了mdk工程的生成逻辑
取消ci对keil和iar生成工程的检查
1.这些工程是否可以生成是BSP可选项，不是每个BSP都支持
2.CI环境中并没有安转IAR和Keil环境，导致直接获取IDE版本失败
]
> [scons] 使用target=mdk5 和 iar时，打印IDE版本号

- bsp/stm32/libraries/HAL_Drivers/drv_usart.c
UART_FLAG_TC 不能在中断里CLEAR;
因为函数 static int stm32_putc(struct rt_serial_device *serial, char c)里发送完成后
while 循环等这个标志退出，中断服务函数CLEAR后，此处进入死循环
[
首次提交PR,STM32 Poll 发送bug修复
]
> bug：STM32 Poll 发送bug修复

- bsp/wch/risc-v/Libraries/ch32_drivers/drv_usart.c
- bsp/wch/risc-v/Libraries/ch32_drivers/drv_usart.h
> [drv_usart]完善ch32的串口驱动。

- include/rtdef.h
- src/Kconfig
4.1.1发布后，已经创建了lts-v4.1.x长期支持版本分支，主线分支转入5.0.0开发
> change version number to v5.0.0

- .gitignore
- bsp/imxrt/libraries/drivers/drv_eth.c
[
修复imxrt除1170之外的BSP网络驱动编译错误
]
> Fix ethernet

- README.md
- README_zh.md
> [readme] 增加贡献者名单

- src/thread.c
`rt_thread_sleep()` 不应该在中断中被调用，因此我里面添加了上下文检查。
> [kernel] 为rt_thread_sleep添加上下文检查

- bsp/cypress/libraries/HAL_Drivers/drv_i2c.c
- bsp/cypress/libraries/HAL_Drivers/uart_config.h
- bsp/cypress/psoc6-cy8cproto-4343w/board/Kconfig
- bsp/renesas/libraries/HAL_Drivers/drv_usart_v2.c
- bsp/renesas/ra2l1-cpk/README.md
[
Fix initialize assertion problem of serial V2
]
> 【renesas】Fix initialize assertion problem of serial V2

- .gitignore
- bsp/imxrt/imxrt1170-nxp-evk/board/Kconfig
- bsp/imxrt/imxrt1170-nxp-evk/board/board.c
- bsp/imxrt/libraries/MIMXRT1170/SConscript
- bsp/imxrt/libraries/drivers/drv_can.c
- bsp/imxrt/libraries/drivers/drv_gpio.c
[
1、消除drv_gpio.c编译警告
2、增加flexcan支持
]
> Support flexcan

- components/drivers/include/drivers/spi.h
- components/drivers/spi/spi_core.c
[
修复 rt_spi_sendrecv16 api 对最高有效位(MSB or LSB)的处理不当造成的一些问题。
]
> [spi]fix some bug for rt_spi_sendrecv16

- bsp/wch/risc-v/Libraries/ch32_drivers/drv_usart.c
- bsp/wch/risc-v/Libraries/ch32_drivers/drv_usart.h
[
问题：CH32V307的串口1外设挂接在APB2桥上，其余串口均挂接在APB1桥上，为保证程序正常运行做出修改。
修改：主要对`struct ch32_uart_hw_config`结构体做了一定修改与适配，修改后的结构体成员名符合要求，调用相应串口，程序运行正常。
]
> 完善CH32V307的串口BSP
