RT-Thread/rt-thread

bsp/lpc178x/drivers/board.c
bsp/lpc408x/applications/board.c
bsp/lpc5410x/applications/board.c
bsp/mb9bf500r/board.c
bsp/xplorer4330/drivers/board.c

SysTick_Config substract one inside the function. So there is no need to
substract one when passing the parameter.

bsp/{cortex-M}: fix the SysTick_Config

---

components/cplusplus/crt_init.c

If there is no SHT$$INIT_ARRAY, calling
$Super$$__cpp_initialize__aeabi_() will fault. At least until Keil5.12
the problem still exists. So we have to initialize the C++ runtime our
own.

crt_init: fix hardfault in Keil toolchain when there is no cpp object

---

components/drivers/src/ringbuffer.c

OXape reports: http://www.rt-thread.org/phpBB3/topic3939.html
driver/ringbuffer: when data length is bigger than space length
for rb, the read_index in rb is not update.
When length > space, update the read_index, the bug can be fix, and
works fine.

[Driver/ringbuffer]: Fix put_force bug

---

bsp/stm32f10x/drivers/usart.c

1、解决 #347 
2、增加 了奇偶校验配置
3、修改 了串口putc()方法，保证在退出putc()方法前，串口缓冲区中的数据会被发送完成。为以后的485总线支持做好准备。

完善 stm32f10x 串口驱动

---

bsp/simulator/drivers/dfs_win32.c

test case
```
int testdir()
{
DIR * dir;
struct dirent * ptr;
int offset = 0, offset_5 = 0, i = 0;
dir = opendir("/");
while ((ptr = readdir(dir))!=NULL)
{
offset = telldir(dir);
if(++i == 5) offset_5 = offset;
rt_kprintf("d_name :%s offset :%d \n", ptr->d_name, offset);
}
seekdir(dir, offset_5);
rt_kprintf("Readdir again!\n");
while ((ptr = readdir(dir))!=NULL)
{
offset = telldir(dir);
rt_kprintf("d_name :%s offset :%d\n", ptr->d_name, offset);
}
closedir(dir);
return 0;
}
```

dfs_win32: add seekdir support, fix #346

---

components/net/freemodbus-v1.6.0/SConscript
components/net/freemodbus-v1.6.0/modbus/functions/mbfunccoils_m.c
components/net/freemodbus-v1.6.0/modbus/functions/mbfuncdisc_m.c
components/net/freemodbus-v1.6.0/modbus/functions/mbfuncholding_m.c
components/net/freemodbus-v1.6.0/modbus/functions/mbfuncinput_m.c
components/net/freemodbus-v1.6.0/modbus/include/mb_m.h
components/net/freemodbus-v1.6.0/modbus/include/mbconfig.h
components/net/freemodbus-v1.6.0/modbus/include/mbport.h
components/net/freemodbus-v1.6.0/modbus/mb_m.c
components/net/freemodbus-v1.6.0/modbus/rtu/mbrtu_m.c
components/net/freemodbus-v1.6.0/port/port.c
components/net/freemodbus-v1.6.0/port/port.h
components/net/freemodbus-v1.6.0/port/portevent.c
components/net/freemodbus-v1.6.0/port/portevent_m.c
components/net/freemodbus-v1.6.0/port/portserial.c
components/net/freemodbus-v1.6.0/port/portserial_m.c
components/net/freemodbus-v1.6.0/port/porttimer.c
components/net/freemodbus-v1.6.0/port/porttimer_m.c
components/net/freemodbus-v1.6.0/port/user_mb_app.c
components/net/freemodbus-v1.6.0/port/user_mb_app.h
components/net/freemodbus-v1.6.0/port/user_mb_app_m.c

1、更新FreeModbus主机及从机代码至最新版本；
2、移植采用RTT自带的设备驱动框架，降低在RTT平台上的移植难度。

更新FreeModbus主机及从机

---

libcpu/arm/cortex-m3/context_rvds.S

..\..\libcpu\arm\cortex-m3\context_rvds.S(207):  
warning: A1581W: Added 2 bytes of padding at address 0xd6

Fix compile warning

---

tools/building.py

The global variables in the building.py are totally a pile of shit.

building: PrepareBuilding forgot to declare BuildOptions as global

---

components/drivers/include/drivers/serial.h
include/rtdef.h

Maybe it is the best place to define these macros

mv device ctl cmd macros from serial.h to rtdef.h

---

components/drivers/serial/serial.c

correct rx_fifo init size error

---

components/drivers/src/SConscript

Remove dataqueue/pipe if not enable RT_USING_HEAP, supply the missing `not`.

[DeviceDriver] Fix inverted logic on SConscript

---

bsp/stm32f0x/drivers/usart.c
bsp/stm32f40x/drivers/usart.c

According to STM32 Manual, the USART RXNE flag will be clear automatically after
read to the USART_DR register[1], so the call to USART_ClearITPendingBit is
unnecessary.
[1]: See RM0090 Reference Manual p.992, Bit 5

[DeviceDriver] stm32: Remove explicity clear of RXNE flag

---

src/memheap.c

This will ease the debugging of double-free bug.

memheap: check the USED bit in rt_memheap_free

---

bsp/stm32f10x/drivers/gpio.c

correct stm32f10x pin64 define error

---

bsp/stm32f20x/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F2xx/system_stm32f2xx.c
bsp/stm32f40x/Libraries/CMSIS/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c

原来的PLL_M被定义为固定值25，当晶振不是25Mhz时，会出现主频与预设值不对应的。

update stm32f2/f4: fixed PLL_M define.

---

components/net/lwip_dhcpd/dhcp_server.c

Since it use "netif_find" function, the num variable in netif_find() will return meaningless value when you are using "e0" , eventually it will return NULL for struct netif. This patch was used to solve this problem.

The problem of finding ethernet interface

---

libcpu/arm/am335x/mmu.c

Since the 16 domains are configured as the client domains in
mmu_setttbase(), a Permission fault is generated if the XN bit
(Execute-never) is set in the short-descriptor translation table
(for section and supersection). This leads to the booting failure
when enabling MMU for beagleboard bsp. Here is log:
----------------------------------------------------------------
SD/MMC found on device 0
reading uEnv.txt
117 bytes read in 3 ms (38.1 KiB/s)
Loaded environment from uEnv.txt
Importing environment from mmc ...
Running uenvcmd ...
reading rtthread.bin
162624 bytes read in 24 ms (6.5 MiB/s)
\## Starting application at 0x80200000 ...
----------------------------------------------------------------
This commit removes the XN bit configuration in the section of the
short-descriptor …

[libcpu][am335x] Fix the booting failure when enabling MMU

---

libcpu/arm/cortex-m0/context_rvds.S
libcpu/arm/cortex-m3/context_rvds.S
libcpu/arm/cortex-m4/context_rvds.S

fixed assembly warnings.

---

src/SConscript

when the macro of RT_USING_COMPONENTS_INIT is not open ,then remove the source of components.c  from the project.

when the macro of RT_USING_COMPONENTS_INIT is not open ,then remove the source of components.c  from the project.

---

bsp/stm32f10x/drivers/bxcan.c

把RCC_APB2PeriphClockCmd移到stm32_bxcan_init里。
更改前：如果bxcan1晚于bxcan2打开，则bxcan2不能正常工作。
更改后：上述情况下bxcan2能正常工作。由于bxcan2与bxcan1共享512字节滤波设置寄存器，故bxcan2使用时需始终把bxcan1的PeriphClock开启。

correct bxcan init error

---

tools/keil.py

update scons MDK5 project script: clean old groups.

---

components/drivers/can/can.c

fixed rt_can_close issues.

---

src/kservice.c

in rt_console_set_device, open new device first and get the new device to _console_device.
我在编写程序时，在device驱动中打印log，但是使用rt_kprintf时，如果_console_device存在非空，那就执行驱动的write函数，但是这是device还没有初始化成功，但是已经提前给_console_device赋值，导致了程序无故fault，以上述修改可避开这样的矛盾。

open and then get the new device

---

components/libc/dlib/sys/types.h

For using pthread with IAR tool chain

[libc][dlib] Add missing definition of mode_t

---

bsp/stm32f7-disco/drivers/board.c
bsp/stm32f7-disco/drivers/drv_mpu.c

1. Fixed the bug that MPU init function was called 2 times.

[bsp][stm32f746g-disco] Fix MPU init bug.

---

bsp/stm32f40x/Libraries/SConscript

fixed bug: 'scons --target=iar -s' output iar project missing startup code, and link file
修复scons生成IAR工程中没有startup code和链接文件，导致工程中断异常和Finsh无法工作

include iar startup code

---

components/dfs/filesystems/romfs/dfs_romfs.c

比如实际目录为abcde，msh执行 cd abc也能执行成功，判断名称时存在bug

修正romfs在输入的目录名称比实际的名称短时存在的判断错误

---

src/ipc.c

when we don't care which event raised, we can pass a null "recved".

allow parameter "recved" can be null in function "rt_event_recv"

---

components/cplusplus/SConscript
components/finsh/shell.c

finsh: 
rootcause: When set finsh echo = 0, now, still print '\n'. No echo mode check when print '\n'.
solution: Add echo mode check when print '\n'
CPP:
rootcause: When do not use RT_USE_LIBC, cpp support can not compile and link, due to Scons script add RT_USE_LIBC depends. But cpp support can work without RT_LIBC.
solution: Remove that depends.

finsh: change no echo mode. cpp: remove RT_USE_LIBC depends

---

bsp/lpc176x/rtconfig.h

解决因为缺少RT_DFS_ELM_CODE_PAGE 导致scons无法正确配置工程文件系统代码页问题。

add RT_DFS_ELM_CODE_PAGE

---

tools/building.py

Example "rtconfig.h" content:
...
//#define BOARD_USING_LED
#if defined(BOARD_USING_LED)
#define RT_USING_RTGUI
#endif
...
- Before patching, RTGUI module will be built although not intend to do so.
- After patching, RTGUI module will not be built.

SCons PreProcessor patch: Stop processing "#define" in false condition

---

bsp/stm32f10x/applications/SConscript
bsp/stm32f10x/drivers/SConscript
bsp/stm32f10x/drivers/bxcan.c
bsp/stm32f10x/rtconfig.h

temporarily disable canapp initialization.

fix initialization error in bsp/stm32f10x

---

bsp/stm32f10x/applications/application.c

finsh_set_device is not needed since version 1.2.0

remove function finsh_set_device in application.c in bsp/stm32f10x

---

bsp/stm32f10x/applications/canapp.c
bsp/stm32f10x/drivers/SConscript
bsp/stm32f10x/drivers/bxcan.c
bsp/stm32f10x/rtconfig.h
components/drivers/misc/pin.c

enum CANBAUD was changed in components/drivers/include/drivers/can.h ,
which causes array index out of bound in bsp/stm32f10x/drivers/bxcan.c
temporarily remove RT_CAN_USING_BUS_HOOK, because there are some bugs in
bsp/stm32f10x/applications/canapp.c  function can_bus_hook

fix can baud rate config error in bsp/stm32f10x  fix #597

---

components/finsh/cmd.c

list_thread 主要美化的以下 3 个方面
- 1、增加了自适应 `线程名列` 列宽功能，解决了之前线程名超过 8 个字节后，线程名列信息无法保证对齐的问题；
- 2、优先级内容修改为 10 进制，便于识读；
- 3、最大已用的 stack 信息采用占用线程 stack 总容量的 **百分比** 来表示，更加直观。
美化前：
```
msh >
msh >ps
thread  pri  status      sp     stack size max used   left tick  error
-------- ---- ------- ---------- ---------- ---------- ---------- ---
gcp disp 0x0a suspend 0x00000558 0x00000800 0x00000558 0x0000000a 000
gcp disp 0x0a suspend 0x00000558 0x00000800 0x00000558 0x0000000a 000
gcp disp 0x0a suspend 0x00000558 0x00000800 0x00000558 0x0000000a 000
gcp_req_cmd_job2 0x0a suspend 0x00000094 0x00000400 0x00000154 0x00000005 000
gcp_req_cmd_job1 0x0a suspend 0x00000094 0x00000400 0x0000015c 0x00000002 000
gcp_req_cmd_job0 0x0a suspend 0x00000094 0x00000400 0x00000154 0xffffff0d 000
pid_control 0x07 suspend …
```

[finsh] Beautify all list object information command.

---

bsp/ls1bdev/applications/startup.c
bsp/ls1cdev/applications/startup.c
libcpu/mips/loongson_1b/cache.c
libcpu/mips/loongson_1c/cache.c

现象：
通过pmon加载rtthread.elf，经常会出现pmon的异常打印，导致rtthread加载失败。
原因：
安装异常处理程序后没有刷新cache，且网口收到数据产生中断，导致打开中断后立即进入PMON中断服务程序。

flush cache after exception code install

---

bsp/stm32f107/drivers/stm32_eth.c
bsp/stm32f20x/Drivers/stm32f2_eth.c
bsp/stm32f40x/drivers/stm32f4xx_eth.c
bsp/stm32f40x/rtconfig.h

disable stm32 EMAC hardware checksum.

---

components/drivers/spi/SConscript
components/drivers/spi/sfud/LICENSE
components/drivers/spi/sfud/README.md
components/drivers/spi/sfud/inc/sfud.h
components/drivers/spi/sfud/inc/sfud_cfg.h
components/drivers/spi/sfud/inc/sfud_def.h
components/drivers/spi/sfud/inc/sfud_flash_def.h
components/drivers/spi/sfud/src/sfud.c
components/drivers/spi/sfud/src/sfud_sfdp.c
components/drivers/spi/spi_flash.h
components/drivers/spi/spi_flash_sfud.c
components/drivers/spi/spi_flash_sfud.h

[**SFUD** 是一款使用 JEDEC SFDP 标准的串行 (SPI) Flash 通用驱动库](https://github.com/armink/SFUD) ，将 SFUD 引入后，使得 RTT 可以驱动 **更多型号的 SPI Flash**  。同时使用该驱动支持多 Flash 对象实例， 能够让用户 **同时驱动多片 SPI Flash** 。主要使用方法如下：
在 `rtconfig.h` 可增加如下配置信息，每个配置的功能详见 [`rt-thread/components/drivers/spi/sfud/inc/sfud_cfg.h`](https://github.com/armink/rt-thread/blob/master/components/drivers/spi/sfud/inc/sfud_cfg.h)
```C
#define RT_USING_SFUD                      //必选
#define RT_DEBUG_SFUD                  1   //可选
#define RT_SFUD_USING_SFDP                 //可选
#define RT_SFUD_USING_FLASH_INFO_TABLE     //可选
```
以往的方式只需输入 SPI Flash 的设备名称及对应的 SPI 设备名称即可
```C
w25qxx_init("flash", "spi10");
dfs_mount("flash", "/", "elm", 0, 0);
```
现在使用方法也类似，只不过初始化成功后会返回 SPI flash 对象，这是一个动态 SPI flash 对象，支持对该 SPI flash 设备的删除。
```C
static …
```

增加使用 SFUD 库作为 SPI Flash 设备的芯片级驱动

---

components/drivers/include/rtdevice.h
components/drivers/src/dataqueue.c

- 1、在 push 过程中，线程等待超时后，没有对 `queue->waiting_lwm` 标志清零，这导致接下来的 pop 操作发生全局中断无法恢复使能的问题；
- 2、push 和 pop 中对 data buffer 索引计算方式兼容性不好，部分 size 大小的场景下，计算出来的索引是错误的。下面是设定 dataqueue 长度为 10 ，使用之前的 `&mask` （mask = size -1）方式和新修改的 `%size` 方式进行 push 和 pop 操作，对实际计算出来的 索引值 结果的对比：
```
msh >dq push
queue->put_index & mask:0
queue->put_index % size:0
msh >dq push
queue->put_index & mask:1
queue->put_index % size:1
msh >dq push
queue->put_index & mask:0
queue->put_index % size:2
msh >dq push
queue->put_index & mask:1
queue->put_index % size:3
msh >dq push
queue->put_index & mask:0
queue->put_index % size:4
msh >dq push
queue->put_index & mask:1
queue->put_index % size:5
msh >dq push
queue->put_index & mask:0
queue->put_index % size:6
msh >dq push
queue->put_index & mask:1
queue->put_index % size:7
msh >dq push …
```

修复 dataqueue 的两处 Bug

---

components/finsh/shell.c
components/finsh/shell.h

在我们产品中，为了便于产品售后调试跟踪，在产品在出货时，Finsh 往往也是开启的，这就会有一定的安全风险。所以增加 Finsh 密码验证功能，效果如下图
**功能说明** ：
- 1、使用前需开启 `FINSH_USING_AUTH` 宏
- 2、默认密码 **`rtthread`** ，可以通过定义 `FINSH_DEFAULT_PASSWORD` 宏来修改默认密码
- 3、提供 `finsh_set_password(pw)` 及 `finsh_get_password()` 这两个接口，便于用户在系统启动后动态修改 Finsh 密码。配合 [EasyFlash](https://github.com/armink/EasyFlash) 将密码作为参数来存储，可轻松实现密码修改及掉电保存功能。

[finsh]添加密码验证功能，增强系统输入安全性

---

bsp/lpc408x/drivers/drv_lpccan.c
bsp/stm32f10x/drivers/bxcan.c

CAN中断进入和离开时需分别调用
rt_interrupt_enter();
rt_interrupt_leave();

Fix can.irq.enter.exit.irq

---

components/drivers/spi/SConscript
components/drivers/spi/spi_flash_w25qxx_mtd.c
components/drivers/spi/spi_flash_w25qxx_mtd.h

增加 W25 FLASH驱动，注册为MTD 设备类，任意位置读写，适用于spiffs contiki/cfs...

添加 w25 mtd设备驱动

---

bsp/beaglebone/uboot_cmd.txt

When use u-boot or other tools to load rtthread.bin, change the load address 0x802000000 according to your link address!

add /bsp/beaglebone/uboot_cmd.txt file

---

bsp/stm32f10x/drivers/usart.c

发送中断模式下，发送完成应该禁发送中断，不是禁接收中断，上次添加发送中断模式时，引进的错误，这里更正一下

correct stm32f10x txisr error

---

bsp/stm32f10x/drivers/usart.c
bsp/stm32f40x/drivers/usart.c
components/drivers/serial/serial.c

之前的驱动在数据接收压力极大的条件下，可能会导致缓冲区错误。

增强串口 DMA 接收驱动的可靠性

---

components/dfs/filesystems/elmfat/dfs_elm.c

rt_time_t / time_t different from fat time format.

fix fattime different from elmfat definition

---

components/drivers/sdio/sdio.c

1.修正sdio_irq_wakeup函数中的bug:关sdio中断前添加判断条件"if (host->flags & MMCSD_SUP_SDIO_IRQ)"，防止当sdio host->flags无"MMCSD_SUP_SDIO_IRQ"项时出错。
2.修正sdio_unregister_driver函数的bug：注释掉语句"rt_list_insert_after(&sdio_drivers, &sd->list);",否则不能正确卸载sdio驱动，而且会进入硬件错误中断。

修正sdio驱动框架的一些bug

---

bsp/stm32f429-apollo/drivers/board.c

修正stm32fxx的flash向量基地址: 0x00000000 -> 0x08000000

correct stm32f4xx flash vector table base location

---

bsp/stm32f10x/drivers/usart.c
bsp/stm32f40x/drivers/usart.c
components/drivers/include/drivers/serial.h
components/drivers/serial/serial.c

- 1、修复了 STM32F10X 及 STM32F4XX BSP 中串口接收 DMA 驱动，在首次接收数据并一次性填满 FIFO 会导致数据丢失的 Bug；
- 2、在 rt_serial_rx_fifo 中增加了满标识，使得 FIFO 可以存储与缓冲区大小一致的数据（之前会少一个）。并在串口接收 DMA 驱动实现该功能。

Fix uart rx dma

---

components/libc/newlib/libc.c

修正pthread_system_init函数重复运行使信号量“psem”被重复初始化并导致list_sem陷入死循环的问题，

	modified:   components/libc/newlib/libc.c

---

bsp/stm32f10x/drivers/bxcan.c

fix bsp/stm32f10x/drivers/bxcan.c “inline” bug on iar

[bsp] fix bxcan.c inline bug

---

bsp/ls1cdev/rtconfig.py

使用龙芯官方推出的那个用于编译linux的交叉编译工具链来编译RT-Thread会报错，
可以使用RT-Thread官方推荐那个

在龙芯1c的编译配置脚本“rtconfig.py”中增加“交叉编译工具链的说明”

---

bsp/lpc824/applications/application.c
bsp/lpc824/drivers/board.c

- update core clock before configure systick
- add led task to easy confirm kernel is running
==================================
忘记调用 systemcoreclockupdate()函数， 导致systick中断频率太慢。

[bsp] update core clock and add led task

---

components/net/lwip-2.0.2/src/arch/sys_arch.c
components/net/lwip-2.0.2/src/netif/ethernetif.c

在 lwip 2.0.2 中，当未插入网线时对设备开机，存在 link 状态显示不正确的 Bug。

[LWIP] Fix lwip 2.0.2 link status problem.

---

bsp/stm32f10x/drivers/bxcan.c

Fix a CAN interrupt number macro definition bug for STM32F10X_LD,STM32F10X_MD and STM32F10X_XL series.
Prevent compilation errors in bxcan.c when using STM32F10X_LD_VL,STM32F10X_MD_VL,STM32F10X_HD_VL incorrectly choose to use the RT_USING_CAN.

[bsp] Fix a CAN interrupt number macro definition bug for STM32F10X_LD,STM32F10X_MD and STM32F10X_XL series.

---

src/mem.c

Free the old memory when new size is 0 in `rt_realloc`.

[Kernel] Fix rt_realloc issue when new size is 0.

---

components/net/lwip-2.0.2/SConscript
components/net/lwip-2.0.2/apps/tftp_server.c
components/net/lwip-2.0.2/src/apps/tftp/tftp_server.c

- 1、修复了 LWIP 2.0.2 中 TFTP 服务器传输文件名可能乱码的 Bug
- 2、在 LWIP 2.0.2 中增加适配 RTT 的 TFTP 服务器 app

Fix lwip 2.0.2 TFTP server

---

bsp/stm32f20x/stm32_rom.icf
libcpu/arm/cortex-m0/context_gcc.S
libcpu/arm/cortex-m0/context_iar.S
libcpu/arm/cortex-m0/context_rvds.S
libcpu/arm/cortex-m3/context_gcc.S
libcpu/arm/cortex-m3/context_iar.S
libcpu/arm/cortex-m3/context_rvds.S
libcpu/arm/cortex-m4/context_gcc.S
libcpu/arm/cortex-m4/context_iar.S
libcpu/arm/cortex-m4/context_rvds.S
libcpu/arm/cortex-m7/context_gcc.S
libcpu/arm/cortex-m7/context_iar.S
libcpu/arm/cortex-m7/context_rvds.S

1. 部分芯片或bootloader启动后，fualt没开。
2. F2的IAR链接脚本没有把HEAP放最后。

Update cortex m port

---

bsp/x86/Makefile
bsp/x86/applications/application.c
bsp/x86/drivers/console.c
bsp/x86/rtconfig.h
bsp/x86/rtconfig.py
bsp/x86/src/extract.sh
bsp/x86/src/hello.c
bsp/x86/src/stdio.h
bsp/x86/x86_ram.lds
components/libc/libdl/dlopen.c
src/module.c
src/module.h

1. upddate kernel module to support i386
2. update libdl to support open *.so by absolute path
3. new test case bsp/x86/src/hello.c to test i386 module feature
Signed-off-by: parai <parai@foxmail.com>

x86: bring up share object module on i386 machine

---

bsp/stm32f40x/drivers/usart.c

STM32F4系列UART在初始化的时候，如果GPIO_AF放到GPIO_INIT后边，系统复位后，串口会向外发送一个字节的数据，通常是0x00。将GPIO_AF放到GPIO_INIT前边可以避开这个问题。

修改了GPIO_Configuration

---

components/drivers/can/can.c
components/drivers/include/drivers/can.h

Because completion can only suspend one thread and muti-thread may suspend when hardware can not send can msg, so we use change completion to sem here!

[Components]drivers can change txcompletion to sem

---

components/finsh/shell.c

当 RT_DEBUG 未启用时，Finsh 的密码验证功能可能会失效。 thx @AubrCool

[Finsh] Fix finsh password auth not valid when RT_DEBUG is not define

---

libcpu/arm/cortex-m0/context_gcc.S
libcpu/arm/cortex-m0/context_iar.S
libcpu/arm/cortex-m0/context_rvds.S

cortex-m0 没有 `CPSIE   F` 指令。
异常处理一直是打开状态。

update libcpu: cortex-m0 fault handlers always enable.

---

bsp/ls1cdev/applications/startup.c
bsp/ls1cdev/drivers/board.c
bsp/ls1cdev/rtconfig.h
libcpu/mips/loongson_1c/stackframe_fpu.h

增加硬浮点FPU的配置项和修改异常向量间隔

---

bsp/stm32f429-apollo/drivers/drv_sdio_sd.c

在使用device_test("sd0")测试SD卡驱动时, 发现超过2G的SD会测试失败, 提示the end sector failed. 将读写操作接口的sector地址变量扩大为64位后, 测试驱动正常

修改SD卡驱动无法读写超过2G sector地址的数据

---

src/KConfig

和一些使用这个宏的components起了冲突，无法编译通过。

[错误]：RT_DEBUG_INIT不能是bool型

---

examples/test/device_test.c

1. 该问题是打开设备后, 出错或者成功后没有关闭设备而导致.

修复无法重复使用finsh命令device_test进行驱动测试

---

components/net/lwip-2.0.2/src/include/lwip/arch.h

Fix the lwIP 2.0.2 IAR compile error when the `RT_LWIP_USING_RT_MEM` macro is not defined.

[lwIP] Fix the lwIP 2.0.2 IAR compile error

---

bsp/ls1cdev/drivers/net/synopGMAC_network_interface.h

清理编译告警和错误。编译告警和错误的原因是删除了头文件“components.h”

---

components/finsh/shell.c

bug 复现
- 上次输入命令 `send 10`
- 当前输入命令 `send 1`
- 新命令未被加入到历史中

[Finsh] Fix an auto complete history bug.

---

components/net/lwip-2.0.2/src/netif/ethernetif.c

[lwip]判定eth_rx是否为空,为空不执行。

---

tools/menuconfig.py

Fix config line split error when config line contains more then one equal marks.

[tools]menuconfig.py. Fix config line split error.

---

bsp/gd32450z-eval/applications/rtgui_demo.c
bsp/stm32f429-apollo/applications/rtgui_demo.c
bsp/stm32f429_armfly/applications/rtgui_demo.c

<rtgui/dc_hw.h> 已经合并到<rtgui/dc_.h>

[bsp] remove old head file include for RTGUI

---

bsp/stm32f10x_HAL/drivers/drv_usart.c

[BSP]STM32F10x_HAL fix uart3

---

bsp/ls1cdev/drivers/drv_gpio.c
bsp/ls1cdev/drivers/drv_gpio.h
bsp/ls1cdev/rtconfig.h

将龙芯1c库中的gpio接口重新封装为RTT统一标准的pin接口

[BSP][ls1c]新增PIN接口

---

components/drivers/include/drivers/usb_common.h
components/drivers/include/drivers/usb_device.h
components/drivers/usb/usbdevice/class/winusb.c
components/drivers/usb/usbdevice/class/winusb.h
components/drivers/usb/usbdevice/core/core.c

协议栈增加允许class在windows环境下枚举时向系统注册附加属性。并在winusb class中提供范例（注册GUID信息）详细信息参见MicroSoft文档 《Extended Properties OS Feature Descriptor Specification》
https://technet.microsoft.com/zh-cn/library/ff537430

[Components][Drivers][USB]WinUSB And Core update

---

components/net/lwip-2.0.2/src/arch/sys_arch.c
components/net/lwip-2.0.2/src/netif/ethernetif.c

取消 INIT_PREV_EXPORT(eth_system_device_init);
由 lwip_system_init 自动调用 eth_system_device_init_private
同时留空 eth_system_device_init 以兼容旧的代码。

[LWIP] make sure lwip initialization order.

---

components/net/KConfig
components/net/lwip-2.0.2/SConscript
components/net/lwip-2.0.2/src/arch/sys_arch.c
components/net/lwip-2.0.2/src/lwipopts.h
components/net/lwip-2.0.2/src/netif/ethernetif.c

1. Kcondig中添加 RT_USING_LWIP_IPV6 选项
2. 使能 IPV6后，默认生成一个 link-local address
3. 支持ND (Neighbor Discovery)自动分配地址
4. 开启IPV6不影响原来IPV4和网络驱动接口。
5. 使用IPV6功能，需要网络驱动做好多播方面的处理。

[LWIP] update LWIP 2.0.2: support IPV6.

---

bsp/qemu-vexpress-a9/rtconfig.py

on ubuntu, use g++ will add an additional linkflag "-lstdc++" and this will result link failed.

[bsp] better use gcc to link instead of g++

---

components/libc/compilers/newlib/libc.c

以前是#if defined(RT_USING_DFS) 
修改成#if defined(RT_USING_DFS) & defined(RT_USING_DFS_DEVFS)
解决使用 dfs时组件初始化卡死

龙芯1C使用的libc初始化添加了dev的定义条件

---

components/dfs/filesystems/net/netinet/in.h

in components/dfs/filesystems/net/netinet/in.h, add IN6_IS_ADDR_MULTICAST support

[dfs] add IN6_IS_ADDR_MULTICAST support

---

components/drivers/usb/usbdevice/class/hid.c

修复一个 bug 该bug曾导致在设备不断电但主机重新枚举设备的情况下会导致内存泄漏并无法接收数据

[Components][Drivers][USB]fix memory leak

---

components/drivers/usb/usbdevice/class/cdc_vcom.c

1:修复cdc_vcom命令处理错误，SetLineCoding命令用于设置一些vcom参数，在此处判定vcom连接状态不合适，因通过SetControlLineState命令wValue字段最低位进行判断。

修复cdc_vcom命令处理错误

---

libcpu/arm/cortex-m4/context_gcc.S
libcpu/arm/cortex-m4/context_iar.S
libcpu/arm/cortex-m4/context_rvds.S
libcpu/arm/cortex-m7/context_gcc.S
libcpu/arm/cortex-m7/context_iar.S
libcpu/arm/cortex-m7/context_rvds.S

线程时，更新目标线程的FPU FPCA标致位的时机不合理，当不需要切换时，可能会引起目标线程寄存器错乱。
相关讨论详见 issus #1196

[libcpu]: fixed #1196 FPU FPCA issue.

---

bsp/imxrt1052-evk/drivers/usart.c

修复uart配置的bug，错误的停止位会导致硬件同时接收多个数据出错。

[bsp] fix uart driver bug

---

src/components.c

没用使用RT_USING_HEAP宏时，components.c文件第211行会报警告，增加一条语句用于消除此警告

没用使用RT_USING_HEAP宏时，增加一条语句用于消除此警告

---

bsp/stm32f10x/drivers/gpio.c

In function **stm32_pin_irq_enable**, missing **GPIO_EXTILineConfig** may cause that program enters interrupt handler forever. So, the following statement is necessary.
` GPIO_EXTILineConfig(index->port_source, index->pin_source);
`

stm32f10x enters external interrupt handler forever

---

bsp/v2m-mps2/README.md
bsp/v2m-mps2/drivers/drv_uart.c
bsp/v2m-mps2/project.uvoptx

将uart驱动改成使用serial方式，是为了可以打开RT_USING_POSIX选项，原来的实现并不支持POSXI方式的getchar。
- 更新uart驱动
- readme修复一些错误

[bsp] update uart driver and fixed typo

---

bsp/stm32f10x/project.ewp
bsp/stm32f10x/project.uvproj
bsp/stm32f10x/project.uvprojx

更新MDK4/MDK5/IAR工程。
IAR工程手动移除了_DLIB_THREAD_SUPPORT选项，避免在新的IAR版本编译不过问题。

[bsp][stm32f10x] update projects

---

bsp/lpc824/rtconfig.h

[bsp][lpc824] fixed error: incomplete type is not allowed

---

bsp/tm4c129x/libraries/SConscript
components/libc/compilers/minilibc/stdint.h

Add missing C99 definition of int/uint_least/fast8/16/32/64_t.
Remove int/uint_fast8/16/32_t definition in tm4c129x BSP driver library's Sconscript.

[components][mini-libc] Add missing C99 definition

---

bsp/imxrt1052-evk/drivers/drv_pin.c
bsp/imxrt1052-evk/drivers/drv_pin.h

更新如下:
1. 修复GPIO5_0~2管脚复用调用错误(错误情况会影响SDRAM正常工作)。
2. 添加中断模式，支持上升沿、下降沿、双边沿、高电平、低电平触发中断模式。
3. 移除C99特性。

[BSP] fix pin drive bug and add interrupt mode. | 修复PIN驱动BUG并添加中断模式.

---

bsp/v2m-mps2/rtconfig.py

在env里面会默认把RTT_CC设置为gcc。
仅仅支持keil的bsp就没必要从环境变量获取编译器类型了。

[bsp][v2m-mps2] fix "scons --target=mdk5" error

---

bsp/imxrt1052-evk/Kconfig
bsp/imxrt1052-evk/drivers/SConscript
bsp/imxrt1052-evk/drivers/drv_i2c.c
bsp/imxrt1052-evk/drivers/drv_i2c.h

1. 添加硬件i2c.
1. 增加menuconfig中的图形选项,用户可以通过选项,配置硬件i2c的分频数,自由配置4路i2c分别为 硬件i2c 或者 模拟i2c .不受只能同时配置一种硬件或模拟模式的限制.
1. 测试 过程: 分三组测试mpu6050模块,每组4路i2c. 第一组:全部为硬件i2c.第二组:两路硬件,两路模拟.第三组:全部为模拟i2c.以上测试通过.

[bsp][imxrt1052] add hardware i2c

---

bsp/sam7x/drivers/SConscript
tools/building.py

统一转换为相对路径后，再严格判断。
之前的版本无法区别   sd.c 和  test/sd.c

update scons script: strict SrcRemove() match rule.

---

bsp/imxrt1052-evk/drivers/drv_i2c.c

修复每次传给 LPI2C_MasterReceive 的总是 msg[0] 的问题。

Fix imxrt1052-evk  rt_i2c_transfer bug

---

bsp/imxrt1052-evk/Kconfig
bsp/imxrt1052-evk/drivers/drv_i2c.c
bsp/imxrt1052-evk/drivers/drv_pin.c
bsp/imxrt1052-evk/rtconfig.h

1.drv_pin.c中
1. SION位置1.
1. rt1052_pin_read()函数 改为直接从PSR寄存器读取,不再是从DR寄存器读取.
`.....................`
1. 在menuconfig中增加波特率选项. 
1. 移除软件i2c.
1. 修复之前,micropython下i2c无法正确扫描设备的问题.

[BSP][imxrt1052] add baudrate options, Delete simulate i2c . 

---

components/drivers/spi/enc28j60.c
components/drivers/spi/enc28j60.h

ENC28J60的LINK中断，除中断控制寄存EIE外，还受PHY里面的PHIE寄存器控制，需要明确使能。

update enc28j60 driver: ensure enable PHY link changed interrupt.

---

bsp/imxrt1052-evk/Libraries/gcc/MIMXRT1052xxxxx_flexspi_nor.ld
bsp/imxrt1052-evk/Libraries/gcc/MIMXRT1052xxxxx_ram.ld
bsp/imxrt1052-evk/Libraries/gcc/MIMXRT1052xxxxx_sdram.ld
bsp/imxrt1052-evk/Libraries/gcc/MIMXRT1052xxxxx_sdram_txt.ld

When using gcc compiler and configuring RT-Thread with "Support C++ features" (RT_USING_CPLUSPLUS), the final link step will report errors as below:
LINK rtthread-imxrt.elf
build\kernel\components\cplusplus\crt_init.o: In function 'cplusplus_system_init':
crt_init.c:(.text.cplusplus_system_init+0x18): undefined reference to '__ctors_start__'
crt_init.c:(.text.cplusplus_system_init+0x1c): undefined reference to '__ctors_end__'
collect2.exe: error: ld returned 1 exit status
scons: *** [rtthread-imxrt.elf] Error 1
According to the RT-Thread C++ rules defined in 'crt_init.c', we should supply these symbols in link script files.

[bsp][imxrt1052]update ctors/dtors sections to fix link error with RT_USING_CPLUSPLUS

---

bsp/imxrt1052-evk/drivers/drv_sdio.c

1.格式化代码.
2.优化SDIO接口稳定性和速度: 将SDIO时钟树中分频数增大, 提高内部时钟的稳定性, 同时SDIO速度提高到25M. 并且通过USB拷贝12M MP3文件测试, 多次拷贝数据稳定.

[BSP][RT1050] improve sdio stability and speed. | 优化SDIO接口稳定性和速度.

---

components/libc/compilers/armlibc/stubs.c

统一定义 time() 到 time.c 中
https://github.com/RT-Thread/rt-thread/blob/a00cdcd7506489ad986d2b684b126fce6323349b/components/libc/compilers/armlibc/time.c#L40

[libc/armlibc] Remove time() on stubs.c.

---

bsp/tm4c129x/tm4c_rom.icf

Fix last commit error. Modify .icf IAR Link file, move block RTT_INIT_FUNC to flash region.

[BSP] TM4C129X: Fix IAR compile errors.

---

bsp/qemu-vexpress-a9/cpu/start_gcc.S

[bsp][qemu]更改中断栈大小为2048

---

components/net/lwip-1.4.1/src/api/sockets.c

[lwIP] Fix lwip 1.4.1 assert when using DFS_NET.

---

components/drivers/wlan/wlan_cmd.c

[components/drivers/wlan] remove duplicate configuration in `wlan_cmd.c`, this configuration is included in the `dhcp_server.c`

[components/drivers/wlan] remove duplicate configuration

---

bsp/stm32f429-apollo/drivers/drv_sdio_sd.c
bsp/stm32f429-apollo/drivers/drv_spi.c
bsp/stm32f429-apollo/drivers/drv_spi.h

关闭 SPI DMA，降低 SDIO 初始速度，提高 BSP 的可靠性

Fix apollo429

---

components/drivers/cputime/cputime_cortexm.c

to be able debug trace bit  before use DWT.

---

bsp/lpc54608-LPCXpresso/drivers/drv_emac.c
bsp/lpc54608-LPCXpresso/drivers/drv_sd.c

1. The issue concerns sdmmc library bug (I finally solved) in SD_Init() in the file sdmmc/src/fsl_sd.c:SD_SelectBusTiming()
calls SD_SwitchFunction() which sets block size to 64bytes (512bits).Therefore SD_SetBlockSize(card, FSL_SDMMC_DEFAULT_BLOCK_SIZE)
should be called again before SD_Init() exits.
2. The issue is wrong variable in drv_emac.c:lpc_emac_tx(), and the wrong data length of send packet
to cause the send failure.
Signed-off-by: zheng-chow <sernia.zhou@foxmail.com>

Fix the SD Card and EMAC issue:

---

components/drivers/Kconfig
components/drivers/include/drivers/rt_drv_pwm.h
components/drivers/include/rtdevice.h
components/drivers/misc/SConscript
components/drivers/misc/_pwm.c
components/drivers/misc/rt_drv_pwm.c

PWM(脉冲宽度调制)
简单的 PWM 主要两个参数：
* 频率
* 占空比
一般用在背光灯等要求不高的地方。
高级特性不太适合通用框架
* 同步模式
* 死区控制
1. 为省空间，所有的PWM通道合并为一个设备： RT_Device_Class_Miscellaneous
2. 使用pos参数作为通道号
3. 支持以纳秒为单位设置周期（频率）和占空比。
```
struct rt_pwm_configuration
{
rt_uint32_t channel; /* 0-n */
rt_uint32_t period; /* unit:ns 1ns~4.29s:1Ghz~0.23hz */
rt_uint32_t pulse;  /* unit:ns (pulse<=period) */
};
```
之所以单位没有使用赫兹，是因为占空比尽可能不使用浮点数。
所以统一使用纳秒比较好。
新定义了3条命令，用于控制PWM。
```
#define PWM_CMD_ENABLE      (128 + 0)	//使能PWM
#define PWM_CMD_SET         (128 + 1)	//设置PWM参数
#define PWM_CMD_GET         (128 + 2)	//获取PWM参数
```
```
rt_size_t rt_device_write(rt_device_t dev,
rt_off_t    pos,
const void *buffer,
rt_size_t   size);
```
映射通用的 rt_device_write 到 PWM_CMD_SET 命令。
rt_device_write 只用来配置PWM的占空比。
pos参数为通道编号，每次只能配置一个通道。
传入的size单位为字节，大小为 …

[DeviceDrivers] add pwm driver framework.

---

bsp/ls1cdev/drivers/drv_spi.c
bsp/ls1cdev/libraries/ls1c_spi.c

[bsp/ls1cdev]SPI0添加CS0支持，移除drv_spi.c中的msd_init。SPI00可用于注册NORFLASH驱动

---

bsp/stm32f40x/drivers/stm32f4_rtc.c

get_week获取的值是0-6.而stm32f4xx_rtc.h中IS_RTC_WEEKDAY中判断的有效值是1-7.当设置日期是周日时，会有问题。

解决get_week的有效值与IS_RTC_WEEKDAY判断有效值不一致的问题。

---

components/drivers/wlan/wlan_cmd.c

```
download firmware done!                                                   
SSID                      MAC             rssi   chn    rate 
------------------------------- -----------------     ----   ---    ------
Zero                            ec:88:8f:88:aa:9a      -37     6    300000
AI-THINKER_23C19D               b6:e6:2d:23:c1:9d      -60     9    54000 
ubnt                            00:15:6d:20:91:68      -69     7    300000
NEO-shanghai-ap2                58:66:ba:a1:ee:71      -61    11    54000 
KVIP                            70:65:82:3b:75:43      -70    11    72200 
Xiaomi_3F                       78:11:dc:1b:9f:cc      -71    11    144400
WQ1                             88:25:93:94:51:54      -65    13    144400
YST2016                         88:25:93:c6:67:d1      -70 …
```

[components][drivers]wlan打印ap信息更加友好

---

include/rtservice.h

增加这两个 API 使得 slist 的迭代循环可以改为如下方式
```C
for (node = rt_slist_first(rlist); node; node = rt_slist_next(node))
{
...
}
```

[rtservice] Add `rt_slist_first` and `rt_slist_next` API to slist.

---

components/drivers/wlan/wlan_dev.c

[drivers/wlan] Fix the problem that the password is empty

[drivers/wlan] Fix the problem that the password is empty

---

bsp/stm32f10x-HAL/drivers/board.c
bsp/stm32f10x-HAL/drivers/stm32f1xx_hal_conf.h

[bsp][stm32f10x] Fix compile error when configuring HSI | 修复当配置为HSI内部时钟做为时钟源时编译错误问题.

[bsp][stm32f10x] Fix compile error when configuring HSI.

---

bsp/imxrt1052-evk/drivers/drv_pin.c

1. 当首先配置PIN为普通输入输出后, 再修改成中断, 不会出现无法触发中断的问题.

[BSP][RT1050] Improve pin drive stability. | 提高PIN驱动稳定性.

---

include/rtservice.h

Some non-gnu toolchains don't support gnu C extended keyword "typeof", like MDK (if no "gnu" option) and IAR, in this case we can provide list element manipulation macro functions to iterate over the list.

Add list iterators over list elements

---

include/rtthread.h
src/device.c
src/ipc.c
src/memheap.c
src/mempool.c
src/module.c
src/object.c
src/thread.c
src/timer.c

尝试修复 https://github.com/RT-Thread/rt-thread/issues/1550 这个问题。
我的修复思路是： 
在从object里移除的时候， 把object的list的prev和next成员设置为空指针。然后在使用delete/detach/release/take等等API的，对prev和next做空指针检查。

add more assert for object check

---

components/dfs/src/dfs_posix.c

参考 http://pubs.opengroup.org/onlinepubs/7908799/xsh/fcntl.html
避免 F_GETFL 无法获取

[dfs] Fix dfs_file_ioctl return check on fcntl.

---

components/libc/compilers/armlibc/stubs.c

rt_device_write()/rt_console_get_device() need RT_USING_CONSOLE and RT_USING_DEVICE
如果只打开RT_USING_CONSOLE，不打开RT_USING_DEVICE就会编译报错。

[libc] dependence update: 

---

libcpu/arm/cortex-m3/context_rvds.S
libcpu/arm/cortex-m4/context_gcc.S
libcpu/arm/cortex-m4/context_iar.S
libcpu/arm/cortex-m4/context_rvds.S
libcpu/arm/cortex-m4/cpuport.c
libcpu/arm/cortex-m7/context_gcc.S
libcpu/arm/cortex-m7/context_iar.S
libcpu/arm/cortex-m7/context_rvds.S
libcpu/arm/cortex-m7/cpuport.c

1. 修复M3的MDK移植中获取栈错误，fixed #1646 
2. 更新M4和M7的异常处理，同M3一样，支持简单的fault原因追溯。

enhancement hard fault exception handler.

---

tools/keil.py

更新scons脚本，添加对MDK中armcc的版本获取。
输出格式为
```
MDK Plus 5.24/ARM Compiler 5.06 update 5 (build 528)/armcc [4d3621]
```

[Tools] add armcc(MDK) get version support

---

tools/building.py
tools/mkdist.py

使用scons --dist-strip ，而不是scons --dist --strip，因为没法找到合适的办法添加二级参数，可以在help里面显示正确的信息。
scons --dist-strip的工作是：
- 复制BSP目录下的所有文件
- 复制libcpu/ARCH目录下当前BSP可能需要的文件
- 复制compontents/libc/compilers下所有的文件。
- 复制当前程序所有用到RT-Thread目录下的源码（*.c *.h）
- 复制所有源码的相关目录下的SConscript文件
- 复制所有Kconfig文件
- 更新BSP目录下的Sconstruct文件，
- 更新BSP目录下的可能存在的Kconfig文件
- 更新BSP目录下的所有的工程文件（目前支持mdk4/mdk5/iar/vs/vs2012/cdk）
- 打包到dist目录

add scons --dist-strip support

---

bsp/stm32f4xx-HAL/Kconfig
bsp/stm32f4xx-HAL/drivers/SConscript
bsp/stm32f4xx-HAL/drivers/drv_can.c
bsp/stm32f4xx-HAL/drivers/drv_can.h
bsp/stm32f4xx-HAL/drivers/stm32f4xx_hal_conf.h

STM32F4xx HAL的can驱动。没有实现过滤器。基本收发功能正常。抛砖引玉。

[STM32 BSP]CAN driver for stm32f4xx HAL.

---

include/rtdbg.h

- 重定义 dbg_log_line 宏，不再使用 dbg_log ，降低 LOG_X 宏展开时的代码体积
- 增加 LOG_X 宏 API 的日志级别检测功能，低于设定级别日志不仅不输出，同时也会不再展开。进一步降低资源占用

[rtdbg] Optimize footprint for rtdbg log.

---

components/cplusplus/crt_init.c

打开"Support C++ features"后gcc将编译失败,提示_init和_fini重复定义.暂时加入RT_WEAK避开此问题.

修正打开"Support C++ features"后gcc编译失败问题

---

components/dfs/filesystems/uffs/dfs_uffs.c

修正参数类型不匹配问题. uint32_t为unsigned int, 而rt_uint32_t为unsigned long
注: armclang编译器报错

dfs_uffs_getdents函数声明问题修正

---

components/libc/compilers/armlibc/mem_std.c

armlibc下malloc/realloc/calloc函数声明同一更正

---

components/libc/compilers/armlibc/stubs.c

_sys_command_string返回值错误,no support时cmd为随机数据,可能导致c库初始化时在此函数返回处死循环或跑飞.

修正_sys_command_string返回值

---

bsp/stm32f10x/drivers/bxcan.c

correct error when alloc filter to fifo1

[bsp] stm32f10x correct fifo1 alloc error

---

components/dfs/filesystems/ramfs/dfs_ramfs.c

将ramfs 的 memheap 创建完毕后被删除的标志位重新赋值

[components][dfs][ramfs] add RT_Object_Class_MemHeap flag for ramfs->memheap

---

bsp/allwinner_tina/drivers/spi/drv_spi.c

To avoid 'unknown type name' error, replace uint8_t and uint16_t to
rt_uint8_t and rt_uint16_t respectively.

uint8_t/uint16_t -> rt_uint8_t/rt_uint16_t

---

libcpu/ia32/__udivsi3.c
libcpu/ia32/__umodsi3.c

already uint32_t is defined at components/libc/compilers/minilibc/stdint.h.
there is two ways to solve, using <stdint.h>/uint32_t pair or
<rtthread.h>/rt_uint32_t pair.
I choose former because this code belongs to C compiler, not RT-Thread system.

avoid to conflicting types for 'uint32_t' error.

---

components/drivers/cputime/cputime.c
components/drivers/usb/usbdevice/class/cdc_vcom.c
components/drivers/usb/usbhost/core/hub.c

armclang支持PR拆分出来的改动: 修正drivers下,armclang编译时的警告或错误
注:vcom_tx_thread_entry下, if(!res & CDC_TX_HAS_DATE)应为bug.

修正drivers下一处bug,并修正armclang编译时该目录下的错误或警告

---

libcpu/arm/am335x/mmu.c
libcpu/arm/am335x/mmu.h

1) mmu_disable_dcache/mmu_enable_dcache等, 应使用rt_cpu_xxx相关函数,否则会跑飞. armcc并没有提供rt_cpu_xxx对应汇编代码,先删除
2) mmu_setmtt抽取为函数mmu_setmtts,并增加RT_WEAK.mmu_setmtts此处作为示例函数.实际用户板子可在bsp中重新实现该函数.可在rt_components_board_init函数前调用rt_hw_mmu_init
3) 增加mmu.h文件

修正am335x中mmu问题

---

bsp/stm32f10x-HAL/applications/main.c
bsp/stm32f10x-HAL/drivers/board.c
bsp/stm32f10x-HAL/drivers/board.h
bsp/stm32f10x-HAL/drivers/drv_gpio.c
bsp/stm32f10x-HAL/drivers/drv_gpio.h
bsp/stm32f10x-HAL/drivers/drv_sdcard.c
bsp/stm32f10x-HAL/drivers/drv_sdcard.h
bsp/stm32f10x-HAL/drivers/drv_spi.c
bsp/stm32f10x-HAL/drivers/drv_spi.h
bsp/stm32f10x-HAL/drivers/drv_usart.c
bsp/stm32f10x-HAL/drivers/drv_usart.h
bsp/stm32f10x-HAL/drivers/drv_usb.c
bsp/stm32f10x-HAL/drivers/drv_usb.h
bsp/stm32f10x-HAL/project.uvprojx
bsp/stm32f10x-HAL/template.uvprojx

 [BSP][STM32F1xx-HAL] 修复配置为HSE时 当HSE不起振 会assert

---

components/net/at/at_socket/at_socket.c

使用ec20做coap的时候发现的，rtthread的sal层框架，在使用at指令集设备时UDP通讯的时候，数据接受不上来，debug下来发现UDP不用调用connect方法，所以接受的回调函数没有和事件绑定，回调函数设置后就没问题了。
在at_socket.c的at_sendto函数中udp分支下添加
/* set AT socket receive data callback function */
at_dev_ops->at_set_event_cb(AT_SOCKET_EVT_RECV, at_recv_notice_cb);
at_dev_ops->at_set_event_cb(AT_SOCKET_EVT_CLOSED, at_closed_notice_cb);

sal框架，使用at设备，UDP通讯数据无法获得

---

components/net/at/at_socket/at_socket.c
components/net/at/at_socket/at_socket.h

fix at socket issue

---

components/libc/compilers/dlib/time.c

修复iar dlib时间映射函数的函数声明，适应不同版本的iar

修复iar dlib时间映射函数的函数声明，适应不同版本的iar

---

src/mem.c

减低了 malloc/free 中的 ISR 检查范围，使得其内部一些 ISR 无关代码也可以在 ISR 中执行。
该 pr 可以解决，在 GCC 环境下，中断中无法使用 `loacltime_r` 的问题。

[kernel][mem] Improve some ISR check range.

---

bsp/stm32f10x-HAL/Kconfig
bsp/stm32f10x-HAL/drivers/SConscript
bsp/stm32f10x-HAL/drivers/drv_pwm.c

添加pwm驱动
参考:stm32f4xx-HAL drv_pwm.c
测试代码:
```
/* pwm test cmd */
static int pwm_test(int argc, char **argv)
{
char *pwmc = argv[1];
rt_device_t pwmd = rt_device_find(argv[1]);
struct rt_pwm_configuration cfg =
{
.channel = 0,  /* 0-n */
.period = 100, /* unit:ns 1ns~4.29s:1Ghz~0.23hz */
.pulse = 50    /* unit:ns (pulse<=period) */
};
for (int i = 1; i < 5; i++)
{
cfg.channel = i;
rt_device_control(pwmd, PWM_CMD_SET, &cfg);
rt_device_control(pwmd, PWM_CMD_ENABLE, &cfg);
}
}
MSH_CMD_EXPORT(pwm_test, pwm_test pwm1); 
```
测试结果:pwm1的ch3 ch4 无输出,已暂时将相应代码屏蔽

[driver][pwm] add pwm driver.

---

components/utilities/ulog/syslog/syslog.c
components/utilities/ulog/ulog.c
components/utilities/ulog/ulog.h
components/utilities/ulog/ulog_def.h
include/rtdbg.h

增强了 ulog 对于 rtdbg 的兼容性。当 ulog 启用后，rtdbg 会依赖于 ulog 完成日志的输出转换。
应用层无需做任何修改，即可调用 rtdbg 的 API 来使用 ulog 。

Add ulog compatible with rtdbg.

---

bsp/x86/Makefile
bsp/x86/applications/application.c
bsp/x86/drivers/board.c
components/libc/libdl/arch/x86.c

There is no problem to create hello.mo with default compiler on
Debian-9.5/amd64.
But building hello.mo with i386-elf-gcc (5.5.0) cross compiler on
OpenBSD-6.3/amd64, undefined reference to 'rt_kprintf' error occurs.
To avoid this error, "compile and link" process needs to be divided to
simply "compile" and "link".
On Debian-9.5, both previous and current method produces same hello.mo.
We have to improve disk image creation (Linux dependent),
this is a future homework.

change hello.mo building process, compile and link separately

---

bsp/stm32f4xx-HAL/drivers/drv_usbh.c

修复STM32F4-Hal bsp USB主机驱动的一个bug

修复STM32F4-Hal bsp USB主机驱动的一个bug

---

components/drivers/audio/audio_pipe.c
components/drivers/misc/rt_drv_pwm.c

1. fixed audio_pipe.c compile error.
2. update pwm driver: support RT_USING_DEVICE_OPS.

[DeviceDriver] update RT_USING_DEVICE_OPS.

---

src/Kconfig

The external package can use this number on Kconfig version choice, when need version depend. 
For example: 
```
prompt "Version"
default PKG_USING_AT_DEVICE_LATEST_VERSION
help
Select the at_device version
if AT_SW_VERSION_NUM >= 0x10200
config PKG_USING_AT_DEVICE_V140
bool "v1.4.0"
endif 
if AT_SW_VERSION_NUM = 0x10100
config PKG_USING_AT_DEVICE_V130
bool "v1.3.0"
endif
if (AT_SW_VERSION_NUM >= 0x10000 && AT_SW_VERSION_NUM < 0x10100) || (!AT_SW_VERSION_NUM)
config PKG_USING_AT_DEVICE_V120
bool "v1.2.0"
endif
config PKG_USING_AT_DEVICE_LATEST_VERSION
bool "latest"
endchoice
config PKG_AT_DEVICE_VER
string
default "latest"    if PKG_USING_AT_DEVICE_LATEST_VERSION
default "v1.4.0"    if PKG_USING_AT_DEVICE_V140
default "v1.3.0"    if PKG_USING_AT_DEVICE_V130
default "v1.2.0"    if …
```

Add RTT version number on Kconfig file.

---

bsp/stm32f4xx-HAL/stm32_rom.ld

[STM32F4xx-HAL] Fix link error when enable cmbacktrace package.

---

components/net/at/at_socket/at_socket.c

[net][at] Fix at_recvfrom() select event issue

---

bsp/stm32f107/drivers/usart.c

[BSP]stm32f107 fix usart3

---

bsp/stm32f7-disco/drivers/drv_usart.c

__HAL_UART_CLEAR_FLAG在stm32f7xx_hal_uart.h中不存在，编译会报错

[bsp/stm32f7-disco] 修复串口驱动编译报错

---

bsp/stm32/libraries/HAL_Drivers/config/f4/spi_config.h

spi_config.h中多了 .dma_rx、.dma_tx

修复spi驱动中spi_config一个bug

---

bsp/stm32/libraries/HAL_Drivers/drv_rtc.c
bsp/stm32/libraries/HAL_Drivers/drv_soft_i2c.c

I2C.c文件中I2C2_BUS_CONFIG改为I2C3_BUS_CONFIG。RTC驱动137行多了()

修复I2C和RTC中的粗心BUG

---

components/finsh/cmd.c
src/scheduler.c

对栈顶的位置应该是原程序中ptr = (rt_uint8_t *)thread->stack_addr + thread->stack_size的值- 1，如果不减实际上已经溢出到别的内存区域了

fix some bug when stack grows upward

---

components/drivers/spi/sfud/src/sfud.c

用全局空间换栈空间，当多个任务需要使用sfud时，可以节省内存
例如任务需要使用文件系统，任务栈可以减少

减少sfud对任务栈的占用

---

bsp/stm32f10x-HAL/drivers/drv_i2c.c

STM32F10x-HAL库当中用的是 GPIO_SPEED_FREQ_HIGH
> GPIO_SPEED_HIGH --> GPIO_SPEED_FREQ_HIGH

[driver][i2c] Fix GPIO_SPEED_FREQ_HIGH

---

bsp/stm32h743-nucleo/drivers/board.h
bsp/stm32h743-nucleo/drivers/drv_usart.c
bsp/stm32h743-nucleo/project.uvoptx
bsp/stm32h743-nucleo/project.uvprojx
bsp/stm32h743-nucleo/rtconfig.h

修正HEAP起始地址定义错误问题，加入USART3驱动，并更改使用USART3输出，可以直接通过ST-Link的VCP串口打开msh

 [bsp][stm32h743-nucleo] fix the bug of HEAP_BEGIN define.

---

components/drivers/usb/usbdevice/core/core.c

根据 usb2.0白皮书第292页所述，当只支持Fullspeed的设备收到主机的 get device_qualifier 时应返回错误的请求。原文如下
> If a full-speed only device (with a device descriptor version number equal to 0200H) receives a
> GetDescriptor()
> request for a device_qualifier, it must respond with a request error. The host must not make
> a request for an other_speed_configuration descriptor unless it first successfully retrieves the
> device_qualifier descriptor.

[components][USB][Device][Core]fix the device_qualifier error respond on fullspeed

---

tools/menuconfig.py

这么修改，是因为虽然 .config 没有变化，但与 rtconfig.h 的配置已经不一致。

[tools] menuconfig.py silent 模式的时候，不检查 .config 文件时间戳变化，直接更新 rtconfig.h

---

components/dfs/src/dfs.c
components/libc/compilers/armlibc/stubs.c

This will make vi package work with keil, when RT_USING_POSIX is defined.

Fix stdio fd error when POSIX api is used

---

components/utilities/ulog/ulog.c

修复 ulog_strcpy 函数可能存在的内存写穿风险。（之前在应用层已规避，所以暂无影响）。
@BernardXiong 

[component][ulog] Fix the ulog_strcpy function.

---

components/utilities/ulog/backend/console_be.c

修改 `ulog_console_backend_init` 函数的自动初始化级别，使用与 `ulog_init` 同级别的 `INIT_PREV_EXPORT` 而非 `INIT_COMPONENT_EXPORT`。
这样做的目的是为了组件初始化中的其他模块可以使用 ulog 输出日志。
@BernardXiong @armink 

[components][ulog] fix ulog_console_backend_init auto init level

---

tools/building.py

在Kernel Group中添加BSP的路径，这样不需要在BSP中显式的添加Dir('#')路径。
@BernardXiong 

[tools] Add BSP path into Kernel Group.

---

components/dfs/include/dfs_file.h
components/dfs/src/dfs.c
components/dfs/src/dfs_file.c

Signed-off-by: yangfasheng <yangfasheng@rt-thread.com>
修复文件系统挂载多个设备，并同时在不同设备上同样的相对路径下打开相同文件名的文件时其中一个打开失败的BUG。
@BernardXiong 

update dfs.c  dfs_file.c  dfs_file.h

---

components/dfs/filesystems/romfs/dfs_romfs.h
tools/mkromfs.py

修正mkromfs.py脚本的问题，并移到tools目录中。这个问题主要是当要生成romfs的C代码时，如果遇到空目录或空文件时，生成了空的结构体，导致编译出错。已经在qemu-vexpress-a9上测试通过，但生成bin文件的方式未验证，还需要进行验证。

[DFS][romfs] fix the mkrom issue when file/dir size zero

---

components/lwp/lwp_syscall.h

修正lwP编译时和libc的宏定义冲突。目前在qemu-vexpress-a9上进行测试。

[lwp] Fix compiling warning in lwP.

---

bsp/stm32f4xx-HAL/drivers/drv_can.c
components/drivers/can/can.c

[
由于#2164 PR有部分争议，但关于CAN驱动的修改是完备的，故先行提交。
特别地：
1. 修改系统CAN驱动框架中关闭设备时对于接收和发送handler的处理，如果此处不恢复为空，在下次打开设备后，驱动将无法正常工作。
2. 修改STM32F4xx_hal中CAN驱动，使其在发生OV等异常中断后，能够继续使能其他正常中断。
]

修复CAN驱动部分问题

---

bsp/k210/Kconfig

[
解决了K210 BSP Kconfig文件语法错误，scons --pyconfig可以正常运行。
]

[bsp][k210] Fixed Kconfig file Syntax error.

---

components/finsh/cmd.c
src/scheduler.c
src/thread.c
src/timer.c

在RT-Thread 4.0中，当任务获得CPU进行执行时，已经从READY队列中脱离，并进行运行（如果是多核情况，分别放到不同的核心上进行执行），所以这个时候RUNNING状态已经和原来的READY状态完全独立出来了。所以把RUNNING状态定义成非READY状态，并在shell中也给出相应的状态信息出来。
已经在下述BSP中测试验证：
* K210

[Kernel] Enable RUNNING status in thread.

---

bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f0.c
bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f1.c
bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_l4.c

[bsp][stm32/libraries] 修复 drv_flash_l4.c 驱动中无法写入非8字节对齐的数据的限制，因为 L4 芯片要求 doubleworld 写入，在要求了写入地址是 8 字节对齐后，写入的数据会默认 8 字节对齐。
所有修改已经在 `stm32.stm32l475-atk-pandora` bsp 上得到验证。
同样，在 f0 和 f1 中也移除了 size 对齐限制的相关代码。

[bsp][stm32/libraries] 移除 flash 驱动中 flash write 函数对 size 对齐的限制

---

components/net/lwip-2.0.2/src/arch/include/arch/cc.h

[
解决 lwip 2.02 在未使能 LIBC 的情况下，errno 错误号重复定义的问题；
已在stm32f407-atk-explorer 上编译测试；
]

[lwIP] the errno definition of rt_libc.h is used by default.

---

components/libc/aio/posix_aio.c
components/libc/mmap/posix_mmap.c

修正POSIX AIO中的aio_read_work返回值问题，应该返回读取到的长度；修正mmap中，当addr=0时，会造成0地址数据污染的问题；

Fix libc posix

---

components/drivers/src/ringbuffer.c

[
ringbuffer rb 指针被释放后没有置空，然后直接作为返回值返回，导致非法内存访问。
]

[driver/ringbuffer]illegal access to freed memory

---

components/libc/compilers/armlibc/stubs.c

[
在这个PR中实现了_sys_flen()函数并解决了unistd.h和dirent.h不能同时包含的问题。
`_sys_flen()`函数的文档[请看这里](http://www.keil.com/support/man/docs/armlib/armlib_chr1359122859809.htm)，在KEIL中，若要使用标准库中的`fseek()`函数需要实现`_sys_flen()`。本[实现](https://github.com/gztss/rt-thread/blob/7b5723f84d9b913b3fa892197dc68efcb1085fc8/components/libc/compilers/armlibc/stubs.c#L266)使用POSIX库中的`stat()`函数来获取文件尺寸。
这些改动已经在STM32L4 IOT Board开发板上测试过。
]

实现_sys_flen()函数并解决了unistd.h和dirent.h不能同时包含的问题。

---

bsp/imxrt/Libraries/imxrt1050/drivers/drv_pin.c

1. **修复 gpio 进入中断后，无法清除中断标志的问题**（见 bsp/imxrt/Libraries/imxrt1050/drivers/drv_pin.c 第225行）
2. **修复 gpio 上下拉配置。**（见 bsp/imxrt/Libraries/imxrt1050/drivers/drv_pin.c 第450---478行, 第607---635行）
3. **修复 gpio 配置为中断模式时，无法正确读取引脚状态的问题。**（ 见
bsp/imxrt/Libraries/imxrt1050/drivers/drv_pin.c 第592行，第597行）
**测试情况说明：** 已经在自己画的 1052 板子上测试通过。

[BSP] Fixed imxrt1050 gpio driver | 修复 imxrt1050 gpio 驱动

---

components/net/lwip-2.1.0/src/arch/sys_arch.c
components/net/lwip-2.1.0/src/netif/ethernetif.c

fix lwip2.1.0 port bug
[
fix lwip2.1.0 port bug
test: nuc977 with eth0 on chip.
]

fix lwip2.1.0 port bug

---

bsp/stm32/stm32f103-dofly-lyc8/Kconfig
bsp/stm32/stm32f103-hw100k-ibox/Kconfig
bsp/stm32/stm32f746-st-disco/Kconfig
bsp/stm32/stm32f767-st-nucleo/Kconfig
bsp/stm32/stm32g071-st-nucleo/Kconfig
bsp/stm32/stm32l432-st-nucleo/Kconfig
components/drivers/Kconfig

[
1. fix kconfig syntax error etc. some new stm32 BSP have this problem.
2. add RX buffer size config in kconfig file.
3. the RT_USING_LIBC option  is selected by default in RTC module.
* the above  has tested in qemu-vexpress-a9 BSP.
]

[components/drivers & bsp/stm32]fix kconfig syntax error etc.

---

bsp/x1000/drivers/board_key.c
bsp/x1000/drivers/sfc/drv_sfc_gd25qxx_mtd.c

在第217行中,“(rt_uint32_t*)&keyId”应改为“(rt_ubase_t*)&keyId”。
In line 217, "(rt_uint32_t*)&keyId" should be changed to "(rt_ubase_t*)&keyId".
Signed-off-by: Zhou Yanjie <zhou_yan_jie@163.com>
[
修复编译过程中的警告。
Fix compile-time warnings.
]

BSP: X1000: drivers: board_key.c: 修复编译过程中的警告/Fix compile-time warnings

---

bsp/x1000/drivers/sfc/mtd_nor_partition.c

在第166行中,“rt_size_t length”应改为“rt_uint32_t length”。
在第200行中,“rt_size_t length”应改为“rt_uint32_t length”。
In line 166, "rt_size_t length" should be changed to "rt_uint32_t length".
In line 200, "rt_size_t length" should be changed to "rt_uint32_t length".
Signed-off-by: Zhou Yanjie <zhou_yan_jie@163.com>
[
修复编译过程中的警告。
Fix compile-time warnings。
已在RatCharm板上进行过测试。
Has been tested on the RatCharm board.
]
我在这个拉取/合并请求中已经考虑了 As part of this pull request, …

X1000: mtd_nor_partition.c: 修复编译过程中的警告/Fix compile-time warnings

---

bsp/stm32/libraries/HAL_Drivers/drv_adc.c

[
解决了原函数在单独选择ADC2或ADC3的时候，注册到系统的名字仍是adc1的问题，通过判断当前选的ADC通道，给系统注册不同的名字，即单独选ADC2或ADC3时，注册到系统的名字是adc2或adc3。
在正点原子探索者开发板上进行了测试。
]

完善stm32_adc_init函数

---

components/drivers/spi/spi_flash_sfud.c

[
修复了使用 spi 驱动并打开 SFUD 的 QSPI 模式，调用 sfud_qspi_fast_read_enable 函数会导致断言的问题。
打开 debug 模式后编译通过，并在 stm32F429 上测试通过。
]

[components][driver]修复使用spi驱动在sfud的qspi模式下的断言问题

---

components/libc/pthreads/pthread.c
src/thread.c

When pthread invokes pthread_exit, it just detach self.
test on qemu-vexpress-a9

[ptherad] Fix pthread_exit issue

---

components/net/at/Kconfig

[
由于M5310发送时发送的字节位于CMD命令行里，默认的AT_CMD_MAX_LEN长度太短，满足不了要求
]

增加AT_CMD_MAX_LEN配置

---

components/utilities/ymodem/ymodem.c

[
之前的 ymodem 在握手阶段，在接收到第一个数据为 SOH 或 STX 后，会立即读取后面的所有数据。而有些单片机的串口硬件 fifo 为 128，小于 ymodem 的一帧 133，会导致接受数据不全，ymodem 握手失败，直接退出。
已经在 CY8C6347BZI 和 stm32l475 上测试成功。
]

[components][ymodem]ymodem 握手阶段增加超时重试，防止数据接收不全

---

src/scheduler.c
src/signal.c

Disable interrupt to check thread->stat in _signal_entry to ensure the signal is not lost.
At the same time, remove the disable interrupt return code from rt_thread_handle_sig function.
test on qemu-vexpress-a9.

[Kernel] fix signal issue

---

components/net/sal_socket/socket/net_sockets.c

[
[net][sal_socket] improve closesocke/shutdown error handling
完善 closesocket()/shutdown() 函数在关闭失败的错误处理，添加 socket 关闭错误时 errno 的设置。
在 qemu 环境下测试通过。
]

[net][sal_socket] improve closesocke/shutdown error handling

---

components/finsh/shell.c

[
- Fix issue #2099 
- finsh_getchar invokes getchar, who's return type is int, and return value may < 0, which means error occurred or EOF.
- finsh should handle that situation properly, and inform user about the error.
]

[finsh] change return type of finsh_getchar from ch to int

---

components/finsh/SConscript
src/SConscript

删除 `--keep` 链接配置，因为：
- 相关导出变量及函数已经使用 `RT_USED` 宏修饰，这个选项显得多余
- 同时这个选项会导致 AC6 链接过程产生警告

Delete the unused '--keep' link flag when used RT_USED marco.

---

components/finsh/shell.c

[
The serial getchar will only modify the LSB of ch, the MSB 3 bytes
will be unchanged as the random value on stack, so if MSB 3 bytes
not zero, the value got is wrong.
test on es32f0654 BSP.
]

[components/shell] shell will not work if ch is none zero as random value in stack

---

libcpu/risc-v/k210/interrupt.c
libcpu/risc-v/k210/interrupt_gcc.S

[
添加异常时堆栈信息打印 如下
```bash
Exception:
Store access fault
=================================================================
x1 (ra   : Return address                ) ==> 0x000000008003d1e0
x2 (sp   : Stack pointer                 ) ==> 0x0000000080012606
x3 (gp   : Global pointer                ) ==> 0x0000000000000080
x4 (tp   : Thread pointer                ) ==> 0x00000000801cf054
x5 (t0   : Temporary                     ) ==> 0x00000000deadbeef
x6 (t1   : Temporary                     ) ==> 0x0000000000000080
x7 (t2   : Temporary                     ) ==> 0x000000000000000f
x8 (s0/fp: Save register,frame pointer   ) ==> 0x000000000000d438
x9 (s1   : Save register                 ) ==> 0x000000008003b9d8
x10(a0   : Function argument,return value) ==> 0x0000000080038940
x11(a1   : …
```

[libcpu][k210]add stack info printf

---

include/rtthread.h
src/clock.c

[
修复 rt_tick_from_millisecond 转换较大入参时计算溢出问题
]

【修复】修复ms转tick时计算溢出问题

---

components/drivers/misc/adc.c
components/finsh/shell.c

[
1. add rt_device_ops for adc device 
2. fix finsh_getchar() return wrong value in Big-endian status.
3. 开启设备OPS后编译通过。
]

[components]add rt_device_ops for adc device and fix finsh_getchar() bug.

---

bsp/x1000/drivers/drv_gpio.h
bsp/x1000/drivers/drv_uart.c

在配置引脚路由时需要将未使用的引脚配置为输入模式，
否则有可能同u-boot中的配置产生冲突。
Unused pins need to be configured as input mode when
configuring pin routing, otherwise there may be
conflicts with the configuration in u-boot.
Signed-off-by: Zhou Yanjie <zhouyanjie@zoho.com>
[
在配置引脚路由时需要将未使用的引脚配置为输入模式，
否则有可能同u-boot中的配置产生冲突。
已在RatCharm平台和Realboard平台测试通过。
Unused pins need to be configured as input mode when
configuring pin routing, otherwise there may be
conflicts with the configuration in u-boot. 
Tested on the RatCharm platform and the Realboard platform.
]
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check …

X1000:drv_uart.c:修复引脚路由中的问题/Fix bugs in pin routing

---

src/kservice.c

[
[src/kservice.c] 修复 rt_vsnprintf 格式化后宽度不正确的问题
[src/kservice.c] 修复 rt_vsnprintf 处理 size 和 buf 为 0 极端情况的 bug (对 0 地址写入)
该修改分别在 QEMU 双核模式 和 stm32f407-atk-explorer 下通过 testcases/src/kservice/sprintf/sprintf_tc.c 测试用例的测试
]

[src/kservice.c] 修复 rt_vsnprintf 函数 bug

---

include/rtdef.h
src/Kconfig

加入RT_USING_ARCH_DATA_TYPE配置，可以由bsp来提供基础的数据类型定义，包括
`rt_int8/uint8_t, rt_int16/uint16_t, rt_int32/uint32_t`

[Kernel] Support ARCH data types definitions

---

bsp/qemu-vexpress-a9/drivers/audio/drv_audio.c

对qemu-vexpress-a9 bsp中的audio driver，添加device ops接口；

[BSP] Add device ops for audio driver in qemu-vexpress-a9

---

bsp/tm4c129x/drivers/drv_eth.c

Decide whether to close eth hardware checksum by definition.
[Update drv_eth.c to support hardware or software checksum by LWIP definition. Test in USR-TCP232-ED2 module.]

[bsp][tm4c129x] Update drv_eth.c

---

libcpu/arm/cortex-a/cache.c
libcpu/arm/cortex-a/mmu.h

Add cache invalidate and clean interfaces.
Adjust the default cache type of memory to 'WriteBach with WriteAllocate'.
[
本次提交针对cortex-a结构。
对内存的cache类型进行优化，以提高内存访问效率。
增加对cache操作的rt-thread标准接口。
]

Add standard rt-thread cache interfaces for arm/cortex-a.

---

components/drivers/include/ipc/pipe.h
components/drivers/src/pipe.c

修正未命名管道关闭，pipe未删除的问题；在STM32F411 Nucleo开发板上测试通过；

[libc] Fix the unamed pipe close issue

---

components/libc/libdl/dlmodule.c

修正dlmodule_load函数中在打开文件失败时仍继续进行elf文件magic比较的问题

fix dlmodule_load(): return immediately when open file fail

---

bsp/es32f0334/.config
bsp/es32f0334/README.md
bsp/es32f0334/drivers/Kconfig
bsp/es32f0334/drivers/SConscript
bsp/es32f0334/drivers/drv_rtc.c
bsp/es32f0334/drivers/drv_rtc.h
bsp/es32f0334/libraries/SConscript
bsp/es32f0334/rtconfig.h
bsp/es32f0334/rtconfig.py

[ [bsp/es32f0334] add rtc driver ]

[bsp/es32f0334] add rtc driver

---

src/scheduler.c

Fix the enter/exit critical issue under SMP when scheduler not started. Test on qemu-vexpress-a9

[Kernel] Fix the critical issue under smp

---

components/libc/compilers/newlib/syscalls.c
components/net/lwip-1.4.1/src/arch/include/arch/cc.h
include/libc/libc_errno.h

- [components/net/lwip-1.4.1] 修复不开启 RT_USING_LIBC 时 errno 错误码重复定义的问题
- [components/net/lwip-1.4.1] 移除对 errno.h 的引入
- [include/libc] 在使用 ARMCC 和 IAR 时，移除对 errno.h 的引入。如果引入了 errno.h，errno 就不会被重定向到 _rt_errno。
- [compilers/newlib] 在 syscalls.c 增加 __errno () 函数实现，解决在使用 newlib 编译时 errno 无法重定向到 _rt_errno 的问题
> 基于 stm32.stm32f429-atk-apollo BSP 测试，分别测试了 lwip141 和 lwip202 两个版本。

Fix libc&errno

---

bsp/stm32/libraries/HAL_Drivers/drv_usart.c

fix the error when open uart6 alonely!
修复了单独打开 uart6编译报错的问题。
已在 f411-nucleo板上做了验证。

[bsp][stm32]fix the error when open uart6 alonely!

---

bsp/lpc54114-lite/Libraries/devices/LPC54114/gcc/SConscript
bsp/lpc54114-lite/rtconfig.py

[
This PR fixed a bug of bsp lpc54114-lite. The bug is that the bsp failed to compile by gcc under Linux.
]

[bsp][lpc54114-lite] bug fix: can not compile when using gcc under Linux

---

components/drivers/include/ipc/workqueue.h
components/drivers/src/workqueue.c
components/net/sal_socket/src/sal_socket.c

[
- 改进delayed work功能，支持 work 动态申请和释放
- netdev 组件同步本次改动
- 已在 stm32l4 上测试
]

[components][workqueue]improve delayed work for reinit.

---

include/rtdef.h
src/ipc.c

修改struct rt_semaphore的成员变量value类型为rt_uint32_t，以和初始化时的参数类型一致

修改sem中的value成员变量和赋值参数类型相同

---

components/dfs/src/dfs_fs.c

[
1、当文件系统使能，使用的文件系统没有注册的时候 mkfs 函数会因为数组访问越界出现hardfault。
2、在IMXRT号令者开发板上测试通过。
]

[components/dfs]fix index overflow bug when not filesystem was selected

---

components/net/at/src/at_client.c

[
修复 AT 命令发送超时时错误日志格式为 LOG_D。
该修改已经在 IoT-Board 开发板上测试通过。
]

[net][at] Modify AT commands send timeout error log level

---

components/drivers/can/can.c

在RT_CAN_USING_HDR宏关闭的时候，接收数据大小的计算应该是：已使用链表数*sizeof(struct rt_can_msg)。
[
原程序在can接收到数据后计算接收到的数据大小的时候有误：
/* get rx length */
rx_length = rx_fifo->freenumbers * sizeof(struct rt_can_msg);
这里不应该用空闲链表数来计算，而应该用已使用链表数，应改为：
rx_length = rt_list_len(&rx_fifo->uselist)* sizeof(struct rt_can_msg);
本次提交已经在开发板 野火STM32f429上测试验证。
]

[components][drivers][can] can.c bug修复：

---

bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c

[
BSP/stm32 drv_hwtimer.c 中 stm32f7 使用TIM14  报错 ，TIM14 中断未定义stm32f7 使用哪个中断函数
增加了stm32f7 TIM14 选择
在stm32f767-st-nucleo BSP上进行测试
]

fix drv_timer.c  stm32f7 TIM14 Interrupt

---

components/net/Kconfig
components/net/netdev/src/netdev.c
components/net/sal_socket/src/sal_socket.c

[
- 删除创建 socket 时对默认网卡的判断条件
- 添加默认网卡自动切换功能选项
该提交已经在 IoT-Board 开发板、STM32F429 开发板上验证通过。
]

[net][netdev] Add default netdev automatic change features configuration 

---

bsp/stm32/stm32f767-atk-apollo/board/Kconfig
bsp/stm32/stm32f767-atk-apollo/board/ports/drv_qspi_flash.c

[
修改：
- 该开发板上 SPI FLASH 的名称实际型号为 W25Q256，修改为正确名称
- 修改 QSPI FLASH 的初始化顺序为 device。
已经在 正点原子 F767 开发板上做过测试。
]

[bsp][stm32][atk-f767] 修改 QSPI FLASH 名称以及设备初始化顺序

---

components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c
components/net/sal_socket/src/sal_socket.c

[
- 删除 sal_send/sal_recv 等接口中对于网卡 link_up 状态的判断限制；
- 已在 IoT_Board、STM32F429、QEMU 等环境下测试通过；
]

[net][sal][netdev] Delete the link_up status judgment in the send/recv interface

---

components/net/Kconfig

[
- 修复当没有开启 POSIX 支持时，SAL 组件中 sys/time.h 编译错误问题。
- 已在 QEMU 和 IoT-Board 开发板中测试通过。
]

[net][sal] Fix sys/time.h missing error when not enabled POSIX support

---

components/drivers/serial/serial.c

[
1、使用串口 DMA发送时， rt_serial_open函数缺少对驱动层的配置。
2、在正点原子 IMXRT1052 开发板测试通过。
]

[components/drivers/serial]add low level DMA TX config support.

---

components/net/sal_socket/impl/af_inet_lwip.c

[
- 修复 socketfd 调用 fcntl 函数时，无法使用 F_GETFL/F_SETFL 等宏定义进行操作问题。
- 已在 STM32F429 和 QEMU 中测试通过。
]

[net][sal] Fix fcntl() function not support F_GETFL/F_SETFL operations for socketfd.

---

bsp/amebaz/applications/smartconfig_app.c
components/drivers/wlan/wlan_cfg.c

remove gnu99 code

---

bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f0.c
bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f1.c
bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f4.c
bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f7.c

[
【修复】f0 f1 f4 f7 系列 flash 擦除函数返回值与 fal 接口不匹配的问题。
在 fal 函数 `fal_partition_erase()` 中 flash 擦除返回值是擦除大小，如果不是擦除大小，返回错误值。而在 flash 驱动中擦写成功返回 RT_EOK，这就造成返回值不匹配的问题。
可以通过将 flash 驱动中的擦除成功返回值修改为擦除的字节数来解决这个问题。
已经在正点原子 f767 开发板上测试。
]

[stm32][driver] flash 驱动擦除接口与 fal 不匹配的问题

---

bsp/stm32/libraries/HAL_Drivers/SConscript

开启 BSP_USING_ETH 自动添加 drv_eth.c文件，但是 W5500 不需要这个文件，因此添加依赖关系，解决这个问题。
已在 f411 和 iotboard 做了验证。

[bsp][stm32]修复 w5500 和 drv_eth.c 依赖的问题

---

bsp/stm32/libraries/HAL_Drivers/drv_common.c

[
**问题描述：**
运行时delay时间不准
**问题原因：**
STM32H7系列与STM32F系列时钟架构不同
STM32F系列systick时钟源来自HCLK
STM32H7系列systick时钟源来自SystemCoreClock
**解决方案：**
因此增加SOC_SERIES_STM32H7作为编译条件，如果是STM32H7系列，systick时钟频率从SystemCoreClock获取，如果是STM32F系列，systick时钟频率从HCLK获取
**测试基板：**
野火STM32H435XI PRO开发板，delay正常
]

修改systick初始化，由于STM32H7系列与STM32F系列时钟架构不同导致

---

components/net/at/Kconfig
components/net/at/at_socket/at_socket.c
components/net/at/at_socket/at_socket.h
components/net/at/include/at.h
components/net/at/src/at_client.c
components/net/at/src/at_utils.c

change as follows:
- AT Socket feature supports multi-client connections;
- Fix `send data error, current socket (0) state (0) is error` issue when the socket is closed;
- Improve dirty data processing when AT device hard reset;
- Improve `at_obj_set_urc_table()` fucntion, support for setting multiple URC tables;
- Improve RAW data print format;
[
AT 组件发布 V1.3.0 版本，改动如下：
- AT Socket 功能支持多客户端同时连接；
- 修复当 socket 关闭时可能产生错误 `send data error, current socket (0) state (0) is error`;
- 完善设备硬重启时脏数据处理方式；
- 完善 `at_obj_set_urc_table()` 函数实现方式，支持动态添加多个 URC 列表；
- 完善 RAW 数据打印格式；
该部分改动已经在 stm32f429、stm32l475-atk-pandora 开发板，以及 esp8266、rw007、m26 、mc20、ec20、sim800c 等模块上测试验证通过。
]
The following content must not be …

[net][at] update AT component V1.3.0

---

components/net/at/at_socket/at_socket.c
components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c

[
- 默认网卡不匹配时，使用 at_socket 接口创建 socket 失败问题。
- 已经在stm32f429 开发板上验证问题。
]

[net][at] Fix socket create failed issue when default netdev mismatch.

---

components/drivers/Kconfig
components/drivers/hwcrypto/hw_bignum.c
components/drivers/hwcrypto/hw_bignum.h
components/drivers/hwcrypto/hw_hash.h

[
根据实际使用情况，对大数进行了相应的调整
- 大数对象增加符号成员。
- 将 bignum_alloc 创建大数对象，更换成 bignum_init 初始化大数对象。实际使用中初始化用起来方便
- 移除大数比较功能，这个功能在硬件大数中使用不到
- bignum_set_bin 更名为 bignum_export_bin ，函数表意更加明确
- bignum_import_bin / bignum_export_bin 导入导出均是大端格式。之前是原始数据，意义不大
其他改动
- 更正一处函数命名错误
- 更正一处配置定义错误
上述改动均是实际使用中发现了问题，做出的合理调整。
上述改动在 W60X 及 QEMU 上进行过验证
]

[components][drivers] 硬件大数适应性调整

---

components/drivers/sensors/sensor.c

[
修复锁的获取和释放不对应的错误. 已在 F411-Nucllo 开发板上做了验证。
]

[sensor] Fixed error with mutex_lock take and release not matching.

---

components/drivers/Kconfig
components/drivers/usb/usbdevice/class/ecm.c
components/drivers/usb/usbdevice/class/rndis.c
components/drivers/usb/usbdevice/class/rndis.h

[
修复了 RNDIS 和 ECM的热插拔通信异常问题，添加了通过menuconfig 配置 RNDIS delay linkup的配置选项。问题修复点如下：
RMDIS:
- 当存在通信链接时 热插拔 Windows会发送REMOTE_NDIS_RESET_MSG，该指令未实现，现已实现。
- 当存在通信链接时 热插拔 eth_tx线程大几率会死等传输完成的信号量通知，导致LWIP卡死。
- 当存在通信链接时 热插拔 eth_rx的接收缓冲未重置，导致接收数据异常。
ECM:
- 当存在通信链接时 热插拔 eth_tx线程大几率会死等传输完成的信号量通知，导致LWIP卡死。
- 当存在通信链接时 热插拔 eth_rx的接收缓冲未重置，导致接收数据异常。
现已测试 stm32f469i-discovery / LWIP2.0.2 / Windows 10 1903下 RNDIS，iperf传输过程中反复热插拔后功能正常， delay linkup宏开启前后功能正常，连续热插拔功能正常。
现已测试 stm32f469i-discovery / LWIP2.0.2 / MacOS Mojave 10.14.2下 ECM，iperf传输过程中反复热插拔后功能正常。
另添加部分代码注释，修改注释头Change Logs
]
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please …

 [Components][USB][RNDIS/ECM] fix hotplug and "delay linkup"

---

components/drivers/Kconfig
components/drivers/usb/usbdevice/class/ecm.c
components/drivers/usb/usbdevice/class/rndis.c

[
修复RNDIS和ECM在低数据量时热插拔依然存在一定问题的bug，强制delay linkup 使用软件定时器实现。
感谢 @cris8259 提供的问题复现场景和分析以及稳定性测试，已通过STM32F469I-DISCO和F407的鲁棒性测试。
相关issue
#2724 
] 

 [Components][USB][RNDIS/ECM] 修复热插拔鲁棒性和delay linkup 使用硬件定时器时报错的问题

---

components/drivers/sensors/sensor.c
components/drivers/sensors/sensor_cmd.c

之前 数据缓冲区的内存分配是在 sensor 设备的 init 接口里完成的，而且在设备关闭的时候没有释放这一部分的内存，造成了资源的浪费。因此在 close 的接口中添加 释放内存的操作，为了保证设备的正常工作，将分配内存的操作从只在设备第一次打开的时候才会运行的 init 接口转移到了设备每次打开都会运行的 open 接口，修复了 sensor 设备关闭后内存不释放的问题。已在 F411-Nuclleo 开发板上做了验证。

修复 sensor 设备关闭后分配的内存不释放的问题

---

libcpu/ti-dsp/c28x/context.s

In C28x DSP, interrupt mask status are stored in ST1 register. Both INTM and DBGM is used for masking interrupt, while the latter one is used in real-time debug mode. The origin function rudely enable and disable the interrupt without considering the recent interrupt mask status, which not only may cause  problem in some situation but also is not in conformity with rt-thread design specifications. The new api will fix this bug.
我在这个拉取/合并请求中已经考虑了 …

[libcpu][c28x] Fix bugs of old c28x interrupt api

---

bsp/stm32/libraries/HAL_Drivers/drv_wdt.c

[
利用 stm32fxxx_hal_conf.h 提供的 LSI_VALUE 宏计算看门狗超时时间。
1. 在野火 f103 测试通过。（32KHZ 看门狗时钟源）
2. 在正点原子 f407 测试通过。（40KHZ 看门狗时钟源）
]

[bsp][stm32] drv_wdt.c | 完善 stm32 看门狗驱动

---

bsp/stm32/libraries/HAL_Drivers/drv_common.c

[
修复了STM32bsp无法在mdk仿真器中运行的问题，同时也解决了，当配置为外部晶振，外部晶振不起振时，无法切换至内部时钟源的问题。解决方法是在配置时钟的这段时间中将中断打开以提供systick中断。
]

[bsp][stm32] fix mdk simulator

---

components/net/lwip-1.4.1/src/netif/ethernetif.c
components/net/lwip-2.0.2/src/netif/ethernetif.c
components/net/lwip-2.1.0/src/netif/ethernetif.c
components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c

[
- 在网络相关命令中添加 RT_USING_FINSH  判断；
- 删除网络命令中关中断操作；
- 该测试已经在 QEMU 和 STM32F407 开发板上验证通过。
]

 [net][netdev] Add RT_USING_FINSH control for netdev network commands 

---

libcpu/ti-dsp/c28x/context.s
libcpu/ti-dsp/c28x/cpuport.c

Use a native instruction "Count Sign Bits" to support fast ffs function, then add __rt_ffs support in C28x.
[
增加了C28x对int __rt_ffs(int value)的原生支持，使用C28x指令集中的“CSB(Count Sign Bits)”指令来实现ffs
功能快速计算
]

[libcpu][c28x]Add __rt_ffs support

---

components/net/netdev/src/netdev.c

为 netstat 命令添加非空判断。
[
当 网络模块不支持 netstat 接口时，直接调用会 haldfault，因此添加非空判断。
已在，ali-devilopekit 开发板上做了验证。
]

[netdev] Add a non-null judgment to the netstat command.

---

components/net/lwip-1.4.1/src/netif/ethernetif.c
components/net/lwip-2.0.2/src/netif/ethernetif.c
components/net/lwip-2.1.0/src/netif/ethernetif.c
components/net/lwip_dhcpd/SConscript
components/net/lwip_dhcpd/dhcp_server_raw.c

[net][lwip] Fix set_if() compile error when enable dhcpd fucntion and close finsh
[net][dhcpd] Fix dhcpd fucntion compile error in lwIP 2.1.0.
[
- 修复关闭 Finsh 功能时 DHCP Server 功能编译错误；
- 修复在 lwIP 2.1.0 版本中 DHCP Server 功能编译错误；
- 该问题已经在 STM32F407 开发板中验证。
]

[net][lwip][dhcpd] Fix dhcp server compile error in lwIP 2.1.0

---

bsp/stm32/stm32f103-dofly-M3S/README.md
bsp/stm32/stm32f103-dofly-M3S/applications/nrf24l01_init.c
bsp/stm32/stm32f103-dofly-M3S/board/Kconfig

[
添加对NRF24L01扩展模块的支持
Add support for nRF24L01 extension module
]

[bsp][stm32][f103-dofly-m3s]Add support for nRF24L01 extension module

---

components/drivers/usb/usbdevice/class/hid.c

在第375行中,“uint8_t *data,”应改为“rt_uint8_t *data,”。
In line 375, "uint8_t *data," should be changed to "rt_uint8_t *data,".
Signed-off-by: Zhou Yanjie <zhouyanjie@zoho.com>
[
usb: hid.c: 修复编译过程中的错误/Fix compile-time error.
]

usb: hid.c: 修复编译过程中的错误/Fix compile-time error.

---

components/drivers/serial/serial.c

[
去除串口 DMA 中无法触发的代码判断。
测试方法如下：
在程序中在此位置设置断言，然后使用串口软件发送大量数据到开发板进行测试，经过 30分钟大量数据测试，并没有触发断言，说明该条件在此种测试情况下不能成立。
测试使用的开发板为 atk-407 开发板。
]

[components][serial] 去除串口 DMA 中无法触发的代码判断

---

components/net/sal_socket/impl/af_inet_lwip.c

[
- 修复 select 函数中获取 error 事件之后，error 事件未清空，导致网络出错时（WIFI 断开等） select 一直返回 0 问题；
- 该问题已经在 W60X 和 IoT-Board 开发板上测试验证通过；
]

[net][sal] Fix not clean event issue after poll get the error event in lwIP

---

components/dfs/src/dfs.c

[
MSH command list_fd prints error fd num.
fd num in user program has an offset to dfs internal fds. 
This offset should be added when displayed to the users.
]

[components][dfs] Fix fd error in command list_fd

---

bsp/qemu-vexpress-a9/rtconfig.py

修正编译动态模块时，qemu-vexpress-a9中mac地址文件生成报错的问题。
Fixed the issue of generation MAC address file in qemu-vexpress-a9 BSP when building dynamic module.

[BSP][QEMU-VExress] fix the automac issue under rtthread-apps

---

components/drivers/wlan/wlan_dev.c

[components][drivers][wlan] 修复密码临界值判断错误

---

components/drivers/include/ipc/workqueue.h
components/drivers/src/workqueue.c

[
提交工作的 API 原型: `rt_err_t rt_work_submit(struct rt_work *work, rt_tick_t time);`
一般用户想提交延时工作时，会将第二个参数 填上延时时间。然后进行提交。
但目前这个 API 不能实现这样子工作，如果传递的时普通任务，第二个参数时无意义的。
因此做了一些调整，使 API 的定义上与功能上相切合。
提交无等待的工作，`rt_work_submit(work, 0)`
提交需要等待 100 tick 的工作,  `rt_work_submit(work, 100)`
此次修改兼容之前的代码。
在 qemu 上进行模拟测试，并且是 RTK 平台进行实际运行。
1. 可直接提交延时任务, 无需额外调用延时初始化
2. 修复延时任务 PENDING 时，取消延时任务会递归调用的问题
] …

[components][drivers][ipc] 完善工作队列，增强稳定性

---

bsp/stm32/libraries/HAL_Drivers/drv_adc.c

修复 stm32 bsp 中的 adc 驱动中 RT_ASSERT 使用位置错误问题。

[bsp][stm32] fix RT_ASSERT location error

---

include/libc/libc_fcntl.h

修复了libc头文件的宏定义。之前被错误定义成了十六进制表示，现改为八进制。

	fixup two macro definition in include/libc/libc_fcntl.h

---

include/libc/libc_fcntl.h

改回O_DIRCTORY与O_NONBLOCK,避免O_DIRCOTY(0200000)与newlib中O_BINARY(0x10000)的相同定义

[include][libc]改回O_DIRCTORY与O_NONBLOCK,解决O_DIRCOTY与newlib中O_BINARY的相同定义

---

bsp/stm32/libraries/HAL_Drivers/drv_eth.c
bsp/stm32/stm32f407-atk-explorer/board/ports/phy_reset.c
components/net/lwip-1.4.1/src/arch/sys_arch.c

[
之前提交的pr不符合新的ci脚本要求，现重新提交。
解决问题:
1、修复因LAN8720A以太网芯片重启无效而导致无法进行自动协商，引起网卡初始化失败。
2、修复因LWIP-1.4.1版本中tcp协议栈的初始化顺序有误，导致使用netdev组件时，网卡无法正常注册。
]

[stm32][driver_eth] 修复开启自动协商时出错的 bug 

---

components/net/lwip-1.4.1/src/core/dns.c
components/net/lwip-1.4.1/src/netif/ethernetif.c
components/net/lwip-2.0.2/src/core/dns.c
components/net/lwip-2.0.2/src/netif/ethernetif.c
components/net/lwip-2.1.0/src/core/dns.c
components/net/lwip-2.1.0/src/netif/ethernetif.c
components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c

[
- 多网卡时，修复 DNS 服务器地址设置错误问题
- 完善默认网卡设置处理，同步 netdev 和 lwip 底层默认网卡设置
- 该修改已经在 STM32F407 开发板和 QEMU 环境中验证通过
]

Fix dns server address set error and improve the default netdev set operations

---

bsp/stm32/libraries/HAL_Drivers/drv_can.c
components/drivers/can/can.c

[
fix drv_can.c and can.c bug
verified platform:
stm32f103-fire-arbitrary
stm32f429-atk-apollo
stm32f767-atk-apollo
]

[bsp] [stm32] fix drv_can.c and can.c bug

---

bsp/tms320f28379d/applications/startup.c
bsp/tms320f28379d/drivers/drv_sci.c
libcpu/ti-dsp/c28x/cpuport.c

在 /libcpu/ti-dsp/c28x/context.s 修改相关 API 后，发现会存在在在线程中无法响应中断的问题。经检查发现线程栈初始化的时候，INTM 初始化值有可能被置1，使得新线程中总中断被关闭。修改了线程栈 ST1 寄存器初始化值来避免这个问题。
所有更改在 TMS320F28379D LaunchPad 开发板上测试通过。

[bsp][tms320f28379d] Fix an issue that interrupts are disabled in the thread

---

components/net/at/include/at.h
components/net/at/src/at_cli.c
components/net/at/src/at_server.c

[
- 修复 AT Server 中 "\r\n" 结束符获取后错误处理问题；
- 添加 at_server_send、at_server_recv 接口，用于直接通过串口接收和发送数据；
- 该修改已经在 IoT-Board 开发板上验证。
]

[network][at] Fix the end sign "\r\n" conversion error in AT server，and at_server_send、at_server_recv function

---

components/libc/compilers/common/time.c

[
* 解决的问题:IAR8.1之后出现__localtime32等函数重定义错误
* 解决方法: 根据查询的IAR手册中的描述只重新实现__time32和__time64函数，不再重新实现__localtime32等函数，这些函数采用IAR标准库里面的实现
* 测试平台:
芯片:STM32F103ZET6(使用硬件RTC)
软件:IAR8.4+IAR7.3
]

修复IAR8.1之后出现的__localtime32等重定义错误

---

bsp/qemu-vexpress-a9/rtconfig.py

[
计算 MAC 地址时，会通过一定的运算生成带序号的宏定义，这个宏定义序号为整数。在 Python3 环境下，两整数相除会得到一个小数，导致生成的宏定义不正确，编译报错。
]

[bsp][qemu-vexpress-a9]修复py3环境下编译，整数相除为浮点数的问题

---

components/drivers/sdio/sdio.c

[
当 fun1-7 product 不存在时，需要从卡的结构体中获取。
]

[components][drivers][sdio]修复 SDIO product 为空的问题

---

bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c

[
原因：使用canfestival 包时发现定时只要设置过HWTIMER_MODE_ONESHOT，后面定时器就不能正常工作。
修复stm32 timer_start函数不能设置HWTIMER_MODE_PERIOD模式
修复timer_start函数注释：将TIM2改为TIM更合理
在stm32f429igt6 野火开发板上面验证ok
]

[bsp][stm32][HAL_Drivers]modified stm32 timer_start cant set  HWTIMER_MODE_PERIOD mode

---

bsp/stm32/libraries/HAL_Drivers/drv_rtc.c

1. 在使用 drv_rtc.c 驱动时发现, rt_rtc_config() 并未对 RTC时钟进行使能, 导致程序卡死.
2. 目前已经在 STM32F4 板卡上进行测试 并成功运行

bsp: fix stm32 rtc hal library error.

---

components/drivers/wlan/wlan_mgnt.c

[
WLAN 产生事件时，附加数据没有进行拷贝，已修复。
在 W60X 平台进行测试
]

[components][drivers][wlan] 修复WLAN事件附加数据为空的问题

---

libcpu/arm/cortex-m0/cpuport.c

修复AIRCR地址错误导致M0系列处理器无法成功执行reboot命令。
在ARMv6-M系列的CPU中，AIRCR地址均为0xE000ED0C
参考
https://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0497a/CIHFDJCA.html
https://static.docs.arm.com/ddi0419/e/DDI0419E_armv6m_arm.pdf#page=227

Fix CORTEX-M0 Cannot Execute Reboot

---

components/drivers/spi/sfud/inc/sfud_cfg.h

Fix the compiling warning for SFUD_FLASH_DEVICE_TABLE definition. Test under QEMU VExpress A9 BSP.

[SFUD] Fix the compiling warning for SFUD_FLASH_DEVICE_TABLE definition

---

components/net/Kconfig
components/net/at/Kconfig

拉取/合并请求描述：(PR description)
[
- 移除 SAL 组件开启或者 AT Socket 功能开启后对 LIBC 功能依赖（time 相关功能支持）
- 该提交已经在 STM32F429 + ESP8266 设备上验证通过。
]

[net] Remove libc select in SAL and AT Socket function

---

components/net/netdev/src/netdev.c

[
- 修改 ifconifg 命令显示 IMEI 是时拼写错误；
- 已经在 STM32F407 + EC20 上测试验证问题；
]

[net][netdev] fix IMEI spell mistake in ifconfig command

---

bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c

[
硬件定时器重载寄存器值应减1后填入重载寄存器。
在stm32h7平台上进行了测试。
]

bug fix: the value of timer auto reload should be (val-1)

---

components/finsh/cmd.c
include/rtdef.h
src/mempool.c

在申请内存时被挂起的任务超时后，定时器超时函数是直接把任务从mp挂起队列中摘除，并不会将suspend_thread_count减1，从而造成suspend_thread_count和挂起队列上的实际任务数不一致，最后当挂起队列为空时，后续操作会出错。
修改方式
去除此成员变量suspend_thread_count，rt_mp_free的最后部分修改为判断挂起队列是否为空。此修改会影响到finsh/cmd.c中的list_mempool。

修正rt_mp_free有可能唤醒一个错误任务指针的问题

---

include/rtdef.h
include/rtthread.h
src/ipc.c

[
消息队列发送等待是一个很常用的接口，无论是对接其他接口或是应用开发都会用到。目前如果需要使用等待发送的消息队列，常规做法是 邮箱+内存池的方式。使用起来非常麻烦。所以增加了消息队列发送等待接口。
发送等待的实现，**完全参考**邮箱发送的代码，主要修改如下：
1. 消息队列对象中，添加一个成员，用于保存挂起的线程
2. 发送消息，若超时时间不为0其队列已满，添加线程挂起操作。
3. 接受消息，恢复因队列满而挂起的线程。
4. 消息控制，恢复所有因队列满而挂起的线程。
其他修改：
1. init 和 create 中添加链表的初始化
2. rtthread.h 头文件添加相应的定义。
测试：
1. 在 QEMU 反复上进行单步调试，关键步骤反复确认，确保没有引入其他问题。
2. 多线程无等待消息收发测试，未发现异常。
]

[kernel][ipc] add send wait support for message queue

---

libcpu/arm/cortex-m3/cpuport.c
libcpu/arm/cortex-m4/cpuport.c
libcpu/arm/cortex-m7/cpuport.c

[
MDK 6 编译器环境，__rt_ffs 是函数嵌套汇编的形式，调用时会有压栈处理，所以不能提前 BX 返回。
直接 BX 返回不会有弹栈的处理，会导致 SP 指针不对称，只有压栈没有弹栈。
]

[libcpu][arm] 修复因提前返回,导致sp指针不对称问题

---

components/drivers/i2c/i2c_core.c

rt_i2c_master_send和rt_i2c_master_recv函数设置flag无效
因为未修改前  `msg.flags = flags & RT_I2C_ADDR_10BIT;`，这个操作会把其他设置的标志给清除了
所以函数传进来的flag不会被正确写入到msg.flag，比如外部flag设置RT_I2C_IGNORE_NACK等

fix i2c flags bug

---

src/ipc.c

[
创建 0 长度的消息队列是，会导致内存申请失败，调用 rt_mq_delete 删除对象，代码片段如下：
```
/* allocate message pool */
mq->msg_pool = RT_KERNEL_MALLOC((mq->msg_size + sizeof(struct rt_mq_message)) * mq->max_msgs);
if (mq->msg_pool == RT_NULL)
{
rt_mq_delete(mq);
return RT_NULL;
}
```
由于引入了发送等待链表，该链表初始化的位置很靠后，导致 rt_mq_delete 中操作了一个未初始化的链表，程序宕机。
对比 rt_mb_create 失败中的处理方法，结合 mq 的实际情况。内存申请失败后，使用 `rt_object_delete(&(mq->parent.parent));` 删除对象。从而修复这个问题。
初始化阶段 ，使用 `rt_object_delete` 删除 mq 对象与 rt_mq_delete 等价。并在 qemu 平台测试验证
mq 其他 API 也浏览了一遍，暂没发现问题。
]
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check items one by …

[kernel][ipc] 修复创建0长度的消息队列宕机问题

---

bsp/imxrt/libraries/drivers/drv_hwtimer.c

[
1、在使用RT1050分支bsp的hw_timer驱动时，发现这种周期性形式模式时，定时器只触发一次中断，经debug发现底层定时器模式有误；
2、此修改已经在飞凌OK1052-C开发板上进行了验证；
]

fix bug when use HWTIMER_MODE_PERIOD

---

bsp/stm32/libraries/templates/stm32h7xx/board/linker_scripts/link.icf
bsp/stm32/libraries/templates/stm32h7xx/template.ewp
bsp/stm32/stm32h743-atk-apollo/board/linker_scripts/link.icf
bsp/stm32/stm32h743-atk-apollo/project.ewp
bsp/stm32/stm32h743-atk-apollo/template.ewp
bsp/stm32/stm32h743-st-nucleo/board/linker_scripts/link.icf

[
1,修复stm32h7系列在IAR编译环境下直接下载后无法运行的BUG。
原因是link.icf目录下的的__ICFEDIT_region_RAM_end 地址设置错误。
本次PR修正了 stm32h7xx-templates stm32h743-atk-apollo  stm32h743-st-nucleo.
2,修正IAR工程文件中的芯片型号
]

[bsp][stm32h7]Fix BUG that cannot run in IAR environment

---

bsp/stm32/libraries/HAL_Drivers/drv_gpio.h

When compiling C code containing statements like this:
rt_base_t xx_io_tbl[] =
{
GET_PIN(A,0),
};
the compiler will report:
Warning: #1296-D: extended constant initialiser used
[
]
以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项ch …

fix warning: #1296-D

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

[
当前版本的pwm初始化有BUG，初始化代码执行完后，相应的时钟并没有使能。这是由于`HAL_TIM_Base_Init()`与`HAL_TIM_PWM_Init()`调用顺序不对，导致执行`HAL_TIM_Base_Init()`时，`HAL_TIM_Base_MspInit()`没有被调用，继而导致相应的时钟没被使能。
现在参照STM32CubeMx生成PWM初始化代码，修改了`HAL_TIM_Base_Init()`与`HAL_TIM_PWM_Init()`调用顺序。
已在STM32F429 野火挑战者开发板上测试通过。
]

修复pwm初始化时，相应的时钟没有使能的问题

---

bsp/lpc54114-lite/drivers/drv_i2c.c

[
bsp/lpc54114-lite/drivers/drv_i2c.c 中 master_xfer 函数中 xfer.subaddresssize 值应该为0
已在该板卡上使用ssd1306 oled u8g2 软件包进行过测试
]

The subaddresssize should be 0

---

bsp/stm32/libraries/HAL_Drivers/drv_eth.c
bsp/stm32/libraries/HAL_Drivers/drv_eth.h

[
1. `phy_monitor_thread_entry()`与`eth_phy_isr()`功能重叠，新增加函数`phy_linkchange()`函数以减少代码冗余
2. `phy_speed`中保存与硬件相关的值，但被定义为`uint8_t`，可能导致数据丢失的问题。这个PR通过引入一个与硬件无关的枚举来解决这个问题。
3. 修复`eth_phy_isr()`函数检测不到LINK_UP的问题
4. 修复`eth_phy_isr()`不重新检查网络速率的问题
5. 增加对DP83848C的支持
6. 修复了一处拼写错误，将MSAK改为MASK
已经在STM32F107的开发板上测试，使用DP83848C。
]

优化STM32以太网驱动

---

include/rtdef.h

[
fix the bug that g++ can't expand macro SECTION(".rti_fn."level). 
#define RT_USED \_\_attribute\_\_((used))
#define SECTION(x) \_\_attribute\_\_((section(x)))
typedef int (*init_fn_t)(void);
#define INIT_EXPORT(fn, level) \
RT_USED const init_fn_t \_\_rt_init_##fn SECTION(".rti_fn." level) = fn
static int demo_func(void)
{
return 0;
}
INIT_EXPORT(demo_func, "5");
int main(void)
{
return 0;
}
g++ demo.cpp -E
]
我在这个拉取/合并请求中已经考虑了 As part of this …

修复了g++编译器无法展开自动初始化宏的错误

---

bsp/stm32/libraries/HAL_Drivers/drv_eth.c

1. 中断模式下：以太网驱动不必等待网卡变为UP状态时再退出线程，尽快退出驱动内部线程以节约系统资源。
2. 轮循模式下：以太网驱动不必在自身线程里轮循网卡状态，使用rt_timer进行定时检测并退出当前线程以节约系统资源。
在STM32F107开发板上测试，中断模式和轮循模式均测试通过。

STM32以太网驱动改进

---

components/finsh/cmd.c

[
- 修复 finsh 组件中 Table 补齐功能关闭之后编译失败问题；
- 该问题已经在 STM32L475 开发板上验证测试；
]

[components][finsh] fix compile error when the symbol table feature closed

---

src/thread.c

在修改了任务状态之后且在关中断之前如果任务被中断切走，则有可能再也没有机会切换回当前任务去完成下面把当前任务加入到rt_thread_defunct，当前任务则进行不到回收阶段。

修正rt_thread_delete在特定点被切走后不能回来继续执行的问题

---

bsp/lpc54114-lite/drivers/drv_i2c.c

[
修改了lpc54114-lite bsp中i2c传输函数的实现，解决了i2c总线无法读取的问题，已在该板卡使用wm8904音频解码进行了验证，可以正常工作
]

修改读写逻辑，解决i2c驱动无法读取的问题

---

src/thread.c

多核版本中，rt_thead_exit在调用rt_hw_interrupt_enable()之后及rt_schedule()之间有可能别的核上的idle任务得到了cpu锁，从而运行了释放操作，从而导致原任务在后续运行中出现问题。

修正在多核时，运行在另外核上的idle任务有可能会插在rt_thread_exit调用rt_schedule之前释放其资源的问题

---

components/drivers/Kconfig
components/utilities/Kconfig

pr https://github.com/RT-Thread/rt-thread/pull/2983 合并后，个别组件对于 libc 的无需强依赖，现移除

[components] remove libc dependency in ulog and RTC driver.

---

components/net/sal_socket/socket/net_sockets.c
components/net/sal_socket/src/sal_socket.c

[
在测试modbus-tcp时，发现sal的shut_down函数会把fd关闭并且，释放掉socket。但是，lwip的shut_down并不是关闭socket，导致调用close函数的时候失败。下次在进行创建，再shut_down，多次之后，创建socket就失败了。
]

去除sal shut_down后释放socket导致close失败的问题

---

include/libc/libc_signal.h
include/rtdef.h
include/rthw.h
src/clock.c
src/device.c
src/ipc.c
src/kservice.c
src/signal.c
src/thread.c

cleanup the code and comments in the kernel.

[kernel] code and comments cleanup

---

components/utilities/Kconfig
components/utilities/ymodem/SConscript
components/utilities/ymodem/ry_sy.c
components/utilities/ymodem/ymodem.c

Fix the dependence of file feature in ymodem.

[Util] fix the dependence of file feature in ymodem

---

components/libc/Kconfig
components/libc/libdl/dlmodule.c
components/libc/libdl/dlmodule.h

[
解决dlmodule只能依赖于文件系统的问题，增加dlmodule扩展接口，以适应更多需求。
当产品不带文件系统，或者需要从外部设备（如SPI，UART，WIFI，蓝牙，共享内存，或其他协处理器等）加载动态模块时，当前接口无法满足需求。
为了不改变之前程序接口，在新增加的两个函数接口中引入“加载/释放”回调函数接口，可由外部程序根据需求灵活的修改“加载/释放”方式，以满足对不同应用场景的需求。
该问题已经在RK2108开发版上验证；
]

Fix dlmodule must depends on file system issue

---

components/drivers/spi/sfud/src/sfud.c
src/thread.c

[
`(register_status & SFUD_STATUS_REGISTER_WEL) == 1` 这个表达式始终为假
]

修复不能发现禁止写spi flash失败的情形

---

bsp/stm32/stm32f469-st-disco/board/SConscript

[
修复STM32F469-DISCO在开启QSPI后出现两次引用文件导致编译错误的问题
]

[BSP][STM32][STM32F469-DISCO]fix build error with qspi

---

components/net/lwip-1.4.1/src/arch/sys_arch.c
components/net/lwip-2.0.2/src/arch/sys_arch.c
components/net/lwip-2.1.0/src/arch/sys_arch.c
components/net/lwip-2.1.0/src/netif/ethernetif.c

[
- 修复在一个线程在等待接收数据，另一个线程关闭 socket 引起的断言问题
- 提交上次未提交的 lwIP 2.1.0 里的 hostname 相关代码
- 已在 STM32F407 平台上测试过
]

[net][lwip] fix assert in the sys_arch_mbox_fetch function when close socket

---

components/drivers/audio/audio.c

[
问题：rt-thread/components/drivers/audio.c中_audio_send_replay_frame函数，使用了未初始化变量remain_bytes编译会报warning。
解决方案：remain_bytes初始化为0。
测试： 云知声自研芯片平台验证通过。
]

:bug: fix compile warning, undefine var

---

bsp/stm32/libraries/HAL_Drivers/drv_pm.c

[
- 修复 drv_pm.c 驱动在 run_mode 在低频模式切换到高频模式时会出现死机的问题
- 已在 stm32l475-pandora 平台上测试过
]

[bsp][stm32] fixed a bug that caused system crash by changing the run_mode in low power mode

---

components/utilities/ulog/ulog.c

[
Because the function```void ulog_raw(const char *format, ...); ``` does not output the color information to the log string, there is no need to subtract the string occupied by the color when the output device does not support the color, resulting in A length error
]

[ULOG] fix row size bug for backend which don't suport color

---

bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f7.c

[
问题场景：
移植rt-thread到stm32f767开发板时发现，flash擦除功能不可用，调试发现f7的flash芯片上电默认是single bank mode而rt-thread的驱动只支持duel bank mode 导致获取的sector号错误，flash擦除失败
解决方案：
这个PR将f7的flash驱动修改为仅支持single bank mode，如果用户需要使用duel bank mode需要自己额外修改驱动代码。
测试场景：
stm32f767：上电flash默认为single bank mode模式时进行擦除、写数据、读数据均成功。
]
- [Y] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [Y …

Bugfix drvflashf7

---

bsp/stm32/stm32f769-st-disco/board/Kconfig
bsp/stm32/stm32l4r5-st-nucleo/board/Kconfig

[
在使用 stm32l4r5-st-nucleo BSP 时发现，当执行 menuconfig 并保存 .config 之后，再执行 scons 编译工程时出现“undefined reference to `entry`”错误。经检查发现造成错误的原因是 RT_USING_COMPONENTS_INIT 和 RT_USING_USER_MAIN 配置项缺失导致的。因此在 board/Kconfig 中为该 BSP 增加默认开启这两项。 
已在 ST 官方 NUCLEO-L4R5ZI 开发板上进行测试。
]

[BSP] fix error 'undefined reference to entry' after menuconfig

---

bsp/stm32/libraries/HAL_Drivers/drv_eth.c

…urn value conflicts with function's parameter
[
- fixed drv_eth.c read phy SR register function's return value conflicts with the parameter.
]
- [√] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [√] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [√] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [√] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [√] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [√] 本拉取/合并请求代码是高质量的 …

[stm32/libraries/HAL_Drivers/drv_eth.c]fixed read phy SR register return value

---

bsp/gd32450z-eval/drivers/drv_enet.c

[
源文件主要存在以下问题：
1> rt_hw_gd32_eth_init函数中对MAC初始化完成后并没有修改PHY的连接状态，这会导致测试TCP例程时无法建立TCP链接，应在初始化完成后将PHY的连接状态修改成linkup；
已在GD32450Z-EVAL开发板上测试，修改后没有再出现以上问题。
]
- [√] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [√] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, …

Fix bug for drv_enet.c

---

bsp/raspberry-pi/raspi3-64/Kconfig

raspi-64 BSP is in `RTT_ROOT/bsp/raspberry-pi/raspi-64`, so that the RTT root should be `../../..` instead of `../..` 
Which cause the `scons --menuconfig` failed to find `RT-Thread Kernel` and `RT-Thread Components` two entries. With rtconfig.h generated, compilation will fail.
- [*] …

update Kconfig in raspi-64 bsp  to fix RTT root path

---

bsp/w60x/drivers/board.c
bsp/w60x/drivers/drv_soft_i2c.c

为W60x添加rt_hw_us_delay
[
原因: 因为W60x的BSP缺少rt_hw_us_delay方法,导致online packages中的ds18b20/dht11无法使用
解决的问题: 使得ds18b20/dht11直接被支持
解决方案是: 将drv_soft_i2c的w60x_udelay, 改名为rt_hw_us_delay, 并搬到broad.c
已经在W600 Arduino板进行测试,运行正常
]

fix: 为W60x添加rt_hw_us_delay

---

components/drivers/serial/serial.c

[
由于串口接收缓冲区满了的时候会调用`void _serial_check_buffer_size(void)`，而该函数会使用ulog输出一些Warning信息且该函数是在中断中被调用的。
因此，当串口接收缓冲区满了的时候当若用户没有开启ULOG_USING_ISR_LOG就会造成死机。
目前手头上没有常规的开发板，只在自己的开发板上测试过。
]

修复因串口接收缓冲区满且没有开启ULOG_USING_ISR_LOG而造成的死机问题

---

components/dfs/filesystems/uffs/uffs_nandif.c

[
Note that the word 'wirte' is wrong,
so that 'wirte' should been replaced with 'write'.
]

Fixed typo: 'wirte' in uffs_nandif.c

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

[
- fixed stm32 bsp drv_pwm.c:pwm timer init.
]
- [√] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [√] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [√] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [√] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [√] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [√] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

[STM32/drv_pwm.c]fixed PWM timer init.

---

components/net/at/Kconfig

[
lenght -> length
sfotware -> software
]

Fixed typo: 'lenght'  and 'sfotware' in Kconfig

---

bsp/hifive1/drivers/interrupt.c

[
Note that the symbol ';;' is wrong in 'return (rt_uint32_t)PLIC_claim_interrupt(&g_plic);;',
so that ';;' should been replaced with ';'.
]

[bsp/hifive1]Fixed symbol error in interrupt.c

---

components/finsh/finsh_compiler.c

[
The code just clean the first member of array 'finsh_vm_stack', but it works well in the past years, 
`memset(&finsh_vm_stack[0], 0, sizeof(finsh_vm_stack[0]));`
Is it better to re-code as below, it will be more readable and robust:
` memset(&finsh_vm_stack[0], 0, sizeof(finsh_vm_stack));`
]

[finsh]Fixed minor bug in finsh_compiler.c

---

components/drivers/usb/usbdevice/core/core.c

[
rt_kprintf("alloc memery failed\n"); -> rt_kprintf("alloc memory failed\n");
]

Fixed wrong output information in core.c

---

components/drivers/sdio/block_dev.c
components/drivers/sdio/mmc.c

[
本次PR主要解决以下两个问题：
(1) SD卡整个磁盘格式化成一个分区时无法被使用；
原因：代码中错误增加了一个break条件，导致跳出了整个for循环，后续的mount流程都不执行了，导致SD卡不可用；
解决办法：删除break
(2) 协议栈尝试无效的线宽导致启动时间过长
原因：协议栈export了线宽的cap给驱动或者BSP来配置，所以协议栈应该respect这个规则。
否则无论BSP或者驱动怎么配置，协议栈仍然强制按照841的顺序来测试。这极大消耗了
启动时间，特别是对启动时间很敏感而固件又保存再eMMC中的时候。
以上提交在Rockchip RK2108上基于主线版本测试过。
]

component sdio fix

---

components/drivers/sdio/mmc.c

Currently RTT mmc stack only support Highspeed mode or
blow, which means the max speed should be 52MHz according
to JEDEC spec. Two problems show here:
(1) max_data_rate = (unsigned int)-1. The value of unsigned int
depends on compilers/arch. Moreover, it makes no sense to assume
cpu addressing width with IP clock rate limit.
(1)hs_max_data_rate was set to 200MHz.
So what should BSP drivers do if 52MHz < max_data_rate < 200MHz?
Either it blindly sets a spec-violated clock rate to drive a Highspeed
card, or just adjust the clock rate internally. Both cases are
really bad for practice.
If the card claims to support Highspeed, we set the clock to not
to exceed 52MHz. Otherwise it should be set according to
card->max_data_rate parsed by ext_csd. This patch fixes it as-is,
and also simplify …

component: sdio: fix potential ricky clock setting

---

bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f1.c

support stm32f103vg
[
解决stm32f103vgt6 flash的bank2不能操作的问题，解决方法为bank1和bank2擦除动作分区操作。
在本地stm32f103vgt6进行了测试，运行easyflash的的env和log，通过download分区在线升级测试。
[I/FAL] ==================== FAL partition table ====================
[I/FAL] | name      | flash_dev    |   offset   |    length  |
[I/FAL] -------------------------------------------------------------
[I/FAL] | boot      | onchip_flash | 0x00000000 | 0x00010000 |
[I/FAL] | app       | onchip_flash | 0x00010000 | 0x00050000 |
[I/FAL] | easyflash | onchip_flash | 0x00060000 | 0x00050000 |
[I/FAL] | download  | onchip_flash | 0x000b0000 | 0x00050000 |
[I/FAL] =============================================================
]
The following content must not be …

drv_flash_f1.c support stm32f103vg

---

include/rtthread.h
src/kservice.c

Signed-off-by: lihui <leehui_hrbeu71102@163.com>
[
this change is done for fixing the following warning while I execute "scons" under rt-thread/bsp/hifive1
Note the compiler is [master of riscv-gnu-toolchain](https://github.com/riscv/riscv-gnu-toolchain.git)
rt-thread/src/kservice.c:1391:5: warning: 'strcasecmp' alias between functions of incompatible types 'int(const char *, const char *)' and 'rt_uint32_t(const char *, const char *)' {aka 'unsigned int(const char *, const char *)'} [-Wattribute-alias=]
1391 | int strcasecmp(const char *a, const char *b) __attribute__((weak, alias("rt_strcasecmp")));
|     ^~~~~~~~~~
rt-thread/rt-thread/src/kservice.c:373:13: note: aliased declaration here
373 | rt_uint32_t rt_strcasecmp(const char *a, const char *b)
|             ^~~~~~~~~~~~~
comiled …

fix return type error of rt_strcasecmp: rt_uint32_t to rt_int32_t

---

components/drivers/usb/usbdevice/class/cdc_vcom.c
components/drivers/usb/usbdevice/class/ecm.c
components/drivers/usb/usbhost/core/hub.c

[
Added 'RT_ASSERT' after 'rt_malloc'
`RT_ASSERT(var!= RT_NULL);`
]

[components/usb]Fixed a stack overflow bug

---

src/mem.c

[
修复 rt_realloc 可能造成的系统内存泄漏。
当用户调用 rt_realloc 时，如果申请的new_size的尺寸较小，那么函数内部会截出一个新的空闲内存块，它有可能比 lfree 的值要小，此时应该及时地检查并更新 lfree。
如果不更新，就会造成内存泄漏，除非用户调用 rt_free 释放掉地址更前面的内存块为止。
]

fix bug in rt_realloc of mem.c,  which may cause memory leak

---

components/drivers/usb/usbdevice/class/hid.c

[
USB驱动代码在处理`Get_Report`请求时采用了多余的条件判断，导致composite设备不能被识别。本修改删除该段代码。
]

修复USB不能正常识别composite设备的bug

---

components/libc/termios/posix_termios.c
components/libc/termios/posix_termios.h

问题在rt-thread\components\libc\termios中出现.
1. 为什么PR：
在使用libc时编译无法通过，提示错误为：pid_t未定义.
2. 原因：
pid_t是在sys/types.h中定义 --> termios.h文件中引用了sys/types.h --> posix_termios.h文件未引用termios.h --> 导致编译无法通过
3. 解决办法：
把posix_termios.c文件中的
`#include <termios.h>`
放在posix_termios.h中即可
4. 已在stm32f103-atk-nano板上进行了测试通过

posix_termios.h头文件修改

---

components/drivers/include/ipc/dataqueue.h
components/drivers/src/dataqueue.c

[
[components][dataqueue]add rt_data_queue_deinit
在 stm32f407-atk-explorer 上测试通过
]

[components][dataqueue]add rt_data_queue_deinit

---

components/drivers/serial/serial.c

[
[components][serial]关闭uart时，反初始化tx_dma->data_queue，防止内存泄漏。
在 stm32f407-atk-explorer 上测试通过
]

[components][serial]关闭uart时，反初始化tx_dma->data_queue，防止内存泄漏

---

bsp/ls1bdev/drivers/board.c
bsp/ls1bdev/rtconfig.py
libcpu/mips/common/mips_fpu.h
libcpu/mips/common/mips_regs.h

MIPS: fix FPU compile error for ls1bdev

---

components/net/sal_socket/src/sal_socket.c

[
After socket_new () succeeds, the subsequent function returns -1 , without deleting the socket
]

socket_new() 错误返回时的问题

---

tools/utils.py

Fix the siginfo_t compiling issue caused by gcc_version and +c99 in command line. Verified in K210 BSP.

[tools] fix c99/siginfo_t issue caused by gcc_version

---

bsp/k210/driver/Kconfig
bsp/k210/driver/drv_io_config.c
bsp/k210/driver/drv_uart.c

[RISC-V:K210]Add UART1~3 support for K210
This patch adds UART1~3 support for K210, and separates the rt_uart_ops of  UARTHS from UART.
This patch add configs in Kconfig for configuring the pins of UARTx, please check the sysctl_set_power_mode for the pins in the io_config_init  of bsp/k210/driver/drv_io_config.c

K210 drv uart upstream

---

components/drivers/usb/usbdevice/class/mstorage.c

[
mstorage.c: fix the issue that _read_capacity() returns the wrong last valid address of storage medium
]

mstorage.c: fix the issue bug in_read_capacity()

---

components/drivers/can/can.c

[
Get stuck issue after open-close-open CAN device.
Append rt_sem_detach(&(tx_fifo->sem)); .
]

Get stuck issue after open-close-open CAN device.

---

bsp/stm32/libraries/HAL_Drivers/drv_spi.c

The bug affects in SPI mode 1 (probably and mode 2)
When changing SPI device, HAL returns timeout error for the first time trying to read/write.
之前的SPI在设置成 mode 1，并切换SPI 设备后 （重新初始化后）第一次读写设备会导致STM32的hal层返回timeout。 我推测是因为 https://github.com/RT-Thread/rt-thread/blob/5c399d50a759cf778e4dae4e8ceef5a1819621b8/bsp/stm32/libraries/HAL_Drivers/drv_spi.c#L260 这里在初始化时就已经打开了spi导致hal部分时序错误。在调用hal进行数据收发后，不影响mode 0 和mode 3，但是mode 1 和mode2会返回timeout。 而在初始化时打开SPI设备不是必须的操作，因为HAL会在传输开始时使能SPI。 
The previous driver will caues SPI timeout when setting SPI to mode 1, switching device and read/write for the first time (this operation will lead to spi reinitialization.). I think this is the issue  https://github.com/RT-Thread/rt-thread/blob/5c399d50a759cf778e4dae4e8ceef5a1819621b8/bsp/stm32/libraries/HAL_Drivers/d …

Fix bug cause STM32 HAL SPI timeout

---

bsp/stm32/libraries/HAL_Drivers/config/h7/dma_config.h
bsp/stm32/libraries/HAL_Drivers/config/h7/uart_config.h
bsp/stm32/libraries/HAL_Drivers/drv_dma.h
bsp/stm32/libraries/HAL_Drivers/drv_usart.c
bsp/stm32/stm32h743-atk-apollo/README.md
bsp/stm32/stm32h743-atk-apollo/board/Kconfig
bsp/stm32/stm32h743-atk-apollo/board/drv_mpu.c

[
本次提交已经在stm32h743-atk-apollo 测试通过，修改说明如下：
1.dma_config.h删除了部分宏定义，STM32H7的DMA和F系列的区别在于可以指定到任何外设，而不是几个外设公用一个DMA，所以这里不需要考虑多个DMA使用一个通道的问题；
2.uart_config.h修改channel为reques；
3.在drv_mpu.c中增加了cache使能，方便后续驱动提交都基于使能cache；
4.README.md中增加了使能cache为WT模式之后会出现数据一致性问题的说明，并给出了解决方法；
]

[bsp/stm32/stm32h743-atk-apollo]support stm32h7 uart dma

---

bsp/stm32/libraries/HAL_Drivers/config/f1/pwm_config.h

[
增加 PWM1_CONFIG 的定义。
定时器1是每个芯片都有的定时器，比较常用，建议加上PWM1_CONFIG的定义，方便使用。
已在stm32f103-mini-system上测试通过。
]

add PWM1_CONFIG

---

ChangeLog.md

update change log.

---

bsp/stm32/libraries/HAL_Drivers/drv_spi.c

[
修改 SPI NSS 引脚类型判断错误。
因为 SPI 设备不支持从设备，所以在 NSS 类型判断时，只判断了软件 NSS 和 硬件输出两种方式。
已在 stm32f407-atk-explorer 测试。
]

SPI 设备初始化 NSS 类型判断错误

---

src/object.c

Fix the maxlen issue in rt_object_get_points() function. Test with kobject testcase.

[Kernel] Fix the maxlen issue in rt_object_get_pointers

---

components/net/at/at_socket/at_socket.c

[
AT socket 框架中有多次重复的 recv 和 close 事件回调函数绑定操作，包括 at_connect、at_sendto 和 at_recvfrom 接口函数，容易造成误解。我认为应该将该操作放在 at_socket 接口函数内即可，一方面代码变得更简洁，另一方面如果 at device 在 connect 时出错了，例如申请的 socket 号与 AT 模块实际返回的 socket 号不一致，可以及时关闭该 socket，避免应用程序 closesocket 时出错。
]

[AT] Adjust where the AT socket callback function

---

bsp/stm32/libraries/HAL_Drivers/drv_rtc.c

[
- when cpu reset rtc date is not saved in stm32f1 series.this pr will fix this bug
- verify platform
- stm32f103-fire-arbitary
- stm32f407-atk-explorer
- stm32f767-atk-apollo
- stm32h743-atk-apollo
]

[bsp] fix stm32 f1 series rtc bug

---

src/thread.c

Signed-off-by: Cliff Chen <cliff.chen@rock-chips.com>
[
如果一个线程已经退出，即已经调用了rt_thread_exit，然后其他线程再调用rt_thread_delete或者rt_thread_detach，则会导致double free，比如挂在第二次thread_timer的释放里。所以这里做了一个判断，在rt_thread_delete和detach入口判断一下线程的状态，如果是close，就直接返回，自测PASS。
]
- [ x ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [ x ] 已经仔细查看过代码改动的对比 Already check the …

[Kernel] Fix double release for thread

---

components/libc/libdl/dlmodule.c

Signed-off-by: Cliff Chen <cliff.chen@rock-chips.com>
[
动态模块退出的时候会去判断线程状态，然后stop线程的timer，但是现在的判断逻辑是错的，导致已经退出的线程还会进stop timer，而实际上这个timer已经释放了，结果就crash了。
]
- [ x ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [ x ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ x ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, …

[dlmodule] Fix crash when dlmodule exit

---

libcpu/arm/cortex-m0/context_gcc.S
libcpu/arm/cortex-m0/context_iar.S
libcpu/arm/cortex-m0/context_rvds.S
libcpu/arm/cortex-m23/context_gcc.S
libcpu/arm/cortex-m23/context_iar.S
libcpu/arm/cortex-m23/context_rvds.S
libcpu/arm/cortex-m3/context_gcc.S
libcpu/arm/cortex-m3/context_iar.S
libcpu/arm/cortex-m3/context_rvds.S
libcpu/arm/cortex-m33/context_gcc.S
libcpu/arm/cortex-m33/context_iar.S
libcpu/arm/cortex-m33/context_rvds.S
libcpu/arm/cortex-m4/context_gcc.S
libcpu/arm/cortex-m4/context_iar.S
libcpu/arm/cortex-m4/context_rvds.S
libcpu/arm/cortex-m7/context_gcc.S
libcpu/arm/cortex-m7/context_iar.S
libcpu/arm/cortex-m7/context_rvds.S

[
更新cortex-M系列的systick中断优先级配置，在系统启动时，把systick中断配置为最低。
相关链接:
* https://www.rt-thread.org/qa/thread-421383-1-1.html
* https://blog.csdn.net/sinat_31039061/article/details/99640944
]

set Systick interrupt priority to the lowest

---

bsp/stm32/stm32f103-hw100k-ibox/project.ewp
bsp/stm32/stm32f103-hw100k-ibox/template.ewp

[
stm32f103-hw100k-ibox IAR 工程 Device 显示为空，导致 RT-Thread Studio 导入失败。已修复，成功编译并导入 。
]

修复了 stm32f103-hw100k-ibox iar 工程导入报错 的BUG

---

bsp/stm32/libraries/HAL_Drivers/drv_common.c
bsp/stm32/libraries/HAL_Drivers/drv_usart.c

关于SysTick的中断优先级配置的问题：
https://www.rt-thread.org/qa/thread-421383-1-1.html
之前关于systick中断优先级在libcpu中的汇编有修改，但是stm32的驱动中又配置成0，0,这里修改systick中断保持systick中断优先级一致：
#3637

调整STM32系列bsp部分外使的中断优先级配置

---

components/net/lwip-1.4.1/src/netif/ethernetif.c
components/net/lwip-2.0.2/src/netif/ethernetif.c
components/net/lwip-2.1.0/src/netif/ethernetif.c

[
if LWIP_NETIF_HOSTNAME enable, the length is 'sizeof(struct netif)+ LWIP_HOSTNAME_LEN',
not only  equal to  'sizeof(struct netif)'.
]

[lwip]Fixed a memset bug in ethernetif.c

---

bsp/ls2kdev/drivers/clk.c
bsp/ls2kdev/drivers/clk.h
bsp/ls2kdev/drivers/ls2k1000.h

Signed-off-by: Du Huanpeng <548708880@qq.com>
[
龙芯 2K 时钟驱动，沿用 1C 的驱动函数名。
支持 NODE（CPU），DDR，APB三个频率的获取。
下面这个是带有测试代码的分支，可供测试：
https://github.com/imgtec/rt-thread/tree/bsp-ls2k/clk-draft.2020.6.15
另外：
rt_kprintf 不能正常支持 %llx 打印64位整数。
]

bsp: ls2k: initial clk driver

---

libcpu/arm/cortex-m23/context_gcc.S
libcpu/arm/cortex-m23/context_iar.S
libcpu/arm/cortex-m23/context_rvds.S

Change exception return call address to 0xFFFFFFFD.
EXC_RETURN[31:0] Description
0xFFFFFFFD Return to Thread mode, exception return uses non-floating-point state from
the PSP and execution uses PSP after return.

[libcpu][arm][cortex-m23] Change exception return call address

---

components/net/lwip-1.4.1/src/arch/include/arch/cc.h
components/net/lwip-2.0.2/src/arch/include/arch/cc.h
components/net/lwip-2.1.0/src/arch/include/arch/cc.h

[
* lwip clock confict with minilibc clock, when RT_LIBC_USING_TIME has been defined
* has been tested on stm32f407-atk
]

[fix] lwip clock confict with minilibc clock

---

bsp/ls2kdev/drivers/drv_rtc.c
bsp/ls2kdev/drivers/ls2k1000.h

hardware date format
year, the same as ctime
month 1 ~ 12
no leap second
Signed-off-by: Du Huanpeng <548708880@qq.com>
[
支持读取时间，设置时间。
年份储存使用<ctime>格式，即读出值之后，加上1900
月份使用 1 ~ 12 计，（ctime 是 0 ~ 11）
驱动程序中有一对 硬件格式 与 ctime struct tm 格式转换的函数。
ls2k1000 实时时钟直接支持0.1秒，但暂未体现给应用程序。
patches are welcome~
]

bsp: ls2k: internal rtc driver

---

libcpu/arm/cortex-a/gic.c
libcpu/arm/zynq7000/gic.c

[
此次提交解决gic代码中对中断进行ack时的问题，原操作是关闭中断分发器，eoi之后再打开，现改为eoi之前清除对应中断标志位。
此修改在zynq7000中测试通过。
]
- [x ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP

fix gic ack irq problem

---

components/drivers/sensors/sensor.h
components/drivers/sensors/sensor_cmd.c

[
增加 AMS 传感器厂商标识，同时在 packages 中增加 AMS 的 ccs811 气体传感器软件包
]

[Sensor] Add AMS sensor vendor info

---

bsp/ls2kdev/drivers/drv_pwm.c
bsp/ls2kdev/drivers/ls2k1000.h

attach probe of the oscilloscope too the
3.3v & PWM3 like below:
jack
------|  |---|    |-|    |----
|o o 3.3v    |eth1| |eth0|
|o o
|o o
|o o PWM3
|o o
type commands below to rt-thread console:
msh /> pwm_enable pwm0 3
msh /> pwm_set pwm0 3 140 90
turn off pwm:
msh /> pwm_disable pwm0 3
Signed-off-by: Du Huanpeng <548708880@qq.com>
[
富含调试信息的分支：
https://github.com/imgtec/rt-thread/tree/bsp-ls2k/pwm-v0
] …

bsp: ls2k: pwm driver

---

bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f4.c

2.stm32_flash_write函数按byte、half word、word对齐写入，提升写入效率。
[
！！误删提交分支，重新提交！！
stm32_flash_erase函数size参数如果传入0会选择flash错误的sector，修改此bug，如果size为0则返回错误。
stm32_flash_write函数当前是按byte写入，效率低，修改此函数按照word、half word、byte的顺序匹配写入地址对齐字节，提升写入效率。double word方式需要外部电压支持，暂不支持。
（另外stm32f4内核使用的汇编指令LDRD应该是不支持硬件非8字节对齐访问，如提供double word写时内存也需要8字节对齐）
对1、2、3、4字节对齐写入进行了测试，块写速度提升将近4倍。
]

1.增加对stm32_flash_erase函数入口参数size为0的检测。

---

components/utilities/ulog/syslog/syslog.c

[
rt_snprintf参数字符串%数与参数个数不对应。 ‘’rt_tick_get() % 1000‘’应该是表达毫秒数，跟ulog syslog格式不对应，这个参数应该是多余的。
]

syslog_formater调用rt_snprintf多了个参数。

---

bsp/nrf5x/libraries/drivers/drv_gpio.c
bsp/nrf5x/libraries/drivers/drv_gpio.h
bsp/nrf5x/nrf52840/applications/application.c
bsp/nrf5x/nrf52840/board/board.c
bsp/nrf5x/nrf52840/board/board.h
bsp/nrf5x/nrf52840/board/sdk_config.h

提交nrf5x的gpio驱动

---

tools/eclipse.py

[
修复了在工程所在目录的所有父级目录列表中，对于非工程目录的过滤代码。
在原版本实现中，对列表元素进行迭代并判断删除，因为 Python 可变对象为引用传递，导致操作的是同一列表对象，在删除操作后，部分元素被跳过迭代。
]

fixbug:eclipse.py do not remove all unused path from list

---

components/drivers/sensors/sensor_cmd.c

[
在使用 sensor read 命令读取传感器设备时，发现有些设备经常读取失败。经检查是由于 sensor read 的延时固定为 100ms 所致，建议延时时间应使用 sensor 驱动指定的最小测量周期（sensor->info.period_min）。同时发现部分 sensor 驱动并没有设置 period_min，为了保证兼容，当 period_min 没有设置或者小于 100ms 时，仍然使用 100ms 延时。
]

[sensor] fixed sensor cmd delay time

---

components/drivers/wlan/wlan_mgnt.c

[components][wlan] 修复 rt_wlan_event_dispatch() 在某种情况下未传递 user_buff 的问题。

---

src/mempool.c

[
1. Improved code readability,  unify the variable name  in the likely functions, when some functions used "level", but some other functions used "temp" in functions "rt_hw_interrupt_enable()" and "rt_hw_interrupt_enable()" 
so changed variable  "temp" to "level".
]

Minor optimization for mempool.c

---

bsp/stm32/libraries/HAL_Drivers/drv_wdt.c

[bsp][stm32][wdt] Optimize code style.

---

components/net/at/Kconfig
components/net/at/at_socket/at_socket.c
components/net/at/at_socket/at_socket.h
components/net/at/include/at.h

[
由于目前 at socket 框架在获取 at_socket 对象是采用固定查询方式进行，具体在 components/net/at/at_socket/at_socket.c 文件中的 alloc_socket_by_device 函数：
```c
for (idx = 0; idx < device->class->socket_num && device->sockets[idx].magic; idx++);
if (idx == device->class->socket_num)
{
goto __err;
}
```
这种方式带来了一些限制，比如有些 AT 模块的可用 socket 并非从 0 开始，申请的 socket 也并非一定是按顺序的，由此给 at_device 的实现带来了一些困扰。因此建议在 at_socket_ops 结构体增加 at_socket 函数，为需要动态分配 socket 的 AT 设备提供一个处理的时机。
```c
struct at_socket_ops
{
int (*at_socket)(struct at_device *device, enum at_socket_type type);
int (*at_connect)(struct at_socket *socket, char *ip, int32_t port, enum at_socket_type type, rt_bool_t is_client);
int (*at_closesocket)(struct at_socket *socket);
int (*at_send)(struct at_socket *socket, const char *buff, size_t bfsz, enum at_socket_type type);
int …
```

[at_socket] support alloc socket dynamically with at device

---

tools/eclipse.py

[
- 修复：当用户通过 menuconfig 或者 RT-Studio 更改系统配置后，当 LIBS 为空时，应当删除之前链接的库文件
- 新增：对 scons 添加的库文件添加特征后缀，特征后缀为5个空格，当 scons 执行 scons --target=eclipse 更新 eclipse 工程文件时，根据是否具有特征标志来区分用户添加的库和 scons 添加的库，从而保留用户配置
]

fixbug:keep user's lib configuration while running --target=eclipse

---

bsp/efm32/copy_this_file_shell.c
components/finsh/shell.c

[
function should be parameter.
test on stm32f407 board and qemu with testcase, run well.
]

[update] function must have parameter

---

components/drivers/rtc/rtc.c

[
libc ctime returns a fixed 25 character string without a NULL terminator. Print it without specifying length in FINSH date command prints extra contents and could potentially be dangerous.
Tested on STM32F103 MCU.
]

Specify date string length in FINSH date command.

---

src/kservice.c

[
modify  internal function 'isdigit' name to '_isdigit' in kservice，avoiding to be the same to C library.
test on stm32f407 board and qemu with testcase.
]

[modify] internal function 'isdigit' name to '_isdigit'

---

bsp/nuvoton/libraries/m480/StdDriver/inc/nu_eadc.h
bsp/nuvoton/libraries/m480/StdDriver/inc/nu_qspi.h
bsp/nuvoton/libraries/m480/StdDriver/inc/nu_spi.h
bsp/nuvoton/libraries/m480/StdDriver/inc/nu_usci_spi.h
bsp/nuvoton/libraries/m480/rtt_port/Kconfig
bsp/nuvoton/libraries/m480/rtt_port/drv_can.c
bsp/nuvoton/libraries/m480/rtt_port/drv_clk.c
bsp/nuvoton/libraries/m480/rtt_port/drv_fmc.c
bsp/nuvoton/libraries/m480/rtt_port/drv_gpio.c
bsp/nuvoton/libraries/m480/rtt_port/drv_gpio.h
bsp/nuvoton/libraries/m480/rtt_port/drv_i2s.c
bsp/nuvoton/libraries/m480/rtt_port/drv_qspi.c
bsp/nuvoton/libraries/m480/rtt_port/drv_scuart.c
bsp/nuvoton/libraries/m480/rtt_port/drv_sdh.c
bsp/nuvoton/libraries/m480/rtt_port/drv_softi2c.c
bsp/nuvoton/libraries/m480/rtt_port/drv_spi.c
bsp/nuvoton/libraries/m480/rtt_port/drv_spi.h
bsp/nuvoton/libraries/m480/rtt_port/drv_tpwm.c
bsp/nuvoton/libraries/m480/rtt_port/drv_uart.c
bsp/nuvoton/libraries/m480/rtt_port/drv_ui2c.c
bsp/nuvoton/libraries/m480/rtt_port/drv_uspi.c
bsp/nuvoton/libraries/m480/rtt_port/drv_uuart.c
bsp/nuvoton/libraries/m480/rtt_port/drv_wdt.c
bsp/nuvoton/numaker-iot-m487/README.md
bsp/nuvoton/numaker-iot-m487/applications/main.c
bsp/nuvoton/numaker-iot-m487/board/board_dev.c
bsp/nuvoton/numaker-pfm-m487/README.md

[
Correct typo.
Fix spi/qspi/uspi TX/RX PDMA trigger issue.
Drain RX FIFO to remove remain FEF frames in FIFO.
Implement RT_DEVICE_CTRL_CLOSE in uart/uuart/scuart driver.
]

[nuvoton] Sync drivers of Nuvoton-M480 platform.

---

include/rtdef.h

[
format enumeration define two styles: define first or all.
test on stm32f407 board and qemu with testcase, run well.
]

[format] enumeration define two styles: define first or all.

---

components/drivers/include/drivers/usb_common.h
components/drivers/usb/usbdevice/class/winusb.c

[code style] spelling mistake : PROERTY -> PROPERTY

---

bsp/stm32/stm32f072-st-nucleo/README.md
bsp/stm32/stm32f091-st-nucleo/README.md
bsp/stm32/stm32f412-st-nucleo/README.md
components/libc/compilers/armlibc/stubs.c

[
1.增加条件编译，防止RT_USING_DFS没有定义时 _sys_flen()出现编译警告：stat变量定义但没有被调用 的问题
已经在STM32F412 nucelo板子上测试过，编译器为Keil-MDK Compiler 5
2.修改部分stm32-nucelo开发板readme，烦请提示STM32 BSP开发者一定要仔细检查readme，有一些马虎的错误。例如：
板子的链接给错了
readme标题还在使用模板的标题
readme从上一个型号复制过来，板子的型号以及参数还保留上一个型号的，没有修改
闪烁的LED颜色描述错误
等
我只检查了F072 F091 F412的readme，其他的nucleo readme烦请组织人员检查一下。
]

[fixed]增加条件编译，防止RT_USING_DFS没有定义时 _sys_flen()出现编译警告：stat变量定义但没有被调用 的问题

---

include/rtdef.h

[
struct rt_device_ops 结构体增加宏定义
]

struct rt_device_ops 结构体增加宏定义

---

bsp/nrf5x/libraries/drivers/SConscript
bsp/nrf5x/libraries/drivers/drv_adc.c
bsp/nrf5x/libraries/drivers/drv_adc.h
bsp/nrf5x/libraries/drivers/drv_gpio.c
bsp/nrf5x/nrf52840/board/Kconfig

add nrf5x adc driver

---

bsp/ls2kdev/SConstruct
bsp/ls2kdev/drivers/board.c
bsp/ls2kdev/drivers/drv_gpio.c
bsp/ls2kdev/drivers/drv_rtc.c
bsp/ls2kdev/ls2k_ram.lds
bsp/ls2kdev/rtconfig.py
libcpu/mips/common/asm.h
libcpu/mips/common/stackframe.h

[
MIPS:remove redundant #ifdef ARCH_MIPS64
bsp:ls2k:make rtc driver to adapter Kconfig 
bsp:ls2k:gpio read typo error,fix it. 
bsp:ls2k:add c++ support
MIPS:improvement FPU support
bsp:ls2k: adapt to FPU
]

MIPS:remove redundant #ifdef ARCH_MIPS64

---

bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c

[
修复STM32硬件定时器配置时候可能存在的逻辑问题。例如当 APB1CLKDivider 或 APB2CLKDivider为RCC_HCLK_DIV1的时候，此时旧版本的 drv_hwtimer.c 中仍然会以 PCLKx 频率的2倍计算. 由此造成设置的定时时间变成了原来的2倍。例如定时1S，实际得到的结果是2S。
由“STM32的硬件定时器在 APBxCLKDivider 为 RCC_HCLK_DIV1 的时候，timer clocks 频率等于外设总线时钟PCLKx， 反之 timer clocks 为 PCLKx 的2倍”规则。在进行定时器计算的时候均先获取当前 APBxCLKDivider 的配置情况，然后再决定是否需要对PCLx的时钟进行倍频计算。
当前已经测试板卡/MCU:STM32F412xx实际运行测试。其他STM32F0xx、STM32F1xx、STM32F2xx、STM32F3xx、STM32F7xx、STM32H7xx、STM32MP15x系列均使用STM32CubeMX进行验证，时钟逻辑均是如此。
]
必须选择一项 …

修复STM32的硬件定时器的时钟配置问题

---

bsp/stm32/libraries/HAL_Drivers/drv_hwtimer.c

[
修复 drv_hwtimes.c 文件内错误的结构体变量使用。
已在 F0，F1，F4，F7，H7，G0，L4，MP1 上编译通过。
]

[update] drv_hwtimers.c file error struct member variables

---

src/thread.c

[
问题复现描述：代码使用 heap 情况下，某处如果使用 rt_thread_init 初始化的线程，调用 rt_thread_control(&tc_thread_thread7, RT_THREAD_CTRL_CLOSE, RT_NULL) close 线程，直接出错。
分析：当前线程无法区分该线程是 init 还是 create 的，并且 rt_thread_control 使用命令 `RT_THREAD_CTRL_CLOSE` 只有 delete 线程一种方式。
修改后测试结果：stm32f407 与 qemu 测试静态创建、动态创建线程分别使用、不使用 RT_USING_HEAP 情况下，结果均运行正常。
]

[fix] thread control bug about RT_THREAD_CTRL_CLOSE command

---

bsp/imxrt/imxrt1064-nxp-evk/SConstruct

[
1. 为什么提交这份PR
imxrt1064-nxp-evk的SConstruct文件中对libraries的拼写为“Libraries”，导致在Linux环境下无法正确的找到libraries下的SConscript文件而构建失败。
基于imxrt1064-nxp-evk的BSP和开发板做了测试
]

[BSP][IMXRT]fixed SConstruct file spell error in imxrt1064-nxp-evk

---

libcpu/risc-v/nuclei/cpuport.c

* Fix wrong RT_KERNEL_INTERRUPT_LEVEL settings, it should be set to zero, zero will set lowest level

libcpu/nuclei: Fix wrong RT_KERNEL_INTERRUPT_LEVEL

---

bsp/imxrt/libraries/drivers/drv_eth.c

[
1. 为什么要提交这份PR
imxrt的BSP中的drv_eth.c对变量g_txBuffDescrip和g_rxBuffDescrip存储位置分配存在问题，在使用GCC版本编译时，会产生错误的数据，使得软件运行异常。
2. 解决方案
使用了NXP官方的AT_NONCACHEABLE_SECTION_ALIGN宏来定义上面两个变量，可以兼容keil, iar, gcc编译器。
使用了imxrt1052-nxp-evk的BSP来进行测试
]

[BSP][imxrt]fixed ethernet driver bug for imxrt

---

src/scheduler.c

[
smp实现中，在多核且任务数大于32的情况下，rt_schedule_remove_thread对pcpu->priority_group的标志清除时，判断的位置应为pcpu->ready_table[thread->number] ，代码中笔误成了rt_thread_ready_table[thread->number] ，可能导致出现priority_groupw对应就绪位未正确清除，在下面的测试中会出现dabt：
```c
static void thread_entry(void* parameter)
{
int count = 0;
while (1)
{
rt_thread_mdelay(1000);
}
}
int task0(void)
{
rt_thread_t tid;
int cpuid = 0;
tid = rt_thread_create("count0", thread_entry, RT_NULL,
4096, 22, 10);
if (tid)
{
rt_thread_control(tid, RT_THREAD_CTRL_BIND_CPU, (void*)cpuid);
rt_thread_startup(tid);
}
return 0;
}
int task1(void)
{
rt_thread_t tid;
tid = rt_thread_create("count1", thread_entry, RT_NULL,
4096, 22, 10);
if (tid)
{
rt_thread_startup(tid);
}
return 0;
}
```
修正后，任务正常运行。
]
以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check， …

修正多核rt_schedule_remove_thread时pcpu的ready_table判断问题

---

components/drivers/spi/spi_msd.c

[修复"response+1"导致STM32 HAL库SPI内存非对齐访问的hard fault]

修复"response+1"导致STM32 HAL库SPI内存非对齐访问的hard fault

---

src/clock.c
src/scheduler.c
src/thread.c

[
- 问题描述： 在rt_thread_yield函数中，由于没有设置RT_THREAD_STAT_YIELD标志而导致在调用rt_schedule时可能未能成功切换到相同优先级就绪任务。
]

解决yield操作不能及时释放cpu的问题

---

components/finsh/shell.h

[
原来的 finsh/shell.c 中，有部分操作会使用`strlen(shell->line)`来计算字符串长度，但代码中并没有确保`shell->line`的最后一位为'\0'。现已修复。
]

[shell] Ensure that the last char of `char line[]` is '\0'

---

components/drivers/usb/usbdevice/class/cdc_vcom.c
components/drivers/usb/usbdevice/class/hid.c
components/drivers/usb/usbdevice/class/mstorage.c

[
Enable HS device functions(VCOM, HID, MSTORAGE) for Nuvoton M487 platform.
]

Solved USB device class issue.

---

bsp/stm32/stm32l4r5-st-nucleo/board/Kconfig

[
stm32l4r5-st-nucleo BSP 中的 board/Kconfig 文件 BSP_USING_PWM1 项遗漏了双引号，导致每次 menuconfig 都会出现“multi-line strings not supported”的警告。
]

[bsp][stm32] fixed Kconfig multi-line strings warning

---

src/memheap.c

[
使用 rt_sem_detach 取代 rt_object_detach，以便 rt_memheap detach 时，等待的任务能被正常通知。
]

fix bug of rt_memheap_detach

---

bsp/stm32/stm32f103-blue-pill/board/CubeMX_Config/Src/stm32f1xx_hal_msp.c
bsp/stm32/stm32f103-blue-pill/board/Kconfig

[
blue pill 增加USART2功能
已经在bluepill上测试通过
]

[bsp][stm32][bluepill] add USART2

---

bsp/k210/driver/drv_gpio.c

fixed drv_gpio bug

---

components/libc/pthreads/semaphore.c

[
`posix_sem_find` 函数中，`iter->sem` 的数据类型为 `rt_sem_t`指针类型，转换为 `rt_object_t` 时候应该为 
`(rt_object_t)iter->sem` 而不是 `(rt_object_t)&(iter->sem)`
]

[bug] [libc] 修复posix_sem_find中iter->sem的数据类型转换问题

---

components/drivers/rtc/alarm.c

[
使用rtc alarm时，若更新rtc 的日期时间，并且日期的日期超前于当前日期。会造成基于hour、minute、second为周期的闹钟，无法正常触发。
造成这个问题的原因为：
* alarm hour：只关心mm:ss，set alarm时，hour需要采用当前时间的hour，因为hour是alarm不关心的项。
* alarm minute：只关心 ss，set alarm时，hour、minute 需要采用当前时间的hour、minute。此时hour minute 是alarm不关心的项。
* alarm second：只要更新，就需要触发！，set alarm时，hour、minute、second 需要采用当前时间的hour、minute、second。此时second、hour 、minute都 是alarm不关心的项。
但是setalarm，需要设置hh:mm:ss，若因为更新rtc时间，设置的alarm时间：hh:mm:ss比当前的rtc时间超前，则当天可能就不再触发alarm，这样 hour 、minute、second 为周期性的alarm，无法触发。
基于hour、minute、second 周期性的alarm，在设置时，不关心的项，需要同步当前时间项。
apollo3、STM32L4等平台验证通过。
] …

[rtc.alarm][fix]fix alarm when update datetime

---

bsp/stm32/libraries/HAL_Drivers/drv_lcd.c

`_lcd.lcd_lock` should be detach with rt_sem_detach.
[
`_lcd.lcd_lock`是静态初始化的，需要rt_sem_detach脱离。
]

change `rt_sem_delete` to `rt_sem_detach`

---

bsp/lpc43xx/M0/applications/vbus_hw.h
bsp/lpc43xx/M4/applications/vbus_hw.h

[
Added define `__VBUS_HW_H__`
]

[bsp/drivers]Update vbus_hw.h

---

components/drivers/sdio/sdio.c

Improve the clock Settings for switching to high speed mode in the SDIO framework.
****
[
关联issue：https://github.com/RT-Thread/rt-thread/issues/3737
]

完善sdio框架中切换到高速模式时的时钟设置

---

components/drivers/include/ipc/ringbuffer.h
components/drivers/src/ringbuffer.c

[
增加 'rt_ringbuffer_peak' API。
对于 'rt_ringbuffer_get' API 需要我们再定义一个数组来获取环形缓冲区中的数据。但是有很多情况，我们只需要获取到连续的数据处理就够了。而且外部定义数组对于 RAM 小的 MCU 来说开销太大，所以我们可以直接使用环形缓冲区自己的 buffer_ptr 来获取连续的数据。
char *ptr = RT_NULL;
rt_size_t len = rt_ringbuffer_peak(rb, &ptr);
len 为连续数据的长度，ptr 为数据起始指针
]

add 'rt_ringbuffer_peak' API

---

libcpu/risc-v/common/context_gcc.S
libcpu/risc-v/k210/interrupt_gcc.S
libcpu/risc-v/k210/startup_gcc.S

…ruction
[
**Target**
k210
**Problem**
As code size increases to a point in development, especially in `BUILD='debug'` mode, the following linker errors may occur:
```
xxx/libcpu/risc-v/k210/startup_gcc.o: in function `.L0 ':
xxx/libcpu/risc-v/k210/startup_gcc.S:125:(.start+0x134): relocation truncated to fit: R_RISCV_JAL against symbol `secondary_cpu_c_start' defined in .text.secondary_cpu_c_start section in xxx/libcpu/risc-v/k210/cpuport_smp.o
xxx/libcpu/risc-v/common/context_gcc.o: in function `.L0 ':
xxx/libcpu/risc-v/common/context_gcc.S:50:(.text+0x12): relocation truncated to fit: R_RISCV_JAL against symbol `rt_cpus_lock_status_restore' defined in .text.rt_cpus_lock_status_restore section in xxx/src/cpu.o
xxx/libcpu/risc-v/k210/interrupt_gcc.o: in function `.L0 ': …
```

fix long call linker error with 'jal', 'j' or conditional branch instruction in .S files for k210

---

bsp/stm32/stm32f746-st-disco/rtconfig.py

[
这份PR解决了在STM32F746-DISCOVERY上使用float和double会报错的问题。
STM32F74X系列的FPU Configurable Options中提到，STM32F74X的FPU只支持单精度浮点数。因此`-mfpu`应该设置为`-mfpu=fpv5-sp-d16`。
具体参考手册链接: [Floating Point Unit Demonstration on STM32 Microcontrollers](https://www.st.com/resource/en/application_note/dm00047230-floating-point-unit-demonstration-on-stm32-microcontrollers-stmicroelectronics.pdf)（第13页表格）
修改后，经过测试，在STM32F746-DISCOVERY上可以正常使用浮点运算。
]
我在这个拉取/合并请求中已经考虑了 As part …

修正stm32f746-disco和FPU相关的flag错误

---

libcpu/sim/win32/cpu_port.c
libcpu/sim/win32/cpu_port.h

这份PR解决了simulator中调度器的2个问题：1.线程Yield时没有及时被挂起；2.Yield中断优先级高于Timer中断，导致调度器挂起了非正在运行的线程。我的解决方案是：1.增加一个YieldEvent事件，用于确保异步挂起动作被执行前，线程不会继续执行；2.修改Yield中断的优先级，确保它是当前所有中断里面最低级的。
更详细的描述可以看这两篇帖子：
https://club.rt-thread.org/ask/question/429478.html
https://club.rt-thread.org/ask/question/3899.html
这个版本在vs2019 simulator中通过了测试。

fix scheduler bug in simulator.

---

bsp/stm32/stm32mp157a-st-ev1/board/Kconfig
bsp/stm32/stm32mp157a-st-ev1/board/SConscript
bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_dfsdm.c
bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_emmc.c
bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_ov5640.c
bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_sdcard.c
bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_sound.c
bsp/stm32/stm32mp157a-st-ev1/board/ports/eth/drv_eth.c

[
to avoid  the not be enabled ram be init by function `__iar_data_init3()` ;
]

[ST32MP1] add modifier __no_init for IAR

---

components/drivers/Kconfig
components/drivers/touch/touch.c
components/drivers/touch/touch.h

[
- 将 touch 框架和 pin 框架进行解耦
- 增加 rt_hw_touch_isr api 通知框架有中断发生
]

[components][drivers] separate touch framework and pin framework

---

components/drivers/hwtimer/hwtimer.c

[
获取timer count时，防止因中断到来导致overflow更新
]

[update] 获取timer count时，防止因中断到来导致overflow更新

---

bsp/gd32450z-eval/drivers/drv_spi.c

[修改 gd32450z-eval spi 驱动模式判断条件错误的问题]

[bsp][gd32450z-eval]fixed spi driver bug

---

bsp/nrf5x/libraries/templates/nrf52x/applications/ble_nus_app.c
components/dfs/filesystems/jffs2/src/gcthread.c

[
bsp/nrf5x/libraries/templates/nrf52x/applications/ble_nus_app.c ，
components/dfs/filesystems/jffs2/src/gcthread.c  ：
add error checks of function rt_event_recv()
添加rt_event_recv()函数的错误检查
修复 #4105
]

add error checks of function rt_event_recv()

---

components/net/at/src/at_client.c

Signed-off-by: RGW <rgw5267@gmail.com>
假如串口接收数据在箭头处收到，那么后面的指令会清除掉上次中断中释放的信号量，但此时serial设备中还缓存着接收到的数据，下次收到新数据时，才会因为收到新信号量而老数据被接收到。
修改后与原函数行为一致，引用``at_client_getchar()``函数的地方有
``at_recv_readline()``和``at_client_obj_recv()``，测试无问题。
[
] …

fix the bug that rx_notice out of sync when data received after last rt_device_read() is zero

---

libcpu/ti-dsp/c28x/context.s
libcpu/ti-dsp/c28x/cpuport.c

[
[libcpu][c28x]add support for c28x hardware fpu. (only support FPU32)
Tested on mcu TMS320F28335.
]

[libcpu][c28x]add support for c28x mcu hardware fpu

---

src/idle.c
src/thread.c

[
原来的cleanup时机是在idle中，这会在多核中造成问题；且由于原来cleanup是在disable了调度器的状态下执行的，会造成在cleanup不能释放内存及和别的线程通讯。
此修改方式是把cleanup的时机移到当前线程的退出函数来完成（注意，此修改并不包括释放当前线程的tcb和stack)
]

cleanup操作改由当前线程退出前执行

---

bsp/CME_M7/drivers/emac.c
bsp/fh8620/drivers/i2c.c
bsp/lpc55sxx/Libraries/drivers/drv_sd.c
bsp/simulator/drivers/sst25vfxx_mtd_sim.c
bsp/swm320-lq100/drivers/drv_nor_flash.c

[
bsp\stm32f20x\Drivers\i2c.c : add error check of rt_mutex_take()
添加rt_mutex_take()函数的返回值ret的错误检查
修复 #4103 中的部分问题
]

add error checks of rt_mutex_take()

---

bsp/nrf5x/nrf52840/board/Kconfig

修复NRF52840启用SPI驱动后编译错误问题

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

[
按官网 [PWM 设备使用示例](https://www.rt-thread.org/document/site/programming-manual/device/pwm/pwm/)测试端口没有正常输出PWM信号，在drv_pwm.c中添加 HAL_TIM_Base_Init() 后可以正常使用。
目前已在 stm32f407-atk-explorer 测试通过
]

[bsp][stm32] Add HAL_TIM_Base_Init

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
components/drivers/include/drivers/rt_drv_pwm.h
components/drivers/misc/rt_drv_pwm.c

[在STM32H7系列使用STM32的PWM驱动时，发现H7宏定义缺失，添加后解决、发现不支持PWM的互补输出，原因为使能PWM输出的底层函数未有添加相应PWM的互补输出函数，导致互补PWM输出没有反应，添加并做兼容性处理后解决此问题，并完善缺失的pwm_get函数。修改在ART-PI和其他核心板上测试成功]

为stm32的PWM驱动添加对STM32H7的支持、添加互补PWM功能的支持，补全pwm_get命令等

---

components/drivers/spi/spi_flash.h

[
使用fal的分区时创建mtd设备，打开RT_USING_MTD_NOR，spi_flash.h编译报错。
编译环境是mdk5
为spi_flash.h增加头文件包含:
#ifdef RT_USING_MTD_NOR
#include "drivers/mtd_nor.h"
#endif
在stm32f407vet6上使用mdk5环境做了测试，测试通过。
]
- [+ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [+] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- …

解决添加RT_USING_MTD_NOR编译报错的问题

---

bsp/mm32l07x/drivers/linker_scripts/link.icf
bsp/mm32l3xx/drivers/linker_scripts/link.icf

[
修复 MM32 在 IAR icf 文件中地址范围名称配置不正确的问题，以及去掉了不存在的 `EROM_region` 地址区间
]

[bsp] fix mm32 iar icf bugs

---

components/utilities/ulog/ulog.c

[
- 修复 ulog 后端颜色日志长度计算错误问题；
-  该修改已经在 ART-PI 开发板上验证通过；
]

[utilities][ulog] fix ulog backend color log length calculation error

---

components/dfs/filesystems/uffs/src/inc/uffs/uffs_flash.h
components/dfs/filesystems/uffs/uffs_nandif.c

[
For overriding various DATA/ECC/SEAL_BYTE layout on NAND flash.
Tested Winbond QSPI NAND on Nuvoton NUC980 platform.
]

Append RT_WEAK for overriding various ECC layout.

---

components/net/lwip_dhcpd/SConscript
components/net/lwip_dhcpd/dhcp_server.c

[
修复了在使用lwip 2.1.2协议栈时，使能dhcp serve服务后，编译报错的问题（lwip2.1.2没有了相关宏定义）。
在stm32f401-st-nucleo上测试通过
]

[fix] 修复使用lwip 2.1.2作为协议栈，并使能dhcp server选项时，编译报错问题。

---

bsp/ls2kdev/drivers/drv_spi.c

Bug Fixed : clock division cannot been adjusted as expected due to wrong register configuration.
[
修正了错误：由于寄存器配置错误，分频系数不能被设置成预期的。
Bug Fixed : clock division cannot been adjusted as expected due to wrong register configuration.
已在龙芯派第二代上测试过了
]

[BSP][LS2K][Bug fix]修正龙芯2K平台下SPI分频系数调节不正确的错误

---

bsp/stm32/libraries/HAL_Drivers/drv_qspi.c

[
问题：在STM32的drv_qspi.c文件中，struct stm32_hw_spi_cs成员为Pin，而在使用软件cs控制时，使用的却是pin，前后大小写不一致，导致编译报错。
解决办法，将成员pin全改为Pin。
已在stm32l475-atk-pandora开发板上验证通过。
]

修复在STM32的qspi驱动中，若定义BSP_QSPI_USING_SOFTCS开启软件cs引脚控制，则结构体成员pin大小写不一致的错误。

---

bsp/stm32/libraries/HAL_Drivers/drv_rtc.c
components/drivers/rtc/rtc.c
components/libc/compilers/common/sys/time.h
components/libc/compilers/common/time.c

[
1. libc time.c增加timegm函数（mktime转换是会自动考虑时区，timegm不会考虑时区）
2. 修复STM32 RTC驱动 格林威治时区与当地时区混用的问题
3. 整理了RTC驱动文件，看着改动比较大 实际上只是函数调换了位置 ，增加了注释
本次修改为后续增加时区功能做出铺垫，防止增加时区功能后，由于底层驱动没有区分time库中考虑时区和不考虑时区函数的区别，进而导致RTC时钟出现混乱。
在潘多拉上测试通过
]

[libc][stm32-driver RTC] 修复RTC驱动以及libc time.c库若干问题

---

components/libc/compilers/common/SConscript

[
对CLOCKS_PER_SEC宏进行重定义，受限于平台的不同规则，该功能仅能在keil中应用
GCC和IAR依然保持默认100
已经在keil平台潘多拉上验证
#3938
]

[libc][keil] 在sconscript中定义CLOCKS_PER_SEC宏

---

components/libc/compilers/armlibc/syscalls.c

[
实现_sys_tmpnam()函数
已经在keil上编译通过
已经在潘多拉上测试通过
#4337
]

[libc][keil]实现_sys_tmpnam()函数

---

bsp/imxrt/libraries/drivers/drv_spi.c

[
對imxrt的SPI傳輸改用非阻塞API
對imxrt的SPI傳輸使用信号量，確保傳輸完成后才退出傳輸函數
Use non-blocking api for spi transfer in imxrt driver
Use a semaphore to ensure xfer function return while the transfer is completed
已經在自製的imxrt1052 板子進行了測試
Had tested with a custom made imxrt1052 board
]

對imxrt的SPI傳輸改用非阻塞API

---

bsp/efm32/rtconfig.h
bsp/simulator/rtconfig_project.h
bsp/taihu/rtconfig.h
components/libc/compilers/common/readme.md
tools/building.py

[
去除在RTT中残留的RT_USING_NOLIBC痕迹
#4337
]

[libc] 去除RT_USING_NOLIBC 历史遗留

---

bsp/stm32/libraries/HAL_Drivers/drv_usart.c

[
STM32串口在8bits字长，使用奇偶校验时，比较奇葩，必须设置串口字长为9bits。如在使用posix接口进行配置时，不能进行正常通信。此PR修复这个错误。
]

[drv_usart.c]修复stm32串口开启奇偶校验时字长设置错误

---

components/net/netdev/src/netdev.c

[
Fix the problem for [ISSUE](https://github.com/RT-Thread/rt-thread/issues/4355).
have been tested on qemu.
* add a check for the length of netdev's name.
]

[fix] the wrong 'ifconfig' information for multi-network interface

---

src/thread.c
src/timer.c

[
rt_object_detach 是 初始化的内核对象的脱离。
（1）thread.c 的rt_thread_detach函数，有部分代码，前面有RT_ASSERT断言，应该永远走不到。
```
RT_ASSERT(rt_object_is_systemobject((rt_object_t)thread));
```
```
if (rt_object_is_systemobject((rt_object_t)thread) == RT_TRUE)
{
rt_object_detach((rt_object_t)thread);
}
else
{
/* disable interrupt */
lock = rt_hw_interrupt_disable();
/* insert to defunct thread list */
rt_list_insert_after(&rt_thread_defunct, &(thread->tlist));
/* enable interrupt */
rt_hw_interrupt_enable(lock);
}
```
else 分支，函数前，已经有断言，静态的内核对象，不需要这部分。
（2）timer.c 中：rt_timer_detach 函数：
```
rt_object_detach((rt_object_t)timer);
```
建议改为：
```
rt_object_detach(&(timer->parent));
```
理由是，rt_timer结构体，派生于rt_object。
```
/**
* timer structure
*/
struct rt_timer
{
struct rt_object parent;                            /**< inherit …
```

[update][kernel]规范rt_object_detach的使用

---

src/thread.c
src/timer.c

[
1、除了rt_thread，统一其他内核对象派生对象，rt_timer的操作。
2、消除上次提交，rt_thread.c 有一处未使用变量未移除，引起的编译报警。
只是代码规范，不影响功能。在模拟器、STM32L4平台验证通过
]

[update][kernel]规范rt_object_t强制转换的使用，消除上次提交的编译警告

---

bsp/stm32/stm32l475-atk-pandora/board/ports/sdcard_port.c

[
fix a bug that cannot use fatfs in the main thread at starting up
]

[bug][bsp][stm32][pandora] cannot use fatfs in the main thread at starting up

---

components/drivers/i2c/i2c-bit-ops.c

msg->flags is accessed without proper intialized msg variable.
[
When pass num=0 to i2c_bit_xfer, the uninitialized msg will be accessed in order to check the flags. This may lead to unintentionally i2c_stop. Add a shortcut return when num is 0.
Tested on stm32.
]

Return when i2c transfer 0 messages

---

libcpu/arm/cortex-m33/cpuport.c

[
O0 优化与 O2 优化函数行为有偏差。导致不同优化等级，调用该函数会宕机
调整实现方式，确保不同优化等级下，函数行为移植。
验证不同优化等级下，编译出的汇编代码行为是否一致。
]

[libcpu][cm33] 修复不同优化等级，函数行为不一致的问题

---

components/drivers/src/waitqueue.c

[
修改一下 `queue->flag` 为下面的方式
`queue->flag = RT_WQ_FLAG_CLEAN;` 
修改后比原来 `queue->flag = 0;`  更易理解
]

[fix] wait queue flag 赋的值使用宏

---

include/rtdbg.h

…NG_ULOG not defined
[
修复在没有定义 RT_USING_ULOG 时调用 LOG_HEX 出现未定义错误的问题.
stm32f103x 平台编译通过
]

[rtdbg] Fix compile error when using LOG_HEX function but RT_USING_ULOG not defined

---

bsp/bluetrum/ab32vg1-ab-prougen/board/board.c

[
最新rtt在开启POSIX函数后必须实现rt_hw_us_delay()函数，在sleep()函数中会用到该函数，进行精确延时，如果没有实现可以直接返回空函数不进行us级延时，以防止报错。
]

[ab32vg1] 增加rt_hw_us_delay()函数防止报错

---

src/thread.c

[
rt_thread_delay_until存在以下问题：
1. 延时时间不准
已在cortex-a8开发板测试.
]

修正rt_thread_delay_until时间不准问题

---

bsp/stm32/libraries/HAL_Drivers/drv_sdram.c
bsp/stm32/stm32f746-st-disco/board/CubeMX_Config/Src/stm32f7xx_hal_msp.c
bsp/stm32/stm32f746-st-disco/board/Kconfig

STM32F7XX 系列中开启 SDRAM 后，可用的空间只有 1MB，对超过 1MB 的访问将会产生 Overwrite。例如对 0xC0100000 的修改将会引起 0xC0000000 的变化。跟官方 HAL 库提供的 DEMO 对比来看，产生这种错误的原因在于函数`HAL_FMC_MspInit` 中少了几个 GPIO 引脚的初始化，导致实际的寻址空间错误。本 PR 中仿照官方 HAL 库对代码进行了修改。
而且，在 `sdram_test` 中由于写入 SDRAM 的内容都是一样的，无法检测出 Overwrite。本 PR 修改了写入的测试数据。
同时在 KConfig 中，缺少了`BSP_USING_FMC`的说明，导致在 MenuConfig 中无法显示。本 PR 补充了它的说明。
本次修改已在 STM32F746G-DISCO 上测试通过。

[bsp]fix overwrite issue when using SDRAM on STM32F7XX

---

bsp/bluetrum/ab32vg1-ab-prougen/board/Kconfig
bsp/bluetrum/ab32vg1-ab-prougen/rtconfig.py
bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/include/ab32vg1_hal_rtc.h

[
修复 sizeof(time_t) 和实际 AB32VG1 的寄存器不匹配问题
修复之前，测试 RTC 驱动
```
\ | /
- RT -     Thread Operating System
/ | \     4.0.3 build Mar 19 2021
2006 - 2021 Copyright by rt-thread team
Hello, world a
msh >date
found rtc sizeof time_t=8
111111 time_now=0x10
over found rtc
now=-1
xmsh >
```
修复之后，测试 RTC 驱动
```
\ | /
- RT -     Thread Operating System
/ | \     4.0.3 build Mar 19 2021
2006 - 2021 Copyright by rt-thread team
Hello, world a
msh >
msh >date
found rtc sizeof time_t=4
111111 time_now=0x60135001
over found rtc
now=1611878401
Fri Jan 29 00:00:01 2021
msh >
```
在 AB32VG1 板子测试通过
] …

[bsp][ab32vg1] Fix sizeof(time_t) no match with this chip

---

bsp/bluetrum/ab32vg1-ab-prougen/board/Kconfig
bsp/bluetrum/libraries/hal_drivers/drv_rtc.c
bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/include/ab32vg1_hal_rtc.h

[
添加 AB32VG1 的 RTC 驱动 alarm 和 1s 中断支持
在 AB32VG1 板卡测试通过
]

[bsp][ab32vg1] Add alarm and 1 second interrupt support

---

components/drivers/spi/sfud/src/sfud.c

[
Correct DUAL_IO Fastread dummy cycle to 4.
Checked dummy cycle of supported DUAL_IO flashes in SFUD is 4.
]

[sfud] Correct dual_io dummy cycle setting to 4.

---

bsp/nrf5x/nrf52832/rtconfig.py
bsp/nrf5x/nrf52840/rtconfig.py
bsp/nrf5x/tools/sdk_dist.py

[
完善了nRF52832和nRF52840 bsp的'scons --dist'功能，经过测试导出的dist目录下的项目可以正常编译。
]

[UPD]nRF5x 'scons --dist' support

---

components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c
components/net/sal_socket/src/sal_socket.c

[
* have tested on qemu-a9, stm32f407-atk
accord to ```enum netdev_cb_type``` , the ```netdev->callback``` should include UP/DOWN LINK_UP/LINK_DOWN INTERNET_UP/INTERNET_DOWN status. But we haven't INTERNET_UP/INTERNET_DOWN status callback before.
```c
enum netdev_cb_type
{
NETDEV_CB_ADDR_IP,                 /* IP address */
NETDEV_CB_ADDR_NETMASK,            /* subnet mask */
NETDEV_CB_ADDR_GATEWAY,            /* netmask */
NETDEV_CB_ADDR_DNS_SERVER,         /* dns server */
NETDEV_CB_STATUS_UP,               /* changed to 'up' */
NETDEV_CB_STATUS_DOWN,             /* changed to 'down' */
NETDEV_CB_STATUS_LINK_UP,          /* changed to 'link up' */
NETDEV_CB_STATUS_LINK_DOWN,        /* changed to 'link down' */
NETDEV_CB_STATUS_INTERNET_UP,      /* changed to 'internet up' */ …
```

[add] the function of set [internet up] status, activate the callback.

---

components/drivers/sdio/mmc.c

现有的MMC 设备在切换数据宽度的时候，会遇到切换失败的情况。以前没问题，现在换了一个emmc之后出现了问题。
溯源发现是发送切换指令后，等待时间不够长。这里我把原来的20ms固定的delay换成多次尝试。成功使新的emmc切换到8bit宽度。
When switching data width in emmc car, try a few times before considering the width is invalid (leave a longer timer for the card to prepared). 
The original strategy (simply wait for 20ms ) failed on STM32H743 with an MTFC4GACAJCN-4M (4GB EMMC) when switching data width. 
(unless the debugging info is enabled, which add more delays)
With this EMMC, the fixed delay was set to 50ms for it to be able to work. 
Instead of increasing the fixed delay, I think we better change the strategy to trying a few more times with smaller delays.
This change was validated on a customized board with STM32H743BI and  MTFC4GACAJCN-4M and THGBMNG5D1LBAIT (Both are 4 GB emmc ). The …

Add more trys when switching MMC card data width

---

tools/mkdist.py

Use this command: `scons --dist-strip` to detach project. but it aborted with error: "TypeError: dist_handle() takes exactly 2 arguments (1 given):"
[
使用 scons --dist-strip 命令导出 bsp 里的项目，抛出异常：TypeError: dist_handle() takes exactly 2 arguments (1 given)
发现是 tools/mkdist.py 脚本里 MkDist_Strip 函数调用 dist_handle 时少了一个参数，加上之后就好了；MkDist 函数里是正常的
]

[fix] miss arguments when invoke dist_handle

---

bsp/stm32/libraries/HAL_Drivers/config/f0/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/f1/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/f2/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/f4/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/f7/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/g0/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/g4/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/h7/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/l1/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/l4/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/mp1/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/wb/spi_config.h
bsp/stm32/libraries/HAL_Drivers/config/wl/spi_config.h
bsp/stm32/libraries/HAL_Drivers/drv_spi.c
bsp/stm32/libraries/HAL_Drivers/drv_spi.h
bsp/stm32/stm32f072-st-nucleo/board/Kconfig

[
本 PR 是修复 gitee 上的一个 [issuse](https://gitee.com/rtthread/rt-thread/issues/I3NDPA)
在使用 SPI DMA 收发时需要使能外设中断，查看了 `stm32f407-atk`  这个 BSP 在 msp.c 中就打开了外设中断，然后能正常工作，所以就有了 issues 提到的中断未开启导致 DMA 方式接受失败的问题。
这个中断的使能，如果在 cubemx 配置了，就会在 msp.c 文件生成，如果没有配置，就需要在驱动层去配置。这个中断应该在哪个地方使能，目前没有看到有具体的说法。
查看了 uart 和 eth 的驱动，发现中断的使能都是在驱动层，因此有了本次的 PR。
本次提交在 `stm32f407-atk`  和 `ART-Pi` 测试通过。
] …

[add] spi config increases irq_type

---

components/libc/compilers/common/sys/time.h
components/libc/compilers/common/time.c
components/libc/compilers/newlib/SConscript

[
去除没有用的宏定义 _TIMESPEC_DEFINED 该定义未在newlib或者musl中出现
细微调整了代码格式
gcc keil iar编译通过
]

[libc][time] remove _TIMESPEC_DEFINED in common/sys/time.h and complete time.c

---

components/libc/compilers/common/sys/mman.h
components/libc/compilers/common/sys/time.h
components/libc/compilers/common/time.c

[
1.优化gettimeofday/settimeofday
2.规范set_timeval/get_timeval函数返回值
3.考虑到使用time.c时，libc可能没有开启，因此由errno改为rt_set_errno
至此，简易版时区功能支持完毕。所谓简易版即时区为只能手动更改且固定不变。与简易版相对的是完整版即支持夏令时功能的版本。
简易版对中国用户没有影响，因为中国的时区永远是UTC+8。默认即为中国时区。对于中国用户而言，可认为至此RTT已经完全支持时区功能。但是简易版对欧美国家并不友好，因为欧美国家一般采用夏令时的方式，简易版时区无法支持夏令时功能。
夏令时功能将在4.0.4发布之后支持，不作为近期支持计划。夏令时功能支持起来非常麻烦。
https://github.com/RT-Thread/rt-thread/pull/4653
] …

[libc][time]优化gettimeofday/settimeofday; 规范set_timeval/get_timeval函数返回值

---

components/net/Kconfig

[
LWIP官方表示2.0.2在发布时意外带入了一些bug，建议用户尽快升级到2.0.3，因此默认2.0.2并不合适。默认版本改为最新稳定版2.1.2. 详见：http://savannah.nongnu.org/forum/forum.php?forum_id=8953
顺便建议2.0.2版本也尽快升级到2.0.3吧，2.0.3也是相当不错的稳定版本
]

[network][lwip][kconfig] 默认LWIP协议栈版本由2.0.2转为2.1.2

---

components/utilities/Kconfig
components/utilities/ymodem/SConscript

目前开启的逻辑存在问题，ymodem的文件传输功能开启的前提是得有完整的文件系统，
但是目前，这个开启逻辑错了。
用户选择YMODEM_USING_FILE_TRANSFER功能后select DFS没有任何意义，因为除了需要依赖DFS之外还要依赖其他的例如FATFS，需要和SDIO适配等等等
正确的做法应该是用户配置好完整的文件系统后，ymodem文件传输才能有机会开启，
因此是depends on DFS 而非select DFS
更改之后，只要用户开启了文件系统，在选定YMODEM时，会自动开启文件传输功能，这也是用户希望看到的，直接一键搞定，不需要再多点一步
https://club.rt-thread.org/ask/question/431237.html

[ymodem] 修改YMODEM_USING_FILE_TRANSFER功能的开启条件

---

components/finsh/msh.c

[
- 修复msh_exec函数内部访问内存越界的问题
- 关于shell中内存访问越界（只读越界）的复现方法：
往shell中输入如下字符串（两组）回车：
第一组（第一个字符空格，79个其它可打印字符）：
` aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
第二组（全空格80个）：
```TEXT
```
]

fix shell msh_exec memory over-bound.

---

src/clock.c

[
对 #4741 做出补充，由于滴答时钟中断一般位于最低优先级，该函数内的全局变量必须予以保护，以防止用户在高优先级中断中修改对应全局变量时造成意外。
类似：https://github.com/weston-embedded/uC-OS3/blob/develop/Source/os_tick.c#L94-L129
stm32f407探路者测试通过
]

[kernel]对rt_tick_increase临界区进行保护

---

src/mem.c
src/memheap.c
src/slab.c

[
rt_malloc,rt_free函数内部也是调用的以fifo创建的信号量，也就是说凡是调用rt_malloc rt_free的线程都会导致该线程超出用户意料之外的非实时，可能会导致超出deadline。进言之，rt_thread_create rt_thread_delete rt_sem_create等等这些调用rt_malloc函数的动态创建内核对象的api都存在非实时的问题，最可怕的是这些问题用户并不会察觉，用户并不清楚调用上述api会导致自己的线程处于非实时状态。
]

[bug][kernel][heap] 将内存堆信号量保护机制由FIFO改为PRIO

---

components/libc/compilers/common/unistd.c

[sleep] 加入调度器尚未运行时的延时情况

---

bsp/w60x/drivers/pin_config.h

[
问题描述：https://gitee.com/rtthread/rt-thread/issues/I3UHB8
]

[w60x] 修复UART1功能无法使用

---

src/ipc.c

[kernel] Fix comment error for rt_mutex_detach().

---

components/finsh/shell.c
include/libc/libc_signal.h
include/rtlibc.h
include/rtthread.h
src/components.c
src/kservice.c

[
__CC_ARM 是 arm的内置宏定义 只适用于AC5
__CLANG_ARM 是rtt的宏定义 由于arm内部并没有直接表示armclang AC6的宏，因此rtt内部创造了一个
在rtt代码中判断编译器是否为keil（不区分AC5 还是AC6）时，可以使用__ARMCC_VERSION来代替(__CC_ARM) || (__CLANG_ARM) 这种写法，因为这种写法必须包含rtthread.h，有可能引发类似于 https://github.com/RT-Thread/rt-thread/issues/3720 所述的问题。
keil官方手册中给出的定义是，凡是使用keil编译器的话，__ARMCC_VERSION 即会被定义。
]

将defined(__CC_ARM) || defined(__CLANG_ARM) 改为 ifdef __ARMCC_VERSION

---

examples/utest/testcases/Kconfig
examples/utest/testcases/drivers/SConscript
examples/utest/testcases/drivers/serial_v2/Kconfig
examples/utest/testcases/drivers/serial_v2/README.md
examples/utest/testcases/drivers/serial_v2/SConscript
examples/utest/testcases/drivers/serial_v2/uart_rxb_txb.c
examples/utest/testcases/drivers/serial_v2/uart_rxb_txnb.c
examples/utest/testcases/drivers/serial_v2/uart_rxnb_txb.c
examples/utest/testcases/drivers/serial_v2/uart_rxnb_txnb.c

[
该测试用例配合这个PR[[serial] 增加serial_v2版本的框架和基于stm32的串口驱动](https://github.com/RT-Thread/rt-thread/pull/4764#partial-pull-merging)验证新版本的串口框架。
测试用例包含四个文件，分别为串口 发送阻塞接收非阻塞、发送阻塞接收阻塞、发送非阻塞接收非阻塞、发送非阻塞接收阻塞这种操作模式进行测试。
以上四种操作模式，需要结合硬件的配置模式一起工作。例如 发送阻塞接收非阻塞 ，这个测试有很多种硬件配置，配置情况例如：DMA发送阻塞DMA接收非阻塞，INT发送阻塞DMA接收非阻塞，POLL发送阻塞DMA接收非阻塞等等。因此通过排列组合后的测试场景有4*9=36种，有意义的组合方式为20种。如下表：
| 接收非阻塞 | 发送阻塞 | 组合              | 有意义的组合方式 |
| ---------- | -------- | ----------------- | ---------------- |
| POLL       | POLL     | RX_POLL + TX_POLL |                  |
|            | INT      | RX_POLL + TX_INT  |                  |
|            | DMA      | RX_POLL + TX_DMA  |                  |
| INT        | POLL     | RX_INT + TX_POLL  | ✔                |
|            | INT      | RX_INT + TX_INT   | ✔                |
| …

[testcase] 增加serial_v2的测试用例

---

components/net/sal_socket/src/sal_socket.c

[
背景：应用中有一个AT网卡，有一个LWIP网卡，AT的网卡先初始化，被设置为默认网卡，设备也需要4G用来访问公网。 同时设备基于lwip网卡上运行了webnet组件，跑了webserver，用以设备配置业务。 webnet初始化时绑定的网卡为本地lwip网卡，设备初始化正常，设备使用list_webnet能看到浏览器发来的请求，但是无法收发数据。 在sal组件中，accept底层调用的了socket_init函数，该函数创建的socket绑定的网卡是默认网卡（AT网卡），导致数据收发不正常。
解决的问题：tcp server调用 accept函数创建的网卡绑定错误。
解决方案:accept创建的socket使用和server一致的网卡
测试办卡： STM32F407 自研板卡   lwip+at(ec20)+webnet
] …

修订多网卡应用下，accept创建socket绑定网卡错误的问题

---

components/drivers/serial/serial.c

[
解决STM32串口使用DMA接收方式时，清空缓存bug
因为驱动层DMA使用循环接收方式，这里粗暴的把索引清零将会导致数据错乱
]

[drivers]serial.c

---

src/ipc.c

[
信号量、消息队列、消息邮箱其FIFO功能，还有保留的意义。但是互斥量的FIFO没有任何存在的意义。
互斥量诞生之初就是为了解决信号量带来的无界优先级反转问题(Sha, 1990)，而FIFO flag却恰恰人为引入了无界优先级反转的问题，这与互斥量的出现目的背道而驰。
再想一个问题，请问互斥量的FIFO和信号量的FIFO 有什么区别呢，答案是没有任何区别，那么直接用信号量的FIFO好不好呢？
因此解决方法为直接移除FIFO flag，无论用户选择FIFO 还是PRIO 一律按照PRIO处理。
]

[kernel][ipc] 移除mutex RT_IPC_FLAG_FIFO 功能

---

components/net/at/src/at_client.c
components/net/at/src/at_server.c
components/net/at/src/at_utils.c

[
修改 at_vprintf 可能导致的指针溢出
更改 at_vprintfln 使命令和新行一起发送
完善 end_sign 的响应机制
在项目中验证过
]

fix at_vprintf and at_vprintfln and end_sign response

---

src/kservice.c

[
在`kservice.c`中，`_console_device`设备在系统启动时打开了两次。
1. 第一次是调用`rt_device_t rt_console_set_device(const char *name)`。打开的`oflag`为`RT_DEVICE_OFLAG_RDWR | RT_DEVICE_FLAG_STREAM`
2. 第二次是在finsh线程`void finsh_thread_entry(void *parameter)`中。打开的`oflag`为`RT_DEVICE_OFLAG_RDWR | RT_DEVICE_FLAG_INT_RX |  RT_DEVICE_FLAG_STREAM`
基于以上情况，在多核环境下，`rt_kprintf`中的以下逻辑可能会覆盖掉`finsh`线程设置的`RT_DEVICE_FLAG_INT_RX` `oflag`
```c
rt_uint16_t old_flag = _console_device->open_flag;
_console_device->open_flag |= RT_DEVICE_FLAG_STREAM;
rt_device_write(_console_device, 0, rt_log_buf, length);
_console_device->open_flag = old_flag;
```
覆盖逻辑如下：
1. CORE0 调用`rt_kprintf`，执行完`rt_uint16_t old_flag = _console_device->open_flag;`
2. CORE1 执行`finsh`线程打开`_console_device`并设置oflag为`RT_DEVICE_OFLAG_RDWR | RT_DEVICE_FLAG_INT_RX | …

[components][kernel] 解决多核下 finsh 不能响应串口输入问题

---

components/net/at/at_socket/at_socket.c

[
解决at_socket在极限情况下内存泄漏问题，分2点：
1. AT模块在执行AT+CLOSE并返回OK后，在实际关闭前（上报URC前）仍然有可能接收到数据。所以接收数据时需要判断状态是否为AT_SOCKET_CONNECT。
2. at_recv_notice_cb在拒绝数据包时，没有释放数据包内存，从而导致内在泄漏。
另，在拉取最新代码编译时，at_socket.c编译不过。这是由libc改动所导致。这次顺便把这编译问题也解决掉。
在基于stm32芯片自建的bsp中验证通过。
]

解决at_socket内存泄漏问题

---

components/libc/Kconfig
components/libc/compilers/common/sys/time.h
components/libc/compilers/common/time.c

[
增加动态设置时区接口
rt_tz_set 设置时区函数
rt_tz_get 获取时区函数
rt_tz_is_dst 获取夏令时信息（目前没用）
上述三个函数不属于标准C库或者linux函数的一部分
由于模仿linux行为来进行时区的调整会占用大量资源
因此针对嵌入式的场景，创建了上述三个函数。
]

[libc][timezone] implement timezone APIs

---

components/drivers/include/ipc/workqueue.h
components/drivers/src/workqueue.c

[
将rt_work_sys_workqueue_init函数设为私有
]

[workqueue] 将rt_work_sys_workqueue_init函数设为私有

---

components/drivers/include/drivers/mmcsd_core.h
components/drivers/sdio/block_dev.c

[
移除 rt_mmcsd_blk_init函数 该函数已经废弃
]

[sdio] remove rt_mmcsd_blk_init

---

components/drivers/include/ipc/workqueue.h
components/drivers/src/workqueue.c
components/net/sal_socket/src/sal_socket.c

[
The first time that the function `rt_delayed_work_init` was implemented and submitted was on #2463 in 2019.
However, after several contributions, this function has been meaningless but another version of `rt_work_init`.
Thus, this function should be removed.
]

[workqueue] remove rt_delayed_work_init()

---

src/irq.c
src/timer.c

[fix the comment of the irq.c and timer.c]

[kernel] add the comment of irq.c and timer.c

---

bsp/stm32/stm32f407-atk-explorer/board/ports/drv_filesystem.c

[
由于fal_init支持反复调用，
PR https://github.com/RT-Thread-packages/fal/pull/32 https://github.com/RT-Thread/packages/pull/997 取消
因此配合上述两个PR的宏FAL_USING_AUTO_INIT也取消掉
]

[stm32f407-explorer] remove FAL_USING_AUTO_INIT

---

examples/utest/testcases/kernel/Kconfig
examples/utest/testcases/kernel/SConscript
examples/utest/testcases/kernel/irq_tc.c

[utest][kernel_irq] add the utest of irq

---

components/finsh/shell.c
components/finsh/shell.h

[
目前在finsh线程中如果使用getchar函数，必须开启DFS，ROM一下子飙升40KB，但是完全可以通过finsh_getchar函数替代libc的getchar函数，因此需要将finsh_getchar函数暴露出来。
]

[finsh] 将finsh_getchar函数暴露出来

---

components/drivers/include/ipc/ringblk_buf.h
components/drivers/src/ringblk_buf.c
components/net/at/src/at_client.c

[
1. 在不使用动态内存分配的时候 ringblk_buf 会报错，使用 RT_USING_HEAP 宏定义来隔离
2. 更改 at_client_obj_recv，从原来的长度不对就返回 0 变更为返回收到的字节数
]

修复 ringblk_buf 在不使用动态内存时报错的问题以及 AT 组件优化

---

components/utilities/ulog/ulog.c

[
#ifdef(RT_USING_FINSH)在keil mdk 上编译报语法错误不能通过，编译器为compiler version 5。
]

fix Macro definition syntax error in ulog.c

---

components/net/lwip-2.1.2/src/include/netif/ethernetif.h
components/net/lwip-2.1.2/src/netif/ethernetif.c

The ethernetif use semaphore netif->tx_ack to protect the local variable
`struct eth_tx_msg msg` in function `ethernetif_linkoutput`. But the
function could be called in multiple context: LwIP "tcpip" thread, "erx"
thread(on linkup) and any user thread that call `udp_sendto`. So the
global semaphore protection is not sufficient. It could only wakeup the
top priority waiting thread instead of the thread that owns the `msg`
and may result the `msg` next in the mailbox got destructed.
So to use a `rt_completion` within the `struct eth_tx_msg` and
synchronize on that. This could deal the ownership issue in an easy way.
- [] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered …

[Netif] Fix the eth_tx_msg protection

---

bsp/x86/drivers/floppy.c
components/dfs/src/dfs_posix.c

[
problem description: https://github.com/RT-Thread/rt-thread/pull/5056
related pr: https://github.com/RT-Thread/rt-thread/pull/5053
]

[libc] fix the conflict warning of read and write functions

---

bsp/wch/arm/Libraries/ch32_drivers/SConscript
bsp/wch/arm/Libraries/ch32_drivers/drv_hwtimer_ch32f10x.c
bsp/wch/arm/Libraries/ch32_drivers/drv_pwm_ch32f10x.c
bsp/wch/arm/ch32f103c8-core/board/Kconfig
bsp/wch/arm/ch32f103c8-core/board/board.c
bsp/wch/arm/ch32f103c8-core/board/board.h

[
更改函数名ch32f1_hwtimer_clock_init, ch32f1_hwtimer_clock_get为ch32f1_tim_clock_init，ch32f1_tim_clock_get；
实现PWM驱动；
以上在ch32f103c8测试通过。
]
- [ X] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [ X] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ X] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, …

support ch32f10x pwm driver.

---

components/libc/Kconfig

[
该问题在修复 https://github.com/RT-Thread/rt-thread/pull/5099 时被发现，部分应用程序如dfs_elm.c仅通过RT_LIBC_USING_TIME来判断是否使用time相关功能，但是一直以来该宏定义是定义在仅当libc不存在时，一旦libc开启，该宏定义将不会再定义，因此在当前代码下，通过RT_LIBC_USING_TIME判断是否可以使用time相关功能并不准确。但是修改后，用户就可以通过RT_LIBC_USING_TIME来判断是否可以开启time相关功能了。
也就是说 以后，可以通过RT_LIBC_USING_TIME一个宏定义直接来判断time相关功能是否可用。
]

[libc]在开启libc后依然保持RT_LIBC_USING_TIME定义存在

---

src/Kconfig
src/memheap.c

[
1. memheap版本的rt_malloc实现中，当主内存堆heap无法分配内存时，之前会自动从其它块分配。现增加一个开关，默认建议关闭，以禁用这种特性，确保分配出来的内存特性可控。
]

优化memheap内存管理：1.自动多块粘合可配置；

---

components/libc/compilers/common/stdlib.c

[
system函数之前只留了接口，处于TODO状态。现社区小伙伴有需求，遂实现。
https://club.rt-thread.org/ask/question/433032.html
潘多拉测试通过。支持keil iar平台，但是目前还不支持gcc
优化了exit() abort()函数的警告输出
]

[libc][keil][iar] 支持system函数

---

bsp/stm32/libraries/HAL_Drivers/drv_wdt.c

…o use "stm32_wdt.hiwdg.Init.Window = 0x00000FFF", otherwise the watchdog always reset.
[
[bsp/stm32/libraries/HAL_Drivers/drv_wdt.c]: 添加SOC_SERIES_STM32G0宏，以便初始赋值(“stm32_wdt.hiwdg.Init.Window = 0x00000FFF”)，否则会出现不断重启的问题。
以上使用软件包syswatch在stm32g031f8p6测试通过。
]
- [ x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [ x] 已经仔细查看过代码改动的对比 …

[bsp/stm32/libraries/HAL_Drivers/drv_wdt.c]: add SOC_SERIES_STM32G0 to fix wdt always reset.

---

libcpu/risc-v/t-head/e9xx/context_gcc.S
libcpu/risc-v/t-head/e9xx/cpuport.c

[fix][libcpu][riscv][t-head] fix rt_hw_interrupt_disable/rt_hw_interupt_enable bug
使用不同的优化等级会出现不同的效果
当使用-O0 等级时，无法正确得到关闭中断之前的状态
Using different optimization levels will have different effects
When the - o0 level is used, the state before the shutdown interrupt cannot be obtained correctly
[
> 原始代码
```c
rt_base_t rt_hw_interrupt_disable(void)
{
__asm volatile("csrrci a0, mstatus, 8");
return;
}
```
> 使用 -O2 优化等级编译结果
```assembly
rt_base_t rt_hw_interrupt_disable(void)
{
__asm volatile("csrrci a0, mstatus, 8");
11fbe:	30047573          	csrrci	a0,mstatus,8
return;
}
11fc2:	8082                	ret
```
> 使用 -O0 优化等级编译结果
```assembly
rt_base_t rt_hw_interrupt_disable(void)
{
1494a:	1141                	addi	sp,sp,-16
1494c:	c622                	sw	s0,12(sp)
1494e:	0800                	addi …
```

[fix][libcpu][riscv][t-head] fix rt_hw_interrupt_disable/rt_hw_interupt_enable bug

---

src/Kconfig
src/kservice.c

[
这份PR的目的是增加一种新的查找字节最低非0位的算法，该算法比一般的位图算法更省空间，同时对于 32bit以及更长的字节，该算法查找字节最低非0位的实现路径也更加高效。
该算法的原理为：假设 X 为 uint32_t 类型的变量， 则 X & (X - 1) ^ X 的算式可以得到仅含字节最低非0位的结果，也就是将所有的可能转变为仅有的32种可能，也就是32个 “1在不同bit位” 的数，接着将这32个数对 37 取余，能够得到互不相同的结果，利用这些结果建立一个位图表，就能实现在O(1)的时间复杂度上查找到目标结果。
该算法已经经过测试程序对比，输入所有可能的输入，得到的结果与之前的位图算法相同。

[kernel]增加一种新的查找字节最低非0位的算法

---

components/libc/compilers/common/nogcc/fcntl.h
components/libc/compilers/common/nogcc/unistd.h
components/libc/compilers/gcc/newlib/fcntl.h

[
此PR旨在修复 https://github.com/RT-Thread/rt-thread/issues/5186 和 https://github.com/RT-Thread/rt-thread/issues/5265 所报告的问题
This PR will fix the problem which is reported by 5265 and 5186
经过再次查证，这个不是arm-链的问题，
历史上fcntl.h有两种标准，一个是以16进制进行编码的版本 也就是newlib arm链用的https://github.com/bminor/newlib/blob/80cda9bbda04a1e9e3bee5eadf99061ed69ca5fb/newlib/libc/include/sys/_default_fcntl.h
还有一种是8进制编码的标准 也就是rtt给keil iar以及musl库用的 https://github.com/bminor/musl/blob/cfdfd5ea3ce14c6abf7fb22a531f3d99518b5a1b/arch/arm/bits/fcntl.h
这两种标准的编码值并不相同，因此造成了冲突，这个问题是我在4.0.4整理libc时引入的。目前已经修复了。
] …

[libc] 修复在fcntl.h中两种不同的宏编码方式导致的bug

---

components/libc/Kconfig
components/libc/compilers/armlibc/mem_std.c
components/libc/compilers/armlibc/syscalls.c
components/libc/compilers/dlib/syscall_close.c
components/libc/compilers/dlib/syscall_lseek.c
components/libc/compilers/dlib/syscall_mem.c
components/libc/compilers/dlib/syscall_open.c
components/libc/compilers/dlib/syscall_read.c
components/libc/compilers/dlib/syscall_remove.c
components/libc/compilers/dlib/syscall_write.c
components/libc/compilers/gcc/newlib/syscalls.c

[libc]重新梳理read write桩函数实现

---

bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_l4.c

[
问题:stm32l4系列MCU在下载完程序后，首次进行擦除会出现失败。
解决:drv_flash_l4.c文件，stm32_flash_erase函数中，清除的flash标志位增加FLASH_FLAG_PGSERR。
在stm32l431，stm32l475上测试通过。
]

[drv_flash_l4.c]修复stm32l4系列flash在下载完程序后首次擦除会失败的问题

---

components/Kconfig
components/dfs/SConscript
components/legacy/README.md
components/legacy/SConscript
components/legacy/dfs/dfs_poll.h
components/legacy/dfs/dfs_select.h
components/legacy/ipc/workqueue_legacy.c
components/legacy/ipc/workqueue_legacy.h
components/legacy/rtlegacy.h
include/rtthread.h

[
增加legacy功能/组件，将淘汰或者废弃的功能放在legacy下，确保用户可以在未来的版本中继续使用老版本的功能，同时也可以保证rt-thread不被历史包袱所裹挟，轻装上阵。
利用此种方法，可以确保rt-thread在未来所有版本都可以支持老版本的函数和头文件，而且未来版本不会因兼容性而束缚住手脚。
]

implement legacy support

---

components/drivers/serial/serial.c
components/libc/Kconfig
components/libc/compilers/common/sys/time.h
components/libc/compilers/common/time.c
components/libc/posix/getline/SConscript
components/libc/posix/getline/posix_getline.c
components/libc/posix/src/SConscript
components/lwp/Kconfig
components/net/Kconfig

[
- RT_USING_POSIX_FS 是 剥离RT_USING_POSIX有关的关键一步，在之前的RT_USING_POSIX宏中，不管posix相关的功能是否需要文件系统，都会强迫选定文件系统。
- 整理之后增加RT_USING_POSIX_FS ， 把和文件系统相关的集中在RT_USING_POSIX_FS 目录之下，其他不需要posix文件系统的与RT_USING_POSIX_FS并列，不必强制选定文件系统。
- 同时RT_USING_POSIX_FS 也是作为快捷键，方便熟悉posix但是不熟悉rt-thread的用户，可以不必翻来翻去找去配置dfs，直接RT_USING_POSIX_FS一键搞定, RT_USING_POSIX_FS 内部会自动选定RT_USING_DFS以及DFS_USING_POSIX
STM32潘多拉测试通过, 忽略CI报警
注意：RT_USING_POSIX_FS和 RT_LIBC_USING_FILEIO宏定义属于方便用户的快捷方式，在sconscript脚本中不能使用GetDefine('RT_LIBC_USING_FILEIO') 来判断，要用GetDefine('DFS_USING_POSIX')来判断；RT_LIBC_USING_FILEIO同理。
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a …

[PSE分支] 增加RT_USING_POSIX_FS

---

bsp/qemu-virt64-aarch64/link.lds
bsp/raspberry-pi/raspi3-64/link.lds
bsp/raspberry-pi/raspi4-64/link.lds
libcpu/aarch64/common/context_gcc.S
libcpu/aarch64/common/stack.c
libcpu/aarch64/common/vector_gcc.S
libcpu/aarch64/cortex-a/entry_point.S
src/thread.c

[
修改aarch64 栈指针为当前异常级别的栈指针
修改aarch64清理bss段步长的汇编代码，同时更正对应bsp对bss段size的定义
]

fixup .bss size define in link.lds and set spsel=1 in aarch64

---

tools/building.py

[
本pr旨在修复创建时没有剔除空白object的问题：
对以下两种情况进行检查：
1. 检查列表中是否有空字符串，如果有就剔除掉
2. 检查列表是否为空列表，如果是空列表，说明给定的参数是无效的，不加入到env中。
依然存在的问题，需要其他PR来处理：
1.添加的参数在其他Group是否已经添加过了，即需要做防重复添加检查；
2.在src为空的情况下，就不需要添加group名了，否则会在IAR里创建一个空的工程文件夹出来。
3.local_group 没有处理
]

[tools][building.py] 修复加入空列表和空字符串的问题

---

bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
bsp/stm32/stm32l475-atk-pandora/board/Kconfig
components/cplusplus/Kconfig
components/drivers/src/pipe.c
components/libc/Kconfig
components/libc/compilers/armlibc/syscalls.c
components/libc/posix/Kconfig
components/utilities/ymodem/ry_sy.c

[
替换宏定义; 将posix单独划分为一个Kconfig目录
目前RT_USING_DFS在bsp里边的没有增加select DFS_USING_POSIX, 这个不作为强制选定，让用户自己确定是否使用read还是dfs_file_read (默认DFS_USING_POSIX为y)
DMODULE的RT_USING_POSIX暂时不替换，等dfs_posix.h脱敏的时候一起替换掉就可以了，这个暂时不对主代码构成影响。
]

[PSE分支] 替换宏定义 将posix单独划分为一个Kconfig目录

---

components/utilities/ulog/backend/console_be.c
components/utilities/ulog/ulog.c
components/utilities/ulog/ulog.h
components/utilities/ulog/ulog_def.h

为每个 ulog 后端增加独立的过滤器，方便控制每个后端的输出方式
大致用法：
- 定义过滤器函数
```c
rt_bool_t console_backend_filter(struct ulog_backend *backend, rt_uint32_t level, const char *tag, rt_bool_t is_raw,
const char *log, size_t len)
{
rt_uint32_t setting_level = DBG_INFO;
if (level > setting_level && rt_strstr(log, "XYZ") != RT_NULL)
{
return RT_TRUE;
}
else
{
return RT_FALSE;
}
}
```
- 在代码中设置过滤器，可以看到只有符合过滤器条件的日志才会被输出
```C
ulog_backend_set_filter(ulog_backend_find("console"), console_backend_filter);
```

[ulog] Add ulog backend filter.

---

components/net/lwip-1.4.1/src/arch/include/arch/cc.h
components/net/lwip-1.4.1/src/arch/include/arch/sys_arch.h
components/net/lwip-1.4.1/src/lwipopts.h
components/net/lwip-2.0.2/src/arch/include/arch/cc.h
components/net/lwip-2.0.2/src/arch/include/arch/sys_arch.h
components/net/lwip-2.0.2/src/lwipopts.h
components/net/lwip-2.0.3/src/arch/include/arch/cc.h
components/net/lwip-2.0.3/src/arch/include/arch/sys_arch.h
components/net/lwip-2.0.3/src/lwipopts.h
components/net/lwip-2.1.2/src/arch/include/arch/cc.h
components/net/lwip-2.1.2/src/arch/include/arch/sys_arch.h
components/net/lwip-2.1.2/src/lwipopts.h

[
BYTE_ORDER 的定义应该放在cc.h中
在GCC和Keil下 1.4.1 2.0.2 2.0.3 2.1.2冲突已经解决
]

[lwip] solve the conflict between multi BYTE_ORDER(s)

---

components/net/lwip-2.1.2/src/arch/sys_arch.c
components/net/lwip-2.1.2/src/lwipopts.h

[
* 修复了 lwip2.1.2 中的隐式声明错误。
* 函数声明在 lwipopt.h 是经过考量的，对源码修改最小。
* LWIP_HDR_OPT_H 不会造成重复引用 lwipopt.h 文件。
]

[fix] the problem of implicit declaration for "lwip_ip4_route_src".

---

bsp/raspberry-pi/raspi3-32/driver/drv_gpio.c
bsp/raspberry-pi/raspi3-32/driver/raspi.h
bsp/raspberry-pi/raspi3-64/driver/drv_gpio.c
bsp/raspberry-pi/raspi3-64/driver/raspi.h

[
当使用树莓派3B进行开发时，使用GPIO时出现Coredump，检查后发现寄存器偏移量错误，遂跟踪到所修改的代码，位于`bsp/raspberry-pi/raspi3-32(或64)/driver/driver_gpio.c`与`bsp/raspberry-pi/raspi3-32(或64)/driver/raspi.h`。
问题1：
```c
static void raspi_pin_write(struct rt_device *dev, rt_base_t pin, rt_base_t value)
{
...
BCM283X_GPIO_GPCLR(pin / 32) |= (0 << (pin %32)); // 原始代码 移位值为0，会导致无法清空该GPIO
BCM283X_GPIO_GPCLR(pin / 32) |= (1 << (pin %32)); // 修改为1，在树莓派3B上64位版本系统测试正常，32位系统未做测试。
...
}
```
问题2：
```c
/* Defines for GPIO */
...
#define BCM283X_GPIO_GPCLR(n) HWREG32(BCM283X_GPIO_BASE + 0x0028 + 0x4 * n) /* GPIO Pin Output Clear */
// GPIO控制寄存器地址计算，每32个GPIO为一个寄存器控制，计算时宏参数未加括号，导致在问题1函数中调用时，如果使用GPIO号大于一定值（如BCM GPIO21，计算表达式0x4 * 21 / 32=2），会导致越界访问，应当先计算除法，如下方更改。
#define BCM283X_GPIO_GPCLR(n) HWREG32(BCM283X_GPIO_BASE + 0x0028 + 0x4 * (n)) /* GPIO …
```

BugFix: Raspi3 GPIO driver write bug

---

src/idle.c
src/thread.c

[
本次提交基于[上次的修改 #4843](https://github.com/RT-Thread/rt-thread/pull/4843)思维逻辑，并没考虑上次提交所做改动的合理性，
本次修改的相关讨论文章[rt-thread 系统优化系列（五） 之 线程销毁谜题](https://club.rt-thread.org/ask/article/3138.html) [rt-thread 系统优化系列（六） 之 让 idle 线程闲下来](https://club.rt-thread.org/ask/article/3141.html) [rt-thread 僵尸线程销毁流程优化分析篇](https://club.rt-thread.org/ask/article/3144.html)
]

remove duplicate work between idle and thread_exit

---

components/net/at/src/at_cli.c

[
[fix]修复AT组件在CLI模式下，指令输入过长导致数组越界的问题
]

[fix]修复AT组件在CLI模式下，指令输入过长导致数组越界的问题

---

bsp/stm32/stm32l475-atk-pandora/board/pm_cfg.h
components/drivers/Kconfig
components/drivers/include/drivers/lptimer.h
components/drivers/include/drivers/pm.h
components/drivers/pm/SConscript
components/drivers/pm/lptimer.c
components/drivers/pm/pm.c

[
- 更新PM框架，优化PM模块的请求与释放
- 更新PM框架睡眠策略，可以主动suspend睡眠模式
- 增加low power timer管理
- 根据不同睡眠模式threshold timer timeout不同，调整睡眠模式
以上更新在：STM32L4等平台验证通过，依旧适用于其他平台
]

[components] PM框架更新

---

src/memheap.c

[   
原memheap内存管理算法中存在两个问题，如下：
1. rt_malloc(0)时会分配长度为RT_MEMHEAP_MINIALLOC（`12`）的内存，这里与slab、小内存管理算法的行为不一致，并且有可能导致rt_malloc分配的内存地址没有RT_ALIGN_SIZE字节对齐。
2. rt_system_heap_init初始化堆时，如果传入的地址没有RT_ALIGN_SIZE字节对齐，rt_malloc分配的地址也不会RT_ALIGN_SIZE字节对齐。
本次提交对上述两个问题进行修复，方案如下：
1. rt_malloc(0) 时返回RT_NULL，与slab算法、小内存算法保持一致。
2. 对rt_system_heap_init传入的地址进行对齐。  
]

memheap内存管理算法漏洞修复

---

bsp/qemu-vexpress-a9/drivers/drv_clcd.c
bsp/qemu-vexpress-a9/drivers/lvgl/SConscript
bsp/qemu-vexpress-a9/drivers/lvgl/lv_demo.c
bsp/qemu-vexpress-a9/drivers/lvgl/lv_port_disp.c
bsp/qemu-vexpress-a9/drivers/lvgl/lv_port_indev.h
bsp/simulator/Kconfig
bsp/simulator/drivers/SConscript
bsp/simulator/drivers/lvgl/SConscript
bsp/simulator/drivers/lvgl/lv_conf.h
bsp/simulator/drivers/lvgl/lv_demo.c
bsp/simulator/drivers/lvgl/lv_port_disp.c
bsp/simulator/drivers/lvgl/lv_port_disp.h
bsp/simulator/drivers/lvgl/lv_port_indev.c
bsp/simulator/drivers/lvgl/lv_port_indev.h
bsp/simulator/drivers/lvgl/win32drv.c
bsp/simulator/drivers/lvgl/win32drv.h
bsp/stm32/stm32l475-atk-pandora/board/ports/lvgl/lv_demo.c

[
fps测量直接爆表了
https://user-images.githubusercontent.com/34888354/146308489-99fad735-b72e-480b-ab49-ae2d604dc068.mp4
]

[vs][simulator][lvgl] vs模拟器增加lvgl仿真功能

---

components/drivers/include/drivers/mmcsd_card.h
components/drivers/include/drivers/mmcsd_host.h
components/drivers/sdio/block_dev.c
components/drivers/sdio/mmcsd_core.c

1. Issue on traveling second node in list if multi-partitions on card.
[
修複 移除 "多分區"的SD卡時，造成的 infinite-loop
支持多卡多分區掛載/缷載
1. New naming rule for multiple cards: sdXpY. Ex: sd0, sd0p0, sd0p1, sd1, sd1p0, sd1p1, .... sdXpY.
2. Always create super-node block device for backward-compatible and fdisk-like utility. EX: sd0, sd1, ..... sdX.
3. Shrink code.
Tested on Nuvoton MA35D1 platform.
] …

[SDIO] Fix infinite-loop in rt_mmcsd_blk_remove.

---

bsp/stm32/stm32f746-st-nucleo/board/Kconfig

修复stm32f746-st-nucleo 的env环境不能使用menuconfig配置的问题
Fix the problem of stm32f746-st-nucleo that env cannot be configured with menuconfig
已经stm32f746-st-nucleo开发板测试验证
Has been tested and verified on the stm32f746-st-nucleo development board

Fix the problem of stm32f746-st-nucleo that env cannot be configured with menuconfig

---

include/rtthread.h
src/thread.c

该函数作为线程内建定时器的回调函数，应该仅作为私有函数使用，不应该暴露出来，并更名为_thread_timeout

[kernel] 将rt_thread_timeout设置为私有函数

---

components/drivers/usb/usbdevice/class/cdc_vcom.c

[
cdc vcom的发送函数参数和ops的函数指针参数类型不一致，导致编译会报警告，解决方法是修正参数类型
]

[components][usb] fix compile warning in cdc_vcom.c

---

include/rtthread.h

[
Add __attribute__(...) for rt_kprintf() to let the compiler check the format string parameters.
Tested in the following environment：
1. Keil uVersion：Arm Compiler v5.06、v6.7、v6.16  
2. Atollic TrueSTUDIO for STM32：GNU v6.3.1  
3. Code Composer Studio：TI Compiler v20.2.2.LTS、GNU v7.2.1
4. IAR Embedded Workbench：IAR C/C++ Compiler for ARM 9.20.2.320
]

[kernel] Add __attribute__(...) for rt_kprintf() to let the compiler check the format string parameters

---

include/rtthread.h

Reverts RT-Thread/rt-thread#5432
This PR causes many of warnings. We can fix these warnings and then merge this PR.

Revert "[kernel] Add __attribute__(...) for rt_kprintf() to let the compiler check the format string parameters"

---

components/drivers/sdio/mmc.c

[
优化代码，修复编译警告。mmc.c中函数mmc_select_bus_width的局部变量数组bus_widths实际上没有用，只用来算了个数，用来索引ext_csd_bits数组成员。实际改成用ext_csd_bits数组本身来算个数会更加合理，也去除了编译器警告。
]

[components][sdio] fix compile warning and optimized code.

---

components/net/lwip_dhcpd/SConscript

[
将1.4.1和其他版本的条件反过来，这样以后升级也不需要增加版本宏定义了。
]

[lwip] 修复dhcpd没有包含2.0.3版本的问题

---

bsp/qemu-vexpress-a9/applications/lvgl/SConscript
bsp/ra6m4-cpk/ra_cfg/SConscript
bsp/simulator/applications/lvgl/SConscript
bsp/stm32/stm32f407-atk-explorer/applications/lvgl/SConscript
bsp/stm32/stm32f407-atk-explorer/applications/lvgl/demo/SConscript
bsp/stm32/stm32f469-st-disco/applications/lvgl/SConscript
bsp/stm32/stm32l475-atk-pandora/applications/arduino/SConscript
bsp/stm32/stm32l475-atk-pandora/applications/lvgl/SConscript
bsp/stm32/stm32l475-atk-pandora/applications/lvgl/demo/SConscript

[
python中 group = group + xxx 和 group += xxx 这两种表述方法的行为是不一样的
现在已经证实 至少在keil下，如果使用group += 可能会出现分组上的问题，造成同一个.c文件被同时分配到不同的group。
因此在sconscript中要老老实实的用group = group + xxx的表达方式，不能偷懒成+=
]

[sconscript] 代替+=的表述方法

---

components/net/lwip-1.4.1/src/arch/sys_arch.c
components/net/lwip-2.0.2/src/arch/sys_arch.c
components/net/lwip-2.0.3/src/arch/sys_arch.c
components/net/lwip-2.1.2/src/arch/sys_arch.c

[
sys_arch_mbox_tryfetch在LwIP中的描述是返回0的时候为成功，但在rt-thread的sys_arch.c的实现是成功的时候返回了1，协议栈中使用这个函数的地方都是做的否定判断(SYS_ARCH_TIMEOUT或SYS_MBOX_EMPTY)，所以不影响协议栈的功能，但在做网卡驱动移植的地方，移植的开发者也可能使用sys_arch_mbox_tryfetch这个函数，如果使用肯定判断的情况下，可能就造成Bug。已经将成功的返回值改为0，可以修改上述场景下的问题。
]

[components][net][lwip]fixed the return value for sys_arch_mbox_tryfetch in lwip stack

---

libcpu/arm/cortex-m33/context_gcc.S
libcpu/arm/cortex-m4/context_gcc.S
libcpu/arm/cortex-m7/context_gcc.S

[
当使用thumb指令集时，要求汇编语法中的“条件执行”要跟在IT指令后面，否则会编译不通过。
报错如下：Error: thumb conditional instruction should be in IT block -- `moveq r4,#0x01'
对于4.x版本的gcc编译器，可以通过指定编译选项：-mimplicit-it=thumb 来告诉编译器识别隐式的IT指令，从而通过编译。
但是对于高版本的gcc编译器，已经取消了此编译选项。故必须手动的加上IT指令才能通过编译。
thumb指令集“条件执行”arm官网文档：
https://developer.arm.com/documentation/dui0473/m/condition-codes/conditional-execution-in-thumb-state
参考论坛帖子：
https://club.rt-thread.org/ask/question/433887.html （包含复现方法）
https://club.rt-thread.org/ask/question/4188.html
Signed-off-by: Mingrui Ren <jiladahe1997@gmail.com>
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser …

[bugfix] libcpu/arm/cortex-m/context_gcc: 修复thumb指令集汇编语法错误

---

bsp/n32g452xx/Libraries/rt_drivers/drv_gpio.c
bsp/n32g452xx/n32g452xx-mini-system/applications/main.c

[
【解决的问题】
为 N32G45X 开发板添加了 rt_pin_get 接口支持，name 字符串参数的风格保持 STM32 pin驱动的命名风格，例如PB5使用： `"PB.5"` 字符串
【解决方案】
1. 在原有pin上下文类型`struct pin_index`中添加一个`const char* name`成员；
2. `__N32_PIN`宏中，添加对`name`成员值的填充，采用宏拼接的方式实现；
3. 添加`n32_pin_get`函数，函数中遍历`pins`数组，查到`name`匹配的条目后，返回下标；
4. 将`n32_pin_get`函数绑定到`struct rt_pin_ops _n32_pin_ops `变量的`pin_get`函数指针上；
【测试情况】
已在国民技术N32G45XVL-STB-V1.1开发板测试通过；
]
我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered …

[bsp/n32g452xx] add rt_pin_get support

---

bsp/bluetrum/libraries/hal_libraries/ab32vg1_hal/SConscript
bsp/bluetrum/libraries/hal_libraries/bmsis/SConscript
bsp/ck802/applications/SConscript
bsp/gd32/docs/GD32系列BSP制作教程.md
bsp/ra6m4-cpk/ports/fal/SConscript
bsp/ra6m4-cpk/ports/rw007/SConscript
bsp/stm32/stm32h743-openmv-h7plus/SConstruct
bsp/stm32/stm32l475-atk-pandora/board/ports/fal/SConscript
bsp/thead-smart/applications/SConscript
bsp/tm4c129x/libraries/SConscript
components/drivers/spi/SConscript
tools/building.py
tools/codelite.py
tools/iar.py
tools/keil.py
tools/ses.py

[update] change ccflags to cflags

---

components/drivers/include/ipc/workqueue.h
components/drivers/src/workqueue.c
src/device.c
src/ipc.c
src/thread.c
src/timer.c

[
1. 微调了timer.c的注释
2. 完善了workqueue.c的注释
3. 补充了部分参数的安全检查
4. 将rt_work_init函数放到.c文件中
5. 增加rt_work_urgent函数，系统工作队列紧急插入work item函数
]

[kernel] improve comments and parameter checking

---

bsp/stm32/libraries/HAL_Drivers/drv_usart.c
bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c

避免警告，变量可能未初始化就使用

---

components/drivers/ipc/waitqueue.c
src/ipc.c
src/thread.c

[
有些长时间阻塞 api ，在启用 signal 的时候，可能被 signal 提前唤醒，却没有告知应用层是因为 INTR 错误返回的。
修改部分函数，当线程状态错误时直接返回线程状态
]

return thread error when resumed by signal

---

components/dfs/filesystems/devfs/devfs.c
components/drivers/ipc/completion.c
components/drivers/ipc/dataqueue.c
components/drivers/ipc/waitqueue.c
include/rtdebug.h
src/ipc.c

[
在获取锁的时候，如果调度器不可用，会导致系统异常，而且没有任何提示信息，破坏临界区。用来检查是否存在滥用 rt_enter_critical 的情况。
所以添加了两种情况下的检查：
- 获取锁且不等待时，不论能否获取到都不做任何处理
- 不论能否获取到锁，只要等待，都要检查调度器是否可用（可以被调度走：检查调度器不被锁，且处于线程模式下）。
在ART-Pi上完成了测试。
]

add RT_DEBUG_SCHEDULER_AVAILABLE check.

---

components/drivers/wlan/wlan_lwip.c

[
修复wlan驱动框架里调用LWIP.dhcp接口多任务安全引起的临界资源访问错误的问题。
当触发此问题时会出现如下类似错误信息：
```
dhcp_create_msg: dhcp->p_out == NULL
Assertion: 1823 in rt-thread/components/net/lwip-2.0.3/src/core/ipv4/dhcp.c, thread tcpip
(0) assertion failed at function:sys_arch_assert, line number:621
```
]

fixed wlan driver dhcp multitask safety

---

components/utilities/ulog/ulog.c

[
该文件已经引用<sys/time.h> 无需再extern localtime_r了
]

[ulog]移除localtime_r多余的声明

---

src/thread.c

When we create thread A by rt_thread_init but do
not init the thread object,and then create thread
B in the thread A,it maybe crash.
[
在RT_USING_MODULE特性开启的情况下，利用rt_thread_init去创建线程A，再在A线程中去创建线程B，会出现data abort的问题。
1.在利用rt_thread_init去创建线程A的时候，由于第一个参数（struct rt_thread *）是由用户创建，这个rt_thread中的数据可能是随机的，也就导致其中的成员module_id的值也可能是随机的，而在创建线程B的时候，无论是利用rt_thread_init还是rt_thread_create都会调用rt_object_init函数，我现在看一下这个函数的实现。
``` c
void rt_object_init(struct rt_object         *object,
enum rt_object_class_type type,
const char               *name)
{
register rt_base_t temp;
struct rt_object_information *information;
#ifdef RT_USING_MODULE
struct rt_dlmodule *module = dlmodule_self();
#endif
/* get object information */
information = rt_object_get_information(type);
RT_ASSERT(information != RT_NULL);
/* …
```

[Fix bug] fix thread init bug

---

components/utilities/Kconfig
components/utilities/ulog/syslog/syslog.c
components/utilities/ulog/ulog.c

[
优化ULOG_OUTPUT_FLOAT，避免使用内置libc的vsnprintf函数
]

improve ULOG_OUTPUT_FLOAT, which avoids using inherent vsnprintf

---

src/timer.c

[kernel]Fixed issue that could all timers stop

---

src/ipc.c
src/memheap.c

[
[kernel] Revert modifications to the semaphore
has been tested at stm32-l496-alideviloper.
]

[kernel] Revert modifications to the semaphore

---

documentation/basic/basic.md

[
Fixed the RT-Thread Program Memory Distribution subsection in basic.md. 
]

[documentation] Fixed Program Memory Distribution - Basic.md

---

bsp/stm32/libraries/HAL_Drivers/drv_rtc.c
components/libc/compilers/common/time.c
components/utilities/ulog/backend/console_be.c
components/utilities/ulog/syslog/syslog.c
components/utilities/ulog/ulog.c
components/utilities/ulog/ulog.h
components/utilities/ulog/ulog_def.h

[
ulog增加递归检查，从内部自动处理可能存在的递归导致的死循环问题。
使用互斥量代替信号量作为锁，防止出现实时性问题。
https://club.rt-thread.org/ask/question/434822.html
经测试，已经解决递归问题：
]

[ulog][rtc][time][bug] solve the interference when enable the ulog timestamp

---

libcpu/risc-v/SConscript

[
在移植ch32v103 bsp时 发现scons编译libcpu的中间文件，直接放到源文件目录下，不是tool/building.py指定的
build/kernel/libcpu, variant_dir设置未起作用。同时也会生成.s 文件，污染内核，git追踪也麻烦。
```
if not has_libcpu:
objs.extend(SConscript(Rtt_Root + '/libcpu/SConscript',
variant_dir=kernel_vdir + '/libcpu', duplicate=0))
```
对比libcp/arm SConscript发现libcp/risc-v下的Sconscript 目标使用了绝对地址引用。
改成相对地址后，在ch32v103r-r1， ab32vg1-ab-prougen，gd32vf103v-eva bsp上测试，正常输出到build/kernel/libcpu。
]
我在这个拉取/合并请求中已经考虑了 …

[libcpu/risc-v] 修复risc-v scons编译中间文件不能输出到build/kernel/libcpu目录问题

---

bsp/renesas/libraries/bsp-template/board/ports/SConscript
bsp/renesas/ra6m4-cpk/board/ports/SConscript
bsp/renesas/ra6m4-iot/board/ports/SConscript

[sconscript] LOCAL_CCFLAGS -> LOCAL_CFLAGS

---

libcpu/arm/cortex-r4/cpu.c
libcpu/arm/cortex-r4/start_gcc.S

[
1、当未在rtconfig.h中定义“RT_USING_CPU_FFS”宏时，在src\kservice.c的1706行和libcpu\arm\cortex-r4\cpu.c的90行都存在 __rt_ffs()函数的定义，__rt_ffs()函数重定义导致编译无法通过。
2、基于TI的rm48芯片(cortex-r4核) 的板卡进行rt-thread移植时，在bsp/rm48x50下使用scons生成的rt-thread studio工程，编译后烧写到板卡上后上电运行出现prefetch abort异常，程序挂掉。经过与TI的官方demo代码进行对比，libcpu/arm/cortex-r4/start_gcc.S的reset处相较于TI的官方demo，少了r0-r13以及spsr寄存器的初始化代码。
1*、修改后，不定义RT_USING_CPU_FFS宏的情况下，使用arm-gcc编译也不会出现__rt_ffs()函数重定义，程序编译通过。
2*、在libcpu/arm/cortex-r4/start_gcc.S的reset处添加了r0-r13、spsr寄存器的初始化代码后，重新编译下载到rm48板卡上电后程序正常运行，不再出现prefetch abort异常。
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to …

解决bsp/rm48x50工程使用arm-gcc编译不通过，以及程序出现prefetch abort异常的问题。

---

components/drivers/include/drivers/rtc.h
components/drivers/rtc/alarm.c
components/drivers/rtc/rtc.c

[
时间是有 UTC 时间与本地时间之分的，当前 RTC 时间的设置及使用比较混乱，其中一个原因，是之前的 libc 没有时区的概念。怎么设置都行，只要自己认识就可以。目前 libc time 函数十分完毕，也有时区的机制在里面 。为了避免对 API 的理解偏差，导致业务中时间混乱的问题，rtc 设备框架的 API 行为也要确定下来。
现规定：
1. `rt_err_t (*get_secs)(time_t *sec)` 获取 UTC 时间戳，无时区
2. `rt_err_t (*set_secs)(time_t *sec)` 设置 UTC 时间戳，无时区
3. `rt_err_t (*get_alarm)(struct rt_rtc_wkalarm *alarm)` 获取闹钟时分秒，无时区
4. `rt_err_t (*set_alarm)(struct rt_rtc_wkalarm *alarm)` 设置闹钟时分秒，无时区
5. `rt_err_t (*get_timeval)(struct timeval *tv)` 获取 UTC 毫秒时间戳，无时区
6. `rt_err_t (*set_timeval)(struct timeval *tv)` 设置 UTC 毫秒时间戳，无时区
1. RT_DEVICE_CTRL_RTC_GET_TIME 命令传递的 arg 类型是 `time_t *`，从 RTC 设备获取 UTC 时间
2. RT_DEVICE_CTRL_RTC_SET_TIME 命令传递的 arg 类型是 `time_t *`，设置 UTC 时间到 RTC 设备
3. RT_DEVICE_CTRL_RTC_GET_ALARM 命令传递的 arg 类型是 `struct rt_rtc_wkalarm *`，获取已经设置的闹钟时间，其中的时分秒是 UTC …

[drivers][rtc] 优化 RTC 及 Alarm 代码

---

components/dfs/filesystems/romfs/dfs_romfs.c
components/dfs/filesystems/romfs/dfs_romfs.h
tools/mkromfs.py

[
1. 希望打包出来的 ROMFS 文件系统，不是绝对地址的。这样子就能在多个平台上进行使用。
2. simulator 上会将 ROMFS 载入内存进行使用，每次加载的内存地址可能不一致，也必须使用相对地址
1. ROMFS 支持相对地址功能，采用挂载地址 + 偏移的方式读取文件
2. 相对地址与绝对地址自适应
]

[dfs][romfs]支持相对地址模式

---

tools/building.py

[
group['src'] 在每次  scons --target =xx 时会随机排序。
使用 sort 方法进行排序，防止乱序，已使用 cmake 进行测试
]

[update] Sort the source file path

---

components/dfs/filesystems/romfs/dfs_romfs.c
components/dfs/filesystems/romfs/dfs_romfs.h
tools/mkromfs.py

Reverts RT-Thread/rt-thread#5768
这类方式太投机取巧了，并不是一份正式的模式

Revert "[dfs][romfs]支持相对地址模式"

---

components/Kconfig
components/libc/compilers/common/stdlib.c
include/rtthread.h
src/Kconfig
src/kservice.c

- 为64位cpu设置单独的栈默认大小，否则64cpu按照目前的栈大小，直接就死机
- 将 tick 频率调整为默认是1000，由于RT-Thread只支持32位和64位CPU, 以目前的MCU性能，支持1000Hz中断是不成问题的
- 优化rt_kprintf支持longlong的能力，默认在64位CPU为开启状态
- 将RT_KSERVICE_USING_STDLIB_MEMXXX代替RT_KSERVICE_USING_STDLIB_MEMCP/MEMSET
- 将RT_KSERVICE_USING_STDLIB设置为默认开启
后两点是基于这样考虑的：
由于memxxx函数的不安全，现在必须建议用户默认使用rt_memxxx来代替memxxx，但是就rt_strxxx函数而言，这些函数在不同编译平台下是安全的，因此无需要再默认搞出另一套rt_strxxx，占了ROM空间，可以默认将rt_strxxx直接等效成strxxx函数即可。
修改之后，用户使用rt_memcpy rt_memset等函数还是走的rt-thread这边的安全函数，使用rt_strlen等函数会默认直接走编译器标准C库的strlen。

[kconfig] add 64bit default value for stack size. set tick HZ as 1000 by default

---

bsp/stm32/libraries/HAL_Drivers/drv_can.c

[
[bsp/stm32] fix the bug of can filter conflict
- bug : can1 and can2 of stm32 share the same filter groups, if use the default setting of RTT (when "hdr=-1"), and use can1 and can2 at the same time, the later filter settings will cover the filter settings before. 
- fix : check the name of can devices, can1 use the bank of 0 ~ 13, and can2 use the bank of 14 ~ 27, to prevent the first can device being covered by another can device. 
- attention : neither of these two can devices can set more than 14 filter groups, so I suggest to add an "RT_ASSERT" to find if defined more than 14 groups when defining the can filters. 
- attention : the two can devices' name must be "can1" and "can2". I suggest to inform users in the document.
] …

[bsp/stm32] fix the bug of can filter conflict

---

components/libc/posix/delay/delay.c
include/rtdebug.h
src/kservice.c

[
RT_DEBUG_DEVICE 默认修改为enable
此外，rt_hw_dealy_us应该由kernel负责定义weak函数，不应该由posix来负责。在nano中，一些人也会上来就用rt_hw_us_delay这个函数，应该给一些提示。而且rt_hw_delay_us这个函数声明是在rtthread.h中。
]

[kernel] enable RT_DEBUG_DEVICE by default and move weak rt_hw_dealy_us in kservice.c

---

components/drivers/usb/usbdevice/core/usbdevice_core.c

[
在Full speed上获取DeviceQualifier Descriptor发现一直未能返回STALL握手包，源码设置的是端点0的OUT方向，
但STALL握手包均是由Device向Host返回，属于IN事务包，在控制传输上可以只直接设置端点0的IN 方向STALL即可
more infor, refer to [rtthread USB CDC调用流程](https://club.rt-thread.org/ask/article/3710.html)
或者参考CherryUSB的做法。
已在STM32F407-Disc1上测试，枚举传输均正常。
]

[USB] fix stall bug on control transfers

---

bsp/nuclei/gd32vf103_rvstar/SConstruct
bsp/nuclei/nuclei_fpga_eval/SConstruct

[
具体描述见#5841
我试了芯来,RT-Thread Stuido,和github上的RiSC-V，均编译不过。按照rtthread-stdudio生成rvstart工程的rtconfing.py调整SConstruct如下
```
--- a/bsp/nuclei/gd32vf103_rvstar/SConstruct
+++ b/bsp/nuclei/gd32vf103_rvstar/SConstruct
@@ -23,7 +23,7 @@ AddOption('--run',
DefaultEnvironment(tools=[])
env = Environment(tools = ['mingw'],
AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
-    CC = rtconfig.CC, CFLAGS = rtconfig.CFLAGS,
+    CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
CXX = rtconfig.CXX, CXXFLAGS = rtconfig.CXXFLAGS,
AR = rtconfig.AR, ARFLAGS = '-rc', LIBS = rtconfig.LIBS,
LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
```
可以正常编译，`scons --run debug` 下载后，正常运行。
]
The following content must not be changed in the …

[bsp] add null CCFLAGS for Nuclei bsps

---

bsp/stm32/libraries/HAL_Drivers/drv_adc.c
components/drivers/include/drivers/adc.h
components/drivers/misc/adc.c

[
https://github.com/mysterywolf/RTduino/pull/8
已经在RTduino兼容层上得到了验证
目前适配了STM32 其他bsp的分辨率会显示0，同时获取的时候错误码也是返回错误的，表示不支持此指令，需要其他芯片自己去填写自己的adc分辨率
相关issue：https://github.com/RT-Thread/rt-thread/issues/5817
]

[adc] 支持adc框架获取BSP的ADC分辨率

---

components/libc/compilers/common/SConscript
components/libc/compilers/common/sys/time.h

[
已经证实，早期IAR版本没有struct timespec结构体，因此版本判断需要保留。
但是经过实际测试，目前ENV已经没有能力生成早期例如7.2版本的IAR工程了，打开是错误的。
附上早期7.2版本time.h
[time.h-iar.zip](https://github.com/RT-Thread/rt-thread/files/8533391/time.h-iar.zip)
]

[libc][time] 修复IAR版本判断逻辑错误

---

components/drivers/serial/serial.c
components/drivers/serial/serial_v2.c

[
修复 串口设备 O_NONBLOCK 标记设置失败问题
]

[drivers][serial] ioctl add F_SETFL cmd

---

bsp/stm32/libraries/HAL_Drivers/config/f4/dma_config.h

修复BUG：SDIO和UART6（TX）的DMA通道分配冲突

---

bsp/stm32/libraries/HAL_Drivers/drv_usart.c

在串口不关闭的情况下，更改波特率后，清空上次数据检索，导致更新写入检索错误，
串口无法读出正确的数据。真实数据的位置和检索值之间总有一定的距离，导致读取
数据的时候会有一定的延时。缓冲区大，延时越长
[
]
The following content must not be changed in the submitted …

修复BUG：串口启用DMA接收后，动态修改串口波特率扰乱接收检索

---

components/drivers/include/drivers/usb_device.h
components/drivers/usb/usbdevice/class/cdc_vcom.c

硬件驱动（VCOM）：增加获取USB虚拟串口连接状态的接口

---

include/rtdef.h
src/thread.c
src/timer.c

完全不用有这个心理负担，不要认为自己的水平不够，开源项目就是一个大家一起来找茬的过程，无论这个“茬”是大是小，对于RT-Thread代码的迭代发展都是很重要的。
不一定，就比如这个PR，可以看到，这只是对RT-Thread代码的美化，并没有实质性的修改RT-Thread的任何源码。**但是**！ 这种美化（不限于增加注释，美化代码结构等）对于RT-Thread来说也是非常重要的！因为能够让别人清晰、明了、舒服地阅读代码也是非常重要的！因此不要认为我是小白，我就不能给RT-Thread贡献代码。
我们接收任何对RT-Thread源码迭代发展有益的PR，无论这个PR是大是小，均可！
[1] 请参考视频 [从0教你如何给RT-Thread贡献代码](https://www.bilibili.com/video/BV1gr4y1w7yX)
[2] 欢迎 [点此论坛文章](https://club.rt-thread.org/ask/article/e19f1f0f77fbd119.html) 加群，群内有人指导你如何提交PR
---------------------
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if …

[kernel]【示例】如何给RT-Thread提交PR | beautify code

---

bsp/stm32/libraries/HAL_Drivers/drv_crypto.c

最近在移植密码学的软件包 `libsodium` 和 `libhydrogen` 的时候，发现选中硬件加密组件后， STM32 的硬件随机数时钟没有打开，文档中心例程返回的随机数全部是0。
测试板卡：STM32F407VET6 工控板
```
#include <hw_rng.h>
void hw_rng(void)
{
rt_uint32_t result=0;
int i, num0=0, num1 =0;
const int max_test = 1000;
for (i = 0; i < max_test; i++)
{
result = rt_hwcrypto_rng_update();
result%2 ? num1++ : num0++;
}
LOG_I(" num1: %d, num0: %d ",num1, num0);
}
```
使用 RT-Thread Studio 打开 CubeMX 配置好 RNG 后生成的 `SystemClock_Config()` 不包含 `__HAL_RCC_RNG_CLK_ENABLE()`，需要在驱动里打开时钟。
---------
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and …

[bsp][stm32][drv_crypto] Enable RNG Clock

---

components/drivers/include/drivers/sensor.h
components/drivers/sensors/sensor_cmd.c

print vendor information of Melexis in function sensor()
[
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be …

Add RT_SENSOR_VENDOR_MELEXIS in sensor_cmd.c

---

bsp/nuvoton/nk-980iot/applications/lvgl/lv_conf.h
bsp/nuvoton/nk-n9h30/applications/lvgl/lv_conf.h
bsp/nuvoton/numaker-iot-m487/applications/lvgl/lv_conf.h
bsp/nuvoton/numaker-m032ki/applications/lvgl/lv_conf.h
bsp/nuvoton/numaker-m2354/applications/lvgl/lv_conf.h
bsp/nuvoton/numaker-pfm-m487/applications/lvgl/lv_conf.h
bsp/qemu-vexpress-a9/applications/lvgl/lv_conf.h
bsp/simulator/applications/lvgl/lv_conf.h

[lvgl] remove LV_DISP_DEF_REFR_PERIOD which are defined manually

---

tools/kconfig-frontends/SConstruct

在 `scons --menuconfig` 时， kconfig-frontends 的 SConstruct 应该读取 PATH 环境变量，我在使用时找不到 gcc，发现是这个原因， gcc 不一定在 /usr/bin 下面，比如 NixOS 在 /run/current-system/sw/bin/gcc，可以根据环境变量找到它
这里用的 Append 而不是 Prepend，对别人应该没影响

[tools/kconfig-frontends] append path for scons env

---

bsp/nuvoton/libraries/nuc980/rtt_port/drv_sys.c

Reason: Interrupts were not cleaned up during initialization
[
Fix bug when restarting and getting interrupts that are not processed.
Reason: Interrupts were not cleaned up during initialization
]

Fix bug when restarting and getting interrupts that are not processed.

---

components/drivers/hwcrypto/hw_bignum.c
components/drivers/hwcrypto/hw_bignum.h

[
1. 修复函数返回值定义错误
2. 构造大数时每次初始化内存，放在脏数据残留
]

[drivers][hwcrypto] Correct function return value definition

---

bsp/stm32/libraries/HAL_Drivers/drv_adc.c
components/drivers/include/drivers/adc.h
components/drivers/misc/adc.c

add stm32_adc_get_vref
[
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted …

[device][adc] implement adc_get_vref

---

components/drivers/spi/spi_dev.c

[
_spi_bus_device_control 该函数没有实际被使用到予以移除
一些设备框架的错误码返回值处理不是很仔细，在没有任何有效操作的情况下，也会返回RT_EOK，这对用户的误导非常大。
今天在调试的时候顺道发现了spi control存在类似的问题。
此外在论坛上也有此类问题的反应：http://bbs.eeworld.com.cn/thread-1196113-1-1.html
考虑在4.1.1之前对此类问题进行一次摸排
]

[spi device] remove _spi_bus_device_control

---

bsp/simulator/drivers/SConscript
components/libc/compilers/armlibc/SConscript
components/libc/compilers/dlib/SConscript
include/rtthread.h

remove strnlen from rtthread.h
add __STDC_LIMIT_MACROS macro in Keil
add RT_USING_LIBC in simulator
add _DLIB_ADD_EXTRA_SYMBOLS=0 in IAR
strnlen 不属于ISO/ANSI-C标准库的函数
string.h中部分glibc/POSIX拓展函数各个编译平台不一致
例如strnlen 在IAR中定义 但是keil gcc下没有定义
IAR取消扩展C函数声明
取消strnlen函数在rtthread.h中的定义

[libc] remove strnlen from rtthread.h

---

components/libc/compilers/common/time.c

[
- Fix clock_gettime  calculation for  CLOCK_CPUTIME_ID
- 在计算时如果强制转换成 int 会导致 nsec 一直为 147483647，转换为 long long 计算正确
- 编译器 gcc 10，时钟频率 168MHz，STM32F407
]

[libc][time] Fix clock_gettime for CLOCK_CPUTIME_ID

---

components/drivers/hwcrypto/hw_bignum.c
components/libc/posix/io/poll/poll.c
components/net/netdev/src/netdev.c
components/net/sal/src/sal_socket.c

Fix compiler warnings

---

bsp/stm32/libraries/HAL_Drivers/drv_usart.c

[bsp][stm32] 增加uart7和uart8的DMA配置

---

components/libc/compilers/common/time.c

…ongly because the local variable was not initialized.
[
solve the problem which the os tick can be calculated wrongly because the local variable was not initialized.
it has been tested on the 1052 board.
]

 os tick can be calculated wrongly because the local variable was not initialized.

---

bsp/hc32/ev_hc32f460_lqfp100_v2/board/Kconfig
bsp/hc32/ev_hc32f460_lqfp100_v2/board/board.c
bsp/hc32/ev_hc32f460_lqfp100_v2/board/board_config.c
bsp/hc32/ev_hc32f460_lqfp100_v2/board/board_config.h
bsp/hc32/ev_hc32f460_lqfp100_v2/board/config/can_config.h
bsp/hc32/ev_hc32f460_lqfp100_v2/board/drv_config.h
bsp/hc32/libraries/hc32_drivers/drv_can.c

[
1. 添加HC32F460系列的CAN设备驱动支持；
2. 修改drv_can.c中的几处问题。发送函数中添加IDE赋值操作，解决无法发送正确的扩展帧ID问题。修改接收函数中判断ID类型的值，CAN_ID_STD值为0x40000000，而IDE的值只有0和1，因此不能直接用二者判断。can初始化中过滤器修改为接收标准帧和扩展帧。
3. 修改board.c中时钟配置，HC32F460库中没有CLK_SetCANClockSrc函数，也不需要配置，删掉该操作。
本次PR内容已在ev_hc32f460_lqfp100_v1开发板测试通过（V1和V2开发板CAN部分接口一样），在自己板子上移植测试也正常。
]

添加HC32F460系列CAN设备驱动支持

---

bsp/stm32/stm32l496-st-nucleo/applications/main.c
bsp/stm32/stm32l496-st-nucleo/board/Kconfig
bsp/stm32/stm32l496-st-nucleo/board/SConscript
bsp/stm32/stm32l496-st-nucleo/board/fal_cfg.h
bsp/stm32/stm32l496-st-nucleo/board/mnt_onchip.c

[  add the feature of on-chip on bsp stm32l496zg]

[bsp][stm32l496zg] add on-chip feature

---

bsp/hc32/libraries/hc32_drivers/drv_usart.c
bsp/hc32/libraries/hc32_drivers/drv_usart.h

修复多串口的描述符被覆盖的问题

---

bsp/stm32/libraries/HAL_Drivers/config/f4/dma_config.h

用户自己可以添加DMA分配文件，所以这里的DMA分配有可能和用户自定义的冲突
[
] …

[bsp][stm32]：修复UART6 DMA分配有可能冲突的BUG

---

components/drivers/spi/qspi_core.c

[
根据c标准，char类型为 Implementation Defined。
在不同的编译器上，如果将 `char *ptr ` 认为是 `signed` 那么将会有可能会导致最高位为 1 ，这样最终就会影响到 FLASH 操作的地址将会是一个非常大的地址，也就会出现读写数据错误。
论坛上已经出现过此类[问题](https://club.rt-thread.org/ask/question/82fe3d63596811fb.html)
]

Fix rt_qspi_send symbol extension BUG

---

bsp/hc32/ev_hc32f460_lqfp100_v2/board/Kconfig
bsp/hc32/libraries/hc32_drivers/SConscript
bsp/hc32/libraries/hc32_drivers/drv_rtc.c

[
【ev_hc32f460_lqfp100_v2】BSP中添加RTC驱动。
1.hc32\libraries\hc32_drivers中添加drv_rtc.c文件；
2.修改hc32\libraries\hc32_drivers中sconscript文件；
3.修改board文件夹下Kconfig文件，增加RTC选项；
本次PR代码已在ev_hc32f460_lqfp100_v2开发板测试通过。
]

添加HC32F460系列RTC外设驱动

---

components/finsh/msh.c

[
https://github.com/RT-Thread/rt-thread/issues/5870
已经在qemu上进行了测试
]

[msh]Restore the free command.|还原 free命令。

---

bsp/hc32/libraries/hc32_drivers/drv_usart.c

/* Enable error interrupt */
NVIC_EnableIRQ(uart->config->rxerr_irq.irq_config.irq_num);
上述代码使能错误接收中断后需要使能串口的接收中断`USART_INT_RX`才可以正常触发中断

接收错误中断未触发的问题

---

src/mem.c

```c
if (size > small_mem->mem_size_aligned)
return RT_NULL;
if (size < MIN_SIZE_ALIGNED)
size = MIN_SIZE_ALIGNED;
```
这2个连着看这很不舒服，在判断 size 是否 > 剩余空间之后，可能把size变大
不过 mem_size_aligned 应该是对齐的，MIN_SIZE_ALIGNED 的倍数，不是bug。但我觉得换下位置没有任何害处，而且看着舒服点。
当然工作人员如果觉得没必要，直接关了就行了

[kernel][mem.c] tighten size before check with mem_size_aligned

---

include/rtdef.h

[
The trailing `L`s in version numbers are not friendly to C preprocessors.
To create a version string at compile time using below macros,
what we get is `RT-Thread (4L.1L.1L)`, which is annoying.
```c
#define expand2(X) #X
#define expand(X) expand2(X)
const char version_str[] = "RT-Thread (" expand(RT_VERSION) "." expand(RT_SUBVERSION) "." expand(RT_REVISION) ")";
```
From definition of `RTTHREAD_VERSION`, we can infer that `RT_SUBVERSION` and
`RT_REVISION` will not exceed `100`. So, it's safe to discard these two trailing `L`s.
I think it is also okay to leave out the `L` in RT_VERSION in the near future.
]

version numbers be friendly to macro expansion

---

components/libc/posix/pthreads/pthread_cond.c

[
* have tested on real project.
-----
原 _pthread_cond_timewait 接口使用信号量来使线程处于挂起状态。
在通过 rt_mutex_release<pthread_mutex_unlock> 释放互斥锁时，在 rt_mutex_release 中，如果没有待唤醒的线程则跳过 rt_schedule；因此在 ```_pthread_cond_timedwait`` 中会紧接着获取释放掉的互斥锁，并同时被挂起。   
导致的现象就是尝试获取互斥锁的另一个线程被挂起，两个线程死锁无法执行。
而先释放互斥锁再挂起线程这个操作在 pthread_cond_timewait 里面是不允许存在的，在 pthread_cond_timewait 的挂起操作与互斥量的释放操作是不可被打断的。这个操作是一个原子操作，使用 rt_mutex_release 与 rt_sem_take 的组合操作不能做到这一点，所以需要将信号量挂起的逻辑移到 pthread_cond_timewait 中来解决这个问题。
----
* 经过压力测试 48 小时后仍然正常
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, …
```

[fix] use atomic operation to protect pthread conditional variable.

---

components/finsh/msh_file.c
components/libc/compilers/common/ctime.c
components/libc/posix/pthreads/pthread.c
include/rtdef.h

This reverts commit 6a05ddf63d1202456a37e970e5a9ab58370ed093.
[
#6123
这个地方过分区分0指针或者0值，会在GCC编译器出现大面积警告。经过进一步研究，Keil IAR对NULL的定义是数值0，但是GCC对此处要求比较严格，是指针0，会潜在导致大面积使用RT_NULL的程序报警。
查找其他资料，发现NULL定义成0也比较普遍，因此revert对此处的修改。
]

Revert "解决将RT_NULL当做数字0使用的问题"

---

components/drivers/usb/usbhost/class/hid.c

1.Set idle function should receive an empty package.
2.Fix uinst_t reference error in hid enable function.
Signed-off-by: dengguiling <greens9@163.com>
[
近日在RT-Thread上调试USB鼠标时，发现以下问题：
1.通过USB抓包PC连接鼠标，以及查询USB HID相关资料，发现HID set idle时，发送setup之后，Host需要接收一个空包。
[HID协议SET_IDLE请求的解释说明](http://www.usbzh.com/article/detail-825.html)
2.rt_usbh_hid_enable()函数里面，调用rt_usb_hcd_alloc_pipe()的传参存在错误，应为intf->device。
在mass.c中发现有正确使用，猜测为以前重构遗留问题。[mass.c#L572](https://github.com/RT-Thread/rt-thread/blob/2a8e92b8ee8bfe3b6984603cd8a2c444dc4d3039/components/drivers/usb/usbhost/class/mass.c#L572)
测试：在与STM32F4相同USB IP的开发板上测试，且修改问题比较简单，相关资料和抓包也佐证了修改。
]
The following content must not be changed in the submitted PR message. …

[compoenets][driver][usb] fix usbhost hid issues.

---

libcpu/risc-v/virt64/interrupt_gcc.S

查看 risc-v/virt64/interrupt.c：
对于函数是
void handle_trap(rt_size_t xcause,rt_size_t xtval,rt_size_t xepc,struct rt_hw_stack_frame *sp)
调用参数应该为：
```
csrr  a0, SRC_XCAUSE
csrr  a1, SRC_XTVAL
csrr  a2, SRC_XEPC
mv    a3, s0
call  handle_trap
```

[libcpu/risc-v/virt64]: fix parameter for call handle_trap

---

bsp/gd32/arm/libraries/GD32F4xx_Firmware_Library/CMSIS/GD/GD32F4xx/Source/GCC/startup_gd32f4xx.s

[
1、why
使用gd450分支时，发现其有些中断找不到入口
2、what
增加缺失的中断向量表定义，解决了此问题
3、使用成都资芯科技有限公司的GD32F450ZKT6开发板进行了验证（rt-thread studio 开发环境）
]

fix(bsp gd32f450 gcc):修复中断向量表缺失相关定义导致中断异常的问题

---

bsp/gd32/arm/libraries/GD32F10x_Firmware_Library/SConscript
bsp/gd32/arm/libraries/GD32F20x_Firmware_Library/SConscript
bsp/gd32/arm/libraries/GD32F30x_Firmware_Library/SConscript
bsp/gd32/arm/libraries/GD32F4xx_Firmware_Library/SConscript
bsp/gd32/arm/libraries/gd32_drivers/SConscript
bsp/gd32/arm/libraries/gd32_drivers/drv_log.h
bsp/gd32/arm/libraries/gd32_drivers/drv_sdio.c
bsp/gd32/arm/libraries/gd32_drivers/drv_sdio.h

[
1、增加sdio驱动，使用块设备的方式进行注册
2、使用成都资芯科技有限公司的GD32F450ZKT6开发板进行了验证（rt-thread studio 开发环境）
]

feat(bsp/gd32f1-f4/drv_sdio):增加gd32下sdio驱动

---

bsp/hc32/ev_hc32f460_lqfp100_v2/board/Kconfig
bsp/hc32/ev_hc32f460_lqfp100_v2/board/board_config.c
bsp/hc32/ev_hc32f460_lqfp100_v2/board/board_config.h
bsp/hc32/ev_hc32f460_lqfp100_v2/board/config/pwm_tmra_config.h
bsp/hc32/ev_hc32f460_lqfp100_v2/board/drv_config.h
bsp/hc32/libraries/hc32_drivers/SConscript
bsp/hc32/libraries/hc32_drivers/drv_pwm_tmra.c
bsp/hc32/libraries/hc32f460_ddl/SConscript

[
1. hc32f460, 增加timerA作为pwm设备的驱动，设备名为pwm_ax。
2. 在ev_hc32f460_lqfp100_v2开发板上，使用引脚H2和C13作为pwm输出，功能测试正常。
3. 开发板引脚H2和C13默认作为uart3引脚使用，因此采用depends on (!BSP_USING_UART3)进行资源规避。
]

[bsp/hc32]添加timerA的pwm驱动

---

bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f4.c
bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
bsp/stm32/libraries/HAL_Drivers/drv_soft_i2c.c
bsp/stm32/libraries/HAL_Drivers/drv_spi.c
bsp/stm32/libraries/HAL_Drivers/drv_usart.c
components/dfs/filesystems/romfs/dfs_romfs.c
components/dfs/filesystems/romfs/romfs.c
components/dfs/src/dfs.c
components/drivers/i2c/i2c-bit-ops.c
components/drivers/i2c/i2c_core.c
components/drivers/serial/serial.c
components/fal/src/fal_rtt.c
components/net/netdev/src/netdev.c
components/net/sal/src/sal_socket.c
libcpu/arm/common/showmem.c
src/kservice.c
src/mem.c
src/timer.c

[
* 编译环境: ARM GCC V10.2.1
* BSP: STM32F407
]

Fix some compilation warning
