components/dfs/src/dfs.c

Correct dfs fd_is_open search index error When define DFS_USING_STDIO

Correct dfs fd_is_open search index error

---

bsp/stm32f10x/drivers/usart.c

bsp stm32f10x add uart4 drive

---

components/drivers/misc/pin.c

Maybe pin register name Is error!

Correct pin register name problems

---

components/drivers/src/completion.c

fix: completion wait after, maybe can't clean the flag.

Fixed completion.c

---

tools/vs2012.py

修正rtt-root位于其他目录时计算目录错误的bug

---

components/finsh/SConscript
src/SConscript

Fix the `--keep` parameter for Keil.

Fix keil keep symbol

---

bsp/stm32f0x/rtconfig.py

[bsp][stm32f0x] Modify build config to reduce code size for Travis CI

[bsp][stm32f0x] Modify build config to reduce code size for Travis CI

---

bsp/at91sam9260/debug_scripts/at91sam9260.gdb

1.  Start GDB like this: arm-none-eabi-gdb.exe -x {debug_scripts_path}/at91sam9260.gdb {image_path}/rtthread_at91sam9260.axf
2. Call user-defined command "reset" when you start debug.

[bsp][sam9260] Add GDB start scripts. 

---

bsp/stm32f40x/applications/application.c
bsp/stm32f40x/drivers/SConscript
bsp/stm32f40x/drivers/stm32f4xx_eth.c
bsp/stm32f40x/drivers/stm32f4xx_eth.h

Open the #define RT_USING_LWIP in rtconfig and build it , the stm32_eth.h can not find.
Signed-off-by: pangwei <271372443@qq.com>

Open the #define RT_USING_LWIP in rtconfig and build it , the stm32_eth.h can not find.

---

components/net/lwip/apps/ftpd.c

1.Fixed PASV mode issue;
2.Implement RNFR and RNTO command;
3.Change some command code according RFC959;
4.Add command for msh shell;
5.Implement "noop" command.

[FTP server]

---

components/libc/armlibc/sys/types.h

add definition of mode_t for armlibc.

[components] add definition of mode_t for armlibc.

---

components/finsh/shell.c

[finsh] Clear buffer before switching to new shell device

---

bsp/stm32f10x/drivers/bxcan.c
components/drivers/can/can.c

Fix can.drv.errors

---

components/libc/armlibc/sys/errno.h

update armlibc/sys/errno.h: define EADDRNOTAVAIL

---

bsp/lpc408x/applications/board.c
bsp/lpc408x/applications/canapp.c
bsp/lpc408x/applications/startup.c
bsp/lpc408x/drivers/drv_lpccan.c
bsp/lpc408x/drivers/drv_lpccan.h
bsp/lpc408x/project.uvprojx
bsp/lpc408x/rtconfig.h
bsp/stm32f10x/drivers/bxcan.c
components/drivers/can/can.c
components/drivers/include/drivers/can.h

Fix lpc4088candriver

---

bsp/ls1cdev/SConscript
bsp/ls1cdev/SConstruct
bsp/ls1cdev/applications/SConscript
bsp/ls1cdev/applications/application.c
bsp/ls1cdev/applications/startup.c
bsp/ls1cdev/drivers/SConscript
bsp/ls1cdev/drivers/board.c
bsp/ls1cdev/drivers/board.h
bsp/ls1cdev/drivers/display_controller.c
bsp/ls1cdev/drivers/display_controller.h
bsp/ls1cdev/drivers/uart.c
bsp/ls1cdev/drivers/uart.h
bsp/ls1cdev/readme.txt
bsp/ls1cdev/rtconfig.h
bsp/ls1cdev/rtconfig.py
libcpu/mips/loongson_1c/cache.c
libcpu/mips/loongson_1c/cache.h
libcpu/mips/loongson_1c/cache_gcc.S
libcpu/mips/loongson_1c/context_gcc.S
libcpu/mips/loongson_1c/cpuport.c
libcpu/mips/loongson_1c/exception.c
libcpu/mips/loongson_1c/interrupt.c
libcpu/mips/loongson_1c/ls1c.h
libcpu/mips/loongson_1c/mipscfg.c
libcpu/mips/loongson_1c/start_gcc.S

transplant codes for smart loong board v1.0 which is based on loongson 1C.
http://www.openloongson.org/forum.php

chinesebear add bsp/ls1cdev & libcpu/mips/loongson_1c

---

bsp/ls1cdev/ls1b_ram.lds

"scons" needs this file. I lost it in last push.

	new file:   bsp/ls1cdev/ls1b_ram.lds

---

components/drivers/spi/spi_flash_w25qxx.c

add w25q80 support followed origin driver format.

add w25q80 support to spi flash

---

components/drivers/serial/serial.c

fix DMA tx mod tx_dma->activated flag init bug.

fix DMA tx mod tx_dma->activated flag init bug.

---

bsp/stm32f40x/drivers/stm32f4_rtc.c
bsp/stm32f40x/drivers/stm32f4_rtc.h

[bsp]add stm32f4xx bsp rtc driver

[bsp]add stm32f4xx bsp rtc driver

---

bsp/stm32f40x/rtconfig.py

NOTE:
This patch only fully tested on MDK V4.7

Modify compiler parameter to adjust MDK V4.70

---

bsp/stm32f40x/readme.md
bsp/stm32f40x/readme.txt

Update and rename readme.txt to readme.md

---

bsp/beaglebone/drivers/uart.c

Change the head files in uart.c.

Change the head files in uart.c.

---

bsp/nrf51822/applications/startup.c
bsp/nrf51822/drivers/board.h
bsp/nrf51822/rtconfig.h

Fix the undefined symbol NRF_SRAM_END
Configure SRAM part for Heap

Enable Heap for nRF51822

---

bsp/stm32f10x/applications/canapp.c
bsp/stm32f10x/drivers/board.h
bsp/stm32f10x/drivers/bxcan.c
bsp/stm32f10x/drivers/bxcan.h
bsp/stm32f10x/drivers/gpio.c
bsp/stm32f10x/drivers/gpio.h
bsp/stm32f10x/project.uvprojx
bsp/stm32f10x/rtconfig.h

correct stm32f10x  compile error with canapis
correct stm32f10x can sendmsg  rtr flag set error

Fix stm32f10xcan.snd.rtr.err

---

src/ipc.c

Sorry, i was so careless that i missed this.

Sorry, fix missed, related #590.

---

bsp/lpc176x/drivers/sd.c

in function internal，get "geometry" form paramater "dev->user_data",  not use public variable "SDCfg"

update get “geometry” source

---

components/net/lwip-1.4.1/src/api/api_msg.c
components/net/lwip-head/src/api/api_msg.c

ref: http://savannah.nongnu.org/bugs/?38219

fixed Lwip bug: Assert on TCP netconn_write with sndtimeout set

---

components/net/lwip_nat/ipv4_nat.c
components/net/lwip_nat/ipv4_nat.h

fix incompatible unit in LWIP_NAT_TMR_INTERVAL_SEC
fix copy-paste bug
fix typo
components/net/lwip_nat/ipv4_nat.c | 10 +++++-----
components/net/lwip_nat/ipv4_nat.h |  2 +-
2 files changed, 6 insertions(+), 6 deletions(-)

fix various bugs in lwip-nat

---

libcpu/mips/loongson_1c/context_gcc.S

fix loongson 1c启动异常

---

bsp/stm32f10x/drivers/usart.c
components/drivers/serial/serial.c

- Add fifo mode to serial DMA rx when serial->config.bufsz != 0.
- Add usart DMA Rx driver to stm32f10x.

Improve serial DMA rx mode. #628

---

components/libc/newlib/syscalls.c
components/libc/pthreads/clock_time.c

Fixed time unit error.

---

bsp/stm32f40x/drivers/usart.c

- 1、参考 #628 #632 给 stm32f40x 平台增加新版本 DMA 串口驱动；
- 2、增加串口4及串口5驱动；

[BSP] Add usart DMA Rx driver to stm32f40x.

---

src/kservice.c

in 16bit cpu,  int is 16 bits, so fix it.

Fix type size for 16bit cpu

---

components/libc/dlib/syscall_close.c
components/libc/dlib/syscall_lseek.c

IAR编译器dlib __close,__lseek hanle传入正确值

IAR编译器dlib

---

components/finsh/cmd.c

Modified:
* list_mutex
* list_mailbox
* list_msgqueue
* list_device
etc.

[finsh] Align title and content in list_* cmd

---

bsp/lpc408x/applications/canapp.c
bsp/lpc408x/applications/startup.c
bsp/lpc408x/project.uvprojx
bsp/lpc408x/rtconfig.h
bsp/stm32f10x/applications/canapp.c
bsp/stm32f10x/drivers/bxcan.c
bsp/stm32f10x/project.uvprojx

can driver delete c99 mode

---

include/rtthread.h
src/clock.c
src/ipc.c
src/irq.c
src/kservice.c
src/mem.c
src/mempool.c
src/module.c
src/object.c
src/scheduler.c
src/slab.c
src/thread.c
src/timer.c

注释中的/*@{*/和/*@}*/，修改为/**@{*/和/**@}*/

修正了部分doxygen注释格式

---

bsp/dm365/drivers/spi-davinci.c

Fix missing spiconfig set in dm365

[Bsp] Fix missing spiconfig set in dm365

---

bsp/stm32f10x/drivers/bxcan.c

[BSP] stm32f10x bxcan correct ext frame filter

---

src/components.c

Update components.c 

---

libcpu/arm/am335x/context_iar.S

Add a missing file：libcpu/arm/am335x/context_iar.S

Add libcpu/arm/am335x/context_iar.S file

---

bsp/efm32/SConscript
bsp/efm32/rtconfig.h

To fix the building issue of EFM32 branch.

[BSP EFM32] Fix building issue

---

bsp/stm32f10x/drivers/gpio.c
components/drivers/include/drivers/pin.h
components/drivers/misc/pin.c

[Components] Drivers: pin add irq apis

---

components/net/KConfig
components/net/freemodbus/KConfig
components/net/freemodbus/modbus/functions/mbfunccoils_m.c
components/net/freemodbus/modbus/functions/mbfuncholding.c
components/net/freemodbus/port/portserial.c
components/net/freemodbus/port/portserial_m.c
components/net/freemodbus/port/porttimer.c
components/net/freemodbus/port/porttimer_m.c

- Update source to latest version
- Add KCconfig

Modbus update

---

components/net/KConfig
components/net/SConscript
components/net/lwip-2.0.2/SConscript
components/net/lwip-2.0.2/src/arch/sys_arch.c
components/net/lwip-2.0.2/src/lwipopts.h
components/net/lwip-2.0.2/src/lwippools.h
components/net/lwip-2.0.2/src/netif/ethernetif.c

fix scons file and compile conficts for lwip-2.0.2 version.

Lwip 2.0.2.fix

---

bsp/stm32l072/board/board.c

* set internal oscillator trimming value to default
* replace integer constant by macro from HAL library
* remove SystemCoreClockUpdate() because "SystemCoreClock" updated in HAL_RCC_ClockConfig()
* remove delay()

[bsp] update RCC initial for system

---

components/drivers/include/drivers/mmcsd_card.h
components/drivers/include/drivers/mmcsd_host.h
components/drivers/include/drivers/sdio.h
components/drivers/sdio/mmcsd_core.c
components/drivers/sdio/sdio.c

1.host lock改为互斥锁更为合理。
2.更正一些拼写错误。
3.改进sdio卡id识别策略。
4.function结构体增加priv成员。

improve sdio

---

bsp/ls1cdev/drivers/led.c
bsp/ls1cdev/drivers/led.h
bsp/ls1cdev/libraries/SConscript
bsp/ls1cdev/libraries/ls1c_clock.c
bsp/ls1cdev/libraries/ls1c_clock.h
bsp/ls1cdev/libraries/ls1c_delay.c
bsp/ls1cdev/libraries/ls1c_delay.h
bsp/ls1cdev/libraries/ls1c_gpio.c
bsp/ls1cdev/libraries/ls1c_gpio.h
bsp/ls1cdev/libraries/ls1c_pin.c
bsp/ls1cdev/libraries/ls1c_pin.h
bsp/ls1cdev/libraries/ls1c_public.c
bsp/ls1cdev/libraries/ls1c_public.h
bsp/ls1cdev/libraries/ls1c_pwm.c
bsp/ls1cdev/libraries/ls1c_pwm.h
bsp/ls1cdev/libraries/ls1c_regs.h
bsp/ls1cdev/libraries/ls1c_timer.c
bsp/ls1cdev/libraries/ls1c_timer.h

将“龙芯1c库”中的GPIO，PWM和硬件定时器相关接口移植到RT-Thread

---

bsp/ls1cdev/libraries/ls1c_gpio.c
bsp/ls1cdev/libraries/ls1c_gpio.h
bsp/ls1cdev/libraries/ls1c_public.c
bsp/ls1cdev/libraries/ls1c_public.h
bsp/ls1cdev/libraries/ls1c_regs.h
bsp/ls1cdev/rtconfig.h
bsp/ls1cdev/rtconfig.py
libcpu/mips/loongson_1c/interrupt.c
libcpu/mips/loongson_1c/ls1c.h

将支持的中断个数从32个扩展到160个，硬件定时器中断和外部中断（gpio中断）已调通

主要修改了龙芯1c的中断部分

---

bsp/stm32f10x/drivers/fm24cl64.c
bsp/stm32f10x/drivers/fm24cl64.h
bsp/stm32f10x/drivers/stm32f1_i2c.c
bsp/stm32f10x/drivers/stm32f1_i2c.h
components/drivers/i2c/fm24clxx.c
components/drivers/i2c/fm24clxx.h

添加 fm24clxx i2c driver ，并在stm32f10x上以中断方式实现

Fix fm24clxx.drv

---

bsp/stm32f10x/drivers/SConscript
bsp/stm32f10x/drivers/stm32f1_wdg.c
components/drivers/include/drivers/watchdog.h

BSP stm32f10x add watchdog driver

---

bsp/stm32f107/drivers/rt_stm32f10x_spi.c
bsp/stm32f107/drivers/rt_stm32f10x_spi.h

stm32f107 spi  dma add irq handdle

[Bsp] stm32f107 spi drv : dma add irq

---

components/drivers/spi/spi_wifi_rw009.c

[DeviceDriver] Fix rw009 WiFi module auto reconnect feature.

---

components/utilities/logtrace/log_file.c

you can use log_trace_flush() Flush cached data to log file

add log_file flush function

---

bsp/stm32f10x/readme.txt

Add some descriptions and an English version about building project in readme.txt.

[bsp] Add some descriptions and an English version about building project in readme.txt.

---

components/libc/dlib/sys/errno.h

开启 dlib 后，在编译 Mongoose 时缺少一些 errno ，所以从 LwIP 中拷贝过来。

[Libc] Add some errno to dlib.

---

examples/network/tcp_client.py
examples/network/tcp_server.py
examples/network/tcpclient.c
examples/network/tcpsendpacket.c
examples/network/tcpserver.c

add some python example for tcp server and client.
Complete some error handling when send or receive function returns a value is zero.
correct some explain

add some python example for tcp and complete some error handling.

---

bsp/ls1cdev/drivers/board.c
libcpu/mips/common/mipsregs.h
libcpu/mips/loongson_1c/context_gcc.S
libcpu/mips/loongson_1c/stackframe_fpu.h

增加龙芯1c硬浮点的支持（可以使用硬浮点了）

---

components/net/lwip-2.0.2/SConscript
components/net/lwip-2.0.2/apps/ping.c
components/net/lwip-2.0.2/apps/telnet.c

- 1、增加 ping 命令（从 LwIP1.3.2 中搬运过来），并对其做了完善。例如
- 增加请求超时功能，避免主机不存在导致 shell 线程卡死
- 完善命令交互效果，使其与 Linux 风格更为接近
> 实际命令效果如下：
```
msh />
msh />ping 192.168.2.104
60 bytes from 192.168.2.104 icmp_seq=0 ttl=64 time=1 ticks
60 bytes from 192.168.2.104 icmp_seq=1 ttl=64 time=0 ticks
60 bytes from 192.168.2.104 icmp_seq=2 ttl=64 time=0 ticks
60 bytes from 192.168.2.104 icmp_seq=3 ttl=64 time=0 ticks
msh />ping 192.168.2.108
From 192.168.2.108 icmp_seq=0 timeout
From 192.168.2.108 icmp_seq=1 timeout
From 192.168.2.108 icmp_seq=2 timeout
From 192.168.2.108 icmp_seq=3 timeout
msh />
```
- 2、增加 telnet 命令（从 Radio 项目中搬运过来），并对其使用 socket api 做了重构，可靠性也做了提升。

Add apps to lwip202

---

components/drivers/audio/audio.c
components/drivers/include/drivers/audio.h

audio驱动使用系统内的dataqueue，修复一些缩进，乱码

fix audio.c audio.h

---

bsp/x86/applications/application.c
bsp/x86/drivers/dma.h
bsp/x86/drivers/floppy.c
bsp/x86/drivers/floppy.h
bsp/x86/drivers/include/bsp.h
bsp/x86/drivers/include/i386.h

currently only read okay, write is not supported, this is enough for
me to study ELF, but the floppy is really small, now only about 400kb
space free showed by df("/").
Signed-off-by: parai <parai@foxmail.com>

x86: add floppy driver

---

components/libc/armlibc/sys/errno.h

添加了两个 errno ，为了构建 Mongoose 所用。

Fix ibc armlibc

---

components/drivers/i2c/i2c_core.c

delete an useless %s.

---

libcpu/arm/cortex-m3/cpuport.c
libcpu/arm/cortex-m4/cpuport.c
libcpu/arm/cortex-m7/cpuport.c

update cortex-m libcpu: fixed compile error.

---

bsp/ls1cdev/libraries/ls1c_gpio.c
bsp/ls1cdev/libraries/ls1c_i2c.c
bsp/ls1cdev/libraries/ls1c_i2c.h
bsp/ls1cdev/libraries/ls1c_public.c
bsp/ls1cdev/libraries/ls1c_public.h
bsp/ls1cdev/libraries/ls1c_regs.h

增加龙芯1c硬件I2C接口

---

include/rthw.h

修改rthw.h，增加一些宏定义，用于访问硬件寄存器，开发驱动时可以发方便地使用，另外增加一个微秒级延时函数的声明，但微秒延时函数需要用户定义。

renhaibo-branch

---

bsp/ls1cdev/libraries/ls1c_public.c
bsp/ls1cdev/libraries/ls1c_public.h
bsp/ls1cdev/libraries/ls1c_regs.h
bsp/ls1cdev/libraries/ls1c_spi.c
bsp/ls1cdev/libraries/ls1c_spi.h
bsp/ls1cdev/libraries/ls1c_timer.c
bsp/ls1cdev/rtconfig.py

增加龙芯1c的硬件SPI相关接口

---

src/kservice.c

fix rt_memcpy bug in "RT_USING_TINY_SIZE" enable

fix rt_memcpy bug in RT_USING_TINY_SIZE enable

---

bsp/fh8620/rtconfig.h
components/drivers/wlan/wlan_cmd.c

[wlan cmd] fix rt_kprintf %s no value problem
[lwip ip addr] Modify the IP & GW & MSK ADDR configure mode as string mode, insted separation mode

[wlan cmd][lwip ip addr] modify

---

components/drivers/wlan/wlan_cmd.c

[Fix] Fix issue caused by global info and local info in wlan/wlan_cmd.c
[Add] Change network_mode value according to the finsh shell command

[Fix] Fix issue caused by global info and local info in wlan/wlan_cmd.c

---

components/drivers/wlan/wlan_cmd.c
components/drivers/wlan/wlan_cmd.h

[Fix] Fix building error when `PKG_USING_CJSON` is not defined
[Mod] Modify wifi_usage help message

[Fix]  `PKG_USING_CJSON`  [Mod] wifi_usage

---

tools/building.py

[tools/building.py][Fix] Add `do_copy_file` function form `mkdist`

[tools/building.py][Fix] Add `do_copy_file` function form `mkdist`

---

components/drivers/include/drivers/usb_common.h
components/drivers/include/drivers/usb_device.h
components/drivers/usb/SConscript
components/drivers/usb/usbdevice/SConscript
components/drivers/usb/usbdevice/class/cdc_vcom.c
components/drivers/usb/usbdevice/class/hid.c
components/drivers/usb/usbdevice/class/hid.h
components/drivers/usb/usbdevice/class/mstorage.c
components/drivers/usb/usbdevice/core/core.c
components/drivers/usb/usbdevice/core/usbdevice.c
components/drivers/usb/usbhost/SConscript
components/drivers/usb/usbhost/class/hid.c
components/drivers/usb/usbhost/class/hid.h
components/drivers/usb/usbhost/class/mass.c
components/drivers/usb/usbhost/class/mass.h
components/drivers/usb/usbhost/class/udisk.c
components/drivers/usb/usbhost/class/ukbd.c
components/drivers/usb/usbhost/class/umouse.c
components/drivers/usb/usbhost/core/core.c
components/drivers/usb/usbhost/core/driver.c
components/drivers/usb/usbhost/core/hub.c

1，能够成功创建虚拟串口，在电脑上显示正常
2，电脑上打开虚拟串口，发送数据，系统会奔溃掉，还没检查原因

[usb]update usb stack

---

components/drivers/serial/serial.c

Fix compile error when RT_USING_POSIX_TERMIOS is not define.

[DeviceDriver][serial]Fix compile error when RT_USING_POSIX_TERMIOS is not define.

---

bsp/stm32l476-nucleo/.config
bsp/stm32l476-nucleo/Kconfig
bsp/stm32l476-nucleo/SConstruct
bsp/stm32l476-nucleo/applications/application.c
bsp/stm32l476-nucleo/applications/startup.c
bsp/stm32l476-nucleo/applications/userled.c
bsp/stm32l476-nucleo/drivers/Kconfig
bsp/stm32l476-nucleo/drivers/SConscript
bsp/stm32l476-nucleo/drivers/board.c
bsp/stm32l476-nucleo/drivers/board.h
bsp/stm32l476-nucleo/drivers/drv_led.c
bsp/stm32l476-nucleo/drivers/drv_led.h
bsp/stm32l476-nucleo/drivers/gpio.c
bsp/stm32l476-nucleo/drivers/gpio.h
bsp/stm32l476-nucleo/drivers/usart.c
bsp/stm32l476-nucleo/project.uvprojx
bsp/stm32l476-nucleo/rtconfig.h
bsp/stm32l476-nucleo/rtconfig.py

- add pin driver and user led
- add kconfig support
- clean code

[bsp] stm32l476 bsp update

---

components/drivers/KConfig
components/drivers/usb/usbdevice/SConscript
components/drivers/usb/usbdevice/class/cdc.h
components/drivers/usb/usbdevice/class/ecm.c
components/drivers/usb/usbdevice/core/usbdevice.c

[Components][Drivers][USB] Add CDC-ECM class (LWIP on USB)

---

bsp/ls1cdev/drivers/drv_i2c.c
bsp/ls1cdev/drivers/drv_i2c.h
bsp/ls1cdev/rtconfig.h

龙芯1c平台的rtt统一标准的I2C接口

---

components/drivers/KConfig
components/drivers/include/drivers/usb_common.h
components/drivers/include/drivers/usb_device.h
components/drivers/usb/usbdevice/SConscript
components/drivers/usb/usbdevice/class/hid.c
components/drivers/usb/usbdevice/class/winusb.c
components/drivers/usb/usbdevice/class/winusb.h
components/drivers/usb/usbdevice/core/core.c
components/drivers/usb/usbdevice/core/usbdevice.c

微软OS描述符 可以描述设备，让设备加载Windows内部的驱动 比如winusb rndis

[Compinents][USB]增加USB协议栈对微软OS描述符的支持,修复HID class的IAD接口,增加免驱新class WinUSB

---

bsp/lpc54608-LPCXpresso/SConstruct
bsp/lpc54608-LPCXpresso/drivers/drv_emac.c
bsp/lpc54608-LPCXpresso/rtconfig.py

- fix emac driver bugs: 
- fix scons + armcc build error
- add '--C99' for cflags
- cxxflags remove '--C99'

Lpc54608 fixbugs

---

components/drivers/usb/usbdevice/class/mstorage.c
components/drivers/usb/usbdevice/core/core.c

[Components][Drivers][USB][Core]fix io request

 [Components][Driver][USB][Class]fix msc class

---

bsp/mini2440/drivers/sdcard.c

修改了mini2440的sdcard驱动，适配了文件系统接口，增加了csd信息读取
另问一下mini2440现在还有维护吗。

add csd support for mini2440 sdio driver.

---

components/libc/compilers/armlibc/termios.h
components/libc/compilers/dlib/termios.h
components/libc/compilers/newlib/termios.h
components/libc/termios/posix_termios.c
examples/libc/termios_test.c

1. Add termios test. 2.Add termios.h

[Termios]1. Add termios test. 2.Add termios.h

---

components/drivers/Kconfig
components/drivers/include/drivers/usb_host.h
components/drivers/usb/usbhost/SConscript
components/drivers/usb/usbhost/class/mass.c
components/drivers/usb/usbhost/class/mass.h
components/drivers/usb/usbhost/class/udisk.c
components/drivers/usb/usbhost/core/core.c
components/drivers/usb/usbhost/core/hub.c
components/drivers/usb/usbhost/core/usbhost.c

1。原则上支持HUB 但请慎用，下版本会修复部分hub不兼容的问题，反正手上有个3.0hub插上有问题
2。关于U盘的支持 已测试金士顿2.0U盘 威刚3.0U盘 不知名品牌2.0U盘均测试通过
3。关于F4 hub的问题。由于F4的OTGFS仅支持15个pipe因此HUB需要3个pipe U盘需要4个pipe CDC需要5个pipe。等等 即使有那么多口也不是全都能插东西。

 [Components][Drivers][USB HOST]Fix core stack and msc driver

---

bsp/imxrt1052-evk/project.uvoptx
bsp/imxrt1052-evk/project.uvprojx

[bsp] remove unused file from project

---

components/libc/pthreads/pthread.h
components/libc/pthreads/pthread_cond.c
components/libc/pthreads/sched.h

add some parameter check and function defintion etc.

add some parameter check and function defintion etc.

---

components/dfs/src/dfs.c

Here is the porting code of lwext4:
https://github.com/parai/as/tree/master/com/as.infrastructure/system/fs/lwext4

[dfs] fix the issue of stat "/.." of lwext4

---

bsp/stm32f4xx-HAL/drivers/board.c

修正84M主频下48M时钟的产生错误
修正没有对部分芯片需要单独配置48M时源(RCC_PERIPHCLK_CLK48)
增加芯片存在非通用时钟树配置时产生编译警告
【严正警告】F4xx工作在100M/180M主频下(F411、F429等的最大主频)无法通过PLLN正确产生48M时钟,此时请另行配置时钟（（PLLSAIP等方式实现48M时钟）建议使用CubeMX生成时钟配置代码）或降频至84M/168M使用。自动配置的时钟将导致芯片无法启动。（只要是不能产生48M时钟的HCLK配置均不能使用该BSP内的自动时钟配置，包括但不限于以下合法时钟：
84M
168M
如果看不懂以上内容,当遇无法启动或外设异常时请直接使用cubeMX产生时钟配置覆盖进board.c。
）

[BSP][STM32F4xx-HAL]Update clock tree

---

bsp/imxrt1052-evk/applications/SConscript
bsp/lpc54608-LPCXpresso/applications/SConscript
bsp/stm32f429-apollo/applications/SConscript
components/libc/compilers/dlib/sys/time.h

[dlib/sys/time.h] Fix iar version problem
[bsp/stm32f429-apollo/applications/SConscript] Remove CPPDEFINES

Fix-IAR-Version-Problem

---

components/dfs/filesystems/ramfs/dfs_ramfs.c

[Components][DFS][RAMFS]Fix bug

---

components/libc/compilers/dlib/time.c

Add dlib/time.c to support gettimeofday function

[libc] Add gettimeofday support to dlib

---

components/drivers/usb/usbdevice/class/cdc_vcom.c

@uestczyh222 
usb vcom add fix console problems

[Components] driver usb vcom fix error for console

---

components/net/Kconfig

update lwip Kconfig

---

components/drivers/usb/usbdevice/class/cdc_vcom.c

[Components][Drivers][USB]fix compiling errors

---

components/drivers/usb/usbdevice/class/cdc_vcom.c

[Components][Drivers][USB]vcom dma_tx模式下根据bulk in提交能力限制tx_ringbuffer的填充长度,避免对下次bulk in传输造成影响.

cdc_vcom dma 发送流程修改

---

components/libc/compilers/minilibc/sys/types.h
components/libc/compilers/minilibc/time.h

for fix #1223 pr [CI build error](https://travis-ci.org/RT-Thread/rt-thread/jobs/342202330)

Fix minilibc time

---

documentation/coding_style_cn.md
documentation/coding_style_en.txt

astyle的配置语句中添加 --indent-preproc-block ，格式化实现如图效果

添加astyle工具的配置语句，格式化时可以实现宏定义的块缩进。

---

components/drivers/spi/spi_msd.c

update spi_msd.c: fixed CSD Version 2.0 sector count calc.

Fixed CSD Version 2.0 sector count calc.

---

components/finsh/cmd.c

```
msh />free
memheap  pool size  max used size available size
---- ---------- ------------- --------------
sram 65828      48            65780
heap 31457280   6128          31451556
msh />
```
```
msh />free
memheap  pool size  max used size available size
------- ---------- ------------- --------------
sram    65828      48            65780
heap    31457280   6128          31451556
msh />
```

[Components][Finsh] Fix list object name align issue.

---

components/drivers/usb/usbdevice/class/cdc_vcom.c

fix function _ep_out_handler  to notify receive data.

fix cdc_vcom.c notify receive data.

---

bsp/imxrt1052-evk/drivers/board.c
bsp/imxrt1052-evk/drivers/drv_uart.c
bsp/imxrt1052-evk/drivers/drv_uart.h

1. 将CLOCK_SetMux(kCLOCK_UartMux, 0);CLOCK_SetDiv(kCLOCK_UartDiv, 0);从board.c移到drv_uart.c的imxrt_hw_uart_initI()中.
1. 将CLOCK_EnableClock(kCLOCK_Iomuxc);放入board.c的BOARD_BootClockRUN()中.而不是每次uart初始化都要重复操作.
1. 修改BOARD_DebugConsoleSrcFreq()函数名称为GetUartSrcFreq().
1. 删除多余空格

[BSP][i.mxrt1052] fix uart

---

components/drivers/src/pipe.c
components/finsh/msh.c
src/mempool.c

fixed signed/unsigned mismatch warning

---

bsp/imxrt1052-evk/Libraries/drivers/fsl_enet.c
bsp/imxrt1052-evk/drivers/drv_eth.c

- fixed eth send frame bug
- code clean
修复i.mx rt以太网驱动
- 修复i.mx rt在一个包分散在多个pbuf里面出错的问题
- 修复iperf测试失败的问题
- 整理代码

[bsp][imxrt1052-evk] update eth driver

---

bsp/imxrt1052-evk/drivers/drv_hwtimer.c
bsp/imxrt1052-evk/drivers/drv_hwtimer.h

Add drv_hwtimer to imxrt1052 BSP

[BSP][IMXRT1052]Add drv_hwtimer

---

components/drivers/usb/usbhost/class/udisk.c

[Components][HOST]fix sem name

---

bsp/stm32f7-disco/Libraries/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/startup_stm32f745xx.s
bsp/stm32f7-disco/Libraries/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/startup_stm32f746xx.s
bsp/stm32f7-disco/Libraries/CMSIS/Device/ST/STM32F7xx/Source/Templates/gcc/startup_stm32f756xx.s

[Bsp][F7-Disco]fix startup by gcc

---

components/drivers/i2c/i2c_dev.c

fix an i2c debug print bug

---

bsp/imxrt1052-evk/Kconfig

1、menuconfig适配shareboard选项。
2、对应的bsp的scons脚本不需要更改。

适配shareboard。

---

bsp/imxrt1052-evk/Kconfig
bsp/imxrt1052-evk/drivers/SConscript

[BSP] 修改env menuconfig支持Seeed Studio RT-M7开发板

add Seeed Studio RT-M7 board support.|添加Seeed Studio RT-M7开发板支持

---

bsp/ls1cdev/drivers/drv_gpio.c
bsp/ls1cdev/drivers/drv_gpio.h

[bsp/ls1cdev]drv_gpio add interrupt ops

---

components/dfs/Kconfig
components/libc/Kconfig
components/libc/compilers/armlibc/SConscript
include/libc/libc_signal.h
src/signal.c
tools/building.py
tools/gcc.py

Add cconfig.h file for different version of GCC, which is automatically
detected and generated by scons script.

Add GCC version detection.

---

bsp/imxrt1052-evk/xip/SConscript

fix ATK shareboard  board xip issue. 

---

src/ipc.c

adjust rt_event_send() hook function position

---

bsp/ls1cdev/.config
bsp/ls1cdev/SConstruct
bsp/ls1cdev/drivers/board.c
bsp/ls1cdev/drivers/net/synopGMAC.c
bsp/ls1cdev/kconfig
bsp/ls1cdev/libraries/ls1c_pin.c
bsp/ls1cdev/ls1c_ram.lds
bsp/ls1cdev/rtconfig.h
libcpu/mips/loongson_1c/cpuport.c
libcpu/mips/loongson_1c/sdram_cfg.h
libcpu/mips/loongson_1c/start_gcc.S

1、添加自引导特性，添加配置选项
2、修复cpuport.c的bug
3、修复ls1c_pin.c不能默认复用的bug

[bsp/ls1cdev]添加自引导特性，添加配置选项 

---

bsp/imxrt1052-evk/Kconfig
bsp/imxrt1052-evk/Libraries/arm/MIMXRT1052xxxxx_flexspi_nor.scf
bsp/imxrt1052-evk/rtconfig.h
bsp/imxrt1052-evk/xip/SConscript

[BSP][RT1050] fix EVK .scf issue. | 修复 官方板分散加载文件问题.

---

components/finsh/msh_cmd.c
components/net/Kconfig
components/net/lwip-1.4.1/src/netif/ethernetif.c
components/net/lwip-2.0.2/src/netif/ethernetif.c

1. 更新 Kconfig ，添加 erx/etx线程的配置。
2. 列出网络状态时，同时列出所有的udp连接。

update lwip Kconfig & cmd.

---

components/net/Kconfig
components/net/lwip_dhcpd/dhcp_server.c

[components/net] add dns server ip address config, may custom in `menuconfig`

[components/net] add dns server ip address config

---

bsp/stm32f10x-HAL/drivers/board.c
bsp/stm32f10x-HAL/drivers/drv_usart.c

修复了问题：当屏蔽宏定义RT_DEBUG时，RT_ASSERT()调用的函数运行不到

[stm32f10x-HAL] Fixed the problem of including functions in RT_ASSERT()

---

components/drivers/src/waitqueue.c

[components][drivers] Add irq lock to rt_wqueue_wait.

---

bsp/stm32f10x-HAL/drivers/board.c

[stm32f10x-HAL] add function rt_hw_us_delay

---

components/dfs/filesystems/net/socket/sys/socket.h

[components/dfs] Fix inconsistent structure of lwip_sock structure, adaptation lwip202 version

[components/dfs] Fix inconsistent structure of lwip_sock structure

---

components/net/lwip_dhcpd/SConscript
components/net/lwip_dhcpd/dhcp_server.c
components/net/lwip_dhcpd/dhcp_server.h
components/net/lwip_dhcpd/dhcp_server_raw.c

添加新的DHCP服务器，使用LWIP RAW API。
-  不占用socket；
-  不需要独立的线程; 
-  支持指定网卡回应，防止串扰。

add new DHCPD use lwip raw api.

---

tools/building.py

- 使用原先的 `{target_name:(CROSS_TOOL, PLATFORM)}` 方式，自动更新 `rtconfig.CROSS_TOOL, rtconfig.PLATFORM`
- 调整 GenCconfigFile 位置，至 `{target_name:(CROSS_TOOL, PLATFORM)}` 代码的下面
- 统一 `AddOption` 位置至 `PrepareBuilding` 函数开头，避免接下来使用 `GetOption` 可能异常的问题

完善对于 'scons --target=cc' 生成的工程可能编译出错问题的修复

---

components/dfs/src/dfs.c

- 修改之后的打印效果
```
fd type    ref magic  path
-- ------  --- ----- ------
0 file      1 fdfd  /uart0
1 socket    1 fdfd
2 dir       1 fdfd
3 user      1 fdfd
4 file      1 fdfd  /uart0
```

[components][dfs] list_fd 打印信息更加友好

---

components/finsh/msh_cmd.c

[finsh] update netstat, add udp macro judgment

[finsh] update netstat

---

components/finsh/shell.c
components/finsh/shell.h

update shell prompt.

---

components/dfs/src/dfs.c
components/finsh/shell.c
components/net/lwip-2.0.2/src/arch/sys_arch.c

add re-initial check.

---

components/drivers/include/drivers/usb_common.h
components/drivers/usb/usbdevice/class/hid.c

[Components][USB][Device]Support customer HID class|支持自定义HID设备

---

bsp/imxrt1052-evk/drivers/drv_eth_fire.c

[BSP][RT1050] Fix the fire ethernet driver compilation bug. | 修复野火以太网驱动编译BUG.

[BSP][RT1050] Fix the fire ethernet driver compilation bug. 

---

components/dfs/Kconfig
components/dfs/src/dfs.c
components/dfs/src/dfs_fs.c

- [dfs] Update DFS_FD_MAX default size to 16.
- [dfs] Update error log for dfs. fixed #1620

Update DFS fd_max and errror log

---

tools/building.py

[scons] remove check whether exist group library.

---

bsp/stm32f10x/drivers/gpio.c

Add GPIO Out_OD mode config In stm32f10x bsp

Add GPIO Out_OD mode config

---

tools/mkdist.py

- fixed windows path case bug
- fixed linux walk_children crash
- rewrite dist/copy/copy-header
- auto update CDK/IAR/MDK/VS project after "scons --dist/copy"

[tools] rewrite "scons --dist/copy/copy-header"

---

components/net/at/include/at.h
components/net/at/src/at_client.c
components/net/at/src/at_server.c

[net][at] Using DMA mode first when device is supported.

---

components/Kconfig
src/components.c

add config main thread priority

---

libcpu/arm/cortex-m3/cpuport.c
libcpu/arm/cortex-m4/cpuport.c
libcpu/arm/cortex-m7/cpuport.c

为cortex-m4、cortex-m4、cortex-m7系列cpu增加软复位函数

add rt_hw_cpu_reset for cortex-m cpu

---

bsp/stm32f4xx-HAL/drivers/drv_pwm.c

[STM32 BSP]Fix PWM channel calculate argorithm.

---

components/drivers/include/drivers/spi.h
components/drivers/spi/spi_flash_sfud.c
components/drivers/spi/spi_flash_sfud.h

[components/drivers/spi] 增加 sfud flash 设备查找接口，方便在应用层拿到设备对象

[components/drivers/spi] 增加 sfud flash 设备查找接口

---

components/utilities/ymodem/ymodem.c

[component][ymodem] Fix compilation warning in MDK

[component][ymodem] Fix compilation warning in MDK

---

components/net/freemodbus/modbus/rtu/mbrtu_m.c

修改源文件中的断言指令

---

components/utilities/ymodem/ymodem.c

[components][ymodem] 修复 ymodem 不支持 secureCRT 下 1024字节传输的问题

[components][ymodem] 修复 ymodem 不支持 secureCRT 下 1024字节传输的问题

---

tools/pymenuconfig.py

Solve the flicker problem when display the pyconfig window.

---

tools/kconfig-frontends/frontends/mconf/mconf.c

修改 menuconfig 程序的返回码，解决 ci 会认为该程序执行失败的问题。 @BernardXiong

[tools]: change the status code

---

bsp/stm32f40x/drivers/gpio.c

[bsp][stm32f40x] Fix the bug of gpio driver.

---

documentation/coding_style_en.txt

There is three "micro" word in this document, I think these means "macro".
Please check.

There is some "micro" word (e.g. section6), maybe "macro"?

---

bsp/stm32f4xx-HAL/drivers/drv_pwm.c
components/drivers/include/drivers/rt_drv_pwm.h
components/drivers/misc/rt_drv_pwm.c

[components][drivers][pwm] Add rt_pwm_disable function and API Interface 
[bsp][stm32f4xx-HAL] update PWM driver
1. Fixed the overflow error of intermediate value
2. Fixed the error that counter register is not cleared
3. Add macro control for each channel

update PWM driver | 完善pwm驱动

---

bsp/stm32f10x/drivers/Kconfig
bsp/stm32f10x/drivers/SConscript
bsp/stm32f10x/drivers/i2c.c
bsp/stm32f10x/drivers/i2c.h

为 bsp\stm32f10x 标准库添加了 i2c 总线驱动

Add I2C bus driver for stm32f10x

---

bsp/hifive1/Makefile

[bsp][hifive1] add Makefile file

---

bsp/stm32f0x/applications/startup.c
bsp/stm32f107/applications/startup.c
bsp/stm32f10x/applications/startup.c
bsp/stm32f20x/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F2xx/system_stm32f2xx.c
bsp/stm32f20x/applications/startup.c
bsp/stm32f40x/Libraries/CMSIS/ST/STM32F4xx/Source/Templates/system_stm32f4xx.c
bsp/stm32f40x/drivers/board.h
bsp/stm32f411-nucleo/drivers/board.h
bsp/stm32f429-apollo/drivers/board.h
bsp/stm32f429-armfly/drivers/board.h
bsp/stm32f429-disco/drivers/board.h
bsp/stm32f429-disco/project.uvproj
bsp/stm32f7-disco/drivers/board.h
bsp/stm32l072/app/startup.c
bsp/stm32l475-iot-disco/drivers/board.h
bsp/stm32l476-nucleo/drivers/board.h

[bsp][stm32] Fix compile failure when using ARM Compiler V6.

 [bsp][stm32] Fix compile failure when using ARM Compiler V6.

---

components/libc/compilers/dlib/time.c

修复IAR dlib的time时间映射，支持64bit的时间戳

修复IAR的dlib时间映射，支持64bit的时间。

---

bsp/stm32f10x-HAL/drivers/drv_usart.c

【bsp】【stm32f10x-HAL】 update drv_usart.c

---

components/utilities/Kconfig
components/utilities/ulog/ulog.c
components/utilities/ulog/ulog.h
components/utilities/ulog/ulog_def.h

[component][ulog] Reduce thread stack usage when using ulog.

---

components/utilities/ulog/ulog.c

- 优化 hexdump 格式，类似下面效果
```shell
D/HEX buf_dump_test: 0000-0010: 00 01 02 03 04 05 06 07  08 09 0A 0B 0C 0D 0E 0F    ................
0010-0020: 10 11 12 13 14 15 16 17  18 19 1A 1B 1C 1D 1E 1F    ................
0020-0030: 20 21 22 23 24 25 26 27  28 29 2A 2B 2C 2D 2E 2F     !"#$%&'()*+,-./
0030-0040: 30 31 32 33 34 35 36 37  38 39 3A 3B 3C 3D 3E 3F    0123456789:;<=>?
0040-0050: 40 41 42 43 44 45 46 47  48 49 4A 4B 4C 4D 4E 4F    @ABCDEFGHIJKLMNO
0050-0060: 50 51 52 53 54 55 56 57  58 59 5A 5B 5C 5D 5E 5F    PQRSTUVWXYZ[\]^_
0060-0070: 60 61 62 63 64 65 66 67  68 69 6A 6B 6C 6D 6E 6F    `abcdefghijklmno
0070-0080: 70 71 72 73 74 75 76 77  78 79 7A 7B 7C 7D 7E 7F    pqrstuvwxyz{|}~.
```
- 全局日志级别高于 DEBUG 时，hexdump  停止输出

[component][ulog] Update ulog hexdump format.

---

bsp/allwinner_tina/drivers/drv_gpio.c
bsp/allwinner_tina/drivers/drv_sdio.c
bsp/allwinner_tina/drivers/spi/drv_spi.c
bsp/imxrt/Libraries/imxrt1050/drivers/drv_eth.c
bsp/imxrt/Libraries/imxrt1050/drivers/drv_eth_fire.c
bsp/imxrt1052-evk/drivers/drv_eth.c
bsp/imxrt1052-evk/drivers/drv_eth_fire.c
bsp/qemu-vexpress-a9/drivers/audio/drv_pl041.c
bsp/qemu-vexpress-a9/drivers/drv_keyboard.c
bsp/qemu-vexpress-a9/drivers/drv_mouse.c
bsp/qemu-vexpress-a9/drivers/drv_sdio.c
bsp/x1000/drivers/mmc/drv_mmc.c
components/dfs/src/dfs.c
components/dfs/src/dfs_file.c
components/dfs/src/dfs_fs.c
components/drivers/sdio/block_dev.c
components/drivers/sdio/mmc.c
components/drivers/sdio/mmcsd_core.c
components/drivers/sdio/sd.c
components/drivers/sdio/sdio.c
components/drivers/serial/serial.c
src/signal.c

rtdbg.h 中的 dbg_log API 由于资源占用过多，已经 **废弃**，不再建议大家去使用：
https://github.com/RT-Thread/rt-thread/blob/3dc6334b2a490b3e7cd6ca42778c2c70cebd3b28/include/rtdbg.h#L85-L90
替换所有的 dbg_log 为 LOG_X 格式日志

Change all dbg_log to LOG_X.

---

components/drivers/wlan/wlan_dev.c

fix wlan_dev bug

---

bsp/stm32f40x/project.uvproj
bsp/stm32f40x/project.uvprojx
bsp/stm32f429-apollo/project.uvprojx

[bsp] fix default project compilation error.

---

examples/network/tcpclient.c
examples/network/tcpserver.c
examples/network/udpclient.c
examples/network/udpserver.c

[examples][network] 更新 tcp client & server 例程

[examples][network] 更新 tcp/udp client & server 例程

---

tools/building.py
tools/gcc.py

SCons script should apply this fix: see [Scons PR 3237]
Tested with Python 3.7.1 + Scons 3.0.1 with fix.

 [Tools] Modify buliding.py and gcc.py for work with python 3.

---

include/rtthread.h
src/timer.c

Change 'rt_timer_timeout_hook' function to 'rt_timer_enter_hook' and add 'rt_timer_exit_hook' hook function.

[kernel]修改定时器 hook 函数

---

components/drivers/Kconfig

[drivers] Modify RTC_SYNC_USING_NTP depends on PKG_NETUTILS_NTP

---

bsp/stm32f429-apollo/drivers/Kconfig
bsp/stm32f429-apollo/drivers/SConscript
bsp/stm32f429-apollo/drivers/audio/drv_audio.h
bsp/stm32f429-apollo/drivers/audio/drv_mic.c
bsp/stm32f429-apollo/drivers/audio/drv_sound.c
bsp/stm32f429-apollo/drivers/audio/drv_wm8978.c
bsp/stm32f429-apollo/drivers/audio/drv_wm8978.h
bsp/stm32f429-apollo/drivers/drv_spi.c
bsp/stm32f429-apollo/drivers/stm32f4xx_hal_conf.h

Add STM32F429-Apollo platform sound and micphoe driver.

[bsp][stm32f429-apollo]add audio sound and micphone driver.

---

bsp/stm32f107/drivers/usart.c

Fix usart3 initialization bug

---

bsp/stm32f411-nucleo/template.emProject
tools/building.py
tools/ses.py

Add a draft project generator for SEGGER Embedded Studio.

[Tools] Add a draft project generator for SES.

---

tools/utils.py

此处引发了
```
scons: Reading SConscript files ...
AttributeError: 'bool' object has no attribute 'split':
....................
File "rt-thread/tools/utils.py", line 248:
la = ver1.split('.')
```
错误.

[tools] fix bug.

---

include/libc/libc_signal.h

[unite] header of process

---

components/utilities/ulog/ulog.h
components/utilities/ulog/ulog_def.h

增加内存信息显示API, 减ulog Flash占用
log_hex
LOG_HEX

减ulog Flash占用

---

bsp/CME_M7/rtconfig.h
bsp/CME_M7/rtconfig.py
bsp/apollo2/rtconfig.py
bsp/frdm-k64f/MK64F.sct
bsp/frdm-k64f/rtconfig.py
bsp/lpc176x/SConstruct
bsp/mb9bf500r/rtconfig.py
bsp/mini4020/rtconfig.h
bsp/nv32f100x/rtconfig.py
bsp/rm48x50/rtconfig.py
bsp/samd21/rtconfig.py
bsp/samd21/sam_d2x_asflib/SConscript
bsp/stm32f107/drivers/stm32_eth.c
bsp/stm32f40x/drivers/stm32f4xx_eth.c
bsp/stm32f429-disco/drivers/drv_lcd.c
bsp/stm32f429-disco/drivers/drv_touch.c

修复一系列BSP编译错误

---

bsp/qemu-vexpress-a9/cpu/context_gcc.S
bsp/qemu-vexpress-a9/cpu/cpuport.c
bsp/qemu-vexpress-a9/cpu/interrupt.c
bsp/qemu-vexpress-a9/drivers/board.c

Move idle_wfi to board.c for idle hook.

[bsp][qemu-vexpress] code cleanup.

---

bsp/qemu-vexpress-a9/link.lds
bsp/stm32/stm32f429-atk-apollo/board/linker_scripts/link.lds

[bsp] 为常用板卡的 gcc 链接脚本增加 utest section 段

[bsp] 为常用板卡的 gcc 链接脚本增加 utest section 段

---

tools/building.py
tools/menuconfig.py
tools/pymenuconfig.py

[tools] pyconfig 增加 silent 模式，不显示窗口但可以更新 .config 和 rtconfig.h

[tools] pyconfig 增加 silent 模式，不显示窗口但可以更新 .config 和 rtconfig.h

---

bsp/x1000/drivers/usbd/drv_usbd.c

Fix bugs of X1000's USB driver.

Fix bugs of X1000's USB driver.

---

components/net/at/at_socket/at_socket.c

fix socket nullptr bug

---

tools/vsc.py

**Add description here.** **VS code 功能支持 env 在中文路径**
(@<github.com username(s)> Ex: @BernardXiong )  

[tools][vsc.py] Support Chinese path

---

bsp/stm32f40x/drivers/usart.c

请仔细阅读以下文字。请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please read the following carefully. Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;
并确认已经在什么情况或板卡上进行了测试。

[bsp][stm32]fix bug with dma setting

---

bsp/stm32f10x/drivers/usart.c

请仔细阅读以下文字。请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please read the following carefully. Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;
并确认已经在什么情况或板卡上进行了测试。

[bsp][stm32f10x]fix bug with dma setting

---

components/drivers/spi/spi_flash_sfud.c

调整 rt_sfud_flash_find 函数位置，避免被 FINSH 宏包裹

[DeviceDriver][SFUD] Change the rt_sfud_flash_find() function position.

---

.travis.yml
tools/mkdist.py

[
添加新 BSP 的 CI 检测，修改 dist 后的语法错误。
]

【修改】：添加新 BSP 的 CI 检测，修改 dist 后的语法错误。

---

components/drivers/wlan/wlan_dev.c
components/drivers/wlan/wlan_lwip.c

[DeviceDriver][wlan] Add device ops to wlan.

---

bsp/amebaz/SConstruct
bsp/gd32303e-eval/SConstruct
bsp/gd32450z-eval/SConstruct
bsp/imxrt/imxrt1050-ArchMix/SConstruct
bsp/imxrt/imxrt1050-evk/SConstruct
bsp/imxrt1052-evk/SConstruct
bsp/lpc54114-lite/SConstruct
bsp/lpc824/SConstruct
bsp/mb9bf500r/SConstruct
bsp/mb9bf506r/SConstruct
bsp/mb9bf618s/SConstruct
bsp/nuvoton_nuc472/SConstruct
bsp/swm320-lq100/SConstruct
bsp/upd70f3454/SConstruct
tools/building.py

[
- 在IOT板子上发现，使用 iar 工具链在命令行进行编译，链接阶段会失败。原因是库文件没有参与链接，经过修改后。iar 工具链在命令行中能够正确编译链接，且不影响生成 iar 工程。
]

[tools] 修复命令行使用 iar 工具链，库文件链接不上的问题

---

components/utilities/utest/utest.c
components/utilities/utest/utest.h
components/utilities/utest/utest_assert.h

[components][utest] 将 utest_assert.h 加入 utest.h，以后测试用例仅需要包含 utest.h
[components][utest] 增加 buf 类型的字节比较 assert 宏
[components][utest] 修复错误日志打印的输出类型为 ERR 级别
以上修改均已在 `stm32.stm32f429-atk-apollo` BSP 中测试验证。
@armink @BernardXiong 

[components][utest] 修复日志打印问题并增加内存比较接口

---

components/dfs/src/dfs_file.c

Remove opened file check in dfs_file_open function. It will be replaced with POSIX flock/fcntl.

[DFS] Remove opened file check

---

bsp/stm32f10x-HAL/Libraries/STM32F1xx_HAL_Driver/Inc/stm32f1xx_hal_can.h

[stm32f1xx_hal_can.h fix  "CAN_FLAG_TXOK2" define error]

Fixbug stm32f1xx_hal_can.h

---

bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f4.c
bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_f7.c
bsp/stm32/stm32f103-atk-nano/board/Kconfig
bsp/stm32/stm32f103-fire-arbitrary/board/Kconfig
bsp/stm32/stm32f407-atk-explorer/board/Kconfig
bsp/stm32/stm32f407-atk-explorer/board/ports/fal_cfg.h
bsp/stm32/stm32f429-armfly-v6/board/Kconfig
bsp/stm32/stm32f429-armfly-v6/board/ports/fal_cfg.h
bsp/stm32/stm32f429-atk-apollo/board/Kconfig
bsp/stm32/stm32f429-atk-apollo/board/ports/fal_cfg.h
bsp/stm32/stm32f429-fire-challenger/board/Kconfig
bsp/stm32/stm32f429-fire-challenger/board/ports/fal_cfg.h
bsp/stm32/stm32f767-atk-apollo/board/Kconfig
bsp/stm32/stm32f767-atk-apollo/board/ports/drv_qspi_flash.c
bsp/stm32/stm32f767-atk-apollo/board/ports/fal_cfg.h
bsp/stm32/stm32f767-fire-challenger/board/ports/drv_qspi_flash.c
bsp/stm32/stm32f767-fire-challenger/board/ports/fal_cfg.h
bsp/stm32/stm32l475-atk-pandora/board/Kconfig
bsp/stm32/stm32l475-atk-pandora/board/ports/drv_qspi_flash.c

[
- 修复 flash 驱动在 fal 测试下出现的 bug
- 统一 spi flash 在 kconfig 的提示项为大写
已经在相应的开发板上进行测试。
]

[bsp][stm32] optimize stm32 series BSP

---

src/Kconfig
src/kservice.c

- 更新 Kconfig 里的版本号
- 更新版本信息中的年份信息

Update the version number and year info

---

components/utilities/ymodem/ymodem.c

[
ymodem support multiple files transmission.
TEST: stm32f767-apollo
]

ymodem support multiple files transmission

---

components/net/lwip-2.1.0/src/arch/sys_arch.c
components/net/lwip-2.1.0/src/netif/ethernetif.c

[
修复编译过程中的警告。
Fix compile-time warnings。
已在X1000 BSP测试过，其他BSP应该也能正常工作。
Has been tested on the X1000 BSP, othre BSP should work as well.
]

net:  lwip-2.1.0: 修复编译过程中的警告/Fix compile-time warnings

---

components/libc/pthreads/pthread.c
src/idle.c

修正pthread的问题，包括join及detach。当前在QEMU VExpress A9 BSP中完成测试，utest测试用例后续推送。

Fix pthread

---

components/dfs/src/dfs.c
components/drivers/serial/serial.c
src/kservice.c
src/mem.c

修正无符号和有符号数标记时的编译警告，bsp/simualtor with VC++测试通过

[Kernel] Code cleanup for compiling warning.

---

include/rtdef.h

添加 rt_uint64_t/rt_int64_t 类型定义

Add rt_uint64_t/rt_int64_t type definition.

---

bsp/stm32/libraries/templates/stm32f0xx/SConscript
bsp/stm32/libraries/templates/stm32f10x/SConscript
bsp/stm32/libraries/templates/stm32f4xx/SConscript
bsp/stm32/libraries/templates/stm32f7xx/SConscript
bsp/stm32/libraries/templates/stm32l4xx/SConscript
bsp/stm32/stm32f091-st-nucleo/SConscript
bsp/stm32/stm32f103-atk-nano/SConscript
bsp/stm32/stm32f103-dofly-lyc8/SConscript
bsp/stm32/stm32f103-fire-arbitrary/SConscript
bsp/stm32/stm32f103-hw100k-ibox/SConscript
bsp/stm32/stm32f107-uc-eval/SConscript
bsp/stm32/stm32f407-atk-explorer/SConscript
bsp/stm32/stm32f407-st-discovery/SConscript
bsp/stm32/stm32f411-st-nucleo/SConscript
bsp/stm32/stm32f429-armfly-v6/SConscript
bsp/stm32/stm32f429-atk-apollo/SConscript
bsp/stm32/stm32f429-fire-challenger/SConscript
bsp/stm32/stm32f446-st-nucleo/SConscript
bsp/stm32/stm32f746-st-disco/SConscript
bsp/stm32/stm32f767-atk-apollo/SConscript
bsp/stm32/stm32f767-fire-challenger/SConscript
bsp/stm32/stm32f767-st-nucleo/SConscript
bsp/stm32/stm32g071-st-nucleo/SConscript
bsp/stm32/stm32l053-st-nucleo/SConscript
bsp/stm32/stm32l432-st-nucleo/SConscript
bsp/stm32/stm32l475-atk-pandora/SConscript

[bsp/stm32]change str(Dir('#')) to GetCurrentDir()

---

components/utilities/Kconfig
components/utilities/utest/utest.c

1. 增加线程模式
之前 utest 运行测试用例是使用的 shell 线程的上下文，但是，这样导致无法测试 shell 本身，因此增加线程模式，使得 utest 运行在独立的线程环境中。
2. 增加 loop 功能
便于持续对单一一个测试用例进行测试。
3. 增加通配符指定测试用例功能
增加使用 `*` 号通配符指定测试用例名字；支持仅指定测试用例前部分名字运行测试用例。
4. 增加 utest_help 命令，用于输出帮助信息
5. 对于不支持的 testcase，增加输出日志

[components][utest] 增加线程模式、loop功能、通配符指定名字

---

.travis.yml
bsp/stm32/README.md

[ci]add new bsp

---

bsp/stm32/docs/STM32系列驱动介绍.md

[bsp][stm32] 为文档添加引导索引

---

bsp/stm32/libraries/HAL_Drivers/drv_gpio.c

[BSP][STM32]增加GPIO驱动对GPIOK时钟初始化

---

bsp/stm32/libraries/STM32F7xx_HAL/SConscript

在给stm32f746增加lcd驱动时发现，官方 ltdc 驱动并没有被增加进工程中。
本次修改脚本为了在选中lcd驱动时，itdc 驱动增加进工程中。

增加 LTDC 官方驱动条件加入工程

---

components/drivers/spi/spi_flash_sfud.c
components/drivers/spi/spi_flash_sfud.h

增加 rt_sfud_flash_find_by_dev_name 函数，方便上层通过 Flash 名查找 SFUD 设备

[DeviceDriver] Add rt_sfud_flash_find_by_dev_name function to SFUD 

---

components/drivers/wlan/wlan_mgnt.c

[
WLAN 管理层注册回调处，入口上锁写错了，已经更正
已经测试通过
]

[components][drivers][wlan] 修复一处加锁错误

---

include/libc/libc_errno.h

修复libc_errno.h的bug

---

bsp/stm32/libraries/HAL_Drivers/drv_common.c

[bsp][stm32] add rt_hw_us_delay
从 soft_i2c 的驱动中拷贝出来的，在F411开发板验证通过。

[bsp][stm32] add rt_hw_us_delay

---

.travis.yml

[ci] update Travis yml to support auto test

---

bsp/qemu-vexpress-a9/Makefile
tools/rtthread.mk

now makefile works

---

.travis.yml

[ci] 调整 ci 中 auto test 使用的项目仓库

[ci] 调整 ci 中 auto test 使用的项目仓库

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

更新pwm驱动
在 F411-NUCLEO 开发板上验证通过

[bsp][stm32]更新pwm驱动

---

components/drivers/sensors/sensor.c
components/drivers/sensors/sensor.h
components/drivers/sensors/sensor_cmd.c

添加 irq_handle 由驱动注册，作用是当产生接收中断时，框架调用这个函数供驱动处理中断。
为距离传感器添加毫米的单位定义 RT_SENSOR_UNIT_MM。
修复sensor_cmd中的一个小问题。
已在 F411-NUCLEO 开发板验证

完善 sensor 框架

---

.travis.yml

[ci] 使用环境变量配置 ci 中 auto test 使用的项目仓库

[ci] 使用环境变量配置 ci 中 auto test 使用的项目仓库

---

components/utilities/ulog/ulog.c
include/rtdbg.h
include/rtthread.h
src/kservice.c

- 更新 rtdbg.h ，避免 RT_DEBUG 关闭，导致 ulog 常规生产日志无法输出。
- 修正线程名可能输出不正常的问题

Update the ulog

---

.travis.yml

[ci] rm auto test stage

---

components/drivers/Kconfig

[components] 添加 RT_USING_ALARM 选项

---

bsp/imxrt/Libraries/imxrt1050/drivers/drv_eth.c
bsp/stm32/libraries/HAL_Drivers/drv_eth.c
components/net/Kconfig
components/net/lwip-1.4.1/src/lwipopts.h
components/net/lwip-2.0.2/src/lwipopts.h
components/net/lwip-2.1.0/src/lwipopts.h

[
添加 LWIP 的硬件校验和选项，修改了 stm32 系列驱动和 rt1052 的驱动。
在 stm32f429、stm32f407 和 rt1052 上测试通过，stm32 上开启硬件校验和后，iperf 测试速度提升明显，1052 不开硬件校验和就快跑满 100M 了，开启硬件校验和后，iperf 测试速度提升不太明显。
]

[components][lwip]添加 LWIP 硬件校验和选项，修改 STM32 系列和 rt1052 系列以太网驱动，支持硬件校验和

---

components/utilities/utest/utest.c

[components/utilities/utest] 增加测试运行测试打印

[components/utilities/utest] 增加测试运行测试打印

---

src/slab.c

fix slab at 64bits CPU

---

bsp/qemu-vexpress-a9/cpu/stack.c

修正当在sprintf函数中打印double类型的问题（原因是栈非8字节对齐）

fix the problem of double in sprintf

---

bsp/stm32/stm32f405-smdz-breadfruit/applications/main.c
bsp/stm32/stm32f405-smdz-breadfruit/rtconfig.h
bsp/stm32/stm32f405-smdz-breadfruit/template.uvprojx

[
1.修改mdk5模版,自动生成工程测试通过,代码编译运行测试通过
2.增加板载LED灯驱动程序
]

[bsp][stm32]添加板载LED灯示例程序

---

bsp/es32f0334/.config
bsp/es32f0334/README.md
bsp/es32f0334/drivers/Kconfig
bsp/es32f0334/drivers/SConscript
bsp/es32f0334/drivers/drv_hwtimer.c
bsp/es32f0334/drivers/drv_hwtimer.h
bsp/es32f0334/rtconfig.h

[ [bsp/es32f0334] add hwtimer driver ]

[bsp/es32f0334] add hwtimer driver

---

bsp/stm32/libraries/templates/stm32f0xx/SConstruct
bsp/stm32/libraries/templates/stm32f0xx/board/linker_scripts/link.lds
bsp/stm32/libraries/templates/stm32f0xx/rtconfig.py
bsp/stm32/libraries/templates/stm32f10x/SConstruct
bsp/stm32/libraries/templates/stm32f10x/board/linker_scripts/link.lds
bsp/stm32/libraries/templates/stm32f10x/rtconfig.py
bsp/stm32/libraries/templates/stm32f4xx/SConstruct
bsp/stm32/libraries/templates/stm32f4xx/board/linker_scripts/link.lds
bsp/stm32/libraries/templates/stm32f4xx/rtconfig.py
bsp/stm32/libraries/templates/stm32f7xx/SConstruct
bsp/stm32/libraries/templates/stm32f7xx/board/linker_scripts/link.lds
bsp/stm32/libraries/templates/stm32f7xx/rtconfig.py
bsp/stm32/libraries/templates/stm32l4xx/SConstruct
bsp/stm32/libraries/templates/stm32l4xx/board/linker_scripts/link.lds
bsp/stm32/libraries/templates/stm32l4xx/rtconfig.py

this time add C++ for templates
[last push forget modified the templates to support C++ this time add C++ for templates]

last push forget modified the templates to support C++

---

tools/building.py
tools/eclipse.py
tools/makefile.py
tools/rtthread.mk

在scons工具中添加Makefile及Eclipse工程更新的功能；都基于QEMU-VExpress-A9进行测试

[Tools] Add Makefile generation and Eclipse target

---

bsp/stm32/libraries/HAL_Drivers/drv_common.c

[bsp][stm32][libraries][HAL_Drivers] Update drv_common.c

---

libcpu/SConscript
libcpu/arc/SConscript
libcpu/arm/SConscript
libcpu/avr32/SConscript
libcpu/blackfin/SConscript
libcpu/c-sky/SConscript
libcpu/m16c/SConscript
libcpu/mips/SConscript
libcpu/nios/SConscript
libcpu/ppc/SConscript
libcpu/risc-v/SConscript
libcpu/sim/SConscript
libcpu/ti-dsp/SConscript
libcpu/unicore32/SConscript
libcpu/v850/SConscript
libcpu/xilinx/SConscript

修正libcpu中scons编译目录的 :bug ，相关目标文件都放置于build/kernel/libcpu中。

[libcpu] Fix the build directory issue

---

bsp/stm32/stm32l475-atk-pandora/board/ports/fal_cfg.h

[
修改 fal_cfg.h 来支持外置 FLASH
已在 IOT Board 测试通过
]

[BSP]Modify the fal_cfg.h to support spi flash

---

src/clock.c

[src/clock.c] avoid warning

---

components/libc/compilers/armlibc/sys/types.h
components/libc/compilers/dlib/sys/types.h
components/libc/compilers/minilibc/sys/types.h

[libc]fix size_t ssize_t

---

bsp/k210/driver/board.c
bsp/k210/driver/drv_io_config.c
bsp/k210/link.lds
libcpu/risc-v/k210/interrupt.c

[
- 修复栈帧错位
- 添加IO配置查询指令
- 添加reboot复位指令
- 添加utest支持
]

K210 enchance

---

libcpu/arm/cortex-a/start_gcc.S

[
禁止数据对齐检查，防止编译器优化导致的内存访问异常。
已在v3s上测试通过。
]

Disable the data alignment check.

---

src/Kconfig

[ [src][Kconfig]open soft_timer by default ]

[src][Kconfig]open soft_timer by default

---

components/drivers/Kconfig
components/drivers/include/ipc/workqueue.h
components/drivers/src/workqueue.c

…ayed work.
1.  增加系统默认工作队列，优先级、栈大小均可配置，默认该功能关闭
2.  增加delayed_work及实现
3.  增加rt_work_submit接口，替代rt_do_work功能   

[components][drivers][workqueue] add system default workqueue and delayed work.

---

src/object.c

[WIP][Kernel] Add object re-initialization check.

---

components/finsh/shell.c

移除shell中 `finsh get char error` 的错误打印避免切换stdio流时显示该打印。

[components][finsh][shell]remove finsh get char error print

---

bsp/es32f0654/.config
bsp/es32f0654/README.md
bsp/es32f0654/drivers/Kconfig
bsp/es32f0654/drivers/SConscript
bsp/es32f0654/drivers/drv_pm.c
bsp/es32f0654/drivers/drv_pm.h
bsp/es32f0654/drivers/drv_rtc.c
bsp/es32f0654/drivers/drv_rtc.h
bsp/es32f0654/libraries/SConscript
bsp/es32f0654/rtconfig.h
bsp/es32f0654/rtconfig.py

[ [bsp/es32f0654] add rtc driver ]

[bsp/es32f0654] add rtc driver

---

components/cplusplus/Mail.h
components/cplusplus/Mutex.h
components/cplusplus/Queue.h
components/cplusplus/Thread.h
components/cplusplus/crt.cpp
components/cplusplus/crt.h
components/cplusplus/crt_init.c

[
格式化 cplusplus 组件代码，代码风格统一，更美观
]

[components][cplusplus] 格式化代码

---

src/Kconfig

Disable color log in default. Test on qemu-vexpress-a9 bsp.

[Kernel] Disable color log in default

---

bsp/es32f0654/.config
bsp/es32f0654/README.md
bsp/es32f0654/drivers/Kconfig
bsp/es32f0654/drivers/SConscript
bsp/es32f0654/drivers/drv_adc.c
bsp/es32f0654/drivers/drv_adc.h
bsp/es32f0654/rtconfig.h

[ [bsp/es32f0654] add adc driver ]

[bsp/es32f0654] add adc driver

---

bsp/stm32/libraries/HAL_Drivers/SConscript
bsp/stm32/libraries/HAL_Drivers/config/f4/qspi_config.h
bsp/stm32/libraries/HAL_Drivers/config/f4/usbd_fs_config.h
bsp/stm32/libraries/HAL_Drivers/drv_config.h
bsp/stm32/libraries/HAL_Drivers/drv_usbd_fs.c

对F4系列增加USB驱动支持和QSPI驱动支持，已在STM32F469-discovery验证OK

[BSP][STM32] 对F4系列增加USB驱动支持和QSPI驱动支持

---

components/dfs/src/dfs_file.c

[DFS] Update dfs file open log.

---

bsp/qemu-vexpress-a9/drivers/drv_sdio.c

Remove the error log in SD/MMC driver of QEMU VExpress A9 BSP.

[BSP] remove error log for SD/MMC driver in QEMU VExpress A9 BSP

---

bsp/es32f0334/.config
bsp/es32f0334/README.md
bsp/es32f0334/drivers/Kconfig
bsp/es32f0334/drivers/SConscript
bsp/es32f0334/drivers/drv_adc.c
bsp/es32f0334/drivers/drv_adc.h
bsp/es32f0334/drivers/drv_pm.c
bsp/es32f0334/drivers/drv_pm.h
bsp/es32f0334/rtconfig.h

[ [bsp/es32f0334] add pm/adc driver ]

[bsp/es32f0334] add pm/adc driver

---

bsp/stm32/libraries/HAL_Drivers/drv_qspi.c

[
在使用 QSPI 驱动时，发现输出的提示信息单词拼写错误。
已经在正点原子 F767 开发板上做过测试，提示正常。
]

[bsp][stm32] Modify error message

---

components/drivers/sensors/sensor.c
components/drivers/sensors/sensor.h
components/drivers/sensors/sensor_cmd.c

[
增加新的传感器类型和新的传感器厂商。
sensor type: force sensor
vendor type: MiraMEMS
在stm32l475-atk-pandora开发板测试。
]

Add new sensor type and vendor type.

---

components/net/lwip-1.4.1/src/core/dns.c
components/net/lwip-1.4.1/src/netif/ethernetif.c
components/net/lwip-2.0.2/src/core/dns.c
components/net/lwip-2.0.2/src/netif/ethernetif.c
components/net/lwip-2.1.0/src/core/dns.c
components/net/lwip-2.1.0/src/netif/ethernetif.c

[
修复 lwIP 协议栈中 netdev 相关设置 DNS 地址错误问题
已经在 qemu、IoT-Board 开发板等环境下测试通过
]

[net][lwip] fix lwip netdev DNS address setup error

---

bsp/stm32/libraries/STM32F4xx_HAL/SConscript

[
为了适配F469-DISCO的LCD驱动，增加使用“BSP_USING_LTDC”时所引用的库函数文件
]

【修改】增加使用“BSP_USING_LTDC”时所引用的库函数文件

---

components/net/lwip-1.4.1/src/netif/ethernetif.c
components/net/lwip-2.0.2/src/netif/ethernetif.c
components/net/lwip-2.1.0/src/netif/ethernetif.c
components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c

[
完善 netdev 组件中 DNS 服务器设置功能
已经在 QEMU、IoT-Board 开发板上验证测试
]

[net][netdev] Improve netdev DNS setting function

---

bsp/stm32/stm32f469-st-disco/board/Kconfig
bsp/stm32/stm32f469-st-disco/board/SConscript
bsp/stm32/stm32f469-st-disco/board/ports/touch/SConscript
bsp/stm32/stm32f469-st-disco/board/ports/touch/drv_touch.c
bsp/stm32/stm32f469-st-disco/board/ports/touch/drv_touch.h
bsp/stm32/stm32f469-st-disco/board/ports/touch/drv_touch_ft.c
bsp/stm32/stm32f469-st-disco/project.ewp
bsp/stm32/stm32f469-st-disco/project.uvoptx
bsp/stm32/stm32f469-st-disco/project.uvproj
bsp/stm32/stm32f469-st-disco/project.uvprojx

[
为stm32f469-st-disco增加touch驱动，已在stm32f469-st-disco上通过测试。
Add touch drivers to stm32f469-st-disco, and passed the test on stm32f469-st-disco.
]

[bsp][stm32][f469-disco]Add touch drivers

---

components/net/sal_socket/src/sal_socket.c

[
修复 sockfd 初始化错误问题。
已经在 QEMU 和 IoT-Board 开发板上测试。
]

[net][sal] fix sockfd initialize error problem

---

components/dfs/Kconfig

当使能ramfs时自动选中memheap。
在 F411-Nucleo上验证通过

[components/dfs/ramfs] Automatically select memheap when ramfs enabled.

---

tools/makefile.py

Fix the `scons --target=makefile -s` issue under Windows. Test under qemu-vexpress-a9 bsp on Windows.

[tools] Fix the makefile issue under Windows.

---

bsp/stm32/libraries/STM32F1xx_HAL/SConscript

[
修复使用sdio时的错误hal库引用。
Fixed error stm32f1xx_hal library reference when using sdio.
]

[bsp][stm32]Fixed error stm32f1xx_hal library reference when using sdio.

---

components/lwp/arch/arm/cortex-a/lwp_gcc.S
components/lwp/arch/arm/cortex-a9/lwp_gcc.S
libcpu/arm/cortex-a/start_gcc.S

arm-cortex-a体系的vector_swi修改为weak函数，在使用lwp时，vector_swi入口函数由lwp组件提供。

修改lwp支持中arm cortex-a的swi入口函数处理

---

components/net/lwip-1.4.1/src/apps/ping/ping.c
components/net/lwip-2.0.2/src/apps/ping/ping.c
components/net/lwip-2.1.0/src/apps/ping/ping.c
components/net/netdev/src/netdev.c
components/net/sal_socket/src/sal_socket.c

[
修复网卡设备 link_down 状态时，Socket 创建失败问题。
修复只开启 netdev 组件和 lwIP 组件时，ping 命令导出问题。
该修改已经在 STM32f767 开发板和 QEMU 环境下测试通过。
]

[net][netdev] Fix netdev link_down status, socket create failed issue

---

components/drivers/include/ipc/workqueue.h

[
工作队列有些成员没有初始化，在 Init 中执行了初始化操作
]

[components][drivers][ipc] 初始化工作对象所有成员

---

tools/keil.py

[
[bug fix]:scons创建mdk工程时，group组中有多个library的情况下，会重复创建同名group.修改Tools/keil.py中的函数MDK45Project，若group已经创建，则直接添加子节点。已在bsp\stm32\stm32f429-atk-apollo下测试。
]

修复scons创建mdk工程时，group组中有多个library的情况下，会重复创建同名group.

---

components/net/lwip-2.0.2/src/api/api_lib.c
components/net/lwip-2.1.0/src/api/api_lib.c

[
修复lwip2.0.2和lwip2.1.0版本，不使能LWIP的TCP功能时，编译出错问题。在stm32f429-apollo下测试。
]

[bug fix]不使能LWIP的TCP功能时，编译出错。

---

bsp/lpc1114/.config
bsp/lpc1114/Kconfig
bsp/lpc1114/SConscript
bsp/lpc1114/SConstruct
bsp/lpc1114/applications/SConscript
bsp/lpc1114/applications/main.c
bsp/lpc1114/driver/SConscript
bsp/lpc1114/driver/board.c
bsp/lpc1114/driver/board.h
bsp/lpc1114/driver/drv_uart.c
bsp/lpc1114/driver/drv_uart.h
bsp/lpc1114/driver/startup_gcc.s
bsp/lpc1114/link.lds
bsp/lpc1114/rtconfig.h
bsp/lpc1114/rtconfig.py

Here is LPC1114 support. Tested with Z111xP board by http://www.the0.net/
To build, use arm-none-eabi-gcc(5.4.1 20160919) with Debian9.9.

add LPC1114 support

---

bsp/es32f0334/drivers/board.h
bsp/es32f0654/drivers/board.h
bsp/gd32e230k-start/drivers/board.h
bsp/mm32l07x/drivers/board.h
bsp/nuvoton_m451/applications/startup.c
bsp/samd21/applications/startup.c
bsp/stm32/libraries/templates/stm32f0xx/board/board.h
bsp/stm32/libraries/templates/stm32f10x/board/board.h
bsp/stm32/libraries/templates/stm32l4xx/board/board.h
bsp/stm32/stm32f091-st-nucleo/board/board.h
bsp/stm32/stm32f103-atk-nano/board/board.h
bsp/stm32/stm32f103-atk-warshipv3/board/board.h
bsp/stm32/stm32f103-dofly-M3S/board/board.h
bsp/stm32/stm32f103-dofly-lyc8/board/board.h
bsp/stm32/stm32f103-fire-arbitrary/board/board.h
bsp/stm32/stm32f103-hw100k-ibox/board/board.h
bsp/stm32/stm32f103-mini-system/board/board.h
bsp/stm32/stm32f107-uc-eval/board/board.h
bsp/stm32/stm32f407-atk-explorer/board/board.h
bsp/stm32/stm32g071-st-nucleo/board/board.h
bsp/stm32/stm32l053-st-nucleo/board/board.h
bsp/stm32/stm32l496-ali-developer/board/board.h
bsp/swm320-lq100/drivers/board.h

[
[bsp]support AC6 for some bsp and stm32 bsp templates.
]

 [bsp]support AC6 for some bsp and stm32 bsp templates.

---

components/net/sal_socket/include/sal_socket.h

[
- 添加多播流量处理相关的选项定义
- 添加 IPPROTO_IP 相关的选项定义
- 已在 IoT-Board 开发板和 QEMU 下测试通过
]

[net][sal] Add options and types for UDP multicast traffic handling

---

bsp/ls1cdev/drivers/drv_wdt.c
bsp/ls1cdev/drivers/drv_wdt.h
bsp/ls1cdev/libraries/ls1c_wdog.c
bsp/ls1cdev/libraries/ls1c_wdog.h

[
1. 添加了看门狗库函数。
2. 添加了看门狗的RTT驱动。
]

[bsp][ls1c] Add watchdog library function and driver .

---

components/net/sal_socket/dfs_net/dfs_net.c

[
- 完善 ioctrl 接口对 socketfd 操作支持
- 已在 STM32F429 开发板和 QEMU 下测试通过
]

[net][sal] Improve ioctl interface to support socketfd operations

---

components/drivers/sensors/sensor.h
components/drivers/sensors/sensor_cmd.c

[sensor] 完善sensor框架
* 修复开启 RTC 编译报错的问题。
* 在显示 sensor 数据时添加单位。
已在 iotboard 上进行了验证。

[sensor] 完善sensor框架

---

bsp/stm32/stm32l475-atk-pandora/board/Kconfig
bsp/stm32/stm32l475-atk-pandora/board/SConscript
bsp/stm32/stm32l475-atk-pandora/board/ports/drv_qspi_flash.c
bsp/stm32/stm32l475-atk-pandora/board/ports/sensor_port.c

[bsp][stm32][pandora] 添加 icm20608 及 flash 文件系统支持.
已在 iotborad 上进行了验证。

[bsp][stm32][pandora] 添加 icm20608 及 flash 文件系统支持.

---

bsp/stm32/libraries/HAL_Drivers/SConscript

[bsp][stm32]去除 drv_eth.c 和 lwip 的依赖关系。
已在正点原子F407上验证通过。

[bsp][stm32]去除 drv_eth.c 和 lwip 的依赖关系。

---

bsp/k210/rtconfig.py

[BSP][K210]fix build error with new sdk

---

bsp/stm32/stm32l475-atk-pandora/board/Kconfig
bsp/stm32/stm32l475-atk-pandora/board/SConscript
bsp/stm32/stm32l475-atk-pandora/board/ports/sensor_port.c

[
[bsp][stm32/stm32l475-atk-pandora]添加 sensor 框架下 aht10 的支持
在潘多拉开发板上测试通过
]

[bsp][stm32/stm32l475-atk-pandora]添加 sensor 框架下 aht10 的支持

---

tools/utils.py

[
[tools] 修复 GCC 版本判断的方式并增加异常捕获。修复前，对版本不完全的 split 会导致版本比较时，列表第三个元素进行 int 转化产生 ValueError 异常。
在 Windows 和 Linux 下测试通过。
]

[tools] 修复 GCC 版本判断的方式并增加异常捕获

---

bsp/qemu-vexpress-a9/drivers/drv_sdio.c
bsp/qemu-vexpress-a9/drivers/secondary_cpu.c
components/drivers/sdio/sd.c
libcpu/arm/cortex-a/interrupt.h

[BSP][qemu-vexpress-a9] code cleaup for compiling warning.

---

components/libc/pthreads/pthread.c
components/libc/pthreads/pthread.h
components/libc/pthreads/pthread_attr.c

更改pthreads的一些定义，使得他们更类似newlib/glibc中的定义。已经在qemu-vexpress-a9上进行验证。

[pthreads] The fields definition are more like those of newlib/glibc.

---

bsp/qemu-vexpress-a9/.gitignore
bsp/qemu-vexpress-a9/drivers/automac.h
bsp/qemu-vexpress-a9/drivers/drv_smc911x.c
bsp/qemu-vexpress-a9/rtconfig.py

[
根据主机的mac地址自动生成qemu的mac地址，并添加Clean和dist ignore
]

[BSP][qemu-a9] auto generate mac address from host

---

components/libc/Kconfig
components/libc/pthreads/pthread.c
components/libc/pthreads/pthread.h
components/libc/pthreads/pthread_cond.c
components/libc/pthreads/pthread_internal.h
components/libc/pthreads/pthread_tls.c
include/rthw.h

1. 调整pthreads的管理方式为数组方式管理，而不是把pthread_t直接与rt_thread_t关联起来；这样整体的容错性可以更好些。在qemu-vexpress-a9上验证通过。
2. 调整单核时spinlock的代码，使得在单核下时，类似开关中断的方式；

[pthreads] Change the pthreads management.

---

tools/menuconfig.py

[
解决.config中如果存在多个等号
CONFIG_PKG_SYSVIEW_SYSDESC0="I#15=SysTick"
在生成的rtconfig.h中被截断成:
CONFIG_PKG_SYSVIEW_SYSDESC0="I#15
的问题
解决方法:如果存在多个等号,用正则表达式提取第一个等号后面所有内容
]

fix menuconfig.py

---

components/net/freemodbus/port/portserial.c
components/net/freemodbus/port/portserial_m.c

[
更新 xMBPortSerialInit() 与 xMBMasterPortSerialInit() 函数
查找设备相关代码
已经在 F405 测试通过
]

[components][freemodbus] update function : xMBPortSerialInit(); xMBMasterPortSerialInit

---

bsp/allwinner_tina/libcpu/interrupt.c
bsp/at91sam9g45/drivers/board.c
bsp/at91sam9g45/link_scripts/at91sam9g45_ram.ld
bsp/at91sam9g45/platform/interrupt.c
bsp/at91sam9g45/rtconfig.py
libcpu/arm/arm926/trap.c

[
1.libcpu/arm/arm926/start_gcc.S的修改导致芯片at91sam9g45的编译无法通过，根据当前start_gcc.S修改相关输入段名称
2.修改rt_interrupt_dispatch函数，增加参数，区别FIQ及IRQ类型（at91sam9g45下无法通过寄存器区分）
3.[bss][at91sam9g45]下按照libcpu/arm/arm926/trap.c的要求增加相应的rt_interrupt_dispatch函数
]

[bsp][at91sam9g45] at91sam9g45芯片编译问题修改

---

bsp/stm32/libraries/HAL_Drivers/drv_eth.c

[
检测 PHY 设备时，应当进行多次尝试检测，然后再确定是否报错，而不是只检测一次就报错终止测试程序。
已经在正点原子 f767 开发板上经过测试。
]

[bsp][stm32][driver] fix phy detection driver

---

components/libc/compilers/armlibc/time.c
components/libc/compilers/dlib/time.c
components/libc/compilers/minilibc/time.c
components/libc/compilers/newlib/time.c

[
由于 `gettimeofday()` 函数依赖 rtc 设备才能实现，因此如果无法获取 rtc 设备则该函数无效，此时如果直接返回 0 会产生很大疑惑，应当断言提醒。
已经在 atk-apollo-f767 上测试。
]

[components][libc] Modify the gettimeofday() function

---

components/utilities/ulog/ulog.c

[components][ulog] Make the asynchronous log output more timely.

---

src/Kconfig

Update the version number to 4.0.2

Update the version number to 4.0.2

---

bsp/stm32/libraries/HAL_Drivers/drv_usart.c

[
增加uart的dma半中断接收方式，用来解决连续一次性接收大于dma缓存的数据而不会丢失数据。
]

[bsp][stm32] 增加uart的dma半中断接收方式。

---

bsp/stm32/stm32l432-st-nucleo/board/linker_scripts/link.icf

[
修改 STM32L432KC ROM 为 256K 
]

[bsp][stm32l432-st-nucleo]  fix link.icf rom size

---

bsp/stm32/stm32f746-st-disco/SConstruct

[
发现论坛有人说 stm32f746 BSP 的 dist 功能无法使用，后来发现是其提价 BSP 时使用了旧的 sconstruct 文件，因此更新该文件。
已经在 stm32f746 BSP 测试了 dist 功能。
]

[bsp][stm32] Fixed dist function of stm32f746 BSP

---

bsp/lpc54608-LPCXpresso/drivers/drv_i2c.c

[
1、软件模拟I2C初始化GPIO后拉高引脚。
2、gpio_set_scl函数else分支需要做拉低引脚操作。
]

[bsp/lpc54608]write high to scl and sda pin after init

---

include/rtdef.h
src/components.c
src/scheduler.c
src/signal.c

合并signal的改动到v3.1.3分支，在QEMU中测试通过；

prepare v3.1.3 release

---

bsp/stm32/libraries/HAL_Drivers/config/f0/uart_config.h
bsp/stm32/libraries/HAL_Drivers/config/f1/uart_config.h
bsp/stm32/libraries/HAL_Drivers/config/f7/uart_config.h
bsp/stm32/libraries/HAL_Drivers/config/g0/uart_config.h
bsp/stm32/libraries/HAL_Drivers/config/h7/uart_config.h
bsp/stm32/libraries/HAL_Drivers/config/l0/uart_config.h
bsp/stm32/libraries/HAL_Drivers/config/l4/uart_config.h

[
由于添加了串口 DMA 的发送，修改了相关的配置项，因此要对串口 DMA 接收的配置项进行一定的修改。
正在进行测试。
]

[bsp][stm32] 由于添加串口 DMA 发送对串口 DMA 接收配置造成的影响

---

bsp/stm32/libraries/HAL_Drivers/SConscript
bsp/stm32/libraries/HAL_Drivers/drv_lcd_mipi.c
bsp/stm32/stm32f469-st-disco/board/Kconfig
bsp/stm32/stm32f469-st-disco/board/SConscript
bsp/stm32/stm32f469-st-disco/board/ports/drv_otm8009a.c
bsp/stm32/stm32f469-st-disco/board/ports/lcd_port.h

[
分离MIPI-LTDC和LCD配置
Separation of MIPI-LTCDC and LCD Configuration
]

[bsp][stm32][f469-disco]Separation of MIPI-LTCDC and LCD Configuration

---

components/drivers/Kconfig
components/drivers/hwcrypto/SConscript
components/drivers/hwcrypto/hw_bignum.c
components/drivers/hwcrypto/hw_bignum.h
components/drivers/hwcrypto/hw_crc.c
components/drivers/hwcrypto/hw_crc.h
components/drivers/hwcrypto/hw_gcm.c
components/drivers/hwcrypto/hw_gcm.h
components/drivers/hwcrypto/hw_hash.c
components/drivers/hwcrypto/hw_hash.h
components/drivers/hwcrypto/hw_rng.c
components/drivers/hwcrypto/hw_rng.h
components/drivers/hwcrypto/hw_symmetric.c
components/drivers/hwcrypto/hw_symmetric.h
components/drivers/hwcrypto/hwcrypto.c
components/drivers/hwcrypto/hwcrypto.h
components/drivers/include/drivers/crypto.h
components/drivers/include/rtdevice.h

[
添加硬件加解密驱动，已经在w60x sdk 平台上做了部分验证。
]

[components][drivers] add hardware crypto device

---

components/net/sal_socket/src/sal_socket.c

[
- 完善 sal_bind() 函数功能，添加对不同协议簇判断和处理；
- 已在 stm32f429 开发板上验证问题；
]

[net][sal] Improve the sal_bind() function

---

components/net/lwip-1.4.1/src/netif/ethernetif.c
components/net/lwip-2.0.2/src/netif/ethernetif.c
components/net/lwip-2.1.0/src/netif/ethernetif.c

[
解决netdev注册后，ifconfig无法正确显示网卡IP地址，网关，掩码的bug。
已在stm32f407-atk-explorer开发板测试。
]

[bugfix][net][netdev] Update netdev->ip_addr&gw&netmask after registered.

---

libcpu/arm/cortex-a/context_gcc.S
libcpu/arm/cortex-a/stack.c
libcpu/arm/cortex-a/start_gcc.S
libcpu/arm/cortex-a/trap.c

add cortex-a fpu support

---

components/drivers/sensors/sensor.c

在添加力传感器时，添加的设备名称前缀代码有问题，会造成计步器名称显示有问题。修复这个问题。
已在 ali-developer 开发板上做了验证。

[sensor] fixed step name display abnormal.

---

src/object.c

[kernel] skip warning when disable debug.

---

components/drivers/pm/pm.c

[
- PM组件内部添加对 ops 选项的支持
- 已在 QEMU 上进行测试
]

[components][pm]add pm ops support

---

bsp/stm32/libraries/HAL_Drivers/drv_eth.c

[
修复并完善 issue #2756 中提到的 PHY 状态检查时出现的问题。
已经在正点原子 f407 探索者开发板上做过测试。
]

[stm32][driver] Fix the problems of PHY status examination mentioned in issue #2756

---

include/rtdef.h
src/Kconfig

Update the version number to 3.1.4

---

components/drivers/include/drivers/i2c.h
components/drivers/touch/SConscript
components/drivers/touch/touch.c
components/drivers/touch/touch.h
components/finsh/cmd.c
include/rtdef.h

1、components\drivers 中新增 touch 框架
2、新增设备类型 RT_Device_Class_Touch 和 "Touch Device"
3、新增 I2C 从设备控制块

add touch framework

---

components/dfs/filesystems/uffs/dfs_uffs.c

- 修复了一些 uffs 文件系统的BUG. 
- 已在 lpc4088 开发板上做了验证。

[dfs] fix some bug for uffs filesystem.|修复了一些uffs文件系统的BUG.

---

tools/building.py
tools/mkdist.py

[
为新的 IDE 添加 scons --dist-ide 功能。
已经在 bsp stm32f103-dofly-M3S 做过测试。
]

[tools] add scons --dist-ide function

---

components/drivers/Kconfig

add touch index in Kconfig file

add touch index in Kconfig file

---

bsp/stm32/libraries/HAL_Drivers/drv_sdio.h
bsp/stm32/stm32f407-atk-explorer/board/Kconfig
bsp/stm32/stm32f469-st-disco/board/Kconfig

[
添加 SDIO_MAX_FREQ 选项，如果没有定义这个选项的值，默认这个值为 1000000
]

[bsp][stm32 ] 添加 SDIO_MAX_FREQ 选项

---

tools/building.py
tools/eclipse.py

完善 scons --target=eclipse 命令，支持自定义工程名及还原工程配置功能

Fix eclipse

---

bsp/stm32/libraries/HAL_Drivers/drv_gpio.c

[bsp][stm32] fix drv_gpio.c 直接将特殊引脚删除，不再作为 pin 设备

---

libcpu/arm/cortex-a/cache.c

[
修复cortex-a 中cache操作没有 dsb isb 已在arm-a7上测试
]

修复cortex-a 中cache操作没有 dsb isb

---

components/dfs/filesystems/elmfat/dfs_elm.c
components/dfs/filesystems/elmfat/ff.c
components/dfs/src/dfs.c
components/dfs/src/dfs_file.c
components/dfs/src/dfs_posix.c
components/dfs/src/poll.c
components/drivers/audio/audio.c
components/drivers/audio/audio_pipe.c
components/drivers/i2c/i2c-bit-ops.c
components/drivers/i2c/i2c_dev.c
components/drivers/sensors/sensor.c
components/drivers/sensors/sensor_cmd.c
components/drivers/serial/serial.c
components/drivers/src/pipe.c
components/drivers/src/ringblk_buf.c
components/drivers/src/ringbuffer.c
components/drivers/usb/usbdevice/core/core.c
components/finsh/shell.c
src/ipc.c
src/kservice.c
src/thread.c

fix kernel and framework no cast type error  when use cpp11

fix kernel and framework no cast type error 

---

components/drivers/include/drivers/mtd_nand.h
components/drivers/mtd/mtd_nand.c

[
优化了 MTD_NAND 驱动框架
- 修复了 MTD_NAND 驱动框架当 ops 为空 hardfault 的问题。
- 添加调试命令到 MSH。
- 格式化代码。
已在 lpc4088 开发板上做了验证。
]

优化了 MTD_NAND 驱动框架

---

components/net/at/Kconfig
components/net/at/at_socket/at_socket.c
components/net/at/at_socket/at_socket.h
components/net/at/include/at.h
components/net/at/src/at_client.c
components/net/at/src/at_utils.c
components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c

[
更新 3.1系列 AT 组件和 netdev 组件，已经在stm32f407上测试通过
]

[component] Synchronize AT and netdev components

---

components/cplusplus/Thread.cpp
components/utilities/utest/utest.h
components/utilities/utest/utest_assert.h

[ fix cpp thread class error and add utest.h extern "C" ]

fix cpp thread class error

---

components/dfs/filesystems/nfs/SConscript
components/dfs/filesystems/nfs/dfs_nfs.c
components/dfs/filesystems/nfs/mount_xdr.c
components/dfs/filesystems/nfs/nfs_auth.c
components/dfs/filesystems/nfs/nfs_xdr.c

[
在 qemu 上测试过 Windows 环境及 Linux 环境。文件系统能正常读写。
]

[components][dfs][nfs] 修复连接 Linux NFS服务器认证错误的问题

---

bsp/imxrt/Libraries/MIMXRT1050/SConscript
bsp/imxrt/Libraries/drivers/SConscript
bsp/imxrt/Libraries/drivers/drv_can.c
bsp/imxrt/Libraries/drivers/drv_can.h
bsp/imxrt/imxrt1052-fire-pro/README.md
bsp/imxrt/imxrt1052-fire-pro/board/Kconfig
bsp/imxrt/imxrt1052-fire-pro/board/MCUX_Config/clock_config.c
bsp/imxrt/imxrt1052-fire-pro/board/MCUX_Config/pin_mux.c
bsp/imxrt/imxrt1052-fire-pro/rtconfig.h

[
1、imxrt 系列 BSP 增加 CAN 驱动。
2、在野火RT1052 EVK PRO开发板测试通过。
]

[bsp/imxrt]add can driver

---

bsp/stm32/libraries/HAL_Drivers/drv_can.c
bsp/stm32/libraries/HAL_Drivers/drv_can.h

[
[bsp][stm32][libraries][HAL_Drivers] update drv_can.c.
why : adapt to new HAL_lib.
test board : stm32f407-atk-explorer.
]

[bsp][stm32][libraries][HAL_Drivers] update drv_can.c

---

src/mempool.c

[
为 mempool 添加参数检查。已在潘多拉开发板上做了验证。
]

[src/mempool.c] add parameter check.|添加参数检查。

---

libcpu/arm/cortex-m3/cpuport.c
libcpu/arm/cortex-m4/cpuport.c
libcpu/arm/cortex-m7/cpuport.c

[
[libcpu/arm] add __rt_ffs() for armclang in CORTEX M3/4/7
解决了__rt_ffs()在AC6编译情况下由于语法差异造成的错误
潘多拉上测试通过
]

[libcpu/arm]add __rt_ffs() for armclang in CORTEX M3/4/7

---

bsp/es32f0334/drivers/drv_rtc.c
bsp/es32f0334/drivers/drv_spiflash.c
bsp/es32f0654/drivers/drv_rtc.c
bsp/es32f0654/drivers/drv_spiflash.c

[
[bsp][es32f0 334/654] 修改会在AC6下编译报错的函数
修改了以下导致的报错：
static void rtc_init(rtc_init_t *init)与库函数同名了。修改了函数名
static int rt_hw_spi_flash_init(void)在相应的头文件中被声明了。去除static修饰
]

[bsp][es32f0 334/654] 修改会在AC6下编译报错的函数

---

include/rtthread.h
src/ipc.c

[
完善 rt_mq_send 及 rt_mq_urgent 函数定义。
]

[src][ipc]完善 message queue 相关定义

---

src/irq.c

[
部分应用场景，不知道何时进出中断。但可以通过查询寄存器获取到。修改 rt_interrupt_get_nest 为 WEAK 形式，由外部提供，这样系统就知道当前上下文环境。
]

[src][irq] 添加 WEAK 修饰，中断嵌套数可由外部提供。

---

bsp/stm32/libraries/HAL_Drivers/drv_wdt.c

[bsp][stm32] update drv_wdt.c

---

src/idle.c

[src][idle] 修复一处编译警告

---

components/drivers/hwcrypto/hw_bignum.c
components/drivers/hwcrypto/hw_rng.c
components/drivers/hwcrypto/hwcrypto.c
components/drivers/hwcrypto/hwcrypto.h

[components][drivers][hwcrypto] 更正一处命名错误

---

components/drivers/Kconfig
components/drivers/wlan/SConscript
components/drivers/wlan/wlan_cfg.c
components/drivers/wlan/wlan_cmd.c
components/drivers/wlan/wlan_dev.c
components/drivers/wlan/wlan_dev.h
components/drivers/wlan/wlan_lwip.c
components/drivers/wlan/wlan_mgnt.c
components/drivers/wlan/wlan_mgnt.h
components/drivers/wlan/wlan_prot.c
components/drivers/wlan/wlan_prot.h
components/drivers/wlan/wlan_workqueue.c

[
- WLAN 连接信息保存功能可裁剪
- WIFI MSH 命令功能可裁剪
- WLAN 管理功能可裁剪
- WLAN 自动连接功能可裁剪
- WLAN 自动连接时使用最新热点信息
- WLAN 用户事件回调由独立线程调用
- WLAN 独立线程可裁剪
- WLAN 协议管理功能可裁剪
- LWIP 协议层可裁剪
- SCAN 结果支持过滤
- WIFI 阻塞式连接支持多次扫描
- WLAN 新增网卡对象指针
- WLAN 获取信息时更新信号强度
- 其他优化性质改动
已在 RTK / STM32L4 / W60X 平台上进行验证。
]

[components][drivers][wlan] 功能可裁剪

---

components/drivers/sensors/sensor.h
components/drivers/sensors/sensor_cmd.c

[
Increase the output of sensor information
增加在sensor info命令下的传感器信息输出
]

[component][drivers][sensors]Increase the output of sensor information

---

bsp/x1000/drivers/mmc/drv_mmc.c

[
X1000: drv_mmc.c: 修复DMA中的问题/Fix bug in DMA.
]

X1000: drv_mmc.c: 修复DMA中的问题/Fix bug in DMA.

---

components/drivers/sdio/mmc.c

[
sdio: mmc.c: 防止容量计算过程溢出/Prevent capacity calculation overflow.
]

sdio: mmc.c: 防止容量计算过程溢出/Prevent capacity calculation overflow.

---

bsp/pic32ethernet/project.cbp
libcpu/mips/common/mips.h
libcpu/mips/common/mips_def.h
libcpu/mips/loongson_1b/cache_gcc.S
libcpu/mips/loongson_1b/context_gcc.S
libcpu/mips/loongson_1b/start_gcc.S
libcpu/mips/loongson_1c/cache_gcc.S
libcpu/mips/loongson_1c/context_gcc.S
libcpu/mips/loongson_1c/start_gcc.S
libcpu/mips/pic32/context_gcc.S
libcpu/mips/x1000/mips_cache_gcc.S
libcpu/mips/x1000/mips_context_gcc.S
libcpu/mips/x1000/mips_excpt_gcc.S
libcpu/mips/x1000/mips_fp_gcc.S
libcpu/mips/x1000/startup_gcc.S
libcpu/mips/xburst/cache_gcc.S
libcpu/mips/xburst/context_gcc.S
libcpu/mips/xburst/start_gcc.S

[
libcpu: MIPS: 清理代码并更新版权信息/Clean up code and update copyright information.
]

libcpu: MIPS: 清理代码并更新版权信息/Clean up code and update copyright information.

---

bsp/x1000/drivers/board_io.c

[
X1000: board_io.c: 根据配置进行复位/Reset according to configuration.
]

X1000: board_io.c: 根据配置进行复位/Reset according to configuration.

---

bsp/x1000/x1000_ram.lds

[
X1000: x1000_ram.lds: 修复调试时崩溃的问题/Fix crash when debugging.
]

X1000: x1000_ram.lds: 修复调试时崩溃的问题/Fix crash when debugging.

---

bsp/stm32/libraries/HAL_Drivers/drv_common.c

[
[bsp][stm32/drv_common.c]修复在关闭UART设备框架时，编译报错
在潘多拉上测试通过
]

[bsp][stm32/drv_common.c]修复在关闭UART设备框架时，编译报错

---

bsp/stm32/libraries/STM32F0xx_HAL/SConscript
bsp/stm32/libraries/STM32F1xx_HAL/SConscript
bsp/stm32/libraries/STM32F2xx_HAL/SConscript
bsp/stm32/libraries/STM32F4xx_HAL/SConscript
bsp/stm32/libraries/STM32F7xx_HAL/SConscript
bsp/stm32/libraries/STM32G0xx_HAL/SConscript
bsp/stm32/libraries/STM32H7xx_HAL/SConscript
bsp/stm32/libraries/STM32L0xx_HAL/SConscript
bsp/stm32/libraries/STM32L4xx_HAL/SConscript

[bsp][stm32/libraries]修改各个系列下的sconscript文件，默认添加 stm32xxxx_hal_gpio.c
[
[bsp][stm32/libraries]修复在关闭GPIO device drivers时的报错：修改各个系列下的sconscript文件，默认添加库文件stm32xxxx_hal_gpio.c
原因：关闭RT_USING_PIN时，会关闭stm32xxxx_hal_gpio.c，但是此时还有一些文件使用了GPIO的初始化与反初始化函数而报错，如 hal_msp.c、hal_rcc.c 、hal_comp.c等等。
STM32各个BSP测试通过
]

[bsp][stm32/libraries]修复在关闭GPIO device drivers时的报错

---

components/drivers/Kconfig
components/drivers/wlan/wlan_dev.c
components/drivers/wlan/wlan_mgnt.c
components/drivers/wlan/wlan_mgnt.h

[
1. 可指定扫描的通道
2. 自动连接的检查周期可配置
已在 RTK 平台验证
]

[components][drivers][wlan] 自动连接周期可配置，可指定扫描通道

---

bsp/stm32/libraries/HAL_Drivers/drv_wdt.c

[update][bsp][stm32] drv_wdt.c

---

components/drivers/wlan/wlan_cmd.c
components/drivers/wlan/wlan_lwip.c
components/drivers/wlan/wlan_mgnt.c

[components][drivers][wlan] 修复自动连接 32 密码长度失败的问题，增强代码稳定性

---

components/libc/compilers/dlib/sys/errno.h
components/libc/compilers/dlib/sys/signal.h
components/libc/compilers/dlib/sys/unistd.h

添加IAR/dlib中缺少的类UNIX头文件，在stm32f411 bsp上验证通过。

[dlib] Add more header files for IAR/dlib

---

components/cplusplus/Thread.cpp
components/cplusplus/Thread.h
src/components.c

[
1、修改 Thread.cpp 文件和 Thread.h 文件的一些 bug
2、删除 component.c 文件在 GCC 编译器下多于的 extern int main(void);
]

fix bug in Thread.cpp/Thread.h/components.c files

---

components/net/netdev/src/netdev.c

[
修复 netdev 解除注册的一个问题，手误将 memcmp 写成了 memcpy
]

[components][net][netdev] 修复一处BUG

---

components/net/at/at_socket/at_socket.c

len值如果不给初始值0，到最后__exit的时候，result = len会导致result的值变成一个不可预估的值，进而导致mbedtls库的while循环无法正常结束，其中mebedtls中发生异常的地方在ssl_tls.c文件中的mbedtls_ssl_flush_output函数while( ssl->out_left > 0 )，因为out_left 是一个无符号整型，退出的条件只能是 out_left = 0,又因为这里面的len没有给初始值0，返回出来的值是一个很大的整型数字，导致了mbedtls中的死循环
[
And confirm in which case or board …

修改at_socket.c文件中的sendto函数，len局部变量没有给初始值

---

bsp/stm32/libraries/HAL_Drivers/config/f1/usbd_fs_config.h
bsp/stm32/libraries/HAL_Drivers/drv_config.h

[
添加了HAL库的f1的USB配置，保证f1能使用USB设备；添加了bsp/stm32/libraries/HAL_Drivers/config/f1/usbd_fs_config.h，修改了bsp/stm32/libraries/HAL_Drivers/drv_config.h
已在bsp/stm32/stm32f103-atk-nano进行编译，并在stm32f103c8t6/rct6/zet6上经过测试
]

添加f1的usbd驱动

---

bsp/stm32/libraries/templates/stm32f0xx/board/Kconfig
bsp/stm32/libraries/templates/stm32f10x/board/Kconfig
bsp/stm32/libraries/templates/stm32f2xx/board/Kconfig
bsp/stm32/libraries/templates/stm32f4xx/board/Kconfig
bsp/stm32/libraries/templates/stm32f7xx/board/Kconfig
bsp/stm32/libraries/templates/stm32h7xx/board/Kconfig
bsp/stm32/libraries/templates/stm32l4xx/board/Kconfig
bsp/stm32/libraries/templates/stm32xx_board_Kconfig

[
[bsp][stm32/templates]简化stm32模板下的Kconfig，增加Kconfig参考模板 stm32xx_board_kconfig
]

[bsp][stm32/templates]简化stm32模板下的Kconfig，增加Kconfig参考模板

---

components/utilities/ulog/ulog.c

[component/ulog] Fix ulog hexdump show issue.

---

tools/menuconfig.py

修正 pyconfig 在 Windows 上错误下载 env 问题

[tools] Fix pyconfig issue on windows.

---

bsp/stm32/stm32f103-dofly-M3S/.project
bsp/stm32/stm32f401-st-nucleo/.project
bsp/stm32/stm32f407-atk-explorer/.project
bsp/stm32/stm32f429-atk-apollo/.project
bsp/stm32/stm32f429-fire-challenger/.project
bsp/stm32/stm32f767-atk-apollo/.project
bsp/stm32/stm32l475-atk-pandora/.project

[bsp/stm32] Update the eclipse project.

---

tools/eclipse.py

基于eclipse的stm32cubeIDE，可以在eclipse脚本下修改少量代码即可对其进行支持。

add stm32cubeide support

---

bsp/imxrt/imxrt1052-atk-commander/SConstruct
bsp/imxrt/imxrt1052-atk-commander/rtconfig.py
bsp/imxrt/imxrt1052-fire-pro/SConstruct
bsp/imxrt/imxrt1052-fire-pro/rtconfig.py
bsp/imxrt/imxrt1052-nxp-evk/SConstruct
bsp/imxrt/imxrt1052-nxp-evk/rtconfig.py
bsp/imxrt/tools/sdk_dist.py

[
修正了dist命令对imxrt系列bsp包的支持，修改前的dist命令生成的工程缺少了Libraries。
本次修改在imxrt下的3个bsp支持包中测试通过。
]

修正了dist命令对imxrt系列bsp包的支持，修改前的dist命令生成的工程缺少了Libraries。

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

[bsp][stm32] fix `drv_pwm.c` device register usagefault.

[bsp][stm32] fix drv_pwm.c device register usagefault

---

bsp/swm320-lq100/drivers/drv_iwg.c

[
[bsp][swm320-lq100]统一看门狗名称：修改看门狗设备名称与stm32保持一致
]

[bsp][swm320-lq100]修改看门狗设备名称与stm32保持一致

---

components/net/lwip-2.0.2/src/include/netif/ethernetif.h
components/net/lwip-2.0.2/src/netif/ethernetif.c
components/net/lwip-2.1.0/src/include/netif/ethernetif.h
components/net/lwip-2.1.0/src/netif/ethernetif.c
components/net/lwip_dhcpd/dhcp_server.c
components/net/lwip_dhcpd/dhcp_server.h
components/net/lwip_dhcpd/dhcp_server_raw.c
components/net/netdev/src/netdev.c
components/net/sal_socket/src/sal_socket.c

[
网卡可卸载的功能主要是需要在应用中使用。
应用中会启动 AP 进行配网，AP 配网完成后，连接热点进行通信。当配网完成，AP 网卡不会在用到，并且 AP 网卡还会影响正常的网络通信。部分socket 会被创建到 AP 网卡上，导致通信失败。
因此网络这块支持了网卡卸载功能。1. 可回收内存等资源 2. 避免 scoket 创建到其他网卡上的情况。
网卡卸载功能在 qemu 上进行完整测试，在 RTK 平台上进行应用测试。使用测试时间为一周左右。
目前网卡卸载支持 2.0.2 及 2.1.0 版本，1.4.1 版本未做支持
]

[components][net] 1.网卡可卸载 2.dhcpd 服务可停止

---

bsp/w60x/drivers/linker_scripts/link.lds

[
W60X 软件包更新，GCC 链接脚本中缺少相应的段，现补上。
在板子上跑过，正常运行。
]

[bsp][w60x] update GCC linker scripts

---

components/drivers/wlan/wlan_dev.c
components/drivers/wlan/wlan_dev.h

[components][drivers][wlan] WLAN 支持被动扫描

---

components/drivers/Kconfig
components/drivers/include/drivers/encoder.h
components/drivers/include/rtdevice.h
components/drivers/misc/SConscript
components/drivers/misc/encoder.c

[
添加编码器驱动框架
已在原子 F407 验证过 AB 相编码器驱动的使用
]

[components][drivers] add encoder driven framework

---

bsp/stm32/libraries/HAL_Drivers/drv_can.c
bsp/stm32/libraries/HAL_Drivers/drv_can.h
bsp/stm32/libraries/STM32H7xx_HAL/SConscript
components/drivers/can/can.c
components/drivers/include/drivers/can.h
components/finsh/cmd.c

[
fix stm32 drv_can bug
test platform:
a.stm32f103-fire-arbitrary
b.stm32f429-atk-apollo
c.stm32f767-atk-apollo
]

[bsp] [stm32] fix drv_can.c

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

[
问题：之前很多小伙伴在做小车电机控制的时候，发现 stm32 的 PWM 配置好之后总是没有 PWM 输出，之后发现是时钟没有使能
修改：在 drv_pwm.c 里面根据配置使能相应的时钟。
测试：在 stm32f103RC stm32F407 测试通过
]

[stm32][driver] pwm enable clock

---

components/drivers/wlan/wlan_lwip.c

[
1.修复异步调用 dhcp 无法停止的bug 2.支持解挂载 lwip 协议
已经在 RTK 平台上进行测试验证
]

[components][drivers][wlan] 1.修复异步调用 dhcp 无法停止的bug 2.支持解挂载 lwip 协议

---

bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_l4.c
bsp/stm32/stm32l452-st-nucleo/board/Kconfig
bsp/stm32/stm32l452-st-nucleo/board/SConscript
bsp/stm32/stm32l452-st-nucleo/board/ports/fal_cfg.h

[
1.fix stm32 drv_flash_l4.c bug
2.add stm32l452 on chip flash Kconfig
]

[bsp] [stm32] fix drv_flash_l4.c bug

---

bsp/stm32/stm32f103-dofly-M3S/board/Kconfig
bsp/stm32/stm32f103-dofly-M3S/board/SConscript
bsp/stm32/stm32f103-dofly-M3S/board/ports/drv_sdcard.c

[
增加stm32f103-dofly-M3S开发板的SPI SD Card驱动代码，已在stm32f103-dofly-M3S上测试通过。
Add spi sdcard port code and pass the test in stm32f103-dofly-M3S.
]

[bsp][stm32][stm32f103-dofly-M3S]Add spi sdcard port code

---

components/drivers/misc/encoder.c

[components][drivers][encoder] update

---

components/net/netdev/src/netdev.c

[
- 完善 PING 命令错误日志显示
- 已在IoT-Board 开发板和 QEMU 环境下验证
]

[network][netdev] Improve the ping command error log prompt

---

tools/iar.py

[tools][fix] 修改 iar.py 中 iar 版本查找失败后的处理，目的是在出错后终止 scons 程序，以发现并修改错误；并在成功后打印 iar 版本，便于调试。

[tools][fix] 修改 iar.py 中 iar 版本查找失败后的处理

---

components/libc/compilers/common/time.c

[
修改__IAR_SYSTEMS_ICC__宏定义的作用范围，将gettimeofday放在宏定义之外
]

[components][libc][common]修改__IAR_SYSTEMS_ICC__宏定义的作用范围

---

components/net/sal_socket/src/sal_socket.c

[
多线程访问的情况下，创建 socket 时，有一定概率创建相同 fd。原因是分配 fd 的策略有点问题，并且关键地方没有得到保护。
1. 修改分配fd的策略，保证已经分配出去的fd不会在分配给其他人
2. 出现问题，及时回收fd，防止fd泄露
已经在 RTK 平台进行 7*24 小时测试。
]

[components][net][sal]修复多线程访问创建相同fd的问题

---

bsp/stm32/stm32f429-atk-apollo/applications/SConscript
bsp/stm32/stm32f429-atk-apollo/applications/mnt.c

[
port to dfs
verify plarform:stm32f429-atk-apollo
]

[bsp] [stm32] port to dfs

---

components/net/at/at_socket/at_socket.c

[
at_socket的socket成员释放和申请都是根据链表长度判断，多路socket时可能会出现socket重复。
我在插入链表之前先判断从0开始有没有被释放的socket空出来，然后把新的插入这里替代。
]

at_socket的socket成员可能重复问题

---

bsp/rv32m1_vega/README.md
bsp/rv32m1_vega/ri5cy/board/pin_mux.c
bsp/rv32m1_vega/ri5cy/driver/Kconfig
bsp/rv32m1_vega/ri5cy/driver/drv_uart.c

[
在做课程设计的过程中，要使用两个串口，原来只有UART0的驱动，我在原来代码的基础上添加了支持UART1的代码段；
已经在织女星开发板rv32m1_vega(lite版)上使用Micropython，并使用如下代码：
`from machine import UART `
`u1 = UART(1,9600)`
`u1.write('hello RT-Thread!')`
进行测试；
]

Add UART1 driver of rv32m1_vega

---

tools/gcc.py

[
Added header file detection codes to tools/gcc.py so that it can handle most manually unpacked toolchain. 
]

Hollylee patch gccroot

---

tools/building.py

[tools]armclang库文件编译支持

---

bsp/stm32/stm32l475-atk-pandora/board/board.h
bsp/stm32/stm32l475-atk-pandora/board/linker_scripts/link.icf
bsp/stm32/stm32l475-atk-pandora/board/linker_scripts/link.lds
bsp/stm32/stm32l475-atk-pandora/board/linker_scripts/link.sct

[bsp][stm32] fix : #define HEAP_BEGIN

---

bsp/stm32/libraries/HAL_Drivers/drv_gpio.c

Fix STM32L0 Series External Interrupt BUG

---

components/libc/compilers/armlibc/libc.h
components/libc/compilers/dlib/libc.h
components/libc/compilers/newlib/libc.h

[components/libc/compilers]c++文件引用libc.h支持

---

tools/building.py

[
修正外部环境变量未引入Env Path,导致自定义Builder的action参数使用python函数时,无法找到外部程序的问题.
自定义Builder的action参数使用python函数时,无法找到外部程序, 自定义builder类似如下:
def CreateSrcFile(target, source, env):
cmd = '''cd %s && python3 ... ''' % (os.path.dirname(str(source[0])), ...)          #...省略了部分代码
os.system(cmd)
...
builder = Builder(action = CreateSrcFile, source_ext_match = None)
Env.Append(BUILDERS = {'MyBuilder' : builder})
Env.MyBuilder(target = ..., source = [...])
...
] …

[tools]修正外部环境变量未引入Env Path,导致自定义Builder的action参数使用python函数时,无法找到外部程序的问题

---

bsp/imxrt/imxrt1052-nxp-evk/applications/main.c
bsp/imxrt/imxrt1052-nxp-evk/applications/mnt.c
bsp/imxrt/imxrt1052-nxp-evk/board/Kconfig
bsp/imxrt/imxrt1052-nxp-evk/board/SConscript
bsp/imxrt/imxrt1052-nxp-evk/board/board.c
bsp/imxrt/imxrt1052-nxp-evk/board/board.h
bsp/imxrt/imxrt1052-nxp-evk/board/ports/phyksz8081/fsl_phy.c
bsp/imxrt/imxrt1052-nxp-evk/board/ports/phyksz8081/fsl_phy.h
bsp/imxrt/imxrt1052-nxp-evk/board/ports/sdram_port.h
bsp/imxrt/libraries/drivers/SConscript
bsp/imxrt/libraries/drivers/drv_eth.c
bsp/imxrt/libraries/drivers/drv_sdram.c

[
The PR includes five commits, they are created based on the new imxrt BSP framework in RT-Thread,
and verified on IMXRT1050EVKB board.
- imxrt:uart: Add PINs init for each uart port
- imxrt:board: Add LPUART3 item for imxrt1052-nxp-evk
- imxrt:sdram: Add sdram support for imxrt1052-nxp-evk
- imxrt:app: Support ramfs for imxrt1052-nxp-evk
- imxrt:enet: Support imxrt ethernet interface
] …

imxrt: Update for imxrt UART, SDRAM, ENET, PHY modules

---

components/drivers/Kconfig
components/drivers/usb/usbdevice/SConscript
components/drivers/usb/usbdevice/class/audio.h
components/drivers/usb/usbdevice/class/audio_mic.c
components/drivers/usb/usbdevice/class/audio_speaker.c
components/drivers/usb/usbdevice/core/core.c

[
添加 USB Audio Class，添加了一个麦克风，一个扬声器。已在潘多拉开发板上做了验证。
]

添加 USB Audio Class

---

bsp/imxrt/libraries/drivers/drv_uart.c
bsp/stm32/libraries/HAL_Drivers/drv_usart.c

完善 stm32/imxrt bsp 串口驱动实现，移除对于 device user_data 的占用
- atk pandora
- nxp imxrt1050 
上测试通过

Fix serial

---

components/drivers/include/drivers/pm.h
components/drivers/pm/pm.c

修复 pm 组件中的数据类型问题，改用 rt-thread 定义的数据类型。在 bsp/stm32/stm32f407-atk-explorer 中验证。

[components/drivers][pm] fix data type problem

---

include/rtdef.h
include/rthw.h
include/rtthread.h
libcpu/arm/cortex-a/cpu.c
libcpu/risc-v/k210/cpuport_smp.c
src/Kconfig
src/SConscript
src/cpu.c
src/scheduler.c
src/thread.c

Add and cleanup spinlock API in SMP Kernel. Test it under QEMU VExpress A9.

Add spin lock API in Kernel

---

components/cplusplus/Queue.h

[components] [cplusplus] fix Queue.h mpool bug

---

bsp/stm32/libraries/HAL_Drivers/config/f1/pulse_encoder_config.h
bsp/stm32/libraries/HAL_Drivers/config/f4/pulse_encoder_config.h
bsp/stm32/libraries/HAL_Drivers/drv_pulse_encoder.c

[
1. 为编码器驱动添加中断支持。
2. 移除对 pulse_encoder->parent.user_data 的使用。
已经在 stm32f407-atk 板子上验证过。
]

[bsp][stm32][driver] drv_pulse_encoder.c

---

components/net/at/at_socket/at_socket.c

[
fix bug in function: int at_sendto(int socket, const void *data, size_t size, int flags, const struct sockaddr *to, socklen_t tolen)
return undined value when zhe socket is disconnect.
]

[fixbug] [lts-v3.1.x] [rt-thread] [components] [net] [at] [at_socket] at_socket.c

---

components/dfs/filesystems/elmfat/dfs_elm.c
components/dfs/include/dfs_file.h
components/dfs/include/dfs_posix.h
components/dfs/src/dfs_file.c
components/dfs/src/dfs_posix.c
components/libc/compilers/newlib/syscalls.c

[
* 添加为elmfat添加ftruncate接口实现
* 添加flock、getuid、umask接口，暂无实现
* 测试平台: qemu-vexpress-a9 
* 测试文件系统:elmfat
]

[components]添加ftruncate、flock、getuid、umask接口

---

components/libc/pthreads/pthread.c

[
一、问题描述：
pthread_create
--> stack = (void *)rt_malloc(ptd->attr.stacksize);
此时 stack 还未赋值到 ptd->tid->stack_addr，以下两个地方失败会导致 stack 不被释放
--> ptd->tid = (rt_thread_t) rt_malloc(sizeof(struct rt_thread));
--> ptd->joinable_sem = rt_sem_create(name, 0, RT_IPC_FLAG_FIFO);
并且由于 ptd->tid->stack_addr 未赋值
_pthread_data_destroy --> rt_free(ptd->tid->stack_addr); 也是非法操作
二、解决方案：
1、将 stack 分配紧挨 rt_thread_init，确保 ptd->tid->stack_addr 记录的就是 stack 地址；
2、free 的时候先判断 ptd->tid->stack_addr 是否非空，避免释放空指针。
三、验证结果：
在 samc21 开发板上验证OK：压力测试导致 pthread_create 异常，撤去压力之后，通过 free 查看内存消耗，确保和加压前内存消耗一致。
]
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted …

fix bug for pthread_create memory leak

---

bsp/k210/driver/board.c
bsp/k210/driver/drv_uart.c

[
更新了K210 bsp 对嘉楠SDK v0.5.6的支持 旧版本兼容情况已测试OK。
测试板卡 荔枝丹
]

[bsp][k210] update sdk support for v0.5.6

---

bsp/stm32/libraries/HAL_Drivers/drv_rtc.c

[
社区反馈，某些 stm32 系列（如 stm32f030 ） 是没有后备寄存器的，导致原有的 rtc 驱动中 “检查 rtc 时间是否配置过的代码逻辑” 存在编译不过的问题。
]

[update][bsp][stm32] drv_rtc.c

---

bsp/gd32vf103v-eval/board/board.c
bsp/gd32vf103v-eval/libraries/n22/env_Eclipse/init.c

[
test platform gd32vf103v-eval
]

[bsp] [gd32vf103] explicit call clock init

---

bsp/allwinner_tina/link.lds
bsp/beaglebone/beaglebone_ram.lds
bsp/imx6sx/cortex-a9/cpu/start_gcc.S
bsp/imx6sx/cortex-a9/imx6.lds
bsp/imx6ul/imx6.lds
bsp/lpc2478/lpc2478_ram.lds
bsp/qemu-vexpress-a9/link.lds
bsp/qemu-vexpress-gemini/cpu/start_gcc.S
bsp/qemu-vexpress-gemini/vexpress.lds
bsp/raspi2/cpu/start_gcc.S
bsp/realview-a8/realview.lds
libcpu/arm/am335x/start_gcc.S
libcpu/arm/cortex-a/start_gcc.S
libcpu/arm/cortex-r4/start_gcc.S
libcpu/arm/realview-a8-vmm/start_gcc.S
libcpu/arm/zynq7000/start_gcc.S

fixed linker script and stack align issues.

---

libcpu/arm/cortex-m7/cpu_cache.c

Signed-off-by: ZYH <lymz@foxmail.com>
[
修复m7 的cache编译警告
]

[libcpu][M7]修复cache编译警告

---

libcpu/arm/cortex-m33/SConscript
libcpu/arm/cortex-m33/context_gcc.S
libcpu/arm/cortex-m33/context_iar.S
libcpu/arm/cortex-m33/context_rvds.S
libcpu/arm/cortex-m33/cpuport.c
libcpu/arm/cortex-m33/syscall_gcc.S
libcpu/arm/cortex-m33/syscall_iar.S
libcpu/arm/cortex-m33/syscall_rvds.S
libcpu/arm/cortex-m33/trustzone.c

[
支持 CM33 架构，在 NXP55S69 上进行验证。目前不不支持 M33 的工程构建
]

[WIP][libcpu][cm33] support cortex-m33

---

tools/menuconfig.py

[
1. 更新 rt_config 更新函数，解决后缀为 _PATH，_VER 时生成 rt_config.h 错误的问题。
2. 在 rt_config.h 中不显示为开启的配置项。
已经和 env 中的实现函数进行过仔细比对，确定功能运行正确。
]

[tools/menuconfig.py] update rt_config.h generation func

---

components/drivers/serial/serial.c

[
合并重复代码，在f429上测试通过，修改buff 大小能够进行一次提醒
]

[DeviceDrivers] add warning about overflowing by serial receiver

---

components/net/sal_socket/src/sal_socket.c

[
fix rt_thread_mdelay parameter error bug;
]

fix rt_thread_mdelay parameter error bug;

---

libcpu/risc-v/common/context_gcc.S

[
修改了K210上下文切换退出时的bug，该bug会导致中断被提前打开造成死锁。
在K210芯片上进行了测试验证。
]

修改了上下文切换退出时的bug，该bug会导致中断被提前打开造成死锁

---

components/drivers/misc/rt_drv_pwm.c

[Missing "pwm1" in components/drivers/misc/rt_drv_pwm.c . Fix pwm shell command error "pwm_set pwm1 1 100 50".]

components: drivers: misc: pwm: Missing "pwm1" here.

---

bsp/qemu-vexpress-a9/drivers/secondary_cpu.c
include/rtdef.h
src/clock.c
src/scheduler.c
src/thread.c

修正存在多个具有相同优先级就就绪任务时，这些任务之间切换过于频繁的问题，现在改为必须等运行时间片用完一轮后才能由同优先级任务抢占。

修正相同优先级任务切换太频繁的问题

---

components/drivers/usb/usbdevice/class/rndis.c

[RNDIS]fix speed on HS

---

bsp/stm32/libraries/STM32F7xx_HAL/SConscript

添加 stm32f7xx_hal_crc_ex.c，避免开启 CRC IP 的时候报错

[bsp/stm32] Update f7 HAL Lib SConscript

---

components/dfs/include/dfs_fs.h
components/dfs/src/dfs_fs.c
components/dfs/src/poll.c
components/dfs/src/select.c
components/drivers/sdio/block_dev.c

2.dfs增加函数，配合实现sd卡热插拔自动挂载卸载文件系统
[
1.修复SD卡热插拔内存泄露的bug
2.dfs层增加函数，配合实现sd卡热插拔文件系统自动挂载和卸载。该函数之前只有调用，没有实现函数体。
这2个问题在STM32H750上测试时发现，经过修改测试通过。
]

1.修复sd卡热插拔内存泄露的bug

---

bsp/stm32/libraries/HAL_Drivers/drv_common.c

Fix comment errors
[
]
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please …

Fix comment errors

---

bsp/gd32303e-eval/drivers/drv_i2c.c
bsp/gd32e230k-start/drivers/drv_i2c.c
components/drivers/Kconfig
components/drivers/i2c/i2c-bit-ops.c
components/drivers/i2c/i2c_core.c
components/drivers/i2c/i2c_dev.c
components/drivers/include/drivers/i2c.h

[
Chang i2c debug message print way to ulog, and insert debug config
choices ioto kconfig file.
]

[Device/I2C] Chang debug message print way to ulog

---

bsp/stm32/libraries/HAL_Drivers/config/f7/uart_config.h

[bsp/stm32] Update uart_config.h

---

bsp/stm32/libraries/HAL_Drivers/drv_gpio.c

增加GPIO中断进入退出保护

---

bsp/stm32/libraries/HAL_Drivers/config/l4/dma_config.h
bsp/stm32/libraries/HAL_Drivers/drv_usart.c

[bsp/stm32] Add DMAMUX support for stm32l4+.

---

components/finsh/shell.c

[
fix spelling mistake in the comments of shell.c
]

fix spelling mistake in the comments of shell.c

---

bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_l4.c
bsp/stm32/libraries/HAL_Drivers/drv_usbd.c

[
修改stm32驱动库:
1.修改drv_flash_l4.c文件中stm32_onchip_flash定义的blk_size字段,由原来2048改为FLASH_PAGE_SIZE,以增强芯片适应性.
2.修改drv_usbd.c文件中stm_usbd_register函数,增加支持RT_USING_DEVICE_OPS配置.
]

修改stm32驱动库

---

tools/eclipse.py

优化 scons target=eclipse 功能，移除一些无用的 path

[tools] remove unused path when using scons target eclipse.

---

components/drivers/Kconfig
components/drivers/spi/spi_flash_sfud.c

[
增加 SFUD 调整 SPI 波特率的选项。（默认值和原来一样）
]

[components][sfud] update sfud options.

---

components/utilities/Kconfig
components/utilities/ymodem/ry_sy.c
components/utilities/ymodem/ymodem.c
components/utilities/ymodem/ymodem.h

[
Achieve the function of sending and receiving files via UART using YMODEM。
Use the command "ry [uart0]" to receive the file. Use the command "sy file_path [uart0]" to send the file. The console is used by default. You can choose any uart if you want.
The test uses the console to send and receive files including text, PDF, mp3 without errors, compared with the original file. (The 0x1A at the end of the file is added by the Ymodem protocol to simulate the ctrl Z, which is normal.) Other uart also passed the test. The test uses a baud rate of 115200 and stable transmission rate at 4kB / s. It has been found that an error will occur when the baud rate reaches 1.5M.
Optimization direction:
(1) Add 1024 Byte data packet support.
(2) Support higher serial baud rate transmission.
] …

[components]: utilities: ymodem: Add ymodem send protocol and ry_sy application.

---

components/drivers/spi/spi_flash_sfud.c

[drivers/spi_flash_sfud] accept the error from spi read or write in spi_write_read function.

---

components/drivers/src/ringblk_buf.c

修正 rt_rbb_destroy 中存在的 free 问题

[DeviceDriver][IPC] Fix rbb free bug in rt_rbb_destroy.

---

bsp/stm32/stm32f427-robomaster-a/README.md
bsp/stm32/stm32f427-robomaster-a/board/board.h
bsp/stm32/stm32f427-robomaster-a/board/linker_scripts/link.icf
bsp/stm32/stm32f427-robomaster-a/board/linker_scripts/link.lds
bsp/stm32/stm32f427-robomaster-a/board/linker_scripts/link.sct

[
Correct RAM configuration information
]

[BSP/stm32f427-robomaster-a] Correct RAM configuration information

---

components/net/lwip-1.4.1/src/lwipopts.h
components/net/lwip-1.4.1/src/netif/ethernetif.c
components/net/lwip-2.0.2/src/lwipopts.h
components/net/lwip-2.0.2/src/netif/ethernetif.c
components/net/lwip-2.1.0/src/lwipopts.h
components/net/lwip-2.1.0/src/netif/ethernetif.c

[
- 使得路由器可以发现带有 RT-Thread 名称的网络设备
- 已在 STM32F407 平台上测试过
]

[net][lwip] add personalized RT-Thread sign into lwip protocol stack

---

components/utilities/ulog/ulog.c

Signed-off-by: RGW <rgw5267@gmail.com>
当consol使用rt_hw_console_output时，rt_hw_console_output会忽略掉ulog_console_backend_output传进来的len长度，将log当作字符串直接打印。
[
]
The …

ulogbuffer增加1，为\0预留空间

---

components/drivers/usb/usbdevice/class/ecm.c

#3288 
[
修复ECM的编译错误，已在STM32F469上测试
]

[Components][USB][ECM] fix build error

---

src/components.c

[
test platform:
stm32l475-atk
imxrt1052-atk
]

[src] [components] fix compiler optimize bug

---

bsp/stm32/libraries/STM32G4xx_HAL/CMSIS/Device/ST/STM32G4xx/Source/Templates/gcc/startup_stm32g431xx.s
bsp/stm32/libraries/STM32G4xx_HAL/CMSIS/Device/ST/STM32G4xx/Source/Templates/gcc/startup_stm32g441xx.s
bsp/stm32/libraries/STM32G4xx_HAL/CMSIS/Device/ST/STM32G4xx/Source/Templates/gcc/startup_stm32g471xx.s
bsp/stm32/libraries/STM32G4xx_HAL/CMSIS/Device/ST/STM32G4xx/Source/Templates/gcc/startup_stm32g473xx.s
bsp/stm32/libraries/STM32G4xx_HAL/CMSIS/Device/ST/STM32G4xx/Source/Templates/gcc/startup_stm32g474xx.s
bsp/stm32/libraries/STM32G4xx_HAL/CMSIS/Device/ST/STM32G4xx/Source/Templates/gcc/startup_stm32g483xx.s
bsp/stm32/libraries/STM32G4xx_HAL/CMSIS/Device/ST/STM32G4xx/Source/Templates/gcc/startup_stm32g484xx.s
bsp/stm32/libraries/STM32G4xx_HAL/CMSIS/Device/ST/STM32G4xx/Source/Templates/gcc/startup_stm32gbk1cb.s

[
- 修复使用 RT-Thread Studio 上编译基于芯片创建的 STM32G431 工程无法执行的问题 
- 已在 STM32G431 Nucleo-64  平台上测试过
]

[bsp][stm32] fix a problem that using gcc compile the chips of stm G4 series  but chip doesn't work

---

bsp/w60x/makeimg.py

修正`makeimg.py`逻辑以便在linux上生成烧录固件

fix makeimg.py wrong on linux

---

src/Kconfig

Update the RT_VER_NUM to 4.0.3.

Update the RT_VER_NUM to 4.0.3.

---

src/timer.c

[
-  [src/timer.c]fixed rt_timer_list_next_timeout multi-task safe
]
- [ √] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [√ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [√] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [√] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [√] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [√] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [v] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

[src/timer.c]fixed rt_timer_list_next_timeout multi-task safe

---

bsp/lpc55sxx/lpc55s69_nxp_evk/applications/main.c
bsp/lpc55sxx/lpc55s69_nxp_evk/applications/tfm_ps.c
bsp/lpc55sxx/lpc55s69_nxp_evk/project_ns.uvoptx
bsp/lpc55sxx/lpc55s69_nxp_evk/project_ns.uvprojx

[
TFM is an implementation of PSA, these patches are going to add protected storage (PS) demo in RTT. The PS service is from TFM in secure, meanwhile, RTT in the non-secure side can call into TFM to get data secure.
This feature needs package PR https://github.com/RT-Thread/packages/pull/544.
It also needs TFM package branch lpc-v1.0 after PR merged. https://github.com/RT-Thread-packages/trusted-firmware-m/pull/1
This feature has been tested on NXP LPC55S69.
]
必须选择一项 Choose …

Add TFM PS demo with RTT

---

bsp/raspberry-pi/raspi3-32/applications/test_device.c

[bsp] fix macro error

---

bsp/stm32/libraries/HAL_Drivers/config/f4/dma_config.h
bsp/stm32/libraries/HAL_Drivers/config/f4/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f4/tim_config.h
bsp/stm32/libraries/HAL_Drivers/drv_lcd.c
components/drivers/Kconfig
components/drivers/usb/usbdevice/class/cdc_vcom.c

[
1、Update the adc, now can use DMA in adc.
2、Fix the SPI4 RX DMA error, because SPI4_RX is writen to SPI4_TX in dma_config.h
3、Add the PWM9 default config in pwm_config.h, and add the TIM3 default config in tim_config.h
4、Add a empty function for the case: LCD backlight neither controled by PWM nor by PIN level.
All the 4 modifies were test in my working project.
]

Add DMA for ADC driver, and other little update.

---

ChangeLog.md
src/components.c

[
- **fixed file whitespace character.**
]
- [√ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [√ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ √] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [ √] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [√ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ √] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ √] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

fixed whitespace character

---

bsp/imxrt/imxrt1052-atk-commander/board/Kconfig
bsp/imxrt/libraries/drivers/SConscript
bsp/imxrt/libraries/drivers/drv_usbd.c
bsp/imxrt/libraries/drivers/usb/device/usb_device.h
bsp/imxrt/libraries/drivers/usb/device/usb_device_dci.c
bsp/imxrt/libraries/drivers/usb/device/usb_device_dci.h
bsp/imxrt/libraries/drivers/usb/device/usb_device_ehci.c
bsp/imxrt/libraries/drivers/usb/device/usb_device_ehci.h
bsp/imxrt/libraries/drivers/usb/host/usb_host.h
bsp/imxrt/libraries/drivers/usb/host/usb_host_devices.c
bsp/imxrt/libraries/drivers/usb/host/usb_host_devices.h
bsp/imxrt/libraries/drivers/usb/host/usb_host_ehci.c
bsp/imxrt/libraries/drivers/usb/host/usb_host_ehci.h
bsp/imxrt/libraries/drivers/usb/host/usb_host_hci.c
bsp/imxrt/libraries/drivers/usb/host/usb_host_hci.h
bsp/imxrt/libraries/drivers/usb/include/usb.h
bsp/imxrt/libraries/drivers/usb/include/usb_device_config.h
bsp/imxrt/libraries/drivers/usb/include/usb_ehci.h
bsp/imxrt/libraries/drivers/usb/include/usb_misc.h
bsp/imxrt/libraries/drivers/usb/include/usb_spec.h
bsp/imxrt/libraries/drivers/usb/phy/usb_phy.c
bsp/imxrt/libraries/drivers/usb/phy/usb_phy.h

[
[imxrt] [driver] add usb device driver
verify platform:imxrt1052-atk-command
]

[imxrt] [driver] add usb device driver

---

src/kservice.c

Update show version info.

---

include/rtdef.h
src/timer.c

[解决的问题：2个线程在同时操作一个软件定时器，在A线程打开了定时器，B线程要根据定时器的开关状态做一些操作，所以增加定时器运行状态查询功能。
实际产品上测试： 物联网产品中使用软件定时器实现网络状态灯功能，解决了个别异常网络状态下指示灯不正常工作的问题]

给软件定时器增加定时器工作状态查询的功能

---

tools/gcc.py

rename GCC_VERSION to GCC_VERSION_STR to avoid conflict.

[Tools] rename GCC_VERSION to GCC_VERSION_STR

---

components/net/at/Kconfig

[ 发现并修正了一个单词拼写错误 Commonds --> Commands ]

[AT] Fix typos in Kconfig

---

libcpu/rx/cpuport.c

[
Fixed typo:
threah -> thread
swithc -> switch
]

Fixed typos: 'threah' and 'swithc' in cpuport.c

---

components/net/lwip-1.4.1/src/core/snmp/msg_out.c

[
Note that the word 'lenght' is wrong,
so that 'lenght' should been replaced with 'length'.
]

Fixed typo: 'lenght'

---

libcpu/rx/context_iar.S

[
function name: swtich_to_thread -> switch_to_thread
]

Fixed function spelling mistakes in context_iar.S

---

bsp/lpc176x/drivers/sd.c

[
Note that the word 'commond' is wrong,
so that 'commond' should been replaced with 'command'.
]

Fixed typo: 'commond'

---

components/net/uip/uip/lc-switch.h

[
Fixed macro error: __LC_SWTICH_H__ -> __LC_SWITCH_H__
]

[net] Fixed macro error in lc-switch.h

---

libcpu/arm/cortex-m33/context_gcc.S

[libcpu]context-m33:fix label error in context_gcc.S

---

bsp/qemu-vexpress-a9/drivers/audio/drv_pl041.c
bsp/qemu-vexpress-a9/drivers/audio/drv_pl041.h
bsp/qemu-vexpress-a9/drivers/audio/drv_sound.c

[
**macro error:**  
PL041_CHANNLE_NUM ->   PL041_CHANNEL_NUM 
PL041_CHANNLE_LEFT_DAC  -> PL041_CHANNEL_LEFT_DAC
PL041_CHANNLE_RIGHT_DAC  ->  PL041_CHANNEL_RIGHT_DAC
PL041_CHANNLE_LEFT_ADC   -> PL041_CHANNEL_LEFT_ADC
PL041_CHANNLE_RIGHT_ADC  -> PL041_CHANNEL_RIGHT_ADC             
**parameter error:**
channle -> channel
**functions error:**
aaci_pl041_channle_disable -> aaci_pl041_channel_disable
aaci_pl041_channle_enable -> aaci_pl041_channel_enable
aaci_pl041_channle_read -> aaci_pl041_channel_read
aaci_pl041_channle_write -> aaci_pl041_channel_write
aaci_pl041_channle_cfg -> aaci_pl041_channel_cfg
]
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed …

Fixed  spelling mistakes of macro, parameter ,functions 

---

bsp/raspberry-pi/raspi3-64/driver/Kconfig
bsp/raspberry-pi/raspi3-64/driver/drv_spi.c

[
MicroPython depends on SPI driver. By making SPI driver pass compiling, MicroPython is compiled and runnable on device.
Tested on Raspberry Pi 3B. Python itself works. But machine package is not working yet, rthread package functions freeze after done its work.
]

Make MicroPython run on Raspi3-64 bsp

---

components/drivers/sensors/sensor.h

[
我在使用Sensor设备驱动框架时发现缺少我目前需要的一些传感器类型定义和厂家信息，因此希望能增加相应的内容。
]

[Sensor] Add some class and vendor information of sensor

---

bsp/lpc176x/drivers/sd.c

[
LPC17xx_SD_WirteDataBlock -> LPC17xx_SD_WriteDataBlock
]

Fixed  spelling mistakes of function

---

components/drivers/sensors/sensor.c
components/drivers/sensors/sensor.h

[
之前提交的宏是 `RT_SENSOR_VENDOR_AOSONG`，经查阅，广州奥松 Aosong Electronics Co., LTD. 的商标为"ASAIR"，同时在 aht10 软件包中也使用了 asair 的标识，因此修改为 `RT_SENSOR_VENDOR_ASAIR` 应该更合适。
另外，`RT_SENSOR_CLASS_DUST` 和 `RT_SENSOR_CLASS_ECO2` 传感器类型缺少了前缀字符串，因此为其添加对应字符串。
]

[Sensor] Modified vendor name and add two prefix corresponding to sensor types

---

bsp/raspberry-pi/raspi3-64/driver/SConscript
bsp/raspberry-pi/raspi3-64/driver/board.c
libcpu/aarch64/cortex-a53/mmu.c
libcpu/aarch64/cortex-a53/mmu.h

[
完善raspi3-64 mmu的功能，支持最小4k映射的方式
]

[bsp/raspi3] raspi3 mmu

---

components/dfs/filesystems/uffs/src/emu/uffs_fileem_ecc_hw_auto.c
components/dfs/filesystems/uffs/src/emu/uffs_fileem_ecc_soft.c
components/dfs/filesystems/uffs/src/example/flash-interface-example.c

[
WirtePageWithLayout ->WritePageWithLayout 
]

Fixed typo 'WirtePageWithLayout' in uffs

---

src/thread.c

Signed-off-by: suhui <3164683437@qq.com>
[
the comment is not correct
it does not need test
]

fix the comment

---

bsp/stm32/libraries/HAL_Drivers/drv_eth.c

[
Note that the word 'lenth' is wrong in the output infomation,
so that 'lenth' should been replaced with 'length'.
And floder-> folder in line 22.
]

[bsp/stm32]Fixed typo 'lenth' in drv_eth.c

---

bsp/raspberry-pi/raspi3-32/driver/drv_sdio.c

[
修复raspi sdio 驱动多个block读取时的bug
]

fix raspi3-32 sdio driver

---

include/rtdbg.h

[rtdbg] Add for cpp support.

---

bsp/amebaz/libraries/Kconfig

[bsp] Fixed the wrong output infomation in Kconfig

---

components/drivers/wlan/wlan_dev.c
components/drivers/wlan/wlan_dev.h

[
- wlan 框架中添加裸帧数据发送接口和管理帧过滤和回调注册接口；
- 该改动已经在 W600 设备和 RTL8720CF 设备上验证通过，用于阿里云零配主配网功能支持。
]

[driver][wlan] add raw frame send interface and Management frame filter interface

---

components/libc/time/clock_time.h

[
Make `clock_time.h` available to C++ since I need the real-time clock for C++ `condition_variable::wait_for`.
Tested on qemu-vexpress-a9
]

make clock_time.h available to C++

---

components/drivers/sensors/sensor_cmd.c

[
为 sensor 命令增加了对一些传感器类型和厂商的支持。
]

[Sensor] Add vendor info and sensor types for cmd

---

bsp/stm32/stm32f407-atk-explorer/project.uvprojx

[
修改了 bsp 下 stm32f407-atk-explorer， mdk5 工程编译报错的 bug。 解决方法，使用 env 工具重新生成 mdk5工程。 编译通过。
]

[update] 修改了 stm32f407-atk-explorer mdk5 工程编译报错的bug

---

bsp/simulator/SConstruct

Fixed typo 'rthread' in help infomation

---

bsp/stm32/libraries/HAL_Drivers/config/l4/uart_config.h
bsp/stm32/libraries/HAL_Drivers/drv_usart.c

[
修复 UART DMA TX 的问题，l4r9 测试通过
]

[bsp] fix UART DMA TX

---

bsp/at32/at32f403a-start/README.md

[modify at32f403a-start README.md]
- [] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback

[bsp/at32] modify at32f403a-start README.md

---

bsp/gd32450z-eval/drivers/synopsys_emac.c

[
源文件主要存在以下两点问题：
1> EMAC_init函数中对MAC进行配置时直接对寄存器进行操作，然而寄存器名称与官方文档中的寄存器名称不符，另外并没有对基于的gd32f450z开发板使用的PHY芯片DP83848进行配置，直接使用了其上电自协商的模式，而且直接配置了MAC为百兆全双工的工作模式，这里应该通过读取PHY的自协商结果来设置MAC，所以替换了GD官方的初始化函数；
2> 使用原文件编译下载至开发板后复位有概率ping不通，这是由于在初始化过程中清空发送FIFO的操作没有增加延迟导致的，所以换成了GD官方的enet_txfifo_flush函数；
已在GD32450Z-EVAL开发板上测试，修改后没有再出现以上问题。
]
- [√] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback …

Fix bug for synopsys_emac.c

---

bsp/stm32/libraries/HAL_Drivers/drv_crypto.c

[
Added if null before used.
]

[bsp]Fixed a  stack overflow bug in drv_crypto.c

---

bsp/fh8620/drivers/pwm.c

[
'memset' should been next step after 'NULL' judge, Not before it.
]

Fixed a hidden stack overflow bug

---

components/dfs/include/dfs_fs.h
components/dfs/src/dfs_fs.c
components/drivers/usb/usbdevice/class/mstorage.c

Signed-off-by: Cliff Chen <cliff.chen@rock-chips.com>
[
目前的msc模式不支持自动切换，有两个问题：
1. device连上设备的时候，不会自动卸载文件系统，导致pc上msc挂不上
2. pc断开msc连接的时候，device不会自动挂载文件系统，导致device上无法访问文件
上述问题导致，msc模式下device和pc共享同一个磁盘分区很不方便，这个补丁可以解决这个问题
]

Support msc mode automatic switching

---

components/drivers/include/drivers/spi.h

support slave mode and master mode runtime config.
Change-Id: Iabadbade8997bb8e3adef8ce95f6c45f6bb35329
Signed-off-by: Yifeng Zhao <yifeng.zhao@rock-chips.com>
[
spi: support slave mode and master mode runtime config.
]

spi: support slave mode and master mode runtime config

---

components/drivers/sensors/sensor.c
components/drivers/sensors/sensor.h

[
Sensor 框架面向传感器驱动的接口只有 fetch_data 和 control，并且 rt_sensor_control 只对框架内定义的7个命令有效，这样难以满足很多传感器的特定功能。因此建议增加对自定义命令的支持，将非 Sensor 框架内的命令传递到传感器驱动进行处理。
此外，对于有 module 的 sensor 设备，在 default 直接 return 会造成 take 的互斥锁没有 release，可能影响下一次访问 sensor 设备。
所作修改已在本地工程通过测试。
]

[Sensor] Support custom commands for rt_sensor_control

---

bsp/mm32l3xx/README.md

update readme ：Fixed spelling mistakes

---

bsp/imx6sx/iMX6_Platform_SDK/sdk/drivers/audio/src/snd_card.c

fixed a typo

---

components/drivers/Kconfig

[
mesage -> message
memmory -> memory
]

Fixed typos in Kconfig

---

tools/eclipse.py

修复 scons --target=eclipse 时，部分带值宏出错的问题，

修复 scons --target=eclipse 时，部分带值宏出错的问题

---

bsp/stm32/libraries/HAL_Drivers/drv_adc.c

[
修复部分STM32系列中由于在HAL库中没有相应的ADC通道宏定义而产生的编译错误。
L0系列中的STM32L053xx/063xx/073xx/083xx 没有 ADC_CHANNEL_16；
F0系列中的STM32F030x6/x8/xB/xC和STM32F070x6/xB 没有 ADC_CHANNEL_18；
H7系列有 ADC_CHANNEL_19；
L1系列有多达32个ADC通道，因还没适配，暂时划入最大通道号 ADC_CHANNEL_19。
]

[drv_adc.c]Fixed ADC channel configuration bug for SMT32F0/L0/H7

---

tools/eclipse.py

update eclipse tools version number.

[tools] update eclipse tools version number.

---

bsp/stm32/libraries/HAL_Drivers/drv_usart.c
bsp/stm32/libraries/HAL_Drivers/drv_usart.h
components/drivers/serial/serial.c
include/rtdef.h

[
- 为串口设备添加设备关闭功能
- 修复当开启 DMA 发送功能时，如果此时产生串口溢出中断，程序无法清除 UART_FLAG_ORE，会导致系统频繁进入 HAL_UART_IRQHandler 大量消耗 CPU 的问题
已经在 407 探索者开发板上做过测试。
]

[stm32/driver] optimize uart driver

---

bsp/x1000/drivers/board.c

fix x1000 memory use bug

---

bsp/raspberry-pi/raspi3-64/driver/board.c
libcpu/aarch64/cortex-a53/context_gcc.S

add soc timer cntpct

---

components/net/netdev/src/netdev_ipaddr.c

[
修复netdev中的NETDEV_IPV4拼写错误，导致inet_ntop函数解析错误。已在开发板验证通过
]

[update] 修复拼写错误

---

bsp/essemi/es32f0271/drivers/drv_i2c.c
bsp/essemi/es32f0334/drivers/drv_i2c.c
bsp/essemi/es32f0654/drivers/drv_i2c.c

[
fixed i2c bug, change i2c_dbg() to LOG_E().
]

fixed i2c bug, change i2c_dbg() to LOG_E().

---

components/drivers/wlan/wlan_dev.c

Fixed wrong output information

---

components/finsh/cmd.c

[
为FINSH添加类似于Linux终端下的clear命令,用于清除当前终端上的内容.算是一个比较基本的命令.常用的其他平台的终端都有这个命令.
]

为FINSH添加clear命令

---

bsp/stm32/libraries/STM32F2xx_HAL/SConscript
components/drivers/usb/usbhost/class/adk.h

[
Fix some spelling mistakes
]

Fix some spelling mistakes

---

components/libc/compilers/minilibc/sys/types.h

[
minilibc/sys/types.h redefinition of typedef 'mode_t'
]

remove redefinition 'mode_t'

---

examples/file/listdir.c
examples/file/readspeed.c
examples/file/readwrite.c
examples/file/seekdir.c
examples/file/writespeed.c

文件系统相关的测试代码已经很久没更新了。以前只支持 FinSH 命令，这个 PR 加入了 MSH。另外把中文注释翻译成了英文。
The file examples haven been updated for a long time. It only supports FinSH cmd. This PR will add MSH support to these examples.
其他修改 additional changes
-   添加Apache-2.0 声明。 add apache 2.0 license
-   中文注释改成英文 replace Chinese comments into English.
-   静态buffer改成动态申请 change static buffer to dynamically allocated buffers.
已经在自制STM32H7下用sd卡和emmc进行测试。无内存泄漏或其他情况。
This has been tested under a customized STM32H7 development board with SD card and EMMC. No memory leaking or other issues. …

Export file examples to MSH

---

components/drivers/src/pipe.c

[
Fixed stackover flow bug when create pipe->fifo
]

[components/drivers] update pipe.c

---

include/rtservice.h
include/rtthread.h
src/object.c
src/timer.c

Add rt_object_get_length/rt_object_get_pointers APIs and test under QEMU-VExpress-A9

Kernel object

---

bsp/raspberry-pi/raspi3-64/README.md
bsp/raspberry-pi/raspi4/driver/board.c
bsp/raspberry-pi/raspi4/driver/board.h
bsp/raspberry-pi/raspi4/driver/drv_gpio.h
bsp/raspberry-pi/raspi4/driver/drv_uart.c
bsp/raspberry-pi/raspi4/driver/drv_uart.h
bsp/raspberry-pi/raspi4/driver/iomap.h
components/finsh/finsh.h
components/finsh/finsh_compiler.c

[
1.fix raspi3-64 readme
2.clean up raspi4 code
3.fix finsh compiler waring
]

Fix aarch64 waring

---

examples/network/tcpsendpacket.c

[
1. Fixed stackover flow bug;
2. Changed the notes from GB18030 to UTF-8.
]

[examples/network]Update tcpsendpacket.c

---

README.md
README_zh.md

* 修改主页上的README.md, 增加Nuclei处理器展示

[DOC] Add Nuclei to main README.md

---

libcpu/arm/s3c24x0/start_gcc.S
libcpu/arm/s3c44b0/start_gcc.S

[libcpu/arm]Update start_gcc.S

---

bsp/raspberry-pi/raspi3-64/driver/drv_fb.c
bsp/raspberry-pi/raspi3-64/driver/mbox.c
bsp/raspberry-pi/raspi3-64/driver/mbox.h

Raspi mbox

---

bsp/nrf5x/libraries/drivers/drv_uart.c
bsp/nrf5x/nrf52840/board/Kconfig
bsp/nrf5x/nrf52840/rtconfig.h

[
BSP UART支持
在nRF52840-DK上做了测试，可以开启并与FinSH交互
]

[bsp\nrf5x]Support BSP UART0

---

components/drivers/sensors/sensor.h

[
添加sensor厂商信息（TI），已在TI TMP1075温度传感器上测试使用。
]

Add vendor information of sensor

---

bsp/stm32/stm32f103-atk-warshipv3/applications/main.c

fix led0 --> led1

---

components/net/at/at_socket/at_socket.c
components/net/netdev/src/netdev.c
components/net/sal_socket/src/sal_socket.c

fixed some typos

---

tools/eclipse.py

[
ubuntu 环境下，路径表示错误，无法找到正确的路径。已在 ubuntu 环境下进行测试。
]

[update] ubuntu 环境下，文件路径错误

---

tools/eclipse.py

修改 eclipse.py 版本

---

components/drivers/watchdog/watchdog.c

[
修改 components\drivers\watchdog\watchdog.c 注释的一处笔误：
This function initializes serial 改为 This function initializes watchdog
]
- [] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback

[drivers][watchdog] 修复watchdog.c 注释的一处笔误

---

bsp/ls2kdev/README.md
bsp/ls2kdev/SConstruct

[
ls2k windows construction of development environment
]

add bsp/ls2k windows compilation instructions

---

bsp/stm32/libraries/HAL_Drivers/SConscript
bsp/stm32/libraries/HAL_Drivers/drv_flash/drv_flash_h7.c
bsp/stm32/stm32h743-atk-apollo/README.md
bsp/stm32/stm32h743-atk-apollo/board/Kconfig
bsp/stm32/stm32h743-atk-apollo/board/ports/fal_cfg.h

[
1.适配stm32h7的内部flash的fal；
2.本次提交已在stm32h743-atk-apollo测试通过；
3.本次提交的drv_flash_h7.c和fal_cfg.h 由作者(yufanyufan77)委托(whj4674672)PR，测试由(whj4674672)完成。
]

[bsp/stm32/stm32h743-atk-apollo]support stm32h7 fal

---

components/finsh/cmd.c

[
鉴于[https://www.rt-thread.org/qa/thread-424565-1-1.html](https://www.rt-thread.org/qa/thread-424565-1-1.html)的情况,添加了一个static,防止出现冲突.@aozima
]

添加static前缀,防止与用户自定函数冲突

---

bsp/nrf5x/libraries/drivers/SConscript
bsp/nrf5x/libraries/drivers/drv_spi.c
bsp/nrf5x/libraries/drivers/drv_spi.h
bsp/nrf5x/nrf52840/board/Kconfig
bsp/nrf5x/nrf52840/board/sdk_config.h

[
1. 添加 nrf5x 的 SPI 外设接口的 BSP 驱动。
2. 可使用 rt-thread 的 SPI 接口函数管理 nrf5x 系列芯片的 SPI 总线设备。
3. 测试板卡：nrf52840 DK(pca10056) 测试通过。
]

[BSP]Add nrf5x SPI BSP

---

bsp/ls2kdev/drivers/drv_gpio.c
bsp/ls2kdev/drivers/drv_gpio.h
bsp/ls2kdev/drivers/ls2k1000.h

Signed-off-by: duhuanpeng <548708880@qq.com>
[
GPIO（不含IRQ）驱动 V2 版本：
1. 修正了代码风格，并使用 checkpatch.pl 检查，没有错误，有部分超80字符的警告。
]

bsp: ls2k: initial gpio driver without irq support

---

bsp/raspberry-pi/raspi2/cpu/cp15.h
bsp/raspberry-pi/raspi2/cpu/interrupt.c
bsp/raspberry-pi/raspi2/driver/board.c
bsp/raspberry-pi/raspi3-32/driver/board.c
libcpu/arm/cortex-a/start_gcc.S

[
1.fix raspi2 bsp timer
2.remove  raspi3-32 unnecessary code
3.hyp mode fix startup code address relative jump
]

fix raspi bsp

---

components/drivers/spi/sfud/inc/sfud_flash_def.h

[
新增 W25Q32BV 支持 Fast Read QUAD_OUTPUT and QUAL_IO mode
]

[W25Q32BV]Support fast read QUAD_OUTPUT and QUAL_IO.

---

components/libc/compilers/newlib/syscalls.c
components/libc/pthreads/SConscript
components/libc/pthreads/pthread.c
include/rtdef.h

修正使用新版本的newlib时，pthreads编译出错的问题；同时解决64位下pthreads的问题；
在以下工具链中验证：
* gcc-arm-none-eabi-5_4-2016q3
* gcc-arm-none-eabi-7-2018-q2-update
* gcc-arm-none-eabi-8-2019-q3-update
* gcc-arm-none-eabi-9-2019-q4-major
* riscv-none-embed-gcc-8.3.0-1.1
* mips-2016.05

Fix pthreads

---

tools/building.py

[
Use generic algorithms to replace outdated`python2 cmp`
]

[tools] fixed python 2.x `cmp`

---

components/drivers/sensors/sensor.h
components/drivers/sensors/sensor_cmd.c

[
正在制作攀藤（Plantower）PM2.5传感器软件包，希望增加相应标识。
]

[Sensor] Add Plantower sensor info

---

components/finsh/msh_file.c

[
add code:
if (line_buf == RT_NULL) return -RT_ENOMEM;
]

[finsh]Fixed a bug may cause stackover flow

---

bsp/imxrt/imxrt1052-atk-commander/rtconfig.py
bsp/imxrt/imxrt1052-fire-pro/rtconfig.py
bsp/imxrt/imxrt1052-nxp-evk/rtconfig.py
bsp/imxrt/imxrt1064-nxp-evk/SConstruct
bsp/imxrt/imxrt1064-nxp-evk/rtconfig.py
bsp/imxrt/tools/sdk_dist.py

[
1. 为什么提交这份PR？
在imxrt中imxrt1064-nxp-evk的BSP包中使用scons --dist生成的工程目录中没有libraries目录，无法正常使用
2. 解决的问题是什么？
修复了无法生成libraries目录的问题，我的解决方案是修改了SConstruct，rtconfig.py, sdk_dist.py中与生成libraries相关的python脚本。
在imxrt1064-nxp-evk的BSP中进行了测试
]

[BSP][IMXRT]fixed scons --dist in IMXRT BSP

---

bsp/at32/at32f403a-start/rtconfig.py
bsp/at32/at32f407-start/rtconfig.py
bsp/at32/tools/sdk_dist.py

[
修复 AT32 系列 BSP 在 scons --dist 构建工程失败的问题
]

[BSP] [AT32] fixed scons --dist

---

libcpu/arm/cortex-m3/cpuport.c
libcpu/arm/cortex-m33/cpuport.c
libcpu/arm/cortex-m4/cpuport.c
libcpu/arm/cortex-m7/cpuport.c

[
fixed __rt_ffs bug on account of armclang LTO.
issues  related:  #3698 
]

[libcpu/arm/*/cpuport.c]fixed __rt_ffs bug on account of armclang LTO.

---

components/net/Kconfig

[
enable LWIP_SO_LINGER option feature of LWIP.
]

[net/lwip]: enable LWIP_SO_LINGER option feature of LWIP.

---

bsp/stm32/libraries/HAL_Drivers/drv_sdio.c

[bsp][stm32][drv_sdio.c]  adapt stm32f2 series | 适配 stm32f2 系列

---

bsp/tm4c129x/applications/board.c
bsp/tm4c129x/applications/board.h

[
**Fix the bug that HEAP is not initialized at system start up.** 
reference #3713
**Test with TI TM4C129X**
]
The following content must not be changed in …

[BSP][TM4C129X] Fix the bug that HEAP is not initialized at system start up.

---

components/net/lwip-2.1.2/src/netif/ethernetif.c

[
Delete duplicate header files.
]

delete duplicate header files

---

bsp/gd32vf103v-eval/board/Kconfig
bsp/gd32vf103v-eval/drivers/drv_gpio.c
bsp/gd32vf103v-eval/drivers/drv_gpio.h

[
在 GD32VF103C-START 开发板上验证通过
]

[BSP][gd32vf103] add drv_gpio.c

---

components/drivers/spi/spi_flash_sfud.c

[DeviceDriver][SFUD] Update the 'sf bench' command.

---

bsp/stm32/stm32f746-st-disco/rtconfig.py
bsp/stm32/stm32f767-st-nucleo/rtconfig.py

[
发现 stm32f746-st-disco 和 stm32f767-st-nucleo 两个 BSP 在 scons --dist 构建的工程不完整，因此为其添加缺失的 dist_handle 函数。顺便调整了几处缩进不对齐的小问题。
]

[bsp] add missing dist_handle function for two stm32 bsp

---

bsp/imxrt/imxrt1052-atk-commander/rtconfig.py
bsp/imxrt/imxrt1052-fire-pro/rtconfig.py
bsp/imxrt/imxrt1052-nxp-evk/rtconfig.py
bsp/imxrt/imxrt1064-nxp-evk/SConstruct
bsp/imxrt/imxrt1064-nxp-evk/rtconfig.py
bsp/imxrt/tools/sdk_dist.py
tools/mkdist.py

[
1. 为什么提交这份PR？
在imxrt中的BSP包中使用scons --dist生成的工程目录中没有libraries目录，无法正常使用
2. 解决的问题是什么？
修复了无法生成libraries目录的问题，我的解决方案是修改了SConstruct，rtconfig.py, sdk_dist.py， 中与生成libraries相关的python脚本以及tools/mkdist.py。
在imxrt的所有BSP中进行了测试
]

fixed scons --dist in IMXRT BSP

---

bsp/stm32/stm32mp157a-st-discovery/README.md
bsp/stm32/stm32mp157a-st-discovery/README_zh.md

[update] add English README.md

---

src/kservice.c

[
format code style of rt_strcmp function
testcase run well, and run the next process
```
/* kservice_array is differrent from temp_cmp */
static void test_kservice_strcmp(void)
{
rt_uint8_t result = 0;
const char temp_cmp[TC_MEM_LENGTH] = "012dcd";
result = rt_strcmp(kservice_array, temp_cmp);
uassert_true(result != 0);
result = rt_strcmp(temp_cmp, temp_cmp);
uassert_true(result == 0);
}
````
run normal.
] …

[format] code style of rt_strcmp function

---

bsp/stm32/stm32h743-st-nucleo/board/SConscript

[
更新该 bsp 构建脚本，解决 dist 后编译出错的问题。
已经重新测试该 bsp 的 dist 后编译功能。
]

[bsp][stm32] update stm32h743-st-nucleo bsp scripts

---

bsp/nrf5x/libraries/drivers/SConscript
bsp/nrf5x/libraries/drivers/drv_pwm.c
bsp/nrf5x/nrf52840/board/Kconfig

[bsp/nrf5x]: add the driver of pwm

---

bsp/essemi/es8p508x/SConscript

[
Add " from building import * ".
]

bugfixed on SConscript

---

src/ipc.c
src/timer.c

[
add switch default clause.
switch 使用结构不完整，编写不规范，添加缺少 default 语句。 
test on stm32f407 board and qemu with testcase, run well.
]

[add] switch default clause

---

bsp/stm32/stm32h750-armfly-h7-tool/board/SConscript

[
启动文件选择错误
Wrong startup file selection
]

fix startup files

---

components/dfs/src/dfs_fs.c

clean the unnecessary checking in dfs/unmount device.

[DFS] clean the unnecessary checking

---

bsp/imxrt/imxrt1052-nxp-evk/rtconfig.py
bsp/imxrt/imxrt1064-nxp-evk/README.md
bsp/imxrt/imxrt1064-nxp-evk/rtconfig.py

[
1. 为什么提交这份PR
IMXRT1064-NXP-EVK的BSP使用GCC编译的文件无法运行。
2. 问题的原因
未预定义__STARTUP_INITIALIZE_NONCACHEDATA和__STARTUP_CLEAR_BSS，使得NONCACHEDATA和BSS段的数据未被初始化
3. 解决方案
在rtconfig.py中对GCC平台下的汇编选项增加了预定义__STARTUP_INITIALIZE_NONCACHEDATA和__STARTUP_CLEAR_BSS
在imxrt1064-nxp-evk的板子中已经测试OK
]

fixed gcc assembly option in rtconfig.py for imxrt1064-nxp-evk

---

bsp/stm32/libraries/HAL_Drivers/drv_adc.c

[
在开发过程中发现，部分STM32 ADC需要调用 HAL_ADCEx_Calibration_Start() 函数进行自动校准，才能得到较为准确的值。比如 SOC_SERIES_STM32L4 系列，因此参照 stm32mp1 的做法，在 drv_adc.c 的 stm32_get_adc_value() 函数中增加对该函数的调用。
该修改已在 STM32L4R5 上进行测试。
]

[stm32] perform an automatic ADC calibration using HAL_ADCEx_Calibration_Start()

---

components/drivers/Kconfig

[
Change I2C configuration hierarchy
In RT-Thread Studio it looks like this
]

Change I2C configuration hierarchy

---

components/drivers/spi/sfud/inc/sfud_flash_def.h

[
update error SFUD support manufacturer (Micronix -> Macronix) and add sfud flash MX25L51245G info .
]

update error SFUD support manufacturer (Micronix -> Macronix)

---

src/timer.c

拉取/合并请求描述：(PR description)
[
fixed #3817 
]
- [X ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code

fixed the iterator failure for softtimer list timeout check.

---

bsp/nrf5x/libraries/drivers/SConscript
bsp/nrf5x/libraries/drivers/drv_wdt.c
bsp/nrf5x/nrf52840/board/Kconfig

[
增加[bsp/nrf5x/libraries/drivers] 看门狗驱动
测试板卡：清风nrf52840
]

[bsp/nrf5x/libraries/drivers] add wdt driver

---

documentation/coding_style_cn.md
documentation/coding_style_en.txt

Change the license description in code sytel document.

[skip travis] [Doc] Update file header copyright information for license

---

components/utilities/utest/utest.h

[
utest:fixed compile err
]
- [] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

utest:fixed compile err

---

bsp/stm32/libraries/templates/stm32f7xx/SConstruct
bsp/stm32/stm32f769-st-disco/SConstruct

[
修复 stm32f769-st-disco bsp dist 功能，完善 f7 系列 bsp 模板，已经在该 BSP 做过测试。
]

[stm32][bsp] fix stm32f769-st-disco bsp scons --dist function

---

bsp/nrf5x/nrf52832/board/Kconfig
bsp/nrf5x/nrf52832/board/sdk_config.h

[
针对nrf52832 添加 外设ADC, WDT, PWM等配置，支持menuconfig配置。
在青风NRF52832板卡测试没有问题
]

Add some config for nrf52832

---

bsp/nrf5x/nrf52840/board/Kconfig

[add the example of softdevice]

[bsp/nrf5x]add the sample of softdevice config

---

bsp/stm32/libraries/HAL_Drivers/drv_qspi.h
bsp/stm32/libraries/HAL_Drivers/drv_spi.h

[
修复 `SPI API` 在 `C++` 下调用报错。
| MCU           | Frequency | ROM   | RAM   |
|:---------------:|:-----------:|:-------:|:-------:|
| STM32F103ZET6 | 72Mhz    | 512KB | 64KB |
]

[bsp/stm32] Add C++ Support

---

components/libc/compilers/armlibc/fcntl.h
components/libc/compilers/armlibc/sys/ioctl.h
components/libc/compilers/armlibc/sys/unistd.h
components/libc/compilers/armlibc/unistd.h
components/libc/compilers/common/unistd.c
components/libc/compilers/dlib/sys/unistd.h
components/libc/termios/posix_termios.c
components/libc/termios/posix_termios.h

[
详情请查看每次提交的说明
对armlibc的修改已经考虑到附带对dlib和newlib的影响。无须担心，影响已经消除。增加unistd.c文件为所有lib共用文件，该文件负责对unistd.h声明的函数予以实现。
**后续还有一系列的PR要提，请求优先通过**
]

[fix/add/bug] 修改armlibc多处,重新提交了[请求优先通过！！]

---

bsp/at32/Libraries/rt_drivers/drv_eth.c

[
[bsp/at32] add link detecting thread for ethernet driver
]
- [] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback

[bsp/at32] add link detecting thread for ethernet driver

---

bsp/stm32/libraries/HAL_Drivers/drv_can.c

[
add can support for stm32l4
tested on stm32l476
]

[bsp][stm32]add can support for stm32l4

---

components/utilities/ulog/syslog/syslog.c

syslog.c:154:34: error: unknown type name 'uint8_t'
[
ulog:fixed compile err
]

ulog:fixed compile err

---

components/drivers/sensors/sensor.c
components/drivers/sensors/sensor.h
components/drivers/sensors/sensor_cmd.c

[
为 sensor 框架添加 GPS/GNSS 卫星定位传感器类型支持
]

[sensor] support GPS/GNSS sensor class

---

bsp/ls2kdev/drivers/net/synopGMAC.c

[
ls2k1000 gmac address variable,read from pci header
]

gmac address variable

---

bsp/raspberry-pi/raspi3-32/README.md
bsp/raspberry-pi/raspi3-32/README_zh.md
bsp/raspberry-pi/raspi3-64/README.md
bsp/raspberry-pi/raspi3-64/README_zh.md
bsp/raspberry-pi/raspi4-32/README.md
bsp/raspberry-pi/raspi4-32/driver/mbox.c
bsp/raspberry-pi/raspi4-32/driver/mbox.h

Raspi add mbox

---

components/drivers/spi/spi_msd.c

Signed-off-by: SimpleInit <63694297@qq.com>
[删除非对齐地址访问语句和__CORTEX_M宏定义判断]

删除非对齐地址访问语句和__CORTEX_M宏定义判断

---

bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
bsp/stm32/libraries/HAL_Drivers/drv_gpio.h

[
* [stm32/gpio]Optimized the pin-index algorithm
* 已经在我的环境中测试正常（**由于涉及到的地方较多，例如I2C，诸多STM32，所以需要更多开发者来测试**）
]

[stm32/gpio]Optimized the pin-index algorithm

---

components/dfs/filesystems/devfs/devfs.c
components/dfs/include/dfs.h
components/dfs/src/dfs.c

[
遍历句柄时，无法区分设备类型与文件类型。
DFS 添加设备类型
QEMU 模拟器测试运行
]

[add] DFS file system supports device types

---

components/dfs/src/dfs_file.c

[
修复 DEVICE 类型的 FD，无法获取或设置标记
]

[dfs] fix the DEVICE could not get or set flags

---

components/drivers/usb/usbdevice/class/cdc_vcom.c
components/drivers/usb/usbdevice/class/hid.c
components/drivers/usb/usbdevice/class/mstorage.c

[
fix bug in device descriptor that MAC OS enumeration failed.
]

mstorage.c: fix bug in device descriptor that MAC OS enumeration failed.

---

components/drivers/usb/usbhost/core/usbhost_core.c

[
Fixed a bug may cause stackover flow
]

[drivers/usb]Fixed a bug may cause stackover flow

---

bsp/stm32/libraries/HAL_Drivers/drv_gpio.c

[
修复 gpio 驱动无法在 STM32MP1 工作的 BUG；已在 STM32MP1-DK1 开发版上测试通过。 
]

[update] stm32mp1 pin-index

---

bsp/nrf5x/nrf52832/board/Kconfig
bsp/nrf5x/nrf52832/board/board.c
bsp/nrf5x/nrf52832/board/sdk_config.h

[
同步nrf52840相关修改到nrf52832中，在青风nrf52832中，测试了ble 相关sample，同时测试了RTC设备，可以正常工作
]

同步nrf52840相关修改到nrf52832中，测试了ble 相关sample，同时测试了RTC设备，可以正常工作

---

components/libc/compilers/common/unistd.c
components/libc/getline/README.md
components/libc/getline/posix_getline.c

[
将posix_getline.h termios.h 头文件包含从<>改为""以防止路径出现分歧
]

将posix_getline.h termios.h 头文件包含从<>改为""以防止路径出现分歧

---

components/libc/compilers/common/readme.md
components/net/lwip-1.4.1/src/arch/include/arch/cc.h
components/net/lwip-2.0.2/src/arch/include/arch/cc.h
components/net/lwip-2.1.2/src/arch/include/arch/cc.h
include/libc/libc_errno.h
include/libc/libc_fcntl.h
include/libc/libc_fdset.h
include/libc/libc_stat.h

[fix bug] #3902

---

components/finsh/msh_file.c

[
rm 命令不支持递归删除，不方便调试
增强 rm 命令，支持递归删除
qemu 验证
]

[msh] rm command supports recursive deletion of folders

---

src/timer.c

[
fix the software issue when the system timer thread pending. Fix the timer/software timer handling issue if the timeout function starts/stops/deletes this timer.
Passed with timer testcase under qemu/stm32f429.
]

[kernel] fix the timer issue

---

src/ipc.c

[
add semaphore values' overflow-check code in the function of rt_sem_release
] 

[fix bug] #3951

---

.github/PULL_REQUEST_TEMPLATE.md

fix some English grammar errors

---

bsp/stm32/stm32mp157a-st-discovery/applications/main.c
bsp/stm32/stm32mp157a-st-discovery/board/ports/OpenAMP/drv_openamp.c

[
允许用户动态切换 tshell 设备（串口和 OpenAMP），已在 stm32mp157-dk1 上测试完成。
]

[update] Dynamic change console

---

components/drivers/sensors/sensor.h
components/drivers/sensors/sensor_cmd.c

[1.Add sensor vendor MAXIM.
2.Fix: When printing sub-zero temperature, "-" is displayed after ".".]

Add sensor vendor MAXIM; Fix temp ptint error

---

src/ipc.c

[bug fixed] add mutex values' overflow-check code

---

src/thread.c

Fix the delay_until bug for calculation formula issue. Verification passed under qemu-veexpress-a9 bsp.

[Kernel] fix the delay_until issue

---

include/rtdef.h
src/ipc.c

[
这是最后一批增加溢出检查代码，修改多处，请确认无误后再合并
在rtdef.h中增加各ipc类型最大值宏定义 define maximum value of ipc type
]

[bug fixed] add mb mq value overflow-check code

---

bsp/stm32/stm32f103-blue-pill/board/CubeMX_Config/Inc/stm32f1xx_hal_conf.h
bsp/stm32/stm32f103-blue-pill/board/Kconfig

[
support RTC device.
have tested on the STM32F103 blue pill platform
]

[bsp][stm32][bluepill] support RTC

---

components/net/lwip-1.4.1/src/arch/include/arch/cc.h
components/net/lwip-2.0.2/src/arch/include/arch/cc.h
components/net/lwip-2.1.2/src/arch/include/arch/cc.h

[
resume the previous state of IAR structure which is located in cc.h file
]

[revert] [lwip] cc.h IAR structure

---

bsp/stm32/stm32mp157a-st-discovery/board/Kconfig
bsp/stm32/stm32mp157a-st-discovery/board/SConscript
bsp/stm32/stm32mp157a-st-discovery/board/ports/OpenAMP/drv_openamp.c
bsp/stm32/stm32mp157a-st-discovery/board/ports/drv_rcc.c
bsp/stm32/stm32mp157a-st-discovery/board/ports/drv_rs485.c
bsp/stm32/stm32mp157a-st-discovery/board/ports/drv_rs485.h

[
修改 openamp 代码，增加判断 console 是否默认为 openamp；添加 RS485 驱动代码；修改 RCC 例程，解决与 A7 IP 冲突。
所有改动，均已在 MP157-DK1 上测试通过。
]

[update] openamp driver and add rs485 driver

---

libcpu/risc-v/SConscript

[
统一了 libcpu\risc-v\SConscript 里的判断逻辑。
本地编译正常。
]

[libcpu][risc-v] Fixed bsp k210 failing to compile | 修复 k210 无法编译的问题。

---

components/drivers/include/drivers/alarm.h
components/drivers/rtc/alarm.c

[
update alarm component, add alarm flags:
#define RT_ALARM_HOUR          0x1000 /* alarm each hour at a certain min:second */
#define RT_ALARM_MINUTE        0x2000 /* alarm each minute at a certain second */
#define RT_ALARM_SECOND        0x4000 /* alarm each second */
alarm can set and repeated by hour or minute or second.
]

add alarm flags, alarm can repeated by hour minute and second

---

src/kservice.c

[
测试环境：当在程序中使用接口 `rt_console_set_device` 动态切换 device 时，如果新设备 name 与旧设备的 name 相同时，会导致 Finsh 线程挂掉。
修改方法：加入对设备的判断，用户无法重复设置同一设备。
验证环境：已在 STM32MP157-DK1 开发板上测试完成。
]

[update] check whether it's a same console device.

---

bsp/nrf5x/libraries/drivers/drv_spi.c

[
修复了bsp/nrf5x SPI 驱动
已在nrf52840-DK开发板上测试完成，可以挂载文件系统
]

[bsp/nrf5x]fixed spi driver bugs

---

components/drivers/usb/usbhost/class/udisk.c
components/drivers/usb/usbhost/core/hub.c

[
1. Limit >4 USB ports hubs.
2. Double free intf.
3. dname buffer size is too small.
4. Reset child pointer after detaching instance.
]

Fix USB host core bugs.

---

components/libc/compilers/armlibc/README.md
components/libc/compilers/common/readme.md
components/libc/compilers/dlib/README.md
components/libc/compilers/newlib/README.md

[
add readme for dlib armlib newlib
]

[libc]  add readmes
