bsp/stm32/libraries/HAL_Drivers/drv_eth.c
bsp/stm32/stm32mp157a-st-discovery/board/ports/drv_eth.c
bsp/stm32/stm32mp157a-st-discovery/board/ports/drv_eth.h
bsp/stm32/stm32mp157a-st-ev1/board/ports/eth/drv_eth.c
bsp/stm32/stm32mp157a-st-ev1/board/ports/eth/drv_eth.h
components/drivers/include/drivers/phy.h
components/drivers/phy/phy.c

https://github.com/RT-Thread/rt-thread/issues/6021
https://github.com/RT-Thread/rt-thread/issues/5700
报告
将枚举体转为宏定义的方式，通过#undef来防止冲突，.c内部使用自己重定义的PHY_FULL_DUPLEX 
冲突的问题目前只发生在stm32身上，因为stm32 的PHY_FULL_DUPLEX 使用的是自己定义的一套，没有用phy框架的

[phy] fix the PHY_FULL_DUPLEX conflicts

---

components/libc/compilers/common/cstdlib.c
components/libc/posix/pthreads/pthread.c
include/rtdef.h
src/thread.c

[
* was tested base on qemu-a9
]

[fix] the risk for function exit() when open pthread support.

---

libcpu/arm/cortex-m3/cpuport.c
libcpu/arm/cortex-m4/cpuport.c
libcpu/arm/cortex-m7/cpuport.c

[
当 armclang 开启 LTO 时，`__rt_ffs()`  会被内联，导致不一定会从 `r0` 中获取返回值。当在 C 语言中嵌入汇编时，应使用 `%[value]` 进行输入和输出操作数的替换。
]

Fix armclang error when enable LTO

---

bsp/imxrt/imxrt1060-nxp-evk/board/Kconfig
bsp/imxrt/imxrt1060-nxp-evk/board/linker_scripts/link.lds

GUI比赛中报告
this is reported in slack group:
- I had to do a small fix in board/linker_scripts/link.lds file.
line 81, should be:
ivt_begin = ORIGIN(m_boot_data) + LENGTH(m_boot_data);
(add a space between ivt_begin and "=“).
- For unknown reason I had to set DEMO_PANEL_RK043FN66HS as default in imxrt1060-nxp-evk/board/Kconfig
Leaving the DEMO_PANEL_RK043FN02H was not working even after selecting RK043FN66HS in menuconfig. The result was touch not working without this change as a wrong driver was being pick.
[ …

[imxrt1060] fix tiny problems

---

bsp/imxrt/libraries/drivers/drv_gpio.c

report in #4184
NXP 官方提交 代转： https://gitee.com/xinyigao/rt-thread-1170/commit/0a4928339186c5b04601a64ff3488148e4c8d4c4
[
]
The following content must not be …

[imxrt] fix gpio interrupt bug in drv_gpio.c

---

components/drivers/can/can.c

[
- in _can_int_tx if can driver sendmsg do not return RT_EOK,
it will repeat until sendmsg return RT_EOK
- if error occur on can bus(wire broken or EMI), all threads that
have lower priority will not be executed
- we should let application layer to determine if resend is appropriate
when send fail, besides in data link layer, can already implemented
auto resend in hardware
- CAN总线产生错误，或者短线的情况下，_can_int_tx 会陷入无限循环
- 通常 CAN 发送线程的优先级会比较高，比如为了实时控制电机，这样就会导致比它优先级低的所有线程得不到执行
- CAN 总线消息重发应交给应用层执行，底层数据链路层有自动重发，在驱动中再加一个自动重发没有必要
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and …

[DeviceDriver] Fix can infinite loop when can driver send error

---

bsp/imxrt/imxrt1052-fire-pro/board/linker_scripts/link.lds
bsp/imxrt/imxrt1064-nxp-evk/board/linker_scripts/link.lds
bsp/imxrt/libraries/MIMXRT1050/MIMXRT1052/gcc/MIMXRT1052xxxxx_flexspi_nor.ld
bsp/imxrt/libraries/MIMXRT1050/MIMXRT1052/gcc/MIMXRT1052xxxxx_flexspi_nor_sdram.ld
bsp/imxrt/libraries/MIMXRT1064/MIMXRT1064/gcc/MIMXRT1064xxxxx_flexspi_nor.ld
bsp/imxrt/libraries/MIMXRT1064/MIMXRT1064/gcc/MIMXRT1064xxxxx_flexspi_nor_sdram.ld
bsp/imxrt/libraries/templates/imxrt1050xxx/board/linker_scripts/link.lds
bsp/imxrt/libraries/templates/imxrt1064xxx/board/linker_scripts/link.lds

[nxp][link script] format issue

---

components/libc/compilers/armlibc/syscalls.c

该问题在Keil-MDK中没有一个太好的解决方案。本PR为权衡利弊之后得到的一套解决方案。Keil曾经提供了底层桩函数_sys_ensure，但是目前已经被废弃。因此唯一的解决方案就是每写完一句，就调用fsync去同步一次。
该问题在mbedos社区也进行过讨论，他们也面临和我们相同的两个问题：
1. Keil-MDK无有效的fflush解决方案，mbedos依然在使用淘汰的_sys_ensure桩函数。
2. Keil-MDK没有fileno函数，我方少部分软件包因此而无法使用Keil平台编译。
参考：https://github.com/ARMmbed/mbed-os/issues/1601
issue: https://github.com/RT-Thread/rt-thread/issues/4928
经过进一步测试发现，Keil-MDK中的fflush函数已经退化成服务于STDOUT的函数，Keil-MDK内部有一个buffer可以存放fputc(stdout) 发过来的数据，如果调用fflush，这些数据是可以flush出去的。但是如果是真正的文件数据，fflush函数并没有提供任何桩函数接口可以让文件flush数据出去。
[ …

[armlibc] 解决fflush失效的问题

---

bsp/Vango/v85xxp/drivers/board.h
bsp/imxrt/imxrt1021-nxp-evk/board/board.h
bsp/microchip/samc21/board/board.c
bsp/microchip/samc21/board/board.h
bsp/microchip/same54/board/board.c
bsp/microchip/same54/board/board.h
bsp/microchip/same70/board/board.c
bsp/microchip/same70/board/board.h
bsp/microchip/saml10/board/board.c
bsp/microchip/saml10/board/board.h
bsp/wch/arm/ch579m/board/board.h

attach https://github.com/RT-Thread/rt-thread/pull/5451
[
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be …

[armclang] 使用__clang__代替__CLANG_ARM

---

src/kservice.c

[
```
rt_uint16_t old_flag = _console_device->open_flag;
_console_device->open_flag |= RT_DEVICE_FLAG_STREAM;
rt_device_write(_console_device, 0, str, rt_strlen(str));
_console_device->open_flag = old_flag;
```
当一个线程正在执行 rt_device_write(_console_device, 0, str, rt_strlen(str));函数时，一个高优先级线程抢占当前线程并修改 _console_device->open_flag（修改为RT_DEVICE_FLAG_INT_RX，之前不是中断接收），高优先级线程执行完后，继续执行以前线程，此时old_flag与_console_device->open_flag不一致，执行_console_device->open_flag = old_flag;后_console_device->open_flag新的值被覆盖。控制台串口实际配置成硬件中断接收，因为_console_device->open_flag值被修改为不是中断，最后导致控制台串口无法接收任何数据输入。
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted …

解决控制台无法输入bug

---

bsp/stm32/libraries/HAL_Drivers/drv_can.c

* 2021-02-02     YuZhe XU     fix bug in filter config
* 2021-8-25      SVCHAO       The baud rate is configured according to the different APB1 frequencies.
f4-series only.
这是其他人修复的bug，目前看起来没有合并到3.1 希望能合并。

其他人修改的Can 总线Bug 希望合并到长期支持版中。 

---

tools/keil.py

[keil.py] 修复生成Keil4/5工程文件时，头文件路径重复添加到工程的问题

---

src/thread.c

当 `rt_thread_sleep()` 的 `tick` 为 0 时线程不该被挂起，而是直接返回。

当tick为0时rt_thread_sleep不应该挂起线程

---

src/kservice.c

[
update rt_vsnprintf for compliance with ti c28x cpus.
]

[kservice][ti c28x]rt_vsnprintf

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
components/drivers/include/drivers/rt_drv_pwm.h
components/drivers/misc/rt_drv_pwm.c

[
原先PWM设备框架中是提供命令去设置PWM的互补输出的。如图：
所以，在框架中，建议使用提供好的命令去设置互补输出模式，而不是直接修改configuration.complementary的值。
当我们使用PWMN_CMD_ENABLE和PWMN_CMD_DISABLE命令的时候，代码没有返回值，而且这个swicth case语句没有break，那么会执行到 return RT_EINVAL 我们希望返回的是RT_EOK。
]

[rt_drv_pwm]完善PWM框架互补输出部分代码

---

src/kservice.c

[
增加printf格式2进制和8进制，RT_KPRINTF_USING_LONGLONG 和 RT_PRINTF_SPECIAL 做了相应处理
增加了%b支持2进制输出；
函数rt_inline int divide(long long *n, int base) 函数用变量base获取逐位字符；
函数static char *print_number 中 局部数组tmp[]做了相应的增加，SPECIAL选项对二进制做了处理，显示为0bxxxx
stm32h747-st-discovery bsp 测试通过
]

[kservice] 增加printf格式2进制和8进制，RT_KPRINTF_USING_LONGLONG 和 RT_PRINTF_SPECIAL 做了相应处理

---

libcpu/arm/arm926/trap.c

[
arm926设备在异常时打印栈名称为乱码
在nuc980-mcu板卡上进行了测试
]

fix: 修复arm926异常时打印栈名乱码

---

bsp/wch/risc-v/ch32v307v-r1/board/Kconfig

[
解决了ch32v307使用ENV工具中  Hardware Drivers Config → On-chip Peripheral Drivers 中usart配置只有usart1开关的问题，添加了usart2-usart8
但是由于drv_usart.c的时钟配置bug并未修改，故即使开启了usart2-usart8，usart2-usart8仍不可正常使用
已使用env工具测试
]

Ch32 v307 kconfig fix

---

bsp/nuvoton/libraries/nuc980/rtt_port/drv_uart.c

[
(bsp-nuv980)
如果串口未使用pdma，而关闭串口时不应该关闭pdma，pdma通道默认值为0，而其他设备可能正在使用pdma通道0。
在 nuv980-mcu上进行了测试
]

fix: (nuv980)修复关闭串口时意外关闭其他设备正在使用的pdma

---

bsp/nuvoton/libraries/nu_packages/Demo/slcd_show_tick.c
bsp/simulator/drivers/SConscript
components/legacy/rtlegacy.h
components/net/sal/src/sal_socket.c
include/rtdef.h
src/kservice.c
tools/building.py

https://github.com/RT-Thread/rt-thread/discussions/6224#discussioncomment-3326523
版本控制规范：https://semver.org/
目前的版本子号不是很规范，其中RT_VERSION甚至和VS那边造成了冲突
```c
/* RT-Thread version information */
#define RT_VERSION                      4L              /**< major version number */
#define RT_SUBVERSION                   1L              /**< minor version number */
#define RT_REVISION                     1L              /**< revise version number */
```
建议改成：
```c
/* Major version number (X.x.x) */
#define RT_VERSION_MAJOR   5
/* Minor version number (x.X.x) */
#define RT_VERSION_MINOR   0
/* Patch version number (x.x.X) */
#define RT_VERSION_PATCH   0
```
老版本版本宏放在legacy中，以保持对老版本的兼容
The following content must …

[kernel][version] 采用新的版本宏定义

---

bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/pins_arduino.c

[
关于SWD和JTAG调试选择，其实CubeMX已经做了处理，我们不用重复的在实现了！
我们在CubeMX配置的时候，需要选择调试方式，这时候CubeMX会根据我们的选择，自动生成SWD和JTAG调试选择的代码。为了不干扰用户，建议还是将本段代码删除。
]

[stm32][RTduino]删除一些不必要的代码

---

tools/building.py

…fixed link order.
**Reason for submission:**
The map file, BIN file, and link order generated by RT-Thread Scons compiled from the same source code are different.
This introduces uncontrollable variables for embedded debugging to trace back the source code from the lr or pc register address.
Experiments show that the BIN files generated by different link sequences are different,
and their operating phenomena are also different.
Running differences in BIN files are easy to observe on some software versions, but not so easy on others.
We have encountered such situations in our practice:
(1) Some versions of the software work fine (and seem to work fine) in all linking orders,
(2) while some versions of the software work fine in some link sequences and stuck in others.
Random link order …

[tools/link-order] Sort objects so that compilation can be done in a fixed link order.

---

components/utilities/ymodem/ry_sy.c

[
为什么提交这份PR:
Ymodem的msh命令ry希望添加能自定义保存路径选项
解决的问题是什么：
Ymodem组件的MSH命令ry实现可以自定义路径的选项。
你的解决方案是什么：
按照sy函数的实现，对ry实现的相关函数进行改造。
1.ry命令第二个参数改为file_path路径，第三个为设备号。
2.在rym_download_file函数使得ctx->fpath参数为msh中填写的保存路径。
3.在_rym_recv_begin函数中判断ctx->fpath字符串结束符，以便拼接路径与文件名。
确认并列出已经在什么情况或板卡上进行了测试：
在RTTV4.1.0操作系统上使用Ymodem组件。
硬件为STM32F429IGT6野火挑战者核心板。
使用USART3串口作为控制台设备进行Ymodem接收发送。
在W25Q128使用elm-fatfs文件系统，使用ROMFS系统挂载目录。
使用MSH命令 ry /flash uart3测试接收成功。
] …

修改Ymodem组件中MSH的ry命令，已便于自定义保存路径

---

bsp/stm32/libraries/HAL_Drivers/drv_usart.c
bsp/stm32/libraries/HAL_Drivers/drv_usart.h

[
原有的DMA接收逻辑不是很清晰，我按照V2的代码进行了简化。已经在stm32427和405上进行了测试，功能正常。
]

[bsp/stm32] 简化drv_usart中的DMA接收逻辑

---

bsp/stm32/libraries/HAL_Drivers/drv_rtc.c

转移自：https://gitee.com/rtthread/rt-thread/pulls/567
[
bsp\stm32\libraries\HAL_Drivers\drv_rtc.c在STM32F10x上有一个“RTC首次上电时BKP时钟没使能”的问题。
STM32F10x要求：
写RTC Domain and RTC registers之前需要__HAL_RCC_BKP_CLK_ENABLE（详见：stm32f1xx_hal_rtc.c里面的##### Backup Domain Access #####）
问题分析：
1、RTC首次上电时：由于HAL_RTC_Init初始化之前没有使能BKP时钟，所以对RTC registers的初始化无效。 2、然后用date命令设置时间，调用到set_rtc_time_stamp也没有__HAL_RCC_BKP_CLK_ENABLE，所以HAL_RTCEx_BKUPWrite写的值无法真正永存于BKP，重启后就丢失。 最终导致：对于RTC首次上电的情况，每次重启后RTC_BKP_DR1里的值都不是BKUP_REG_DATA，导致永远无法调用到rt_rtc_f1_bkp_update()去使能BKP时钟。
解决办法：
参考STM32F10x_StdPeriph_Lib_V3.5.0\Project\STM32F10x_StdPeriph_Examples\RTC\Calendar\main.c里面的RTC_Configuration()同时打开RCC_APB1Periph_PWR和RCC_APB1Periph_BKP
]
The following …

RTC STM32F1 Enable PWR and BKP clocks in the same time

---

components/utilities/ulog/backend/console_be.c
src/mem.c

[
ulog console 后端在输出日志时，会修改设备的 `open_flag`，多线程并发的情况下，会导致 `open_flag` 被改成意外的值。从而导致终端无法输入。
目前 `RT_DEVICE_FLAG_STREAM` 标志都会有，不需要额外处理。即使没有这个标记，也只是显示上的问题，不会导致功能上的问题。额外添加这个标志，弊大于利
]

修复低概率终端无法输入问题

---

tools/menuconfig.py

[
修复 pyconfig 运行错误
当前 pyconfig 强制依赖 `ENV_ROOT` 环境变量，使用 `ENV_ROOT` 来设置 `PKGS_ROOT` 环境变量。当 `ENV_ROOT` 环境变量没有设置时，就会抛异常。
在某些工程中，不需要通过 `PKGS_ROOT` 获取软件包的根路径，也就不依赖  `ENV_ROOT` 环境变量
此改动之后，如果 Kconfig 中依赖  `PKGS_ROOT` 环境变量，则会打印如下日志，提示用户
```
Kconfig:19: 'packages/Kconfig' not found (in 'source "$PKGS_DIR/Kconfig"'). Check that environment variables are set correctly (e.g. $srctree, which is unset or blank). Also note that unset environment variables expand to the empty string.
```
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no …

[menuconfig] Fix pyconfig running errors

---

.github/workflows/action.yml
.github/workflows/action_tools.yml
.github/workflows/action_utest.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

tools/building.py

User choice IDE build, after GenTargetProject there's no need to do the rest. 并且，既然用户指定了IDE，接下来的命令行编译却仍然是使用arm-none-eabi-gcc，为什么不是用IDE的编译器呢？（也许是个bug）
以下是旧的编译过程：
> $ scons --target=iar --verbose
> scons: Reading SConscript files ...
> IAR Version: 9.30.1.335
> scons: done reading SConscript files.
> scons: Building targets ...
> scons: building associated VariantDir targets: build
> arm-none-eabi-gcc -o build\applications\main.o -c -mcpu=cortex-m3 -mthumb ...
通过 --verbose 可以看到，生成完 IAR 工程后，还进行了编译，且编译器用的是 GCC ，而不是 IAR 。
加上 need_exit 后， rtconfig.py 里面的IDE部分就可以写的很简单了（不用再关心那些 CFLAGS AFLAGS LFLAGS 等），如下：
> ...
> elif PLATFORM == 'iccarm':
>     EXEC_PATH = EXEC_PATH + '/arm/bin/'

build: EndBuilding need_exit after GenTargetProject

---

bsp/wch/risc-v/ch32v307v-r1/board/Kconfig

[
修改KCONFIG文件，使在menuconfig中更美观
]

[bsp][ch32v307] 修改部分菜单

---

bsp/stm32/stm32mp157a-st-discovery/board/ports/OpenAMP/drv_openamp.c
bsp/stm32/stm32mp157a-st-ev1/board/ports/OpenAMP/drv_openamp.c

[
- Solved problem:
- Fix string comparison method in bsp stm32mp157a-st-discovery and stm32mp157a-st-ev1.
- Methods:
- Replaced the `"str1" == "str2"` to `rt_strcmp("str1", "str2") == 0`.
- In the original method, compiler optimizations may make str1 and str2 refer to the same address.
But the C standard does not mandate this behavior.
- Refer to PR#6437. Using the `rt_strcmp` method
- Test environment:
- pass the `scons` build.
- but sadly I don't have the development board to test the modification.
]
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by …

Fix string comparison method

---

bsp/stm32/libraries/HAL_Drivers/drv_pulse_encoder.c

[
问题：
正交编码器从 0 反方向转动时跳变到 0x7fff，驱动预期变为负数
原因：
stm32 bsp pulse encoder 中未开启定时器更新中断导致驱动中的溢出处理不生效
解决方案：
添加定时器溢出中断使能
测试：
stm32f103rc 测试霍尔正交编码器读数，测试通过
]

FIX: [bsp][stm32] pulse_encoder driver did not handle TIM overflow

---

src/object.c

[
The RT_ASSERT(obj != object) line is only compiled for debug mode. But the rt_enter/exit_critical causes the compiler not to optimize at least these 2 calls, even if it could optimize out the whole loop, because the rt_list_entry function has no side effect, and RT_ASSET is a no-operation in release mode. So this patch fixes this:
- no warnings anymore
- better speed in release mode
Tested with the CH32V307V-R1-1v0 development board.
] …

remove unused code to improve speed

---

components/dfs/src/dfs_posix.c

[
1 lseek()函数中，当seek到文件的位置和当前位置相同时，不需要调用dfs_file_lseek()函数，直接返回当前位置即可。
2 同时，以lseek(fd,0,SEEK_CUR)的方式执行函数可以返回文件当前读去位置，可以实现ftell()的功能.
]

lseek()函数中，当seek到文件的位置和当前位置相同时，不需要调用dfs_file_lseek()函数，直接返回当前位置即可。

---

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript
bsp/wch/risc-v/Libraries/ch32_drivers/drv_hwtimer.c
bsp/wch/risc-v/Libraries/ch32_drivers/drv_hwtimer.h
bsp/wch/risc-v/ch32v307v-r1/board/Kconfig

[
新增CH32V307的硬件定时器功能，并在CH32V307V-R1-1V0板卡上进行了测试。
]

新增CH32V307的硬件定时器功能

---

bsp/stm32/libraries/HAL_Drivers/drv_usart.c

修复RX DMA 第一包收不到的bug
[
出现的问题: 
使用RT框架串口DMA接收的时候,如果上位机发送的第一包大小超过缓冲区大小(设置的NDRT寄存器大小,或者说是buffsize大小),则会丢失一整个包(包长为buffsize)。
定位问题:
问题被定位到,是[uart->dma_rx.remaining_cnt]参数初始化的值不对, 导致第一次DMA半接受中断没有做事情, 等待DMA满中断过来的时候[因为是串口循环],数据已经被覆盖了.
解决方案:
正确初始化[uart->dma_rx.remaining_cnt]为(buffsize)的值.
测试:
已经在STMF405的板卡进行测试了,可以正确接受第一包.
]

修复  RTT 串口DMA接受 开头丢失一整包的问题

---

components/net/lwip/port/lwipopts.h

修正当有 TCP 连接未断开时，重新 PPP 拨号导致的断言错误

[net/lwip] Fix ppp retry assert error when tcp is connect.

---

bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
bsp/stm32/libraries/HAL_Drivers/drv_spi.c

[
将驱动文件中判断RT_USING_XXX改为BSP_USING_XXX,解决了部分框架层与驱动层的混用，仅在stm32f429-fire-challenger上进行测试
]

[bsp]将驱动文件中判断RT_USING_XXX改为BSP_USING_XXX,解决了部分框架层与驱动层的混用

---

examples/utest/testcases/kernel/thread_tc.c

Signed-off-by: fan.ji <fan.ji@weiheng-tech.com>
[
a counter in test_thread_yield  is not reset to zero.
if we run test_thread_yield in utest framework for multiple times, uassert_true(thread5_source == 10) will case a fail, but this is wrong.
I have already tested it on a stm32f103rct6 core board and this finally fix the problem.
]
我在这个拉取/合并请求中已经考虑了 As part of …

fix test_thread_yield fail bug in multiple utest loop case.

---

bsp/stm32/libraries/HAL_Drivers/config/f0/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f1/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f2/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f3/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f4/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f7/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/g0/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/g4/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/h7/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/l1/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/l4/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/l5/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/mp1/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/u5/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/wb/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

[
在使用stm32的pwm驱动时，发现其初始化channel的时候是根据device->channel这个值去初始化的，device->channel这个值是在pwm_configh.h里面定义设置的，又根据rtt的pwm例程，和常规习惯，应该大多数人会更喜欢设置channel=1/2/3/4，而不是在pwm_configh.h中将channel设置为TIM_CHANNEL_1/2/3/4，因此建议drv_pwm.c做出PR中的修改。
在实际开发中，因pwm_configh.h的示例均是.channel=0，又没有做出解释说明要让.channel=TIM_CHANNEL_1/2/3/4的值，容易误操作导致没有成功输出PWM，这是我在实际开发中遇到的现实问题，因而提出此建议。
]

提交stm32 bsp drv_pwm.c里面的一个小建议

---

bsp/stm32/libraries/HAL_Drivers/config/f0/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f1/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f2/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f3/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f4/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f7/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/g0/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/g4/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/h7/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/l1/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/l4/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/l5/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/mp1/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/u5/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/wb/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

Reverts RT-Thread/rt-thread#6517

Revert "提交stm32 bsp drv_pwm.c里面的一个小建议"

---

bsp/stm32/libraries/HAL_Drivers/config/f0/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f1/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f2/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f3/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f4/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/f7/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/g0/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/g4/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/h7/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/l1/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/l4/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/l5/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/mp1/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/u5/pwm_config.h
bsp/stm32/libraries/HAL_Drivers/config/wb/pwm_config.h

[
删除pwm_config.h中对pwm_config的判断，并初始化channel 为RT_NULL，仅仅测试语法无错误，未进行编译测试
]

[bsp]  修改了stm32中pwm的部分选择编译选项，并使pwm channel初始化为RT_NULL

---

bsp/stm32/libraries/HAL_Drivers/config/f4/dma_config.h
bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c

Modified   bsp/stm32/libraries/HAL_Drivers/config/f4/dma_config.h
Modified   bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c
修复f4的dma配置，修改v2串口驱动dma接收不响应半满和全满
[
解决的问题：
串口接收数据错误，应用层接收的数据被截断成两个。
解决方案：
按照stm32f4的数据手册修改dma_config.h，drv_usart_v2.c中stm32_uart_get_config添加缺失的串口，屏蔽dma接收的半满和全满的处理，不然应用层触发时那一帧数据会被截取成两段。
测试环境：
f429系列的开发板
]

Modified   bsp/stm32/libraries/HAL_Drivers/config/f4/dma_config.h

---

components/drivers/sdio/block_dev.c

■bug现象
SD卡快速抽拔，导致死机.
■bug原因
①  插入SD卡，检卡流程: init_sd->rt_mmcsd_blk_probe .
②  检卡执行流到rt_mmcsd_blk_probe 时突然拔卡的话，可能会导致rt_mmcsd_blk_probe 中的rt_mmcsd_req_blk 函数执行失败（read mmcsd first sector failed）。
③ rt_mmcsd_blk_probe 出错后，会 goto 到 remove_card分支，  调用rt_mmcsd_blk_remove函数释放块设备.
④ rt_mmcsd_blk_remove会释放 挂载 card->blk_devices上的块设备，但是由于 ②步骤中读取分区失败，所以 card->blk_devices没有挂任何设备，导致之后的处理出现问题(for循环刚开始 l 变量被赋值为null)。
■解决方法
在rt_mmcsd_blk_remove函数刚开始的地方判断 card->blk_devices 是否为空表, 如果为空，则直接返回

[components/sdio] bugfix: remove sdcard block dev may cause a infinite loop.

---

components/dfs/src/dfs.c

[
最近发现，使用 [rt_kprintf_threadsafe](https://packages.rt-thread.org/detail.html?package=rt_kprintf_threadsafe)
软件包后, 无法 List_fd, 检查后发现，是由于 list_fd 使用了 `rt_enter_critical` 做临界区保护，导致无法使用 mutex.
仔细检查后，发现list_fd 过程中唯一使用到的共享资源是 `fd_table`, 而在其它读写 fd_table 的位置均使用了 `dfs_lock`,
所以，个人认为此处使用 dfs_lock 就足够了。一点个人见解, 如有错误，还望见谅, 谢谢哈 :)
]

proposal: `replace `rt_enter_critical` with `dfs_lock` for list_fd

---

bsp/stm32/libraries/HAL_Drivers/drv_usbd.c
components/drivers/usb/usbdevice/class/cdc_vcom.c

Modified   bsp/stm32/libraries/HAL_Drivers/drv_usbd.c
Modified   components/drivers/usb/usbdevice/class/cdc_vcom.c
修复cdc在v1v2的serial框架下接收发送错误的问题.stm32下usbd添加更多的ep_id,以支持复合设备.
[
问题: 我使用cdc设备接管finsh,但是无法正确工作.修复了cdc的问题后,复合设备也出问题,pc无法识别.
解决方案:修复cdc的接收发送问题,给drv_usbd.c,增加更多的ep_id
测试环境:stm32f103cbt6
]

修复cdc在v1v2的serial框架下接收发送错误的问题.stm32下usbd添加更多的ep_id,以支持复合设备.

---

src/object.c

Reverts RT-Thread/rt-thread#6605
目前的解决方案不彻底，重新讨论一种新的解决方案可以完美解决此问题。

Revert "[kernel] 修正复制name字段时潜在的内存踩踏问题"

---

bsp/nrf5x/nrf52832/board/Kconfig

Signed-off-by: supperthomas <78900636@qq.com>
[
CI 检测出编译有问题
参考nrf52840 kconfig
手动编译ok
]

[bsp/nrf5x] Fix the Kconfig of nrf52832

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

[
- STM32的PWM驱动无法输出占空比100%，即高电平
- 当CCR=CNT时，导致电平拉低，输出高电平失败。
- 如这里分析所示 https://club.rt-thread.org/ask/question/e3883b5ac8310051.html
- 修改为判断脉宽大于等于周期时，即默认用户需要使用高电平，输出占空比100%时，让CCR>ARR，输出高电平。
- STM32F429
- RTT 5.0.0
- 使用PWM驱动
]

[fix][stm32]修复输出高电平异常的问题

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

[
解决 tim_clock_get 函数中关于不同stm32芯片的tim时钟配置相关代码。
未修改代码前：
我在编译stm32l431系列的芯片的时候，报了以下错误：
就是说目前的这种实现方式太笼统了，这里的stm32l431系列单片机其实是没有TIM17的，所以这个TIM17这个宏定义根本不存在。
发现这段代码也就是判断TIM是在APB1，还是APB2外设总线上。
原先的方法是根据芯片的系列去判断，但是这里就出现了一个问题，子系列可能会有所不同，就比如我上面出现的那个问题，这里我建议通过库文件的外设宏定义去做判断会更好！
在stm32的库文件中，一般来说大部分外设都是挂在APBx总线上的，比如定时器，我们直接根据内存映射去处理，因为无论如何定时器总会在这两条总线上，考虑到部分系列单片机只有一条APB总线，所以我做了区分。
基本所有系列单片机的库文件都有这样的宏定义。
比如这样，我们直接根据内存映射，就可以知道TIM5，TIM9到底在哪个总线上了。
]

[BSP][STM32]修改PWM驱动APBx外设时钟选择方案

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c

[
STM32使用PWM驱动时，使用不可配置主从定时器模式的定时器配置PWM模式时，将触发HAL库的断言
添加判断当前使用定时器是否可配置为主从定时器模式
- stm32f429
-  使用TIM14 通道1
]

[fix][stm32]添加判断当前使用定时器是否可配置为主从定时器模式

---

components/finsh/cmd.c

[
list_mutex 显示挂起线程
]
```
msh />list_mutex
mutex      owner  hold priority suspend thread
-------- -------- ---- -------- --------------
lock     main     0001       20  0001 hello
fat0     (NULL)   0000      255  0000
sal_lock (NULL)   0000      255  0000
sd_bus_l (NULL)   0000      255  0000
mu0      (NULL)   0000      255  0000
fslock   (NULL)   0000      255  0000
heap     (NULL)   0000      255  0000
msh />
```
我在这个拉取/合并请求中已经考虑了 As …

[shell]list_mutex show suspended Threads

---

bsp/stm32/libraries/HAL_Drivers/drv_spi.c

* H7下SPI时钟不再为外设总线时钟频率
* H7和F7下DMA驱动需要进行CacheLine对齐
* 打印SPI时钟配置信息进行修改
[
在H7芯片下修复时钟频率获取错误问题并添加DMA驱动
- H7下SPI时钟不再为外设总线时钟频率
- 里面我进行了说明
> https://github.com/RT-Thread/rt-thread/pull/6698#issuecomment-1350548069
其中调用HAL SPI_Init是因为CUBEMX生成的对于SPI的时钟配置放在HAL SPI_Init里.如果不先调用一遍,获取的时钟频率是错误的.
单独为H7编写查询代码
- H7和F7下DMA驱动需要进行CacheLine对齐
- 根据如下帖子
> https://club.rt-thread.org/ask/question/b5049fff129ff608.html
单独为H7和F7编写DMA驱动
- 打印SPI时钟配置信息进行修改
可以打印出实际的SPI时钟频率
- ART-PI
- SPI FLASH W25Q128
- 具体测试情况
> https://club.rt-thread.org/ask/question/67709922b1d2022b.html
]

[STM32][SPI]在H7芯片下修复时钟频率获取错误问题并添加DMA驱动

---

components/drivers/spi/sfud/src/sfud.c

[
qspi模式下，单线操作时，命令为SFUD_CMD_READ_DATA，在大容量设备，即四地址模式的读命令是0x13；
在新平台中验证通过（不方便介绍型号）
]

fix(sfud.c):qspi_set_read_cmd_format三字节读命令0x03，四字节读命令0x13，当命令为0x03需要加上0x10

---

bsp/stm32/libraries/HAL_Drivers/drv_spi.c

[STM32][SPI]使用rt_hw_cpu_dcache_ops函数替换HAL库函数

---

components/libc/compilers/common/cstring.c

问题：在rv32下编译时cstring.c中的strtok_r函数与libc.a中的strtok_r重定义
修改：在strtok_r前添加rt_weak
工具链：riscv32-unknown-elf-gcc.exe
工具链本地相对路径：RT-ThreadStudio\repo\Extract\ToolChain_Support_Packages\RISC-V\RISC-V-GCC-RV32\2022-04-12\bin
libc.a相对路径:RT-ThreadStudio\repo\Extract\ToolChain_Support_Packages\RISC-V\RISC-V-GCC-RV32\2022-04-12\riscv32-unknown-elf\lib

[components][libc] 在rv32下编译时cstring.c中的strtok_r函数与libc.a中的strtok_r重定义

---

libcpu/risc-v/ch32v1/cpuport.c

[
对接了rt_hw_context_switch_interruptC(rt_ubase_t from, rt_ubase_t to, rt_thread_t from_thread, rt_thread_t to_thread)接口，使得ch32v103能够成功编译，已经测试，能够成功编译。
]

[ch32]对接了rt_hw_context_switch_interrupt接口

---

bsp/stm32/libraries/HAL_Drivers/drv_adc.c

* 添加16位与14位分辨率配置
* 添加内部参考电压与温度,电池电压通道配置
[
- 更改配置通道与校准函数顺序
在使能函数中配置通道更为合适
- 添加16位与14位分辨率配置
H7芯片支持16位与14位分辨率
- 添加内部参考电压与温度,电池电压通道配置
在H7芯片中,使用17~19通道去读取上述信息值错误.
需要单独配置通道,才可读取正常
- 进行修改
- ART-PI H750
- 测试代码如下
```c
#include <main.h>
#define ADC_DEV_NAME        "adc3"      /* ADC 设备名称 */
#define ADC_VREF_CHANNEL     ADC_CHANNEL_VREFINT - ADC_CHANNEL_0    /* ADC Vref 通道 */
#define ADC_TEMP_CHANNEL     ADC_CHANNEL_TEMPSENSOR - ADC_CHANNEL_0 /* ADC Temp 通道 */
static int adc_vol_sample(void)
{
rt_uint32_t vref_value,temp_value;
rt_uint16_t vref_mv,temp_mv; 
rt_adc_device_t adc_dev;
rt_err_t ret = RT_EOK;
/* 查找设备 */
adc_dev = (rt_adc_device_t)rt_device_find(ADC_DEV_NAME);
if (adc_dev == RT_NULL)
{
rt_kprintf("adc sample run failed! can't find %s device!\n", …
```

[stm32][adc]更改配置通道与校准函数顺序

---

components/drivers/serial/serial_v2.c

[
- 修复DMA+TX阻塞模式异常
- 使用例程代码去配,运行错误
> https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/programming-manual/device/uart/uart_v2/uart?id=%e4%b8%b2%e5%8f%a3%e8%ae%be%e5%a4%87%e4%bd%bf%e7%94%a8%e7%a4%ba%e4%be%8b
```shell
msh />uart_dma_sample
.................................................................................
固件名称：rt-thread，硬件版本号：1.0，软件版本号：1.0
在线程(tshell)中发生错误异常
发生总线错误，原因：不精确的数据总线错误
```
- 应该说我运气比较差吧,malloc分配的空间刚好是被用完的.....
- 正常来说分配的是空的空间的话,就不会有问题
- 初始化时进入rt_serial_tx_enable函数
1.在If not use RT_SERIAL_TX_BLOCKING_BUFFER判断中未对tx_fifo->rb进行清零.
2.导致tx_fifo->rb.buffer_ptr不为空指针
- 在串口发送时,进入rt_serial_write函数,tx_fifo->rb.buffer_ptr不为空指针,导致进入_serial_fifo_tx_blocking_buf函数
- 按照DMA+TX阻塞方式来说,应该进入nbuf函数的
- 从而发生错误,不发生错误也无法正常串口发送
- 清零rb空间 …

[drivers][serial_v2]修复DMA+TX阻塞模式异常

---

bsp/stm32/libraries/HAL_Drivers/drv_spi.c
bsp/stm32/libraries/HAL_Drivers/drv_spi.h
components/drivers/Kconfig
components/drivers/include/drivers/spi.h
components/drivers/spi/spi_core.c

[STM32][SPI]解决挂载函数里面不同bsp对uaer_data的滥用

---

bsp/lpc55sxx/Libraries/drivers/drv_spi.c

fix the syntax error of drv_spi.c in lpc55sxx.

---

bsp/stm32/stm32f411-st-nucleo/rtconfig.py
tools/building.py
tools/options.py

[
此PR意图在脚本中增加 scons --strict命令，使用该命令编译工程时，会自动将CFLAGS CXXFLAGS设置为 Werrors，即较为严格的编译模式，任何警告都会当做错误来处理。
该命令主要用于CI，在CI执行bsp编译时，可以使用 scons --strict命令。现在QEMU的rtconfig.py 为了CI检查，直接将CFLAGS加上了Werrors，导致正常编译过程中也把警告当做了错误，对日常使用该bsp造成了影响。
]

[env] add scons --strict

---

bsp/stm32/libraries/HAL_Drivers/drv_spi.c
bsp/stm32/libraries/HAL_Drivers/drv_spi.h
bsp/stm32/stm32f103-100ask-pro/board/ports/spi_flash_init.c
bsp/stm32/stm32f103-atk-nano/board/ports/spi_flash_init.c
bsp/stm32/stm32f103-dofly-M3S/applications/nrf24l01_init.c
bsp/stm32/stm32f103-dofly-M3S/board/ports/drv_sdcard.c
bsp/stm32/stm32f103-dofly-M3S/board/ports/spi_flash_init.c
bsp/stm32/stm32f103-fire-arbitrary/board/ports/spi_flash_init.c
bsp/stm32/stm32f103-fire-arbitrary/board/ports/w5500_device.c
bsp/stm32/stm32f103-hw100k-ibox/board/ports/w5500_device.c
bsp/stm32/stm32f407-armfly-v5/board/ports/spi_flash_init.c
bsp/stm32/stm32f407-atk-explorer/board/ports/spi_flash_init.c
bsp/stm32/stm32f411-atk-nano/board/ports/spi_flash_init.c
bsp/stm32/stm32f429-armfly-v6/board/ports/spi_flash_init.c
bsp/stm32/stm32f429-atk-apollo/board/ports/spi_flash_init.c
bsp/stm32/stm32f429-fire-challenger/board/ports/spi_flash_init.c
bsp/stm32/stm32h750-artpi/board/port/drv_spi_ili9488.c
bsp/stm32/stm32h750-artpi/board/port/spi_flash_init.c
bsp/stm32/stm32h750-weact-ministm32h7xx/board/port/drv_spi_flash.c
bsp/stm32/stm32l431-BearPi/board/ports/lcd/drv_lcd.c
bsp/stm32/stm32l475-atk-pandora/applications/nrf24l01_init.c
bsp/stm32/stm32l475-atk-pandora/board/ports/drv_filesystem.c
bsp/stm32/stm32l475-atk-pandora/board/ports/lcd/drv_lcd.c
bsp/stm32/stm32l496-ali-developer/board/ports/drv_spi_lcd.c
bsp/stm32/stm32mp157a-st-discovery/board/ports/spi_sample.c
bsp/stm32/stm32mp157a-st-ev1/board/ports/spi_sample.c
components/drivers/include/drivers/pin.h
components/drivers/include/drivers/spi.h
components/drivers/spi/spi_core.c

[stm32][spi] spi attach函数问题解决方案

---

include/rtservice.h

[
#6857
```
F:/development/rtos/rt-thread/include/rtservice.h:131: warning: Found unknown command '@pos'
F:/development/rtos/rt-thread/include/rtservice.h:132: warning: Found unknown command '@head'
F:/development/rtos/rt-thread/include/rtservice.h:139: warning: Found unknown command '@pos'
F:/development/rtos/rt-thread/include/rtservice.h:141: warning: Found unknown command '@head'
F:/development/rtos/rt-thread/include/rtservice.h:149: warning: Found unknown command '@pos'
F:/development/rtos/rt-thread/include/rtservice.h:150: warning: Found unknown command '@head'
F:/development/rtos/rt-thread/include/rtservice.h:151: warning: Found unknown command '@member'
F:/development/rtos/rt-thread/include/rtservice.h:160: warning: Found unknown command '@pos' …
```

[doxygen] Fix some comments in rtservice.h

---

components/drivers/ipc/workqueue.c

[
workqueue 用于中断得延后处理机制时，丢失中断频繁
减少临界区，提交重复work时，不需要检查判忙。
stm32l475潘多拉，测试代码及结果见下面评论
]

[workqueue] Reduce critical section, improve performance

---

components/lwp/arch/risc-v/rv64/lwp_gcc.S
components/lwp/lwp_user_mm.c
libcpu/risc-v/t-head/c906/stackframe.h
libcpu/risc-v/t-head/c906/trap.c
libcpu/risc-v/virt64/stackframe.h
libcpu/risc-v/virt64/trap.c

[
Kernel exploits `accessible()` to protect itself from panic of accessing corrupted user pointer. But stack is a special case that may be unmapped by still a legal address. These commits enable kernel to access legal but unmapped user stack by prefetching and loading user stack region in `accessible()` routine.
Tested on:
* allwinner D1s
* qemu-virt64-riscv
* qemu-virt64-aarch64
* qemu-vexpress-a9
]

[rt-smart] handling kernel from accessing unmapped user stack

---

bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/README.md
bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/pins_arduino.c
bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig

[
1.README文档更新
2.Kconfig更新
3.增加pins_arduino.c缺少的库
]

[rtduino][lpc55s69] update

---

components/lwp/lwp_shm.c
libcpu/aarch64/common/mmu.c

[
* [fix][lwp/shm] use virtual address in shm struct to establish a mapping in user space
* [fix][libcpu/aarch64] unmapping should stop if pos is NULL
]

[rt-smart] use virtual address in shm struct

---

components/libc/compilers/common/ctime.c

[
修复timer delete入参timerid非法的情况。在musl libc中，当使用SIGEV_THREAD创建timer_create对象时会失败，而失败之后在musl libc的实现中有一个pthread线程里不检查timer id(应该也无需检查或没法检查非法值)就进行 timer_delete系统调用来释放资源。如此在内核系统调用中会因为timerid非法而出现数组越界访问fault。
]

fixed ctime timer_delete timerid parameter check.

---

bsp/qemu-virt64-aarch64/drivers/drv_gpio.c
bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
components/drivers/include/drivers/pin.h
components/drivers/misc/pin.c

[
STM32
[修改pin数据类型]
[修改pin数据类型]
]

[pin][5.0.0] 修正pin框架数据类型使用不当

---

components/lwp/lwp_syscall.c

[
* [fix] kernel overwrites ustack data in `sys_timer_create` by writing to timer_id & sigevent which take up fewer bytes in libc
]

[rt-smart] fix `timer_create` bug

---

components/net/at/src/at_server.c

use __ARMCC_VERSION to replace __CC_ARM
[
to fix AC6 link error when configure and enable AT component in ENV.
the old #if defined (__CC_ARM) should be replaced to #if defined(__ARMCC_VERSION) 
using ArmCompiler 6.18 and 5.06  MDK V5.37
]
- [x 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up

[Fix]:fix at_server.c link failed when using ac6

---

documentation/device/pwm/pwm.md

[
使用doc中的pwm示例无法正常使用pwm驱动改变led的发光程度，在STM32F407ZGT6上测试的时候发现是由于将IO同时设置为输出模式引起的。
需要被PWM驱动控制的IO不要再配置为输出模式。
RT-Thread Studio+RTT 4.1.0+STM32F407ZGT6
]

修改doc文件夹下pwm例程中将led的io设置为输出模式后再使用PWM控制LED，经验证使用这样是无法正常输出PWM的

---

bsp/lpc54114-lite/drivers/drv_i2c.c
components/drivers/i2c/i2c_core.c
components/drivers/include/drivers/i2c.h

[
[修改i2c读写函数返回类型为rt_ssize_t]
[修改i2c读写函数返回类型为rt_ssize_t]
]

[device]修改i2c读写函数返回类型为rt_ssize_t

---

libcpu/risc-v/virt64/startup_gcc.S

[
在当前 master 分支中，qemu-riscv-virt64 smode 启动有问题，只有在使用 [Sifive 工具链](https://www.sifive.com/software) 的情况下才能进入系统，使用其他工具链则会报 `Illegal Instruction`  异常。
经过排查，最终确定是在 `startup_gcc.S` 没有为 `boot_hartid` 分配空间，在后续的指令中，发生了错误的修改。
```
boot_hartid: .int
.global boot_hartid
.global _start
.section ".start", "ax"
_start:
```
```c
/* save hartid */
la t0, boot_hartid /* global varible rt_boot_hartid */
mv t1, a0 /* get hartid in S-mode frome a0 register */
// 由于没有为 boot_hartid 分配空间，修改 boot_hartid 导致了其他指令的改动
sw t1, (t0) /* store t1 register low 4 bits in memory address which is stored in t0 */
```
对应的汇编语句如下，`boot_hartid` 与 `memset` 地址相同
```c
8020001c:   44828293                addi    t0,t0,1096 # 80200460 <memset>
80200020:   00050313                mv      t1,a0 …
```

[libcpu/riscv/virt64] fix (#5979) 修复 qemu-riscv-virt64 smode 下无法启动

---

src/ipc.c

[
When trying to update the priority of a thread in the scene of taking a mutex, there's a chance to update a suspended thread. And in the routine to update priority of a target thread, it reinsert the target thread to the suspended list of the waiting object (mutex in this case). The reinsertion is implemented by `_ipc_list_suspend`. Then it turns out that `_ipc_list_suspend` should not call `rt_thread_suspend_with_flag` directly because the suspended thread is suspended already.
In the end you will see error like this:
```text
(thread == rt_thread_self()) assertion failed at function:rt_thread_suspend_with_flag, line number:984
```
Following codes describe the scene above:
```c
struct rt_mutex _test_mutex1;
struct rt_mutex _test_mutex2;
struct rt_mutex _test_ceiling;
rt_thread_t tid1, …
```

[mutex] mutex may suspend a thread already suspended & fix ceilingprio

---

components/lwp/lwp_user_mm.c
components/mm/mm_aspace.c

[
* [mm] mmu operations should be wrapped by _aspace_bst_insert & _aspace_bst_remove to avoid competition on page table
* [lwp] may not return null on failed
]

[rt-smart] fix competition on aspace

---

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
bsp/stm32/libraries/HAL_Drivers/drv_tim.c
bsp/stm32/libraries/HAL_Drivers/drv_tim.h

[
这个问题已经在过去四年间反复折腾，主要问题就是集中在HAL_TIM_Base_Init和HAL_TIM_PWM_Init这两个函数的初始化顺序上。四年依赖，有很多小伙伴曾经在论坛上反馈过这个问题，并且也有很多PR。但是所有PR都是在这两个函数的调用顺序上扯大锯拉大锯，上一个PR换过去，下一个PR换回来.....
https://github.com/RT-Thread/rt-thread/pull/3155
https://github.com/RT-Thread/rt-thread/pull/3337
https://github.com/RT-Thread/rt-thread/pull/4254
https://github.com/RT-Thread/rt-thread/pull/5241
https://github.com/RT-Thread/rt-thread/pull/7030
论坛上的相关问题
https://club.rt-thread.org/ask/question/a8b1487fde9f0e77.html
https://club.rt-thread.org/ask/question/6ce57376be3021bd.html
https://club.rt-thread.org/ask/article/e611b91ad2e31ae8.html
https://club.rt-thread.org/ask/article/aae3a83f0bfe9857.html
本PR:
1. HAL_TIM_Base_Init 和 HAL_TIM_PWM_Init按照CubeMX生成的顺序，即先调用HAL_TIM_Base_Init再调用HAL_TIM_PWM_Init
2. 由于HAL_TIM_Base_Init 和 …

[stm32][pwm] fix the timer clock enable problem

---

bsp/ESP32_C3/drivers/Kconfig
bsp/ESP32_C3/drivers/drv_hw_i2c.c
bsp/ESP32_C3/drivers/drv_hw_i2c.h
bsp/ESP32_C3/rtconfig.h

[
ESP32——C3
添加ESP32_C3 I2C驱动
]

[driver]添加ESP32_C3 I2C驱动

---

bsp/k210/drivers/drv_i2c.c
bsp/k210/drivers/drv_io_config.c
bsp/lpc55sxx/Libraries/drivers/SConscript
bsp/lpc55sxx/Libraries/drivers/drv_i2s.c
bsp/lpc55sxx/Libraries/drivers/drv_i2s.h
bsp/lpc55sxx/Libraries/drivers/drv_sound_wm8904.c
bsp/lpc55sxx/Libraries/drivers/drv_sound_wm8904.h

lpc55sxx 增加i2s驱动及wm8904驱动，还未测试，近期会测试完善；
k210增加i2c驱动，为了测试i2c-tools增加的，并修改了drv_io_config.c的字符串，因为使用io命令时输出是乱码

[bsp/lpc55sxx] add drv_i2s, [bsp/k210] add drv_i2c

---

components/libc/compilers/common/ctime.c

[
when i use stime set rtc time, tv.tv_usec not 0,but always is 0xdeadbeef, make set time error,
and i2c transmit is slow,  i think get_timeval and set_timeval do same thing twice, i think its not necessary,
this happend on my device with mcu imxrt1020 and rtc sd3078, i fix this, now it work well
]

[libc][ctime] stime clear tv.tv_usec as zero

---

bsp/at32/libraries/rt_drivers/drv_gpio.c

[
在AT32F437-START开发板上使用IAR编译project工程会报“结构体类型不匹配的问题”，定位原因到drv_gpio.c与pin.h文件中。
在此给出文件的详细路径：
1.  bsp/at32/libraries/rt_drivers/drv_gpio.c
2. components/drivers/include/drivers/pin.h
查看pin.h文件中struct rt_pin_ops 原型：
```
struct rt_pin_ops
{
void (*pin_mode)(struct rt_device *device, rt_base_t pin, rt_uint8_t mode);
void (*pin_write)(struct rt_device *device, rt_base_t pin, rt_uint8_t value);
rt_int8_t  (*pin_read)(struct rt_device *device, rt_base_t pin);
rt_err_t (*pin_attach_irq)(struct rt_device *device, rt_base_t pin,
rt_uint8_t mode, void (*hdr)(void *args), void *args);
rt_err_t (*pin_detach_irq)(struct rt_device *device, rt_base_t pin);
rt_err_t (*pin_irq_enable)(struct rt_device *device, rt_base_t pin, rt_uint8_t enabled);
rt_base_t (*pin_get)(const char *name);
};
``` …

[HUST CSE][bsp] fix mismatched function types in rt_pin_ops

---

components/net/at/at_socket/at_socket.c

[
在at_socket.c文件中，检查出（警告）指针变量“at_sock”存在可能的空指针解引用。问题定位到了文件at_socket.c和rtservice.h中。在此给出文件的详细路径如下：
1. rt-thread\components\net\at\at_socket.c
2. rt-thread\include\rtservice.h
该空指针隐患在at_socket.c文件中多处存在，容易导致代码崩溃，主要导致该问题的原因在于如下代码，即在引用之前未判断pkt != RT_NULL：
``` 
pkt = rt_slist_entry(node, struct at_recv_pkt, list);
if (pkt->buff)
{
rt_free(pkt->buff);
}
```
查看rtservice.h文件中关于宏函数rt_slist_entry的描述：
```
#define rt_slist_entry(node, type, member) \
rt_container_of(node, type, member)
#define rt_container_of(ptr, type, member) \
((type *)((char *)(ptr) - (unsigned long)(&((type *)0)->member)))
```
综上所述，笔者发现可能存在空指针引用问题，所以提出了该问题并尝试解决。
在可能存在空指针引用的代码段内，添加一层空指针判断的步骤。由于存在多处空指针引用错误，所以举例一处如下：
未修改前的代码如下（将空指针判断错误地放到了内层判断中）：
```
rt_slist_for_each(node, &_socket_list)
{
at_sock = rt_slist_entry(node, struct …
```

[HUST CSE][components] Fix null pointer problems caused by the function rt_slist_entry()

---

bsp/ESP32_C3/drivers/drv_gpio.c
bsp/Vango/v85xx/drivers/drv_gpio.c
bsp/Vango/v85xxp/drivers/drv_gpio.c
bsp/acm32/acm32f0x0-nucleo/drivers/drv_gpio.c
bsp/acm32/acm32f4xx-nucleo/drivers/drv_gpio.c
bsp/airm2m/air105/libraries/rt_drivers/drv_gpio.c
bsp/airm2m/air32f103/libraries/rt_drivers/drv_gpio.c
bsp/allwinner_tina/drivers/drv_gpio.c
bsp/bluetrum/libraries/hal_drivers/drv_gpio.c

[
经由[[HUST CSE][bsp] fix mismatched function types in rt_pin_ops](https://github.com/RT-Thread/rt-thread/pull/7161)为启发，当时只发现一个板子上的问题，故只修改了一个文件。然后发现除少部分drv_gpio.c文件变量类型正确无误外，下面所列出的文件均有类型不匹配的问题。
1. bsp/ESP32_C3/drivers/drv_gpio.c
2. bsp/Vango/v85xx/drivers/drv_gpio.c
3. bsp/Vango/v85xxp/drivers/drv_gpio.c
4. bsp/acm32/acm32f0x0-nucleo/drivers/drv_gpio.c
5. bsp/acm32/acm32f4xx-nucleo/drivers/drv_gpio.c
6. bsp/airm2m/air105/libraries/rt_drivers/drv_gpio.c
7. bsp/airm2m/air32f103/libraries/rt_drivers/drv_gpio.c
8. bsp/allwinner_tina/drivers/drv_gpio.c
9. bsp/bluetrum/libraries/hal_drivers/drv_gpio.c
将drv_gpio.c的不匹配字段按照应有的类型做出一定的修改。
]

[HUST CSE][bsp]fix mismatched function types in rt_pin_ops for all drv_gpio.c

---

bsp/Infineon/libraries/IFX_PSOC6_HAL/mtb-hal-cat1/source/cyhal_crc.c

Either the condition 'NULL!=obj' is redundant or there is possible null pointer dereference: obj.
在判断断言时，若obj==NULL，或语句的右边为假，会进行或语句的左边obj->resource.type，故有错
此处给出文件路径：
bsp/Infineon/libraries/IFX_PSOC6_HAL/mtb-hal-cat1/source/cyhal_crc.c
查看源码：
`CY_ASSERT(NULL != obj || obj->resource.type != CYHAL_RSC_CRYPTO);`
将一个断言换成两个,避免空指针可能出现的bug
`CY_ASSERT(NULL != obj);
CY_ASSERT(obj->resource.type != CYHAL_RSC_CRYPTO);`
测试成功!

[HUST CSE]avoids the risk of a null pointer

---

components/dfs/dfs_v1/filesystems/tmpfs/dfs_tmpfs.c
components/dfs/dfs_v1/filesystems/tmpfs/dfs_tmpfs.h
include/rthw.h

fix tmpfs spinlock error.

---

components/drivers/cputime/cputime.c
components/drivers/cputime/cputime_cortexm.c
components/drivers/cputime/cputime_riscv.c
components/drivers/cputime/cputimer.c
components/drivers/include/drivers/cputime.h
components/drivers/include/drivers/cputimer.h
components/libc/compilers/common/ctime.c

[
原有cpu timer在多线程下存在逻辑错误，造成线程死锁
改用sem
aarch64 30线程压测几百万次未死锁
]

🐞 fix(components/drivers): fix cpu timer in multithreading

---

bsp/hpmicro/libraries/hpm_sdk/soc/HPM6360/hpm_clock_drv.c

**- 为什么提交这份PR** (why to submit this PR)**
在hpm_clock_drv.c文件中，发现两个判断Clock source是否有效的if语句存在着逻辑错误，从而导致无法对Clock source进行有效性验证。
文件的详细路径如下：
RT-Thread/rt-thread/blob/master/bsp/hpmicro/libraries/hpm_sdk/soc/HPM6360/hpm_clock_drv.c
具体的问题源于文件中第371行与391行，具体代码如下：
可以看到在if语句中，使用||会导致逻辑错误，使得有效的src也会被认为是无效的。
**- 你的解决方案是什么 (what is your solution)**
将||改为&&，使得src在同时满足两个判断都不满足时才认为有效性验证不通过。
**- 在什么测试环境下测试通过 (what is the test environment)**
all

[HUST CSE][blob]Fix logical errors in if statements

---

bsp/at32/at32f403a-start/board/Kconfig
bsp/at32/at32f407-start/board/Kconfig
bsp/at32/at32f413-start/board/Kconfig
bsp/at32/at32f415-start/board/Kconfig
bsp/at32/at32f421-start/board/Kconfig
bsp/at32/at32f423-start/board/Kconfig
bsp/at32/at32f425-start/board/Kconfig
bsp/at32/at32f435-start/board/Kconfig
bsp/at32/at32f437-start/board/Kconfig
bsp/at32/libraries/rt_drivers/drv_usart.c
bsp/at32/libraries/rt_drivers/drv_usart_v2.c
bsp/at32/libraries/rt_drivers/drv_usart_v2.h

[
[bsp/at32] update for perfection of drv_usart_v2
]

[bsp/at32] update for perfection of drv_usart_v2

---

components/finsh/msh_parse.c
src/idle.c
src/slab.c

[
根据这个issues  https://github.com/RT-Thread/rt-thread/issues/6857  在idle.c文件中找到一个函数缺失参数
fix the comment
no need
]

[HUST CSE][doxygen][src]Fix the comment in rt_thread_defunct_enqueue

---

components/drivers/serial/serial.c
components/drivers/serial/serial_v2.c

[
#7248 
错误的判断顺序：
- 该数组的定义：
`_tio_buf[i] = finsh_getchar();`
- 错误的代码：
`while(_tio_buf[cnt1] != ';' && cnt1 < _TIO_BUFLEN)`以及`while(_tio_buf[cnt2] != ';' && cnt2 < _TIO_BUFLEN)`
- 原因：
当`cnt1=_TIO_BUFLEN`时，在执行判断：`_tio_buf[cnt1] != ';'`时会导致数组下标越界错误
- 思路：
- 修改判断的顺序，先判断`cnt1 < _TIO_BUFLEN`，再判断`_tio_buf[cnt1] != ';' `
- 具体实现：
将语句由
`while(_tio_buf[cnt1] != ';' && cnt1 < _TIO_BUFLEN)`
改为
`while(cnt1 < _TIO_BUFLEN && _tio_buf[cnt1] != ';')`
并同时将cnt2的代码也同理作出调整
all
]

[HUST CSE] Fix: Wrong order of judgment

---

bsp/at32/libraries/rt_drivers/drv_qspi.c

[
在bsp/at32/libraries/rt_drivers/drv_qspi.c这个文件中，第444行申请qspi_device变量空间后，紧接着判断了是否申请成功，而在451行中申请cs_pin变量空间后，本应该判断这个变量是否申请成功，却继续判断qspi_device变量是否申请成功，如果cs_pin申请空间失败没有转入异常处理，后续就会发生错误，因此提交这份PR
直接将if语句错误的变量名qspi_device替换为正确的cs_pin
只修改了相应的变量名，测试一定会通过
]

[HUST CSE] Fix: if语句的判断条件存在变量名错误

---

components/lwp/lwp_ipc.c
components/lwp/lwp_ipc.h

[
进程间通讯，需要传递 文件描述符 fd，用于类似于 Linux dmabuf 的 内存共享机制
在 lwp_ipc 中，增加收发 文件描述符的操作，进程 A 发送： `fd->dfs_vnode`    进程B 接收 `dfs_vnode->new_fd`
rt-smart aarch64 平台测试通过
]

[smart][lwp_ipc] support file descriptor transmit

---

components/drivers/virtio/virtio_net.c
components/lwp/arch/aarch64/cortex-a/lwp_arch.c
components/lwp/arch/risc-v/rv64/lwp_arch.c
components/lwp/arch/x86/i386/lwp_arch.c
components/lwp/lwp.c
components/lwp/lwp_shm.c
components/lwp/lwp_syscall.c
components/lwp/lwp_user_mm.c
components/mm/avl_adpt.c
components/mm/ioremap.c
components/mm/mm_aspace.c
components/mm/mm_fault.c
components/mm/mm_object.c
components/mm/mm_page.c
components/mm/mm_page.h
libcpu/aarch64/common/cache.h
libcpu/aarch64/common/cpu.c
libcpu/aarch64/common/mmu.c
libcpu/aarch64/common/mmu.h
src/Kconfig

- [mm/page] multi-list page manager
- [mm/page] page debugger
- [libcpu/aarch64] hugepage support

[components/mm] support for scalable memory management

---

bsp/wch/arm/Libraries/CH32F20x_StdPeriph_Driver/StdPeriph_Driver/src/ch32f20x_adc.c
bsp/wch/risc-v/Libraries/CH32V10x_StdPeriph_Driver/StdPeriph_Driver/src/ch32v10x_adc.c

[
源码:
```
for(i=0; i<10; i++){
for(j=0; j<10; j++){
if(buf[j]>buf[j+1]){
t=buf[j];
buf[j]=buf[j+1];
buf[j]= t;
}
}
}
```
在1063行buf被声明为buf[10]，但由于1074和1075的边界条件错误导致1076行在j=9时访问到buf[10]越界
1079行数值交换错误
ch32v10x_adc.c中错误与上述错误一致
此处给出文件路径：bsp/wch/arm/Libraries/CH32F20x_StdPeriph_Driver/StdPeriph_Driver/src/ch32f20x_adc.c
bsp/wch/risc-v/Libraries/CH32V10x_StdPeriph_Driver/StdPeriph_Driver/src/ch32v10x_adc.c
修改冒泡排序i<9和j<9-i避免数组越界
修改为正确的数值交换
ALL
]

[HUST CSE]fix error in Bubble Sort

---

components/dfs/dfs_v1/src/dfs.c
components/dfs/dfs_v2/src/dfs.c

修改fdt_fd_release函数，在释放根节点之前，把子节点先释放，不然会出现内存泄漏问题
在qemu-riscvrvv上使用pingpong用户态测试用例测试，解决了内存泄漏问题

[dfs]释放fd_slot之前将子节点释放避免内存泄漏

---

components/net/at/src/at_server.c

[
for循环终止条件设定存在问题，读取字符串的最大索引应该是字符串长度-1，虽然继续读取字符串长度后面一个字节会读取到'\0',可能不会导致错误，但这一步是不必要的，并且不符合字符串读取的逻辑。
将for循环的终止条件改为i<strlen(cmd_buffer)
通过多个文件进行流程分析，并且只改动这一个位置，不会导致测试不通过。
]

[HUST CSE] for循环判断条件出错字符串读取越界

---

components/net/lwip/lwip-2.0.3/src/include/lwip/ip_addr.h
components/net/lwip/lwip-2.1.2/src/include/lwip/ip_addr.h
components/net/lwip/lwip-2.1.2/src/include/lwip/prot/ip6.h
components/net/lwip/port/ethernetif.c
components/net/lwip/port/lwipopts.h

[
在使用2.1.2版本lwip组件中，开启ipv6从编译到运行都遇到了问题，提供该修改策略。
首先声明，这不是一个充分解决```ipv6```问题的```pr```，算是一份必要不充分的修改。
```
- #define IP6_FRAG_HLEN    8
+ #define IP6_FRAG_HLEN    12
```
这里的修改是为了应对不同架构硬件平台指针大小```size```差异，出现```ip6_frag.c line 115```断言。
```
//components/net/lwip/lwip-2.1.2/src/core/ipv6/ip6_frag.c line 115
#if !IPV6_FRAG_COPYHEADER
LWIP_ASSERT("sizeof(struct ip6_reass_helper) <= IP6_FRAG_HLEN, set IPV6_FRAG_COPYHEADER to 1",
sizeof(struct ip6_reass_helper) <= IP6_FRAG_HLEN);
#endif /* !IPV6_FRAG_COPYHEADER */
```
其余说明可以参考issues #6985 中我个人的评论。
如果想让ipv6功能跑起来，还需要在```components/net/lwip/port/lwipopts.h```考量下面这两行代码的处理方式，这边的问题同样在上述 issues #6985 中提及，鉴于还没来得及找到比较好的处理方式，暂未处理。
```c
//components/net/lwip/port/lwipopts.h line 645
#include "lwip/ip_addr.h"
struct netif *lwip_ip4_route_src(const ip4_addr_t …
```

fix ipv6 compatibility issues

---

components/mm/mm_page.c
libcpu/aarch64/common/cache.h

[
* `ic iallu` is replaced with `ic ialluis` because previous implementation is not working properly on cortex-a55
*  fix a misuse of va in `mm_page.c`
]

[libcpu/aarch64] fix cache invalidate operation

---

components/lwp/lwp_syscall.c

[
rt_err_t 不是 lwp 定义的，不能依赖一个外部类型 所以将所有的 rt_err_t 改为 sysret_t
]

[syscall] lwp_syscall 中 rt_err_t 改为 sysret_t

---

bsp/imx6sx/iMX6_Platform_SDK/sdk/common/usb_stack/Device/source/driver/mx6x/usb_dci_imx6.c

以下一行代码中memset函数使用有误
memset(qh_buf, 0x0, sizeof(qh_buf));
sizeof(qh_buf)为固定值8，而这里的想要实现的功能是初始化qh_buf所指向的内存，因而代码改为以下：
memset(qh_buf, 0x0, TOTAL_QTD_SIZE);

[HUST CSE] memset函数使用错误

---

components/lwp/lwp_syscall.c

[
- 修复sys_execve系统调用在解析脚本参数的时候错误的释放了空指针
- 修复参数解析过程未能正确释放旧内存缓冲区的问题
]

fix lwp _load_script.

---

bsp/lpc55sxx/Libraries/drivers/drv_hwtimer.c
bsp/lpc55sxx/Libraries/drivers/drv_hwtimer.h
bsp/lpc55sxx/Libraries/drivers/drv_i2s.h
bsp/lpc55sxx/Libraries/drivers/drv_soft_spi.h
bsp/lpc55sxx/Libraries/drivers/drv_sound_wm8904.h
bsp/lpc55sxx/Libraries/drivers/drv_wdt.h
bsp/lpc55sxx/lpc55s69_nxp_evk/README.md
bsp/lpc55sxx/lpc55s69_nxp_evk/README_zh.md
bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig

[bsp][lpc55s69]update:drv_hwtimer

---

components/drivers/usb/usbdevice/class/winusb.c

[
发现在winusb.c文件中rt_usbd_function_winusb_create函数为变量winusb_device分配了内存空间，但是未检查空间不足时分配失败的情况，因此存在潜在风险
比对其他文件中对于malloc的后续处理步骤，添加了检查malloc结果的步骤，并在分配失败时返回RT_NULL
通过进行流程分析，并且只改动这一个位置，不会导致测试不通过.
]

[winusb.c] add a checkout procedure after allocating memory for variable winusb_device to make sure allocating successfully

---

libcpu/sim/posix/cpu_port.c

[
cpu_port.c中RT_ASSERT判断存在逻辑错误
```c
RT_ASSERT(RT_TICK_PER_SECOND <= 1000000 || RT_TICK_PER_SECOND >= 1);
```
显然 逻辑应该为且，不是或
改为且运算符 &&
]

[HUST CSE]fix:修复了cpu_port.c中RT_ASSERT逻辑错误

---

components/vbus/vbus_chnx.c

[
在vbus_chnx.c中rt_vbus_chnx_register_disconn函数中的指针变量dev以及vdev访问在空指针判断之前进行，存在可能的空指针引用,进而引起程序异常退出
修改程序运行逻辑，使指针变量先进行空指针判断再进行访问
ALL
]

[HUST CSE] Adjust the null pointer check and access orderPointer error

---

bsp/simulator/pcap/pcap_netif.c

[
bsp/simulator/pcap/pcap_netif.c 文件中的 pcap_netif_tx 函数中定义了 rt_uint8_t buf[2048] 数组，并在将函数参数 struct pbuf* p 形成的 pbuf 链表内的数据拷贝到这个 buf 数组中（见[pcap_netif_tx 函数相关代码](https://github.com/RT-Thread/rt-thread/blob/master/bsp/simulator/pcap/pcap_netif.c#L192-L214)）。
然而在 pcap_netif_tx 函数代码中并没有对参数 struct pbuf* p 形成的 pbuf 链表内的总数据长度进行检查。若按照当前代码的拷贝方式，在 pbuf 链表的总数据长度超过 2048 个字节后会引起缓冲区溢出，使得栈内其他数据被修改。
认为该函数存在潜在缓冲区溢出漏洞的原因是：
1. 在对仓库代码进行检索后，并未在可能调用该函数的相关代码中看到对输入参数 struct pbuf* p 形成的 pbuf 链表内的数据长度进行限制（例如在可能的函数调用关系“ethip6_ouput=>ethernet_output=>linkoutput(ethernetif_linkoutput)=>eth_tx(pcap_netif_tx)”中并没有发现对 pcap_netif_tx 函数输入参数 struct pbuf* p 形成的 pbuf 链表内的总数据长度的限制）。
2. 可以注意到和 pcap_netif_tx 函数类似作用的 bsp/allwinner/libraries/sunxi-hal/hal/source/gmac/hal_geth.c 文件下的 rt_geth_xmit 函数中对拷贝的 pbuf 链表总数据长度超过 2048 …

[HUST CSE][bsp][fix] Fix potential buffer overflow vulnerability

---

bsp/lpc55sxx/lpc55s69_nxp_evk/board/SConscript
bsp/lpc55sxx/lpc55s69_nxp_evk/board/ports/rw007_lpc55sxx_port.c
bsp/lpc55sxx/lpc55s69_nxp_evk/board/ports/rw007_port.c

[bsp][lpc55sxx]add: rw007_lpc55sxx_port.c

---

components/drivers/usb/usbdevice/class/rndis.c

[
发现在rndis.c文件中rt_usbd_function_rndis_create函数为变量_rndis分配了内存空间，但是未检查空间不足时分配失败的情况，因此存在潜在风险
比对其他文件中对于malloc的后续处理步骤，添加了检查malloc结果的步骤，并在分配失败时打印日志并返回RT_NULL
通过进行流程分析，并且只添加一个检查分支，不会导致测试不通过.
]

[components][rndis.c] add a checkout procedure after malloc to make sure allocating successfully

---

components/drivers/spi/spi_core.c

- 在 rt_spi_configure 中没有对配置结果做检查，建议补充上
- 偶然发现有人不是很明白这里为何，何时需要执行配置 (ref : https://blog.csdn.net/lilijianqun/article/details/103061547) , 故增加了一行注释说明一下
```DIFF
if (device->bus->owner == device)
{
+               /* current device is using, re-configure SPI bus */
result = device->bus->ops->configure(device, &device->config);
if (result != RT_EOK)
```

[components/drivers] add result check for configure in `rt_spi_configure`

---

components/drivers/usb/usbdevice/class/rndis.c

[
在rndis.c的rt_usbd_function_rndis_create函数中，调用rt_usbd_interface_new函数创建了两个接口，但是rt_usbd_interface_new函数在分配内存失败的时候会返回RT_NULL，但是后面用这两个数据结构的时候没有检查就直接用了。如果创建失败的话，会导致空指针引用缺陷。
比对其他文件中对于变量是否为空的检查与后续处理步骤，添加了检查与后续处理的步骤，并在变量为空时打印日志并返回RT_NULL
通过进行流程分析，并且只添加一个检查分支，不会导致测试不通过
]

[components][rndis.c] add a checkout procedure after creating variable intf_comm and intf_data to make sure them usable

---

components/libc/posix/ipc/mqueue.c

[
The related issue is #7485 
> error: 'PATH_MAX' and 'NAME_MAX' undeclared (first use in this function) 
It can be reproduced by following [Getting Started of QEMU (Ubuntu)](https://www.rt-thread.io/document/site/documentation/quick_start_qemu/quick_start_qemu_linux/)  
Execute `cd rt-thread/bsp/qemu-vexpress-a9` and `scons`, then you will get such compile error belows:  
```text
...
CC build/kernel/components/libc/posix/io/poll/select.o
CC build/kernel/components/libc/posix/io/stdio/libc.o
CC build/kernel/components/libc/posix/io/termios/termios.o
CC build/kernel/components/libc/posix/ipc/mqueue.o
/home/dylan/workspace/repos/rt-thread/components/libc/posix/ipc/mqueue.c: In function 'mq_open':
/home/dylan/workspace/repos/rt-thread/components/libc/posix/ipc/mqueue.c:141:33: error: …
```

[components][libc][posix] fix RT_NAME_MAX misspelled as NAME_MAX

---

components/dfs/dfs_v1/src/dfs_posix.c
components/dfs/dfs_v2/src/dfs_posix.c
components/lwp/lwp_syscall.c

[
gcc12中C++的filesystem模块有使用到openat系统调用，特此添加实现。已经在aarch64上测试通过。
]

[component] add openat syscall.

---

bsp/lpc55sxx/Libraries/drivers/drv_i2c.c
bsp/lpc55sxx/Libraries/drivers/drv_soft_i2c.c
bsp/lpc55sxx/Libraries/drivers/drv_soft_i2c.h
bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig

[bsp][lpc55sxx]update: drv_soft_i2c

---

src/device.c

[
如果是相同的flags，这个条件也能够满足，也就是open函数还是会被调用。
在qemu-a9上测试通过
]

[kernel] fix device_open oflag comparison error.

---

src/thread.c

如果hw_interrupt_disable支持嵌套,这里是否会导致中断不恢复,导致调度出错呢

[kernel][src] possible issues

---

components/net/lwip/port/sys_arch.c
components/net/netdev/src/netdev.c

[
Original implementation always return default netif to caller.
We should compare source IP address and netif IP address with netmask at the same time. 
Tested on multi-ethernet cards on Nuvoton platform.
]

[components][net][lwip][port]  Fix next-hop finding in lwip_ip4_route_src.

---

include/rtthread.h
src/object.c
src/thread.c

- Added rt_thread_get_name() API
- Added rt_object_get_name() API
[
需要接口去获取 rt-thread中对应object和thread 的name
增加相应的两个API
- rt_object_get_name
- rt_thread_get_name
HPM6750EVKMINI上添加API测试代码
]

[include][src] Add API to get object name and thread name

---

.github/workflows/action.yml
bsp/stm32/stm32l475-atk-pandora/board/SConscript
bsp/stm32/stm32l475-atk-pandora/rtconfig.py
components/drivers/spi/SConscript
components/libc/compilers/common/cstring.c
components/libc/compilers/common/extension/SConscript
components/libc/compilers/picolibc/README.md
components/libc/compilers/picolibc/SConscript
components/libc/compilers/picolibc/syscall.c
libcpu/arm/cortex-m4/SConscript
tools/llvm_arm.py

[
支持ARM开源的LLVM工具链，仓库地址 https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm
需要下载最新的 llvm16.0版本
在 潘多拉开发板测试通过
]

support llvm-arm 16.0

---

libcpu/arm/cortex-a/start_gcc.S

[
- 问题现象
arm/cortex-a/start_gcc.S 中stack_setup 函数中，当调用rt_asm_cpu_id 时会出现循环卡死的情况，修改前代码为
修改后的代码为：
修改掉无效的lr 备份操作，由 ”mov pc, lr“ 指令从子程序返回到调用者。
- 测试方法：
目前已经在demo board 上进行测试，测试方法为屏蔽掉外部 rt_asm_cpu_id 强定义，使用默认weak函数
]

[libcpu] fix arm/cortex-a/start_gcc.S

---

tools/building.py

In some envs, the Env['CPPDEFINES'] returns deque data type. And the list can not add with a deque variable.

[building] Fix the deque issue for Env['CPPDEFINES']

---

components/libc/posix/ipc/mqueue.c

[
添加了LIBC文件夹POSIX函数中mqueue.c的mq_unlink函数注释
]

[components]对POSIX函数中mqueue.c的mq_unlink函数注释

---

components/libc/compilers/common/ctime.c

[
解决clock_gettime计算出来的nsec超过1sec的问题
]

[ctime]解决clock_gettime计算出来的nsec超过1sec的问题

---

components/drivers/tty/n_tty.c

[此处为ring buf从末尾到开头的部分，在回到开头的时候，将n减去了buf_size，而n是作为接受buf的长度，返回给n_tty_read的，导致每次ring_buf从末尾回到开头的时候就必定丢失buf_size长度的数据，这里做了一个temp_n代替n
]

[tty]修复多次scanf之后,导致丢数据的问题

---

bsp/stm32/libraries/HAL_Drivers/drv_spi.c
include/rtdef.h

[
- 根据建议,进行优化
> https://github.com/RT-Thread/rt-thread/pull/6741#discussion_r1220817019
- 区分H7/F7情况下的SPI+DMA流程.
- 以支持单独使用TX_DMA和RX_DMA的情况.
- STM32H750[ART-PI]
- KEIL V6 -OZ编译
- 使用SPI FLASH W25Q128,搭载littlefs文件系统测试
- 仅测试TXDMA和RXDMA开启情况.未测试单独开启TXDMA或者单独开启RXDMA的情况
测试图片传不上github >https://oss-club.rt-thread.org/uploads/20230607/cf0f422a1f56108ab381ddbc1c94e76a.png
]

[bsp][stm32][spi] 优化DMA数据非字节对齐的处理流程

---

components/libc/posix/signal/posix_signal.c

[
#7426 
There are missing comments for functions in posix_signal.c. 
I add the comments based on posix standard and the implement of the functions. 
No need.
]

[comment][libc] add some comments for functions in posix_signal

---

components/drivers/misc/adc.c

The variable result_str is never used after this assignment.
[
The variable result_str is never used after this assignment.
Remove the dead code (this assignment to result_str).
n32/n32g43xcl-stb
]

[adc] remove dead code

---

components/libc/compilers/common/ctime.c

This null check was redundant because the pointer timep was dereferenced in any case.
[
Fix null pointer dereference.
Move null pointer check before dereference
n32/n32g43xcl-stb 
]

[libc][ctime] move null pointer check before dereference

---

bsp/wch/risc-v/Libraries/ch32_drivers/drv_common.c
bsp/wch/risc-v/Libraries/ch32_drivers/drv_common.h

[
- 提供了`rt_hw_us_delay`，用以 us 延时。
- 参考 arm 系列芯片的延时方案，实现 risc-v 系列芯片的 us 延时。
- CH32V307VCT6 自制板卡。
]

向 wch-riscv-bsp 添加 drv_common.c/.h 文件

---

bsp/stm32/libraries/HAL_Drivers/drv_adc.c

[
- Issue present: Using ADC1 module on the STM32U575, the result of `rt_adc_read()` is always zero.
- The definitions for `SOC_SERIES_STM32U5` is added. Power configuration for VDDA analog power domain must be added. (See code from https://community.st.com/s/question/0D53W00001Uz3k3SAB)
- BSP: stm32u575-st-nucleo. Board: NUCLEO-U575ZI-Q
]

[bsp][stm32u575] add ADC support

---

components/drivers/tty/pty.c

[pty]修正pty引起waitqueue崩溃的问题

---

bsp/stm32/stm32f103-dofly-lyc8/rtconfig.py
include/rtdebug.h
include/rthw.h
src/ipc.c
src/irq.c

[
在cortex-M系列芯片上关闭中断时，也是不可以进行调度的。添加 api rt_hw_interrupt_is_disabled，可以更早的发现问题
在F407芯片测试通过
测试代码
```
rt_bool_t rt_hw_interrupt_is_disabled(void)
{
return (__get_PRIMASK() != 0);
}
int main(void)
{
do
{
rt_hw_interrupt_disable();
rt_thread_mdelay(500);
}while(1);
}
```
]

[kernel]add api rt_hw_interrupt_is_disabled

---

include/rtdef.h

[atomic]修复bsp/simulator vs2019编译下 atomic 两个volatile的问题

---

components/drivers/serial/serial.c

有时 putc(serial, (char)data) 失败后，重试时重复发送 '\r' 。
由于 serial->ops->putc(serial, (char)data) 失败后，导致 serial->ops->putc(serial, '\r') 重复执行 （表现为串口有时多输出了‘\r’），此修改可以修复此问题。

[components][drivers][serial] serial.c 修复串口有时重复发送 '\r' 的问题

---

bsp/efm32/rtconfig.h
bsp/lpc43xx/M0/rtconfig.h
bsp/sep6200/rtconfig.h
bsp/simulator/drivers/module_win32.c
components/libc/posix/libdl/arch/arm.c
components/libc/posix/libdl/arch/riscv.c
components/libc/posix/libdl/arch/x86.c
documentation/basic/basic.md
libcpu/ti-dsp/c28x/cpuport.c
src/Kconfig
src/ipc.c
src/irq.c
src/mem.c
src/memheap.c
src/scheduler_mp.c
src/scheduler_up.c
src/slab.c
src/thread.c
src/timer.c

remove RT_DEBUG_THREAD RT_DEBUG_SCHEDULER RT_DEBUG_IPC RT_DEBUG_TIMER RT_DEBUG_IRQ RT_DEBUG_MEM RT_DEBUG_SLAB RT_DEBUG_MEMHEAP
全部使用新版ulog debug宏代替
[
]

[debug] remove RT_DEBUG_xxx

---

bsp/Infineon/libraries/HAL_Drivers/SConscript
bsp/Infineon/libraries/HAL_Drivers/drv_i2c.c
bsp/Infineon/psoc6-evaluationkit-062S2/board/Kconfig

Add Arduino I2C pin config for **PSoC™ 62 WITH CAPSENSE™ Evaluation Kit**
因为：
* RTT PSoC开发板的Arduino接口的I2C引脚与主控芯片的P8.0和P8.1相连
* 主控芯片的P8.0和P8.1可以通过引脚复用设置为硬件I2C功能
因此，添加了这两个引脚的硬件I2C配置之后，就可以使用Arduino扩展版；
硬件I2C代码以及有了，加个配置就好了
**PSoC™ 62 WITH CAPSENSE™ Evaluation Kit** 板子上测过了

[bsp][Infineon] Add I2C4 config for psoc6-evaluationkit

---

components/net/sal/socket/net_sockets.c

[
在使用 socket 编程时开启 RT_DEBUG
在调用 closesocket() 接口时出现了断言问题：
(header_ptr->magic == (RT_MEMHEAP_MAGIC | RT_MEMHEAP_USED)) assertion failed at function:rt_memheap_free, line number:623
Debug 后发现 vnode 的地址被 free 了两次
]

[SAL/SOCKET]修复在 RT_DEBUG 开启后，调用 closesocket 接口触发断言的 BUG

---

components/lwp/arch/aarch64/cortex-a/lwp_gcc.S
libcpu/aarch64/common/armv8.h
libcpu/aarch64/common/asm-fpu.h
libcpu/aarch64/common/stack.c

In aarch64's rt_hw_exp_stack.fpu, there is only 16 vector regs, but each reg only 8 byte, we should fixup it to 16 byte. Maybe the fpu context codes is from ARMv7 that only stored 16 vector regs before. Now, we append Q16 ~ Q31.
Link: https://github.com/RT-Thread/rt-thread/issues/7707
[
1. 在 AArch64 之前 FPU 部分，实际上只保存了 Q0 ～ Q15，理论上需要 `16 * 16 = 256` 字节的空间，但是在 rt_hw_exp_stack 中的 `fpu` 实际上只有 `16 * 8 = 128` 字节，虽然 rt_hw_exp_stack 并没有广泛使用但也是个危险的定义。
2. 由于只保存了 Q0 ~ Q15，因此根据 [[NEON]在armv8-a架构下，任务切换时，v0-v31向量寄存器是否进行了现场保存](https://github.com/RT-Thread/rt-thread/issues/7707) 的反馈，增加了对 Q16 ～ Q31 的保存。
]

AArch64: fixup fpu storage's size in stack and append Q16 ~ Q31

---

libcpu/arc/em/contex_gcc_mw.S
libcpu/arc/em/cpuport.c

[
在实际项目中发现线程切换bug
* 添加线程环境切换未保存的上下文  
* `context_switch_reqflg`改为`rt_thread_switch_interrupt_flag`  
* 在中断环境切换时增加rt_thread_switch_interrupt_flag`  标志位判断，防止中断嵌套时修改from的sp，进而破坏from线程的栈空间，或者栈溢出。  
在windows下使用加特兰的Alps 雷达开发平台测试。  
]

[libcpu][arc]修复arc架构线程切换bug

---

bsp/Infineon/libraries/HAL_Drivers/drv_i2c.c
bsp/Infineon/psoc6-evaluationkit-062S2/board/Kconfig
bsp/Infineon/psoc6-evaluationkit-062S2/board/board.h

[
添加iic4的配置，将初始化错误断言部分修改为打印方式
]

[bsp][Infineon]fix i2c init error

---

components/drivers/tty/console.c
components/drivers/tty/n_tty.c
components/drivers/tty/tty.c
components/libc/compilers/common/ctime.c
components/lwp/arch/aarch64/cortex-a/lwp_arch.c
components/lwp/arch/aarch64/cortex-a/lwp_arch.h
components/lwp/arch/aarch64/cortex-a/lwp_gcc.S
components/lwp/arch/arm/cortex-a/lwp_arch.c
components/lwp/arch/arm/cortex-a/lwp_arch.h
components/lwp/arch/arm/cortex-a/lwp_gcc.S
components/lwp/arch/risc-v/rv64/lwp_arch.c
components/lwp/arch/risc-v/rv64/lwp_arch.h
components/lwp/arch/risc-v/rv64/lwp_gcc.S
components/lwp/lwp.c
components/lwp/lwp.h
components/lwp/lwp_arch_comm.h
components/lwp/lwp_clone.h
components/lwp/lwp_dbg.h
components/lwp/lwp_pid.c
components/lwp/lwp_pid.h
components/lwp/lwp_signal.c
components/lwp/lwp_signal.h
components/lwp/lwp_syscall.c
include/rtdef.h
src/thread.c

[
Support more features of signal from POSIX.1-2017
- [components/lwp] lwp signal
- add sigqueue handling
- support sigtimedwait, sigwait, sigpending
- update the generation, pending and delivery routines
- [components/lwp] architecture porting layer
- move part of the codes to C from asm in signal handling
- remove lwp_signal_backup/restore() to reduce architecture codes
- [components/libc] update signal generation routine for lwp
- adapt to new api and do the signal handling in thread context
- [components/drive] tty
- adapt to new api and do the signal handling in thread context
- Tested on qemu-a9, qemu-aarch64, qemu-riscv64 with basic signal application
- Tested on qemu-aarch64 with PSE51 test suite
] …

[component/lwp] support more feature of signal from IEEE Std 1003.1-2017

---

bsp/airm2m/air32f103/libraries/rt_drivers/drv_gpio.c
bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
bsp/synwit/swm320/drivers/drv_gpio.c
bsp/synwit/swm341/drivers/drv_gpio.c
bsp/wch/arm/Libraries/ch32_drivers/drv_gpio_ch32f10x.c
bsp/wch/arm/Libraries/ch32_drivers/drv_gpio_ch32f20x.c
bsp/wch/risc-v/Libraries/ch56x_drivers/ch56x_gpio.c
components/drivers/misc/pin.c

[
pin num 命令输入的GPIO字符串不合理， 不同平台GPIO命令不一致，示例命令应该由驱动层输出提供。例如rockchip GPIO格式为GPIO0_A0, STM32为PA0
]

[bsp][stm32][airm2m]<pin>更新pin num命令

---

components/libc/compilers/common/ctime.c
components/lwp/lwp.h
components/lwp/lwp_pid.c

[
Memory leak will happen if user create a timer and exiting without calling to `timer_delete()`
- Add timer management code for lwp, so it can recycle the timer on lwp defunct routine
- POSIX app running on qemu-aarch64
]

[smart] fix possible memory leak

---

.github/CODEOWNERS

[ci] update code owner

---

components/dfs/dfs_v1/filesystems/devfs/devfs.c
components/dfs/dfs_v1/filesystems/elmfat/dfs_elm.c
components/dfs/dfs_v1/filesystems/romfs/dfs_romfs.c
components/dfs/dfs_v1/filesystems/tmpfs/dfs_tmpfs.c
components/dfs/dfs_v1/include/dfs_file.h
components/dfs/dfs_v1/src/dfs_file.c
components/dfs/dfs_v2/filesystems/devfs/devfs.c
components/dfs/dfs_v2/filesystems/elmfat/dfs_elm.c
components/dfs/dfs_v2/filesystems/romfs/dfs_romfs.c
components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c
components/dfs/dfs_v2/include/dfs_file.h
components/dfs/dfs_v2/src/dfs_file.c
components/drivers/ipc/pipe.c
components/drivers/serial/serial.c
components/drivers/tty/tty.c
components/net/sal/dfs_net/dfs_net.c

[
dfs_file_ops结构体存放的read、write、lseek函数原型的返回值类型选取错误
修改dfs_file_ops结构体存放的read、write、lseek函数原型的返回值类型
在A1000开发板上，编写应用，调用应用层使用的接口read、write、lseek，通过测试
]

modify some function prototypes of the dfs_file_ops structure and the function declarations based on it

---

components/lwp/arch/arm/cortex-a/lwp_arch.c
examples/utest/testcases/kernel/atomic_tc.c
include/rtdef.h
libcpu/aarch64/common/context_gcc.S
libcpu/arm/cortex-a/context_gcc.S
libcpu/arm/cortex-a/start_gcc.S

[
Fix the issue in https://github.com/RT-Thread/rt-thread/issues/7841
Clear an existing tag on context switch, so local monitor can notice the race condition when executing exclusive store
Tested on board qemu-vexpress-a9 with atomic_tc under `examples` directory
]

[libcpu/arm] fix race condition with ldrex,strex

---

bsp/wch/risc-v/Libraries/ch32_drivers/drv_usart.c

将UART4后的中断函数声明改为UART
[
在CH32V307R1 BSP 发现使用UART4后的UART会发生中断函数跑飞，检查BSP库发现中断声明写为USART。
查阅数据手册，发现USART3后的4 5 6等等均为UART
[![pCXszkR.md.png](https://s1.ax1x.com/2023/07/25/pCXszkR.md.png)](https://imgse.com/i/pCXszkR)
直接修改声明USART->UART
已在CH32V307R1 上运行UART示例代码，可收发
]

[bsp][wch] fix UART IRQ declarion

---

bsp/at32/libraries/rt_drivers/drv_usbfsh.c
bsp/imxrt/libraries/drivers/drv_usbh.c
bsp/nuvoton/libraries/m2354/rtt_port/drv_usbhost.c
bsp/nuvoton/libraries/m460/rtt_port/drv_usbhost.c
bsp/nuvoton/libraries/m480/rtt_port/drv_usbhost.c
bsp/nuvoton/libraries/ma35/rtt_port/drv_usbhost.c
bsp/nuvoton/libraries/n9h30/rtt_port/drv_usbhost.c
bsp/nuvoton/libraries/nuc980/rtt_port/drv_usbhost.c
bsp/stm32/libraries/HAL_Drivers/drv_usbh.c
components/drivers/usb/usbhost/core/hub.c

related: https://github.com/RT-Thread/rt-thread/pull/7799
[
]

[debug] use LOG_D instead RT_DEBUG_LOG

---

components/drivers/include/drivers/mmcsd_card.h
components/drivers/sdio/mmc.c

[sdio]开启emmc内部cache加快传输

---

components/drivers/ofw/base.c
components/drivers/ofw/fdt.c
components/drivers/ofw/irq.c
components/mm/ioremap.c
components/mm/ioremap.h
components/mm/mm_page.h
libcpu/Kconfig
libcpu/aarch64/Kconfig
libcpu/aarch64/common/cpuport.h
libcpu/aarch64/common/mmu.c

[
1. Fixup:Arch Kconfig empty in MCU
2. AArch64:cpuport:replace rt_inline with macros
3. Components:MM:add early map api
4. Drivers:OFW:replace new rt_str* to string.h

Prepare some api for DM

---

components/lwp/lwp_pmutex.c

[lwp] 修复错误码误用

---

components/dfs/dfs_v1/filesystems/elmfat/dfs_elm.c
components/dfs/dfs_v1/src/dfs_file.c
components/dfs/dfs_v1/src/dfs_posix.c

[
在项目运行过程中发现在打开一个文件并使用过 `write` 写入数据，此时若拔掉SD卡，`close` 必然返回失败，但是此时 `dfs` 的文件描述符并没有被释放，该内存将被永久占用，无法被释放。从而导致内存泄漏
通过修改 `dfs` 的文件关闭逻辑，使其无论当前是否能够成功关闭，都会释放文件描述符（参考Linux 内核代码）。
在 ART-PI 上测试通过
]

[DFS_V1] 修复close失败后不释放fd导致内存被永久占用且无法释放

---

components/drivers/sdio/mmc.c

- Corrected the HIGH_SPEED timing setting
- Adjusted the bus_width setting logic
- Avoided potential null derefence issue in rt_mmcsd_blk_remove function
[
在测试mmc驱动时，发现了一些bug
对照EMMC 5.1 规范以及当前mmc.h的结构体定义修改了代码逻辑
当前的这份改动在先楫HPM6750EVKMINI和HPM6300EVK上做过测试。
]

[components][drivers][sdio] Fix minor issue in sdio driver

---

components/lwp/arch/aarch64/cortex-a/lwp_arch.c
components/lwp/arch/aarch64/cortex-a/lwp_arch.h
components/lwp/arch/aarch64/cortex-a/lwp_gcc.S
components/lwp/lwp_pid.c
components/lwp/lwp_signal.c
components/lwp/lwp_syscall.c

[
Previous implementation only allow main thread in a process to do the termination. If the termination is triggered by a sub-thread while main thread is suspended, the process will hang up forever.
The user status may be corrupted during `rt_schedule()` because of this.
https://github.com/RT-Thread/rt-thread/blob/5c4b44f81e82d813bfd991e57d21c64ca3070a44/libcpu/aarch64/common/context_gcc.S#L147
For issue 1:
In `lwp_termiante()`, each thread can race to terminate the process, which will set a flag to other threads to indicate a termination is pending and **request** all the threads to exit. Still, after every other threads exit, the main thread only will complete the remaining termination progress (setup return code, etc.)
For issue 3:
This patch bypass this through constructing the SPSR …

[smart] Fix bugs on lwp kill

---

components/drivers/wlan/wlan_dev.c
components/drivers/wlan/wlan_mgnt.c

[
wlan层的代码有一些编译警告，修复这些局部变量没有使用的警告，以及结构体对象初始化不标准的问题，消除这些警告。
HMIBoard
消除编译警告
删除一些无效的代码，规范结构体对象的初始化方式
RTTStudio
]

fix some variables not used warnings when build.

---

components/drivers/sdio/block_dev.c
components/finsh/cmd.c
components/finsh/msh_file.c
components/libc/posix/io/stdio/libc.c
components/lwp/lwp.c
components/lwp/lwp.h
components/lwp/lwp_ipc.c
components/lwp/lwp_pid.c
components/lwp/lwp_sys_socket.h
components/lwp/lwp_syscall.c
components/net/lwip/lwip-2.1.2/src/core/netif.c
components/net/sal/socket/net_sockets.c
components/net/sal/src/sal_socket.c
include/rtdef.h
libcpu/aarch64/common/backtrace.c
libcpu/aarch64/common/backtrace.h
libcpu/aarch64/common/context_gcc.S
libcpu/aarch64/common/trap.c
src/kservice.c

update components & lwp.

---

components/dfs/dfs_v2/src/dfs_file.c

[
修复dfs_file_open的返回值，不正确的返回值会最终给到系统调用，并影响到应用态的应用处理逻辑。
]

fix dfs_file_open error code

---

components/lwp/lwp_pid.c

[
修复lwp_free时切换前台tty的逻辑。
原有逻辑没有考虑进程退出的顺序，存在进程退出顺序和前台tty进程栈顺序压栈不一致的问题，会导致进程退出后无法正常切换回前台进程tty。
]

fix lwp_free tty switch to foreground error

---

components/finsh/msh.c

[
修复msh里执行应用的时候遇到权限问题能正确的给出权限不够的提示信息
]

fix msh exec permission denied

---

components/dfs/dfs_v1/filesystems/nfs/rpc/types.h
components/lwp/libc_musl.h
components/lwp/lwp.c
components/lwp/lwp.h
components/lwp/lwp_syscall.c
components/lwp/lwp_user_mm.c
components/lwp/lwp_user_mm.h
components/mm/mm_aspace.c
components/mm/mm_aspace.h
components/mm/mm_fault.c
components/mm/mm_fault.h
components/mm/mm_flag.h
examples/utest/testcases/mm/SConscript
examples/utest/testcases/mm/common.h
examples/utest/testcases/mm/mm_lwp_tc.c
examples/utest/testcases/mm/test_aspace_api.h
examples/utest/testcases/mm/test_bst_adpt.h
libcpu/aarch64/common/mmu.c
libcpu/aarch64/common/trap.c
libcpu/arm/cortex-a/trap.c
libcpu/risc-v/t-head/c906/trap.c
libcpu/risc-v/virt64/trap.c

[
Support `varea_unmap_page()` and new unit test cases.
QEMU arm, aarch64, riscv64; A1000
]

[components/mm] add unmap page API

---

components/drivers/can/can.c

[
随机出现 bsp can 成功发送消息，但 rt_device_write 返回值不为 0。
出现上述问题的原因：
每次component can发送消息前，没有对 tx_tosnd->completion 进行初始化设置。
所以可能出现：在 bsp can 驱动未完成消息发送的情况下，_can_int_tx 根据前一次的 RT_COMPLETED，误判本次消息已发送完成
component can发送消息前，调用rt_completion_init对tx_tosnd->completion进行初始化设置（设为RT_UNCOMPLETED）
HC32F4A0
]
- [x ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

[components][drivers][can]Init can tx completion flag before tx

---

components/dfs/dfs_v1/filesystems/elmfat/ff.c
components/dfs/dfs_v1/src/dfs_file.c

[
在使用 ART-PI BSP 时发现启用 sdcard 文件系统后在终端输入 `ls` 会有如下显示：
sdcard 目录被识别成了 **BAD file**。实际上此时 `cd sdcard` 是正常可以进入的。并且内部的文件都能够正常查看。而且这个问题似乎是最近才出现的。
经排查发现这个问题是由这个PR引入的：
https://github.com/RT-Thread/rt-thread/pull/7887
该PR中删除了 `dfs_file.c` 中对当前是否是根目录的判断，导致无论是否是根目录都会进入 `fs->ops->stat` 的调用，进而调用到 `f_stat`，然而在目前版本的 FATFS 的 `f_stat` 在发现当前是根目录时会返回一个 `FR_INVALID_NAME` 的错误导致最终目录信息获取失败。
```c
FRESULT f_stat (
const TCHAR* path,	/* Pointer to the file path */
FILINFO* fno		/* Pointer to file information to return */
)
{
FRESULT res;
DIR dj;
DEF_NAMBUF
/* Get logical drive */
res = mount_volume(&path, &dj.obj.fs, 0);
if (res == FR_OK) {
INIT_NAMBUF(dj.obj.fs);
res = follow_path(&dj, path);	/* Follow the file path */
if (res == FR_OK) {				/* Follow completed */
------->    if (dj.fn[NSFLAG] & NS_NONAME) {	/* …
```

[DFS_V1]修复 dfs_file_stat 一个 FATFS 根目录会失败的问题

---

components/libc/posix/io/epoll/epoll.c

Optimize the epoll code to remove restrictions on descriptors

---

components/lwp/arch/aarch64/cortex-a/lwp_arch.c
components/lwp/arch/arm/cortex-a/lwp_arch.c
components/lwp/arch/risc-v/rv64/lwp_arch.c
components/lwp/lwp.c
components/lwp/lwp_syscall.c
components/lwp/lwp_user_mm.c
components/lwp/lwp_user_mm.h

[
Current implementation has unsafe usage of `rt_memcpy` to get data from/to user space address.
Add a wrapper function `lwp_memcpy` to replace the `rt_memcpy` where address may come from user.
]

[smart] fix rt_memcpy to lwp_memcpy in smart source

---

components/libc/compilers/picolibc/syscall.c
include/rtdef.h

[
related: https://github.com/RT-Thread/rt-thread/issues/4791
]

[rtdef] support POSIX compatible errno

---

components/lwp/lwp_pid.c
components/lwp/lwp_signal.c

[
cmd kill failed with assertion
Give a default value to cmd_kill as the general system do
> NAME
kill - send a signal to a process
SYNOPSIS
kill [options] <pid> [...]
DESCRIPTION
The  default  signal for kill is **TERM**.
]

[smart] fix of cmd_kill

---

components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c
components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.h
components/dfs/dfs_v2/src/dfs_file.c
components/lwp/lwp_ipc.c

dfs_v2 下的 tmpfs 文件系统添加 truncate 功能以及 unlink 的适配

dfs_v2 tmpfs adds truncate functionality and unlink adaptations

---

tools/kconfig-frontends/frontends/mconf/mconf.c

After running "menuconfig", a message prompting you to run "make" appears, which can be confusing.  Correct prompt message to make it clear.
[
修正 menuconfig 的提示信息。
修改提示信息。
本机重新编译通过。
]

[tools] Correct prompt message

---

bsp/raspberry-pico/libraries/Kconfig

Fix SPI and I2C configuration menu. Add UART enablement option. Limit the pin selection for UART and I2C according to the datasheet.
[
优化树莓派 Pico 的 Kconfig 配置。
为 UART 添加 BSP_USING_UART0 和 BSP_USING_UART1 选项。修复 SPI 与 I2C 菜单的问题使其子选项可正确显示到子菜单中。根据数据表限制了 UART 和 I2C 的引脚选择。
本机测试通过。
]

[bsp][pico] Optimize Kconfig configuration

---

bsp/nuclei/gd32vf103_rvstar/applications/usb_conf.h
bsp/nuclei/gd32vf103_rvstar/applications/usbd_conf.h
bsp/nuclei/gd32vf103_rvstar/applications/usbh_conf.h

Nuclei sdk requires the USB configuration header file to be completed by the application in versions after 0.3.8. see https://github.com/Nuclei-Software/nuclei-sdk/pull/54 and https://github.com/Nuclei-Software/nuclei-sdk/commit/43912c1a22faeaa02220c2dea8fbc17c13735091
[
When compiling the code for Nuclei gd32vf103 rvstar, there were errors such as "usb_conf. h" where the USB configuration file could not be found. Upon inspection, it was found that Nuclei sdk removed the USB related configuration header files in version 0.3.8 and requested the application to configure it itself. In gd32vf103_ rvstar compilation test passed.
Reference: https://github.com/Nuclei-Software/nuclei-sdk/pull/54 And https://github.com/Nuclei-Software/nuclei-sdk/commit/43912c1a22faeaa02220c2dea8fbc17c13735091
] …

[bsp][nuclei] fix "usb_conf.h not found"

---

components/drivers/serial/serial_v2.c

修复阻塞模式下中断发送的逻辑问题
[
在开源之夏活动中申请了“在RT-Thread上实现稳定可靠的串口设备框架”项目，阅读源码的过程中发现了这些问题。
Commit1 ：[bug fix] 修复serial_v2逻辑问题
第一处修改理由:
一. 函数_serial_fifo_tx_blocking_buf中，需要将buffer中的数据复制到tx->fifo中，然后调用serial->ops->transmit（）进行发送，因为buffer的数量可能远大于tx->fifo的大小，因此需要多次发送。
二. 该函数多次发送的正确流程应该是:   
(1.)将数据放入ringbuffer。
(2.)调用传输函数，启动中断发送
(3.)根据所发送数据的数量更新偏移量。(从而能够发送buffer中还未发送的数据)
三. 但是原版的代码的流程是 :      
(1.)将数据放入ringbuffer。
(2.)根据所发送数据的数量更新偏移量。
(3.)调用传输函数，启动中断发送。
因此我认为源码代码逻辑有问题，跟正确的逻辑顺序相反。（注：offset初始值为0）
四. 此处代码之所以没有发生恶性的bug，经过查证, 是因为传输函数serial->ops->transmit（）函数底层调用的是 
stm32_control()，此函数的目的是开启中断。因此，传输函数serial->ops->transmit(serial, (rt_uint8_t *)buffer + offset, 
tx_fifo ->put_size, RT_SERIAL_TX_BLOCKING)中关于buffer与偏移量的实参并没有发挥作用。正式因为这些参数没有发挥作用，传输 的逻辑的问题才没有让阻塞模式下的中断发送产生毁灭性的后果，但是我认为这个问题还是要改的，所以提了这个pr。
第二处修改理由：
一. …

[serial_v2] 修复阻塞模式下中断发送的逻辑顺序问题与多线程下的竞态条件

---

components/lwp/lwp.c
components/lwp/lwp.h
components/lwp/lwp_pid.c
components/lwp/lwp_pid.h
components/lwp/lwp_syscall.c
examples/utest/testcases/mm/mm_lwp_tc.c
examples/utest/testcases/mm/test_bst_adpt.h

[
Prev implementation of lwp_new() including the create of lwp object and the pid allocation. But not every lwp object need a pid. So this patch split out part of business in lwp_new() to lwp_create() to improve the maintainability.
QEMU aarch64 with ash, xargs to test if `fork()` & `execve()` is working properly
]

[smart] replace lwp_new() with lwp_create()

---

components/lwp/lwp_ipc.c

修复 dfs_v2 下传输 fd 时，dentry或者vnode不存在时出现的问题
增加 dentry 和 vnode 的判断

Fix the problem that when dfs_v2 transmits fd, dentry or vnode does not exist

---

components/lwp/lwp_pid.c

[
Recycling of timer in lwp_free() routine may not work because of the early return before the calling to `timer_list_free()`.
Migrate the timer_list_free() ahead before early exit of sub-process.
]

[smart] fixup: lwp_free()

---

components/libc/posix/io/timerfd/timerfd.c

修复在用户态获取当前时间之后，调用到内核态再次获取当前时间，两边差值为负数，定时器不会运行的问题、

Fixed issues with timerfd

---

components/lwp/lwp_syscall.c
components/lwp/lwp_syscall.h

[
All `off_t` types will be cast to long during call to syscall(). Then interpreting it as an off_t type will be an error, especially for 32-bit architectures, since off_t is defined as off64_t in musl.
Replace `off_t` with `size_t` in `lwp_syscall.c`
QEMU vexpress-a9, aarch64
]

[smart] fixup: syscall.c

---

components/Kconfig
components/mm/Kconfig
components/mm/SConscript
components/mm/mm_memblock.c
components/mm/mm_memblock.h
examples/utest/testcases/mm/SConscript
examples/utest/testcases/mm/mm_memblock_tc.c

[
目前的系统确定可分配内存的方式是各bsp下定义page_region，然后将其加入伙伴系统的方式。这种做法较为过时，如果通过解析设备树来划分可用内存区域，则更加高效，不用再在各bsp下定义可用区域相关的宏。
该方法需要用到当前尚未实现的预留内存概念，即申请一部分区域作为对设备、内核代码、内核堆栈的预留空间。本pr就是对预留内存的实现。
借用了linux中的memblock概念，在初始化阶段通过设备树获得全部物理内存和预留内存范围，初始化结束时将在全部物理内存但不在预留物理内存的区域释放到伙伴系统中
在单元测试中加入对memblock的测试，关注了获得的物理内存信息的各种情况，测试用例全部通过。
对a1000设备树进行测试，其对内存区域解析完全正确
]

[components][mm]添加预留内存支持

---

components/dfs/dfs_v2/filesystems/cromfs/dfs_cromfs.c
components/dfs/dfs_v2/src/dfs_file.c

✨ feat(dfs_v2/cromfs): add symlink support

---

components/dfs/dfs_v2/src/dfs_file_mmap.c
components/dfs/dfs_v2/src/dfs_pcache.c

[
This patch includes following fixups:
- missing unmap of pages when they are recycled
- while instruction page of user is remapped, the neccessary synchronization of data cache to instruction cache is required for machines implementing Harvard Architecture.
]

[dfs] fixups: page cache

---

components/libc/compilers/common/ctime.c

[
使用MDK环境编译ctime时，会提示：Error: L6200E: Symbol difftime multiply defined (by difftime.o and ctime.o).
增加预编译条件，让rt-thread的licb函数difftime()，在MDK环境中禁止编译，转而使用MDK自身提供的库函数。
硬件MCU为HC32F460.
rt-thread studio 2.2.6, GNU 10.2.1, 编译通过。
MDK 5.31.0.0, ArmClang V6.14, 编译通过。
MDK 5.31.0.0, Armcc V5.06 update 6 (build 750), 编译通过。
]

[libc][time]修复MDK编译环境下difftime()函数多重定义的问题

---

components/dfs/dfs_v2/src/dfs_file_mmap.c
components/lwp/lwp.h
components/lwp/lwp_syscall.c
components/lwp/lwp_user_mm.c
components/mm/mm_anon.c
components/mm/mm_aspace.c
components/mm/mm_aspace.h
components/mm/mm_object.c
components/mm/mm_page.c
components/mm/mm_page.h
components/mm/mm_private.h
examples/utest/testcases/mm/SConscript
examples/utest/testcases/mm/aspace_map_expand.c
examples/utest/testcases/mm/aspace_unmap_range_invalid_param.c
examples/utest/testcases/mm/aspace_unmap_range_shrink.c
examples/utest/testcases/mm/aspace_unmap_range_split.c
examples/utest/testcases/mm/common.h
examples/utest/testcases/mm/lwp_mmap_expand.c
examples/utest/testcases/mm/lwp_mmap_fd.c
examples/utest/testcases/mm/lwp_mmap_fd_map_fixed_merge.c
examples/utest/testcases/mm/lwp_mmap_fd_map_fixed_split.c
examples/utest/testcases/mm/lwp_mmap_fix_private.c
examples/utest/testcases/mm/lwp_mmap_map_fixed.c
examples/utest/testcases/mm/mm_api_tc.c
examples/utest/testcases/mm/mm_lwp_tc.c
examples/utest/testcases/mm/rt_ioremap.c
examples/utest/testcases/mm/test_aspace_api.h
examples/utest/testcases/mm/test_aspace_api_internal.h
examples/utest/testcases/mm/test_bst_adpt.h
libcpu/aarch64/SConscript

[
- replace varea pgmgr
- fixup of dfs
- sync test cases
Previous implementation of page recycling in varea slows down the
searching of free page especially with the large varea region. This
patch use a page table entry query instead to improve the performance
on varea reconstructions.
Also fixup: dfs mmap
The return value of DFS mmap is not guarantee to be identical of the
kernel mmap address, since the varea can changed during the mmap.
So this patch use the address as the return value directly.
]

[smart] replace varea pgmgr and fixup of dfs mmap

---

components/libc/compilers/common/ctime.c
components/lwp/lwp_ipc.c
include/rthw.h
include/rtthread.h

[
Fixup of data racing in shared timer id list of `ctime.c`
]

[ctime] fixup of data racing

---

components/dfs/dfs_v2/filesystems/elmfat/00history.txt
components/dfs/dfs_v2/filesystems/elmfat/00readme.txt
components/dfs/dfs_v2/filesystems/elmfat/dfs_elm.c
components/dfs/dfs_v2/filesystems/elmfat/ff.c
components/dfs/dfs_v2/filesystems/elmfat/ff.h
components/dfs/dfs_v2/filesystems/elmfat/ffconf.h
components/dfs/dfs_v2/filesystems/elmfat/ffunicode.c

[
update elmfat from r14b to r15
update elmfat from r14b to r15
A1000
]

update elmfat from r14b to r15

---

components/libc/compilers/common/ctime.c

[libc] [ctime] fix rt_timespec_to_tick fun internal data overflow

---

components/libc/compilers/common/cstdlib.c

[
The purpose of this PR is to submit the  PR to Fixes #7426 
and add comments in the source code to improve the readability and understandability of the code and contribute to the project.
I have added detailed comments to rt-thread\components\libc\compilers\common\cstdlib.c
This PR is mainly for comments on the source code and does not involve specific functional changes, so there is no specific testing environment.
]

Add comments to the rt-thread\components\libc\compilers\common\cstdlib.c

---

components/dfs/dfs_v2/filesystems/cromfs/dfs_cromfs.c
components/dfs/dfs_v2/src/dfs_pcache.c

[
添加 cromfs 的mmap支持，不然smart用户态跑不了
]

✨ feat(dfs_v2/cromfs): add cromfs mmap

---

components/dfs/dfs_v2/src/dfs.c
components/lwp/libc_musl.h
components/lwp/lwp.c
components/lwp/lwp.h
components/lwp/lwp_pid.c
components/lwp/lwp_pid.h
components/lwp/lwp_pmutex.c
components/lwp/lwp_signal.c
components/lwp/lwp_syscall.c
components/lwp/lwp_syscall.h
components/lwp/lwp_user_mm.c
components/mm/mm_anon.c
components/mm/mm_object.c
components/mm/mm_page.c
components/mm/mm_private.h
examples/utest/testcases/mm/mm_lwp_tc.c
libcpu/aarch64/SConscript
libcpu/aarch64/common/trap.c

[
The previous implementation of lwp recycling is all done in `lwp_free()`,
which suspends the parent process for a long time in `wait(2)` until all the resources
is released, especially that `lwp_free()` is running on a defunct thread with
a extremely low priority.
If the parent process never wait for its children, all the resources is holding
until the parent process exits, which decreases the throughput of the system.
This patch includes:
- Separate the process of lwp recycling into 2 phases
- Codes cleanup in `mm_object.c` & `mm_anon.c`
- Fix the data racing problem in pid/tid management
]

[smart] fixup of lwp recycling and mm varea

---

components/lwp/lwp_pid.c
components/lwp/lwp_syscall.c

🐞 fix: fix taskset

---

include/rtservice.h

【转移Gitee提交PR https://gitee.com/rtthread/rt-thread/pulls/644 】
[
[virteman](https://gitee.com/virteman)-virteman virteman create on 2023-10-11 17:33
拉取/合并请求描述：
[
因rt_slist_for_each_entry宏不能正常调用，在实际开发中去循环再调用rt_slist_entry很不简洁，所以修改了rt_slist_for_each_entry宏中关于链表next的判空处理。目前相关代码在GD32系统的MCU上均能正常工作，相关应用也在生产产品中使用大半年了。
]
]
]

[kernel] 解决rt_slist_for_each_entry宏不能正常遍历slist链表中元素的问题

---

src/kservice.c

[
例如：strtol 0xffff000012345678。转换后回变成0x7fffffffffffffff
]

[kservice] 修正backtrace命令转换无符号数不正常的问题

---

components/libc/compilers/picolibc/SConscript
components/libc/compilers/picolibc/exit.c
components/libc/compilers/picolibc/fcntl.h
components/libc/compilers/picolibc/iob.c
tools/gcc.py

[
现阶段的绝大部分的gcc编译工具链默认都是使用newlibc，crosstool-ng可以制作
带picolibc的gcc编译工具链, 使用该工具链接rt-thread无法编译编译
增加部分缺失的picolibc依赖接口:https://github.com/picolibc/picolibc/blob/main/doc/os.md
- 使用crosstool-ng生成的gcc(picolibc)工具链编译，qemu-vexpress-a9 正常启动运行
- llvm-arm能正常编译stm32f407-rt-spark 
]

[libc][picolibc] improve gcc picolibc support

---

libcpu/aarch64/common/trap.c
src/kservice.c

[
修复aarch64上backtrace打印接口，LOG_X接口在异步ulog环境下不能正常看到trace信息，所以修改为rt_kprintf直接输出。
]

fix aarch64 backtrace print.

---

components/fal/inc/fal_def.h
components/fal/src/fal_flash.c

[
原来的fal对 flash不均匀分布的flash不友好，比如stm32. 明明是一块地址连续的 flash，需要注册出来3个flash设备，fal的分区还不能跨 flash 使用。导致app分区只能放在 128K起始的地址上，造成flash的浪费
为 fal 添加 blocks 机制，支持添加特殊的 block 定义。
使用方式如下，添加了具体的flash的blocks定义，4个16K的blk，1个64K，7个128K。
```c
const struct fal_flash_dev stm32_onchip_flash =
{
"onchip",
STM32_FLASH_START_ADRESS,
(1024 * 1024),
(16 * 1024),
{
NULL,
fal_flash_read,
fal_flash_write,
fal_flash_erase,
},
8,
{
{ .size = 0x4000, .count = 4 },
{ .size = 0x10000, .count = 1 },
{ .size = 0x20000, .count = 7 },
{ 0 },
},
};
```
在 星火1号上测试通过。
]

[fal] Add blocks mechanism to fal.

---

bsp/hc32/libraries/hc32_drivers/drv_adc.c
bsp/hc32/libraries/hc32_drivers/drv_can.c
bsp/hc32/libraries/hc32_drivers/drv_pwm_tmra.c
bsp/hc32/libraries/hc32_drivers/drv_spi.c

[
1. hc32驱动函数和rtt函数声明之间的参数类型不一致，在mdk编译时产生警告。
2. hc32的can设备，在注册时就把can中断使能了。导致can设备在打开前，就会产生中断。
3. hc32的pwm驱动，不支持PWM_CMD_SET_PERIOD和PWM_CMD_SET_PULSE指令，导致rt_pwm_set_pulse()函数返回失败。
1. 修改hc32驱动函数参数类型和声明一致。
2. 注册can设备时主动禁止can中断，因为打开设备时会主动打开中断。
3. 修改pwm驱动，增加PWM_CMD_SET_PERIOD和PWM_CMD_SET_PULSE指令支持。
硬件MCU为HC32F460.
rt-thread studio 2.2.6, GNU 10.2.1, 编译通过。
MDK 5.31.0.0, ArmClang V6.14, 编译通过。
]

[bsp][hc32]优化can驱动和pwm驱动

---

components/finsh/finsh.h

FINSH: 优化MSH宏定义

---

bsp/stm32/stm32h750-artpi/board/Kconfig
bsp/stm32/stm32h750-artpi/board/port/filesystem.c

[
为 ART-PI 开发板添加如下功能：ART-Pi 外部 SPI Flash 使用 elmfatfs 文件系统
原代码是先用 romfs 文件系统挂 /flash 和 /sdcard 两个目录，然后再用 littlefs 系统挂 flash 到 /flash下面
我想这样改：通过 RT_USING_DFS_ROMFS 和 RT_USING_DFS_ELMFAT 控制代码，如果开了elmfat，则会使 ART-Pi 外部 SPI Flash 使用 elmfatfs 文件系统，反之则功能和原代码相同，不影响原功能
修改后代码食用指南：
开启 DFS 以及 elmfatfs 文件系统，并将扇区改成 4096 （artpi 的板载外部 spi flash 的 sector 大小就是4096）。
开启 SPI Flash filesystem：
然后保存编译下载，即成功让外部 SPI Flash 使用 elmfatfs 文件系统：
RT-Thread Version: latest
RT-Thread Env Version: 1.3.5
OS: Windows 10
IDE: Keil5
]

enable art-pi spi flash use elmfatfs

---

bsp/stm32/libraries/HAL_Drivers/drv_pulse_encoder.c

[
文件 drv_pulse_encoder.c 中
```
rt_int32_t pulse_encoder_get_count(struct rt_pulse_encoder_device *pulse_encoder)
{
struct stm32_pulse_encoder_device *stm32_device;
stm32_device = (struct stm32_pulse_encoder_device*)pulse_encoder;
return (rt_int32_t)((rt_int16_t)__HAL_TIM_GET_COUNTER(&stm32_device->tim_handler) + stm32_device->over_under_flowcount * AUTO_RELOAD_VALUE);
}
```
对编码器数值的计算可能存在问题：
```
(rt_int32_t)((rt_int16_t)__HAL_TIM_GET_COUNTER(&stm32_device->tim_handler) + stm32_device->over_under_flowcount * AUTO_RELOAD_VALUE);
```
```
rt_device_read(dev, 0, (void *)&pulse_value, 1);
```
|CNT|OV|测试结果|预期结果|
|-|-|-|-|
|0x0000|0|0|0|
|0x7FFF|-1|0|-1|
|0x7FFF|0|32767|32767|
|0x0000|1|32767|32768|
其中`AUTO_RELOAD_VALUE`为重装载值:0x7FFF， 作为乘数应当+1
未使用特定的BSP包，仅在测试工程中使用了 rt_device 驱动框架以及 …

[bsp][stm32] 修复 encoder驱动 编码器数值的计算问题

---

components/lwp/lwp_syscall.c
components/net/sal/include/sal_socket.h
components/net/sal/src/sal_socket.c

[
修复 https://github.com/RT-Thread/rt-thread/pull/8293
- BSP:
- .config:
- action:
]

修复 #8293 问题

---

bsp/stm32/libraries/HAL_Drivers/SConscript
bsp/stm32/libraries/HAL_Drivers/drv_common.c
bsp/stm32/libraries/HAL_Drivers/drv_common.h
bsp/stm32/libraries/STM32L4xx_HAL/SConscript
bsp/stm32/stm32l475-atk-pandora/Kconfig
bsp/stm32/stm32l475-atk-pandora/applications/main.c
bsp/stm32/stm32l475-atk-pandora/board/Kconfig
bsp/stm32/stm32l475-atk-pandora/board/SConscript
bsp/stm32/stm32l475-atk-pandora/board/board.c
bsp/stm32/stm32l475-atk-pandora/board/board.h
bsp/stm32/stm32l475-atk-pandora/board/nano/drv_console.c
components/Kconfig
src/Kconfig

1. Nano 增加 串口（console）的适配
2. STM32潘多拉支持nano版本的LED闪烁与console适配
[
- BSP:
- .config:
- action:
]

[stm32][nano] support nano version for stm32 pandora

---

bsp/rockchip/rk3568/driver/drv_uart.c

https://wiki.friendlyelec.com/wiki/index.php/NanoPi_R5S/zh 文档中，串口波特率为 1500000，所以将原先的115200改为1500000
- BSP: rockchip/rk3568
- .config:
- action:
]

[bsp][rk3568] 修改串口波特率

---

components/dfs/dfs_v2/filesystems/devfs/devfs.c
components/dfs/dfs_v2/filesystems/elmfat/dfs_elm.c
components/dfs/dfs_v2/include/dfs.h
components/dfs/dfs_v2/include/dfs_file.h
components/dfs/dfs_v2/src/dfs.c
components/dfs/dfs_v2/src/dfs_dentry.c
components/dfs/dfs_v2/src/dfs_file.c
components/dfs/dfs_v2/src/dfs_file_mmap.c
components/dfs/dfs_v2/src/dfs_pcache.c

[
- BSP:
- .config:
- action:
]

sync update dfs v2.

---

bsp/wch/risc-v/Libraries/ch32_drivers/drv_gpio.c
bsp/wch/risc-v/ch32v103r-evt/board/board.c
bsp/wch/risc-v/ch32v208w-r0/board/board.c
bsp/wch/risc-v/ch32v307v-r1/board/board.c

Fix #8325
在Linux下构建项目时，`rt_hw_i2c_init`先于`rt_hw_pin_init`被调用，导致崩溃。
在`rt_hw_i2c_init`中显式调用`rt_hw_pin_init`，确保`pin`模块先于`i2c`模块初始化。
- BSP:  在私有的BSP上验证过(version 4.1.1)，master分支未测试

ch32_drivers: call rt_hw_pin_init in rt_hw_i2c_init explicitly

---

bsp/raspberry-pico/Kconfig
bsp/raspberry-pico/SConstruct
bsp/raspberry-pico/applications/SConscript
bsp/raspberry-pico/applications/arduino_main.cpp
bsp/raspberry-pico/applications/arduino_pinout/README.md
bsp/raspberry-pico/applications/arduino_pinout/SConscript
bsp/raspberry-pico/applications/arduino_pinout/pins_arduino.c
bsp/raspberry-pico/applications/arduino_pinout/pins_arduino.h
bsp/raspberry-pico/link.ld

[
为树莓派pico开发板对接 rtduino
- BSP:
- .config:
- action:
]

[bsp][pico] add rtduino

---

src/idle.c

[
修复上次 #8042 中所说的idle_hook_list没有加锁的情况。删除了_idle_inited变量，这变量是上回#8042 调试所加的，理论上永远不会进入到_idle_inited的if 语句分支
- BSP:
- .config:
- action:
]

✨ feat(idle): add _hook_spinlock, rm _idle_inited

---

examples/network/tcpclient.c
examples/network/tcpserver.c

[
- BSP:
- .config:
- action:
]

[examples]更正tcp例程中recv/send返回值判断

---

components/drivers/core/bus.c
components/drivers/core/dm.c
components/drivers/core/platform.c
components/drivers/core/platform_ofw.c
components/drivers/include/drivers/core/bus.h
components/drivers/include/drivers/core/dm.h
components/drivers/include/drivers/core/driver.h
components/drivers/include/drivers/ofw.h
components/drivers/include/drivers/ofw_fdt.h
components/drivers/include/drivers/ofw_io.h
components/drivers/include/drivers/platform.h
components/drivers/ofw/base.c
components/drivers/ofw/fdt.c
components/drivers/ofw/io.c
components/drivers/ofw/ofw.c
components/drivers/ofw/ofw_internal.h
include/rtdef.h

[
- 完善设备模型，并修复部分设备驱动注册之后，无法进入 probe 函数问题
- BSP: 
- .config:
- action:
]

[drivers][core] 完善设备模型

---

components/utilities/Kconfig
components/utilities/ulog/backend/console_be.c
components/utilities/ulog/ulog.c
examples/utest/testcases/kernel/Kconfig
examples/utest/testcases/kernel/SConscript
examples/utest/testcases/kernel/mtsafe_kprint_tc.c
include/rtthread.h
src/Kconfig
src/kservice.c
tools/ci/cpp_check.py

[
- avoid data race in rt_kputs/kprintf and ulog service
BEFORE
```text
ThThiTis is ts is thread 0xffff0000004hhr6e3a0eis ia
sd  thre0adxf 0xfffffff0000000000046e046e33a0a
0
ThisTh iiss  Thtisih thrs is terhad 0xfffread f0ea0This is thread x0xffffd000000000f 0xf004fff4ff00006613af0100468
00313a8
a8
read 0s46This  isd This isatis et8 thhhr
reaxeffd 0xffff000ad 0xffThis000000470970
This 0is0 thread0000000 467230
is xft467hreafff00Thd 0xffff0000003f5220
i0220
s is 0th0046TrThhisf68 ieias8
thread 0xd s0ff isxfThis ff ti0ffhres0f0 t000a0d 0x000468f00468518hr51fff
8
0000ead 000xf46Th5fff000Thfis is thr0is i07804e
s6a t3978
dhr 0Thisead is thr 0xexad 0fffffxfff0ffff000000469800
000000046009800
00469800
```
AFTER
```text
This is thread 0xffff000000462690
This is thread 0xffff0000004732c0
This is …
```

[kservice] MT-safe console support (kprintf/kputs)

---

components/drivers/include/drivers/spi.h
components/drivers/spi/qspi_core.c
components/drivers/spi/spi_core.c

[
#8527 
- BSP:
- .config:
- action:
]

[qspi]修复qspi配置未生效问题

---

components/net/at/Kconfig
components/net/at/at_socket/at_socket.c
components/net/at/include/at.h
components/net/at/src/at_cli.c
components/net/at/src/at_client.c
components/net/at/src/at_server.c
components/net/sal/impl/af_inet_at.c

[
1.优化at server endmark判断，支持自动识别'\r''\n'"\r\n"。
2.优化at_recvfrom,修复大数据量时sem多次释放造成的接收错误。
3.修复at组件中可能存在的内存泄露。
4.优化部分代码逻辑，减少冗余代码。
- BSP: bsp\stm32\stm32l475-atk-pandora
- .config:CONFIG_BSP_USING_AT_ESP8266 
- action:
]

[components][at]update at

---

bsp/qemu-virt64-aarch64/applications/main.c
bsp/qemu-virt64-aarch64/drivers/secondary_cpu.c
components/mm/mm_aspace.c
libcpu/aarch64/common/backtrace.c
libcpu/aarch64/common/gicv3.c
libcpu/aarch64/common/setup.c
src/scheduler_mp.c

[
- Fix NULL pointer access
- gtimer init failed when enable gicv3
- check NULL pointer before access
- using virtual address for `rt_page_install()`
- add `arm_gic_redist_init(0, 0)` for qemu secondary bootup
- using `rt_kprintf` instead of `printf`
- BSP:
- .config:
- action:
]

[fixup] check NULL pointer before access

---

components/drivers/spi/qspi_core.c
components/drivers/spi/spi_core.c

[
#8556 
将cs_pin初始化控制放在配置是否相同判断之前。
注意，在每次挂载设备后需要及时调用rt_spi_configure()以便正确初始化cs_pin
- BSP:
- .config:
- action:
]

[spi]修复spi总线挂载多设备通信可能失败问题

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_eth.c

[
问题复现：
Issue[#8611](https://github.com/RT-Thread/rt-thread/issues/8611)
对于drv_eth.h，看了最新的代码，3个月前有人提交了PR，我们的方案是一样的，在drv_eth.h增加相关的宏定义：
```c
#elif defined(PHY_USING_YT8512C)
/*  The PHY interrupt source flag register. */
#define PHY_INTERRUPT_FLAG_REG      0x13U
/*  The PHY interrupt mask register. */
#define PHY_INTERRUPT_MASK_REG      0x12U
/*  The PHY auto nego and link change mask. */
#define PHY_INT_MASK                (1<<15)|(3<<10)
/*  The PHY status register. */
#define PHY_Status_REG              0x11U
#define PHY_100M_MASK               (1<<14)
#define PHY_FULL_DUPLEX_MASK        (1<<13)
#define PHY_Status_SPEED_10M(sr)    (!PHY_Status_SPEED_100M(sr))
#define PHY_Status_SPEED_100M(sr)   ((sr) & PHY_100M_MASK)
#define PHY_Status_FULL_DUPLEX(sr)  ((sr) & PHY_FULL_DUPLEX_MASK) …
```

[bsp][stm32] eth driver support phy YT8512C

---

bsp/cvitek/drivers/drv_pwm.c

[
现在PWM驱动输出与目标输出极性相反。
CV1800B 芯片支持PWM信号输出并支持极性反转。当POLARITY寄存器设置为1时HLPERIOD寄存器代表高电平拍数，当POLARITY寄存器设置为0时HLPERIOD寄存器代表低电平拍数。目前cvi_pwm_set_config()中将POLARITY设为0，代表HLPERIOD存储的为低电平拍数，而在用户调用时，通常会认为pulse为高电平占用的时间。所以造成了极性与目标不一致的现象。
在cvi_pwm_set_config()中将POLARITY配置为高电平。
- BSP:
- .config:
- action:
]

[bsp][CV1800B] fix cv1800b polarity reversal error

---

components/drivers/Kconfig
components/drivers/wlan/wlan_mgnt.c

[
- 添加`RT_WLAN_JOIN_SCAN_BY_MGNT`配置支持（该功能在c代码中是支持的，但是没有这个宏定义的支持）
- 另外在`rt_wlan_connect`函数中使用了`INVALID_INFO`宏清除`rssi`为`0`，而在`rt_wlan_join_scan_callback`函数中未判断`rssi`属于无效的状态导致无法copy新的`WiFi信息`到`目标WiFi信息`
以下是未修复时的现象:
```shell
msh />wifi scan
SSID                      MAC            security    rssi chn Mbps
------------------------------- -----------------  -------------- ---- --- ----
WirelessNet                     04:9f:ca:98:a8:e0  WPA2_MIXED_PSK -79    1  144
111111                          ec:26:ca:eb:c0:84  WPA2_AES_PSK   -68    1  450
405                             ec:26:ca:fa:c0:d2  WPA2_AES_PSK   -77    1  450
Xiaomi_9535                     a4:39:b3:b1:95:36  WPA2_MIXED_PSK -90    2  144
EvlerHome                       c8:ea:f8:eb:cd:6e  WPA2_AES_PSK   -54    5  300
msh />wifi join …
```

[wlan] add the wlan join scan function

---

components/drivers/wlan/wlan_cmd.c

[
在执行`wifi scan`命令时，扫描出来的结果会重复打印，我测试在`lts-v4.1.x`是不存在这个问题的。
重复打印的问题如下：
```shell
msh />wifi scan
SSID                      MAC            security    rssi chn Mbps
------------------------------- -----------------  -------------- ---- --- ----
EvlerHome                       c8:ea:f8:eb:cd:6e  WPA2_AES_PSK   -48    5  300
EvlerHome                       c8:ea:f8:eb:cd:6e  WPA2_AES_PSK   -47    5  300
ES-650733                       58:48:49:05:84:5d  WPA2_AES_PSK   -86    9   72
TP-LINK_403                     b8:f8:83:af:4c:61  WPA2_AES_PSK   -67   11  450
TP-LINK_403                     b8:f8:83:af:4c:61  WPA2_AES_PSK   -69   11  450
312                             20:6b:e7:81:fc:1b  WPA2_AES_PSK   -62   11  450
EvlerHome                       c8:ea:f8:eb:cd:6e  WPA2_AES_PSK   -46    5 …
```

[wlan][cmd] fixed a duplicate issue with the wifi scan command

---

components/libc/cplusplus/cpp11/atomic_8.c

[
Add GCC generalized atomic operation function
override four gcc built-in functions as follows:
void __atomic_load (size_t size, void *mem, void *return, int model);
void __atomic_store (size_t size, void *mem, void *val, int model);
void __atomic_exchange (size_t size, void *mem, void *val, void *return, int model);
bool __atomic_compare_exchange (size_t size, void *obj, void *expected, void *desired, int success, int failure);
- BSP:
bsp\stm32\stm32f407-atk-explorer
- .config:
#define RT_USING_CPLUSPLUS
#define RT_USING_CPLUSPLUS11
- action:
]

Add GCC generalized atomic operation function

---

components/libc/posix/io/aio/aio.c

[
Fix the issue of incorrect return of invalid parameters in aio_write
]

Fix the issue of incorrect return of invalid parameters in aio_write

---

components/drivers/pin/pin_ofw.c

fix pin ofw variable init.

---

src/SConscript

close: #8494
[
- BSP:
- .config:
- action:
]

[gcc] add footprint information when compiling

---

components/finsh/finsh.h

新增加的二级命令使用方式没有清晰的描述
- 功能实现PR：https://github.com/RT-Thread/rt-thread/pull/8086
- 补充优化PR：https://github.com/RT-Thread/rt-thread/pull/8251
- 使用二级命令的例子：https://github.com/RT-Thread/rt-thread/pull/8398
- 相关issue：https://github.com/RT-Thread/rt-thread/issues/8691
[
- BSP:
- .config:
- action:
]

[msh] add comment for secondary-commands

---

components/drivers/ofw/base.c
components/drivers/ofw/irq.c
components/drivers/pic/pic_rthw.c
components/libc/compilers/common/ctime.c
components/lwp/lwp_internal.c
components/lwp/lwp_syscall.c
components/mm/mm_page.c
libcpu/aarch64/common/SConscript
libcpu/aarch64/common/interrupt.c
libcpu/aarch64/common/mmu.c
tools/ci/cpp_check.py

[
- fixup aarch64 UMP BSP compiler error
- and some compiler warnings
- BSP:
- .config:
- action:
]

[fixup] aarch64 UMP compiler error

---

components/dfs/dfs_v2/src/dfs_file.c

fix symlink

---

components/fal/src/fal_rtt.c

打开文件系统后,出现编译警告:
```
CC build\kernel\components\fal\src\fal_rtt.o
E:\Project\rt-thread\components\fal\src\fal_rtt.c:281:5: warning: initialization of 'rt_ssize_t (*)(struct rt_mtd_nor_device *, rt_off_t,  rt_uint8_t *, rt_size_t)' {aka 'int (*)(struct rt_mtd_nor_device *, long int,  unsigned char *, unsigned int)'} from incompatible pointer type 'rt_ssize_t (*)(struct rt_mtd_nor_device *, rt_off_t,  rt_uint8_t *, rt_uint32_t)' {aka 'int (*)(struct rt_mtd_nor_device *, long int,  unsigned char *, long unsigned int)'} [-Wincompatible-pointer-types]
281 |     mtd_nor_dev_read,
|     ^~~~~~~~~~~~~~~~
E:\Project\rt-thread\components\fal\src\fal_rtt.c:281:5: note: (near initialization for '_ops.read')
E:\Project\rt-thread\components\fal\src\fal_rtt.c:282:5: warning: initialization of 'rt_ssize_t …
```

[fal]修正类型不匹配

---

components/lwp/lwp.c
components/lwp/terminal/freebsd/tty_pts.c
components/lwp/terminal/tty_ptmx.c

[
- Fixup devfs porting layer of terminal
- Fixup logging level of init program not found
- Fixup setting of signal protection flag of init process
Using file->data to preserve the pseudo terminal device for pty file
instead of vnode->data.
- BSP:
- .config:
- action:
]

[smart] fixup devfs porting layer of terminal

---

components/drivers/ipc/workqueue.c
components/drivers/serial/serial_tty.c
include/rtdef.h
src/timer.c

[
之前的workqueue/timer有如下问题
1. rt_workqueue_cancel_work在对work的timer执行停止操作未判断返回值。若在timer线程执行work的timer的回调函数时，另一线程调用rt_workqueue_cancel_work停止该work的timer,此时timer_stop应失败，但之前未考虑此情况，仍按cancel_work成功的逻辑进行
2. 在timer线程执行某timer的timer_out函数时，若另一线程对该timer执行rt_timer_start,应让其执行失败。否则会出现数据混乱。若该线程执行了timer_start又立即让其stop，就会触发ASSERT
3. 之前rt_workqueue_submit_work中调用了rt_timer_start,但该函数不在spinlock的保护范围中，与其他对workqueue数据结构修改操作不是原子的。若执行了spinlock保护范围内操作后调度出去，可能出现数据不一致情况。
1.rt_workqueue_cancel_work中判断rt_timer_stop是否成功
2. 增加timer的执行状态RT_TIMER_FLAG_PROCESSING。该状态下使timer_start执行失败
rk3588
- BSP:
- .config:
- action:
]

[components][drivers]fix workqueue bug

---

components/drivers/can/can.c

[
原来的CAN close中先释放fifo后关闭CAN中断，可能导致释放fifo后且关闭CAN中断前来CAN中断，此时rt_hw_can_isr可能在RT_ASSERT(tx/rx_fifo != RT_NULL)断言失败
调整顺序，先关中断后把资源释放
- BSP:
- .config:
- action:
]

[components][drivers]close can irq before release fifo

---

components/drivers/clk/clk.c
components/drivers/ofw/base.c
components/drivers/ofw/irq.c

[
- BSP:
- .config:
- action:
]

[components][drivers]fix some uninitialize err

---

src/thread.c

[问题]  创建相同优先级的线程，线程时间片设置为0，在rt_tick_increase中会将该线程的时间片变为最大
若存在俩个线程使用轮询的方式调度，则首先启动的线程会长时间占用CPU
[解决办法]  在创建线程时添加对时间片的断言检查
[测试环境]  art-pi + MDK5

[fix] 添加创建线程函数时间片参数检查

---

bsp/cvitek/drivers/SConscript

- 问题：PIN设备未初始化
- 原因：`BSP_USING_CV18XX`仅在scons脚本中使用，Kconfig中不存在
- 修正：改为Kconfig中存在的宏： `BSP_USING_CV180X`
- 验证平台：`milkv-duo`

[bsp][cvitek] 修正PIN设备的控制宏

---

libcpu/arm/cortex-m7/cpu_cache.c

在未使能 `RT_USING_CACHE` 时，`cpu_cache.c` 的函数定义会被替换为空，加上宏开关解决这个问题

[libcpu] fix function replaced by macro

---

tools/building.py
tools/env.py
tools/utils.py

在building.py中增加工具链探测，它会在env/sdk包中，根据rtconfig.CC设置进行探测。
* 会优先使用已有配置；
* 当已有配置的工具链不存在时，会尝试在env/sdk中进行探测：
* 探测成功会使用sdk中的工具链。
* 可以配合新版本env来使用sdk包

[tools] Add toolchain detection in sdk packages

---

tools/building.py

修正EXEC_PATH存在，但EXEC_PATH/CC不存在的问题 <Linux下存在这样的问题>。

[tools] fix EXEC_PATH exists, but the CC does not.

---

components/drivers/ktime/inc/ktime.h
components/drivers/ktime/src/hrtimer.c
components/libc/compilers/common/ctime.c

[
使用ktimer进行sleep，原先代码每次sleep前后都要init/detach，导致sleep时间较期望值多，移除后抖动可以降低。
让使用者来detach hrtimer
- BSP: rk3588
- .config:
- action:
]

[components][drivers]improve ktimer sleep

---

tools/menukconfig.py

[
Fix menuconfig error on vscode console on the remote server.
```text
Error: unsupported locale setting:
File "xxx", line 26:
objs = PrepareBuilding(env, RTT_ROOT, has_libcpu = False)
File "xxx/rt-thread/tools/building.py", line 342:
menuconfig(Rtt_Root)
File "xxx/rt-thread/tools/menukconfig.py", line 269:
menuconfig._main()
File "xxx/rt-thread/tools/kconfiglib/menuconfig.py", line 663:
menuconfig(standard_kconfig(__doc__))
File "xxx/rt-thread/tools/kconfiglib/menuconfig.py", line 707:
locale.setlocale(locale.LC_ALL, "")
File "/usr/lib/python3.8/locale.py", line 608:
return _setlocale(category, locale)
```
Check if the $LANG in the supported locales and reset the environment variable
to POSIX (which is considered the most compatible way) if that is not the case.
- BSP:
- .config:
- …

[tools] fix menuconfig error on vscode console

---

bsp/stm32/libraries/HAL_Drivers/drivers/config/f4/i2c_hard_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_hard_i2c.c

[
我在STM32F429IGTx设备上使用硬件i2c驱动程序师遇到以下几个问题：
1. 语法错误：drv_hard_i2c.c 行67、68中i2c_handle未正常替换过来，估计是上个版本对变量重命名后因为宏定义忽略了此处修改；
2. 语法错误：drv_hard_i2c.c 行326中缺少一个"}"导致编译出错；
3. 初始化i2c设备过程中对双地址选项进行设置时（i2c_handle->Init.OwnAddress2Masks = I2C_OA2_NOMASK），STM32F4系列SOC没有这个配置定义，于是我直接将双地址模式关闭了（i2c_handle->Init.DualAddressMode = I2C_DUALADDRESS_DISABLE）；
4. 初始化i2c设备（DMA方式）过程中发现i2c_hard_config.h文件中未定义DMA通道配置；
5. i2c设备传输过程中，发现i2c从机收不到数据，i2c主机也收不到数据，最终问题定位至HAL_I2C_Master_Seq_Receive_xx、HAL_I2C_Master_Seq_Transmit_xx系列接口调用中，传参将设备地址左移了一位(msg->addr<<1)，不太理解这个做法，个人认定是个bug，感觉上层传过来的i2c从机设备地址不应进行修改，应直接透传；
主要补丁如下：
1. 修复硬件i2c驱动代码中语法错误（drv_hard_i2c.c行67、68、326）；
2. 关闭默认i2c双地址模式（drv_hard_i2c.c行75：I2C_DUALADDRESS_DISABLE）；
3. 修改硬件i2c调用HAL库传输接口从机设备地址传参，原代码中从机设备地址传参为：(msg->addr<<1)，修改为：msg->addr（drv_hard_i2c.c行206、210、231、235、 …

[bsp][stm32] fix bugs of i2c hardware drivers, test on STM32F429IGTx

---

components/drivers/ofw/fdt.c

[
在调用fdt_scan_memory对设备树的内存进行解析后，会根据保留内存对整个内存重新做出一些调整。如下图(添加了一些打印信息)：
如图所示，调整后出现了一个起始地址等于结束地址的一个无效mem_region。
```
[I/rtdm.ofw]   (NULL)           [0x00000000441581a0, 0x00000000441581a0]
```
排查发现是对case 0情况的判断条件不妥。
```
/*
* case 0:                      case 1:
*  +------------------+             +----------+
*  |      memory      |             |  memory  |
*  +---+----------+---+         +---+----------+---+
*      | reserved |             |     reserved     |
*      +----------+             +---+----------+---+
*
* case 2:                      case 3:
*  +------------------+                +------------------+
*  |      memory      |                |      memory      |
*  +--------------+---+------+  +------+---+--------------+
*                 | reserved |  | reserved |
* …
```

[drivers][ofw] Fixed fdt_scan_memory() memory adjustment bug

---

src/mem.c

[
当使用SLAB时，控制台调用memcheck和memtrace的将会异常
memcheck和memtrace时判断当前内存算法为小内存算法才去执行判断逻辑
- BSP:bsp/stm32/stm32H750
- .config:
CONFIG_RT_USING_SLAB_AS_HEAP=y
or
CONFIG_RT_USING_SMALL_MEM_AS_HEAP=y
- 验证使用SLAB算法时,memcheck和memtrace不打印不生效不执行
- 验证使用small mem算法时,memcheck和memtrace生效
]

[mem]When using SLAB, calls to memcheck and memtrace will be abnormal

---

bsp/gd32/arm/libraries/gd32_drivers/drv_usart_v2.c

[
`dma_recv_isr` 的中断调用源有两个：
1. 串口 IDLE 中断
2. DMA 完成半完成中断
因此，如果同时使能了这两个中断，并且中断优先级不同的情况下（目前这是默认情况），一旦出现中断嵌套并且出现嵌套的位置为 `recv_len` 计算后（并且 `recv_len` 不为零），那么就会出现其中一个中断处理已经准备携带不为零的 `recv_len`  进入 `rt_hw_serial_isr`（进入后会更新 RB 索引），但被另一个中断打断，并且这个嵌套的中断同样会计算出与上一个中断同样的 `recv_len` 并进入 `rt_hw_serial_isr` 更新 RB 索引，可以预见这种情况下 RB 索引会被更新两次，从而出现数据异常。并且这个异常一旦出现，数据将永久错位无法自动恢复。
使用开关中断来创建一个临界区，保护 `recv_len` 在计算过程中不会出现重入，这样即使出现中断在计算前出现嵌套并触发两次计算，由于第一次计算时已经更新了 `uart->dma.last_index`，第二次计算时 `recv_len` 会为零，自然也就不会进入 `rt_hw_serial_isr` 从而出现 RB 索引更新两次的情况。
GD32450Z-EVAL
- BSP:  bsp/gd32/arm/gd32450z-eval
- .config:
- action:
]

[bsp][gd32] 修复串口驱动中由于可能的中断嵌套而导致RB索引异常的问题

---

include/rtthread.h
src/clock.c
src/cpu_mp.c
src/idle.c
src/signal.c
src/timer.c
tools/ci/cpp_check.py

[
rt_hw_cpu_id() is an unsafe API that most codes should not use
directly. It's error-prone because it must be used in the proper
context, otherwise, it can lead to errors and unpredictable behavior.
This patch adds a wrapper API for rt_hw_cpu_id() to address this
risk. It includes the context-checking functionality and provides
a safer alternative for obtaining CPU IDs, ensuring it is used
correctly within the appropriate context.
- BSP: Tested on UP/MP(dual-core) vexpress-a9
- .config:
- action:
]

[src] add rt_hw_cpu_id() wrapper API

---

components/drivers/Kconfig
components/drivers/include/ipc/completion.h
components/drivers/ipc/Kconfig
components/drivers/ipc/SConscript
components/drivers/ipc/completion_comm.c
components/drivers/ipc/completion_mp.c
components/drivers/ipc/completion_up.c
components/drivers/ktime/inc/ktime.h
components/drivers/ktime/src/hrtimer.c
examples/utest/testcases/Kconfig
examples/utest/testcases/drivers/ipc/Kconfig
examples/utest/testcases/drivers/ipc/SConscript
examples/utest/testcases/drivers/ipc/completion_tc.c
examples/utest/testcases/drivers/ipc/completion_timeout_tc.c
include/rthw.h
libcpu/risc-v/rv64/cpuport.c
src/Kconfig

[
The new rt_completion implemented by lockless algorithm can
improve timer resolution for up to ~12%, compare to sem IPC.
- BSP: RK3568, QEMU vexpress a9
- .config:
- action:
]

[ipc] support of lockless rt_completion

---

src/timer.c

[
- https://club.rt-thread.org/ask/question/d5c013f9637a6fda.html
- BSP:
- .config:
- action:
]

[timer] The rt_timer_check and _soft_timer_check functions are merged

---

tools/building.py
tools/utils.py

[tools] fix the issue of cc detection failure in Windows

---

components/drivers/ipc/completion_mp.c
components/drivers/ktime/src/hrtimer.c
src/cpu_mp.c

[
- use-after-freed bugs occured while using hrtimer
- BSP:
- .config:
- action:
]

[hrtimer] fixup use-after-free

---

components/drivers/include/drivers/serial_dm.h

[
- BSP:
- .config:
- action:
]

[components][drivers]fix compiler error in serial dm

---

tools/utils.py

[
- BSP:
- .config:
- action:
]

[tools] fix env toolchain path parse issue

---

components/drivers/ofw/base.c

[
处理设备树中aliases节点对于id的解析逻辑存在问题。
假设存在如下设备树aliases节点：
```dts
aliases {
serial123 = &pl011;
serial12  = &pl011;
serial1 = &pl011;
serial = &pl011;
};
```
对应的id解析出来应该是123、12、1、0.
目前代码的解析结果：
修改代码后的解析结果：
- BSP:
- .config:
- action:
]

[drivers][ofw] fix ofw_alias_scan() bug

---

examples/utest/testcases/kernel/sched_sem_tc.c
libcpu/Kconfig
libcpu/aarch64/common/context_gcc.S
libcpu/aarch64/common/cpu.c
libcpu/aarch64/common/cpu_gcc.S
libcpu/aarch64/common/cpuport.h
src/cpu_mp.c
src/scheduler_mp.c
src/thread.c
tools/ci/cpp_check.py

[
Replace the former implementation of flag-based spinlock which is unfair.
Besides, C11 atomic implementation is more readable (it's C anyway),
and maintainable. Cause toolchain can use their builtin optimization and tune for
different micro-architectures. For example armv8.5 introduces a [better instruction](https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/enabling-rcpc-in-gcc-and-llvm).
the compiler can help with that when it knows you target platform in support of it).
- BSP: RK3568, QEMU
- .config:
- action:
]

[libcpu/arm64] add C11 atomic ticket spinlock

---

components/drivers/serial/serial_tty.c
components/lwp/lwp.c
components/lwp/terminal/terminal.h
components/lwp/terminal/tty_device.c
include/rtdef.h
include/rtthread.h
src/object.c

[
- Fixed compiler warning on terminal subsystem for `components/lwp/terminal/terminal.h`
- Updated default console setup to dynamically select an appropriate tty device based on the configured console device.
- BSP:
- .config:
- action:
]

[smart] select console device dynamically

---

components/dfs/dfs_v2/filesystems/devfs/devfs.c

[
reported by KASAN.
This change addresses a potential out-of-memory access issue in the devfs filesystem component. The issue arises when the `rt_malloc` function allocates memory for a path string without accounting for the null terminator, leading to undefined behavior.
As the manual documented:
> DESCRIPTION
>   The strlen() function calculates the length of the string pointed to
>   by s, excluding the terminating null byte ('\0').
To fix this, the memory allocation size was increased by one byte to ensure space for the null terminator. This prevents potential out-of-memory access and ensures proper string termination.
- BSP:
- .config:
- action:
]

[dfsv2] fixup out-of-memory access

---

components/lwp/lwp_pid.c
src/object.c

[
Fixup compiler warning
- BSP:
- .config:
- action:
]

[quality] fixup compiler warning

---

components/drivers/serial/serial_dm.c

[
当前是在serial_dev_set_name第一次执行时初始化serial自动命名所需的全局变量，但进入该初始化过程是有if条件的，可能第一次进入serial_dev_set_name未初始化该变量，导致两个串口命名相同
分离初始化到一个单独的阶段
- BSP:
- .config:
- action:
]

[component][driver]init dm serial naming framework in a separate phase

---

bsp/cvitek/c906_little/Kconfig
bsp/cvitek/c906_little/board/Kconfig
bsp/cvitek/cv18xx_risc-v/Kconfig
bsp/cvitek/cv18xx_risc-v/board/Kconfig
bsp/cvitek/drivers/drv_adc.c
bsp/cvitek/drivers/drv_hw_i2c.c
bsp/cvitek/drivers/drv_pwm.c
bsp/cvitek/drivers/drv_rtc.c
bsp/cvitek/drivers/drv_spi.c
bsp/cvitek/drivers/drv_wdt.c

该 PR 累积多个和 bsp/cvitek 产品（duo/duo256) 的补丁更新
已经在 duo 和 duo256 上运行过测试。
详细修改内容请参考 commits 的 message 描述。
详细修改内容请参考 commits 的 message 描述。
bsp/cvitek/
- BSP:
没有变化
- .config:
N/A
- action:

Accumulated patchsets for bsp/cvitek

---

components/lwp/arch/risc-v/rv64/lwp_gcc.S
libcpu/arm/cortex-m33/context_gcc.S
libcpu/arm/cortex-m7/context_gcc.S
libcpu/risc-v/t-head/c906/context_gcc.S
libcpu/risc-v/virt64/context_gcc.S

[
Using rt_thread_self() to get current TCB to achieve better maintainability.
Relates #8942
- BSP:
- .config:
- action:
]

[libcpu] discard rt_current_thread

---

components/lwp/arch/arm/cortex-a/lwp_gcc.S

[
- BSP:
- .config:
- action:
]

[libcpu] arm: fixup signal handling

---

components/drivers/include/drivers/mmcsd_card.h
components/drivers/include/drivers/mmcsd_cmd.h
components/drivers/include/drivers/mmcsd_host.h
components/drivers/include/drivers/sd.h
components/drivers/sdio/sd.c

- added SDR50, SDR104 and DDR50 support to SD driver
[
- add UHS-I mode support (SDR50,SDR104 and DDR50)
- verified on HPM6800EVK
]

[components][drivers][sd] add uhs-i mode support to sd driver

---

components/drivers/ipc/ringblk_buf.c

[
ringblk_buff.c中
如果空间不足，申请不到需要的空间，需要回收new_rbb
STM32H750 编译测试过。
]
- [ *] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

如果空间不足，申请不到需要的空间，需要回收new_rbb

---

components/drivers/core/SConscript
components/drivers/core/mnt.c

[
1. Mount the rootfs options by parameters:
- root=: root device, like vda1, sda1, sd0p1, nvme0n0p1...
- rootfstype=: root file system type, like elm, ext, crom...
- rw/ro: root is readonly or all enable, if not 'rw' flag, 'ro' flag is default.
- rootwait: always wait for root device status is OK.
- rootdelay=: mount rootfs delay amount of time (millisecond).
2. Mount the other fs options by `fstab.sh`, it will read the script after root mount is OK, it's format is a list of mount cmd in MSH:
```shell
mount vda2 /mnt elm
mount 192.168.1.1:/ /mnt/remote nfs
```
This feature is supported by platfrom information probe interface.
]

[Feature] DFS mount auto by kernel parameters

---

components/drivers/ofw/irq.c

[
`map_len` and `map_mask_len` is the count of elements, not the bytes size of elements.
]

[OFW] Fixup irq parse map and map mask

---

components/drivers/include/drivers/ofw.h
components/drivers/ofw/base.c

[
The OFW map id is always use in DMA, PCI, IOMMU
bus system to find the device identity. this is a access interface.
]

[OFW] Support ID map interface

---

components/drivers/core/SConscript
components/drivers/core/numa.c
components/drivers/include/drivers/core/numa.h
components/drivers/include/rtdevice.h

[
For some CPU memory access devices, that the drivers will find memory and CPU affinity to config device.
Make a way to found the best affinity memory for current CPU (if platform have NUMA memory) or ask the
developers to take care of the memory affinity when driver access a memory:
```c
rt_err_t msi_affinity_init(struct rt_pic_irq *pirq, struct rt_pci_msi_desc *desc, bitmap_t *cpumasks)
{
rt_uint64_t data_address;
/* Get MSI/MSI-X write data adddress */
data_address = desc->msg.address_hi;
data_address <<= 32;
data_address |= desc->msg.address_lo;
/* Prepare affinity */
cpumasks = pirq->affinity;
rt_numa_memory_affinity(data_address, cpumasks);
/* Config affinity */
return rt_pic_irq_set_affinity(irq, cpumasks);
}
```
]
我在这个拉取/合并请求中已经考虑了 As part of this …

[DM/feature] Simple NUMA (Non-Uniform Memory Access)

---

components/drivers/ofw/Kconfig
components/drivers/ofw/io.c
components/drivers/ofw/ofw_internal.h

[
ofw data is private data for every ofw node that
the drivers of ofw node will use item.
replace the ranges supported to list.
]

[OFW] io ranges use list to storage without ofw data

---

include/rtdef.h
include/rtsched.h
include/rtthread.h
libcpu/Kconfig
libcpu/aarch64/common/context_gcc.S
libcpu/aarch64/common/cpu.c
libcpu/aarch64/common/cpuport.h
libcpu/aarch64/cortex-a/entry_point.S
src/cpu_up.c
src/scheduler_mp.c
src/scheduler_up.c
src/thread.c

[
This patch introduces hardware-based thread self-identification
for the AArch64 architecture. It optimizes thread management by
using hardware registers to store and access the current thread's
pointer, reducing overhead and improving overall performance.
Changes include:
- Added `ARCH_USING_HW_THREAD_SELF` configuration option.
- Modified `rtdef.h`, `rtsched.h` to conditionally include
`critical_switch_flag` based on the new config.
- Updated context management in `context_gcc.S`, `cpuport.h`
to support hardware-based thread self.
- Enhanced `scheduler_mp.c` and `thread.c` to leverage the new
hardware thread self feature.
These modifications ensure better scheduling and thread handling,
particularly in multi-core environments, by minimizing the
software overhead associated with thread …

[arm64] add hw thread self

---

components/lwp/lwp.h
components/lwp/lwp_pid.c
components/lwp/lwp_syscall.c

[
Correct `sched_setaffinity()` to use the thread IDs (TIDs) instead of
process IDs (PIDs). The previous implementation used PIDs, which
caused issues since affinity settings need to be applied at the
thread level.
As the manual documented, the signature is:
>        int sched_setaffinity(pid_t pid, size_t cpusetsize,
>                             const cpu_set_t *mask);
Yes, it's tricky, the identification passing in is called **'PID'**.
But when we talk about 'pid' from GNU libc, it's the **'task-id'**,
aka, `thread->tid` known in kernel.
Changes were made by updating the function signatures and logic
in `lwp.h`, `lwp_pid.c`, and `lwp_syscall.c` to accept TIDs. Specifically,
the `lwp_setaffinity` function and related internal functions now
operate using thread IDs and adjust thread …

[smart] update sched_setaffinity() to use thread(task) ID

---

bsp/nxp/imx/imxrt/libraries/drivers/drv_ksz8081.c
bsp/nxp/imx/imxrt/libraries/drivers/drv_rtl8211f.c
components/drivers/include/drivers/phy.h

Current issue:
The current rt_phy_ops API can not specify phy in multi-phy case
Solution:
Add one parameter phy to specify phy instance

improve phy interface driver

---

.clang-format
components/drivers/ktime/inc/ktime.h
components/drivers/ktime/src/aarch64/cputimer.c
components/drivers/ktime/src/boottime.c
components/drivers/ktime/src/cputimer.c
components/drivers/ktime/src/hrtimer.c
components/drivers/ktime/src/risc-v/virt64/cputimer.c

[
ktime部分函数中，计算时间所需的分辨率、振动频率等使用了unsigned long类型，但是该类型在计算会存在溢出。
将存在溢出的unsigned long变量类型修改为rt_uint64_t
- BSP:  qemu
- .config:
- action:
]

解决ktime部分函数计算时unsigned long溢出

---

components/drivers/core/SConscript
components/drivers/core/platform.c
components/drivers/core/platform_ofw.c
components/drivers/core/power_domain.c
components/drivers/include/drivers/core/power_domain.h
components/drivers/include/drivers/ofw.h
components/drivers/include/drivers/platform.h
components/drivers/include/rtdevice.h
components/drivers/ofw/ofw.c
include/rtdef.h

[
A simple  power domain framework:
1. Support device power on/off.
2. Support attach/detach device.
3. Support power domain driver api.
> To find a power domain object in OFW, we make a new ofw object parser API
Apply power domain for platform bus:
1. Add power domain for device probe.
2. Support `remove` and `shutdown` bus interface with power domain API.
]

[Feature] Support simple power domain API

---

components/drivers/misc/rt_random.c

[
dd commands not working on `/dev/urandom`
```sh
/ # dd if=/dev/random of=/dev/shm/random_file bs=1M count=16
0+0 records in
0+0 records out
0 bytes (0B) copied, 0.003571 seconds, 0B/s
```
Fix device read to copy requested bytes as caller.
```sh
/ # dd if=/dev/random of=/dev/shm/random_file bs=1M count=16
16+0 records in
16+0 records out
16777216 bytes (16.0MB) copied, 0.174114 seconds, 91.9MB/s
```
- BSP:
- .config:
- action:
]

dev: random should copy size bytes of data to buffer

---

components/drivers/pic/pic-gic-common.c
components/drivers/pic/pic-gic-common.h

[
- BSP:
- .config:
- action:
]

[fix]fix compile err in pic-gic

---

components/drivers/misc/adc.c

计算式：
`voltage = value * vref / (1 << resolution);`
因为 ADC 实际的最大值是 `((1 << resolution) - 1)`
所以应该改为：
`voltage = value * vref / ((1 << resolution) - 1);`
增加 'adc voltage' 命令的帮助信息。

[fix][misc][adc] 修复 ADC 电压转换的计算错误

---

components/lwp/Kconfig
components/lwp/lwp.c
include/rtdef.h
src/Kconfig
src/clock.c
src/idle.c

[
This patch introduces following features:
- Added CPU usage tracing functionality, enabled by default, for applications like 'top'.
Tracing statistics data on ticks increasing event for threads & cores.
- BSP:
- .config:
- action:
]

[smart] add CPU/thread usage tracing config

---

bsp/hpmicro/hpm6200evk/board/Kconfig
bsp/hpmicro/hpm6300evk/board/Kconfig
bsp/hpmicro/hpm6750evk/board/Kconfig
bsp/hpmicro/hpm6750evk2/board/Kconfig

- removed invalid reference in board KConfig
[
本次Patch用于修复HPMicro BSP中的一些无效的KConfig引用及配置项,
修复了以下开发板的Kconfig配置问题：
- HPM6300EVK
- HPM6200EVK
- HPM6750EVK2
并在开发板上重新做了测试，一切正常
]

[bsp][hpmicro] remove invalid reference in board KConfig

---

components/mm/SConscript

改进 `components/mm/SConscript`
改进理由：
`components/mm/` 目录下不存在下一级目录，不需要再进入下一级目录处理 SConscript 文件

component:mm: improve sconscript

---

components/lwp/lwp_user_mm.h
components/mm/mm_aspace.c
components/mm/mm_fault.c
components/mm/mm_fault.h
components/mm/mm_private.h
examples/utest/testcases/mm/lwp_mmap_fix_private.c
libcpu/aarch64/common/armv8.h
libcpu/aarch64/common/trap.c
libcpu/risc-v/t-head/c906/trap.c
libcpu/risc-v/virt64/riscv_mmu.h
libcpu/risc-v/virt64/trap.c

[
- Fixup errors & improve accuracy in identifying and handling different types
of memory faults, ensuring correct fault type classification and handling.
- Addressed read access faults on arm64 architecture.
- Added new fault types like MM_FAULT_TYPE_GENERIC_MMU and 
MM_FAULT_TYPE_RWX_PERM, and adjusted existing logic to use these 
types.
- Improved fault type determination logic in `mm_fault.c` and 
`trap.c`, ensuring correct fault handling based on permissions and 
operations.
- BSP:
- .config:
- action:
]

[mm] precise & readable mm fault type

---

libcpu/aarch64/common/context_gcc.S
libcpu/aarch64/common/cpu.c

[
Support hw_cpu_id_get on context without stack
Implement this API on assembly codes.
- BSP:
- .config:
- action:
]

[libcpu] arm64: implement cpuid get by assembly

---

components/drivers/sdio/sd.c

[
在ART-PI上移植rtthread的时候，发现最新主线上的内核读取不到emmc和sd的分区，经过回退代码确认，发现是这一次的提交导致了该问题：
#8987 
经过调试发现之前版本中是先初始化总线时钟频率再初始化总线宽度，这次得修改中将顺序反过来了，导致读取不到emmc/sd分区（但是为什么在其他板子上可以读取？），在网上查阅资料发现带宽得初始化一般都是放在最后面（可以保证配置的一致性和稳定性？）。
将初始化时钟频率放在初始化带宽前面
- BSP:
- .config:
- action:
]

【修复】修复ART-PI samrt上读取不到emmc/sd分区问题

---

components/utilities/utest/utest.c

[
The delay is introduced by 0dc7b9a5a26030a945723569c64f5be46bd70ae1.
Though this is unnecessary for synchronous utest.
So it is replaced by a wrapper entry where delay is for asynchronous utest only.
- BSP:
- .config:
- action:
]

[utest] remove delay for on thread testing

---

include/rthw.h
include/rtthread.h
libcpu/aarch64/common/trap.c
libcpu/risc-v/virt64/trap.c
src/Kconfig
src/kservice.c

[
Add `rt_backtrace_to_buffer()` to help debug on
context without logging support to stash the data.
Also, add the extension to backtrace service, by `rt_backtrace_formatted_print()`.
The backtrace can provide a more readable log with the symbol table provided.
Users can choose between two types of backtrace. The default one is:
The ksymtbl implementation is:
Following modification are included:
- make rt_backtrace_frame patchable with weak attr
- export `rt_system_heap_init_generic()` for heap sanitizer
- BSP:
- .config:
- action:
]

[kservice] Enhance support for backtrace service

---

components/drivers/ofw/fdt.c

[
增加cromfs从bootargs启动，在rt_hw_common_setup();时会调用rt_fdt_scan_initrd函数，该函数会判断用户有没有在bootargs中传入cromfs这一变量，如果有，就根据用户传入的起始地址和长度为其注册一块名字为initrd的内存区域，在components/drivers/core/mnt.c的rootfs_mnt_init中，会判断系统有没有注册名为initrd的内存区，如果有，将fsdata的指针指向该内存区，并mount这一块内存区的数据作为根文件系统。
**用法：在uboot中加载cromfs.bin到内存中，在bootarg中传入内存起始地址和长度
load <interface> [<dev[:part]> [<addr> [<cromfs.bin>]]]
setenv bootargs cromfs=<startaddr(HEX)>,<len(hex)>**
**例:
load mmc 1:1 0x10800000 cromfs.bin
setenv bootargs cromfs=0x10800000,0x3897ef0**
- BSP:
- .config:
- action:
]

[add] add cromfs start with bootargs cmd

---

components/drivers/ipc/workqueue.c
examples/utest/testcases/kernel/timer_tc.c
include/rtdef.h
src/Kconfig
src/timer.c

[
添加选项，开启该选项所有timer均在线程环境执行
- BSP:
- .config:
- action:
]

[timer]add all soft timer config

---

components/lwp/arch/risc-v/rv64/lwp_gcc.S
libcpu/risc-v/t-head/c906/stackframe.h
libcpu/risc-v/virt64/stackframe.h

[rv]信号处理进入用户态前恢复gp

---

components/lwp/Kconfig
components/lwp/lwp_user_mm.h
components/mm/mm_fault.c

[
Using memory protection attribution only when architecture supports it.
- BSP:
- .config:
- action:
]

[smart] add mprotect config

---

components/finsh/msh.c

Blocks by #9086
[
This patch introduces a new shell command `bind` that allows users to bind a specific thread to a specified core via the command line. The command accepts a thread ID and a core ID as arguments.
Usage:
```sh
bind <thread_id> <core_id>
```
- BSP:
- .config:
- action:
]

[finsh] add msh command to bind thread to specific core

---

.github/workflows/doxygen.yml
documentation/doxygen/kernel.h
src/kservice.c

[
修复doxygen  warning
kservice.c:474: warning: The following parameter of rt_backtrace_to_buffer(rt_thread_t thread, struct rt_hw_backtrace_frame *frame, long skip, rt_ubase_t *buffer, long buflen) is not documented:
parameter 'thread'
kernel.h:157: warning: unable to resolve reference to '_rt_errno' for \ref command
添加注释，修复之前_rt_errno注释错误
- BSP:
- .config:
- action:
]

[doc][doxygen]: Fix doxygen warning in comment

---

libcpu/risc-v/t-head/c906/riscv_mmu.h

[libcpu/c906]与virt同步

---

documentation/doxygen/kernel.h
include/rtdef.h
include/rtthread.h

[
1. 统一signal并且将其显示在线程通信中。
2. 将mutex event等group整理，防止重复显示
- BSP:
- .config:
- action:
]

[doc][doxygen] Fix doxygen struct error.

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_adc.c
components/drivers/misc/adc.c

[
一、ADC 存在一些bug
1、调用adc.c文件中函数rt_int16_t rt_adc_voltage(rt_adc_device_t dev, rt_int8_t channel)获取不到正确的电压值。分析原因如下
static rt_int16_t stm32_adc_get_vref (struct rt_adc_device *device)
{
if(device == RT_NULL)
return -RT_ERROR;
rt_uint16_t vref_mv;
#ifdef __LL_ADC_CALC_VREFANALOG_VOLTAGE
rt_err_t ret = RT_EOK;
rt_uint32_t vref_value;
ADC_HandleTypeDef *stm32_adc_handler = device->parent.user_data;
ret = rt_adc_enable(device, RT_ADC_INTERN_CH_VREF);
if (ret != RT_EOK) return (rt_int16_t)ret; // 错误的时候，这里返回ret
vref_value = rt_adc_read(device, RT_ADC_INTERN_CH_VREF);
ret = rt_adc_disable(device, RT_ADC_INTERN_CH_VREF); // 会停止ADC外设
if (ret != RT_EOK) return (rt_int16_t)ret;
#ifdef SOC_SERIES_STM32U5
vref_mv = __LL_ADC_CALC_VREFANALOG_VOLTAGE(stm32_adc_handler->Instance, vref_value, …

[bsp][stm32]Optimize ADCs and fix some bugs

---

tools/building.py
tools/cmake.py

* support getting c/cpp standard from c/cpp compilation flags
* support getting post action and conv it to cmake variable
* add a custom cmake file for user custom settings
* support setting project name from `--project-name=` option
[
生成的cmake有一些硬编码的东西，且部分参数并没有去rtconfig.py中读取，对于依赖cmake的ide，如clion，在修改时不是很友好。
- BSP: art-pi
- .config:
- action:
]

[tool][cmake] Let cmake generator get more param from `rtconfig.py`

---

components/drivers/serial/serial_v2.c

[
DFS_V2推出很久了，但是serial_v2目前没有适配dfs_v2中接口。
根据dfs_v2接口定义，采用宏调整的serial_v2中serial_fops_read、serial_fops_write和dfs_file_ops等函数或变量。
- BSP:
- .config:
- action:
]

[fixed]serial_v2.c兼容DFS_V2接口

---

components/drivers/serial/serial_tty.c

[
Skip configure on open since all configs are copied from the current configuration on device. So we don't bother to set it back to device again.
Changes:
- test and skip configuration on open() of tty device
- BSP:
- .config:
- action:
]

[smart/tty] skip configure of rt_serial on tty open

---

components/mm/mm_aspace.h
libcpu/Kconfig
libcpu/risc-v/t-head/c906/mmu.c
libcpu/risc-v/t-head/c906/startup_gcc.S

[
This change was necessary to enable the remapping of the kernel image to
a high virtual address region on the c906 platform.
Just a trival duplication work from #9067.
Changes:
- Introduced new configuration options `ARCH_REMAP_KERNEL`, and
`ARCH_USING_ASID` under the `ARCH_RISCV64` section.
- Updated MMU initialization and switching functions to incorporate
remapping handling.
- Modified page table setup for proper memory attribute settings.
- Added support for early memory setup, kernel remapping
- Added conditional compilation for ASID support in the `rt_aspace` struct,
since this is not enable currently for most architecture.
- BSP: milkv duo 256, persimUI m7
- .config:
- action:
Standard
Smart
] …

feat: support ARCH_REMAP_KERNEL on libcpu/c906

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_soft_spi.c
components/drivers/spi/spi-bit-ops.c

[
cherry-pick https://github.com/RT-Thread/rt-thread/pull/9124 
https://github.com/RT-Thread/rt-thread/pull/9124/commits/ec70a010a5fb8111e730d43ddaaf46c91f35d72d
https://github.com/RT-Thread/rt-thread/pull/9124/commits/64b57dc3baac577e1db64765d33a6bb7d377cb52
- BSP:
- .config:
- action:
]

[components][SPI][spi-bit-ops]修复可能的异常操作

---

.gitignore
components/lwp/Kconfig
components/lwp/SConscript
components/lwp/arch/aarch64/common/vdso.c
components/lwp/arch/aarch64/common/vdso_data.c
components/lwp/lwp.h
components/lwp/lwp_elf.c
components/lwp/vdso/Kconfig
components/lwp/vdso/SConscript
components/lwp/vdso/kernel/vdso.h
components/lwp/vdso/kernel/vdso_data.h
components/lwp/vdso/kernel/vdso_text.S
components/lwp/vdso/user/SConstruct
components/lwp/vdso/user/vdso.lds.S
components/lwp/vdso/user/vdso_sys.c
components/lwp/vdso/user/vdso_sys.h
components/lwp/vdso/user/xmake.lua
components/lwp/vdso/vdso_config.h
components/lwp/vdso/vdso_datapage.h
components/lwp/vdso/vdso_weak.c
libcpu/aarch64/cortex-a/entry_point.S
src/clock.c

[
- BSP:
- .config:
- action:
]

[lwp][vdso] Add VDSO functionality under the aarch64 architecture

---

bsp/cvitek/drivers/drv_adc.c
bsp/cvitek/drivers/drv_adc.h

The ADC controller needs to be calibrated during the initialization phase, otherwise the measured voltage value will be inaccurate.
Fixed #8945
[
请看 commit text
adc 初始化中增加 adc 的 calibration 校正操作
- .config: N/A
- action:
]

[bsp/cvitek]: add calibration for adc

---

components/dfs/dfs_v2/src/dfs_pcache.c

[
This patch optimizes the pcache varea management by refining the conditions under which pages are marked dirty, specifically targeting the unmap operations in the dfs_pcache component. These changes were necessary to enhance the efficiency of page cache management.
Changes:
- Adjusted include statements in `dfs_pcache.c` for better organization.
- Modified `dfs_aspace_unmap` function:
- Added a check to ensure `varea` is not privately locked before marking a page as dirty.
- Updated `dfs_aspace_page_unmap` function:
- Added a similar check for `varea` lock status before marking a page as dirty.
- BSP:
- .config:
- action:
]

[dfs] Mark dirty on unmap on shared mapping only

---

components/lwp/lwp_user_mm.c

[
Do unmap before shrink so we don't see mapped entry on page table insertion, which is not acceptable for riscv implementation of architecture porting.
Changes:
- add un-mapping of pte on `_null_shrink()`
- BSP:
- .config:
- action:
]

[smart] feat: add unmap for null mapper

---

bsp/cvitek/drivers/drv_adc.c
bsp/cvitek/drivers/drv_hw_i2c.c
bsp/cvitek/drivers/drv_pwm.c
bsp/cvitek/drivers/drv_spi.c
bsp/cvitek/drivers/drv_wdt.c

Some drivers use INIT_BOARD_EXPORT, it is not necessary, it is enough to use INIT_DEVICE_EXPORT for genearl drivers.
[
see commit text
Fixed #9173 
see commit text
- .config: N/A
- action: N/A
]

bsp: cvitek: switch to device init function for some drivers

---

bsp/cvitek/cv18xx_aarch64/board/board.c

The aarch64 core of duo on the master cannot enter the
console interface. It can only print the RT flag and hold it.
Analysis: The latest commit that can work is https://github.com/RT-Thread/rt-thread/commit/ae6a3287e6ab4121c07b1e0624b44d0e4477e14f ("Add
psoc62, 61 config"). This phenomenon will occur after adding
https://github.com/RT-Thread/rt-thread/commit/754c59a41185fadd543ae2eaee518ebcbe68af5b ("[Feature] DFS mount auto by kernel parameters").
The specific reason is that when aarch bsp enables the device
tree, the current u-boot will pass in bootargs, which contains
"root=/dev/mmcblk0p2 rootwait rw", which means that the
kernel is required to wait until the rootfs in /dev/mmcblk0p2
loaded successfully. However, the current aarch64 bsp default
does not implement sdmmc device …

bsp: cvitek: fix cv18xx_aarch64 mnt init blocking

---

components/libc/compilers/armlibc/syscalls.c

* [armlibc] 修复AC6更新至6.19后_sys_tmpnam()函数编译报错
直接从主分支的 commit #cef57d006d6a1f46245c7829752498f8f7137ae8 rebase过来的。

[armlibc] 修复AC6更新至6.19后_sys_tmpnam()函数编译报错， 直接从主分支的 commit #cef57d0 rebase过来。

---

components/libc/compilers/common/ctime.c

[
修复不使能 `RT_USING_DEVICE` 时，`ctime.c` 编译报错
对编译报错处做宏定义限制
- BSP: bsp/stm32/stm32f407-atk-explorer
- .config:
- action:
]

修复不使能 RT_USING_DEVICE 时编译报错

---

bsp/airm2m/air32f103/libraries/AIR32F10xLib/src/air32f10x_flash.c

[
This PR is to fix the build error when using the GCC toolchain. The errors are primarily caused by the `SetStrt` function in `air32f10x_flash.c`
The function is missing a declaration, so we call `FLASH_EraseOptionBytes`, as it calls the `SetStrt`. Add this statement in `main.c`:
```c
FLASH_Status st = FLASH_EraseOptionBytes();
```
Then we try to build the project: 
```shell
scons --target=cmake
scons
```
```
/path/to/ld.exe: build/libraries/AIR32F10xLib/src/air32f10x_flash.o: in function `SetStrt':
/path/to/air32f10x_flash.c:653: undefined reference to `asm`
```
`asm` keyword is a GNU extension. It works only under specific conditions, such as `-std=gnu99`. Problems will occur during compilation if `-std=c99` is used.  `__asm` or `__ASM` should be used by convention (from …

[BSP][airm2m/air32f103] fix build errors when using arm gnu toolchain

---

bsp/efm32/application.c
bsp/efm32/dev_accel.c
bsp/efm32/drv_leuart.c
bsp/efm32/drv_usart.c
bsp/sep6200/application/application.c
documentation/thread/thread.md
examples/libc/ex6.c
examples/libc/ex7.c
examples/libc/file.c

[
- BSP:
- .config:
- action:
]

删除rt_thread_sleep遗留

---

components/drivers/include/ipc/completion.h
components/drivers/ipc/completion_comm.c
components/drivers/ipc/completion_mp.c
components/drivers/ipc/completion_up.c

[
Since the completion is used to sync with ISR mostly, we should set the default semantic to ISR-safe. So most user will be happy and don't see any weird behavior in their codes.
Changes:
- Added `rt_completion_wait_noisr` and `rt_completion_wait_flags_noisr` functions in `completion.h`, `completion_comm.c`, `completion_mp.c`, and `completion_up.c`.
- The new APIs allow waiting for completions in non-ISR contexts while ensuring thread context safety.
- Existing documentation and comments were updated to clarify usage contexts and emphasize restrictions on ISR usage.
- BSP:
- .config:
- action:
]

feat: add ISR safe completion API

---

components/lwp/lwp_syscall.c
components/lwp/lwp_tid.c

…failed
[
- BSP:
- .config:
- action:
]

[lwp][tid]add error log when tid depleted, and return correct errno when clone failed

---

components/lwp/lwp_pgrp.c
components/lwp/lwp_syscall.c

[
1.使用mmap时，当传入一个非常大的地址时，offset会计算得到一个值，又因为传入的地址错误，rc会得到错误码，结合offset会得到一个很奇怪的值。
2.执行setpgrp后，再使用getpgrp无法得到创建的group的值
1.修改mmap的返回方式
2.添加group = lwp_pgrp_create(process);执行后的一些行为
- BSP:
- .config:
- action:
]

[lwp] Implementation of setpgrp and fix mmap2 problems

---

components/dfs/dfs_v2/filesystems/devfs/devfs.c
components/dfs/dfs_v2/src/dfs.c
components/dfs/dfs_v2/src/dfs_posix.c
components/lwp/lwp_syscall.c

[
lseek系统调用返回异常值到用户层错误，正常来说，用户调用lseek失败时应期望返回-1，但是由于size变量的设置以及devfs中ret的设置会导致返回的错误码有问题
- BSP:
- .config:
- action:
]

【修复】修复lseek系统调用的错误值返回异常问题

---

components/libc/posix/pthreads/pthread_tls.c

修复 POSIX接口下pthread_setspecific 在第一次设置值时，申请了内存而没有初始化，
导致 获取不是此 key 值以外的索引，存储的是脏数据，导致用户判断到不该有的返回数据。
修改 pthread_setspecific ，在 rt_malloc 未增加 rt_calloc
```
/* check tls area */
if (ptd->tls == NULL)
{
ptd->tls = (void**)rt_calloc(PTHREAD_KEY_MAX, sizeof(void*));
RT_ASSERT(ptd->tls != NULL);
}
```
- BSP:
bsp\stm32\stm32f407-armfly-v5
- .config:
#define RT_USING_POSIX_FS
#define RT_USING_POSIX_POLL
#define RT_USING_POSIX_SELECT
#define RT_USING_POSIX_SOCKET
#define RT_USING_POSIX_DELAY
#define RT_USING_POSIX_CLOCK
#define RT_USING_POSIX_TIMER
#define RT_USING_PTHREADS
#define PTHREAD_NUM_MAX 8
#define RT_USING_CPLUSPLUS
#define RT_USING_CPLUSPLUS11
- action:
编译通过：

修复POSIX ptd->tls申请内存后没有初始化问题

---

components/dfs/dfs_v2/src/dfs_file.c
components/lwp/lwp_syscall.c

[
修复symlink系统调用返回值不是预期问题
- BSP:
- .config:
- action:
]

【修复】修复symlink系统调用返回值不是预期问题

---

libcpu/aarch64/common/include/asm-generic.h
libcpu/aarch64/common/include/vector_gcc.h
libcpu/aarch64/common/mp/context_gcc.S
libcpu/aarch64/common/mp/vector_gcc.S
libcpu/aarch64/common/up/context_gcc.S
libcpu/aarch64/common/up/vector_gcc.S
libcpu/aarch64/common/vector_gcc.S

[
This patch generalize the irq handling on up/mp system by adding the `rt_hw_irq_exit()` & `rt_hw_vector_irq_sched()` API.
Nohted that there's barely **NO** changes on logical behaviour of the IRQ handling, and this is only to remove the redundant part.
Changes:
- Added `rt_hw_irq_exit()` and `rt_hw_vector_irq_sched()` APIs for unified IRQ management.
- Refactored assembly code for both UP and MP systems to use the new IRQ handling flow.
- Removed redundant code and optimized exception handling paths.
- BSP:
- .config:
- action:
]

feat: arm64: generic implementation of vector irq

---

tools/env_utility.py

sdk路径被改乱掉了，修正回来。在stm32，qemu-virt64-aarch64下进行验证测试；

[tools] fix the SDK path issue in env script.

---

bsp/cvitek/drivers/drv_sdhci.c

详解:
中断状态寄存器的BIT0仅表示sdhci处理命令完成，完成结果由其它位指示，当出错时
BIT0也会值1产生中断
[
这个问题导致emmc无法正常初始化
在命令完成中断到达时才触发等待信号量(错误原因中断比完成中断先到达)
修改后SD卡识别正常：
```
- RT -     Thread Operating System
/ | \     5.2.0 build Aug 14 2024 11:21:42
2006 - 2024 Copyright by RT-Thread team
lwIP-2.1.2 initialized!
[I/sal.skt] Socket Abstraction Layer initialize success.
Hello RISC-V!
msh />[I/SDIO] SD card capacity 31166976 KB.
[I/SDIO] sd: switch to High Speed / SDR25 mode 
found part[0], begin: 512, size: 128.0MB
found part[1], begin: 134218240, size: 768.0MB
[I/app.filesystem] sd card mount to '/sdcard'
```
duos-emmc上emmc识别正常:
```
[I/SDIO] emmc card capacity 7634944 KB, card sec count:15269888.
[I/SDIO] emmc: switch to HIGH Speed mode
```
] …

[bsp/cvitek]修正sdhci发送命令超时后触发两次信号量的问题

---

libcpu/arm/cortex-m4/README.md
libcpu/arm/cortex-m4/context_gcc.S
libcpu/arm/cortex-m4/context_iar.S
libcpu/arm/cortex-m4/context_rvds.S

…pi to support independent interrupts management
[
在程序需要精准的中断响应时，由于`rt-thread`多处地方调用`rt_hw_interrupt_disable`导致中断延迟的问题
- 在`libcpu`中的`rt_hw_interrupt_disable`函数添加`weak`修饰以实现临界区的重写
- 在对应bsp的`board.c`文件中添加如下代码
```
#ifdef RT_USING_INDEPENDENT_INTERRUPT_MANAGEMENT
#define RT_NVIC_PRO_BITS    __NVIC_PRIO_BITS
rt_base_t rt_hw_interrupt_disable(void)
{
rt_base_t level = __get_BASEPRI();
__set_BASEPRI(RT_MAX_SYSCALL_INTERRUPT_PRIORITY << (8 - RT_NVIC_PRO_BITS));
__ISB();
__DSB();
return level;
}
void rt_hw_interrupt_enable(rt_base_t level)
{
__set_BASEPRI(level);
}
#endif /* RT_USING_INDEPENDENT_INTERRUPT_MANAGEMENT */
```
- 在`board`目录`Kconfig`文件中添加如下配置
```
menuconfig RT_USING_INDEPENDENT_INTERRUPT_MANAGEMENT
bool "Enable independent interrupt management"
default n
if …
```

允许重写中断控制API以支持独立的中断管理

---

examples/utest/testcases/kernel/Kconfig
examples/utest/testcases/kernel/SConscript
examples/utest/testcases/kernel/smp/Kconfig
examples/utest/testcases/kernel/smp/SConscript
examples/utest/testcases/kernel/smp/smp_affinity_pri1_tc.c
examples/utest/testcases/kernel/smp/smp_affinity_pri2_tc.c
examples/utest/testcases/kernel/smp/smp_assigned_idle_cores_tc.c
examples/utest/testcases/kernel/smp/smp_bind_affinity_tc.c
examples/utest/testcases/kernel/smp/smp_interrupt_pri_tc.c
examples/utest/testcases/kernel/smp/smp_spinlock_tc.c
examples/utest/testcases/kernel/smp/smp_thread_preemption_tc.c

[
添加testcases\kernel\smp测试用例
1.smp spinlock测试用例
2.smp 绑核亲和力与线程优先级的测试用例
3.smp 线程抢占测试用例
4.smp 将线程分配至空闲核测试用例
5.smp 中断优先级设置测试用例
bsp\qemu-vexpress-a9

[utest] add smp testcases

---

components/libc/compilers/common/ctime.c

[
- BSP:
- .config:
- action:
]

[libc] 修复 ctime()死机问题

---

libcpu/aarch64/common/atomic_aarch64.c

[
在https://github.com/RT-Thread/rt-thread/commit/e9b683d0b338b4c92190702d151e5180d0b10ca0 的提交中规范了atomic的实现方式，原本phytium bsp的默认配置同时打开了RT_USING_STDC_ATOMIC/RT_USING_HW_ATOMIC, 关闭后RT_USING_STDC_ATOMIC发现内核不能正常启动，查明原因是libcpu\aarch64\common\atomic_aarch64.c 中rt_hw_atomic_compare_exchange_strong函数逻辑有误，请仔细检查
- BSP:
- .config:
- action:
]

[libcpu/aarch64]atomic实现修改

---

components/drivers/core/device.c
src/object.c

[
修正使用rt_device_create创建设备，使用rt_device_destroy删除失败的问题
问题来源：论坛，链接：https://club.rt-thread.org/ask/question/bfbced466a6fd1c0.html
在rt_device_unregister后对象类型为RT_Object_Class_Null，将rt_device_destroy中的判断的对象类型改为RT_Object_Class_Null
HPM6750 BSP
]

[fix][device] 修正使用rt_device_create创建设备，使用rt_device_destroy删除失败的问题

---

bsp/cvitek/drivers/drv_uart.c

After first called from uart open, the dw8250_uart_configure API cannot be called again. Otherwise, this will mess up the device, and uart will not act properly to interrupt again.
Analysis: Configure uart device will close recive interrupte, causing uart device to malfunction.
Solution: After configure uart device, enable the device's recive interrupte.
[
Fixed https://github.com/RT-Thread/rt-thread/issues/9150
After configure uart device, enable the device's recive interrupte.
- .config:
- action:
]

bsp: cvitek: fix cvitek uart driver can not repeat configure

---

src/ipc.c

[
Issue: using iperf server with sshd together and the kernel will get stuck occasionally.
taken_list is accessed from other mutex when updating priority.
protect taken_list on shared lock, but not on mutex local spinlock.
- BSP:
- .config:
- action:
]

fixup: ipc: protect taken_list on shared lock

---

examples/utest/testcases/kernel/SConscript
examples/utest/testcases/kernel/mutex_pi_tc.c
src/ipc.c

添加mutex优先级继承测试用例
[
- BSP:
- .config:
- action:
]

[utest]add mutex_pi_tc

---

components/drivers/audio/dev_audio_pipe.c

audio_pipe中函数在开启POSIX IPC时与 POSIX PIPE冲突问题。在drivers/audio/audio_pipe.c中申明了：
```
rt_pipe_read
rt_pipe_write
rt_pipe_control
```
这三个函数，如果在不开启POSIX IPC的情况下可以正常编译过去，但是如果开启 POSIX并打开IPC时，会提示以下错误：
将以下三个函数：
```
rt_pipe_read
rt_pipe_write
rt_pipe_control
```
重命名为：
```
rt_audio_pipe_read
rt_audio_pipe_write
rt_audio_pipe_control
```
符合下面 rt_audio_pipe_init函数整体规则。
- BSP:
bsp\at32f437_start
- .config:
#define RT_USING_POSIX_FS
#define RT_USING_POSIX_POLL
#define RT_USING_POSIX_SELECT
#define RT_USING_POSIX_SOCKET
#define RT_USING_POSIX_DELAY
#define RT_USING_POSIX_CLOCK
#define RT_USING_POSIX_TIMER
#define RT_USING_PTHREADS
#define PTHREAD_NUM_MAX 8
#define RT_USING_POSIX_MESSAGE_SEMAPHORE
#define RT_USING_AUDIO
#define RT_AUDIO_REPLAY_MP_BLOCK_SIZE 3840
#define RT_AUDIO_REPLAY_MP_BLOCK_COUNT 2 …

【修复】audio_pipe中函数在开启POSIX IPC时与 POSIX PIPE冲突问题

---

components/drivers/include/drivers/sensor.h
components/drivers/sensor/v1/sensor.c
components/drivers/sensor/v1/sensor_cmd.c

[
https://github.com/RT-Thread/rt-thread/issues/9399 和 [static int sensor(int argc, char **argv)](https://github.com/RT-Thread/rt-thread/blob/master/components/drivers/sensor/v1/sensor_cmd.c)当参数小于2是return 空
https://github.com/CYFS3/packages/commit/815fe8dce0c7b9ba4be6bd9b42c3c641e8ac5058
https://github.com/CYFS3/ina226/commit/bd94132054303f816ba3a5ccabcc63a3d64ed70
* Sensor types增加`RT_SENSOR_CLASS_VOLTAGE` `RT_SENSOR_CLASS_CURRENT` `RT_SENSOR_CLASS_POWER`
* Sensor unit types增加 `RT_SENSOR_UNIT_MV` `RT_SENSOR_UNIT_MA` `RT_SENSOR_UNIT_MW`
* rt_sensor_data增加`float mv,ma,mw`
* 当static int sensor(int argc, char **argv)参数小于2时候返回-RT_EINVAL
- BSP:
- .config:
- action:
]

[components][sensor]增加电源检测类型 

---

components/drivers/include/drivers/misc.h

[
When the driver request a API gets RT_NULL which return value is ptr, they could not know **why** get a RT_NULL.
some API return RT_NULL, is not error internal maybe, it just not supported for this platform, but the driver still could work ok, the API can return (RT_NULL + -RT_EEMPTY) to driver.
on the other hand, the driver can do more behaviors by error No.
When the API return the -RT_EBUSY, driver can wait for a moment and retry. 
When the API return the -RT_ENOSYS, driver can try the next mode or request's name.
]

[DM/MISC] Add error No for ptr

---

bsp/apm32/apm32f030r8-miniboard/rtconfig.py
bsp/apm32/apm32f051r8-evalboard/rtconfig.py
src/ipc.c
src/thread.c

[
- BSP:
- .config:
- action:
]

[kernel][mutex] fix bug of thread exit without releasing mutex & add error check log

---

components/lwp/lwp_syscall.c

[
函数开头检查过了，没必要一直检查
- BSP:
- .config:
- action:
]

[components][lwp]remove extra check in sys_bind

---

bsp/apm32/apm32f030r8-miniboard/rtconfig.py
bsp/apm32/apm32f051r8-evalboard/rtconfig.py
examples/utest/testcases/kernel/mutex_tc.c
src/ipc.c
src/thread.c

[
- BSP:
- .config:
- action:
]

[utest]fix race in mutex tc & add recurse lock tc

---

.github/workflows/static_code_analysis.yml
tools/ci/cpp_check.py

添加summary 方便查看出错信息
[
- BSP:
- .config:
- action:
]

[action][cppcheck] add summary

---

components/net/netdev/src/netdev.c

[
netdev的函数不会在中断中调用，无需关中断
- BSP:
- .config:
- action:
]

[components][sal]replace netdev's spin_lock_irqsave to spin_lock

---

components/drivers/include/drivers/ofw.h
components/drivers/include/drivers/ofw_fdt.h
components/drivers/include/drivers/ofw_io.h
components/drivers/ofw/base.c
components/drivers/ofw/fdt.c
components/drivers/ofw/io.c
components/drivers/ofw/ofw.c

[
Fixup:
1. Remove rt_ofw_foreach_node_by_compatible args's type.
2. Increase append child node's ref_count.
3. Make DTS version header always v1.0.
4. Remove the last empty string for bootargs.
5. Fixup ofw_parse_object object find flow.
Feature:
1. Add bootargs select in early
2. Add address reverse/translate for DMA/CPU's address
Test:
- qemu-virt64-aarch64
- rockchip/rk3568
]

[FIXUP/FEATURE/OFW] OFW API

---

components/dfs/dfs_v2/include/dfs_seq_file.h
components/dfs/dfs_v2/src/dfs_seq_file.c

[
In manual, the prototype of lseek is
`off_t lseek(int fd, off_t offset, int whence);`
where the return type is `off_t` but not ssize_t.
Changes:
- Aligned the current prototype to manual
- BSP:
- .config:
- action:
]

fixup: dfsv2: aligned proto of seq_file_lseek to manual

---

components/lwp/Kconfig

[
The `LWP_CONSOLE_INPUT_BUFFER_SIZE` is a legacy config option for TTY driver used in smart. Since the driver is updated, there's no dependency of this option any more.
Changes:
- Removed unused Kconfig option `LWP_CONSOLE_INPUT_BUFFER_SIZE`
- BSP:
- .config:
- action:
]

fixup: smart: remove unnecessary Kconfig option

---

components/net/sal/src/sal_socket.c

[
ioctlsocket的命令分两部分，一部分是网络设备相关，由sal处理，另一部分是协议族相关，由协议族处理，协议族可以无协议相关的ioctl命令。但是ioctlsocket函数在开头就判断协议族是否有ioctl会导致协议族无协议特定ioctl不能执行公共的ioctl cmd
- BSP:
- .config:
- action:
]

[components][sal]delay getting sal_proto_family in sal_ioctlsocket

---

.github/workflows/doxygen.yml
components/drivers/include/drivers/dev_can.h
components/drivers/include/drivers/dev_serial.h
components/drivers/include/drivers/dev_serial_v2.h
components/finsh/finsh.h
documentation/doxygen/Doxyfile

[
#9424 
添加serial doxygen注释
- BSP:
- .config:
- action:
]

[doxygen] add driver example for doxygen

---

tools/ci/toolchain.sh

[
添加toolchain安装脚本
执行`source ./toolchain.sh all` 会安装所有需要的toolchain，这个会很大
执行`source ./toolchain.sh arm-none-eabi-gcc" 会安装arm-none-eabi-gcc
执行`./toolchain.sh` 会显示所有支持的toolchain
- BSP:
- .config:
- action:
]

[action/ci] Add toolchain stup script

---

components/net/sal/src/sal_socket.c

[
sal_bind原先是在非UNIX/NETLINK协议族时进入中间的流程，而中间流程将sockaddr解析成sockaddr_in，可知只有在使用互联网协议族才走中间流程。如果需要支持更多协议族则需要在if判断里考虑更多中情况。
将if判断改为判断是否是互联网INET协议族
- BSP:
- .config:
- action:
]

[components][sal]修改sal_bind对于协议族的判断

---

components/drivers/ofw/fdt.c

[
1. Fixup `fdt_reserved_memory_reg` loop time.
2. Fixup `rt_fdt_translate_address` cells value reader.
]

[DM/FDT] Fixup memory address reserved and translate in early

---

components/lwp/terminal/tty_ptmx.c

[
The ref_count of the vnode is NOT bound to the resource reference counts of the ptm device created by opening `dev/ptmx`, so the conditional recycling of the resource may end up with memory leaking if multiple users have opened the `dev/ptmx`.
Changes:
- Removed conditional branch on recycling resource
- BSP:
- .config:
- action:
]

fixup: pty: possible memory leaking on close()

---

src/klibc/kstdio.c

- unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]	kstdio.c	
- rttrtt studio 使用的版本并不支持该命令，报错警告
- 没找到什么版本GCC开始支持此命令
- 根据网上搜索,GCC7应该以上是有的
- BSP: bsp\stm32\stm32f407-st-discovery
- .config:
- action:
]

fix:[kstdio]Disable "-Wimplicit-fallthrough" below GNUC V7

---

libcpu/risc-v/SConscript
libcpu/risc-v/t-head/c908/SConscript
libcpu/risc-v/t-head/c908/asm/sbiasm.h
libcpu/risc-v/t-head/c908/asm/sbidef.h
libcpu/risc-v/t-head/c908/cache.c
libcpu/risc-v/t-head/c908/cache.h
libcpu/risc-v/t-head/c908/interrupt.c
libcpu/risc-v/t-head/c908/interrupt.h
libcpu/risc-v/t-head/c908/opcode.h
libcpu/risc-v/t-head/c908/plic.c
libcpu/risc-v/t-head/c908/plic.h
libcpu/risc-v/t-head/c908/riscv_mmu.h
libcpu/risc-v/t-head/c908/symbol_analysis.c
libcpu/risc-v/t-head/c908/symbol_analysis.h

[
- BSP:
- .config:
- action:
]

[libcpu]rv添加c908 cpu

---

components/drivers/include/drivers/adc.h

[
#9424 
添加adcdoxygen注释
- BSP:
- .config:
- action:
]

[doxygen][rsoc] add adc driver example for doxygen

---

bsp/apm32/apm32f030r8-miniboard/applications/main.c
bsp/apm32/apm32f051r8-evalboard/applications/main.c

[
修复apm32/apm32f030r8-miniboard和apm32\apm32f051r8-evalboard编译不通过的问题
修改while循环的条件
- BSP:bsp/apm32/apm32f030r8-miniboard bsp\apm32\apm32f051r8-evalboard
- .config:
- action:
]

[bsp][rsoc] Fix compilation issues with bsp of apm32 series

---

bsp/stm32/stm32f407-rt-spark/board/ports/lvgl/lv_conf.h
bsp/stm32/stm32f407-rt-spark/board/ports/lvgl/lv_port_disp.c

[
这份pr主要是对星火一号开发板中最新的lvgl进行的适配，同时还可以兼容旧版本的lvgl
适配内容主要是对于新旧版本中创建内存的部分做的修改
具体到代码方面则是在原本使用lv_disp_drv_t创建内存的基础增加了使用lv_display_t创建内存
与此同时新版本还添加了对应的LV_FONT_MONTSERRAT_24h以及默认实例必要的宏定义不然编译不通过,同时兼容老版本
该pr在星火一号中分别使用了lvgl的v8.3.11,v8.3-latest,v9.1.0,latest不同的版本进行测试并且通过
- BSP:bsp/stm32/stm32f407-rt-spark
- .config:
- action:
]

[bsp][stm32]lvgl creates adaptations of buffers in high or low versions

---

components/drivers/include/drivers/dac.h

[
- BSP:
- .config:
- action:
]

[doxygen][rsoc]add dac driver example for doxygen

---

components/drivers/rtc/Kconfig
components/drivers/rtc/dev_alarm.c

[
rtc alarm internal thread's attributes are hardcoded which is not good for porting. we should make that configurable.
- BSP:
- .config:
- action:
]

make rtc alarm internal thread's attributes configurable

---

components/drivers/include/drivers/dev_pin.h

[
#9424 
- BSP:
- .config:
- action:
]

[doxygen][rsoc]add pin driver example for doxygen

---

components/utilities/ymodem/ymodem.c

[
issue: #9479
修复ymodem在接收最后一帧时无法自适应SOH/STX的问题
when ymodem receiving last frame in function _rym_do_fin(),
if code is SOH, it should receive another _RYM_SOH_PKG_SZ-1 long data,
if code is STX, it should receive another _RYM_STX_PKG_SZ-1 long data,
but now it will receive _RYM_SOH_PKG_SZ-1 no matter what code is.
- BSP:
- .config:
- action:
]

[components][ymodem] last frame's data_sz issue, fixed.

---

components/drivers/include/drivers/dev_can.h
components/drivers/include/drivers/dev_i2c.h
components/drivers/include/drivers/dev_pin.h
components/drivers/include/drivers/dev_pwm.h
components/drivers/include/drivers/dev_spi.h
components/drivers/include/drivers/dev_touch.h

[
#9424 
- BSP:
- .config:
- action:
]

[doxygen][rsoc]add pwm touch can i2c spi driver example for doxygen

---

components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c

[
添加对每个netdev进行操作的API。这在配置路由等操作时会用到
rockchip
- BSP:
- .config:
- action:
]

[component][sal]add netgetdev api

---

libcpu/aarch64/common/include/armv8.h
libcpu/aarch64/common/include/cpuport.h
libcpu/aarch64/common/mp/context_gcc.S
src/scheduler_mp.c

[
This patch improves the atomicity of context switching by ensuring that the stack pointer (sp) and thread self updates occur simultaneously. This enhancement is crucial for maintaining thread safety and preventing potential inconsistencies during context switches.
Changes:
- Modified `cpuport.h` to use `ARM64_THREAD_REG` for thread self access.
- Added an `update_tidr` macro in `context_gcc.S` to streamline thread ID updates.
- Adjusted `rt_hw_context_switch_to` and `rt_hw_context_switch` to call `update_tidr`, ensuring atomic updates during context switches.
- Cleaned up `scheduler_mp.c` by removing redundant thread self assignments.
- BSP:
- .config:
- action:
]

feat: arm64: update thread self on sp-switch

---

components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c
components/net/sal/src/sal_socket.c

[
- BSP:
- .config:
- action:
]

[components][sal]add netdev ifindex feature

---

libcpu/risc-v/common64/asid.c

Corrected the SATP register to ensure it uses the correct 64-bit format as required by the system architecture.
[
For the qemu-virt64-riscv BSP, when running the smart version, the system fails to boot properly if ARCH_USING_ASID=y.
Change the type of the variable satp_reg in rt_hw_asid_init to rt_uint64_t.
- BSP: bsp/qemu-virt64-riscv
- .config: CONFIG_ARCH_USING_ASID=y
- action:
]

[libcpu][risc-v] fix the bug when using ASID in the RV64 MMU.

---

bsp/nuvoton/libraries/m2354/rtt_port/drv_usbhost.c
bsp/nuvoton/libraries/m460/rtt_port/drv_usbhost.c
bsp/nuvoton/libraries/m480/rtt_port/drv_usbhost.c
bsp/nuvoton/libraries/ma35/rtt_port/drv_usbhost.c
bsp/nuvoton/libraries/n9h30/rtt_port/drv_usbhost.c
bsp/nuvoton/libraries/nuc980/rtt_port/drv_usbhost.c
include/rtsched.h
src/Kconfig

[
Remove compatible definition for v5.1.0 and before.
- BSP:
- .config:
- action:
]

[kconfig] remove RT_USING_SCHED_THREAD_CTX

---

include/rtthread.h
src/components.c
src/defunct.c
src/idle.c

lwp的某些资源回收放到了后台，其中会引起线程挂起，而idle不应该被挂起
[
用户态程序退出后在idle中回收资源会触发assert(mutex->owner == current-thread)
单核smart模式也启用回收线程
#9181 milkv  
]

[kernel]在smart模式也启用"回收线程"

---

components/lwp/lwp_syscall.c

[
This patch addresses a use-after-free (UAF) vulnerability in the sys_mount. The issue occurred due to improper handling of memory deallocation, which could lead to crashes or undefined behavior on user request of mounting.
Changes:
- Moved the `rt_free(copy_source)` function call to occur after the necessary operations are completed, preventing premature deallocation of memory.
- BSP:
- .config:
- action:
]

fixup: smart: sys_mount: UAF vulnerability

---

src/signal.c

[
utest中，kernel/signal_tc.c中，rt_signal_wait_test fail.
```
[E/utest] [  ASSERT  ] [ unit     ] at (signal_tc.c); func: (rt_signal_wait_test:157); msg: ((recive_sig) not equal to (SIGUSR1))
[E/utest] [  FAILED  ] [ result   ] testcase (testcases.kernel.signal_tc)
```
在 rt_signal_wait_thread 中，通过` (void)sigaddset(&selectset, SIGUSR1)`将信号 SIGUSR1 添加到 selectset 中。但在使用 musl-libc 时，sigaddset接口将*selectset 被设置为 (*selectset) | (1 << (signo - 1))。这导致在 rt_signal_wait 函数中的 if (sig_mask(signo) & *set)（第403行）判断条件不满足。
在使用musl-libc时，#define sig_mask(sig_no)    (1u << (sig_no - 1))，与sigaddset接口的实现保持一致；
- BSP: bsp/qemu-virt64-riscv 
- .config: RT_USING_MUSLLIBC =y
- action:
]

[src][signal]:fix the issue of inconsistent results between sigaddset and sig_mask when using musl-libc 

---

include/rtdef.h
include/rtthread.h

When RT_USING_DEBUG is disabled, variables used only in RT_ASSERT statements become unused, triggering -Wunused-but-set-variable compiler warnings. These variables are essential for runtime assertions in debug builds but appear unused in release builds.
Example:
- Variables used in RT_ASSERT(var != RT_NULL) checks
- Affects multiple drivers and components using RT_ASSERT
This is a general cleanup to improve code compilation without affecting functionality.
[
避免編譯警告
透過 { (void)(EX); }告知編譯器
例如 HMI Board 的 BSP 會出現
譬如下面這段源代碼
```
/* I2C initialization function */
int rt_hw_i2c_init(void)
{
rt_size_t obj_num = sizeof(i2c_obj) / sizeof(struct ra_i2c);
rt_err_t result;
for (int i = 0; i < obj_num; i++)
{
i2c_obj[i].ops = ra_bit_ops_default;
i2c_obj[i].ops.data = (void *)&soft_i2c_config[i]; …
```

fix: suppress unused warnings when DEBUG disabled

---

bsp/raspberry-pico/board/Kconfig

[
bsp/raspberry-pico/board/Kconfig中SPI1的MISO_PIN, CS_PIN存在错误, 导致rtconfig.h缺少SPI1的部分定义
使用SPI1时编译报错:
drivers/drv_spi.c:51:24: error: 'BSP_SPI1_MISO_PIN' undeclared here (not in a function); did you mean 'BSP_SPI0_MISO_PIN'?
51 |         .spi_rx_pin  = BSP_SPI1_MISO_PIN,
|                        ^~~~~~~~~~~~~~~~~
|                        BSP_SPI0_MISO_PIN
修复Kconfig中错误的部分
- BSP: bsp/raspberry-pico
- .config:
- action:
]

[bsp][raspberry-pico] 修复rtconfig.h SPI1部分引脚错误问题

---

components/libc/posix/libdl/arch/arm.c
components/libc/posix/libdl/arch/riscv.c
components/libc/posix/libdl/arch/x86.c
components/libc/posix/libdl/dlclose.c
components/libc/posix/libdl/dlelf.c
components/libc/posix/libdl/dlelf.h
components/libc/posix/libdl/dlerror.c
components/libc/posix/libdl/dlfcn.h
components/libc/posix/libdl/dlmodule.c
components/libc/posix/libdl/dlmodule.h
components/libc/posix/libdl/dlopen.c
components/libc/posix/libdl/dlsym.c
components/libc/posix/libdl/dlsyms.c

[
add comments for libdl APIs to make source code easier to read.
add comments for each api with doxygen format, describe each function content, its parameters and return values. 
- BSP:
- .config:
- action:
]

[libc] add comments for libdl APIs.

---

components/dfs/dfs_v2/filesystems/devfs/devfs.c

[
POSIX.1 says:
>  read() attempts to read up to count bytes from file descriptor fd
>  into the buffer starting at buf.
On the other hand, for rt_device_read, the `@size` is defined as the number of units (block size for blk device, otherwise one byte).
In the current implementation, the devfs does not take care of this API misalignment, which could lead to excessive data reading/writing to devices.
Changes:
- Transferred unit size from POSIX R/W(in bytes) to rt_device_R/W during request of file R/W operations.
- BSP:
- .config:
- action:
]

feat: devfs: handling unit size in POSIX RW request

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_can.c
components/drivers/can/dev_can.c
components/drivers/include/drivers/dev_can.h

[
- fix:[CAN][STM32]open时立刻启动can_start,还未完成其他配置,可能导致异常
- open时不启动can_start
- 由control控制启动与stop
- BSP: STM32F407
]

fix:[CAN][STM32]open时立刻启动can_start,还未完成其他配置,可能导致异常

---

libcpu/risc-v/common64/context_gcc.S
libcpu/risc-v/common64/interrupt_gcc.S

[
内核链接太多静态库后会导致jal指令跳转范围不够用
- BSP:
k230
- .config:
- action:
]

[libcpu]riscv使用call指令解决长跳转问题

---

.github/workflows/action_tools.yml
tools/options.py

这个暂时不能改，bsp中的工程名默认为project
改了之后`scons --target=mdk5`之后的工程名都变了
之前为`project.uvprojx`
Reverts RT-Thread/rt-thread#9625

Revert "[tools] use project's dir basename as default project name"

---

components/drivers/core/dm.c
components/drivers/include/drivers/core/dm.h
components/drivers/include/drivers/core/master_id.h
include/rtdef.h

Drivers can manage their own IDs without having to concern themselves with the register/unregister in system
[
Support a system device id management
Link: https://github.com/RT-Thread/rt-thread/issues/9534
]

[DM/FEATURE] DM Device IDA management

---

components/drivers/core/platform.c
components/drivers/core/platform_ofw.c
components/drivers/include/drivers/ofw.h
components/drivers/include/drivers/platform.h
include/rtdef.h
libcpu/aarch64/common/psci.c

[
1. remove OFW switch macros
2. Support driver depends fix auto
3. Support clock subprobe in OFW
- BSP:
1. qemu-virt64-aarch64
2. rockchip/rk3568
]

[DM/FEATURE] Update platform depends rules

---

components/libc/posix/pthreads/pthread_barrier.c

[
1. 为pthread barrier API增加注释；
2. 修正一些问题：
1）pthread_barrierattr_setpshared中，将PTHREAD_PROCESS_PRIVATE直接赋值给指针attr，应该赋给*attr。此外，该函数的返回值在任何时候都是EINVAL；
2）pthread_barrier_destroy函数，在执行destroy前，未检查barrier->count是否为0，即barrier是否仍在使用中。此外，此函数只销毁了barrier中的条件变量cond，而没有销毁mutex。
增加代码以及修正以上问题。
- BSP:
- .config:
- action:
]

add comments for pthread barrier APIs and fix some errors.

---

components/libc/posix/pthreads/pthread_tls.c

[
thread local storage APIs have no comments.
add comments for thread local storage APIs.
- BSP:
- .config:
- action:
]

[components/libc/posix]add comments for thread local storage APIs.

---

tools/cmake.py

[
解决一下cmake脚本处理时对于仅大小写不同的Group，强制转换为大写后生成同一个名称的source group导致覆盖的问题
before
after
添加后缀
- BSP:
hc32f460
- .config:
- action:
]

[tools][cmake] fix processing groups with similar name

---

src/Kconfig

[
- BSP:
- .config:
- action:
]

[kernel] format Kconfig

---

components/drivers/serial/dev_serial_v2.c

[
将串口驱动V2中两处注释（从循环缓冲区中获取线性缓冲区指针）中被错误拼写为“rinbuffer”的"ringbuffer"修改过来，本次提交仅涉及两处注释中的各一个单词，没有修改代码
]

[drivers] fixed a minor typo in the comments of dev_serial_v2.c

---

libcpu/Kconfig
libcpu/aarch64/Kconfig
libcpu/aarch64/common/include/mmu.h
libcpu/aarch64/common/include/tlb.h
libcpu/aarch64/common/mmu.c

[
Support for ARM64 ASID to enhance virtual memory management efficiency by reducing the need for TLB flushes during address space switches. These changes improve performance especially for multi-process systems.
Changes:
- Added `ARCH_USING_ASID` configuration in `libcpu/aarch64/Kconfig`.
- Defined ASID-related constants in `mmu.h`.
- Updated `TLBI_ARG` macro to include ASID manipulation.
- Implemented ASID allocation mechanism with spinlock synchronization.
- Enhanced TLB invalidation to support ASID-specific operations.
- Modified `rt_hw_aspace_switch` to use ASIDs when switching address spaces.
- Adjusted debug logging and function documentation to reflect ASID usage.
- Refactored AArch64 MMU and TLB handling for ASID integration.
- Moved AArch64 architecture configuration to a …

feat: arm64 ASID support

---

include/klibc/kerrno.h
include/klibc/kstdio.h
include/klibc/kstring.h
src/SConscript
src/klibc/SConscript
src/klibc/kstdio.c
src/klibc/rt_vsnprintf_std.c
src/klibc/rt_vsscanf.c

线程安全rt_sscanf
从https://github.com/PetteriAimonen/Baselibc 移植 BSD license
[
- BSP:
- .config:
- action:
]

[klibc] add rt_sscanf

---

bsp/nxp/mcx/mcxa/Libraries/drivers/drv_wdt.c
bsp/nxp/mcx/mcxa/Libraries/drivers/drv_wdt.h

[
add watch dog driver for NXP MCXA153 Board
modify BSP driver files in `bsp/nxp/mcx/mcxa/frdm-mcxa153` directory
- BSP: bsp/nxp/mcx/mcxa/frdm-mcxa153
- .config: CONFIG_RT_USING_WDT
- action: https://github.com/hywing/rt-thread/commit/9d827271b90916d31b076a8beae532c497d5cea2
]

[bsp][nxp][mcxa153] add watch dog driver

---

components/drivers/pci/ofw.c
components/drivers/pci/probe.c

[
Some PCI device devicetree is like:
```dts
pcie@fe270000 {
device_type = "pci";
msi-map = <0x1000 0x9c 0x1000 0x1000>;
pcie@10 {
reg = <0x100000 0x00 0x00 0x00 0x00>;
#address-cells = <0x03>;
#size-cells = <0x02>;
pcie@10,0 {
reg = <0x00 0x00 0x00 0x00 0x00>;
};
};
};
```
that the pcie@10,0 have a private ofw node, it will find property name `msi-map` or `msi-parent` fail.
We should only find the property in host bridge's ofw node.
- BSP:
rockchip/rk3568 (rock3a,r5s,r5c)
]

[DM/FIXUP] Fixup PCI device ofw private node for MSI

---

components/utilities/ulog/ulog.c

[
Some ulog APIs have no comments.
add some comments to ulog for supplement.
- BSP:
- .config:
- action:
]

[components][ulog]add some comments to ulog for supplement.

---

src/components.c

Fixed #9671 
When RT_DEBUGING_AUTO_INIT is enabled, kenrel will add more print message for auto init. However, the original format easily causes the kernel printing and the init function printing to be connected together, resulting in a confusing display format.
For exmaple:
```
initialize lwip_system_initlwIP-2.0.3 initialized!
:0 done
```
Or
```
initialize sal_init[I/sal.skt] Socket Abstraction Layer initialize success.
:0 done
```
Solution: Add a carriage return to separate the kernel printing and the init function printing.
After changing, the output will be:
```
initialize lwip_system_init
lwIP-2.0.3 initialized!
:0 done
```
Or
```
initialize sal_init
[I/sal.skt] Socket Abstraction Layer initialize success.
:0 done
```
一个更好的的 screen scratch
修改前：
修改后：
[
- BSP:
- .config:
- action:
] …

kernel: Optimize display format for auto init when debugging

---

documentation/basic/basic.md
documentation/finsh/finsh.md

…acro in markdown files.
[
some comments about FINSH_USING_SYMTAB in md files are not correct. This macro has nothing to do with the TAB key.
fix the wrong comments for FINSH_USING_SYMTAB.
- BSP:
- .config:
- action:
]

[documentation][Finsh]fix the wrong comments for FINSH_USING_SYMTAB macro in markdown files.

---

components/drivers/include/drivers/dev_spi.h
components/drivers/spi/SConscript
components/drivers/spi/dev_spi.c
components/drivers/spi/dev_spi_bus.c
components/drivers/spi/dev_spi_core.c
components/drivers/spi/dev_spi_dm.c
components/drivers/spi/dev_spi_dm.h

[
Support DM mode in SPI
- BSP:
rockchip/rk3568
rockchip/rk3588
]

[DM/SPI] Support DM mode in SPI

---

components/drivers/include/drivers/pci_endpoint.h
components/drivers/pci/endpoint/SConscript
components/drivers/pci/endpoint/mem.c
components/drivers/pci/host/Kconfig
components/drivers/pci/host/dw/Kconfig
components/drivers/pci/host/dw/SConscript
components/drivers/pci/host/dw/pcie-dw.c
components/drivers/pci/host/dw/pcie-dw.h
components/drivers/pci/host/dw/pcie-dw_ep.c
components/drivers/pci/host/dw/pcie-dw_host.c
components/drivers/pci/host/dw/pcie-dw_platfrom.c

[
Add DesignWare PCIe RC/EP base drivers, too many PCI controllers base on DesignWare PCIe:
- Amazon Annapurna Labs
- Amlogic Meson
- Axis ARTPEC-6 (RC/EP)
- Baikal-T1
- Freescale i.MX6/7/8 (RC/EP)
- Freescale Layerscape (RC/EP)
- HiSilicon Hip05 and Hip06
- HiSilicon Kirin
- HiSilicon STB
- Intel Gateway
- Intel Keem Bay (RC/EP)
- Marvell Armada-8K
- NVIDIA Tegra194 ~ (RC/EP)
- Qualcomm (RC/EP)
- Renesas R-Car Gen4 (RC/EP)
- Rockchip (RC/EP)
- Samsung Exynos
- SiFive FU740
- Socionext UniPhier (RC/EP)
- STMicroelectronics SPEAr
- TI DRA7xx (RC/EP)
- TI Keystone (RC/EP)
- Toshiba Visconti
This is a public module.
We Add memory window pool for EP.
- BSP:
rockchip/rk3568 (rock3a,r5s,r5c)
] …

[DM/PCI] Add DesignWare PCIe RC/EP base drivers

---

libcpu/risc-v/common64/cpuport.h

[
解决如下编译问题
```
/mnt/f/github/rt-thread/libcpu/risc-v/common64/cpuport.h: Assembler messages:
/mnt/f/github/rt-thread/libcpu/risc-v/common64/cpuport.h:18: Error: unrecognized opcode `typedef union{'
/mnt/f/github/rt-thread/libcpu/risc-v/common64/cpuport.h:19: Error: unrecognized opcode `unsigned long slock'
/mnt/f/github/rt-thread/libcpu/risc-v/common64/cpuport.h:20: Error: unrecognized opcode `struct __arch_tickets{'
/mnt/f/github/rt-thread/libcpu/risc-v/common64/cpuport.h:21: Error: unrecognized opcode `unsigned short owner'
/mnt/f/github/rt-thread/libcpu/risc-v/common64/cpuport.h:22: Error: unrecognized opcode `unsigned short next'
/mnt/f/github/rt-thread/libcpu/risc-v/common64/cpuport.h:23: Error: junk at end of line, first unrecognized character is `}' …
```

[libcpu/riscv]解决smp下cpuport.h中的编译问题

---

components/dfs/dfs_v1/src/dfs_posix.c
components/dfs/dfs_v2/src/dfs_posix.c

[
补充部分注释，以及修改原注释中的问题，如“directive”误写成了“directory”。
补充和修改部分注释。
- BSP:
- .config:
- action:
]

[documentation][dfs]add some comments to dfs posix APIs for supplement.

---

bsp/renesas/libraries/HAL_Drivers/drv_pwm.c

[
- BSP:
- .config:
- action:
]

[bsp][renesas] 瑞萨PWM框架 GPT时钟支持RZ系列

---

components/drivers/include/drivers/dev_pin.h
components/drivers/pin/Kconfig
components/drivers/pin/dev_pin.c
components/drivers/pin/dev_pin_dm.c
components/drivers/pin/dev_pin_dm.h
components/drivers/pin/dev_pin_ofw.c

[
1. Fixup pin depend auto.
2. Fixup pin flags get from OFW.
3. Support virtual pin for multi gpio chip.
4. Add sets pin debounce time API.
Depends on: https://github.com/RT-Thread/rt-thread/pull/9576
- BSP:
rockchip/rk3568
]

[DM/FEATURE] Update Pin core

---

components/dfs/dfs_v1/src/dfs.c
components/dfs/dfs_v1/src/dfs_file.c
components/dfs/dfs_v1/src/dfs_fs.c

[
1. 补充一些注释；
2. 修改原注释中的错误：
dfs_unlock()的注释为“this function will **lock** device file system.”
3. dfs_file_unlock()函数的定义不应放在DFS_USING_POSIX宏的内部，否则当DFS_USING_POSIX选项关掉的时候，部分调用它 
的函数如sys_dup2()会编译不通过。
补充及修改注释，修正上述问题3。
- BSP:
- .config:
- action:
]

[components][dfs]add some comments and fix some former comments error for dfs v1.

---

.github/workflows/doxygen.yml
components/dfs/dfs_v2/src/dfs_posix.c
components/drivers/include/drivers/dev_spi.h

[
使能doxygen检查
- BSP:
- .config:
- action:
]

doc(doxyge):fix doxygen path

---

components/drivers/ofw/fdt.c
components/mm/mm_memblock.c

[
- BSP:
- .config:
- action:
]

[componets] fix when printf 0 addr by %p will return nil

---

.devcontainer/Dockerfile
tools/vsc.py

[
workspace中添加clangd的支持，实现精确跳转
发现生成了compile_command.json 文件之后，workspace中添加支持。
只要在bsp中的SConstruct添加下面代码即可，然后执行`scons --target=vsc` 打开workspace文件即可跳转
```
env.Tool('compilation_db')
env.CompilationDatabase()
DoBuilding(TARGET, objs)
```
- BSP:bsp/nrf5x/nrf5340
- .config:
- action:
]

tools: add clangd support

---

components/drivers/rtc/dev_alarm.c
components/drivers/rtc/dev_soft_rtc.c

[
修复PR考虑不周的问题：https://github.com/RT-Thread/rt-thread/pull/9721#issuecomment-2531000024
目前有很大一部分软件包还有bsp使用的软件rtc设备命名都是rtc，不方便直接修改，默认还是使用rtc
- BSP:
- .config:
- action:
]

[drivers][rtc] Fixed software and hardware rtc device naming as rtc

---

tools/vsc.py

[
之前的workspace路径不是太准确，有些目录不合理，现在根据compile_command.json文件实现精准定位文件夹和跳转
通过  compile_commands.json 添加workspace ，可以实现精准定位所有编译的文件夹，并且通过clangd可以实现跳转
只要在bsp中的SConstruct中添加下面的代码,先执行scons，生成compile_command.json, 然后执行`scons --target=vsc` 然后打开workspace即可。
```
env.Tool('compilation_db')
env.CompilationDatabase()
```
效果如图所示：
- BSP:nrf5x/nrf5340
- .config:
- action:
]

[tools] generate workspace by compile_commands.json

---

bsp/stm32/libraries/HAL_Drivers/drivers/config/f1/dma_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/config/f1/i2c_hard_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_hard_i2c.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_hard_i2c.h

[
- 我正在尝试使用rt-thread进行项目开发，发现硬件I2C驱动并没有支持我使用的STM32F1系列芯片。
- 基于现有驱动完善对STM32F1系列的支持
- 完善的过程中发现了现有驱动的通用bug，并进行了修复
- BSP: 没有官方BSP列表中的开发板，使用的是基于模板修改而来的BSP。
- 使用scons --dist命令将BSP导出，因文件上传大小限制，已剔除rt-thread文件夹：[project.zip](https://github.com/user-attachments/files/18072648/project.zip)
- .config: bsp工程中board文件夹下的Kconfig文件，添加以下定义：
```
menu "On-chip Peripheral Drivers"
...
...
...
menuconfig BSP_USING_I2C
bool "Enable I2C1 BUS (hardware)"
default n
select RT_USING_I2C
if BSP_USING_I2C
config BSP_USING_HARD_I2C1
bool "Enable I2C1 BUS"
default n
config BSP_I2C1_TX_USING_DMA
bool "Enable I2C1 TX DMA"
depends on BSP_USING_HARD_I2C1
default n
config BSP_I2C1_RX_USING_DMA
bool "Enable I2C1 RX DMA"
depends on BSP_USING_HARD_I2C1
default n
endif
...
...
...
```
- action: null
]
必须选择一项 Choose one …

[bsp][stm32] hardware i2c driver add support for STM32F1 series

---

components/dfs/dfs_v1/filesystems/iso9660/dfs_iso9660.c

[
1. Fix strchrnul.
2. Fix type of lseek return.
3. Fix packed
]

[DFS/FIXUP] Fixup ISO9660 build

---

components/drivers/mailbox/mailbox-pic.c
components/drivers/pic/pic-gicv2.c
components/drivers/pic/pic-gicv2.h
components/drivers/pic/pic-gicv3.c
components/drivers/pic/pic-gicv3.h

[
1. PIC GICv2 and GICv3 support on AMP slave mode.
2. PIC-Mailbox support on AMP master/slave mode.
- BSP:
]

[DM/PIC] Support AMP mode

---

components/libc/posix/io/timerfd/timerfd.c

[
timer fd posix APIs have no comments.
add comments for timer fd APIs.
- BSP:
- .config:
- action:
]

[components][libc/io]add comments for timer fd APIs.

---

bsp/nxp/imx/imxrt/libraries/drivers/drv_eth.c
components/lwp/arch/x86/i386/lwp_arch.c
components/lwp/lwp.c
components/lwp/lwp_syscall.c
components/utilities/ulog/ulog_def.h
include/rtdbg.h

Fixed: #9783 
- `dbg_log` is a “NOT RECOMMENDED API”, convert the calling of this API to LOG_x and remove this API.
- `dbg_here`/`dbg_enter`/`dbg_exit`: no one use these APIs, remove them directly.
[
- BSP:
- .config:
- action:
]

kernel: cleanup debug APIs

---

bsp/apm32/libraries/Drivers/drv_sdio.h
bsp/at32/libraries/rt_drivers/drv_sdio.h
bsp/bluetrum/libraries/hal_drivers/drv_sdio.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_sdio.h

[
我在测试stm32和at32的sdio驱动sd卡的文件读写的时候，发现文件读写速度不如预期；于是参考论坛文章，将
sdioMaxFreq的速度修改为24000000，但是没有生效，后面才发现，这个sdio.h的头文件中有两处SDIO_MAX_FREQ的宏定义，而我修改的是下面那一处，所以没有生效；
https://club.rt-thread.org/ask/question/b9257a9b2467df77.html
删除多余的SDIO_MAX_FREQ宏定义（有些板子的库文件就只有一处这个宏定义，比如hc32）；
其实也可以在kconfig中加入SDIO_MAX_FREQ宏定义，但是大多数bsp的template是没有这个kconfig的；
无
- .config:
- action:
没看明白
]

[opt][SDIO_MAX_FREQ redundant define del]

---

components/libc/compilers/common/cstring.c
components/utilities/utest/utest.c
components/utilities/utest/utest_log.h
src/Kconfig
src/klibc/Kconfig
src/klibc/utest/SConscript
src/klibc/utest/tc_kstdlib.c

在RT_USING_CI_ACTION宏使能时，会开机自动运行utest 测试用例
[
- BSP:
- .config:
- action:
]

add demo of new utest cases

---

documentation/doxygen/readme.md

Update readme doc to introduce how to build doxygen and run html on Ubuntu machines.
[
- BSP:
- .config:
- action:
]

doc: introduce how to build & run doxygen on ubuntu

---

bsp/stm32/stm32l475-atk-pandora/board/linker_scripts/link.lds
src/klibc/Kconfig
src/klibc/rt_vsnprintf_tiny.c
src/klibc/utest/SConscript
src/klibc/utest/TC_kstdlib.c
src/klibc/utest/TC_rt_sprintf.c

[
- BSP:
- .config:
- action:
]

[utest][klibc] add rt_sprintf family functions test cases

---

components/drivers/rtc/dev_soft_rtc.c

[
- BSP:
- .config:
- action:
]

[drivers][rtc] fix rtc assert

---

bsp/nxp/mcx/mcxa/Libraries/drivers/drv_pwm.c
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/Kconfig
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/MCUX_Config/board/pin_mux.c

[
implement the real eFlexPWM driver instead of using CTimer
modify files in `bsp/nxp/mcx/mcxa/frdm-mcxa153` directory
- BSP: bsp/nxp/mcx/mcxa/frdm-mcxa153
- .config: BSP_USING_PWM0 BSP_USING_PWM1 BSP_USING_PWM2
- action: https://github.com/hywing/rt-thread/commit/ecdab1f9392df137aec024aaea8858c68d24ee0e
]

[bsp][nxp][mcxa153] the full implementation of eFlexPWM

---

components/net/lwip/lwip-2.1.2/src/core/dns.c
components/net/lwip/lwip-2.1.2/src/core/ipv4/dhcp.c
components/net/lwip/lwip-2.1.2/src/core/ipv6/dhcp6.c
components/net/lwip/lwip-2.1.2/src/core/ipv6/nd6.c
components/net/lwip/lwip-2.1.2/src/netif/ppp/ppp.c
components/net/lwip/port/ethernetif.c

[
**在使用多个网络设备时，`dns servers`会被`DHCP`应答处理设置到所有网络设备**
- 在使用`WiFi + ETH + PPP`三个网络设备的情况下，`WiFi`和`ETH`往往使用的是网关作为DNS服务器
- 在`WiFi`和`ETH`发起`DHCP`请求时，`PPP设备(GSM模组)`的DNS服务器也会被设置到`WiFi`和`ETH`的`网关IP`
- 如果`默认的网络`是`PPP网络设备`，那么发起的`DNS`请求会到`WiFi/ETH`的`网关IP`去，导致`gethostbyname`超时
**以下是修改前的DNS IP**
```
msh />dns
network interface device: e0 (Default)
dns server #0: 202.96.128.86
dns server #1: 202.96.134.133
network interface device: w0
dns server #0: 202.96.128.86
dns server #1: 202.96.134.133
network interface device: w1
dns server #0: 0.0.0.0
dns server #1: 0.0.0.0
network interface device: pp
dns server #0: 202.96.128.86
dns server #1: 202.96.134.133
```
- 由于`GSM`启动较慢，`WiFi`和`ETH`先获取到了`DNS`，而后面启动的`PPP网络设备`将`WiFi`和`ETH`的`DNS`都给改掉了
- 且等待一段时间后，`WiFi`和`ETH`再次发起`DHCP`请求时，`PPP网络设备`的`DNS`会被换成`WiFi`和`ETH`的`DNS` …

[components][lwip] add support for independent dns services for multiple network devices

---

components/drivers/wlan/dev_wlan.c
components/drivers/wlan/dev_wlan.h
components/drivers/wlan/dev_wlan_mgnt.c

[
- BSP:
- .config:
- action:
]

[wlan] add get_info api for more new sta information

---

components/drivers/block/partitions/dfs.c

[
`sector` was alloc from memheap, we should free after partition probe.
]

[DM/BLOCK] Fixup DFS partition memory leak

---

components/libc/compilers/common/include/dirent.h

使用gd32470z-lckfb BSP时发现，在未经任何修改的前提下，使用scons命令生成的keil工程编译不通过
BUG原因：components\libc\compilers\common\include\dirent.h文件中，RT_USING_MUSLLIBC 宏的使用使得 ino_t 类型的定义依赖于该宏是否被定义。如果该宏未定义，ino_t 类型将未声明，导致编译错误。
将ino_t d_ino;也加入条件编译
resolved #9833 
- BSP:bsp\gd32\arm\gd32470z-lckfb
- .config:无
- action:
[![pkgs_test](https://github.com/godmial/rt-thread/actions/workflows/pkgs_test.yml/badge.svg)](https://github.com/godmial/rt-thread/actions/workflows/pkgs_test.yml)
]
- [*] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, …

解决了components\libc\compilers\common\include\dirent.h libc_dirent结构体报错的bug

---

components/dfs/dfs_v2/src/dfs_pcache.c
components/drivers/core/device.c
components/fal/src/fal_rtt.c

[
自己板子
当定义了RT_USING_DFS_V2但未定义RT_RT_USING_DFS_DEVFS时，编译报错
当定义了RT_USING_DFS_V2但未定义RT-USING_SMART时，会发生错误
fal_rtt.c 缺少头，提醒函数未定义
修改源码
[ 
[config.txt](https://github.com/user-attachments/files/18203351/config.txt)
]
- BSP: bsp\stm32\stm32f103-atk-nano
- action:
]
- 已经仔细查看过代码改动的对比 Already check the difference between PR and old code

修复编译过程中的 DFS_V2报错、FAL警告

---

components/drivers/include/ipc/workqueue.h
components/drivers/ipc/workqueue.c

[
bsp\qemu-vexpress-a9
1、Fixed #9814
2、去掉每个work的定时器，能大量减少 work的内存占用，和性能优化
去掉work的 timer，只需要在 work线程里面 延迟和同步即可
- BSP: bsp\qemu-vexpress-a9
- .config:  没用改动，直接 menuconfig 生成新的即可
- action: 
测试main函数如下
~~~c
#include <stdint.h>
#include <stdio.h>
struct rt_work work_test0;
struct rt_work work_test1;
struct rt_work work_test2;
struct rt_work work_test3;
struct rt_work work_test4;
void work_func(struct rt_work *work, void *work_data)
{
rt_kprintf("name=%s tick=%d\n", (char *)work_data, rt_tick_get());
}
int main(void)
{
rt_kprintf("Hello RT-Thread!\n");
rt_thread_delay(100);
rt_work_init(&work_test0, work_func, "work_test0");
rt_work_init(&work_test1, work_func, …

workqueue 去掉timer，使用list排序处理方式

---

.github/workflows/doxygen.yml

[
将doxygen部署到github pages上
- BSP:
- .config:
- action:
]

[doc] doxygen attach github pages

---

components/net/at/include/at.h
components/net/at/src/at_client.c
components/net/at/src/at_server.c

[
令 AT 组件支持 SERIAL_V2
- BSP: STM32F407VG
- .config:
- action:
]

[AT] AT_Device 适配 SERIAL_V2

---

components/utilities/utest/TC_uassert.c
components/utilities/utest/utest.c
components/utilities/utest/utest.h
components/utilities/utest/utest_assert.h
src/klibc/utest/TC_rt_memcmp.c
src/klibc/utest/TC_rt_memcpy.c
src/klibc/utest/TC_rt_memmove.c
src/klibc/utest/TC_rt_memset.c
src/klibc/utest/TC_rt_sprintf.c

[
- BSP:
- .config:
- action:
]

[utest] add rt_memset test case

---

src/kservice.c

[
- BSP:
- .config:
- action:
]

[kservice] optimize console_device

---

components/drivers/wlan/dev_wlan.c
components/drivers/wlan/dev_wlan.h
components/drivers/wlan/dev_wlan_mgnt.c

[
- BSP:
- .config:
- action:
]

[wlan] add ap_get_info api for more ap information

---

components/drivers/ipc/workqueue.c

[
**会导致MDK下使用默认的C99标准编译不通过**
在最近关于工作队列的 [PR](https://github.com/RT-Thread/rt-thread/pull/9825) 中，使用了`rt_list_for_each_entry` API 进行列表对象遍历，`rt_list_for_each_entry` API实现中引入了`typeof`关键字，`typeof`关键字属于 GNU C 标准中的一个扩展特性。
使用C99标准实现列表遍历
- BSP:
STM32F407-rt-spark
- .config:
- action:
]

[wq][fix]工作队列默认使用C99标准实现遍历

---

tools/building.py

[
- 添加更方便、好用的logging系统，当`scons --verbose`时可以输出更多构建调试信息；
- 把logging添加到Env['log']中；
- BSP: qemu-vexpress-a9
- .config:
- action:
]

[tools] add logging as Env['log']

---

components/utilities/utest/TC_uassert.c
components/utilities/utest/utest.h
components/utilities/utest/utest_assert.h
src/klibc/utest/TC_rt_memcmp.c
src/klibc/utest/TC_rt_sscanf.c

uassert_float_equal and uassert_float_not_equal
[
- BSP:
- .config:
- action:
]

[utest] add float operators

---

components/utilities/Kconfig
components/utilities/utest/utest.c
src/Kconfig
src/klibc/utest/SConscript

RT_USING_CI_ACTION will select RT_UTEST_USING_AUTO_RUN and RT_UTEST_USING_ALL_CASES
[
- BSP:
- .config:
- action:
]

[utest] make RT_USING_CI_ACTION to be clear

---

components/dfs/dfs_v2/filesystems/devfs/devtmpfs.c
components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c
components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.h
components/dfs/dfs_v2/include/dfs_vfs.h

抽象非基于硬盘的文件系统(如tmpfs,devtmpfs等)的文件组织，独立成API使用
[
- BSP:
- .config:
- action:
]

[components][dfs]separate dfs fs data structure ops

---

components/dfs/Kconfig
components/dfs/dfs_v2/filesystems/procfs/README.md
components/dfs/dfs_v2/filesystems/procfs/SConscript
components/dfs/dfs_v2/filesystems/procfs/proc.c
components/dfs/dfs_v2/filesystems/procfs/proc.h
components/dfs/dfs_v2/filesystems/procfs/proc_cmdline.c
components/dfs/dfs_v2/filesystems/procfs/proc_cpuinfo.c
components/dfs/dfs_v2/filesystems/procfs/proc_devices.c
components/dfs/dfs_v2/filesystems/procfs/proc_filesystems.c
components/dfs/dfs_v2/filesystems/procfs/proc_loadavg.c
components/dfs/dfs_v2/filesystems/procfs/proc_meminfo.c
components/dfs/dfs_v2/filesystems/procfs/proc_mounts.c
components/dfs/dfs_v2/filesystems/procfs/proc_net.c
components/dfs/dfs_v2/filesystems/procfs/proc_partitions.c
components/dfs/dfs_v2/filesystems/procfs/proc_pid.c
components/dfs/dfs_v2/filesystems/procfs/proc_self.c
components/dfs/dfs_v2/filesystems/procfs/proc_stat.c
components/dfs/dfs_v2/filesystems/procfs/proc_tty.c
components/dfs/dfs_v2/filesystems/procfs/proc_uptime.c
components/dfs/dfs_v2/filesystems/procfs/proc_version.c
components/dfs/dfs_v2/filesystems/procfs/procfs.c
components/dfs/dfs_v2/filesystems/procfs/procfs.h

[
- BSP:
- .config:
- action:
]

[components][fs]sync procfs

---

bsp/cvitek/c906_little/board/interrupt.c

[
发现c906_little目录下的interrupt.c中，设置PLIC_PRIORITY[n] 这个寄存器存在BUG。
按照C906的官方文档《玄铁 C906 R2S1 用户手册》，正确配置PLIC_PRIORITY[n]。
每一个寄存器代表一个硬件中断的优先级。
代码中for循环遍历，但是使用 IRQ_MAX_NR / 4 ，导致配置的寄存器减少了4倍。
- BSP: bsp/cvitek/c906_little
- .config: NA
- action:
]
- [V] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [V] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [V] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [V] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [V] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or …

fix bug in setting PLIC_PRIORITY[n]

---

bsp/cvitek/c906_little/Kconfig
bsp/cvitek/c906_little/board/cache.c
bsp/cvitek/c906_little/board/cache.h
bsp/cvitek/c906_little/rtconfig.h

[
由于小核默认开启了D-Cache且没有缓存一致性保证，所以在使用共享内存时会出现大小核读取的数据不一致的情况
从官方的[duo-buildroot-sdk](https://github.com/milkv-duo/duo-buildroot-sdk)库中迁移D-Cache相关函数，这样就可以选择关闭D-Cache或在读前写后调用flush_dcache_range函数进行同步
- BSP: bsp/cvitek/c906_little/board
- .config:
- action:
]

[bsp][cvitek] add dcache opration functions for cache coherence

---

components/lwp/Kconfig

Fixed #9878 
LWP_DEBUG is debugging related, should be disabled by default.
[
- BSP:
- .config:
- action:
]

lwp: Kconfig: LWP_DEBUG default as n

---

bsp/cvitek/README.md
bsp/cvitek/c906_little/applications/main.c
bsp/cvitek/cv18xx_aarch64/README.md
bsp/cvitek/cv18xx_aarch64/applications/main.c
bsp/cvitek/cv18xx_risc-v/applications/main.c

Fixed #9909 
Duo's CPU combination is more complicated:
| BSP           | B/L core| ISA             | UART  |
| ------------- | ------- |---------------- |-------|
| cv18xx_risc-v | Big     | RISC-V C906     | UART0 |
| c906-little   | Littel  | RISC-V C906     | UART1 |
| cv18xx_aarch64| Big     | ARM Cortex A53  | UART0 |
Printing ISA and big and small core information
during the boot process helps developers/testers
determine the CPU and serial port corresponding to the current console.
In addition, the RTT logo printing has already
distinguished whether it is smart, so the bsp
printing no longer distinguishes.
Updated README to sync with this change.
[
- BSP:
- .config:
- action:
] …

bsp/cvitek: print arch info. during boot-up

---

bsp/cvitek/cv18xx_aarch64/README.md
bsp/cvitek/cv18xx_aarch64/rtconfig.py

Fixed #9925 
For bsp/cvitek, duo256m, the operation process is
slightly different when building images for riscv
and arm64.
To improve the user experience, unify the building process and steps of the two as follows:
- Enter c906_little and execute `scons`
- Enter cv18xx_riscv/cv18xx_aarch64 and execute `scons`
That's all. Finally, we can get `fip.bin` and
`boot.sd` under `bsp/cvitek/output/milkv-duo256m`.
Update the README.md accordingly.
[
- BSP:
- .config:
- action:
]

bsp: cvitek: optimze build operations for aarch64

---

bsp/cvitek/c906_little/board/cache.c

[
Fixed #9920 
参数类型是void* 与预设的uintptr_t不匹配
将void* 显示转换为uintptr_t类型
- BSP: cvitek/c906_little
- .config:
- action:
]

[bsp][cvitek] fix c906_little build warning in cache.c

---

components/drivers/serial/serial_tty.c

[
fix when open samrt but using msh after run elf file the msh will down
- BSP:
- .config:
- action:
]

[serial] Fix the issue of msh crashing after running the elf file in smart + msh mode.

---

components/net/netdev/src/netdev.c

… command
[
- BSP:
- .config:
- action:
]

[components][netdev] add statistics and more inupt parameters to ping command

---

tools/attachconfig.py
tools/building.py
tools/options.py

[
尝试将ci.attachconfig.yml 和scons结合使用
按照issues #9941 的要求实现功能
目前已实现:
scons --attach=? 打印出yml中的所有配置
scons --attach=component.cherryusb_cdc 该命令把yml中的component.cherryusb_cdc配置放到.config的最后中，并且执行一下menuconfig
scons --attach=default 恢复备份文件,恢复.config rtconfig为原样。
- BSP:
- .config:
- action:
]

[tools] ci.attachconfig.yml is used in combination with scons

---

.github/workflows/bsp_buildings.yml
bsp/cvitek/c906_little/rtconfig.py

Reverts RT-Thread/rt-thread#9901
#9901 会影响原先的开发者编译流程，导致 fip.bin 无法生成。
所以请求 revert。相关的 ci 工作我会另外安排处理。

Revert "[action] add cvitek/c906_little ci"

---

components/drivers/include/drivers/blk.h

[
https://github.com/RT-Thread/rt-thread/issues/9424
- BSP:
- .config:
- action:
]

[doxygen] add doxygen comment for blk.h

---

bsp/nrf5x/nrf52840/.ci/attachconfig/ci.attachconfig.yml
bsp/nrf5x/nrf52840/board/SConscript
bsp/nrf5x/nrf52840/board/port/SConscript
bsp/nrf5x/nrf52840/board/port/cherryusb/cherryusb.c
bsp/nrf5x/nrf52840/board/port/cherryusb/usb_config.h
bsp/nrf5x/nrf52840/board/sdk_config.h
components/drivers/usb/cherryusb/Kconfig
components/drivers/usb/cherryusb/SConscript
components/drivers/usb/cherryusb/port/nrf5x/README.md
components/drivers/usb/cherryusb/port/nrf5x/usb_dc_nrf5x.c

[
添加nrf52840的cherryusb适配
将赵工@Ghost-Girls 提供的已移植好的cherryusb文件适配到RT-Thread
- BSP: bsp/nrf5x/nrf52840
- .config:CONFIG_RT_USING_MESSAGEQUEUE
- action:
]

[bsp][nrf5x]added the cherryusb adapter for nrf52840

---

tools/keil.py

[
scons --target=mdk5 这个命令可以类似于`scons` 命令一样，生成工程之后，编译一下。
- BSP:
- .config:
- action:
]

[tools/mdk5] 如果本地设置了UV4.exe 命令，则进行MDK编译

---

components/drivers/spi/Kconfig
components/drivers/spi/SConscript
components/drivers/spi/dev_soft_spi.c
components/drivers/spi/dev_spi_bit_ops.c
components/drivers/spi/dev_spi_core.c

[
已经在vision borard中验证
- BSP:
- .config:
- action:
]

[components][drivers]:fix spi bug and add software spi

---

components/drivers/clk/clk.c
components/drivers/include/drivers/clk.h
documentation/Doxyfile

[
Accroding to #9947 and #9424, adding doxygen comment for function in .c files and data structure, macro in .h file is a solution.For this pr, I encountered problem following situations.
- rt_clk_unprepare function return value type is different from rt_clk_ops so I change type of rt_clk_unprepare and its dependencies.
- clk_get function may be similar as rt_clk_unprepare but I'm not sure so not modify.
- clk_release implements may be incomplete, so I just marked in comment.
- BSP:
- .config:
- action:
]

[doxygen] add doxygen comment for clk.c and clk.h

---

bsp/cvitek/c906_little/board/board.c
bsp/cvitek/c906_little/board/tick.h
libcpu/risc-v/common/trap_common.c
libcpu/risc-v/rv64/trap.c

Fixed: #8977 
本 PR  继续 #9865 的工作。
因为告警涉及三个模块，所以本 PR 包括了三个 commit，具体每个 patch 的改动请看每个 commit 的 message。
- libcpu: riscv: rv64: fixed warnings
- libcpu: riscv: common: fixed build warnings
- bsp: cvitek: c906_littel: fixed build warnings for board.c
[
- BSP:
- .config:
- action:
]

bsp: cvitek: c906_little: fix building warnings

---

.github/workflows/action_tools.yml
components/drivers/usb/cherryusb/Kconfig

[
添加menuconfig 的ci 严格检查，
https://github.com/RT-Thread/rt-thread/actions/runs/13070949354/attempts/1
https://github.com/RT-Thread/rt-thread/issues/9957
cherryusb中RT_USING_LWIP212为if中的配置，无法使用select选中
暂时删除RT_USING_LWIP212，会报warning，后续可以在yml中体现。
- BSP:
- .config:
- action:
]

[action] add ci menuconfig check

---

.github/workflows/bsp_buildings.yml
tools/requirements.txt

[
ci报错，缺yaml
安装依赖
- BSP:
- .config:
- action:
]

ci: fix dep miss

---

components/lwp/lwp_syscall.c

[
修正    https://github.com/RT-Thread/rt-thread/issues/9896  的other_tc/fork/3-1
```
msh />3-1
msh />r -1,3,3
r -1,3,3
[00:00:04]
{Test PASSED}
```
- BSP:
- .config:
- action:
]

[lwp]修正kill(pid < -1)时的返回值错误

---

components/drivers/ofw/fdt.c

[
The `rt_fdt_scan_chosen_stdout` will init fdt_earlycon data without `msg` only, the `msg_idx` should not clean, too. Because we check if have old messages by `msg_idx`
]

[DM/FDT] Fixup earlycon loss old messages.

---

components/drivers/spi/dev_spi_core.c

发现 device->bus->owner == RT_NULL || device->bus->owner == device 会导致设置两次SPI配置
[
- BSP:
- .config:
- action:
]

[drivers/spi]修复spi configure会执行两次的问题

---

bsp/mm32f526x/drivers/drv_adc.c

[
1.修复mm32官方的hal库adc校准后没有清除标志位，造成adc转换功能异常的问题；
]

[bsp][mm32f526x] 1.fix adc device;

---

components/lwp/lwp_signal.c

[
fix https://github.com/RT-Thread/rt-thread/issues/9896   :signal_tc/killpg/6-1...FAILED
- BSP:
- .config:
- action:
]

[lwp]检查killpg的signo参数的有效性

---

components/lwp/lwp_syscall.c

[
add comments for lwp system calls.
add comments for lwp system calls.
- BSP:
- .config:
- action:
]

[lwp]add comments for lwp system calls.

---

components/finsh/finsh.h

Changes only related to documentation.
Regular macro definitions according to [1].
Link: https://rt-thread.github.io/rt-thread/page_howto_macro.html [1]
[
整理 finsh API 文档中的 marco
- BSP:
- .config:
- action:
]

doxygen: finsh: Normalize macro definitions

---

bsp/nxp/mcx/mcxa/frdm-mcxa156/applications/main.c
bsp/nxp/mcx/mcxa/frdm-mcxa156/board/MCUX_Config/board/pin_mux.c

[
修复FRDM-MCXA156 GPIO驱动
Fix GPIO driver for FRDM-MCXA156
开启GPIO及PORT时钟，释放对应模块复位
Enable clocks for GPIO and PORT, release reset signals for these modules.
- BSP:
- bsp/nxp/mcx/mcxa/frdm-mcxa156
- .config:
- N/A
- action:
]

bsp: nxp/mcx/mcxa/frdm-mcxa156: Enable GPIO/PORT support

---

components/lwp/Kconfig
components/utilities/utest/utest.h
tools/mkdist.py

[
The issue #8592  mentioned the need to promote the refactoring and improvement of the `scons --dist` packaging command.
1. By reading in the. config file under bsp, copy the contents of components in a targeted manner to reduce the size of the package
2. Further remove some non essential folders such as `__pycache__`
3. Generate information about this packaging at the same time as executing the command, `dist_deadme.md`
- BSP: qemu-virt64-riscv
- .config: default config, and I also modify some config to test.
I cannot be sure if this solution is stable, in fact, due to the existence of some directories that are not included in the processing method I provided, a necessary directory list is also maintained.
If we could use `compile_commands.json` to perform the step of selecting a …

[feature][v5.1.1][tools] Refactoring and improving the `scons --dist` packaging command

---

components/libc/posix/libdl/dlmodule.c

[Problem Description]
When assigning name to rt_object, strncpy() uses size equal to RT_NAME_MAX, which causes missing null-terminator and overflows into adjacent 'type' field. This corruption leads to unexpected system behavior.
[Problem Analysis]
The rt_object structure defines:
| char name[RT_NAME_MAX] | -> buffer
| rt_uint8_t type        | -> adjacent field
Original code calculates size as:
size = end - first + 1;
if (size > RT_NAME_MAX) size = RT_NAME_MAX;
When size equals RT_NAME_MAX, strncpy() will copy exactly RT_NAME_MAX bytes without adding terminating '\0', causing two issues:
1. name buffer is not null-terminated
2. The implicit null-byte writes beyond name[] into type field
[Solution]
Change boundary check from:
if (size > RT_NAME_MAX) size = RT_NAME_MAX;
to:
if (size >= …

components: libc: fix array overflow in rt_object name assignment

---

documentation/1.introduction/introduction.md

Adjust the paragraph format and correct some inaccurate statements.
[
See commit comment please.
- BSP:
- .config:
- action:
]

doxygen: Improve the text description of the introduction section

---

tools/cmake.py

[
cmake生成脚本会漏掉Sconscript里添加的flags
比如f103的rtduino，漏掉了c++的Sconscript里面的关闭异常
类似pr https://github.com/RT-Thread/rt-thread/pull/8957
btw，添加了Change Logs
从env拿这些flags
- BSP:
f103的rtduino
- .config:
- action:
https://github.com/RT-Thread/rt-thread/actions/runs/13469156866/job/37640397344?pr=9998
]

[tools][cmake] fix missing some flags added in Sconscript

---

bsp/hc32/libraries/hc32_drivers/drv_eth.c
bsp/hc32/libraries/hc32_drivers/drv_spi.c

1.在spi驱动中有在中断中打印调试信息的问题，增加ISR log判断进行
2.spi+DMA 写外部flash，由于spi速度很快，不进行delay就可以；同时，仿照Linux的驱动框架进行优化，数据小不使用DMA
[
- BSP:
- .config:
- action:
]

fix - 1 优化中断中打印日志问题；2 优化SPI写外部FLASH慢的问题

---

components/Kconfig
components/dfs/dfs_v2/include/dfs_file.h
components/dfs/dfs_v2/src/dfs_file_mmap.c
components/dfs/dfs_v2/src/dfs_pcache.c
components/lwp/lwp_elf.c
components/lwp/lwp_user_mm.c
components/mm/Kconfig
components/mm/ioremap.c
components/mm/mm_anon.c
components/mm/mm_aspace.c
components/mm/mm_fault.c
components/mm/mm_object.c
components/mm/mm_page.c
components/mm/mm_page.h
libcpu/aarch64/common/mmu.c
src/Kconfig

[
- added affinity page allocator
- improve debugging experience
- BSP:
- .config:
- action:
]

feat: mm: add affinity page allocator and debugging improvements

---

libcpu/risc-v/common64/mmu.h

[
libcpu\risc-v\common64\mmu.h中宏参数有误：
```
#define GET_PPN(pte)                                                           \
(__PARTBIT(pte, PTE_PPN_SHIFT, PHYSICAL_ADDRESS_WIDTH_BITS - PTE_PPN_SHIFT))
```
其中第三个参数为PPN的bit位数，即44位，而PHYSICAL_ADDRESS_WIDTH_BITS为物理地址总位数即56，PTE_PPN_SHIFT为10（对应PTE的属性位数），56-10=46，显然不是44。
物理地址的组成为44bit PPN + 12bit page offset，因此这里正确的计算方式应该是，
PPN位数=物理地址总位数( PHYSICAL_ADDRESS_WIDTH_BITS(=56) ) - page offset位数( PAGE_OFFSET_BIT(=12) )= 44 bit。
将PTE_PPN_SHIFT修改为PAGE_OFFSET_BIT.
- BSP:
- .config:
- action:
]

[bugfix][risc-v]fix the PPN length error in GET_PPN(pte).

---

bsp/nxp/mcx/mcxa/frdm-mcxa153/board/Kconfig
bsp/nxp/mcx/mcxa/frdm-mcxa156/board/Kconfig

[
kconfig错误
- BSP:
- .config:
- action:
]

[bsp][nxp][pwm]:fix nxp pwm kconfig

---

libcpu/risc-v/common64/mmu.c

[
add comments for rv64 sv39 mmu APIs .
add comments for rv64 sv39 mmu APIs.
- BSP:
- .config:
- action:
]

[libcpu][risc-v]add comments for rv64 sv39 mmu APIs.

---

components/dfs/dfs_v2/filesystems/cromfs/dfs_cromfs.c

[
在64位平台下，数据类型不一致，uint32_t取址后强转为uint64_t *，导致栈中数据被越界覆盖。
修改为相同数据类型
- BSP:
riscv/K230
- .config:
- action:
]

[components][dfs_v2]: Fix cromfs bug

---

documentation/3.kernel/basic/basic.md

整理 "Kerenl Basics" 部分的文档内容，这个 PR 没有对文字内容做实质的改动，只是对文档的格式化做了一些优化和调整，包括：
- 为函数名，变量名加上 "`" 括起来，这样 html 渲染后会采用不同的字体和正文文字部分区分开来。
- 段落之间加上空行，否则 html 渲染的时候会将没有空行分隔的段落合并成一个段落。
- 采用 "@ref" 的方式引用对应章节的页面，譬如 “Thread Scheduling” 这个章节的最后对 page_thread_management 的引用。
- 对于 markdown 中的表格，尽量在 text 中对列进行对齐，美化了阅读的感受。
[
见上描述
- BSP:
- .config:
- action:
]

doxygen: improve doc for kernel basics section

---

libcpu/risc-v/common/context_gcc.S

[
解释一下代码中wch专属的可能不是那么好理解的行为
ref: https://github.com/openwch/ch32v307/blob/4fcd1c8d0f6a0314fe617545f1d60a9341f5bfd3/EVT/EXAM/FreeRTOS/FreeRTOS_Core/FreeRTOS/portable/GCC/RISC-V/portASM.S#L215-L223
- BSP:
- .config:
- action:
]

[libcpu][riscv] add a doc for wch saving the irq stack as  stack-512

---

components/drivers/ofw/ofw.c

[
device node should not probe in stub if device is not available or maybe handle a **bus error**
]

[DM/OFW] check available in stub probe

---

components/drivers/thermal/thermal.c

[
coefficients is double u32 data list:
```c
&cpu_thermal {
coefficients = <(-487) 410040>;
thermal-sensors = <&thermal>;
};
```
If only read a u32 cell:
fixup:
]

[DM/THERMAL] fixup coefficients's offset lost

---

documentation/0.doxygen/example/include/enum.h
documentation/0.doxygen/example/include/groups.h
documentation/0.doxygen/example/include/macro.h
documentation/0.doxygen/example/include/struct.h
documentation/0.doxygen/example/include/typedef.h
documentation/0.doxygen/example/include/union.h
documentation/0.doxygen/example/src/function.c

将 doxygen 的例子分组后显示在不同的 page 上，这样可以在文档中方便地链接到相关类型的 page。譬如 macro 的例子有自己单独的 page，function 的例子有自己单独的 page，这样就和各自的代码例子，譬如 macro.h 或者 function.h 对应起来了。
Module 部分页面未分组前的效果：
Module 部分页面分组后的效果：
分组后可以通过页面链接快速跳转到对应的例子的 html 渲染效果：
macro 的 doxygen 注释渲染后的效果，现在集中在一个独立的页面上，方便在线随时查看。
[
见前面 PR 描述。
- BSP:
- .config:
- action:
]

doxygen: group examples in subpages

---

documentation/0.doxygen/example/include/enum.h
documentation/0.doxygen/example/include/groups.h
documentation/0.doxygen/example/include/macro.h
documentation/0.doxygen/example/include/struct.h
documentation/0.doxygen/example/include/typedef.h
documentation/0.doxygen/example/include/union.h
documentation/0.doxygen/example/src/function.c

- 增加说明如何在注释中对 macro 分组
- 增加说明对于那些 structure 成员变量名过长的情况采用新的方式增加注释。
- 对原来采用 html 文件名方式引用的地方采用 group 名字，方便以后移植。
[
见 PR 说明。
- BSP:
- .config:
- action:
]

doxygen: improve howto

---

bsp/renesas/ra8d1-vision-board/board/Kconfig
bsp/renesas/ra8d1-vision-board/board/SConscript
bsp/renesas/ra8d1-vision-board/board/ports/SConscript
bsp/renesas/ra8d1-vision-board/board/ports/mnt.c

[
- BSP:
- .config:
- action:
]

[bsp/renesas/vision_board] Fix the sdio mount

---

components/dfs/dfs_v1/filesystems/elmfat/dfs_elm.c
components/dfs/dfs_v2/filesystems/elmfat/dfs_elm.c
components/libc/posix/pthreads/pthread.c

[
修复pthread中的悬垂指针的问题；
修复dfs_elm中mkfs未挂载的分区时，访问悬垂指针的问题
pthread中在_pthread_cleanup中将pthread_data设置为NULL；
dfs_elm_mkfs中先umount临时分区，再释放临时的FATFS变量
- BSP:bsp/stm32/stm32g070-st-nucleo
- .config:
https://github.com/RT-Thread/rt-thread/actions/workflows/manual_dist.yml -->
- action:
]

fix dangling pointer in component pthread and dfs_elm

---

components/drivers/audio/dev_audio.c
components/drivers/include/drivers/dev_audio.h

[
Fixed #10085 
- BSP:
- .config:
- action:
]

[doxygen][audio] Fix group names by adding group_ prefix

---

libcpu/risc-v/common64/mmu.c

[
上次提交的commit 7f05592遗漏了rt_hw_mem_setup_early函数的注释。
补充注释。
- BSP:
- .config:
- action:
]

[libcpu][risc-v]add comments for rt_hw_mem_setup_early.

---

documentation/3.kernel/basic/basic.md
src/object.c

将 markdown 中对函数的参数的介绍移到源码注释中，因为这部分内容完全是重复的，我们只要保留并维护代码中的注释即可，markdown 中涉及 API 的详细解释可以直接引用代码中的注释。
尽量不在 markdown 文档中直接复制结构体的定义，因为这部分内容可能随着代码的升级而发生改动，所以 markdown 中涉及结构体定义时尽量注明这只是代码片段，具体的定义还是直接引用源码以及源码的注释。
markdown 中引用结构体和函数非常方便，只要用 “`" 将结构体名字或者函数名字括起来，生成的 html 就是指向其定义的链接。
按照这个原则，本补丁只是修改了 kernel object model 部分的文档和代码注释。其他模块以后另外提补丁逐个修改。
[
见 PR 描述。
- BSP:
- .config:
- action:
]

doxygen: update doc for kenrel object model

---

bsp/stm32/libraries/HAL_Drivers/drivers/SConscript
bsp/stm32/libraries/STM32H7xx_HAL/SConscript
bsp/stm32/libraries/STM32H7xx_HAL/STM32H7xx_HAL_Driver/Inc/Legacy/stm32h7xx_hal_eth_legacy.h
bsp/stm32/stm32h750-artpi/.ci/attachconfig/ci.attachconfig.yml
bsp/stm32/stm32h750-artpi/board/CubeMX_Config/Core/Inc/stm32h7xx_hal_conf.h
bsp/stm32/stm32h750-artpi/board/Kconfig
bsp/stm32/stm32h750-artpi/board/SConscript
bsp/stm32/stm32h750-artpi/board/port/drv_eth.c
bsp/stm32/stm32h750-artpi/board/port/drv_eth.h
bsp/stm32/stm32h750-artpi/board/port/drv_mpu.c

[
#9165 
使用旧的api
- BSP:
- .config:
- action:
]

[bsp][stm32][artpi]:fix h750 eth

---

.gitignore
bsp/simulator/template_vs2012.vcxproj
components/finsh/finsh.h
include/rttypes.h
libcpu/sim/win32/cpu_port.c
libcpu/sim/win32/startup_msvc.c
src/SConscript
src/scheduler_up.c

[
随着master的升级（主要是finsh中MSH_CMD_EXPORT宏变化影响较大），但是bsp/simulator没有得到同步维护，bsp/simulator无法使用visual studio 2012/2019/2022等进行正常编译。
本次pr主要是修复该问题，使得bsp/simulator可以在vs中进行编译，并运行。
1、finsh.h随着master做了较大更新，但是vs不支持“变维度数组”，因此对以下宏进行了修复
```
#ifdef _MSC_VER
#define CMD_OPTIONS_STATEMENT(command) static struct msh_cmd_opt command##_msh_options[16];
#else
#define CMD_OPTIONS_STATEMENT(command) static struct msh_cmd_opt command##_msh_options[];
#endif
#ifdef _MSC_VER
#define CMD_OPTIONS_NODE_START(command) static struct msh_cmd_opt command##_msh_options[16] = {
#else
#define CMD_OPTIONS_NODE_START(command) static struct msh_cmd_opt command##_msh_options[] = {
#endif
```
2、finsh中MSH_CMD_EXPORT宏机进行了较大变化，导致vs中老版本的c语言无法正确对MSH_CMD_EXPORT宏进行展开，因此需要将`template_vs2012.vcxproj`中添加默认是使用c11版本
``` …
```

解决bps/simulator无法在vs2019环境下编译

---

libcpu/risc-v/common64/mmu.c

[
_unmap_area函数存在几处潜在风险或问题：
1._unmap_area 函数的size 参数未被使用。
经过分析代码，该函数每次解除映射的范围实际由页表层级自动决定（如 1GB/2MB/4KB），而非依赖 size 参数。该参数未被使用，容易造成对该函数使用方式的误解，建议删除该参数。
2._unmap_area函数中对无效页表项的情况未做处理，可能导致返回的unmapped值不正确。
1. 删除无用的size参数；
2. 针对无效页表项的情况，返回unmapped值为0，这与rt_hw_mmu_unmap中对_unmap_area返回值的异常检查保持一致（rt_hw_mmu_unmap中判定_unmap_area返回0为异常）。
- BSP:
- .config:
- action:
]

[libcpu][risc-v]处理mmu.c中_unmap_area函数的几处潜在风险或问题

---

bsp/stm32/stm32h750-artpi/.ci/attachconfig/ci.attachconfig.yml
bsp/stm32/stm32h750-artpi/applications/main.c
libcpu/arm/cortex-m7/cpu_cache.c

[
artpi 运行nano
- BSP:
- .config:
- action:
]

[bsp][stm32][artpi]:fix artpi nano

---

components/drivers/core/platform_ofw.c

[
If a node request a new node or it's parent node. the  request's node will probe a double time:
```c
/ {
node0 {
request-node1;
};
node1 {
};
node2 {
node3 {
request-node2;
};
};
};
```
So we check the device object of node in ofw probe entry and ofw probe child exit.
]

[DM/Platform] Fixup the node will probe more than once

---

components/finsh/cmd.c

[
使用list mutex时，输出错误。互斥量当前可能没有线程持有，m-owner值就是RT_NULL，会造成打印错误。
- BSP:
- .config:
- action:
]

解决 list_mutex 互斥量没有线程持有时打印错误

---

.github/workflows/bsp_buildings.yml
bsp/nrf5x/nrf52833/rtconfig.py
bsp/nrf5x/nrf52840/rtconfig.py
bsp/stm32/stm32f103-blue-pill/rtconfig.py
bsp/stm32/stm32f407-rt-spark/rtconfig.py
bsp/stm32/stm32h750-artpi/rtconfig.py
bsp/stm32/stm32l496-st-nucleo/rtconfig.py
bsp/stm32/stm32wb55-st-nucleo/rtconfig.py
bsp/yichip/yc3121-pos/Libraries/core/type.h
tools/ci/bsp_buildings.py

[
上传每次编译的结果
https://github.com/RT-Thread/rt-thread/actions/runs/14005206336
更新一下toolchain
- BSP:
- .config:
- action:
]

[action/ci] 把每次编译结果上传到github

---

bsp/cvitek/drivers/drv_spi.c

Build error: 'struct _device_spi' has no member named 'base_addr'
Analyze: the name should be dws.regs
Solution: change base_addr to dws.regs
[
Fixed #10132 
开启SPI功能后编译错误: 'struct _device_spi' has no member named 'base_addr'
修改变量名，将base_addr重命名为dws.reg
- BSP: cvitek
- .config:
- action:
]

[bsp][cvitek] fix spi driver build error

---

.github/workflows/bsp_buildings.yml

[
再加个整合到一个zip中的步骤,把所有产物打包成一个zip，并添加hash值辨别。
- BSP:
- .config:
- action:
https://github.com/RT-Thread/rt-thread/actions/runs/14015896473
]

[action/cd] 整合所有output到一个包中

---

bsp/gd32/arm/gd32450z-eval/.ci/attachconfig/ci.attachconfig.yml
bsp/gd32/arm/gd32450z-eval/board/Kconfig
bsp/gd32/arm/libraries/gd32_drivers/SConscript
bsp/gd32/arm/libraries/gd32_drivers/drv_can.c
bsp/gd32/arm/libraries/gd32_drivers/drv_can.h

[
- BSP:
- bsp/gd32/arm/gd32f450z-eval
- .config:
CONFIG_RT_USING_CAN=y
CONFIG_BSP_USING_CAN=y
CONFIG_BSP_USING_CAN0=y
CONFIG_BSP_CAN0_TX_PB9=y
CONFIG_BSP_CAN0_RX_PB8=y
CONFIG_BSP_USING_CAN1=y
CONFIG_BSP_CAN1_TX_PB6=y
CONFIG_BSP_CAN1_RX_PB5=y
- action:
]

GD32: add CAN driver for GD32F4xx

---

bsp/phytium/board/board.c
libcpu/aarch64/common/gicv3.c

[
https://github.com/RT-Thread/rt-thread/pull/8221/ 去掉了非设备树初始化CPU的方法，设备树初始化CPU的框架下由mpdir_table来存放cpu信息，所以非设备树版gicv3需要使用该变量，同时arm64芯片cpu初始化均应使用设备树(调用rt_hw_common_setup)
- BSP:
- .config:
- action:
]

[libcpu][aarch64]fix gicv3 mpidr table

---

.github/ALL_BSP_COMPILE.json
.github/workflows/bsp_buildings.yml

[
优化提交pr时编译bsp的用时，根据pr修改了的文件来编译对应的bsp，这样可以省去很多不必要的编译过程
优化bsp添加方式，将需要的bsp列表放到ALL_BSP_COMPILE.json中，这样可以让开发者更方便的添加bsp
根据修改的文件中的文件路径进行判断，如果判断到stm32，则搜索json中SUB_RTT_BSP下是否有该关键词，有则编译这个系列
如果修改的是bsp目录以外的文件，则按照ALL_BSP_COMPILE.json填写了的所有bsp进行编译
CI会在开始时读取ALL_BSP_COMPILE.json以便生成matrix
- BSP:
- .config:
- action:
]

[action/ci] 将需要编译的bsp分离，同时根据修改的文件编译对应的bsp

---

bsp/allwinner/d1/board/board.c
libcpu/aarch64/common/include/mmu.h
libcpu/arm/cortex-a/mmu.h
libcpu/risc-v/common64/mmu.h

这个 PR 包含了两个 commit，一个是对 libcpu 的清理，一个是对 bsp 的清理。
`rt_hw_mmu_kernel_map_init` 这个函数没有定义，可是 libcpu 的 `mmu.h` 头文件中却声明了这个函数。
同时清理了 bsp/allwinner/d1 中对 `rt_hw_mmu_kernel_map_init` 这个函数的调用。目前怀疑这个 bsp 已经年久失修，原本就编译不过。
[
- BSP:
- .config:
- action:
]

libcpu: cleanup undefined rt_hw_mmu_kernel_map_init

---

libcpu/risc-v/common64/mmu.c

`libcpu/risc-v/common64/mmu.c` 会使用外部符号 "__bss_end"（这个符号一般定义在链接脚本中），但问题是目前 libcpu 的源文件依赖于 bsp 的 ”board.h“ 中对这个符号的 extern 声明。
这么做本身不会报错，但是不是一个好的编程习惯，对内核的扩展是不利的。这会导致内核的 core（libpcu）对 bsp 的头文件产生依赖。而且这样对 bsp 的 "board.h" 会产生特别的要求，譬如强制要求在 "board.h" 中对这些 "__bss_end" 符号进行 extern 声明， 这个应该避免而且是非必须的。
解决方案：如果是 libcpu 本地使用到了这个 extern 的符号，直接在本地声明就好了。
但这个补丁的改动目前只是在 libcpu 内部显式地 extern 声明 ”__bss_end“。没有删除诸如 ”#include <board.h>" 的操作。因为涉及修改太大，需要涉及的 bsp 自己都清理后才好统一做 libcpu 的清理。所以目前先在 libcpu 中自己加上 extern 声明，确保新的 bsp 中不会发生即使不使用也需要强制声明 “__bss_end" 这些符号的情况。
[
- BSP:
- .config:
- action:
]

libcpu: riscv: declare external symbols inside

---

tools/cmake.py

…ciated issue #10113
[
修复在linux下面使用scons生成cmake报错的问题
修改cmake.py中的CXXFLAGS
- BSP:bsp/at32/at32a403a-start
- .config:不需要修改
- action:
]

Fixed an error by running scons --tartget=cmake under LINUX, #10113

---

components/drivers/ofw/fdt.c

[
Fix garble caused by empty implementation of earlycon series function in driver.If driver doesn't offer earlycon_id or rt_f dt_earlycon_id.setup function but open option, the checking of best_earlycon_id will failed.
Fixed #10154 
- BSP:
- .config:
- action:
]

[DM/FDT] Fix garble when booting

---

bsp/gd32/arm/gd32103c-eval/SConstruct
bsp/gd32/arm/gd32105c-eval/SConstruct
bsp/gd32/arm/gd32105r-start/SConstruct
bsp/gd32/arm/gd32107c-eval/SConstruct
bsp/gd32/arm/gd32205r-start/SConstruct
bsp/gd32/arm/gd32207i-eval/SConstruct
bsp/gd32/arm/gd32303c-start/SConstruct
bsp/gd32/arm/gd32303e-eval/SConstruct
bsp/gd32/arm/gd32305r-start/SConstruct
bsp/gd32/arm/gd32307e-start/SConstruct
bsp/gd32/arm/gd32407v-lckfb/SConstruct
bsp/gd32/arm/gd32407v-start/SConstruct
bsp/gd32/arm/gd32450z-eval/SConstruct
bsp/gd32/arm/gd32470z-lckfb/SConstruct
bsp/gd32/arm/gd32e503v-eval/SConstruct
bsp/gd32/risc-v/gd32vf103r-start/SConstruct
bsp/gd32/risc-v/gd32vf103v-eval/SConstruct

[
修复GD32生成Cmake工程报 
```
AttributeError: 'CLVar' object has no attribute 'replace':
File "E:\_rtthread\rt-thread\bsp\gd32\arm\gd32e503v-eval\SConstruct", line 60:
DoBuilding(TARGET, objs)
File "E:\_rtthread\rt-thread\tools\building.py", line 874:
EndBuilding(target, program)
File "E:\_rtthread\rt-thread\tools\building.py", line 983:
GenTargetProject(program)
File "E:\_rtthread\rt-thread\tools\building.py", line 947:
CMakeProject(Env, Projects, GetOption('project-name'))
File "E:\_rtthread\rt-thread\tools\cmake.py", line 342:
GenerateCFiles(env, project, project_name)
File "E:\_rtthread\rt-thread\tools\cmake.py", line 65:
CFLAGS = env['CFLAGS'].replace('\\', "/").replace('\"', "\\\"")
```
的错误
将所有GD32 bsp 下 `SConstruct` 文件中的
`CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,` 替换成 `CC = …

[bsp] 修复 #10182 GD32生成Cmake工程错误的问题

---

bsp/Infineon/libraries/HAL_Drivers/drv_spi.c
bsp/Infineon/xmc7100d-f144k4160aa/.ci/attachconfig/ci.attachconfig.yml
bsp/Infineon/xmc7100d-f144k4160aa/board/Kconfig
bsp/Infineon/xmc7100d-f144k4160aa/board/SConscript
bsp/Infineon/xmc7100d-f144k4160aa/board/ports/SConscript
bsp/Infineon/xmc7100d-f144k4160aa/board/ports/drv_filesystem.c
bsp/Infineon/xmc7100d-f144k4160aa/board/ports/spi_flash_init.c

[
添加xmc7100d-f144k4160aa的外设适配
使能正常读取tf卡和板载IMU
- BSP: bsp/Infineon/xmc7100d-f144k4160aa
- .config:
- action:
]

[bsp][Infineon] Update the peripherals of XMC7100D

---

.github/ALL_BSP_COMPILE.json
.github/workflows/bsp_buildings.yml
bsp/qemu-vexpress-a9/.ci/attachconfig/ci.attachconfig.yml
tools/ci/bsp_buildings.py

[
添加qemu-vexpress-a9的编译前的执行脚本，和编译后的执行脚本，
添加smart的配置，添加yml中的环境变量的设置，目前ci可以支持多种toolchain的编译同一个bsp
添加yml中的配置
- BSP:
- .config:
- action:
]

[action/ci] add qemu-pre-build-and-post-build for RT_SMART  build

---

libcpu/aarch64/SConscript

该问题由5b3320624da5149fc21c2d3e1f321d855e3d0dfe引入，导致工具链编译时加上了 -std=gnu99,其他架构是否出问题暂时未知
[
- BSP:
- .config:
- action:
]

[FIX AARCH64] Fix Aarch64 architecture runtime issues

---

components/lwp/lwp_elf.c

[
add annotation for lwp elf.
add annotation for lwp elf.
- BSP:
- .config:
- action:
]

[component/lwp]add annotation for lwp elf.

---

.github/workflows/bsp_buildings.yml

[
发现当修改的bsp超过2个时会导致命令被分割从而出现错误
将原本的传递参数的方式修改为[]的形式
- BSP:
- .config:
- action:
]

[action/ci] 修复bsp_buildings的传递参数的问题

---

.github/workflows/auto-assign-reviewers.yml
MAINTAINERS

Fixed #9903
Ps:该CI自动化脚本可自动识别PR修改的文件列表，并根据仓库根目录下的MAINTAINERS文件，映射审核团所维护的path，从而分配审查
下面是该脚本的具体功能说明：
* 审核方式由github bot自动评论@提及，并且保证仅保留一份最新的机器人评论；
* 支持动态检测PR内所有被修改、删除、增加的文件；支持被修改文件的递归目录检测；并根据每次最新PR所变更的所有文件内容的追踪，生成实时的审核内容及审查人任命；
* 支持查看最新PR的审查情况，可根据CI机器人评论的**Current Review Status**部分查看；
* 支持自动捕获被任命的评论信息（审核者需要评论 LGTM/lgtm 来告知审查完毕），CI会同步bot机器人的评论：**Current Review Status**更新审查状况；
* 支持手动点击**🔄 刷新状态**来重新运行CI，以此来获取最新的审查情况；
* 支持一键展开被修改的文件详情，方便定位审查内容。
此外，为避免因PR多次修改而重复@审核者，该脚本还引入缓存机制，仅在第一次@时评论提及，后续仅提示GitHub id
下面是一个演示效果，也可以通过下方链接查看实际效果：
* https://github.com/Nedki-L/rt-thread/pull/15#issuecomment-2608729838
**Path:** `bsp/stm32`  
**Reviewers:** @kurisaW   
<details>
<summary><b>Changed Files</b> (Click to expand)</summary>
- bsp/stm32/docs/How to create a RT-Studio project.md
</details>
**Path:** `src` …

feat: CI script assigns PR reviews based on the list of maintainers

---

bsp/simulator/rtconfig.py

I find some issues like the following output mentioned when I use bsp/simulator's Visual Studio project generator:
```
(RTThreadPython) D:\Projects\MobilityOS\rt-thread\bsp\simulator>scons --target=vs2012 -s
Successfully installed VC 14.3, path:C:\Program Files\Microsoft Visual Studio\2022\Community\VC
Successfully installed VC 14.3, path:C:\Program Files\Microsoft Visual Studio\2022\Community\VC
AttributeError: module 'rtconfig' has no attribute 'DEVICE':
File "D:\Projects\MobilityOS\rt-thread\bsp\simulator\SConstruct", line 81:
objs = PrepareBuilding(env, RTT_ROOT, has_libcpu=False)
File "D:\Projects\MobilityOS\rt-thread\tools\building.py", line 407:
objs.extend(SConscript(Rtt_Root + '/components/SConscript',
File "D:\Projects\MobilityOS\RTThreadPython\Lib\site-packages\SCons\Script\SCon …
```

bsp/simulator: fix issues for Visual Studio project generator

---

bsp/Infineon/libraries/HAL_Drivers/drv_gpio.c

[
修改ifx_pin_irq_enable中断号不正确问题
将IRQn_Type irqn = (IRQn_Type)(irqmap->irqno + PORT_GET(irqmap->port));改为IRQn_Type irqn = irqmap->irqno;
- BSP:
- .config:
- action:
]

fix ifx_pin_irq_enable

---

.github/workflows/auto-assign-reviewers.yml
MAINTAINERS

[
修复存在未创建的文件操作，优化路径匹配策略
- BSP:
- .config:
- action:
]

ci: fixed the abnormal operation of ci files

---

.github/workflows/auto-assign-reviewers.yml

[
明确文件创建、优化缓存逻辑和添加错误检查，修复了首次运行时文件未创建的问题
- BSP:
- .config:
- action:
]

ci: fixed missing unique files creation and cache logic

---

MAINTAINERS

每个entry必须以 tag 为关键字按照英文字母表顺序排序。这样以后 entry 多了方便查找。
而且这一般也是使用英文的惯例，按照字母表排序也比较美观。
[
- BSP:
- .config:
- action:
]

MAINTAINERS: sort entries with tag in alphabetical

---

bsp/k230/.config
bsp/k230/board/Kconfig
bsp/k230/drivers/interdrv/hardlock/SConscript
bsp/k230/drivers/interdrv/hardlock/drv_hardlock.c
bsp/k230/drivers/interdrv/hardlock/drv_hardlock.h
bsp/k230/rtconfig.h

为 bsp/k230 增加 hardlock 驱动。
This hardlock is required by some other drivers, such as sysctl power.
This driver can be enable/disabled by configuration.
[
- BSP:
- .config:
- action:
]

bsp: k230: add hardlock driver

---

bsp/bluetrum/libraries/hal_drivers/drv_gpio.c
bsp/bluetrum/libraries/hal_drivers/drv_gpio.h
bsp/bluetrum/libraries/hal_libraries/bmsis/include/ab32vg1.h

[
ab32vg1 支持GPIO中断
- BSP:
- .config:
- action:
]

bsp: ab32vg1 board support gpio interrupt

---

.github/workflows/git_diff_status_show.yml
tools/ci/git_diff_status_show.py

[
实时监控一下PR 的状态，文件大小，方便审核者评估是否commit过大
用一个python脚本显示PR的状态
- BSP:
- .config:
- action:
]

[action/ci] show the PR status for Pull request

---

components/drivers/audio/Kconfig
components/drivers/audio/SConscript
components/drivers/audio/utest/SConscript
components/drivers/audio/utest/tc_audio_common.h
components/drivers/audio/utest/tc_audio_drv_mic.c
components/drivers/audio/utest/tc_audio_drv_player.c
components/drivers/audio/utest/tc_audio_main.c

[
Fixed #10046 
Achieve driver framework by operating memory to simulate audio peripheral drivers. And it could be as a draft standrad for other drivers test framework.
- BSP:
- .config:
- action:
]

[RFC][utest] Add audio driver test framework

---

tools/building.py
tools/mkdist.py

[
由于studio用的env版本不是最新的导致无法正常导入bsp
适配一下mkdist.py和building.py
- BSP:
- .config:
- action:
]

[tools] 修复rttstudio无法导入bsp的问题

---

bsp/stm32/stm32h723-st-nucleo/SConscript
tools/cmake.py

[
scons创建cmake报错
```bash
scons --target=cmake
scons: Reading SConscript files ...
Newlib version: 4.1.0
E:\project\rt-thread\tools\cmake.py:151: SyntaxWarning: invalid escape sequence '\s'
cm_file.write("SET(CMAKE_EXE_LINKER_FLAGS \""+ re.sub(LINKER_FLAGS + '(\s*)', LINKER_FLAGS + ' ${CMAKE_SOURCE_DIR}/', LFLAGS) + LINKER_LIBS + "\")\n\n")
E:\project\rt-thread\tools\cmake.py:155: SyntaxWarning: invalid escape sequence '\w'
pattern = re.compile('-std=[\w+]+')
Update setting files for CMakeLists.txt...
Cannot find the param of the cpp standard in build flag, set to default 17
Done!
```
使用原始字符串（Raw String）避免转义问题
- BSP:
使用stm32h723-st-nucleo测试
- .config:
无需修改
- action:
]

fix scons --target=cmake command failure

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart_v2.c
components/drivers/serial/dev_serial_v2.c

[
- BSP:
- .config:
- action:
]

[components][serial_v2] 写满丢弃策略对dma_ping_buf的处理有误、细节优化

---

bsp/ESP32_C3/README.md
bsp/ESP32_C3/README_ZH.md
bsp/ESP32_C3/docker/Dockerfile

[
添加dockerfile和并提供docker image来提高ESP32C3的易用性，同时修改readme文件添加维护者
- BSP:
- .config:
- action:
]

[bsp] [ESP32C3] Add dockerfile and update README

---

components/drivers/include/drivers/pci.h
components/drivers/pci/SConscript
components/drivers/pci/pci.c
components/drivers/pci/pme.c
components/drivers/pci/probe.c
components/drivers/pci/procfs.c
components/drivers/pci/procfs.h

[
1. Add ROM base info.
2. Save th PM status.
Build [pciutils](https://github.com/pciutils/pciutils) for testing:
```shell
make HOST=rt_thread_smart CROSS_COMPILE=aarch64-linux-musleabi- ZLIB=no
```
The `ZLIB` can set `yes` or ignore if build in [userapp](https://github.com/RT-Thread/userapps)
]

[DM/PCI] Add /proc access in RT-Smart user

---

include/rtthread.h
src/clock.c

[
- BSP:
- .config:
- action:
]

添加 rt_tick_get_delta 函数

---

libcpu/risc-v/common64/mmu.c

…egment is located
[
rv64 smart版本中，在rt_hw_mem_setup_early中会开启MMU大页映射（1GB）,映射地址范围从0-512G，远超出实际板卡的内存地址空间，板卡上运行时，会出现cpu随机猜测执行到某段不存在的物理地址，导致CPU发生NMI异常。
根据实际需要，只映射代码段所在的1个大页。
- BSP:  bsp/qemu-virt64-riscv
- .config:
- action:
]

[libcpu][risc-v] 减少rv64 smart版本中mmu early map时的地址空间大小以防止cpu猜测执行到不存在的地址空间

---

bsp/Infineon/libraries/HAL_Drivers/config/cy8c62/adc_config.h
bsp/Infineon/libraries/HAL_Drivers/config/drv_config.h
bsp/Infineon/libraries/HAL_Drivers/config/xmc7100/adc_config.h
bsp/Infineon/libraries/HAL_Drivers/config/xmc7200/adc_config.h
bsp/Infineon/libraries/HAL_Drivers/drv_adc.c

[
- BSP: bsp/Infineon/psoc6-evaluationkit-062S2
- .config:
- action:
]

[bsp][Infineon]修复psoc6-evaluationkit-062S2调用rt_adc_disable()时报错的问题

---

bsp/k230/drivers/interdrv/pinctl/SConscript
bsp/k230/drivers/interdrv/pinctl/drv_pinctrl.c
bsp/k230/drivers/interdrv/pinctl/drv_pinctrl.h

实现 k230 的 pinctrl 驱动。
[
- BSP:
- .config:
- action:
]

bsp: k230: support pinctrl driver

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_rtc.c
components/drivers/rtc/Kconfig
components/drivers/rtc/dev_alarm.c

- add the alarm using local time for calculation
rtc的alarm驱动不支持带时区（local time)的时间比较闹钟事件触发
在kconfig中加入使用本地时间的alarm的配置，RT_ALARM_USING_LOCAL_TIME，默认不使能，也就是默认还是UTC时区闹钟。
另外rt_alarm_dump命令加入支持timezone显示，这样比较直观些。

components: drivers: rtc: add the alarm using local time for calculation

---

components/utilities/utest/utest.c

utest 原代码中对 case 名字的匹配有问题，因为采用 memcmp 按照 len 的字节匹配，如果输入的 case name 和存在的 case name 存在包含关系，譬如实际 case 名字是 ”gpip_irq“, 输入 `utest_run gpio` 也会匹配成功， 但这不是期望的结果。
修改精确匹配的逻辑，直接采用 strcmp。
同时保留原先通配的逻辑，即 `utest_run gpio*` 可以同时匹配 ”gpio“ 和 ”gpio_irq“。
[
- BSP:
- .config:
- action:
]

componnets: utest: fix case-name matching problem

---

.gitignore
documentation/6.components/device-driver/INDEX.md
documentation/6.components/device-driver/ofw/dtc.md
tools/dtc.py

[
Devicetree Compiler for dts build
]

[TOOLS] Add DTC (Devicetree Compiler) tools

---

bsp/k230/Kconfig
bsp/k230/SConstruct
components/lwp/vdso/user/arch/risc-v/SConstruct

[
当前内核是使用双精度浮点，V指令集扩展方式编译。加入Soft-FPU的选项，以兼容到类似qemu-riscv64的方式。
在Kconfig中加入对Soft-FPU的选项，同时在SConstruct文件中对Soft-FPU情况下，调整编译参数为 `-march=rv64imafdc -mabi=lp64`。
- BSP: k230
- .config:
- action:
]

[BSP][K230] Add soft-fpu option for k230

---

libcpu/aarch64/cortex-a/entry_point.S

[
The boot EL will save in x0, when current EL is EL3, kernel will jump to the EL2 after EL3.
But the x0 value is **3**, The init for EL2 will not work.
To fix it: the EL3 should jump to the EL2 init branch with not check, and when SoC boot in EL2, kernel will jump to the EL2 test branch.
Link: https://club.rt-thread.org/ask/question/ec320a6765389f67.html
]

Fixup the boot EL check

---

tools/building.py
tools/options.py
tools/targets/vsc.py

[
当使用vscode(及扩展)打开RT-Thread目录时，可以生成一定的类workspace配置，只关注感兴趣的bsp，把其他无关bsp自动排除。
在RT-Thread根目录下使用scons生成适合的配置。<注：若类似stm32这样的bsp，需要自行先解决`pkgs --update`的问题>
- BSP: qemu-vexpress-a9，qemu其他bsp，stm32f412-st-nucleo <需确保手工完成`pkgs --update`更新>
- .config:
- action:
]

[vscode] Add VSCode workspace generation for vscode_extension.

---

libcpu/aarch64/link.lds.S

[
LINK rtthread.elf show:
ld: warning: rtthread.elf has a LOAD segment with RWX permission
Add the attribute for sections to fix it.
]

Fixup linker warning

---

MAINTAINERS

[
申请添加为maintainers
- BSP:
- .config:
- action:
]

maintainers:  添加meng-plus为bsp_lpc4088和bsp_gd32e5的维护者

---

components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c

[Descriptions]:
1. Make these functions public to avoid code duplication and allow direct usage by other components.
2. Apply clang-format for consistent code style.
[Root   Cause]:NA
[Side Effects]:NA
[
目前在开发应用代码时，netdev 接口目前需要多次函数调用（netdev_get_by_name, netdev_set_ipaddr等）来完整配置网络设置，这较为低效。因为 netdev_set_if 已经存在但属于静态函数，导致用户需要自己重新实现一个类似于netdev_set_if接口的流程去进行以太网配置。
改进此功能将允许通过单个函数调用直接配置以太网多项属性，从而简化网络配置代码并避免开发者去重复实现。
所以我认为将该函数接口从静态函数变为一个普通函数可能是更合适的，如果有什么理解不到位的地方欢迎大家指正。
Convert netdev_set_if and netdev_set_dns from static function to normal 
- BSP: cvitek
- .config: CONFIG_BSP_USING_ETHERNET
- action:
]

[refact](netdev): Expose netdev_set_dns and netdev_set_if

---

tools/building.py
tools/targets/iar.py

[
https://github.com/RT-Thread/rt-thread/pull/10169 把env.Append(CPPDEFINES=['STM32F091xC'])放到了bsp顶层的Sconscript中，但是keil和iar的宏定义是从组里面读取的，所以没有添加到对应型号的宏定义
#10503 
参考#10456
- BSP:
- .config:
- action:
]

[tools]:修复iar添加宏不完全 

---

examples/utest/testcases/Kconfig
examples/utest/testcases/perf/Kconfig
examples/utest/testcases/perf/README.md
examples/utest/testcases/perf/SConscript
examples/utest/testcases/perf/context_switch_tc.c
examples/utest/testcases/perf/irq_latency_tc.c
examples/utest/testcases/perf/perf_tc.c
examples/utest/testcases/perf/perf_tc.h
examples/utest/testcases/perf/thread_event_tc.c
examples/utest/testcases/perf/thread_mbox_tc.c
examples/utest/testcases/perf/thread_mq_tc.c
examples/utest/testcases/perf/thread_sem_tc.c

[
- BSP:
- .config:
- action:
]

testcase: add system performance testcase

---

components/net/sal/socket/net_sockets.c

发现个内存泄漏的地方，解决特殊情况下出现的内存泄漏问题，将申请的内存直接进行初始化，而不是在其他条件下执行成功才初始化，执行失败不进行初始化直接释放内存，这段内存只有正确初始化之后才会被释放掉，否则不会被释放掉
将申请的内存直接进行初始化，而不是在其他条件下执行成功才初始化，执行失败不进行初始化直接释放内存
- BSP:rt-thread\bsp\hc32\ev_hc32f4a0_lqfp176
- .config:rt-thread默认配置UDP数量为4
- action:开启超过4个的udp连接，此时sal_socket会执行失败，失败原因是UDP数量不够，失败的时候不会执行dfs_vnode_init初始化函数对申请的vnode内存进行初始化，直接就释放该内存，但是释放该内存的依据是ref_count--为0，未进行初始化的时候，ret_count是个随机值，进行自减极大概率不会变成0，导致这块内存实际上并没有被释放掉

fix #4286,fifx memory leak when sal_socket failed

---

examples/utest/testcases/kernel/Kconfig
examples/utest/testcases/kernel/SConscript
examples/utest/testcases/kernel/object_tc.c
src/object.c

[
Fixed: https://github.com/RT-Thread/rt-thread/issues/10517
object->name存在以下两个问题：
* 缓冲区溢出问题：直接使用RT_NAME_MAX作为拷贝长度，可能会引发字符串拷贝边界问题，使用strncpy并不会主动在末尾补'\0'
* 空指针未处理问题：当name参数为NULL时，直接调用rt_strncpy，可能引发内存访问异常
已给出修复方案并提交测试用例，并且测试通过
- BSP:
- .config:
- action:
]

kernel/testcase: fixed buffer overflow vulnerability in object

---

components/finsh/shell.c

When using char rt_hw_console_getchar(void),
some compilers may default to returning 255 instead of the expected -1, causing the condition if(ch < 0) at F: shell.c L:519 to fail and enter an erroneous loop.
Solution: Use the same int type return value as finsh_getchar
[
- BSP:
- .config:
- action:
]

[Fix] <components>:finsh/shell.c  F: char rt_hw_console_getchar(void)

---

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript
bsp/wch/risc-v/Libraries/ch32_drivers/drv_usart_v2.c
bsp/wch/risc-v/Libraries/ch32_drivers/drv_usart_v2.h
bsp/wch/risc-v/ch32v307v-r1/board/Kconfig

[
为WCH RISC系列适配串口V2驱动
目前已经使用测试代码,在ch32v307v-r1测试
``` C
#include <board.h>
#define echo_test_buffer_size (1024)
// 测试环境
// 串口2、3开启dma, 5、6不开启
// 缓冲区大小都为 128 字节
// echo test
// 3tx - 6rx
// 3rx - 6tx
// self test
// 2tx - 2rx
// 5tx - 5rx
static rt_device_t u2serial;
static rt_device_t u3serial;
static rt_device_t u5serial;
static rt_device_t u6serial;
static rt_uint32_t u2rx_length = 0;
static rt_uint32_t u2tx_length = 0;
static rt_uint32_t u3rx_length = 0;
static rt_uint32_t u3tx_length = 0;
static rt_uint32_t u5rx_length = 0;
static rt_uint32_t u5tx_length = 0;
static rt_uint32_t u6rx_length = 0;
static rt_uint32_t u6tx_length = 0;
static void echo_test_u3_thread_entry(void *parameter)
{
char *uart_name = "uart3";
static char …
```

[bsp][wch]:适配WCH RISC-V系列uart_v2驱动

---

components/libc/posix/pthreads/pthread.c

[
新手任务1 函数注释补充，主要对libc/posix/pthread/pthread.c文件添加注释
]

[components/libc] add comments for some pthread functions.

---

components/libc/posix/pthreads/pthread_cond.c

[
修复#10444
原有实现中只是通过`rt_hw_interrupt_disable/enable`进行保护，然而在`rt_timer_control`中会进行`rt_enter/exit_critical`操作，在`rt_exit_critical`时会进行`rt_schedule`发生调度，而这时`rt_timer_start`还未执行，导致超时唤醒丢失
```c
/* suspend thread */
rt_thread_suspend(thread);
/* Only support FIFO */
rt_list_insert_before(&(sem->parent.suspend_thread), &RT_THREAD_LIST_NODE(thread));
/**
rt_ipc_list_suspend(&(sem->parent.suspend_thread),
thread,
sem->parent.parent.flag);
*/
/* has waiting time, start thread timer */
if (time > 0)
{
/* reset the timeout of thread timer and start it */
rt_timer_control(&(thread->thread_timer),
RT_TIMER_CTRL_SET_TIME,
&time);
rt_timer_start(&(thread->thread_timer));
}
```
- BSP:
qemu-vexpress-a9
- .config:
```diff
--- a/bsp/qemu-vexpress-a9/.config
+++ b/bsp/qemu-vexpress-a9/.config
@@ -390,7 +390,8 …
```

[pthreads] Fix pthread_cond_timedwait lacks timeout wakeup

---

components/dfs/dfs_v2/src/dfs_mnt.c

[
add doxygen comments for dfs_mnt.c in dfs_v2.
add doxygen comments for dfs_mnt.c in dfs_v2.
- BSP:
- .config:
- action:
]

[components/dfs]add doxygen comments for dfs_mnt.c in dfs_v2.

---

components/dfs/dfs_v2/src/dfs_vnode.c

[
add doxygen comments for dfs_vnode.c 
add doxygen comments for dfs_vnode.c 
- BSP:
- .config:
- action:
]

[components/dfs]add doxygen comments for dfs_vnode.c in dfs_v2.

---

components/dfs/dfs_v2/include/dfs_pcache.h
components/dfs/dfs_v2/src/dfs_pcache.c

[
add doxygen comments for dfs pcache file in dfs_v2.
add doxygen comments for dfs pcache file in dfs_v2.
- BSP:
- .config:
- action:
]

[components/dfs]add doxygen comments for dfs pcache file in dfs_v2.

---

components/dfs/dfs_v2/src/dfs_fs.c

[
add doxygen comments for dfs_fs.c in dfs_v2.
重新提交PR #10527里的内容。
add doxygen comments for dfs_fs.c in dfs_v2.
- BSP:
- .config:
- action:
]

[components/dfs]add doxygen comments for dfs_fs.c in dfs_v2.

---

components/dfs/dfs_v2/src/dfs_file_mmap.c

[
add doxygen comments for dfs_file_mmap.c in dfs_v2.
add doxygen comments for dfs_file_mmap.c in dfs_v2.
- BSP:
- .config:
- action:
]

[components/dfs]add doxygen comments for dfs_file_mmap.c in dfs_v2.

---

components/dfs/dfs_v2/include/dfs_seq_file.h
components/dfs/dfs_v2/src/dfs_seq_file.c

[
add doxygen comments for dfs sequence file in dfs_v2.
add doxygen comments for dfs sequence file in dfs_v2.
- BSP:
- .config:
- action:
]

[components/dfs]add doxygen comments for dfs sequence file in dfs_v2.

---

components/drivers/block/partitions/efi.h
components/drivers/include/drivers/nvme.h
include/rtcompiler.h

[
使用MDK5编译器编译工程后，在运行find_valid_gpt函数时， 因sizeof (legacy_mbr)得出的长度未按1字节对齐而出现内存覆盖问题
1、当 __ARMCC_VERSION < 6010050 时定义 rt_packed 为 __packed
2、参考文档:
1）ARM Compiler toolchain Using the Compiler Version 5.01
https://developer.arm.com/documentation/dui0472/g/compiler-coding-practices/the---packed-qualifier-and-unaligned-data-access-in-c-and-c---code?lang=en
2）ARM Compiler toolchain Using the Compiler Version 4.1
https://developer.arm.com/documentation/dui0472/c/compiler-coding-practices/the---packed-qualifier-and-unaligned-data-access-in-c-and-c---code?lang=en
3）ARM Software Development Toolkit Reference Guide Version 2.50
https://developer.arm.com/documentation/dui0041/c/ARM-Compiler-Reference/Compiler-specific-features/Type-qualifiers?lang=en
- BSP:qemu-vexpress-a9
- …

[arm_compiler_v4/v5] define rt_packed as __packed

---

tools/ci/install.sh

[
脚本中对于macOS的判定方法有误，并且gitee的URL错误
修改macOS的uname为 Darwin ，并且此盖大陆地区的URL为 gitee镜像
- BSP:
- .config:
- action:
]

Fix Darwin detection and URL

---

src/cpu_mp.c
src/cpu_up.c

导致问题的 commit：b084503b6d "[kernel] add UP scheduler critical switch flag."
这个提交会导致 doxygen build 产生告警，导致失败：
```
include/rtthread.h:658: warning: argument 'lock' from the argument list of rt_spin_unlock has multiple @param documentation sections 
include/rtthread.h:660: warning: argument 'lock' from the argument list of rt_spin_unlock_irqrestore has multiple @param documentation sections 
include/rtthread.h:660: warning: argument 'level' from the argument list of rt_spin_unlock_irqrestore has multiple @param documentation sections
```
原因分析：
`src/cpu_up.c` 和 `src/cpu_mp.c` 定义了两套完全相同的函数，因为目前 `documentation/Doxyfile` 中的 INPUT 参数会将 `./src` 下的文件全部加入编译，这导致 `src/cpu_up.c` 和 `src/cpu_mp.c` 都会参与 doxygen 的编译，Doxygen 在处理它们的过程中如果发现这同名函数的 doxygen 注释不同的话会自动进行合并操作，导致形成多个 param 的告警。
以前这两个文件中的 API …

doxygen: fix build error

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart_v2.c
components/drivers/include/drivers/dev_serial_v2.h
components/drivers/serial/dev_serial_v2.c
examples/utest/testcases/drivers/serial_v2/posix/uart_posix_echo_block.c
examples/utest/testcases/drivers/serial_v2/posix/uart_posix_nonblock.c
examples/utest/testcases/drivers/serial_v2/uart_blocking_rx.c
examples/utest/testcases/drivers/serial_v2/uart_blocking_tx.c
examples/utest/testcases/drivers/serial_v2/uart_flush_rx.c
examples/utest/testcases/drivers/serial_v2/uart_flush_txb.c
examples/utest/testcases/drivers/serial_v2/uart_flush_txnb.c
examples/utest/testcases/drivers/serial_v2/uart_get_unread_bytes_count.c
examples/utest/testcases/drivers/serial_v2/uart_nonblocking_tx.c
examples/utest/testcases/drivers/serial_v2/uart_overflow_rxb_txb.c
examples/utest/testcases/drivers/serial_v2/uart_rxb_txb.c
examples/utest/testcases/drivers/serial_v2/uart_rxb_txnb.c
examples/utest/testcases/drivers/serial_v2/uart_rxnb_txb.c
examples/utest/testcases/drivers/serial_v2/uart_rxnb_txnb.c
examples/utest/testcases/drivers/serial_v2/uart_timeout_rxb.c
examples/utest/testcases/drivers/serial_v2/uart_timeout_rxb_txb.c
examples/utest/testcases/drivers/serial_v2/uart_timeout_txb.c

[
DMA模式写满丢弃和写满覆盖和中断方式都跑过utest
]

[component][drivers][serial_v2] 优化serial_v2

---

.github/PULL_REQUEST_TEMPLATE.md

[
#10611 
- BSP:
- .config:
- action:
]

[github] 修改PR提示模板

---

components/net/at/include/at.h
components/net/at/src/at_client.c

[
V2版本的串口，已在at_socket没有使用deinit测试3天，ppp拨号中每隔3分钟deinit一次测试4天。
V1版本的串口，在at_socket测试一个小时。
已知待解决：at_device软件包中直接访问at_client的lock变量需要修改一下，合并后就准备给at_device提PR
]

[component][net][at] at_client增加deInit接口

---

components/drivers/include/drivers/pci_msi.h
components/drivers/pci/host/Kconfig
components/drivers/pci/host/dw/pcie-dw_host.c
components/drivers/pci/msi/irq.c
components/drivers/pci/msi/msi.c
components/drivers/pci/ofw.c

[
1. Fixup the MSI info shuold free
2. Fixup the bus-range probe
3. Fixup the DWC PCI resource release
4. Add SoC PCI Kconfig import
]

[DM/PCI] Update PCI

---

components/drivers/thermal/thermal-cool-pwm-fan.c
components/drivers/thermal/thermal.c

[
1. Fixup the C99, 6.8.1 Labeled statements p4
2. Fixup the PWM-FAN remove handle data ptr
]

[DM/THERMAL] Fixup the Thermal

---

src/scheduler_up.c

[
rt_critical_level 之前是非线程安全的，rt_critical_level 也只有在debug的时候才使用。
rt_enter_critical 使用原子操作在硬件支持的情况下可以减少开关中断
- BSP:
- .config:
- action:
]

[kernel] rt_scheduler_lock_nest使用原子操作

---

bsp/gd32/arm/docs/GD32_ARM系列BSP制作教程.md
bsp/gd32/arm/gd32103c-eval/board/Kconfig
bsp/gd32/arm/gd32105c-eval/board/Kconfig
bsp/gd32/arm/gd32105r-start/board/Kconfig
bsp/gd32/arm/gd32107c-eval/board/Kconfig
bsp/gd32/arm/gd32205r-start/board/Kconfig
bsp/gd32/arm/gd32207i-eval/board/Kconfig
bsp/gd32/arm/gd32303e-eval/board/Kconfig
bsp/gd32/arm/gd32305r-start/board/Kconfig
bsp/gd32/arm/gd32307e-start/board/Kconfig
bsp/gd32/arm/gd32407v-lckfb/board/Kconfig
bsp/gd32/arm/gd32450z-eval/board/Kconfig
bsp/gd32/arm/gd32470z-lckfb/board/Kconfig
bsp/gd32/arm/gd32527I-eval/board/Kconfig
bsp/gd32/arm/gd32e230-lckfb/board/Kconfig
bsp/gd32/arm/gd32e503v-eval/board/Kconfig

[
emove gd32 bsp soft i2c config
]

[bsp/gd32] remove gd32 bsp soft i2c config

---

components/dfs/Kconfig
components/drivers/serial/Kconfig
components/drivers/usb/cherryusb/Kconfig
components/drivers/virtio/Kconfig
components/legacy/usb/Kconfig
components/net/lwip/Kconfig
components/utilities/Kconfig
components/utilities/rt-link/Kconfig
libcpu/Kconfig
src/Kconfig

[
没有名字的 choice → 在 Kconfig 里它就是一个匿名 choice，kconfiglib 内部会分配一个临时对象 ID。
这时 default RT_USING_DFS_V1 指向 V1，但在 _check_choice_sanity() 时，它会检查 default.choice is choice，结果可能对不上（匿名 choice 在解析时会生成两个对象副本），于是报 warning。
有名字的 choice RT_USING_DFS_VERSION → 这个 choice 成了一个有名字的 symbol，kconfiglib 会把它注册进符号表，所有地方引用的都是同一个对象。
所以 default.choice 和 choice 指向的就是同一个实例，不会触发警告
给 choice 显式命名（choice XXX）就能保证引用一致。
无
]

fix: warnings generated by Kconfig.

---

src/klibc/rt_vsnprintf_std.c

[
`src/klibc/rt_vsnprintf_std.c` 中通过 `__GNUC__` 宏来在 gcc 中临时关闭 `Wmaybe-uninitialized`，但 clang 编译器也会定义该宏：
```bash
$ clang -dM -E -x c /dev/null | grep __GNUC__
#define __GNUC__ 4
```
从而在 clang 编译时出现判断错误，clang 编译器报 `Wunknown-warning-option`：
```bash
src/klibc/rt_vsnprintf_std.c:598:32: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-warning-option]
598 | #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
|                                ^
1 warning generated.
```
增加对 `__clang__` 宏的判断。
基于 virt riscv bsp 进行测试，但修改了部分代码以适配 clang 编译，相关修改如下。
```diff
diff --git a/bsp/qemu-virt64-riscv/rtconfig.py b/bsp/qemu-virt64-riscv/rtconfig.py
index 09d530af4a..7dec52efc0 100644
--- a/bsp/qemu-virt64-riscv/rtconfig.py
+++ b/bsp/qemu-virt64-riscv/rtconfig.py
@@ -3,15 +3,15 @@ …
```

fix(klibc): also check `__clang__` when detecting gcc

---

libcpu/risc-v/common64/mmu.c

[
在 `rt_hw_mmu_control` 中，`_query` 函数的返回值类型为 `rt_ubase_t *`，这与后续的 `control_handler()` 的输入参数类型 `rt_base_t *` 不符。
```bash
libcpu/risc-v/common64/mmu.c:575:24: warning: initializing 'rt_base_t *' (aka 'long *') with an expression of type 'rt_ubase_t *' (aka 'unsigned long *') converts between pointers to integer types with different sign [-Wpointer-sign]
575 |             rt_base_t *pte = _query(aspace, vaddr, &level);
|
```
将后续的 `control_handler()` 的输入参数类型修改为 `rt_ubase_t *`。这是自然的，因为 `_query` 返回的是 pte，一般来讲被认为是一个无符号的量。
- BSP: bsp/qemu-virt64-riscv
- .config: 默认配置，无需额外修改
- action:
]

fix(risc-v, mmu): fix type mismatch of return type of `_query`

---

documentation/3.kernel/object/object.md

Object management 的 markdown文档中的代码格式不对齐。采用空格替换tab解决。
本 pr 不涉及代码修改。

doxygen: align code for kenerl object doc

---

bsp/gd32/arm/gd32527I-eval/board/Kconfig
bsp/gd32/arm/gd32h759i-eval/board/Kconfig
bsp/gd32/arm/libraries/gd32_drivers/drv_spi.c
bsp/gd32/arm/libraries/gd32_drivers/drv_spi.h

[bsp/gd32] 更新GD32 SPI驱动

---

components/drivers/ipc/Kconfig
components/finsh/Kconfig
components/finsh/finsh.h
components/finsh/msh.c

[
- BSP:
- .config:
- action:
]

fix: 在没有定义FINSH_USING_SYMTAB时编译报错以及IPC及finsh启用时自动选择必要的功能

---

components/drivers/nvme/nvme.c

[
Fixup the QUEUE alloc errorno check by error ptr instead of nullptr.
]

[DM/NVME] Fixup the QUEUE alloc errorno check

---

examples/utest/testcases/kernel/SConscript
examples/utest/testcases/kernel/thread_suspend_tc.c
src/thread.c

修改rt_thread_suspend 以支持可以挂起其他线程
新增三个测试用例：
1. test_suspend_force_api_basic： 基础API测试。
2. test_suspend_force_normal_usage：创建工作线程和监控线程，验证 `rt_thread_suspend_force` 函数能够正确挂起和恢复目标线程，确保线程状态转换正常且系统调度稳定。
3. test_suspend_force_deadlock_risk：用于验证和演示强制挂起可能带来的死锁问题。

[thread]Modify `rt_thread_suspend` to support suspending other threads.

---

components/lwp/lwp_args.c
components/lwp/lwp_args.h

[
add doxygen comment for lwp_args.
add doxygen comment for lwp_args.
- BSP:
- .config:
- action:
]

[components/lwp]add doxygen comment for lwp_args.

---

components/net/netdev/src/netdev.c

Fixed compilation errors when enabling IPv6 and IPv4 dual-stack support.
* 修复使能IPV6和IPV4双栈情况下编译报错问题
* `inet_ntoa` 原型已经按照单栈和双栈进行了区分，因此可以简化代码
[
- BSP:
- .config:
- action:
]

[net/netdev]Fixed compilation errors when enabling IPv6 and IPv4 dual-stack support.

---

src/scheduler_up.c

[
- BSP:
- .config:
- action:
]

[kernel]fix scheduling exception caused by interrupt preemption in rt_schedule

---

bsp/allwinner/libraries/sunxi-hal/hal/source/sdmmc/osal/os/RT-Thread/os_timer.c
bsp/allwinner/libraries/sunxi-hal/hal/source/usb/host/ehci-timer.c
bsp/allwinner/libraries/sunxi-hal/hal/source/usb/host/ehci.h
bsp/at91/at91sam9260/drivers/at91_mci.c
bsp/at91/at91sam9g45/drivers/at91_mci.c
components/drivers/ipc/completion_mp.c
components/drivers/ipc/completion_up.c
components/drivers/ipc/condvar.c
components/drivers/ipc/dataqueue.c
components/drivers/ipc/waitqueue.c
components/libc/posix/io/epoll/epoll.c
components/libc/posix/io/poll/poll.c
components/libc/posix/pthreads/pthread_cond.c
components/lwp/lwp_ipc.c
components/utilities/rt-link/src/rtlink.c
components/vbus/prio_queue.c
components/vbus/vbus.c
components/vbus/watermark_queue.h
examples/utest/testcases/kernel/timer_tc.c
src/ipc.c
src/mempool.c
src/signal.c

RT_TIMER_CTRL_SET_TIME  and RT_TIMER_CTRL_GET_TIME only accept rt_tick_t, but the current code base pass int/rt_int32_t
randomly.
Check all place that use RT_TIMER_CTRL_SET_TIME /RT_TIMER_CTRL_GET_TIME  and fixes it accordingly

Pass rt_tick_t for RT_TIMER_CTRL_SET_TIME and RT_TIMER_CTRL_GET_TIME

---

.clang-format

[
优化clang-format规则，使其更加满足RT-Thread编码规范
**主要修改内容：**
1. **对齐规则调整**：禁用连续赋值和声明对齐（`AlignConsecutiveAssignments`、`AlignConsecutiveDeclarations` 设为 `false`），数组结构对齐改为 `None`。
2. **注释与换行**：尾随注释对齐改为保留原样（`Leave`），`case` 标签后换行（`AfterCaseLabel: true`）。
3. **函数与命名空间**：允许短函数内联显示（`Inline`），命名空间内容全部缩进（`All`）。
]

improve[clang-format]: optimize the formatting logic for RT-Thread coding standard

---

bsp/gd32/arm/gd32527I-eval/board/Kconfig
bsp/gd32/arm/libraries/gd32_drivers/Kconfig
bsp/gd32/arm/libraries/gd32_drivers/drv_can.c
bsp/gd32/arm/libraries/gd32_drivers/drv_can.h

[
- BSP:
- .config:
- action:
]

[bsp][gd32]: can add support for GD32F5xx

---

bsp/k230/drivers/utest/SConscript
components/drivers/audio/utest/SConscript
components/net/utest/SConscript
components/utilities/Kconfig
components/utilities/utest/utest/SConscript
documentation/6.components/utest/utest.md
examples/utest/testcases/cpp11/SConscript
src/Kconfig
src/klibc/utest/SConscript

Fixed: #10734
由于目前很多模块的 utest 并不打算支持一次性统一开启，另外有些模块的测试由于比较复杂，譬如对其他模块有很多依赖，这导致简单通过一个全局开关来控制使能所有测试变得几乎不可能。这导致过去定义的 `RT_UTEST_USING_ALL_CASES` 已经失去了它最初的含义。
建议淘汰掉这个配置开关。如果某些模块内部觉得需要自己通过配置 enable 一批功能测试，那这种局部的 enable all 交给模块自己去实现，不再提供一个 RTT 全局的 enable 开关了。
如果以后再有此类一次性使能所有单元测试的需求，建议仔细设计一下，特别是要考虑从易用性上如何保证通过打开一个开关就能将所有涉及的模块的依赖关系全部都打开。
特别的 `src/Kconfig` 的这个改动请看一下是否合适？

utest: remove RT_UTEST_USING_ALL_CASES

---

Kconfig.utestcases
components/drivers/core/SConscript
components/drivers/core/utest/Kconfig
components/drivers/core/utest/SConscript
components/drivers/core/utest/device_tc.c
src/utest/Kconfig
src/utest/SConscript

src/utest/device_tc.c is testing API: rt_device_find(), which is a function defined in components/drivers/core/device.c. So it should be a testcase for drivers core, not for core.
Move it to under components/drivers/core.
此 pr 没有对 device_tc.c 代码内容进行改动。

utest: move driver related case under to drivers

---

bsp/gd32/arm/gd32h759i-eval/board/board.c
bsp/gd32/arm/gd32h759i-start/board/board.c

[
使能GD32H7 I/D Cache，移除Systick重复配置代码以解决串口驱动接收不正常和内核测试用例无法通过的问题
在GD32H759I-EVAL与GD32H737Z-START开发板验证通过。
]

[fix] 使能GD32H7 I/D Cache，移除Systick重复配置代码

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_can.c
components/drivers/can/Kconfig
components/drivers/can/dev_can.c
components/drivers/include/drivers/dev_can.h

- 新增支持非阻塞模式下的CAN消息发送，包括软件环形缓冲区管理和动态内存分配选项。
- 完善相关注释和错误处理。
- 更新示例代码以展示阻塞与非阻塞发送的使用方式，并修正部分结构体字段命名与宏定义
[
- BSP:
- .config:
- action:
]

feat(can): 实现非阻塞发送机制并增强CAN驱动功能

---

libcpu/arm/cortex-m4/context_iar.S

[
- BSP:
- .config:
- action:
]

fix:Fixed compilation error for libcpu/cortex-m4.

---

include/rtdef.h
include/rtthread.h
src/idle.c
src/scheduler_mp.c
src/scheduler_up.c
src/signal.c
src/thread.c

清理的工作包括三部分：
- 将独立的 "/**@{*/" 合并到 “@addtogroup group_thread_management” 中
- 将 “/@}*/” 修改为 / @} group_thread_management*/，加上 group 名字后方便找到对应匹配的 “@{” 部分。
- 删除 “include/rtthread.h” 中的 “@addtogroup” 命令，因为在这个头文件中并没有 doxygen 注释，针对函数体的 doxygen 注释基本上全部定义在其他 .c 文件中了。除了两个例外，一个是 rt_thread_inited_hookproto_t，这是一个定义在 `include/rtthread.h` 中的函数类型。另一个是 rt_thread_idle_sethook，这是一个已知的问题，具体解释看 `include/rtthread.h` 代码中的 FIXME。

doxygen: cleanup code for group_thread_management

---

.github/workflows/action_tools.yml
.github/workflows/auto_assign_reviewers.yml
.github/workflows/auto_labeler.yml
.github/workflows/bsp_buildings.yml
.github/workflows/compile_bsp_with_drivers.yml
.github/workflows/doxygen.yml
.github/workflows/format_check.yml
.github/workflows/pkgs_test.yml
.github/workflows/pr_clang_format.yml
.github/workflows/pr_format_bot.yml
.github/workflows/static_code_analysis.yml
.github/workflows/utest_auto_run.yml

[
Ref: #10738 
- BSP:
- .config:
- action:
]

[github][ci]: add concurrency control to GitHub Actions
