RT-Thread/rt-thread

bsp/imxrt/imxrt1170-nxp-evk/template.ewd, bsp/imxrt/imxrt1170-nxp-evk/template.ewp, bsp/imxrt/imxrt1170-nxp-evk/template.ewt
[
更新imxrt1170平台iar工程模板，解决版本低的问题
]
=> [imxrt1170]Update iar project

components/drivers/ipc/waitqueue.c
=> [modify]修改waitqueue.c中的注释错误

bsp/wch/risc-v/Libraries/ch32_drivers/drv_log.h
[
添加了drv_ulog.h，解决了scons编译报错的问题，不影响其他功能，其他位置使用ulog打印也是正常的
但实际上，在uasart初始化完之前，drv_usart.c中的日志输出语句是不起作用的，仅仅是在编辑代码的时候，提醒开发者此处应注意
已在ch32v307评估板上测试，使用scons编译，wchlink下载
]
- [ x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ x] …
=> [Bsp/CH32V307] add drv_ulog.h so that the project can be built successfully by env

bsp/apm32/apm32f407ig-minibroard/board/board.c
[
使用APM32F407VGT6芯片发现shell命令行无法接收命令，解决shell命令行输入问题
将board.c中的：
GPIO_ConfigStruct.mode = GPIO_MODE_IN;
GPIO_ConfigStruct.pupd = GPIO_PUPD_UP;
修改为：
GPIO_ConfigStruct.mode = GPIO_MODE_AF;
GPIO_ConfigStruct.pupd = GPIO_PUPD_NOPULL;
使用APM32F407VGT6测试成功
]
=> [bsp][APM32][APM32F407VGT6]

bsp/bluetrum/libraries/hal_drivers/drv_flash.c
=> Add annotations

bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/README.md, bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/pins_arduino.h, bsp/stm32/stm32f103-blue-pill/board/Kconfig
[
补全 stm32f103-blue-pill BSP RTduino软件包中SPI功能的适配。
]
=> [RTduino]Add SPI adaptation of stm32f103-blue-pill BSP

bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/pins_arduino.h
=> Modify error annotations

bsp/wch/risc-v/ch32v307v-r1/README.md
[
- MCU：CH32V307VCT6，主频 144MHz，FLASH和RAM可配置
- LED：2个，用户 LEDs， LED1（blue），LED2(red)。
- 按键：3个，Reset， User 和 Download。
- LED：2个，用户 LEDs， LED1（blue），LED2（blue）。
- 按键：2个，Reset， User 。
- USB：2个，Tpye-C。
- 网口：1个，内置 10M PHY。
- 板载 WCH-Link 下载调试工具。
@@ -32,11 +32,11 @@ CH32V307V-R1 是 WCH 推出的一款基于 RISC-V 内核的开发板，最高主
本 BSP 为开发者提供 Scons编译配置。下面介绍如何将系统运行起来。
本 BSP 为开发者提供 Scons 编译配置。下面介绍如何将系统运行起来。
推荐使用RT-Thread Studio软件里面的编译器。
推荐使用 RT-Thread Studio 软件里面的编译器。
@@ -76,7 +76,7 @@ scons
打开WCH RISC-V MCU ProgrammerTool下载软件，选择刚刚生成的 **rtthread.bin**  文件，进行下载。
打开 WCH RISC-V MCU ProgrammerTool 下载软件，选择刚刚生成的 **rtthread.bin**  文件，进行下载。
修改了 ch32v307 中 readme 文件的一些描述
]
The following content must not be changed in the submitted PR …
=> 修改了ch32 的 readme 文件

bsp/stm32/stm32f767-fire-challenger-v1/README.md
[
提交这份PR的原因是修改这个README.md文档中大小写问题和文章格式问题。
The reason for submitting this PR is to modify the capitalization and article format issues in this README.md document.
解决的问题：stm32f767-v1、STM32f767和在 bsp 下打开 env 工具此类的大小写问题，以及文档的数字和字符间空格。
Resolved issues: capitalization issues such as stm32f767-v1, STM32f767, and opening the env tool under bsp, as well as numbers and spaces between characters in documents.
解决方法：按照PR格式进行修改的，小写换成大写，并且添加。
Solution: Modify according to PR format, change lowercase to uppercase, and add.
] …
=> 对README..md文件中的大小写和文章中的空格修改

tools/building.py
… same link-order/map files/BIN files from the same source files.
**Reason for submission:** 
The map file, BIN file, and link order generated by RT-Thread Scons compiled from the same source code are different, 
which introduces variables for embedded debugging to trace back the source code from the PC register address, 
which increases uncertainty; 
The running results of different BIN files are different , 
this operating difference is smaller in some software versions, 
and larger in some software versions;
**Problem solved:** 
Fixed the link order. The randam The map file, BIN file, and link order generated by RT-Thread Scons compiled from the same source code are different
**Solution:** 
Modify the building.py file to sort objects before each target is generated by objects. …
=> [tools/link-order]Sort objects so that compilation can be done in a fixed link order.

include/rtdef.h
=> A comment has been added

tools/building.py
Reverts RT-Thread/rt-thread#6406
=> Revert "[tools/link-order]Sort objects so that compilation can be done in a fixed link order."

bsp/imxrt/imxrt1170-nxp-evk/board/board.c, bsp/imxrt/libraries/drivers/SConscript, bsp/imxrt/libraries/drivers/drv_common.c
=> Support us delay

tools/building.py
=> [iar] 修正IAR编译链名称

components/libc/compilers/common/extension/sys/types.h, include/rtdef.h
=> [kernel] add rt_ssize_t data structure

bsp/stm32/libraries/HAL_Drivers/drv_can.c
修复字符串比较错误
[
解决问题：
stm32下的drv_can.c的一处代码错误
解决方案：
修复代码错误
测试环境：
开发板
]
=> Modified   bsp/stm32/libraries/HAL_Drivers/drv_can.c

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript, bsp/wch/risc-v/Libraries/ch32_drivers/drv_dac.c, bsp/wch/risc-v/Libraries/ch32_drivers/drv_dac.h, bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
[添加了 dac 的驱动，加入了 drv_dac.c 和 drv_dac.h 文件；
修改了 E:\rt\rt_github\rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下的 SConscript 文件；
修改了 E:\rt\rt_github\rt-thread\bsp\wch\risc-v\ch32v307v-r1\board 目录下的 Kconfig 文件；
已在 ch32v307 评估板进行测试。
]
=> [ch32v307v-r1] 添加dac驱动

bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/README_zh.md, bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/pins_arduino.h
=> [RTduino]stm32f401-st-nucleo 更新对接文件

tools/iar.py
=> [tools][iar] 将IARPath作为独立函数

src/memheap.c
[
修复 AC6 Oz 优化问题
之前修复过，后续代码变更中，将修复弄没了
]
=> [memheap] Fix the Oz optimization problem of AC6 compiler

bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/pins_arduino.h
=> [RTduino]stm32f103-blue-pill更新对接文件

bsp/simulator/rtconfig_project.h, components/dfs/filesystems/romfs/dfs_romfs.c, components/drivers/hwtimer/hwtimer.c, components/drivers/i2c/i2c-bit-ops.c, components/drivers/include/ipc/ringbuffer.h, components/drivers/ipc/pipe.c, components/drivers/ipc/ringbuffer.c, components/drivers/mtd/mtd_nand.c, components/drivers/sdio/block_dev.c, components/drivers/sdio/mmc.c, components/drivers/sdio/sd.c, components/drivers/serial/serial.c, components/drivers/touch/touch.c, components/libc/compilers/common/cstdlib.c, components/libc/compilers/common/ctime.c, components/libc/posix/io/poll/select.c, components/net/lwip/port/ethernetif.c, components/utilities/rt-link/inc/rtlink.h, components/utilities/rt-link/src/rtlink.c, components/utilities/rt-link/src/rtlink_hw.c, components/utilities/ulog/ulog.c, src/ipc.c
=> [fix] Fix simulator compilation warnings

bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/pins_arduino.h, bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/pins_arduino.h
=> [RTduino]更新stm32f469的对接文件

tools/building.py, tools/options.py
scons --target=iar --exec-path=xxxx
scons --exec-path=xxxx
scons -j12 --exec-path=xxxx
xxx为路径，在路径有空格时，需要前后加双引号
https://github.com/RT-Thread/env/commit/7391fab797d3e9548241b7dd6e1c6b279eab28a0
[
] …
=> [tools] 增加scons --exec-path=xxx命令 用于动态设置编译链路径

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript, bsp/wch/risc-v/Libraries/ch32_drivers/drv_rtc.c, bsp/wch/risc-v/Libraries/ch32_drivers/drv_rtc.h, bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
[
添加了ch32v307 的 rtc 驱动，已在评估板进行测试，但有 alarm 部分的 ops 待实现；
在 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下添加了drv_rtc.c 和 drv_rtc.h 文件；
修改了 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下的 SConscript 文件；
修改了 rt-thread\bsp\wch\risc-v\ch32v307v-r1\board 目录下的 Kconfig 文件。
]
=> [ch32v307][bsp]添加了 rtc 驱动

bsp/tms320f28379d/.cproject, bsp/tms320f28379d/.project, bsp/tms320f28379d/2837x_RAM_lnk_cpu1.cmd, bsp/tms320f28379d/drivers/config/pwm_config.h, bsp/tms320f28379d/drivers/drv_config.h, bsp/tms320f28379d/drivers/drv_pwm.c, bsp/tms320f28379d/drivers/drv_pwm.h, bsp/tms320f28379d/rtconfig.h, components/drivers/include/drivers/rt_drv_pwm.h, components/drivers/misc/rt_drv_pwm.c
[
增加c28x芯片的pwm驱动
已经在TMS320F28379中通过测试
pwm设备框架增加如下方法：
#define PWM_CMD_SET_DEAD_TIME  (RT_DEVICE_CTRL_BASE(PWM) + 8)
#define PWM_CMD_SET_PHASE   (RT_DEVICE_CTRL_BASE(PWM) + 9)
#define PWM_CMD_ENABLE_IRQ  (RT_DEVICE_CTRL_BASE(PWM) + 10)
#define PWM_CMD_DISABLE_IRQ  (RT_DEVICE_CTRL_BASE(PWM) + 11)
]
=> [TMS320F28379] implement PWM driver

bsp/essemi/es32f369x/applications/arduino_pinout/README.md, bsp/stm32/libraries/HAL_Drivers/drv_pwm.c, bsp/stm32/libraries/HAL_Drivers/drv_usart.c, bsp/stm32/stm32f072-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/README.md, bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/README_zh.md, bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f412-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/README.md, bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/README.md
=> [rtduino][readme] change title

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript, bsp/wch/risc-v/Libraries/ch32_drivers/drv_iwdt.c, bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
[
添加了 ch32v307 看门狗驱动，已在 ch32v307评估板验证；
修改了 rt-thread\bsp\wch\risc-v\ch32v307v-r1\board 目录下的 Kconfig 文件；
修改了 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下的 SConscript 文件；
添加了 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下的 drv_iwdt.c 文件；
]
=> [ch32v307][bsp]添加了看门狗驱动

bsp/qemu-vexpress-a9/qemu.bat, bsp/qemu-vexpress-a9/qemu.sh
=> [qemu-vexpress-a9] QEMU运行时显示qemu版本号

bsp/gd32/arm/gd32103c-eval/rtconfig.py, bsp/gd32/arm/gd32105c-eval/rtconfig.py, bsp/gd32/arm/gd32105r-start/rtconfig.py, bsp/gd32/arm/gd32107c-eval/rtconfig.py, bsp/gd32/arm/gd32205r-start/rtconfig.py, bsp/gd32/arm/gd32207i-eval/rtconfig.py, bsp/gd32/arm/gd32303c-start/rtconfig.py, bsp/gd32/arm/gd32303e-eval/rtconfig.py, bsp/gd32/arm/gd32305r-start/rtconfig.py, bsp/gd32/arm/gd32307e-start/rtconfig.py, bsp/gd32/arm/gd32407v-start/rtconfig.py, bsp/gd32/arm/gd32450z-eval/rtconfig.py, bsp/hc32/ev_hc32f460_lqfp100_v2/rtconfig.py, bsp/mm32/mm32f3270-100ask-pitaya/SConstruct, bsp/mm32/mm32f3270-100ask-pitaya/rtconfig.py, bsp/n32/n32g45xvl-stb/rtconfig.py, bsp/stm32/stm32f103-100ask-mini/rtconfig.py, bsp/stm32/stm32f103-100ask-pro/rtconfig.py, bsp/synwit/swm341/rtconfig.py
=> [iar] PLATFOMR更正为'iccarm'

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript
=> [ch32v3] 修改RT_USING为BSP_USING

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript, bsp/wch/risc-v/Libraries/ch32_drivers/drv_can.c, bsp/wch/risc-v/Libraries/ch32_drivers/drv_can.h, bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
[
CH32V307 添加can驱动。
CAN1和CAN2均可以使用，而且调整好波特率
]
=> [bsp][ch32v307] 添加can驱动

components/utilities/ulog/ulog.c, components/utilities/ulog/ulog.h
- 重构格式化器
- 重写 HEX 日志功能，与标准日志使用相同的格式化器。与标准日志在日志过滤功能和日志头显示功能上一致
=> [components][utilities][ulog] Improve the HEX LOG by new formater.

.gitignore, tools/building.py, tools/options.py
- 导出rtstudio工程时，多增加一级目录，防止BSP本地Sconscript和导出的工程的Sconscript粘接 导致编译出错
- 增加命令别名 --dist-rtstudio 该命令和 --dist-ide命令执行一致，方便用户理解，--dist-ide IDE表示的内容过于宽泛
ENV 和Studio均测试通过
[
]
以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上 …
=> [dist-ide] 优化导出RTThread Studio工程命令

components/drivers/sdio/mmcsd_core.c
mmcsd_detect 函数在检测 sdio设备不成功时，也需要向 mmcsd_hotpluge_mb这个 mailbox反信。
■需求
代码实现是：
SD卡的插拔检测有一个thread，thread会loop 读取SD卡探测用的gpio，如果gpio值为1，则认为插入SD卡了，紧接着
调用 mmcsd_change 函数通知mmcsd_core，进行SD初始化。
■bug现象
插入SD卡后，
执行流: mmcsd_change(driver中调用) → mmcsd_detect（组件 sdio）
当执行到：mmcsd_detect的mmcsd_send_app_op_cond 函数时拔卡的话， 会造成此此函数执行错误，此时mmcsd_detect函数就不会发rt_mb_send 导致mmcsd_change 卡住 。
这样的话，在插入SD卡时，就无法执行mmcsd_change 了。 …
=> [components] sdio driver

components/utilities/ulog/ulog.c
=> [ulog] fix HEX log size calculate error.

components/drivers/serial/serial_v2.c
[
偶然看到的，个人认为此处用 FINSH_THREAD_NAME 更合适一些， 谢谢！
]
=> [proposal] replace "tshell" with FINSH_THREAD_NAME in rt_serial_control

.github/workflows/action.yml
=> [ci]add ft2004

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript, bsp/wch/risc-v/Libraries/ch32_drivers/drv_soft_i2c.c, bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
[
修复了  bsp/wch/risc-v/Libraries/ch32_drivers 目录下 SConscript 中模拟 iic 的BUG
]
=> [bsp][ch32v307]修复了模拟iic的BUG

bsp/renesas/libraries/HAL_Drivers/drv_common.c, bsp/renesas/ra6m4-cpk/README.md, bsp/renesas/ra6m4-cpk/board/Kconfig
[ 添加segger rtt 为console的Kconfig]
=> [bsp][RA6M4]Add segger rtt function

bsp/stm32/stm32f072-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f072-st-nucleo/applications/arduino_pinout/README_zh.md, bsp/stm32/stm32f412-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f412-st-nucleo/applications/arduino_pinout/README_zh.md, bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/README.md, bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/README_zh.md
=> [bsp][rtduino] update readme

bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c, components/drivers/serial/serial_v2.c
- 简化 串口 V2 STM32 DMA 接收驱动代码
- 增加 STM32 DMA 接收对于使能 CPU Cache 情况的支持
- 完善 串口 V2 配置代码，支持对已打开串口进行配置 
=> Update the SerialV2 drver on STM32

README.md, README_de.md, README_es.md, README_zh.md
=> [readme] add stars status

bsp/at32/libraries/rt_drivers/drv_emac.c, bsp/at32/libraries/rt_drivers/drv_usart.c
[
[at32/bsp] optimize emac and usart driver code
]
=> [at32/bsp] optimize emac and usart driver code

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript, bsp/wch/risc-v/Libraries/ch32_drivers/drv_pwm.c, bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
[
添加了pwm驱动，已在ch32v307评估板验证；
在 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下添加了 drv_pwm.c 文件；
修改了 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下的 SConscript 文件；
修改了 rt-thread\bsp\wch\risc-v\ch32v307v-r1\board 目录下的 Kconfig 文件。
]
=> [bsp][ch32v307]添加了pwm驱动

bsp/synopsys/boards/README.md, bsp/synopsys/boards/SConstruct, bsp/synopsys/boards/drivers/rt_board.c, bsp/synopsys/boards/rtconfig.py
This PR updates ARC port, in particular:
* Makes it buildable with Python 3.x
* Fixes documentation
* Accommodates changes in embARC BSP
=> ARC: Minor port updates

bsp/stm32/libraries/HAL_Drivers/drv_spi.c, bsp/stm32/libraries/HAL_Drivers/drv_spi.h
[
根据[pull-6372](https://github.com/RT-Thread/rt-thread/pull/6372)的建议，将完成量放到底层驱动中。
]
=> [bsp/stm32] 将spi DMA传输更改为阻塞线程方式

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript, bsp/wch/risc-v/Libraries/ch32_drivers/drv_soft_spi.c, bsp/wch/risc-v/Libraries/ch32_drivers/drv_soft_spi.h, bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
[
添加了软件spi驱动，已在ch32v307评估板验证；
在 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下添加了 drv_soft_spi.c 文件；
在 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下添加了 drv_soft_spi.h 文件；
修改了 rt-thread\bsp\wch\risc-v\Libraries\ch32_drivers 目录下的 SConscript 文件；
修改了 rt-thread\bsp\wch\risc-v\ch32v307v-r1\board 目录下的 Kconfig 文件。
]
我在这个拉取/合并请求中已经考虑了 As part of this pull request, …
=> [bsp][ch32v307]增加软件spi驱动

.gitee/PULL_REQUEST_TEMPLATE.en.md, .gitee/PULL_REQUEST_TEMPLATE.zh-CN.md, .github/PULL_REQUEST_TEMPLATE.md
=> [pr-template] 修正PR模板的链接路径错误

bsp/renesas/libraries/HAL_Drivers/drv_usart_v2.c
=> [bug] 修复drv_usart_v2.c

components/utilities/ymodem/ry_sy.c, components/utilities/ymodem/ymodem.c
[
修复了使用ymodem发送文件时，会卡在第二包数据；根据ymodem的协议修复了发送文件出现的问题，并通过测试正常使用。
]
=> ymodem of send error

bsp/wch/risc-v/ch32v307v-r1/rtconfig.py
[
删去了rtconfig.py中对memset重载的配置，经过编译测试，没有问题，注意使用的时候添加string.h头文件
]
=> [ch32v307] 删掉无意义的memset重载

bsp/wch/risc-v/ch32v307v-r1/SConstruct, bsp/wch/risc-v/ch32v307v-r1/board/linker_scripts/link.lds, bsp/wch/risc-v/ch32v307v-r1/rtconfig.py
[
https://github.com/RTduino/RTduino/discussions/46
]
=> [ch32v307] support c++

components/libc/compilers/common/include/sys/time.h
=> [libc][time] 解决部分编译平台CLOCKS_PER_SEC无法被重新定义的问题

bsp/stm32/libraries/HAL_Drivers/drv_pwm.c
=> [bsp] fix the return of the function(drv_pwm_control) in stm32 drv_pwm

tools/keil.py
[
- 把rtconfig.py中PLATFORM改为“armclang”使用KEIL的AC6编译器
使用scons --target=mdk5后，无法打印版本
- 修改PLATFORM改为“armcc”可打印版本
- ARMCC_Version中增加判断为“armcc”还是“armclang”
- armclang使用armlink.exe打印版本信息
- 硬件：STM32F429IGT6
- KEIL5，编译器:AC6
- 测试AC6成功打印版本
]
=> [Tools] add armclang(MDK) get version support

src/Kconfig, src/memheap.c
[
- 更正 RT_MEMHEAP_BSET_MODE -> RT_MEMHEAP_BEST_MODE 拼写错误。
]
=> [update]更正 RT_MEMHEAP_BSET_MODE -> RT_MEMHEAP_BEST_MODE 拼写错误。

bsp/essemi/es32f369x/applications/arduino_pinout/SConscript, bsp/stm32/stm32f072-st-nucleo/applications/arduino_pinout/SConscript, bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/SConscript, bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/SConscript, bsp/stm32/stm32f411-st-nucleo/applications/arduino_pinout/Sconscript, bsp/stm32/stm32f412-st-nucleo/applications/arduino_pinout/Sconscript, bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/SConscript, bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/SConscript
=> [rtduino] 修正pinout_arduino文件所在Group名称

components/finsh/cmd.c, include/rtdef.h, include/rtthread.h, src/ipc.c, src/thread.c
[Kernel] Add nested mutex feature.
=> [Kernel] Add nested mutex feature

bsp/stm32/libraries/HAL_Drivers/SConscript, bsp/stm32/libraries/HAL_Drivers/drv_pwm.c, bsp/stm32/libraries/HAL_Drivers/drv_tim.c, bsp/stm32/libraries/HAL_Drivers/drv_tim.h, bsp/stm32/libraries/HAL_Drivers/drv_usart.h
=> [stm32][tim/pwm] 抽出公共代码，防止日后演进出现分歧

bsp/nuvoton/numaker-pfm-m487/board/Kconfig, bsp/stm32/stm32f407-armfly-v5/board/Kconfig, bsp/stm32/stm32f469-st-disco/board/Kconfig, bsp/stm32/stm32h750-artpi/board/Kconfig, bsp/stm32/stm32l475-atk-pandora/board/Kconfig, bsp/synwit/swm341/drivers/Kconfig
[
packages索引那边的错误，无需设置子级控制宏。
]
=> [Kconfig] remove PKG_USING_SENSORS_DRIVERS and PKG_USING_TOUCH_DRIVERS

bsp/gd32/arm/libraries/gd32_drivers/drv_soft_i2c.h
修改drv_soft_i2c.h中I2C0_BUS_CONFIG定义错误问题。
[
drv_soft_i2c.h中I2C0_BUS_CONFIG定义错误，这里修改。
]
=> [gd32]修改I2C0_BUS_CONFIG定义错误

components/drivers/include/drivers/mmcsd_host.h, components/drivers/sdio/mmc.c, components/drivers/sdio/mmcsd_core.c, components/drivers/sdio/sd.c, components/drivers/sdio/sdio.c
[
SD卡初始化异常
修改SD检测线程函数里面的延时实现，将mmcsd_delay_ms改为rt_thread_mdelay
在imxrt1170-evk板卡测试通过
]
=> [components]修改SD和emmc延时实现

bsp/imxrt/imxrt1170-nxp-evk/m7/applications/mnt.c, bsp/imxrt/imxrt1170-nxp-evk/m7/board/Kconfig, bsp/imxrt/libraries/drivers/drv_sdio.c
[
SD卡作为引导器后，系统无法挂载SD卡分区
SD卡作为引导器时，bootROM已完成对SD卡的初始化，因此drv_sdio.c驱动文件无需再对其进行初始化，基于此，在板级Kconfig中加入CODE_STORED_ON_SDCARD宏，用户在使用SD卡作为引导器时，需开启此宏，以防止驱动文件对SD再次初始化；而在调试模式下，需关闭此宏（如果需要支持SD卡的话）
在imxrt1170-EVK环境下测试通过
]
=> [imxrt1170]修复SD卡作为引导器后，系统无法挂载SD卡的问题

bsp/imxrt/imxrt1170-nxp-evk/m7/board/Kconfig
=> 修复flexspi配置语法错误

components/drivers/include/drivers/sensor.h, components/drivers/sensors/SConscript, components/drivers/sensors/sensor.c
=>  [sensor] 统一数据结构名称和函数命名

components/drivers/include/drivers/sensor.h, components/drivers/sensors/sensor.c
related: https://github.com/RT-Thread-packages/aht10/pull/13 
https://github.com/RT-Thread-packages/mpu-6xxx/pull/26
[
使用rt_ssize_t来作为返回值，既可以返回正确的数值，也可以返回负值作为错误码，该问题同样在SPI IIC中出现，由于早期rt-thread没有定义该错误类型，导致函数无法同时返回数值和错误码，在遇到错误时只能返回0.
]
=> [sensor] use rt_ssize_t as the return value data type

bsp/n32/libraries/n32_drivers/drv_spi.c
[
使用n32g435CBL7时发现spi驱动有低级错误导致不能使用RT_SPI_MODE_0与RT_SPI_MODE_2。
SPI只有Mode0到Mode3,在设置模式时已设置CLKPHA,多余的代码使RT_SPI_MODE_0与RT_SPI_MODE_2失效,直接删除该代码即可。
]
=> [n32] 修改 bsp/n32/libraries/n32_drivers/drv_spi.c,修复SPI驱动不能使用RT_SPI_MODE_0与RT_SPI_MODE_2的错误。

components/net/netdev/src/netdev.c
=> [net] netdev.c ping指令 无参数错误返回信息 参数位置错了

bsp/stm32/stm32l475-atk-pandora/board/ports/sensor_port.c, components/drivers/include/drivers/sensor.h
[
user_data RT-Thread自己偷偷用的情况需要逐步替代 不能什么都叫user_data字段，更不能什么乱七八糟的东西都往user_data里塞
related: https://github.com/RT-Thread-packages/mpu-6xxx/pull/27
]
=> [sensor] use arg to replace user_data

components/fal/SConscript, src/SConscript
=> [kernel] 优化Sconscript脚本

tools/eclipse.py
[
1. 制作瑞萨ra2l1的开发板支持包时，发现工作目录下有几个目录，里面的scons脚本并没有，更新 eclipse的工程之后，并没有被添加到排除列表。
2. 之前还遇到过，如果packages目录下有软件包，但是都没被包含到工程里。这是生成eclipse工程时，也不会把packages目录排除。
在eclipse脚本里获取所有源码所在的路径时，把工作目录下的文件夹都添加进去
> 但是感觉可能还是有风险，感觉这里获取所有目录时，应该用递归的方式，把当前工作目录下的所有路径都加入进来。然后再做后面的排除。
在windows上，制作ra2开发板支持包测试通过。
]
=> 【修复】工作目录下，当某一目录下的源文件都不需要添加到工程时，此目录不会被屏蔽的问题。

bsp/imxrt/imxrt1170-nxp-evk/m7/board/Kconfig, bsp/imxrt/imxrt1170-nxp-evk/m7/board/board.c, bsp/imxrt/libraries/MIMXRT1170/MIMXRT1176/drivers/fsl_os_abstraction.h, bsp/imxrt/libraries/MIMXRT1170/MIMXRT1176/drivers/fsl_os_abstraction_config.h, bsp/imxrt/libraries/MIMXRT1170/MIMXRT1176/drivers/fsl_os_abstraction_rtthread.c, bsp/imxrt/libraries/MIMXRT1170/MIMXRT1176/drivers/fsl_os_abstraction_rtthread.h, bsp/imxrt/libraries/MIMXRT1170/MIMXRT1176/drivers/generic_list.c, bsp/imxrt/libraries/MIMXRT1170/MIMXRT1176/drivers/generic_list.h, bsp/imxrt/libraries/MIMXRT1170/SConscript, bsp/imxrt/libraries/drivers/drv_usbh.c, bsp/imxrt/libraries/drivers/usb/host/usb_host.h, bsp/imxrt/libraries/drivers/usb/host/usb_host_devices.c, bsp/imxrt/libraries/drivers/usb/host/usb_host_ehci.c, bsp/imxrt/libraries/drivers/usb/host/usb_host_ehci.h, bsp/imxrt/libraries/drivers/usb/host/usb_host_hci.c, bsp/imxrt/libraries/drivers/usb/include/usb.h, bsp/imxrt/libraries/drivers/usb/include/usb_host_config.h, bsp/imxrt/libraries/drivers/usb/phy/usb_phy.c, bsp/imxrt/libraries/drivers/usb/phy/usb_phy.h
[
修复USB驱动，实现imxrt1176平台usb host，支持usb3.0读写
]
=> [imxrt1176]Fix usb

components/drivers/Kconfig, components/drivers/include/drivers/sensor.h, components/drivers/sensors/sensor.c
=> [sensor] 传感器数据类型使用rt_sensor_float_t代替rt_uint32_t类型

bsp/wch/risc-v/Libraries/ch32_drivers/drv_soft_spi.c
[
修改ch32v307软件spi的#if宏，问题是BSP_USING_SOFT_I2C，解决方法是修改成 BSP_USING_SOFT_SPI
为了改错
win10,vscode编辑代码，
]
=> [bsp][ch32v307]修改ch32v307软件spi的宏

bsp/stm32/stm32f410-st-nucleo/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f410-st-nucleo/board/Kconfig
=> 修改pins_arduino.c和Kconfig

README.md, README_de.md, README_es.md, README_zh.md
Signed-off-by: supperthomas <78900636@qq.com>
[
readme中缺少nordic芯片
添加Nordic的芯片
无
]
=> [doc] Add the Nordic chip and link

bsp/stm32/stm32l475-atk-pandora/board/Kconfig, components/drivers/Kconfig, components/drivers/sensors/sensor_cmd.c
using floating print format by default
[
]
=> [sensor] improve cmd

components/dfs/src/dfs.c, components/finsh/cmd.c
=> [msh] remove list_xxx commands, use 'list' to replace

bsp/wch/risc-v/ch32v307v-r1/README.md, bsp/wch/risc-v/ch32v307v-r1/README_zh.md
=> [ch32] fix a typo

bsp/qemu-vexpress-a9/rtconfig.py, components/dfs/src/dfs_posix.c, components/libc/compilers/common/include/sys/select.h, components/libc/compilers/common/include/sys/signal.h, components/libc/compilers/common/include/sys/time.h, components/libc/compilers/musl/SConscript, components/libc/compilers/musl/syscalls.c, components/libc/posix/io/stdio/libc.c, include/rtdef.h, tools/gcc.py
=> pre add musl

components/libc/compilers/common/include/sys/signal.h
在keil、iar、newlib、musl、vs2019下编译通过
[
]
=> [libc][musl]解决signal.h报错的问题

components/drivers/Kconfig, components/drivers/include/drivers/serial.h, components/drivers/include/drivers/serial_v2.h, components/drivers/serial/serial.c, components/drivers/serial/serial_v2.c, components/drivers/tty/SConscript, components/drivers/tty/console.c, components/drivers/tty/include/console.h, components/drivers/tty/include/posix_termios.h, components/drivers/tty/include/tty.h, components/drivers/tty/include/tty_ldisc.h, components/drivers/tty/n_tty.c, components/drivers/tty/posix_termios.c, components/drivers/tty/pty.c, components/drivers/tty/tty.c, components/drivers/tty/tty_ioctl.c, components/drivers/tty/tty_ldisc.c, include/rtdef.h
=> add tty device

components/libc/compilers/armlibc/syscalls.c
[
- AC6更新至6.19后_sys_tmpnam()函数编译报错 
- https://github.com/RT-Thread/rt-thread/issues/6642
- 替换为void 类型函数
- 使用宏定义判断编译器版本
- STM32F4
- MDK5.38 AC6 6.19
]
=> [armlibc] 修复AC6更新至6.19后_sys_tmpnam()函数编译报错

bsp/gd32/arm/libraries/gd32_drivers/drv_spi.c
=> [GD32] fix bug on spi driver

libcpu/arm/cortex-a/start_gcc.S
If the application defines dozens of global variables, the speed of clearing the bss segment will be slower.
Because icache can be enabled before the mmu enabled. Therefore, in order to speed up the process of clearing the BSS segment, enable icache needs to be put ahead.
[
应用程序中定义全局变量很多，会导致启动速度很慢，查到原因是清bss段的处理非常慢。
所以做了个优化，在清bss段之前打开icahe 跟分支预测，这样会大大的缩短启动时间。
]
=> [bsp] faster startup for cortex-a

components/dfs/src/dfs_file.c
[
Fix cat cmd cannot output correctly
]
=> Fix cat cmd cannot output correctly

examples/utest/testcases/kernel/messagequeue_tc.c
[
修复 riscv64 messagequeue_tc 报错
]
=> 修复 riscv64 messagequeue_tc 报错

tools/building.py, tools/options.py
若不填写该字段，默认为project.xx 与原来保持一致
相关：https://club.rt-thread.org/ask/article/f998b21633f90916.html
[
]
=> [tools] 支持通过--project-name=xxx设置生成的工程文件名称

bsp/lpc55sxx/lpc55s69_nxp_evk/rtconfig.py
[
CI error 
add macro  -DCPU_LPC55S69JBD100_cm33_core0
gcc ci
]
=> [bsp][lpc55s69] Fix the ci error for lpc55s69

components/libc/compilers/common/ctime.c, components/lwp/lwp_syscall.c
=> 还原原生 timer syscall 支持

bsp/wch/risc-v/Libraries/ch32_drivers/drv_spi.c
[
修改了部分函数名，将大写改为小写，在ch32v307上通过编译验证
]
=> change name in drv_spi.c

bsp/qemu-virt64-aarch64/rtconfig.py, components/net/lwip/port/sys_arch.c
fix the lwIP sem/mutex/mbox valid issue under 64bit width CPU ARCH.
=> [lwIP] fix lwip sem/mutex valid issue.

bsp/stm32/stm32l475-atk-pandora/README.md, bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/README.md
=> [stm32l475-pandora] update readme

bsp/stm32/libraries/HAL_Drivers/drv_tim.c
[
和上一个pr解决一样的问题：
参考 https://github.com/RT-Thread/rt-thread/pull/6682
]
=> [BSP][STM32]修改TIM驱动APBx外设时钟选择方案

bsp/stm32/libraries/HAL_Drivers/drv_usart_v2.c
1.顺序修改回V1,保证每次都是当前数据发送完才跳出
[
串口阻塞发送一段时间出现了异常，经排查发送顺序修改回V1变为正常
串口PUTC顺序修改回V1,保证每次都是当前数据发送完才跳出
STM32L4产品板子
]
=> 修改串口V2的putc顺序

components/utilities/ymodem/ymodem.c, components/utilities/ymodem/ymodem.h
[
- 目前Ymodem传输过程中的发现异常直接报错退出。
> https://club.rt-thread.org/ask/article/9b7f5db2994a76cb.html
- 根据Ymodem协议，允许异常重试。
- 在STM32Ymodem例程中也有相应异常处理流程
- 根据论坛方案与STM32的Ymodem例程。
- 添加异常处理流程。并可通过配置宏选择重试次数
]
=> [ymodem]添加传输过程中的异常处理流程

components/finsh/cmd.c
[
对齐list命令的描述项，并和help输出的命令描述项也对齐
对齐list命令的描述项
对齐list命令的描述项
qemu-a9
]
=> [components/finsh]使 list 命令的解释对齐

components/finsh/msh.c
[
修复开启RT_USING_MODULE时，system 重定义的问题
删除一个旧的实现
qemu-a9
]
=> fix system muti-define when enable RT_USING_MODULE

.github/workflows/action.yml
=> fix ci install libsdl-dev error

bsp/qemu-vexpress-a9/rtconfig.py, tools/building.py, tools/options.py, tools/utils.py
可以通过如下命令在qemu直接调用musl工具链：
scons --exec-path=C:\xxx\arm-linux-musleabi_for_i686-w64-mingw32\bin --exec-prefix=arm-linux-musleabi-
[
]
=> [tools][musl] add scons --exec-prefix= 用于设置编译工具的前缀

bsp/qemu-vexpress-a9/drivers/drv_log.h, components/libc/compilers/common/ctime.c, components/lwp/lwp_syscall.c
=> [rt-smart]同步 gitee nanosleep 修复

components/drivers/serial/serial.c
=> [rt-smart] fix uart can't input after userapp exited at rv64 platform.

bsp/stm32/libraries/HAL_Drivers/drv_tim.c
=> [bug] fix tim bug

libcpu/risc-v/ch32v3/cpuport.c
[
对接了rt_hw_context_switch_interrupt函数，已经在ch32v307上测试
]
=> 对接了rthw.h的接口，修复了不能编译的问题

components/drivers/spi/sfud/README.md
https://github.com/armink/SFUD/commit/db9a1746df24142bd762378bc4e0dcf65b668b2d
[
]
=> [sfud] sync commit

components/finsh/msh.c
=> [components] fix format issue

components/drivers/sdio/mmc.c
fix compiling warning in sd/mmc.
=> [components] fix compiling warning

components/drivers/include/drivers/sensor.h, components/drivers/sensor/sensor_cmd.c
=> [sensor] 增加新传感器类型和单位

bsp/ESP32_C3/README.md, bsp/ESP32_C3/README_ZH.md, bsp/ESP32_C3/drivers/drv_gpio.c, components/finsh/msh.c
[
添加Windows安装步骤，已测试成功。删除drv_gpio.c多余的函数。修改msh.c exec函数声明的位置，如果不定义RT_USING_LWP和DFS_USING_POSIX不用声明。原来的写法导致编译报错，因为ESP32不用RT-Thread libc。
]
=> ESP32_C3: Improve Readme, fix compile errors/warnings

components/dfs/Kconfig, components/dfs/filesystems/cromfs/SConscript, components/dfs/filesystems/cromfs/dfs_cromfs.c, components/dfs/filesystems/cromfs/dfs_cromfs.h
=> [rt-smart][dfs] sync cromfs

components/dfs/src/dfs_file.c
=> add "\n" to cat

documentation/thread-comm/thread-comm.md
=> documention里的一处小问题

components/fal/src/fal_rtt.c
消除函数strtol()隐含声明的警告
[
文件《fal_rtt.c》，消除函数strtol()隐含声明的警告。
在华大hc32f460板卡上测试通过。
mdk V5.31.0.0, ArmClang V6.14.
]
- [ X] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
=> [fal] fal_rtt.c消除函数strtol()隐含声明的警告

bsp/core-v-mcu/Libraries/core_v_hal_libraries/core_v_hal/source/hal_pinmux.c, bsp/core-v-mcu/Libraries/core_v_hal_libraries/core_v_udma_driver/source/udma_cam_driver.c, bsp/core-v-mcu/Libraries/core_v_hal_libraries/core_v_udma_driver/source/udma_i2cm_driver.c, bsp/core-v-mcu/Libraries/core_v_hal_libraries/core_v_udma_driver/source/udma_qspi_driver.c, bsp/core-v-mcu/Libraries/core_v_hal_libraries/core_v_udma_driver/source/udma_sdio_driver.c
[
为了兼容原core-v-mcu工程基于FreeRTOS的驱动
在原驱动中添加rtconfig.h
qemu
]
=> [bsp][core-v-mcu]在驱动中添加rtconfig.h，以兼容原工程基于FreeRTOS的驱动

bsp/stm32/libraries/HAL_Drivers/drv_rtc.c
[
STM32F103ZET6
使用STM32F103ZET6的RTC的Alarm功能出现问题，按照原本的驱动代码编译会报错。
此前提过一次pr需要添加宏控制即可
修改底层驱动drv_rtc.c文件，通过对单片机系列的宏控制将F1系列没有的几个结构体不包括在内即可。
rtstudio及其env+mdk下对STM32F103ZET6进行测试并且成功运行Alarm功能
]
=> [对于RTC-Alarm进行添加STM32F1宏控制]

bsp/stm32/stm32l475-atk-pandora/board/ports/sensor_port.c, components/drivers/include/drivers/sensor.h, components/drivers/sensor/sensor.c, components/drivers/sensor/sensor_cmd.c
- 针对老版本sensor框架的诸多不合理设计进行重构
----------------------
之前的PR中已经重构了浮点数相关的问题
本次PR主要围绕sensor的整体架构予以重构，对过于理想化的参数和模式予以删除
老版本框架采用整形数据返回，仅能应对加减型量纲，且一旦涉及到矩阵运算（如滤波等），跟踪小数点的位数是一个很麻烦的问题。并且查看老框架的传感器对接文件，存在大量自欺欺人的行为，sensor 驱动返回的是浮点数，为了满足框架接口要求，强制转换成了整形，用户拿到整形之后还得转回浮点数。
因此新版本框架全部采用float类型（可选，默认float，也可选高精度double类型）
[
]
=> [sensor] draft new sensor-hal framework

bsp/stm32/libraries/HAL_Drivers/drv_common.c
* 未判断设置延时数是否会溢出
[
- 更新rt_hw_us_delay函数,以支持设置更高延时
- 设置延时数500MS,未更新前代码运行
- 设置延时数500MS,更新代码后运行
- 原因
us * reload的结果溢出32位,导致运行不正确.
进行更改,先除后乘,减少溢出风险.并修改tick为64位
- 更新rt_hw_us_delay函数,以支持设置更高延时
- STM32H750
- 没有判断设置的延时数是否会溢出,感觉这样子用不到溢出的情况
]
=> [STM32][common]更新rt_hw_us_delay函数,以支持设置更高延时

components/finsh/cmd.c, components/utilities/ulog/ulog.c
[
> cmd.c中list_thread等函数printf格式“%-*.s”是否有问题 https://github.com/RT-Thread/rt-thread/issues/6587
修改printf格式“%-*.s”为“%-*.*s
- 开启软件包后 和 没开软件包都可以正常显示
]
=> 修改printf格式“%-*.s”为“%-*.*s

bsp/stm32/libraries/HAL_Drivers/drv_spi.c
* 原先中断优先级不生效
[
- 修改SPI TX DMA中断优先级,原先中断优先级不生效.
- 修改SPI TX DMA中断优先级
- ART-PI
]
=> [stm32][spic]修改SPI TX DMA中断优先级

bsp/qemu-virt64-aarch64/SConstruct, bsp/qemu-virt64-aarch64/drivers/board.c, bsp/qemu-virt64-aarch64/link_smart.lds, components/drivers/serial/serial.c, components/libc/posix/io/termios/termios.c, libcpu/Kconfig, libcpu/aarch64/common/mmu.c
* [bsp][smart] fix virt64 aarch64 link script for smart.
* fix compiling warning.
=> [BSP][smart] Add link script for smart and fix Kconfig issue for smart.

src/Kconfig
RT_NAME_MAX为0是可以在nano中使用，完整版中不支持const name
[
]
=> [kernel] RT_NAME_MAX set the range from 1

bsp/allwinner/libraries/drivers/touch/drv_touch.c, bsp/nuvoton/numaker-iot-m467/board/board_dev.c, bsp/nuvoton/numaker-iot-m487/board/board_dev.c, bsp/nuvoton/numaker-m467hj/board/board_dev.c, bsp/nuvoton/numaker-pfm-m487/board/board_dev.c, bsp/stm32/stm32l475-atk-pandora/board/Kconfig, bsp/stm32/stm32l475-atk-pandora/board/ports/sensor_port.c, components/drivers/Kconfig, components/drivers/include/drivers/sensor.h, components/drivers/include/drivers/touch.h, components/drivers/sensor/sensor.c, components/drivers/sensor/sensor_cmd.c, components/drivers/touch/touch.c
=> [sensor] add sensor list command

bsp/wch/risc-v/ch32v307v-r1/applications/SConscript, bsp/wch/risc-v/ch32v307v-r1/applications/arduino_main.cpp, bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/Sconscript, bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/pins_arduino.c, bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/pins_arduino.h, bsp/wch/risc-v/ch32v307v-r1/applications/main.c, bsp/wch/risc-v/ch32v307v-r1/board/Kconfig, bsp/wch/risc-v/ch32v307v-r1/board/board.h
[
为ch32v307适配rt-duino，支持pwm、gpio、uart、iic，暂不支持 spi。
已在ch32v307评估板测试。
测试内容包括串口打印、呼吸灯、AHT10温湿度读取等。
]
=> [bsp][ch32v307]适配RT-duino框架

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
[
方便大家使用codespace 来验证代码
添加codespace container来构建环境
github codespace
【github】GITHUB 黑科技，一键搭建ubuntu rtthread qemu编译环境【codespace】
https://club.rt-thread.org/ask/article/d25fb0a88165f166.html
]
=> [tool] Add the codespace container of rt-thread

bsp/simulator/drivers/dfs_win32.c
=> 修复BUG(simulator)：修复bsp/simulator编译报错的BUG

bsp/nuvoton/libraries/ma35/rtt_port/drv_disp.c, bsp/nuvoton/libraries/ma35/rtt_port/drv_rtp.c, bsp/nuvoton/numaker-hmi-ma35d1/applications/lvgl/lv_demo.c
=> [bsp][nuvoton] modify RT_WEAK as rt_weak

components/libc/compilers/common/ctime.c
该问题之前已经修正过，但是由 https://github.com/RT-Thread/rt-thread/pull/6641/files#diff-8b967338001199acf0752ead510968f0dbe03611c79e3b3d317f3bcca8c6672e 再次引入
[
]
=> [libc][time] 修正POSIX 时间相关函数返回值错误

bsp/stm32/stm32f407-robomaster-c/applications/arduino_pinout/README.md, bsp/stm32/stm32f407-robomaster-c/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f407-robomaster-c/applications/arduino_pinout/pins_arduino.h, bsp/stm32/stm32f427-robomaster-a/applications/arduino_pinout/README.md
[
修改 arduino_pinout 文件存在的问题，完善 README
]
=> [rtduino] : fix arduino_pinout and README

src/timer.c
=> [kernel][timer] 修复在IAR下数据类型报错

tools/building.py, tools/options.py
[
https://github.com/RT-Thread/rt-thread/pull/6764
]
=> [tools] attach #6764

components/libc/compilers/common/include/sys/unistd.h, components/utilities/ulog/backend/file_be.c
https://github.com/RT-Thread/rt-thread/issues/6777
[
]
=> [libc][unistd.h] define F_OK

components/libc/compilers/common/include/sys/signal.h
[
Incompatible header file signal.h
Redirecting header sys/signal.h to signal.h
]
=> [libc] redirecting header sys/signal to signal

include/rtdbg.h
=> [dbg] add dlog macro

bsp/wch/risc-v/Libraries/ch32_drivers/drv_pwm.c, bsp/wch/risc-v/Libraries/ch32_drivers/drv_pwm.h
=> [bsp][ch32]pwm驱动补丁

components/libc/posix/ipc/mqueue.c, components/lwp/lwp_syscall.c
=> [smart] 简单适配用户态 mq

components/lwp/lwp_syscall.c
[
Fix several compiler warning messages in `lwp/lwp_syscall.c`.
]
=> [rt-smart] fix compiler warning messages

components/drivers/Kconfig, components/drivers/cputime/cputime.c, components/drivers/cputime/cputime_cortexm.c, components/drivers/cputime/cputime_riscv.c, components/drivers/include/drivers/cputime.h, components/libc/compilers/common/ctime.c
[
1. 修复ctime和原有rt-smart分支的差异。
2. 修复cputime的驱动可配置
3. 修复float数据类型溢出
]
=> fix cputime and ctime.

bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/README.md
[
：更新ch32v307的rtduino的readme文件，暂时之后中文，随后更新英文版本
更新ch32v307的rtduino的readme文件
]
=> 更新ch32v307的RTduino的readme文件

bsp/bl808/README.md, bsp/bl808/m0/applications/main.c, bsp/bl808/m0/drivers/board.c, bsp/bl808/m0/drivers/board.h, bsp/bl808/m0/drivers/drv_uart.c, bsp/bl808/m0/drivers/drv_uart.h, bsp/bl808/m0/libraries/.ignore_format.yml
[
【1】格式化driver目录文件
【2】更新bl808的README文件
开发板：m1sdock
]
=> [bsp/bl808]format file && update README.md

components/mm/SConscript
[
enable mm on armv7, armv8, rv64 only
]
=> [rt-smart/mm] enable mm on armv7, armv8, rv64 only

bsp/wch/risc-v/ch32v307v-r1/README.md, bsp/wch/risc-v/ch32v307v-r1/README_zh.md
=> [bsp] update ch32v307 readme

bsp/stm32/stm32f072-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/README.md, bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/README_zh.md, bsp/stm32/stm32f410-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f410-st-nucleo/applications/arduino_pinout/README_zh.md, bsp/stm32/stm32f411-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f411-st-nucleo/applications/arduino_pinout/README_zh.md, bsp/stm32/stm32f412-st-nucleo/applications/arduino_pinout/README.md, bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/README.md, bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/README_zh.md, bsp/wch/risc-v/ch32v208w-r0/board/Kconfig, bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/README.md, bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/README_zh.md, bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/pins_arduino.c, bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/pins_arduino.h, bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
=> [RTduino] 完善BSP readme

bsp/Infineon/libraries/templates/PSOC62/board/Kconfig
[IFX]Delete redundant templates kconfig configuration
[
]
=> [IFX]Delete redundant templates kconfig configuration

bsp/bl808/README.md
[
在 READme 中添加开发过程中可能遇到的问题及解决方案
]
=> [bsp/bl808] update: READme

bsp/stm32/libraries/HAL_Drivers/drv_adc.c
[
优化RTduino一键兼容驱动adc报错问题
stm32f103c8t6
优化RTduino一键兼容驱动adc报错问题
修改drv_adc.c文件
]
=> [BSP][stm32] fix the compile error

bsp/stm32/stm32wle5-yizhilian-lm401/rtconfig.py, bsp/stm32/stm32wle5-yizhilian-lm402/rtconfig.py
[
bsp/stm32wle5-yizhilian-lm401目录下使用scons --dist命名后缺失大量文件[详情](https://club.rt-thread.org/ask/question/43390213206423b1.html)
在rtconfig.py下补上dist_handle(BSP_ROOT, dist_dir)函数
测试通过
]
=> [bsp/stm32wle5-yizhilian-lm401/lm402]修复scons --dist缺失大量文件

bsp/stm32/libraries/HAL_Drivers/drv_soft_spi.c, bsp/stm32/libraries/HAL_Drivers/drv_soft_spi.h, bsp/stm32/stm32f407-atk-explorer/board/ports/soft_spi_flash_init.c, bsp/stm32/stm32f407-atk-explorer/board/ports/touch/drv_xpt2046_init.c, components/drivers/spi/spi-bit-ops.c
[
修改spi函数名称，并支持pin框架，已经在stm32f407-atk-explorer完成测试
]
=> [stm32][softspi]soft spi attach函数问题解决方案

bsp/stm32/libraries/HAL_Drivers/drv_qspi.c, bsp/stm32/libraries/HAL_Drivers/drv_qspi.h, bsp/stm32/stm32f469-st-disco/board/ports/drv_qspi_flash.c, bsp/stm32/stm32f746-st-disco/board/ports/drv_qspi_flash.c, bsp/stm32/stm32f767-atk-apollo/board/ports/drv_qspi_flash.c, bsp/stm32/stm32f767-fire-challenger-v1/board/ports/drv_qspi_flash.c, bsp/stm32/stm32h743-atk-apollo/board/ports/drv_qspi_flash.c, bsp/stm32/stm32h743-openmv-h7plus/board/ports/drv_qspi_flash.c, bsp/stm32/stm32h750-artpi/board/port/drv_qspi_flash.c, bsp/stm32/stm32h750-weact-ministm32h7xx/board/port/drv_qspi_flash.c, bsp/stm32/stm32l475-atk-pandora/board/ports/drv_qspi_flash.c, bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_qspi_flash.c
[
已经在stm32l475-atk-pandora bsp完成测试
]
=> [stm32][qspi] qspi attach 函数问题解决方案

src/object.c
Signed-off-by: supperthomas <78900636@qq.com>
[
https://github.com/RT-Thread/rt-thread/issues/6857
/workspaces/rt-thread/src/object.c:639: warning: argument 'type' of command @param is not found in the argument list of rt_custom_object_create(const char *name, void *data, rt_err_t(*data_destroy)(void *))
fix the comment
no need
]
=> [doxygen][src] Fix the comment in rt_custom_object_create

bsp/allwinner/d1s/mksdcard.sh
=> [D1s]Add mksdcard.sh

components/finsh/shell.c
=> Fix the comment in finsh_set_prompt_mode

include/rtdef.h
[
Add the comment of number_mask
no need
]
=> Add the comment of number_mask

components/utilities/ymodem/ry_sy.c, components/utilities/ymodem/ymodem.c
* 接收错误流程优化
[
- sy命令支持绝对路径传输
-  接收错误流程优化
]
=> [Ymodem]sy命令支持绝对路径传输

bsp/stm32/libraries/HAL_Drivers/SConscript
[
在添加指定.c文件时使用列表，只有Glob一般只用于添加批量C文件时 例如Glob('*.c')
]
=> [stm32] sconscript typo

components/drivers/sdio/block_dev.c
Fix this issue https://github.com/RT-Thread/rt-thread/issues/6874 in mmc/sdio.
Tested under qemu.
=> [DeviceDrivers] fix the partition issue in mmc/sdio

bsp/at32/libraries/rt_drivers/drv_can.c
该驱动收到can消息时，给上级返回消息结构的id和ide成员赋值不正确。
Signed-off-by: 李刚 <lg28870983@163.com>
https://gitee.com/rtthread/rt-thread/pulls/623/files
[
]
=> [at32][can]修复CAN驱动返回消息时，错误给id和ide赋值问题

tools/keil.py
[
控制勾选如下方法 工程整体设定为C99或（以及）GNU扩展
]
=> [tools][keil] 生成工程时选定C99和GNU扩展方法

components/drivers/spi/sfud/src/sfud.c
https://github.com/armink/SFUD/pull/79
[
]
=> [sfud] fix typo 

bsp/nrf5x/libraries/drivers/drv_i2c.c, bsp/nrf5x/libraries/drivers/drv_spi.c, bsp/nrf5x/libraries/drivers/drv_spi.h
[
add spi twi drv for nrf5340
Nordic nrf 5340 DK (PCA10095)
]
=> [BSP][nrf5340] add spi twi drv for nrf5340

bsp/lpc55sxx/.gitignore, bsp/lpc55sxx/Libraries/drivers/drv_i2c.c, bsp/lpc55sxx/Libraries/drivers/drv_rtc.c
1. add i2c DMA mode
2. enable rtc driver
[
LPC55S69_EVK
NXP LPC55Sxx BSP support
LPC55S69_EVK
]
=> [bsp_lpc55sxx] i2c,rtc bsp update

bsp/raspberry-pico/board/board.c, bsp/raspberry-pico/board/board.h, bsp/raspberry-pico/libcpu/SConscript, bsp/raspberry-pico/libcpu/context_gcc.S, bsp/raspberry-pico/libcpu/cpuport.c, bsp/raspberry-pico/libcpu/cpuport.h, bsp/raspberry-pico/libraries/SConscript, bsp/raspberry-pico/rtconfig.py
=> [bsp/raspberry-pico] add: SMP

src/kservice.c
=> [Kernel] Add Smart ID in logo show

components/drivers/sensor/sensor_cmd.c
命令交互应使用rt_kprintf，而非LOG_x
[
修改sensor交互时候串口输出相关函数
STMF103blue pill
修改sensor交互时候串口输出相关函数
修改sensor交互时候串口输出相关函数
]
=> [sensor] 修复命令交互使用日志输出API的问题

documentation/doxygen/.gitignore, documentation/doxygen/filesystem.h, include/rtdef.h, include/rtthread.h, src/ipc.c, src/kservice.c, src/mem.c, src/thread.c
[
#6857 
Correct the comments about warnings throwed in log. 
And the param's description from previous commits in RT-Smart branch.
Rerun, and warning disappear.
]
=> [doxygen] Fix some warnings in doxygen

bsp/lpc55sxx/lpc55s69_nxp_evk/README.md, bsp/lpc55sxx/lpc55s69_nxp_evk/README_zh.md
=> [bsp][lpc55sxx] add: README_en

components/dfs/filesystems/tmpfs/dfs_tmpfs.c
[
tmpfs不能用w模式重复打开一份文件
**musl 库代码：**
**源代码：**
由此可知是return -EEXIST;那里提前返回了，使用if代替return 即可
qemu-riscv
]
=> 🐞 fix(components/dfs/filesystems/tmpfs/dfs_tmpfs.c): fix cannot open the same file repeatedly in 'w' mode

components/libc/compilers/common/ctime.c
=> [rt-smart] 修复 aarch64 timer 地址转换问题

components/libc/compilers/common/ctime.c
=> [time] 修复纳秒微妙混用转换错误

components/drivers/cputime/cputime.c, components/drivers/include/drivers/cputime.h
=> [cputime]  add clock_cpu_settimeout function

libcpu/arm/cortex-m7/cpu_cache.c
=> [cortex-m7]rt_hw_cpu_dcache_ops函数uint32_t替换为rt_uint32_t

components/lwp/lwp_syscall.c
[
处理系统调用返回值在返回前再取errno的情况会被覆盖掉，所以应该在出错之时将错误取出来进行后续的返回。
]
=> fixed syscall errno return.

components/drivers/cputime/cputime.c, components/drivers/include/drivers/cputime.h, components/drivers/include/ipc/ringbuffer.h, components/drivers/ipc/ringbuffer.c
[
将ringbuffer支持的长度改为32位
related: https://github.com/RT-Thread/rt-thread/issues/682
]
=> [ringbuffer] ringbuffer size boost to 32bit

bsp/qemu-vexpress-a9/rtconfig.py, bsp/qemu-virt64-aarch64/rtconfig.py, bsp/qemu-virt64-riscv/rtconfig.py
=> [BSP] Add color build for qemu gcc config.

bsp/stm32/libraries/HAL_Drivers/drv_qspi.c, bsp/stm32/libraries/HAL_Drivers/drv_soft_spi.c, bsp/stm32/libraries/HAL_Drivers/drv_spi.c, components/drivers/include/drivers/spi.h, components/drivers/spi/spi_core.c
[
这个函数实现了原先的挂载功能，并且调用pin框架，初始化cs引脚，是一个功能相对完善的挂载函数。用户也能更简单的使用。
]
=> [spi]添加rt_spi_bus_attach_device_cspin 函数

components/drivers/spi/sfud/src/sfud.c, components/drivers/spi/sfud/src/sfud_sfdp.c
[
Fix typo in sfud error message
]
=> [devicedrivers] Fix typo in sfud error messages

components/drivers/fdt/inc/dtb_node.h, components/drivers/fdt/libfdt/libfdt.h, components/drivers/fdt/src/dtb_access.c, components/drivers/fdt/src/dtb_addr.c, components/drivers/fdt/src/dtb_base.c, components/drivers/fdt/src/dtb_load.c
修正FDT的编译问题，在qemu - arm/smart-arm/aarch64/smart-aarch64/riscv64/smart-riscv64 下完成编译验证。
=> [FDT] Fix POSIX compatibility for string.h

components/drivers/spi/spi_core.c
=> [spi]优化挂载函数对cs_pin的处理

components/drivers/ipc/workqueue.c
=> [revert] workqueue RT_THREAD_SUSPEND flag

components/lwp/lwp_pmutex.c
=> [lwP] fix _m_lock in posix mutex

components/drivers/fdt/inc/dtb_node.h, components/drivers/fdt/src/dtb_base.c
=> driver/fdt] add parse reg array, get address and size by index.

src/kservice.c
[
https://gitee.com/rtthread/rt-thread/pulls/618
```c
long a = 1ul << 63;
rt_kprintf("%d %ld %x %lx %u %lu %p\n", a, a, a, a, a, a, a, a, a, a);
printf("%d %ld %x %lx %u %lu %p\n", a, a, a, a, a, a, a);
a--;
rt_kprintf("%d %ld %x %lx %u %lu %p\n", a, a, a, a, a, a, a);
printf("%d %ld %x %lx %u %lu %p\n", a, a, a, a, a, a, a);
a += 2;
rt_kprintf("%d %ld %x %lx %u %lu %p\n", a, a, a, a, a, a, a);
printf("%d %ld %x %lx %u %lu %p\n", a, a, a, a, a, a, a);
int i;
int  dat = -1;
for (i = 0; i < 32; i++)
{
rt_kprintf("%b %o %x %d\n", dat, dat, dat, dat);
dat <<= 1;
}
long long dat2 = -1;
for (i = 0; i < 32; i++)
{
rt_kprintf("%#llb %#llo %#llx %lld\n", dat2, dat2, dat2, dat2);
dat2 <<= 1;
}
```
qemu
```sh
0 -9223372036854775808 0 8000000000000000 0 9223372036854775808 0x8000000000000000
0 …
```
=> fix rt_kprint 64bit error

components/drivers/include/rtdevice.h
=> update rtdevice.h add lcd

include/rtdef.h
=> [fix]避免字符设备特殊控制指令和通用控制指令冲突

bsp/lpc55sxx/Libraries/drivers/drv_pwm.c, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/SConscript, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_main.cpp, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/README.md, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/SConscript, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/pins_arduino.c, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/pins_arduino.h, bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig, bsp/lpc55sxx/lpc55s69_nxp_evk/rtconfig.py
=> [arduino][lpc55s69] : 对接RTduino

components/drivers/spi/spi_core.c
=> [spi] rt_spi_configure 增加对cs_pin处理

components/net/lwip/port/ethernetif.c, components/net/sal/Kconfig
[
[lwIP] apply AF_UNIX feature
]
=> [lwIP] apply AF_UNIX feature

components/drivers/serial/serial_v2.c
[
_serial_poll_rx/_serial_poll_tx 返回类型修改为rt_ssize_t
]
=> _serial_poll_rx/_serial_poll_tx return data type as rt_ssize_t

bsp/at32/libraries/rt_drivers/SConscript, bsp/at32/libraries/rt_drivers/drv_usart_v2.c, bsp/at32/libraries/rt_drivers/drv_usart_v2.h
=> [serial]增加at32的serial_v2驱动

bsp/Infineon/libraries/IFX_PSOC6_HAL/mtb-hal-cat1/include_pvt/cyhal_scb_common.h, bsp/Infineon/libraries/IFX_PSOC6_HAL/mtb-hal-cat1/source/cyhal_scb_common.c
=> [Infineon]Fix scb5 can't use bug

bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/README.md, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/pins_arduino.c, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/pins_arduino.h, bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
=> [rtduino][lpc55s69] 纠正uart引脚错误并使能相关依赖项

components/drivers/tty/pty.c, components/drivers/tty/tty.c
[
tty 存在bug，不能正常使用
file open时，调用device open 初始化
aarch64 qemu
]
=> 🐞 fix(components/drivers/tty/pty.c): fix ptmx not init

components/drivers/cputime/cputimer.c
=> [cputimer] 解决关中断时进行了调度的误操作

components/lwp/lwp_syscall.c, components/net/sal/impl/af_inet_lwip.c
[
- 修复fstat、stat等系统调用
- 修复socket对于musl工具链的fcntl系统调用的适配
]
=> Fix syscall

bsp/wch/risc-v/Libraries/ch32_drivers/drv_usart.c
[
修复了在一个编译过程中出现的警告，其原因是因为串口驱动集函数使用了不合理的定义，在win11上编译成功
]
=> [ch32][bsp] fix warning: rt_size_t to rt_ssize_t 

libcpu/aarch64/common/backtrace.c, libcpu/aarch64/common/backtrace.h
add `rt_backtrace` function in aarch64.
=> [libcpu.aarch64] add rt_backtrace function.

bsp/stm32/libraries/HAL_Drivers/drv_qspi.c, bsp/stm32/libraries/HAL_Drivers/drv_spi.c, components/drivers/include/drivers/spi.h, components/drivers/spi/spi-bit-ops.c, components/drivers/spi/spi_core.c
=> [spi] 优化SPI设备框架中，对函数返回值类型使用不恰当的情况

bsp/lpc55sxx/Libraries/drivers/drv_hwtimer.c, bsp/lpc55sxx/Libraries/drivers/drv_pwm.c, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/pins_arduino.c
=> [lpc55s69] : fix the pwm driver with the wrong device name

bsp/at32/libraries/rt_drivers/drv_usbd.c, bsp/at32/libraries/rt_drivers/drv_usbd.h, bsp/at32/libraries/rt_drivers/drv_usbfs.h, bsp/at32/libraries/rt_drivers/drv_usbfsd.c, bsp/at32/libraries/rt_drivers/drv_usbfsh.c, bsp/at32/libraries/usbd_library/inc/usb_std.h, bsp/at32/libraries/usbd_library/inc/usbd_core.h, bsp/at32/libraries/usbd_library/inc/usbd_int.h, bsp/at32/libraries/usbd_library/inc/usbd_sdr.h, bsp/at32/libraries/usbd_library/src/usbd_core.c, bsp/at32/libraries/usbd_library/src/usbd_int.c, bsp/at32/libraries/usbd_library/src/usbd_sdr.c, bsp/at32/libraries/usbfs_library/inc/usb_std.h, bsp/at32/libraries/usbfs_library/inc/usbd_int.h, bsp/at32/libraries/usbfs_library/inc/usbd_sdr.h, bsp/at32/libraries/usbfs_library/inc/usbh_ctrl.h, bsp/at32/libraries/usbfs_library/inc/usbh_int.h, bsp/at32/libraries/usbfs_library/src/usbd_core.c, bsp/at32/libraries/usbfs_library/src/usbd_int.c, bsp/at32/libraries/usbfs_library/src/usbd_sdr.c, bsp/at32/libraries/usbfs_library/src/usbh_core.c, bsp/at32/libraries/usbfs_library/src/usbh_ctrl.c, bsp/at32/libraries/usbfs_library/src/usbh_int.c
[
[bsp/at32] fixed gcc compiling usb driver errors
]
=> [bsp/at32] fixed gcc compiling usb driver errors

bsp/qemu-virt64-aarch64/.vscode/launch.json, bsp/qemu-virt64-aarch64/.vscode/smart.json
Add vscode setting for qemu-virt64-aarch64 (build/clean/debug).
=> [BSP] Add vscode setting.

components/lwp/lwp_syscall.c, src/Kconfig
=> [smart] smart select POSIX timer clock

src/memheap.c
Fix the alignment issue for memheap when using 64bit env.
=> [Kernel] Fix the alignment issue for memheap.

bsp/lpc55sxx/Libraries/drivers/drv_pwm.c, bsp/lpc55sxx/Libraries/drivers/drv_pwm.h, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/pins_arduino.c, bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig, bsp/lpc55sxx/lpc55s69_nxp_evk/board/MCUX_Config/board/pin_mux.c, bsp/lpc55sxx/lpc55s69_nxp_evk/board/MCUX_Config/board/pin_mux.h
=> [bsp][lpc55sxx] re-organize PWM driver

bsp/wch/risc-v/Libraries/ch32_drivers/drv_usart.c
[
将空函数的返回值有RT_EOK改为-RT_ENOENT，测试编译通过
]
=> [bsp][ch32]更改了空函数的返回值

src/timer.c
Reverts RT-Thread/rt-thread#6804
=> Revert "[kernel][timer] 修复在IAR下数据类型报错"

bsp/stm32/libraries/HAL_Drivers/drv_lcd.c
[
fix stm32 drv_lcd some problem
修改:
* LTDC：将 Alpha 通道默认设置为0（完全透明）
* rt_malloc 替换为 rt_malloc_align
]
=> fix stm32 drv_lcd some problem

bsp/renesas/ra6m3-ek/board/lvgl/lv_port_disp.c, bsp/renesas/ra6m3-ek/board/ports/SConscript
[
Fix ra6m3 add lvgl build error problem
]
=> [Renesas]Fix add lvgl build error problem

bsp/lpc55sxx/tools/sdk_dist.py
[
- scons --dist复制不全
- 修改了sdk_dist.py，增加了对CMSIS的复制
- scons --dist测试成功，能在导出的工程里成功编译
]
=> [bsp][lpc55sxx]添加了scons --dist复制不全的解决方案

.github/workflows/action.yml, bsp/lpc55sxx/lpc55s06_nxp_evk/rtconfig.py, bsp/lpc55sxx/lpc55s16_nxp_evk/rtconfig.py, bsp/lpc55sxx/lpc55s28_nxp_evk/rtconfig.py, bsp/lpc55sxx/lpc55s36_nxp_evk/rtconfig.py
add CPU define for S06/S16/S29/S36 make GCC comiple pass
[
]
=> [bsp][lpc55sxx] add CPU define for S06/S16/S29/S36 make GCC comiple pass

components/mm/avl_adpt.h, components/mm/mm_aspace.c, components/mm/mm_flag.h, components/utilities/libadt/avl.c, examples/test/avl.c, libcpu/aarch64/common/mmu.c
[
* [fix] implementation fault of avl just degrade binary search tree to linked list and not being noticed
* [fix] mm varea may be freed by calling to rt_free() even they are statically allocated
]
=> [fix] mm bugs

bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_conf.h, bsp/stm32/stm32f469-st-disco/applications/lvgl/lv_port_disp.c
[
Fix f469 touch build error and set lvgl to double buffer
]
=> [STM32]Fix f469 touch build error and set lvgl to double buffer

tools/vsc.py
[
支持在bsp下面加入所有涉及到的.c和.h 包括上一级src文件夹下面的文件
添加workspace文件，直接打开即可
workspace文件直接用vsoce打开即可
]
=> [tools][vsc] Add the workspace of vscode

bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_main.cpp, bsp/stm32/stm32f072-st-nucleo/applications/arduino_main.cpp, bsp/stm32/stm32f103-blue-pill/applications/arduino_main.cpp, bsp/stm32/stm32f401-st-nucleo/applications/arduino_main.cpp, bsp/stm32/stm32f410-st-nucleo/applications/arduino_main.cpp, bsp/stm32/stm32f411-st-nucleo/applications/arduino_main.cpp, bsp/stm32/stm32f411-weact-blackpill/applications/arduino_main.cpp, bsp/stm32/stm32l431-BearPi/applications/arduino_main.cpp, bsp/wch/risc-v/ch32v208w-r0/applications/arduino_main.cpp, bsp/wch/risc-v/ch32v208w-r0/applications/arduino_pinout/pins_arduino.h, bsp/wch/risc-v/ch32v307v-r1/applications/arduino_main.cpp
=> [bsp][rtduino] update arduino_main.cpp

bsp/nuvoton/libraries/m480/StdDriver/inc/nu_fmc.h
Remove redundant 'extern' in function declaration
[
Remove redundant 'extern' in function declaration
just remove it.
]
=> [bsp] Remove redundant 'extern' in function declaration

libcpu/risc-v/readme.md
=> [libcpu/risc-v]更新移植readme

components/net/lwip/port/lwipopts.h
[
修复 LWIP_HOOK_IP4_ROUTE_SRC 在不同版本的定义
]
=> [net] fix LWIP_HOOK_IP4_ROUTE_SRC define

bsp/lpc54114-lite/drivers/drv_i2c.c, components/drivers/i2c/i2c_core.c, components/drivers/include/drivers/i2c.h
=> [i2c] fix the i2c device return error code

components/dfs/src/dfs.c, components/lwp/lwp_futex.c, components/lwp/lwp_pmutex.c, components/lwp/lwp_sys_socket.h, components/lwp/lwp_syscall.c, components/lwp/lwp_syscall.h, components/lwp/syscall_generic.h, include/rtdef.h
[
* [fix] return type of syscall should be compatible in size to `long`
* [fix] `errno` should be recycle immediately after call to RT POSIX layer to avoid outdated value
]
=> [rt-smart] Fix return value in syscall

bsp/renesas/libraries/HAL_Drivers/drv_spi.c, bsp/renesas/libraries/HAL_Drivers/drv_spi.h, bsp/renesas/ra6m4-cpk/board/Kconfig, bsp/renesas/ra6m4-cpk/board/lvgl/SConscript, bsp/renesas/ra6m4-cpk/board/lvgl/demo/SConscript, bsp/renesas/ra6m4-cpk/board/lvgl/demo/lv_demo.c, bsp/renesas/ra6m4-cpk/board/lvgl/lv_conf.h, bsp/renesas/ra6m4-cpk/board/lvgl/lv_port_disp.c, bsp/renesas/ra6m4-cpk/board/lvgl/lv_port_indev.c, bsp/renesas/ra6m4-cpk/board/ports/SConscript, bsp/renesas/ra6m4-cpk/board/ports/drv_rw007.c, bsp/renesas/ra6m4-cpk/board/ports/ili9341/SConscript, bsp/renesas/ra6m4-cpk/board/ports/ili9341/lcd_ili9341.c, bsp/renesas/ra6m4-cpk/board/ports/ili9341/lcd_ili9341.h, bsp/renesas/ra6m4-cpk/board/ports/lcd_port.h, bsp/renesas/ra6m4-cpk/ra_cfg/fsp_cfg/bsp/board_cfg.h, bsp/renesas/ra6m4-cpk/ra_cfg/fsp_cfg/bsp/bsp_cfg.h
[
Add ra6m4-cpk lvgl for spi-lcd support
]
=> [Renesas]Add ra6m4-cpk lvgl for spi-lcd support

bsp/README.md
[
bsp 太多，各个厂商太分散，不易管理
添加readme 把不同厂商的bsp文件夹放到一起，便于大家查看
排名不分先后，按MCU的芯片生产厂商区分
]
=> [bsp] Add bsp readme

components/mm/ioremap.c, components/mm/ioremap.h
[
`rt_ioremap`  的内存映射属性 `MMU_MAP_K_DEVICE` ，在64位处理器上，映射后的内存地址需要8字节对齐，4字节对齐的内存地址内存操作，容易出现 内存对齐异常
增加 `rt_ioremap_wt` 接口，映射内存属性：`MMU_MAP_K_RW`，经过验证映射后的内存可以正常读写操作，未出现内存对齐异常，普通的内存映射接口，可以调用 `rt_ioremap_wt` 来实现
在 aarch64 平台上验证通过
]
=> [components][mm] add ioremap for normal memory api

bsp/hk32/libraries/rt_drivers/drv_gpio.c
=> [error code][RT_EOK] fix RT_EOK with -

bsp/mm32f327x/drivers/Kconfig, bsp/mm32f327x/drivers/SConscript, bsp/mm32f327x/drivers/drv_adc.c, bsp/mm32f327x/drivers/drv_adc.h
[
你好这是我第一次提交PR，我也不知道这样能不能成功通过，就是先试试，如果有操作不当，请见谅！
使用mm32f327x的bsp时想通过rtt的adc driver使用adc。
所以从mm32官方的adc代码移植过来。
在keil下已经测试过adc1 和adc2 可以正常使用。
]
- [ x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
=> add drv_adc  to mm32f327x

bsp/stm32/libraries/HAL_Drivers/drv_gpio.c
=> [stm32][pin] 修复GPIO驱动警告

bsp/stm32/libraries/HAL_Drivers/drv_adc.c
=> [stm32][adc] add error code return

README.md, README_de.md, README_es.md, README_zh.md
=> Update RISC-V description

components/drivers/include/drivers/mtd_nor.h, components/drivers/mtd/mtd_nor.c
[
修改mtd_nor读写函数返回类型为rt_ssize_t
修改mtd_nor读写函数返回类型为rt_ssize_t
]
=> [device]修改mtd_nor读写函数返回类型为rt_ssize_t

bsp/apm32/libraries/Drivers/drv_adc.c, bsp/apm32/libraries/Drivers/drv_rtc.c, bsp/mini4020/drivers/sdcard.c, bsp/n32g452xx/Libraries/rt_drivers/drv_spi.c, bsp/renesas/libraries/HAL_Drivers/drv_sdhi.c, bsp/stm32/libraries/HAL_Drivers/drv_crypto.c, bsp/stm32/stm32h750-artpi/board/port/drv_eth.c, bsp/stm32/stm32mp157a-st-discovery/board/ports/drv_eth.c, bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_nand.c, bsp/stm32/stm32mp157a-st-ev1/board/ports/eth/drv_eth.c, components/drivers/ipc/dataqueue.c, components/drivers/spi/spi_msd.c, documentation/thread-comm/thread-comm.md
=> [errno code][-RT_ETIMEOUT] fix that use RT_ETIMEOUT without -

bsp/Infineon/libraries/HAL_Drivers/drv_gpio.c, bsp/Vango/v85xx/drivers/drv_gpio.c, bsp/Vango/v85xxp/drivers/drv_gpio.c, bsp/acm32/acm32f0x0-nucleo/drivers/drv_gpio.c, bsp/acm32/acm32f4xx-nucleo/drivers/drv_gpio.c, bsp/apm32/libraries/Drivers/drv_gpio.c, bsp/essemi/es32f0654/drivers/drv_gpio.c, bsp/essemi/es32f369x/drivers/drv_gpio.c, bsp/fm33lc026/libraries/HAL_Drivers/drv_gpio.c, bsp/ft32/libraries/Drivers/drv_gpio.c, bsp/gd32vf103v-eval/drivers/drv_gpio.c, bsp/hc32/libraries/hc32_drivers/drv_gpio.c, bsp/hc32l136/drivers/drv_gpio.c, bsp/mm32/libraries/HAL_Drivers/drv_gpio.c, bsp/n32/libraries/n32_drivers/drv_gpio.c, bsp/nrf5x/libraries/drivers/drv_gpio.c, bsp/nuclei/libraries/gd32vf103/HAL_Drivers/drv_gpio.c, bsp/nuvoton/libraries/m460/rtt_port/drv_eadc.c, bsp/renesas/libraries/HAL_Drivers/drv_gpio.c, bsp/rockchip/common/drivers/drv_gpio.c, components/drivers/serial/serial.c
=> [errno code][-RT_EBUSY] fix that use RT_EBUSY without -

tools/mkdist.py
like:scons --dist --target=mdk5 --project-name=hello --project-path=C:\Users\xxx\Desktop\test 
scons --dist [--target=xxx] [--project-name=xxx] [--project-path=xxx] 
支持在dist之后，将dist出来的工程直接生成为目标工程，相当于自动执行scons --target=xxx
related issue: https://github.com/RT-Thread/rt-thread/issues/6955
related PR: https://github.com/RT-Thread/rt-thread/pull/6713 https://github.com/RT-Thread/rt-thread/pull/6649
[
]
=> [tools] support scons --dist --target=xxx

bsp/wch/arm/Libraries/ch32_drivers/drv_gpio_ch32f10x.c, bsp/wch/arm/Libraries/ch32_drivers/drv_gpio_ch32f20x.c
=> [errno code]fix that use RT_EEMPTY without -

bsp/at32/libraries/rt_drivers/drv_qspi.c, bsp/ft2004/drivers/drv_qspi.c, bsp/ft2004/drivers/drv_sdctrl.c, bsp/loongson/ls1cdev/drivers/touch.c, bsp/mini4020/drivers/sdcard.c, bsp/nrf5x/libraries/drivers/drv_gpio.c, bsp/stm32/libraries/HAL_Drivers/drv_qspi.c, components/drivers/ipc/dataqueue.c, components/drivers/usb/usbhost/core/usbhost_core.c, components/utilities/ymodem/ry_sy.c
=> [errno code]fix that use RT_ENOMEM without -

README.md, README_zh.md
【修改】为README.md开发文档修改了[Kendryte]为[Canaan Kendryte]描述 【修改】为README_zh.md开发文档修改了Hifive为sifive描述
【修改】为README_zh.md开发文档修改了[Kendryte]为[嘉楠Kendryte]描述
[
]
=> 【修改】为README.md开发文档修改了Hifive为sifive描述

.github/workflows/action.yml, bsp/bouffalo_lab/bl60x/board/SConscript, bsp/bouffalo_lab/bl61x/board/SConscript, bsp/bouffalo_lab/bl70x/board/SConscript, bsp/bouffalo_lab/bl808/lp/board/SConscript, bsp/bouffalo_lab/bl808/m0/board/SConscript, bsp/bouffalo_lab/bl808/m0/board/board.c, bsp/bouffalo_lab/libraries/bl_mcu_sdk/drivers/lhal/SConscript, bsp/bouffalo_lab/libraries/bl_mcu_sdk/drivers/lhal/src/bflb_ef_ctrl.c, bsp/bouffalo_lab/libraries/bl_mcu_sdk/drivers/lhal/src/bflb_flash.c, bsp/bouffalo_lab/libraries/bl_mcu_sdk/drivers/lhal/src/flash/bflb_sf_ctrl.c, bsp/bouffalo_lab/libraries/rt_drivers/Kconfig, bsp/bouffalo_lab/libraries/rt_drivers/drv_uart.c
1、update bl_mcu_sdk SConscript && add bl808 uart2 driver
2、add bl60x/bl70x bsp to ci-action
[
]
=> [bsp]add bl808 uart2 driver && add bl60x/bl70x bsp to ci-action

components/libc/posix/delay/delay.c
[
fix bugs in usleep function
correct it
]
=> [libc][delay] fix wrong usleep function

bsp/ESP32_C3/rtt.patch, libcpu/risc-v/common/trap_common.c
[
修复esp32_c3编译错误
1、更新rtt.patch
2、更新package
]
=> [bsp]fix esp32_c3 compile error

src/SConscript, src/scheduler_mp.c, src/scheduler_up.c
[
拆分 scheduler.c  针对单核大多数场合只看到单核的代码；针对多核时，才会看到更多多核的代码。
拆分为 scheduler upc 和 scheduler_mp.c 两部分
qemu-vexpress-a9
]
=> [src][scheduler] Split scheduler.c into scheduler upc and scheduler_mp.c

bsp/Infineon/libraries/HAL_Drivers/drv_spi.c, bsp/Infineon/psoc6-evaluationkit-062S2/board/Kconfig
=> [Infineon]Fix spi cs problem

components/libc/posix/delay/delay.c
=> [libc]优化usleep函数

bsp/Infineon/libraries/HAL_Drivers/drv_gpio.c, bsp/Infineon/libraries/HAL_Drivers/drv_pwm.c, bsp/Infineon/libraries/HAL_Drivers/drv_pwm.h, bsp/Infineon/psoc6-evaluationkit-062S2/applications/main.c, bsp/Infineon/psoc6-evaluationkit-062S2/board/Kconfig, bsp/Infineon/psoc6-evaluationkit-062S2/board/ports/slider_sample.c
=> [Infineon]Add slider driver demo

bsp/mm32f327x/drivers/drv_adc.c, bsp/raspberry-pi/raspi4-64/drivers/drv_eth.c, bsp/raspberry-pi/raspi4-64/drivers/drv_sdio.c, bsp/raspberry-pi/raspi4-64/drivers/drv_spi.c, bsp/raspberry-pi/raspi4-64/drivers/drv_wdt.c
=> {bsp] Modify the RT_Exxx error return value to a negative number

libcpu/arm/cortex-a/start_gcc.S
=> [libcpu/arm/cortex-a] Revert safety MMU initialization.

components/dfs/filesystems/devfs/devfs.c, components/dfs/filesystems/tmpfs/dfs_tmpfs.c, components/dfs/src/dfs_posix.c, components/libc/compilers/common/include/sys/statfs.h, components/libc/compilers/common/include/sys/utsname.h, components/lwp/lwp.c, components/lwp/lwp_syscall.c, include/rthw.h, libcpu/aarch64/common/cpu.c, src/kservice.c
[
修复并添加部分系统调用
修复：fstat
增加：lstat, uname, statfs, statfs64, fstatfs, fstatfs64
qemu
]
=> Fix syscall dev

bsp/at91/at91sam9260/link_scripts/at91sam9260_ram.ld
[
https://github.com/RT-Thread/rt-thread/issues/6594
]
=> [at91sam9260] modify link_scripts to fix #6594

bsp/renesas/ra6m3-ek/board/lvgl/lv_port_disp.c, bsp/renesas/ra6m3-ek/buildinfo.gpdsc, bsp/renesas/ra6m4-cpk/board/lvgl/lv_port_disp.c, bsp/renesas/ra6m4-cpk/buildinfo.gpdsc, bsp/renesas/ra6m4-cpk/configuration.xml, bsp/renesas/ra6m4-cpk/ra_cfg/fsp_cfg/bsp/board_cfg.h, bsp/renesas/ra6m4-cpk/ra_cfg/fsp_cfg/bsp/bsp_cfg.h, bsp/renesas/ra6m4-cpk/ra_gen/pin_data.c, bsp/renesas/ra6m4-cpk/template.uvoptx, bsp/renesas/ra6m4-cpk/template.uvprojx
=> [Renesas]Update RA6M3/4 mdk proj

bsp/nuvoton/libraries/m031/rtt_port/drv_gpio.c, bsp/nuvoton/libraries/m031/rtt_port/drv_usbd.c, bsp/nuvoton/libraries/m2354/rtt_port/drv_gpio.c, bsp/nuvoton/libraries/m2354/rtt_port/drv_qspi.c, bsp/nuvoton/libraries/m2354/rtt_port/drv_spi.c, bsp/nuvoton/libraries/m2354/rtt_port/drv_usbd.c, bsp/nuvoton/libraries/m460/rtt_port/drv_gpio.c, bsp/nuvoton/libraries/m460/rtt_port/drv_qspi.c, bsp/nuvoton/libraries/m460/rtt_port/drv_spi.c, bsp/nuvoton/libraries/m460/rtt_port/drv_usbd.c, bsp/nuvoton/libraries/m480/rtt_port/drv_gpio.c, bsp/nuvoton/libraries/m480/rtt_port/drv_qspi.c, bsp/nuvoton/libraries/m480/rtt_port/drv_spi.c, bsp/nuvoton/libraries/m480/rtt_port/drv_usbd.c, bsp/nuvoton/libraries/ma35/rtt_port/drv_common_aarch32.c, bsp/nuvoton/libraries/ma35/rtt_port/drv_gpio.c, bsp/nuvoton/libraries/ma35/rtt_port/drv_qspi.c, bsp/nuvoton/libraries/ma35/rtt_port/drv_spi.c, bsp/nuvoton/libraries/ma35/rtt_port/gmac/drv_gmac.c, bsp/nuvoton/libraries/n9h30/rtt_port/drv_gpio.c, bsp/nuvoton/libraries/n9h30/rtt_port/drv_qspi.c, bsp/nuvoton/libraries/n9h30/rtt_port/drv_usbd.c, bsp/nuvoton/libraries/nu_packages/ADC_TOUCH/adc_touch.c, bsp/nuvoton/libraries/nuc980/rtt_port/drv_gpio.c, bsp/nuvoton/libraries/nuc980/rtt_port/drv_qspi.c, bsp/nuvoton/libraries/nuc980/rtt_port/drv_spi.c, bsp/nuvoton/libraries/nuc980/rtt_port/drv_usbd.c
[
Sync-up upstream.
Fix warning & building.
]
=> [nuvoton] Update fix warnings and builds.

include/rtdef.h, src/Kconfig
=> change version number to v5.1.0

bsp/acm32/acm32f4xx-nucleo/libraries/Device/ACM32F4.h, bsp/acm32/acm32f4xx-nucleo/libraries/Device/System_ACM32F4.c, bsp/acm32/acm32f4xx-nucleo/libraries/HAL_Driver/Inc/HAL_AES.h, bsp/acm32/acm32f4xx-nucleo/libraries/HAL_Driver/Inc/HAL_FAU.h, bsp/acm32/acm32f4xx-nucleo/libraries/HAL_Driver/Inc/HAL_RTC.h, bsp/acm32/acm32f4xx-nucleo/libraries/HAL_Driver/Inc/HAL_UART.h, bsp/acm32/acm32f4xx-nucleo/libraries/HAL_Driver/Src/HAL_DAC.c, bsp/acm32/acm32f4xx-nucleo/libraries/HAL_Driver/Src/HAL_FSUSB.c, bsp/acm32/acm32f4xx-nucleo/libraries/HAL_Driver/Src/HAL_GPIO.c
=> [bsp] Fix many abnormal symbols in annotations. 

components/drivers/fdt/src/dtb_base.c
fix the compiling warning of dtb under 64bit env.
=> [components] fix dtb compiling warning.

include/rtdef.h, src/Kconfig
=> change version number to v5.0.1

bsp/airm2m/air105/libraries/HAL_Driver/Inc/air105_otp.h, bsp/airm2m/air105/libraries/HAL_Driver/Inc/air105_sensor.h, bsp/airm2m/air105/libraries/HAL_Driver/Inc/air105_ssc.h, bsp/airm2m/air32f103/libraries/AIR32F10xLib/src/air32f10x_trng.c, bsp/allwinner/libraries/sunxi-hal/hal/source/g2d_rcq/g2d_driver.h, bsp/allwinner/libraries/sunxi-hal/hal/source/g2d_rcq/g2d_scal.c, bsp/allwinner/libraries/sunxi-hal/hal/source/usb/include/usb_os_platform.h, bsp/allwinner/libraries/sunxi-hal/hal/source/usb/storage/Class/mscTransport.c, bsp/allwinner/libraries/sunxi-hal/hal/source/usb/storage/Class/usb_msc.c, bsp/allwinner/libraries/sunxi-hal/include/hal/sdmmc/mbr.h
[
在静态扫描、代码审计该模块时遇到了无法读取的字符，发现是注释中的中文乱码了，于是顺便将其修复，并提交PR
通过阅读还原原本注释解决无法阅读的注释乱码
只修改了注释，不影响编译运行
]
=> [bsp]Fix Chinese coding errors in annotations.

documentation/thread/thread.md
[
在阅读RT-Thread API参考手册时，关注到对于rt_thread_resume函数的介绍不够准确。
依据rt_thread_resume函数源码，系统只是将线程丢入就绪队列中，如果被恢复线程是就绪队列中优先级最高的，系统并不会直接进行上下文的切换，原文“if the recovered thread is first in place of the priority list, then the system will start context switching.”并不准确，因此删除。可通过源码证实。
```c
rt_err_t rt_thread_resume(rt_thread_t thread)
{
rt_base_t level;
/* parameter check */
RT_ASSERT(thread != RT_NULL);
RT_ASSERT(rt_object_get_type((rt_object_t)thread) == RT_Object_Class_Thread);
RT_DEBUG_LOG(RT_DEBUG_THREAD, ("thread resume:  %s\n", thread->name));
if ((thread->stat & RT_THREAD_SUSPEND_MASK) != RT_THREAD_SUSPEND_MASK)
{
RT_DEBUG_LOG(RT_DEBUG_THREAD, ("thread resume: thread disorder, %d\n",
thread->stat));
return -RT_ERROR;
}
/* disable interrupt */
level = rt_hw_interrupt_disable();
/* remove from suspend list …
```
=> revise the description of rt_thread_resume

bsp/stm32/stm32f411-st-nucleo/template.uvoptx, bsp/stm32/stm32f411-st-nucleo/template.uvprojx
[
STM32f411-st-nucleo原本的template.uvprojx版本太老了，添加新软件包后使用env编译会产生报错，更新模板工程即可解决
]
=> [bsp][stm32] update the template.uvprojx for stm32f411-st-nucleo

bsp/stm32/libraries/HAL_Drivers/drv_tim.c
[
Found `TIM1` and `TIM8` also in **ABP2**.
ref: Table 1 on page 66
https://www.st.com/resource/en/reference_manual/rm0090-stm32f405415-stm32f407417-stm32f427437-and-stm32f429439-advanced-armbased-32bit-mcus-stmicroelectronics.pdf
Add new conditions.
]
=> [HUST CSE IoTS&P Lab][fix] add `TIM1` and `TIM8`

components/net/at/src/at_client.c
1. prevent null-pointer dereference in rt_strcmp
[
`at_client_init` 会使用到 `at_client_get` 来检测设备名称是否已经注册
但是`at_client_get`函数中比较设备名时，`at_client_table[idx].device` 没有被检查是否合法（不是空指针），最终可能导致在 `rt_strcmp` 中出现空指针解引用的问题
```c
int at_client_init(const char *dev_name,  rt_size_t recv_bufsz)
{
... 
// 这里使用到了该函数
if (at_client_get(dev_name) != RT_NULL)
{
return result;
}
}
at_client_t at_client_get(const char *dev_name)
{
int idx = 0;
RT_ASSERT(dev_name);
for (idx = 0; idx < AT_CLIENT_NUM_MAX; idx++)
{
// 这里没有对device指针进行检查
if (rt_strcmp(at_client_table[idx].device->parent.name, dev_name) == 0)
{
return &at_client_table[idx];
}
}
```
检查空指针后再进行比对
]
=> [HUST CSE] [AT] Add null pointer check in at_client_get

bsp/CME_M7/StdPeriph_Driver/inc/cmem7_usb.h, bsp/allwinner/libraries/sunxi-hal/hal/source/ccmu/sunxi-ng/ccu.h, bsp/allwinner/libraries/sunxi-hal/hal/source/regulator/type.h, bsp/allwinner/libraries/sunxi-hal/hal/source/spinor/inter.h, bsp/allwinner_tina/drivers/drv_sdio.h, bsp/bluetrum/libraries/hal_libraries/bmsis/include/ab32vgx.h, bsp/qemu-virt64-aarch64/drivers/drv_gpio.c, bsp/stm32/stm32mp157a-st-discovery/board/ports/drv_pmic.h, bsp/stm32/stm32mp157a-st-ev1/board/ports/drv_pmic.h
[
通过阅读 BIT 实际位移的位数，发现部分宏定义没有设置为无符号整数，但确实存在引用的时候超过位宽的可能性。还有一个宏定义的变量未添加括号。
第二个commit中的 UL 是我认为添加与不添加都可以接受的。
为 BIT 宏定义分别添加了UL。
All.
]
=> [HUST CSE IoTS&P Lab][bsp] add missing UL suffix to BIT macro to prevent undefined behavior

bsp/at32/libraries/rt_drivers/drv_qspi.c, bsp/at32/libraries/rt_drivers/drv_qspi.h
=> [bsp/at32] remove #ifndef

bsp/allwinner/libraries/sunxi-hal/hal/source/sound/component/aw-alsa-utils/aduplex.c, bsp/nuvoton/libraries/m031/rtt_port/drv_fmc.c, bsp/nuvoton/libraries/m2354/rtt_port/drv_fmc.c, bsp/nuvoton/libraries/nu_packages/Demo/smp_demo.c, components/drivers/tty/n_tty.c, components/lwp/lwp_syscall.c
[
发现 rt_mutex_create 函数调用后可能出现指针为空的情况
对返回值进行判断是否为 RT_NULL
all
]
=> [HUST CSE IoTS&P Lab] [fix] check rt_mutex_create return value

bsp/renesas/ra6m3-ek/board/lvgl/lv_conf.h, bsp/renesas/ra6m4-cpk/board/lvgl/lv_conf.h
=> [Renesas]Fix lvgl screen define

bsp/Infineon/psoc6-evaluationkit-062S2/applications/lvgl/SConscript, bsp/Infineon/psoc6-evaluationkit-062S2/applications/lvgl/demo/SConscript, bsp/Infineon/psoc6-evaluationkit-062S2/applications/lvgl/demo/lv_demo.c, bsp/Infineon/psoc6-evaluationkit-062S2/applications/lvgl/lv_conf.h, bsp/Infineon/psoc6-evaluationkit-062S2/applications/lvgl/lv_port_disp.c, bsp/Infineon/psoc6-evaluationkit-062S2/applications/lvgl/lv_port_indev.c, bsp/Infineon/psoc6-evaluationkit-062S2/board/Kconfig
[
添加psoc系列对lvgl的支持
]
- [] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)
=> [Infineon]Add lvgl support

bsp/simulator/applications/lvgl/win32drv.c, bsp/simulator/applications/lvgl/win32drv.h
https://github.com/lvgl/lv_drivers/commit/94dc4ce06c9bae2b415618a883d52be7c7f5d595
[
]
=> [lvgl][simulator] sync upstream win32 driver

tools/building.py, tools/gcc.py
有段代码被注释，不理解意图
完善注释说明，避免其他人也遇到该问题
scons 通过
]
=> [tools] update the comment for old gen cconfig.h code.

bsp/n32g452xx/Libraries/N32_Std_Driver/n32g45x_std_periph_driver/inc/n32g45x_dvp.h
[
头文件bsp/n32g452xx/Libraries/N32_Std_Driver/n32g45x_std_periph_driver/inc/n32g45x_dvp.h中对extern "C" 漏了花括弧 ,导致所有包含该头文件的C++文件出现编译错误。
]
=> [bsp/n32g452xx] 修复会导致C++文件编译错误的头文件错误

bsp/CME_M7/drivers/app_phy.c, bsp/Infineon/libraries/HAL_Drivers/drv_adc.c
[
一下两个文件中的printf函数输出格式与变量类型不对应
将%d修改为%u或将%ld修改为%lu以输出正确格式的整数
all
]
=> 规范输出函数（printf）变量的类型

tools/gcc.py
=> [tools] comment out GenerateGCCConfig revert part of #7177

.github/workflows/static_code_analysis.yml
[
添加静态代码检查，帮助检查PR中的warning。
添加cppcheck 到action中。
cppcheck检查一些数组代码越界等错误，如果出现错误，review者可以根据错误类型，查看是否需要修改。会对.c 和.cpp文件进行检查
]
=> [action][github] Add the cppcheck help check the PR warning

bsp/stm32/libraries/HAL_Drivers/SConscript, bsp/stm32/libraries/HAL_Drivers/drv_sdmmc.c, bsp/stm32/libraries/HAL_Drivers/drv_sdmmc.h
[
[bsp][stm32]添加SDMMC驱动,以区分SDIO与SDMMC 
详细情况看:https://github.com/RT-Thread/rt-thread/issues/7088
STM32的drv_sdio驱动分为sdio驱动和sdmmc驱动
- H7,F7等SDMMC驱动仅加载drv_sdmmc文件,SDIO驱动加载drv_sdio文件
- ART-PI ;STM32H750
- SD卡
]
=> [bsp][stm32]添加SDMMC驱动,以区分SDIO与SDMMC

bsp/stm32/libraries/HAL_Drivers/config/f0/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/f1/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/f2/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/f3/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/f4/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/f7/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/g0/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/g4/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/h7/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/l1/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/l4/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/l5/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/mp1/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/u5/pwm_config.h, bsp/stm32/libraries/HAL_Drivers/config/wb/pwm_config.h
=> [bsp][stm32] 完善STM32系列 pwm_config.h文件

bsp/stm32/libraries/HAL_Drivers/drv_adc.c, components/drivers/include/drivers/adc.h, components/drivers/misc/adc.c
[
ADC设备框架增加特殊内部adc通道号标准宏，防止不同bsp因为内部通道编码不一致导致上层无法通用。
```c
#define RT_ADC_INTERN_CH_TEMPER     (-1)
#define RT_ADC_INTERN_CH_VREF       (-2)
#define RT_ADC_INTERN_CH_VBAT       (-3)
```
此外 STM32的ADC驱动在L4系列中获取片内通道存在，以及获取流程写的非常啰嗦，予以重新修复和调整。
STM32 L475 潘多拉测试通过
]
=> [adc] 增加ADC内置通道通用通道号标识

bsp/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f072-st-nucleo/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f401-weact-blackpill/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f407-robomaster-c/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f410-st-nucleo/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f411-st-nucleo/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f411-weact-blackpill/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f412-st-nucleo/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f427-robomaster-a/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32g474-st-nucleo/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32l431-BearPi/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32l476-st-nucleo/applications/arduino_pinout/pins_arduino.c
[
related : https://github.com/RT-Thread/rt-thread/pull/7198
]
=> [RTduino][STM32] 优化内置ADC通道

bsp/wch/risc-v/Libraries/ch32v30x_libraries/bmsis/source/system_ch32v30x.c
使用ch32v307芯片过程中，发现APB1时钟下的CAN总线速率配置不对，查看时钟设置终发现端倪
]
=> [bsp/wch]ch32v307 PCLK1(APB1)分频注释纠错

bsp/renesas/libraries/HAL_Drivers/SConscript, bsp/renesas/libraries/HAL_Drivers/drv_eth.c, bsp/renesas/libraries/HAL_Drivers/drv_eth.h, bsp/renesas/ra6m3-ek/board/Kconfig
=> [bsp][renesas] Add preliminary ethernet support.

components/finsh/msh_parse.c
[
在msh_parse.c文件中，发现msh_strtohex函数的注释返回值类型写错，误写成bool型，实际上返回的是int型。在此给出文件的详细路径如下：
1. rt-thread\components\finsh\msh_parse.c
原注释修改为
`/**
* This function will transform for string to hex.
*
* @param strvalue string
*
* @return integer transformed from string
*/`
all
]
=> [HUST CES][finsh]更正注释

bsp/stm32/stm32f401-st-nucleo/How to create a new project.md
=> [STM32F401] How to create a new project.md

bsp/Infineon/libraries/HAL_Drivers/drv_spi.c
[
Infineon 中关于片选 SPI 信号的实现没有考虑到 高有效的情况
通过 RT-thread 提供的 RT_SPI_CS_HIGH 标志位实现了高有效的情况
]
=> [HUST CSE] 修复Infineon中片选有效位的不同情况

bsp/allwinner/libraries/sunxi-hal/hal/source/dma/hal_dma.c
源码：if ((NULL == chan && chan->cyclic) || (0 == buf_addr))
这段代码在检查chan是否为NULL之前就检查了chan->cyclic。 如果chan是NULL，那么chan->cyclic就是无效的，并且会导致程序崩溃。
此处给出文件路径：
bsp/allwinner/libraries/sunxi-hal/hal/source/dma/hal_dma.c
直接验证chan和buf_addr的检查都通过
if ((NULL == chan) || (0 == buf_addr))
测试成功
=> [HUST CSE]avoids null pointer problems

src/timer.c
[
新版本中，timer.c在keil中不报错，而在iar中[#617](https://github.com/RT-Thread/rt-thread/blob/master/src/timer.c#L617)就会出问题。
建议将[#617](https://github.com/RT-Thread/rt-thread/blob/master/src/timer.c#L617)改为
`*(void **)arg = (void *)timer->timeout_func;`
]
=> [HUST CSE][src][timer.c]修复 iar 中的类型转换报错

bsp/lpc55sxx/Libraries/drivers/SConscript, bsp/lpc55sxx/Libraries/drivers/drv_soft_i2c.c, bsp/lpc55sxx/Libraries/drivers/drv_soft_i2c.h, bsp/lpc55sxx/lpc55s69_nxp_evk/Kconfig, bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig, bsp/lpc55sxx/tools/sdk_dist.py
[
添加了软件i2c 驱动，并在ubuntu上编译并测试通过，移植来自于stm32
修改了bsp/Kconfig中错误的路径，该bug会导致scons --menuconfig打不开，在ubuntu下测试通过
]
=> [bsp][lpc55s69]add softi2c

libcpu/mips/common/exception.c
[
rt_set_except_vector函数调用sys_exception_handlers[n]时可能会导致程序出现异常，问题在于索引越界判断的条件有问题，且判断应提前到所有赋值语句之前。
修改越界判断条件，更改判断位置.
all
]
- [1] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
=> [HUST][CSE]mips/common/exception.c/rt_set_except_vector

components/drivers/cputime/cputimer.c
[
适配posix timer 的 signal 部分
修复之前cputimer的框架
aarch64平台
]
=> 🐞 fix(components/drivers/cputime/cputimer.c): fix cputimer with signal

bsp/ft32/libraries/Drivers/drv_usart.c
[
有一处语法错误，多写了一个‘)’
删除多余的‘)’
本地环境
]
=> [HUST CSE]fix:Grammar error: An extra ') '

bsp/fm33lc026/libraries/FM33LC0xx_FL_Driver/Src/fm33lc0xx_fl_exti.c
[
源码：
/* 延时需要大于3个32K的周期 */
for(uint16_t i;i<1000;++i)
{
__NOP();
}
循环中没有初始化i，会导致不确定的行为。
文件路径：bsp/fm33lc026/libraries/FM33LC0xx_FL_Driver/Src/fm33lc0xx_fl_exti.c#L189
将i初始化为0
测试成功
]
=> [HUST CSE] Initialize uint16_t variable in delay loop

bsp/at32/libraries/rt_drivers/config/f435_437/uart_config.h
[
[bsp/at32] add at32f435_437 uart interrupt functions macros
]
=> [bsp/at32] add at32f435_437 uart interrupt functions macros

bsp/allwinner_tina/libcpu/interrupt.c
[
边界判断错误，在117行处会造成下标越界。
更改越界判断条件，并将同文件内两处越界判断做同样修改。
ALL
]
=> [HUST CSE]Fix error in bounds judgment(interrupt.c)

bsp/bouffalo_lab/bl808/m0/applications/dfs_mnt_sample.c, bsp/bouffalo_lab/bl808/m0/applications/hwtimer_sample.c, bsp/bouffalo_lab/bl808/m0/board/fal_cfg.h, bsp/bouffalo_lab/libraries/rt_drivers/Kconfig, bsp/bouffalo_lab/libraries/rt_drivers/SConscript, bsp/bouffalo_lab/libraries/rt_drivers/drv_flash.c, bsp/bouffalo_lab/libraries/rt_drivers/drv_flash.h, bsp/bouffalo_lab/libraries/rt_drivers/drv_hwtimer.c, bsp/bouffalo_lab/libraries/rt_drivers/drv_hwtimer.h
[
为bl808芯片增加hwtimer和flash驱动支持
增加 drv_hwtimer和drv_flash相关驱动文件
目前在bl808芯片上运行相关样例测试通过
]
=> [bsp][bouffalo] add hwtimer & flash driver support

bsp/imxrt/libraries/templates/imxrt1050xxx/rtconfig.py
[
在bsp/imxrt/libraries/templates/imxrt1050xxx/rtconfig.py发现缺少右括号
在结尾处添加右括号
PyCharm
]
=> [HUST CSE]Missing right parenthesis

bsp/gd32/arm/docs/GD32_ARM系列BSP外设驱动使用教程.md, bsp/gd32/risc-v/docs/GD32_RISC-V系列BSP外设驱动使用教程.md, bsp/imxrt/docs/IMXRT系列BSP外设驱动使用教程.md, bsp/imxrt/docs/IMXRT系列外设驱动添加指南.md, bsp/renesas/docs/BSP_Peripheral_Driver_Tutorial_of_RA_Series.md, bsp/renesas/docs/RA系列BSP外设驱动使用教程.md, bsp/stm32/docs/STM32系列BSP外设驱动使用教程.md, bsp/stm32/stm32u575-st-nucleo/stm32u575-st-nucleo Getting Started Guide.md, bsp/stm32/stm32u575-st-nucleo/stm32u575-st-nucleo 上手指南.md
[
仓库中env文档链接失效，链接为：https://www.rt-thread.org/document/site/programming-manual/env/env/
链接替换：https://www.rt-thread.org/document/site/#/development-tools/env/env
已查找过所有仓库中的env文档链接
]
=> [HUST-CSE]fix:Invalid document link about env

.github/SECURITY.md
=> [security] Set up security policy

bsp/airm2m/air32f103/libraries/AIR32F10xLib/src/air32f10x_i2c.c, bsp/apm32/libraries/APM32E10x_Library/APM32E10x_StdPeriphDriver/src/apm32e10x_pmu.c, bsp/apm32/libraries/APM32E10x_Library/APM32E10x_StdPeriphDriver/src/apm32e10x_rcm.c, bsp/apm32/libraries/APM32E10x_Library/APM32E10x_StdPeriphDriver/src/apm32e10x_sdio.c, bsp/lpc824/Libraries/peri_driver/dma/dma_8xx.h, bsp/mm32f103x/Libraries/MM32F103/HAL_lib/src/HAL_adc.c, bsp/mm32f103x/Libraries/MM32F103/HAL_lib/src/HAL_dma.c, bsp/mm32f103x/Libraries/MM32F103/HAL_lib/src/HAL_rcc.c, bsp/mm32f103x/Libraries/MM32F103/HAL_lib/src/HAL_tim.c, bsp/mm32f327x/Libraries/MM32F327x/HAL_Lib/Src/hal_rcc.c, bsp/mm32l07x/Libraries/MM32L0xx/HAL_lib/src/HAL_adc.c, bsp/mm32l07x/Libraries/MM32L0xx/HAL_lib/src/HAL_dma.c, bsp/mm32l3xx/Libraries/MM32L3xx/HAL_lib/src/HAL_adc.c, bsp/mm32l3xx/Libraries/MM32L3xx/HAL_lib/src/HAL_dma.c, bsp/mm32l3xx/Libraries/MM32L3xx/HAL_lib/src/HAL_rcc.c, bsp/mm32l3xx/Libraries/MM32L3xx/HAL_lib/src/HAL_tim.c, bsp/mm32l3xx/Libraries/MM32L3xx/HAL_lib/src/HAL_uart.c, bsp/raspberry-pi/raspi3-32/applications/test_device.c, bsp/tkm32F499/Libraries/Hal_lib/src/HAL_rcc.c, bsp/wch/arm/Libraries/CH32F10x_StdPeriph_Driver/StdPeriph_Driver/src/ch32f10x_i2c.c, bsp/wch/risc-v/Libraries/ch32v20x_libraries/bmsis/include/core_riscv.h, bsp/wch/risc-v/Libraries/ch32v20x_libraries/ch32v208_hal/include/ch32v20x.h
=> Fix many abnormal symbols in annotations

bsp/qemu-virt64-aarch64/qemu.bat
[
修复aarch64 qemu在Windows下启动失败的问题
]
=> aarch64:修复qemu.bat

README_zh.md, bsp/amebaz/README.md, bsp/bluetrum/ab32vg1-ab-prougen/README.md
[
一些readme文档链接失效，需要修改以方便阅读
在现在官方的网页文档里寻找合法的链接并修改
所有
]
=> [HUST CSE]Modified some invalid links in README documents

libcpu/mips/gs232/ls1c.h
Fix a misoperation
[
修复之前提交的PR中的误操作
增加误删除的宏定义
在任何测试环境下测试通过
]
=> [bsp][ls1c] fix a misoperation

libcpu/mips/gs232/cache.c
https://github.com/RT-Thread/rt-thread/blob/master/libcpu/mips/gs232/cache.c#L128
该处使用了未初始化的变量
该处代码在start和end之间限制了大小为size的空间，因此end应改为addr，修改如下：
https://github.com/zb1tree/rt-thread/blob/master/libcpu/mips/gs232/cache.c#L128
]
=> [HUST-CSE] fix:fixed variable misuse

bsp/at32/at32f403a-start/README.md, bsp/at32/at32f403a-start/board/Kconfig, bsp/at32/at32f403a-start/board/inc/at32_msp.h, bsp/at32/at32f403a-start/board/src/at32_msp.c, bsp/at32/at32f407-start/README.md, bsp/at32/at32f407-start/board/Kconfig, bsp/at32/at32f407-start/board/inc/at32_msp.h, bsp/at32/at32f407-start/board/src/at32_msp.c, bsp/at32/at32f423-start/README.md, bsp/at32/at32f423-start/board/Kconfig, bsp/at32/at32f423-start/board/inc/at32_msp.h, bsp/at32/at32f423-start/board/src/at32_msp.c, bsp/at32/at32f435-start/README.md, bsp/at32/at32f435-start/board/Kconfig, bsp/at32/at32f435-start/board/inc/at32_msp.h, bsp/at32/at32f435-start/board/src/at32_msp.c, bsp/at32/at32f437-start/README.md, bsp/at32/at32f437-start/board/Kconfig, bsp/at32/at32f437-start/board/inc/at32_msp.h, bsp/at32/at32f437-start/board/src/at32_msp.c, bsp/at32/libraries/rt_drivers/SConscript, bsp/at32/libraries/rt_drivers/config/f403a_407/dac_config.h, bsp/at32/libraries/rt_drivers/config/f423/dac_config.h, bsp/at32/libraries/rt_drivers/config/f435_437/dac_config.h, bsp/at32/libraries/rt_drivers/drv_config.h, bsp/at32/libraries/rt_drivers/drv_dac.c
[
[bsp/at32] add support dac driver
]
=> [bsp/at32] add support dac driver

bsp/gd32/arm/docs/GD32_ARM系列驱动介绍.md, bsp/gd32/risc-v/docs/GD32_RISC-V系列驱动介绍.md, bsp/imxrt/docs/IMXRT系列驱动介绍.md, bsp/lpc55sxx/docs/LPC55Sxx系列驱动介绍.md, bsp/renesas/docs/Introduction_to_RA_Series_Drives.md, bsp/renesas/docs/RA系列驱动介绍.md, bsp/stm32/docs/STM32系列驱动介绍.md
[
README 里有许多文档对应的官网链接已经失效，点击会直接跳转主页，需要替换。
找到真实的链接，对相应的失效链接进行替换。
只是对链接进行替换，不影响编译运行。
]
=> [HUST CSE]Modify invalid links

bsp/renesas/libraries/HAL_Drivers/drv_gpio.c, bsp/renesas/libraries/HAL_Drivers/drv_usart_v2.c
[
参数引用错误的修正
根据错误提示，找到引用函数原型，并进行修正
RA6M3-EK开发板下测试通过。
]
=> 修正renesas / libraries / HAL_Drivers /drv_gpip.c参数引用错误

bsp/lpc55sxx/docs/LPC55Sxx系列BSP外设驱动使用教程.md, bsp/lpc55sxx/docs/LPC55Sxx系列外设驱动添加指南.md, bsp/renesas/docs/Peripheral_Driver_Addition_Guide_of_RA_Series.md, bsp/renesas/docs/RA系列外设驱动添加指南.md, bsp/stm32/docs/STM32系列外设驱动添加指南.md
[
仓库中env工具用户手册链接失效，原链接为：https://www.rt-thread.org/document/site/programming-manual/env/env/
将其替换为新的env工具用户手册链接：https://www.rt-thread.org/document/site/#/development-tools/env/env
查找了当前仓库下所有env工具用户手册链接
]
=> [HUST CSE]fix invalid document link about env tools user manual

components/drivers/include/drivers/serial_v2.h, components/drivers/serial/serial_v2.c
=> [serial-v2]fix the data type error

bsp/imxrt/libraries/MIMXRT1020/MIMXRT1021/utilities/debug_console_lite/fsl_debug_console.c, bsp/imxrt/libraries/MIMXRT1060/MIMXRT1060/utilities/debug_console_lite/fsl_debug_console.c, bsp/imxrt/libraries/MIMXRT1170/MIMXRT1176/utilities/debug_console_lite/fsl_debug_console.c
=> [HUST CSE]fix logical error in judgment statement

bsp/loongson/ls1cdev/libraries/ls1c_spi.c
[
该函数中存在printf缺少参数问题，导致不能正确输出
增加参数，根据代码的上下文，可以想到，缺少的参数正是__function__
all
]
=>  [HUST CSE][bsp] fix printf parameter in loongson

components/net/sal/Kconfig, components/net/sal/src/sal_socket.c
=> “使用网络检测才依赖workqueue”

components/net/sal/src/sal_socket.c
=> [sal] fix #7329 compiling error

examples/utest/testcases/posix/stdio_h/functions/fclose_tc.c
[
两次关闭同一文件，会造成错误，并且if判断条件错误
考虑到fclose成功执行关闭文件，返回参数为0，因而可以先判断是否返回参数为0，如果是则输出fclose success，并且返回为0，否则返回-1
all
]
=> [HUST CSE]fix closing the same file twice

components/mm/mm_fault.c
[
解决编译```warning```
报未初始化```warning```，初始化该变量。
在```linux```下编译```samrt```内核测试通过，```warning```解除
]
=> fix warning

bsp/nv32f100x/lib/src/ics.c, bsp/smartfusion2/CMSIS/startup_arm/retarget.c
=> [HUST CSE]github上正常但导入vscode出现乱码

components/libc/compilers/mlibc/SConscript, tools/gcc.py
=> [mlibc] quick hack

examples/test/net_test.c
源文件：examples/test/net_test.c
修复了if条件语句未闭合
文件中332行if条件语句缺少`}`闭合，导致332行之后的语句将报错
在339行新增一个`}`使if条件语句正确闭合
已完成
=> [HUST CSE]Fix if condition statement not closed

libcpu/risc-v/t-head/c906/io.h, libcpu/risc-v/t-head/c906/plic.c, libcpu/risc-v/t-head/c906/plic.h, libcpu/risc-v/t-head/c906/rt_interrupt.h, libcpu/risc-v/t-head/c906/tick.h
fix c906 ioremap && default param
[
1、修复c906在rt-smart下plic相关寄存器ioremap，
2、部分参数宏定义修改为可通过外部bsp传入
1、通过RT_USING_SMART宏加入rt_ioremap
2、通过#ifndef宏判断保留默认参数，也可以通过bsp自定义参数
1、D1s (RDC2022 纪念版)测试通过可正常运行
2、bl808开发板测试通过可正常运行
]
=> [libcpu/risc-v/c906] add ioremap && default param

components/net/netdev/include/netdev.h, components/net/netdev/src/netdev.c
[
1. 使用接口设置默认网络设备，能够调到底层函数
2. 添加设备注册钩子函数及默认网卡切换钩子函数
]
=> 调整默认网络设备设置方式

.github/workflows/action_tools.yml
[
some time `scons --dist` error REF https://github.com/RT-Thread/rt-thread/issues/7253
add ci to check the dist document project
CI aciton
]
=> [github][action] check the dist project for ci

bsp/ck802/README.md, bsp/gd32450z-eval/README.md, bsp/hifive1/README.md, bsp/imxrt/imxrt1064-nxp-evk/README.md, bsp/lpc408x/README.md, bsp/lpc54608-LPCXpresso/README.md, components/drivers/spi/sfud/README.md
存在失效链接https://github.com/TanekLiang、xfwangqiang (xfwangqiang) - Gitee.com
将https://github.com/TanekLiang 改为 https://github.com/liangyongxiang， 删除 xfwangqiang (xfwangqiang) - Gitee.com
通过多个文件进行流程分析，并且只改动这一个位置，不会导致测试不通过。
=> [HUST CSE] fix: invalid link https://github.com/TanekLiang

libcpu/aarch64/common/interrupt.c, libcpu/aarch64/common/interrupt.h, libcpu/arm/cortex-a/interrupt.c, libcpu/arm/cortex-a/interrupt.h
=> 优化设置中断模式api

libcpu/aarch64/common/gic.c, libcpu/aarch64/common/gicv3.c, libcpu/arm/cortex-a/gic.c, libcpu/arm/cortex-a/gicv3.c
[
修复GICv2、GICv3中断触发模式设置无效的问题
]
=> [fix]:修复GICv2、GICv3中断触发模式设置无效的问题

components/net/netdev/src/netdev.c
=> [netdev] Add check if netdev->ops is null

bsp/stm32/docs/STM32系列如何创建新项目.md
[
[fix]修复STM32系列如何创建新项目.md中错误的图片地址
]
=> [fix]修复不正确的图片地址

components/utilities/zmodem/zcore.c
[
函数中存在指针变量未赋值的情况下进入while循环
根据函数逻辑赋值后进入while循环
all
]
=> [HUST CSE]fix:uninitialized *p

src/clock.c, src/cpu.c, src/kservice.c
[
部分函数注释`@brief`缺失。
添加相应的注释。
修改注释不会导致不通过。
]
=> [HUST_CSE] add doxygen missing `@brief`

src/Kconfig
[
添加rt-smart模式下Kconfig select选项，减少编译报错
1、d1s开发板
2、bl808开发板
]
=> add rt-smart mode Kconcfig select

components/lwp/lwp_syscall.c
应用fork子进程后，子进程使用stat函数，并未正确获得当前目录信息。
fork子进程时，lwp_struct_copy函数增加拷贝working_directory功能
smart+qemu aarch64
]
=> fork子进程时，lwp_struct_copy函数增加拷贝working_directory功能

.github/workflows/action.yml
=> [CI] ci 编译时先执行 scons --pyconfig-silent 后进行编译

libcpu/arm/common/atomic_arm.c
[
通过 IAR 编译 bsp 为 ev_hc32f4a0_lqfp176 的源码时出现 type qualifiers specified more than once 警告
删除多余类型限定符 volatile
IDE: IAR 9.30.1
bsp: ev_hc32f4a0_lqfp176
]
=> 修复 atomic_arm.c 多次指定类型限定符问题

components/drivers/fdt/src/dtb_load.c
[
对应issue：#7387 
fdt指针在释放掉后没有赋空操作，可能引起内存泄漏
fdt指针在释放掉后进行赋值为NULL
在全部环境中测试通过
]
=> [HUST CSE]Assign Null to fdt after free to avoid dangling pointer

bsp/nrf5x/libraries/drivers/drv_spi.c
[
drv_spi.c文件 #ifdef BSP_USING_SPI3处(83行)缺少 "{" 用于闭合
增加 "{" 闭合
]
=> [HUST CSE]drv_spi.c miss a "{" on line 83

bsp/lpc55sxx/lpc55s69_nxp_evk/applications/main.c
=> [bsp][lpc55sxx]update: add missing library

bsp/lpc55sxx/Libraries/drivers/drv_wdt.c
=> [bsp][lpc55sxx]update:update drv_wdt

bsp/loongson/ls2kdev/drivers/ata/dwc_ahsata.c, bsp/simulator/drivers/board.c, bsp/simulator/drivers/dfs_win32.c, components/drivers/fdt/src/dtb_base.c, components/drivers/fdt/src/dtb_get.c, components/drivers/fdt/src/dtb_load.c, components/libc/cplusplus/cpp11/emutls.c, examples/libc/ex4.c
[
对应issue:#7388
存在realloc函数，malloc函数，calloc函数使用后未重新定义的情况
重新定义一次
]
=> [HUST CSE]Update the use of 'realloc','malloc','calloc'

libcpu/arm/s3c44b0/serial.c
[
/libcpu/arm/s3c44b0/serial.c文件第78行语句“|”两侧是相同的表达式
删除其中一个表达式
all
]
=> [HUST CSE]Same expression on both sides of “|”

src/thread.c
=> [HUST CSE][src] 变量 rt_err 没有初始化

bsp/Infineon/psoc6-evaluationkit-062S2/board/board.c
=> [fix]boot os failed in mdk ide!

examples/utest/testcases/posix/stdio_h/functions/perror_tc.c
[
解决了 #7386 这个issue中的问题，在https://github.com/RT-Thread/rt-thread/blob/master/examples/utest/testcases/posix/stdio_h/functions/perror_tc.c#L12 这个函数中，使用了fopen函数，却没有使用fclose函数。
另外，在接下来的第18行uassert_int_equal(perror_entry(), 0);语句中，将perror_entry函数的返回值与0进行比较。但问题在于此函数只有一个返回值0，并没有其它返回值
增加了fclose语句，并且增加了函数运行失败时的返回值，便于后续比较
all
]
=> [HUST CSE][examples]Fixed an issue where fclose was not used after using fopen

bsp/at32/libraries/rt_drivers/drv_spi.c, bsp/hc32/libraries/hc32_drivers/drv_spi.c, bsp/stm32/libraries/HAL_Drivers/drv_spi.c, bsp/wch/risc-v/Libraries/ch32_drivers/drv_spi.c
[
drv_spi.c文件中这两行代码
```c
send_buf = (rt_uint8_t *)message->send_buf + already_send_length;
recv_buf = (rt_uint8_t *)message->recv_buf + already_send_length;
```
message->send_buf和message->recv_buf如果为NULL指针，可能导致程序崩溃
在这两行代码之前加上if判断指针是否为NULL
```c
/* avoid null pointer problems */
if (message->send_buf)
{
send_buf = (rt_uint8_t *)message->send_buf + already_send_length;
}
if (message->recv_buf)
{
recv_buf = (rt_uint8_t *)message->recv_buf + already_send_length;
}
```
测试环境下通过
]
=> [HUST CSE]fix:修改drv_spi.c空指针问题

.github/SECURITY.md
To ensure proper handling of security reports, please complete the "xxx" field in this commit and establish a separate mailing list for individual security-related communication.
=> Security Vulnerability Reporting Suggestion Template

.github/workflows/action.yml, components/libc/Kconfig, components/libc/compilers/musl/SConscript, components/libc/compilers/newlib/SConscript, tools/gcc.py
[
可以使用第三方libc作为软件包，在软件包select RT_USING_EXTERNAL_LIBC后，libc配平层将绕过编译链自带的newlib，进而执行第三方libc软件包的Sconscript。
]
=> [libc] support external third pary libc software package

examples/utest/testcases/kernel/memheap_tc.c
[
在函数memheap_test中存在一处冗余的判断条件
删除冗余的判断条件
ALL
]
=> [HUST CSE] 判断条件冗余

examples/utest/testcases/posix/unistd_h/functions/chdir_tc.c
[
在chdir_tc.c中chdir_entry函数中的指针变量ptr访问在空指针判断之前进行，存在可能的空指针引用,进而引起程序异常退出。
修改程序运行逻辑，使指针变量先进行空指针判断再进行访问
ALL
]
=> [HUST CSE] Adjust the null pointer check and access orderPointer error 

bsp/acm32/acm32f0x0-nucleo/drivers/drv_pm.c
[
变量初值没有初始化
给变量赋予初值
将初值设置为1的原因为参考类似的C代码，程序运行逻辑一致，地址为：https://github.com/RT-Thread/rt-thread/blob/master/bsp/essemi/es32f369x/drivers/drv_pm.c
ALL
]
=> [HUST CSE] 变量 tick 没有初始化

components/drivers/tty/console.c, components/drivers/tty/include/tty.h, components/drivers/tty/n_tty.c, components/drivers/tty/pty.c, components/drivers/tty/tty.c, components/drivers/tty/tty_ldisc.c, src/kservice.c
* tty_struct更类似于一个device，由上层的应用程序来访问；所以console，pts这些都是device。
* ptmx也是一份device，这样上层应用程序open它的同时，创建出一份对应的pts设备出来；
* 对代码进行调整，避免全局变量绕来绕去；
* 在qemu-virt64-aarch64下测试通过；
=> [tty] change driver of tty to device and code cleanup.

components/libc/posix/ipc/mqueue.c, components/libc/posix/ipc/mqueue.h, components/lwp/lwp_syscall.c
=> [components][posix] 完善 posix 接口消息队列

components/libc/compilers/common/include/sys/ioctl.h, components/net/lwip/lwip-1.4.1/src/include/lwip/sockets.h, components/net/lwip/lwip-2.0.3/src/include/lwip/sockets.h, components/net/lwip/lwip-2.1.2/src/include/lwip/sockets.h
=> [libc] redirecting header sys/ioctl to  bits/ioctl

bsp/at32/libraries/rt_drivers/drv_spi.c
=> [bsp][at32]disable spi to change transfer size

components/drivers/cputime/cputimer.c
- 修复ctrl c的问题
- 修复posix timer 与sleep不能共用的问题
- 修复posix timer定时不准的问题
=> [component][drivers][cputime]Fix timer dev

documentation/env/env.md
[
Minor change to update URL to download ENV tool.
]
=> [doc]env.md: Update URL to download env tool

bsp/Infineon/libraries/templates/PSOC62/board/SConscript, bsp/Infineon/psoc6-cy8ckit-062-BLE/board/SConscript, bsp/Infineon/psoc6-cy8ckit-062-WIFI-BT/board/SConscript, bsp/Infineon/psoc6-cy8ckit-062S2-43012/board/Kconfig, bsp/Infineon/psoc6-cy8ckit-062S2-43012/board/SConscript, bsp/Infineon/psoc6-cy8cproto-062S3-4343W/board/Kconfig, bsp/Infineon/psoc6-cy8cproto-062S3-4343W/board/SConscript, bsp/Infineon/psoc6-evaluationkit-062S2/board/Kconfig, bsp/Infineon/psoc6-evaluationkit-062S2/board/SConscript
=> [bsp] [Infineon] 将 slider 和 slider demo 宏分离

components/libc/posix/pthreads/pthread_attr.c
为components\libc\posix\pthreads 路径下的部分函数添加注释
=> [doxygen][libc] Add some comments for posix pthread functions

.hooks/pre-commit, .hooks/readme.md
[
添加formatting自动执行工具，exe文件可以从github中下载
添加git hook机制
git config --local core.hooksPath .hooks
]
=> [git][hooks]add formatting cmd

bsp/bouffalo_lab/libraries/rt_drivers/Kconfig, bsp/bouffalo_lab/libraries/rt_drivers/SConscript, bsp/bouffalo_lab/libraries/rt_drivers/drv_i2c.c, bsp/bouffalo_lab/libraries/rt_drivers/drv_i2c.h
[
新增bouffalo_lab 硬件I2C驱动
bl616/bl808开发板，读取i2c传感器通过
]
=> [bsp/bouffalo_lab]add drv_i2c

bsp/lpc55sxx/lpc55s69_nxp_evk/rtconfig.py
=> [bsp][lpc55sxx]update: rtconfig.py

.github/workflows/action.yml, bsp/raspberry-pi/raspi3-64/driver/Kconfig, bsp/raspberry-pi/raspi4-32/driver/Kconfig, bsp/raspberry-pi/raspi4-64/drivers/Kconfig
[
参考之前PR #7189，优化action显示
显示的log有问题。scons --pyconfig-silent 执行会有问题。
]
=> [CI][action] optimize the action view

bsp/bouffalo_lab/bl808/m0/rtconfig.py, bsp/bouffalo_lab/bl808/tools/sdk_dist.py, tools/mkdist.py
[
在bl808的m0中，dist复制不全
添加并修改了一些脚本文件，修改了mkdist.py，这似乎是个bug
在ubuntu22下能够正常打包，且打包的工程中能够正常编译，正常使用menuconfig配置
]
=> [bsp][bl][tools] add dist function

bsp/renesas/ra6m3-hmi-board/board/lvgl/demo/lv_demo_video.c, bsp/renesas/ra6m3-hmi-board/board/ports/avi/player/player.c, bsp/renesas/ra6m3-hmi-board/board/ports/drv_jpeg.c, bsp/renesas/ra6m3-hmi-board/board/ports/drv_jpeg.h
[
将 video demo 中的 buffer 修改为动态申请
HMI-Board
]
=> [Renesas]Modify player output buffer to dynamic malloc

components/drivers/usb/usbhost/core/hub.c
[
在hub.c中，rt_usbh_hub_init中，hcd->roothub在分配内存后未进行空指针检查
比对其他文件中对于变量是否为空的检查与后续处理步骤，添加了检查与后续处理的步骤
通过进行流程分析，并且只添加一个检查分支，不会导致测试不通过
]
=> [components/drivers] Detect null pointers 

bsp/bouffalo_lab/libraries/rt_drivers/Kconfig, bsp/bouffalo_lab/libraries/rt_drivers/SConscript, bsp/bouffalo_lab/libraries/rt_drivers/drv_gpio.c, bsp/bouffalo_lab/libraries/rt_drivers/drv_soft_i2c.c, bsp/bouffalo_lab/libraries/rt_drivers/drv_soft_i2c.h
=> [bsp][bl]update: drv_soft_i2c

bsp/allwinner/d1/SConstruct, bsp/allwinner/d1s/SConstruct, bsp/allwinner/libraries/sunxi-hal/hal/SConscript
=> [bsp/allwinner]update allwinnter libraries object file path

bsp/renesas/ra6m3-hmi-board/board/Kconfig, bsp/renesas/ra6m3-hmi-board/board/lvgl/demo/img/SConscript, bsp/renesas/ra6m3-hmi-board/board/lvgl/demo/lv_demo.c, bsp/renesas/ra6m3-hmi-board/board/ports/audio/SConscript, bsp/renesas/ra6m3-hmi-board/board/ports/audio/pwm_audio.c, bsp/renesas/ra6m3-hmi-board/board/ports/avi/SConscript, bsp/renesas/ra6m3-hmi-board/board/ports/avi/player/SConscript, bsp/renesas/ra6m3-hmi-board/board/ports/gpio_cfg.h
[
修改kconfig,sconscript脚本，添加demo宏控制
HMI-Board
]
=> [Renesas]Modifying some script files

README.md, README_de.md, README_es.md, README_zh.md
- Added HPMicro to RISC-V Vender List
[
Add HPMicro to RISC-V Vendor List
]
=> Add HPMicro to RISC-V Vendor List

examples/utest/testcases/posix/stdlib_h/functions/atoi_tc.c, examples/utest/testcases/posix/stdlib_h/functions/atol_tc.c
[
atoi_tc.c中的"sizeof(test_data[0])" 和atol_tc.c中的"sizeof(test_data1[0]"错误，小于实际数组中的数据个数
atoi_tc.c中的"sizeof(test_data[0])" 改为"sizeof(test_data)/sizeof(test_data[0])"，atol_tc.c中的"sizeof(test_data1[0]"改为"sizeof(test_data1)/sizeof(test_data1[0])".
正常测试环境
]
=> [HUST CSE]Update atoi_tc.c

bsp/Infineon/psoc6-evaluationkit-062S2/README.md
=> [bsp][Infineon]update: READ.me use path of relative

bsp/stm32/stm32h750-fk750m1-vbt6/board/linker_scripts/link.icf, bsp/stm32/stm32h750-fk750m1-vbt6/board/linker_scripts/link.lds, bsp/stm32/stm32h750-weact-ministm32h7xx/board/CubeMX_Config/MDK-ARM/startup_stm32h750xx.s, bsp/stm32/stm32h750-weact-ministm32h7xx/board/linker_scripts/link.icf, bsp/stm32/stm32h750-weact-ministm32h7xx/board/linker_scripts/link.lds
[
https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/tools/upgrade.py
执行upgreade.py脚本，刷新STM32所有bsp启动文件参数设置
]
=> [stm32][startup] modify heap size as 0x00 and stack size as 0x400

examples/utest/testcases/posix/stdio_h/functions/fgets_tc.c
[
这个文件里存在使用fopen函数后没有关闭文件fclose的现象，而且stream=NULL时是不需要fclose的
调换了fclose出现的位置
解决了fopen后未fclose问题
]
=> [HUST CSE]fix fgets_tc.c

components/drivers/usb/usbhost/class/udisk.c
[
components/drivers/usb/usbhost/class/udisk.c文件中的rt_udisk_run函数中第313行和第351行分别调用了rt_malloc函数进行内存分配，但是没有对分配结果进行检查就继续调用了rt_memset函数。作为对比，同样在rt_udisk_run函数中的第284行的指针sector也调用rt_malloc函数进行了内存分配，但先进行了空指针检查，随后才继续调用rt_memset函数。因此认为第313行和第351行的内存分配行为存在潜在的风险。
参考第284行调用rt_malloc函数后的处理步骤，对第313行和第351行的rt_malloc函数分配内存的行为分别检查rt_malloc函数的结果，并在分配失败时打印日志。
通过进行流程分析，并且只添加一个检查分支，不会导致测试不通过。
]
=> [HUST CSE][components][udisk.c] add two checkout procedures after malloc to make sure allocating successfully

src/device.c
[
https://github.com/RT-Thread/rt-thread/issues/7466
避免多次调用 device_open 接口
在 qemu-a9 bsp测试通过
]
=> [device] Avoid repeated calls device_open interface.

bsp/amebaz/rtconfig.py, tools/release/README.md, tools/release/buildbot.py, tools/release/stm32_update.py
[
将版本发布前自动处理相关脚本放到tools/release 文件夹下，在release文件夹下执行 `python buildbot.py update` (ENV环境下)可完成半自动版本发布前准备工作。  欢迎补充其他发布前自动化脚本
]
=> [tool][release] add tools/release folder for the scrips that prepare the version release

.github/workflows/action.yml
=> [action] add ra6m3-hmi-board (#11)

ChangeLog.md
=> [Add] v5.0.0 ChangeLog.md

components/dfs/dfs_v2/src/dfs_posix.c
=> fixed dfsv2 openat.

examples/utest/testcases/posix/stdio_h/functions/setbuf_tc.c
[
在
https://github.com/RT-Thread/rt-thread/blob/b1584e9fa9b66b250854b1836b79af9ba29400e6/examples/utest/testcases/posix/stdio_h/functions/setbuf_tc.c#LL16C6-L16C6
处，fopen失败后进入_exit，但是仍然进行了fclose，即执行了未定义危险行为fclose(NULL)
fopen失败后直接返回，fopen正常时再执行fclose。将fclose前移到_exit之前。
ALL
]
=> [HUST CSE][examples]Fix undefined behavior 'fclose(NULL)'

bsp/lpc55sxx/Libraries/drivers/drv_spi.c, bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig, bsp/stm32/libraries/HAL_Drivers/drv_qspi.c
=> [bsp][lpc55sxx]update: drv_spi use rt_spi_bus_attach_device_cspin

bsp/raspberry-pico/board/board.c
[
解决pico 芯片 rt_tick 不准确的问题
从正确的系统时钟源clk_sys获取tick数，来配置sys_tick。
使用bsp/raspberry-pico/applications/main.c, 在代码中增加一行打印 rt_kprintf("Tick\n");
```
#define LED_PIN 25
int main(void)
{
rt_kprintf("Hello, RT-Thread!\n");
rt_pin_mode(LED_PIN, PIN_MODE_OUTPUT);
while (1)
{ 
rt_pin_write(LED_PIN, 1);
rt_thread_mdelay(1000);
rt_pin_write(LED_PIN, 0);
rt_thread_mdelay(1000);
rt_kprintf("Tick\n");
} 
}
```
**准确情况下Tick每2秒输出一次。**
**修改前串口打印输出**
串口打印前面的时间戳间隔为：39.037-38.167=0.86s
```
[15:21:37.183]  \ | /
[15:21:37.183] - RT -     Thread Operating System
[15:21:37.183]  / | \     5.0.1 build May 12 2023 15:00:05
[15:21:37.194]  2006 - 2022 Copyright by RT-Thread team
[15:21:37.194] Hello, RT-Thread!
[15:21:38.167] msh >Tick
[15:21:39.037] Tick
[15:21:39.908] Tick …
```
=> [bsp/raspberry-pico] fix sys_tick setting wrong clock source

bsp/gd32/arm/libraries/gd32_drivers/drv_spi.c, bsp/gd32/arm/libraries/gd32_drivers/drv_spi.h
[
更新gd32 drv_spi.c功能支持GD32F4xx
新增支持gd32 spi3 spi4 外设，新增 rt_hw_spi_device_attach
在gd32f450硬件平台测试通过
]
=> [bsp][gd32][spi] add spi3\spi4 support and rt_hw_spi_device_attach

components/lwp/lwp_syscall.c
[
在用户态使用系统调用侧mount、umount，挂载、卸载失败
在内核里加入对系统调用侧mount的对接代码
qemu环境，使用busybox mount、umount命令可成功对tmp、ext文件系统进行挂载与卸载
]
=> [component] add sys_mount and umount2

.github/workflows/action.yml
=> [action] add maxim/max32660

components/libc/cplusplus/cxx_crt_init.c
[
给一个名为cplusplus_system_init()的函数添加了函数注释
]
=> Update cxx_crt_init.c 函数注释

.github/workflows/action.yml, include/rtatomic.h, include/rtdef.h, include/rtthread.h, libcpu/Kconfig, libcpu/arm/common/atomic_arm.c, libcpu/risc-v/common/atomic_riscv.c
=> [atomic] add stdc atomic detection.

bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/README.md, bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/pins_arduino.c, bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/pins_arduino.h
=> [rtduino][stm32] support SPI LCD

bsp/stm32/stm32l475-atk-pandora/board/Kconfig
=> [stm32l475][Kconfig] add BSP_USING_PWM4_CH2 when enable RTduino

components/drivers/include/drivers/spi.h, components/drivers/spi/spi_core.c
rt_spi_send_then_recv是先发再等待一个独立的消息接收
rt_spi_transfer是收发同时进行
rt_spi_sendrecv8/16应使用rt_spi_transfer而不是rt_spi_send_then_recv
[
]
=> [device][spi] 修复 rt_spi_sendrecv8/16 收发不同时的问题

bsp/stm32/libraries/HAL_Drivers/config/l4/dma_config.h
=> [bsp][stm32l4] support SPI3 RX DMA

components/libc/posix/ipc/mqueue.c
=> [libc error] 编译错误PATH_MAX 未定义，移除 mq 中的 PATH_MAX 判断

components/lwp/lwp_syscall.c, components/mm/mm_page.c, components/mm/mm_page.h
[
补充确实的一些系统调用，像sysconf依赖的sysinfo、sched_getaffinity等
以及一些文件系统相关的系统调用。
]
=> add lstat&sysinfo....syscall.

components/libc/posix/signal/posix_signal.c
[
增加 libc/posix/signal/posix_signal.c 部分函数注释
]
=> [libc][posix][signal] 增加posix_signal.c 部分函数注释

.github/workflows/action.yml, bsp/renesas/ra6m3-hmi-board/SConscript, bsp/renesas/ra6m3-hmi-board/board/ports/audio/SConscript, bsp/renesas/ra6m3-hmi-board/board/ports/avi/SConscript, bsp/renesas/ra6m3-hmi-board/board/ports/wifi/SConscript, bsp/renesas/ra6m3-hmi-board/ra/SConscript, bsp/renesas/ra6m3-hmi-board/ra/fsp/src/bsp/cmsis/Device/RENESAS/Source/startup.c, bsp/renesas/ra6m3-hmi-board/ra_cfg/SConscript, bsp/renesas/ra6m3-hmi-board/ra_gen/SConscript, bsp/renesas/ra6m3-hmi-board/rtconfig.py, bsp/renesas/ra6m3-hmi-board/script/fsp.ld
[
[bsp][ra6m3-hmi-board] support gcc and llvm-arm toolchain. 
]
=> [bsp][ra6m3-hmi-board] support gcc and llvm-arm toolchain.

components/libc/compilers/picolibc/syscall.c
[
测试 lvgl 时，编译报错，发现是没对接heap
重定义内存接口，覆盖libc里的符号。
在 ra6m3-hmi-board 上测试通过，lvgl可以正常运行。
]
=> [libc] picolibc support heap.

bsp/Infineon/libraries/HAL_Drivers/drv_gpio.c, bsp/Infineon/libraries/HAL_Drivers/drv_spi.c, bsp/Infineon/psoc6-evaluationkit-062S2/board/Kconfig
[
修复了中断引脚只能使能一个的问题，修复多个设备同一个spi总线导致的问题。
psoc6-evaluationkit-062S2
]
=> [bsp][Infineon]Fix drv_gpio and spi problem

bsp/lpc55sxx/lpc55s69_nxp_evk/board/SConscript, bsp/lpc55sxx/lpc55s69_nxp_evk/rtconfig.py
=> [bsp][lpc55][gcc] fix the compiling errors when enable C++

bsp/bouffalo_lab/README.md, bsp/bouffalo_lab/bl61x/board/Kconfig, bsp/bouffalo_lab/bl61x/board/board.c, bsp/bouffalo_lab/bl61x/board/fw_header.c, bsp/bouffalo_lab/bl61x/flash_prog_cfg.ini, bsp/bouffalo_lab/bouffalo_flash_cube.sh, bsp/bouffalo_lab/libraries/rt_drivers/Kconfig, bsp/bouffalo_lab/libraries/rt_drivers/SConscript, bsp/bouffalo_lab/libraries/rt_drivers/drv_sdh.c, bsp/bouffalo_lab/libraries/rt_drivers/drv_sdh.h
[
新增bouffalo_lab下sd卡驱动
bl618开发板
]
=> [bsp/bouffalo_lab]add sdcard driver

bsp/stm32/libraries/HAL_Drivers/drv_spi.c
[
理论上，如果开启SPI DMA，应该是RX TX的DMA都开，但是在实际使用过程中用户很有可能开启RX TX其中一个DMA，本PR针对这种情况进行了完善。
如果只开启TX DMA，相当于单工发送，接收到的数据将不保证正确性，已经在潘多拉LCD上验证通过。
如果只开启RX DMA，这种情况是不允许的，使用RX DMA必须也开启TX DMA，程序中将给与错误告警。
]
=> [stm32][spi]完善在双工设置下仅开启TX/RX一方DMA的处理

bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/pins_arduino.h, bsp/stm32/stm32l475-atk-pandora/board/Kconfig, bsp/stm32/stm32l475-atk-pandora/board/ports/arduino/SConscript, bsp/stm32/stm32l475-atk-pandora/board/ports/arduino/ST7789_demo.cpp, bsp/stm32/stm32l475-atk-pandora/board/ports/lcd/SConscript
=> [RTduino][stm32][pandora] support Arduino libraries demos

libcpu/arm/cortex-a/start_gcc.S
[
Provide spin-table method to start secondary-cores without TF-A.
Tested on Nuvoton MA35D1 platform.
]
=> [libcpu] [cortex-a] Revert RT_SMP_AUTO_BOOT.

bsp/lpc55sxx/Libraries/drivers/drv_adc.c, bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
=> [bsp][lpc55sxx]update drv_adc

bsp/stm32/stm32l475-atk-pandora/board/Kconfig, bsp/stm32/stm32l475-atk-pandora/board/ports/arduino/ST7789_demo.cpp
=> [stm32][pandora][RTduino] 完善RTduino demo

bsp/lpc55sxx/lpc55s69_nxp_evk/applications/lvgl/SConscript, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/lvgl/demo/SConscript, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/lvgl/demo/lv_demo.c, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/lvgl/demo/lv_demo_calendar.c, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/lvgl/lv_conf.h, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/lvgl/lv_port_disp.c, bsp/lpc55sxx/lpc55s69_nxp_evk/applications/lvgl/lv_port_indev.c, bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
=> [bsp][lpc55sxx]add: adaptation LVGL

bsp/stm32/libraries/HAL_Drivers/drv_spi.c
否则可能影响上层应用的接收/发送buffer
attach: https://github.com/RT-Thread/rt-thread/commit/afcc4005b88c5740cd29f5f8ded69ca2d44c7ec9
[
]
=> [stm32][drv_spi] 优化spi单工发送, 不对接收buffer操作

bsp/raspberry-pico/drivers/drv_soft_i2c.c, bsp/raspberry-pico/drivers/drv_soft_i2c.h, bsp/raspberry-pico/libraries/Kconfig
=> [bsp][pico]add: drv_soft_i2c

bsp/stm32/libraries/HAL_Drivers/drv_spi.c
在传输数据为短小报文时，使用DMA模式反倒会慢
在短小报文密集的情况下，这种DMA劣化传输速度挺严重的
[
]
=> [stm32][spi-dma] 只有传输数据超过一定长度才会使用DMA方式

bsp/lpc55sxx/Libraries/drivers/drv_soft_i2c.c, bsp/lpc55sxx/Libraries/drivers/drv_soft_i2c.h, bsp/lpc55sxx/Libraries/drivers/drv_soft_spi.c, bsp/lpc55sxx/Libraries/drivers/drv_soft_spi.h, bsp/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
1.config pin in menuconfig;
2.update format;
3.chang soft_i2c name
[
]
=> [bsp][lpc55sxx]update: drv_soft_i2c drv_soft_spi

bsp/raspberry-pico/drivers/SConscript, bsp/raspberry-pico/drivers/drv_soft_spi.c, bsp/raspberry-pico/drivers/drv_soft_spi.h, bsp/raspberry-pico/libraries/Kconfig
=> [bsp][pico]update: add drv_soft_spi

bsp/gd32/arm/libraries/gd32_drivers/drv_spi_flash.c
[
GD32 bsp下，sfud驱动spi flash报错
开启cs时钟，以及修改probe入口参数
ALL
]
=> [bsp][gd32]fixed sf probe error

components/drivers/fdt/libfdt/fdt_rw.c
[
Windows 10  
利用cppcheck发现可以存在溢出问题，于是在第一个if前增加判断语句
]
=> [components] [cppcheck] Update fdt_rw.c

bsp/renesas/ra6m3-hmi-board/board/ra6m3_it.c
[
添加宏定义防止编译报错
RA6M3-HMI-Board
]
=> [bsp][Renesas]add definitions to prevent compilation errors

bsp/stm32/libraries/HAL_Drivers/drv_usart.c, bsp/stm32/libraries/HAL_Drivers/drv_usart.h
[
增加一个变量mask，不用每收到一个字节都调用stm32_uart_get_mask函数，mask在每次设置串口后调用stm32_uart_get_mask计算。
STM32H750VBT6用finsh测试通过8n1；（其他格式如8e1等没测试）
]
=> [serial_v1] 增加变量 DR_mask 成员变量提高效率

bsp/renesas/ra6m3-hmi-board/README.md
=> [bsp][Renesas]修改Readme

bsp/gd32/arm/libraries/gd32_drivers/SConscript, bsp/gd32/arm/libraries/gd32_drivers/drv_pwm.c
[在使用 RT-Thread Studio 构建  GD32F303 项目的时候，发现没有 PWD 驱动，然后自己写了一个，并在实际项目上稳定使用了半年有余的时间，现在开源出来给其他有需要的人，免得大家重复造轮子]
=> [bsp][gd32]添加 GD32F303 的 pwm 驱动

bsp/renesas/ra6m3-hmi-board/README.md, bsp/renesas/ra6m3-hmi-board/README_ZH.md
=> [bsp/ra6m3-hmi-board]add english README.md

libcpu/risc-v/common/trap_common.c
[
去掉了并未使用的user_name变量，该语句会引起移除了const的警告，在ubuntu22上编译测试通过
]
=> [risc-v][libcpu] 删去无用局部变量

bsp/renesas/libraries/HAL_Drivers/drv_sci_spi.c
[
测试发现rw007有时会通信失败，最后定位卡死在这里。
hmi-board 测试通过
]
=> [bsp/renesas] drv_sci_spi.c add timeout.

tools/cdk.py
[
1. 将生成的宏定义参数分隔符由逗号改为分号(逗号编译时会产生警告，CDK编辑时会报错)
2. 添加LIBS的支持，支持添加额外的连接库
]
=> [tool][cdk.py] scons的CDK工具宏定义改用分号作分隔符，并支持LIBS

include/rthw.h
=> [atomic] 头文件循环引用导致 rt_hw_interrupt_enable 未定义

components/net/at/src/at_utils.c
[
现在的at指令发送接口，底层会自动添加"\r\n"，某些场景需要发送空指令。如ESP32的蓝牙发送数据指令，收到">"后
发数据，等待接收OK。
详细讨论可见：
https://club.rt-thread.org/ask/question/185810c0aed98558.html
判断at指令长度，长度为0，则直接返回
ALL
]
=> [at] optimize at_vprintfln

.github/workflows/manual_dist.yml
[
提供手动触发scons --dist，并且可以添加config进行配置和生成
https://github.com/RT-Thread/rt-thread/issues/7638
添加mannual trigger
]
=> [feature][action] Add the manual trigger for scons dist 

components/drivers/spi/spi_core.c
If the configurations are the same, we don't need to set again.
如果同一spi从设备，上次配置的参数与本次配置相同，则无需再重新配置一遍，否则进入到drv_spi.c的configure方法中，要配置一堆硬件寄存器，完全是无用的重复性操作。
高密集短报文传输速率提高 ~10%
在RTduino/潘多拉下验证通过。
[
]
=> [spi] optimize the spi transfer speed.

bsp/stm32/libraries/HAL_Drivers/drv_spi.c
it shouldn't be a static variable.
https://github.com/RT-Thread/rt-thread/pull/7237#discussion_r1225512616
[
]
=> [stm32][drv_spi] revert typo

bsp/stm32/stm32l475-atk-pandora/board/ports/arduino/ST7789_demo.cpp
=> [stm32/pandora][arduino] st77xx update demo

libcpu/aarch64/common/psci.c
=> AMP-step4: 添加无设备树模式PSCI

libcpu/aarch64/common/mmu.c, libcpu/aarch64/cortex-a/entry_point.S
[
- 启动过程和__start解耦
- 对于RT_AMP_SLAVE 跳过cpu 非0核等待
]
=> AMP-step2: 修改:启动过程和__start解耦，对于RT_AMP_SLAVE 跳过cpu 非0核等待

components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c, components/dfs/dfs_v2/src/dfs_file.c
Add color ls for executable file. Test it under QEMU/aarch64
=> Add color ls for executable file.

components/dfs/dfs_v2/src/dfs_dentry.c
=> [dfs v2] fix dentry hash lookup bug; update dentry dump msh cmd;

include/rtdef.h
[
H7 DMA判断地址为空进行对齐,否则SPI DMA报错
对上一个pr进行补充> https://github.com/RT-Thread/rt-thread/pull/7637
H7/F7 DMA判断地址为空进行对齐
- STM32H750[ART-PI]
- KEIL V6 -OZ编译
- 使用SPI FLASH W25Q128,搭载littlefs文件系统测试
- 仅测试TXDMA和RXDMA开启情况.未测试单独开启TXDMA或者单独开启RXDMA的情况
]
=> [rtdef] RT_IS_ALIGN marco add a null address exclusive

bsp/rockchip/rk3568/Kconfig, bsp/rockchip/rk3568/driver/Kconfig, bsp/rockchip/rk3568/driver/board.c, bsp/rockchip/rk3568/driver/board.h, bsp/rockchip/rk3568/driver/drv_uart.c, bsp/rockchip/rk3568/driver/rk3568.h, bsp/rockchip/rk3568/link.lds, bsp/rockchip/rk3568/rtconfig.h
[
- 更新rk3568 bsp 支持PSCI、amp模式
]
=> AMP-step6: 更新rk3568 bsp 支持PSCI、amp模式（依赖AMP-step1-5）

libcpu/aarch64/common/mmu.c, libcpu/aarch64/cortex-a/entry_point.S
=> 修复aarch64-qemu启动失败问题

bsp/qemu-virt64-aarch64/drivers/virt.h
=> 删除ioremap 宏定义

.github/workflows/action.yml, .github/workflows/manual_dist.yml
=> [simulator] 添加 simulator in Linux ci

components/finsh/msh.c
These uses of offset 'cmd0_size' should follow the range check.
[
Fix offset used before range check
These uses of offset 'cmd0_size' should follow the range check.
n32/n32g43xcl-stb
]
=> [msh] fix offset used before range check

components/libc/compilers/common/include/sys/time.h
[
使用MDK编译出现该宏未定义问题
增加该宏定义
MDK
]
=> [components][time.h]Fixed undefined macro TIMER_ABSTIME

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript
=> [bsp][ch32-rsicv][sconscript] add drv_common.c

components/finsh/cmd.c
=> [finsh] 添加 RT_Device_Class_Bus 对应的描述字符串

bsp/wch/risc-v/Libraries/ch32_drivers/drv_common.c
=> [wch][risc-v][drv] fix a typo in drv_common.c

examples/utest/testcases/posix/stdlib_h/functions/strtol_tc.c
[
在v5.0.1版本进行utest测试时，发现这两处未通过。
1.使用strtol转换为16进制，c打印出的值是xz，因为0x后的第一个值z不属于十六进制，所以该函数没有将x识别为16进制符号。所以c-s的值等于1，断言应使用TEST2
2.strtol函数最后一个参数，理论上最大为36，这里rtthread写成37，改成36后通过，也许与新编译链有关
上面已描述
在qemu，arm开发板，树莓派4b上进行了测试
=> testcase 修改

bsp/nuvoton/libraries/nu_packages/Kconfig, components/drivers/Kconfig, components/drivers/include/drivers/sensor.h, components/drivers/include/drivers/sensor_v2.h, components/drivers/include/rtdevice.h, components/drivers/sensor/SConscript, components/drivers/sensor/v1/SConscript, components/drivers/sensor/v1/sensor.c, components/drivers/sensor/v1/sensor_cmd.c, components/drivers/sensor/v2/SConscript, components/drivers/sensor/v2/sensor_cmd.c, components/drivers/sensor/v2/sensor_v2.c
[
将对sensor框架的更改独立为v2并revert回到v1以保持兼容性。新的sensor软件包将不再接受对接v1框架(老框架)
新框架使用方法：
```Kconfig
select RT_USING_SENSOR
select RT_USING_SENSOR_V2 
```
]
=> [sensor-v2]将当前sensor框架revert回v1版本并独立为v2

components/libc/posix/io/termios/termios.h
=> [libc/termios]修改oflags定义与musl一致

bsp/imxrt/imxrt1060-nxp-evk/applications/lvgl/lv_port_indev.c
Fix below build error when using LVGL:
applications/lvgl/lv_port_indev.c(73): error: use of undeclared identifier 'BOARD_Touch_I2C_Send'
.I2C_SendFunc     = BOARD_Touch_I2C_Send,
^
applications/lvgl/lv_port_indev.c(74): error: use of undeclared
identifier 'BOARD_Touch_I2C_Receive'
.I2C_ReceiveFunc  = BOARD_Touch_I2C_Receive,
^
applications/lvgl/lv_port_indev.c(154): warning: implicit declaration of
function 'BOARD_LPI2C_Init' is invalid in C99
[-Wimplicit-function-declaration]
BOARD_LPI2C_Init(TOUCH_I2C, TOUCH_I2C_CLOCK_FREQ);
^
[
]
=> [bsp][imxrt1060] application: fix undeclared identifier error

bsp/allwinner/libraries/sunxi-hal/hal/source/sdmmc/osal/os/RT-Thread/os_queue.c, bsp/allwinner/libraries/sunxi-hal/osal/src/hal_queue.c, bsp/fujitsu/mb9x/mb9bf500r/application.c, bsp/imxrt/libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_os_abstraction_rtthread.c, bsp/imxrt/libraries/MIMXRT1060/MIMXRT1060/drivers/fsl_os_abstraction_rtthread.c, bsp/imxrt/libraries/MIMXRT1061/MIMXRT1061/drivers/fsl_os_abstraction_rtthread.c, bsp/imxrt/libraries/MIMXRT1170/MIMXRT1176/drivers/fsl_os_abstraction_rtthread.c, bsp/stm32/stm32mp157a-st-ev1/board/ports/dma_sample.c, components/drivers/usb/usbdevice/class/hid.c, components/drivers/usb/usbdevice/core/usbdevice_core.c, components/drivers/usb/usbhost/core/hub.c, components/libc/cplusplus/os/cxx_queue.h, components/libc/posix/ipc/mqueue.c, documentation/device/uart/uart.md, documentation/thread-comm/thread-comm.md, examples/utest/testcases/kernel/messagequeue_tc.c, include/rtthread.h, src/ipc.c
=> [Kernel] message 可以返回消息的实际大小

bsp/imxrt/libraries/drivers/drv_can.c, components/drivers/include/drivers/can.h
[
现有can.h文件，rt_can_ops成员函数sendmsg返回值为int ,与驱动drv_can,c里面的实例化函数的定义不同，需统一
将rt_can_ops成员函数sendmsg的返回值修改为rt_ssize_t
imxrt1176平台编译通过
]
=> [drivers]修复can驱动编译错误

bsp/imxrt/imxrt1170-nxp-evk/m7/board/linker_scripts/link_ram.icf
[
为imxrt1176平台iar工程添加一份ram版本的链接文件，以消除因自带qspi flash无法调试时的影响
在imxrt1176测试
]
=> [bsp][imxrt1176]add link file for iar project

src/Kconfig
=> [kernel][Kconfig] 调整Kconfig缩进

examples/utest/testcases/kernel/irq_tc.c, examples/utest/testcases/kernel/thread_tc.c
[
解决由于优化等级提升，且测试用例中多线程同时读写，或在中断中读写的变量未加volatile导致测试不通过的问题
]
=> [testcases]增加volatile解决优化等级高的情况下,测试不通过的问题

components/libc/posix/ipc/Kconfig, components/libc/posix/ipc/mqueue.c, examples/utest/testcases/kernel/messagequeue_tc.c, include/rtthread.h, src/Kconfig, src/ipc.c
[
posix 接口中支持消息队列的优先级，因此对系统的优先级进行适配
修改messagequeue 源码并用 RT_USING_MESSAGEQUEUE_PRIORITY 控制开启以保证不对原功能产生影响
添加测试用例以保证功能完好
qemu-vexpress-a9 测试通过
]
=> [src][components][include]消息队列支持优先级

libcpu/aarch64/common/interrupt.c
=> 修复gicv2默认邦核失败

.github/CODE_OF_CONDUCT.md
=> add RT-Thread Code of Conduct

bsp/wch/risc-v/ch32v307v-r1/board/linker_scripts/link.lds
[
https://github.com/mysterywolf/rt-thread/blob/ch32-link/bsp/wch/risc-v/ch32v208w-r0/board/linker_scripts/link.lds#L192
]
=> [bsp][ch32v307v] add _head_end for link file

bsp/wch/risc-v/Libraries/ch32_drivers/drv_common.c, bsp/wch/risc-v/ch32v208w-r0/SConstruct, bsp/wch/risc-v/ch32v208w-r0/board/linker_scripts/link.lds, bsp/wch/risc-v/ch32v208w-r0/rtconfig.py
=> [bsp][ch32v208w] fix C++ compling errors

components/drivers/sensor/v1/sensor.c
[
fix(sensor): 返回类型不一致的编译错误
static rt_size_t rt_sensor_read  ->static rt_ssize_t rt_sensor_read
iar9.30.1
]
=> [sensor]V1返回类型不一致编译错误

components/drivers/fdt/inc/dtb_node.h, components/drivers/fdt/src/dtb_get.c
=> [component][fdt]添加设备树子节点寻找宏

components/drivers/tty/include/tty.h, components/drivers/tty/tty.c, components/lwp/lwp.c
[
- Fix bugs on foreground application maintenance
- Modifying node initialization on both lwp and tty
- glib test case suite
]
=> [components/tty] fix bug on foreground app switch

components/libc/compilers/common/ctime.c, components/libc/posix/Kconfig, components/libc/posix/ipc/Kconfig, components/utilities/Kconfig, components/utilities/resource/SConscript
=> [libc]更新 libc timer id 分配方式

.github/workflows/compile_bsp_with_drivers.yml, tools/ci/compile_bsp_with_drivers.py
原先 CI 编译 BSP 都是根据默认的 Kconfig (rtconfig.h)，无法对更多驱动的编译进行测试
1. 查看当前 PR 修改到的 BSP
2. 根据该 BSP 当前外设驱动的支持情况（Kconfig/.config），直接修改rtconfig.h，然后重新编译
[CI 测试](https://github.com/RT-Thread/rt-thread/actions/runs/5388920070/jobs/9782194277)
=> [CI][bsp] Added CI to compile more drivers for the changed BSP

bsp/stm32/libraries/HAL_Drivers/drv_soft_i2c.c
=> [stm32][i2c] replace stm32_udelay as rt_hw_us_delay

components/drivers/tty/tty_ioctl.c
[
调用 termios 的 api（tcgetattr、tcsetattr）时，tty 中对应的命令未实现，导致功能异常
tty 设备中添加对应的命令
]
=> [tty] add TCGETA/TCSETAF/TCSETAW/TCSETA commands

.github/workflows/manual_trigger/manual_trigger_scons_STM32_all.yml
[
方便通过action来对BSP提供一些`scons --dist`的版本，并且对其进行scons编译
对所有STM32的开发板都进行scons 编译，并且到处scons --dist内容
action中测试通过。
]
=> [ci] add stm32 manual trigger all

bsp/acm32/acm32f0x0-nucleo/rtconfig.py, bsp/acm32/acm32f4xx-nucleo/rtconfig.py
[
#7746 
执行scons --dist不通过
错误报告没有sdk_dist 而当前的工程结构已经将sdk包含在了bsp\acm32\acm32f0x0-nucleo\libraries  所以不再需要dist_handle 命令
scons  win10 x64
]
=> [acm32]修复scons --dist错误

libcpu/aarch64/common/mmu.c, libcpu/aarch64/cortex-a/entry_point.S
=> 修复aarch64 smp启动失败问题

.github/workflows/action.yml, .github/workflows/manual_dist.yml, .github/workflows/manual_trigger_scons_STM32_all.yml, .github/workflows/manual_trigger_scons_except_STM32_all.yml
[
由于matrix只能存放256个，所以STM32和其他的bsp分开，这个yml可以手动触发，用来检查所有bsp的scons编译情况
这个主要用于RTT检查所有bsp的编译情况，一些编译有问题的已经注释掉了，如果需要打开可以直接把前面的#去掉，在自己仓库进行编译。
编译完之后，可以选择是否上传dist文件，上传dist文件方便其他人对于某个bsp单独开发，默认是不带dist的。
不带dsit的见：https://github.com/supperthomas/rt-thread/actions/runs/5418728142
带dist的见：https://github.com/supperthomas/rt-thread/actions/runs/5413242291
summay中可以方便找一些bsp直接下载。
这个主要可以针对不同的tag版本号进行对所有bsp进行编译等。
由于一次手动性执行时间较长，不建议经常执行。
]
=> [ci] Add the exp_STM32 scons

components/lwp/lwp.c, components/lwp/lwp_syscall.c
=> execute elf add executable permissions check.

documentation/thread-sync/thread-sync.md
[
Fix a typo in documentation.
Change  `mumber` to `number`.
Fix the typo in documentation.
no need to test.
]
=> fix a typo in documentation

.github/workflows/manual_dist.yml, .github/workflows/manual_trigger_scons_STM32_all.yml, .github/workflows/manual_trigger_scons_except_STM32_all.yml
[
dist_flag 不生效
修正dist_flag
本地action测试通过
]
=> [ci] Fix the flag of dist

components/utilities/ulog/ulog.c
[
https://github.com/RT-Thread/rt-thread/issues/7771
在 do_output 中添加对此变量的处理。
hmi-board
```
while (1)
{
count ++;
/* output different level log by LOG_X API */
LOG_D("LOG_D(%d): RT-Thread is an open source IoT operating system from China.", count);
LOG_I("LOG_I(%d): RT-Thread is an open source IoT operating system from China.", count);
LOG_W("LOG_W(%d): RT-Thread is an open source IoT operating system from China.", count);
LOG_E("LOG_E(%d): RT-Thread is an open source IoT operating system from China.", count);
ulog_async_output_enabled(RT_FALSE);
LOG_D("LOG_D(%d): off async.", count);
LOG_I("LOG_I(%d): off async.", count);
LOG_W("LOG_W(%d): off async.", count);
LOG_E("LOG_E(%d): off async.", count);
ulog_async_output_enabled(RT_TRUE);
rt_thread_mdelay(1000);
}
``` …
=> [ulog] support ulog_async_output_enabled

components/dfs/Kconfig, components/dfs/dfs_v1/filesystems/mqueue/SConscript, components/dfs/dfs_v1/filesystems/mqueue/dfs_mqueue.c, components/dfs/dfs_v1/filesystems/mqueue/dfs_mqueue.h, components/dfs/dfs_v1/src/dfs.c, components/dfs/dfs_v2/filesystems/mqueue/SConscript, components/dfs/dfs_v2/filesystems/mqueue/dfs_mqueue.c, components/dfs/dfs_v2/filesystems/mqueue/dfs_mqueue.h, components/libc/posix/ipc/Kconfig, components/libc/posix/ipc/SConscript, components/libc/posix/ipc/mqueue.c, components/libc/posix/ipc/mqueue.h
[
测试用例 
```c
#include <stdio.h>
#include <fcntl.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <mqueue.h>
#define THREAD_PRIORITY         25
#define THREAD_STACK_SIZE       5120
#define THREAD_TIMESLICE        5
static rt_thread_t tid1 = RT_NULL;
#define MQ_NAME_1       "/test1"
#define MQ_NAME_2       "/testmsg2"
#define MSG_SIZE    128
#define MAX_MSG     3
const char *s_msg_ptr[] = {"msg test 1", "msg test 2", "msg test 3"};
char r_msg_ptr_1[MAX_MSG][MSG_SIZE];
char r_msg_ptr_2[MAX_MSG][MSG_SIZE];
pthread_t send1, send2, rev1, rev2;
int * send_1(void * mq)
{
int i;
mqd_t mq1 = *(mqd_t *)mq;
printf("Enter into send_1 \n");
for (i = 0; i < MAX_MSG; i++ ) {
if ( -1 == mq_send(mq1, s_msg_ptr[i], MSG_SIZE, i)) {
printf("mq_send doesn't return …
```
=> [posix] posix 的 mqueue 对接到文件系统的 fd

libcpu/sim/posix/cpu_port.c
=> [simulator] 修复函数定义不一致

src/ipc.c
=> [kernel][bug]支持多个线程同时接收同一个事件

bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/pins_arduino.h, bsp/stm32/stm32f411-st-nucleo/applications/arduino_pinout/pins_arduino.h, bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/pins_arduino.h, bsp/stm32/stm32l475-atk-pandora/board/Kconfig, bsp/stm32/stm32l476-st-nucleo/applications/arduino_pinout/pins_arduino.h
=> [stm32][RTduino] support tone timer and pin number check

.github/workflows/action_tools.yml, .github/workflows/action_utest.yml, .github/workflows/file_check.yml, .github/workflows/static_code_analysis.yml
=> [ci][action] add the repo check for self-use

.github/workflows/action.yml, bsp/imxrt/imxrt1021-nxp-evk/board/linker_scripts/link.lds, libcpu/arm/cortex-m7/cpu_cache.c
[
编译cm7相关的bsp 例如`imxrt\imxrt1052-nxp-evk`的时候，keil出现undefine, RT_ASSERT 未定义
```
.\build\keil\Obj\rtthread.axf: Error: L6218E: Undefined symbol RT_ASSERT (referred from cpu_cache.o).
```
添加相关头文件
]
=> [libcpu]fix RT_ASSERT undefine

libcpu/arm/cortex-a/start_gcc.S
[
https://github.com/RT-Thread/rt-thread/issues/7570
https://github.com/RT-Thread/rt-thread/issues/7574
在qemu-vexpress-a9平台测试通过
]
=> [libcpu][cortex-a]modified start_gcc.S

.github/CODEOWNERS
[
添加代码自动reviewer quest机制，其他人在提pr的时候会自动根据文件夹目录来分配reviewer。
添加CODEOWNER
只有仓库有权限的才有reviewer资格。
具体参考
https://docs.github.com/zh/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
]
=> [github] Add the code_owner review request

components/net/sal/socket/net_sockets.c
- Avoid duplicate free as the d->vnode will be freed in the fd_release API call
[
发现了对同一个从heap中分配的对象的多次free的问题
删除第一次free的代码
在HPM6750EVKMINI + RW007_WIFI demo中测试通过
]
=> [components][net][sal][socket] Fix duplicate free on allocated buffer

components/Kconfig, components/drivers/rtc/soft_rtc.c, components/ktime/Kconfig, components/ktime/SConscript, components/libc/compilers/common/ctime.c, components/libc/posix/Kconfig, src/Kconfig
=> [ktime] add RT_USING_KTIME to kconfig build

.github/CODEOWNERS
=> [github] coder reviewer change

components/drivers/hwtimer/hwtimer.c
[
在oneshot模式下的count down的timer，overflow会累加导致计算count错误
oneshot模式下overflow不进行累加
risc-v和core m0的自研芯片上进行验证
]
=> [components] [hwtimer] overflow is invalid in oneshot mode

components/libc/compilers/common/ctime.c
=> [libc][time] cleanup code

include/rtthread.h
=> clean up rtthread.h

.github/workflows/file_check.yml, .github/workflows/static_code_analysis.yml
[
发现只提交readme相关的修改也会运行formatting和静态检查
]
=> [ci] add paths-ignore for format and static check

tools/building.py, tools/keil.py, tools/mkdist.py
e.g. scons --target=mdk5/4 --project-path='test'
will generate the test.uvoptx/uvopt file correctly
[
]
=> [tools][mdk] fix .uvoptx/uvopt project name

documentation/env/env.md
=> [doc][env] update env document

documentation/quick-start/quick_start_qemu/quick_start_qemu_windows.md
=> [docs][qemu] update quick_start_qemu_windows

.github/CODEOWNERS
=> [codeowners] add /documentation owners

documentation/quick-start/quick_start_qemu/quick_start_qemu_windows.md
=> [doc][qemu] update qemu for windows doc

include/rtthread.h
=> [debug] fix the error when disable RT_USING_DEBUG

components/drivers/rtc/soft_rtc.c, components/ktime/README.md, components/ktime/inc/ktime.h, components/ktime/src/aarch64/cputimer.c, components/ktime/src/boottime.c, components/ktime/src/cputimer.c, components/ktime/src/hrtimer.c, components/ktime/src/risc-v/virt64/cputimer.c, libcpu/aarch64/common/gtimer.c, libcpu/risc-v/virt64/tick.c
[
1. 因为tick从中断到设置中间的时延特别大，在1Ghz的平台上每2小时就有差不多5s的误差，因此暂不采用tick做基准时间，直接取gtime的cnt做基准时间，
2. 修复hdtime在smart场景ctrlc异常的bug
]
=> [ktime] fix wrong time

components/lwp/lwp_syscall.c
[
用户态调用`getpeername`函数获取套接字信息时，addr有可能异常
系统调用函数中，`namelen`值返回给用户态时，长度不对，会影响到相邻地址的值
]
=> [syscall][socket]fix socket addr bug

components/drivers/include/drivers/core/bus.h, components/drivers/include/drivers/core/device.h, components/drivers/include/drivers/core/dm.h, components/drivers/include/drivers/core/driver.h
the macros is too common to use so that to avoid conflicts
[
]
=> [drivers/core] revise the macros of header files

documentation/env/env-vscode.md
=> [docs] add env vscode document

bsp/raspberry-pico/drivers/SConscript, bsp/raspberry-pico/drivers/drv_i2c.c, bsp/raspberry-pico/drivers/drv_i2c.h, bsp/raspberry-pico/drivers/drv_spi.c, bsp/raspberry-pico/drivers/drv_spi.h, bsp/raspberry-pico/libraries/Kconfig
=> [bsp][pico]add: drv_spi and drv_i2c

src/ipc.c
[
去掉mutex里的递归
没有改变本身逻辑的情况下去除递归
在stm32f411bsp下测试
]
=> [kernel][mutex] 去除mutex中的递归

bsp/stm32/libraries/HAL_Drivers/drv_spi.c
[
related: https://github.com/RT-Thread/rt-thread/issues/7909
这两个变量会在调用HAL库Transmite函数时自动被设置 无需我们设置
]
=> [bsp][stm32][drv_spi.c] remove meaningless settings

.github/workflows/manual_dist.yml, .github/workflows/manual_trigger_scons_STM32_all.yml, .github/workflows/manual_trigger_scons_except_STM32_all.yml, .github/workflows/manual_trigger_scons_fail_bsp_all.yml
[
manual trigger 添加功能，并且添加一个fail的bsp 的列表，用于检查所有fail的bsp
]
=> [ci] add the manual trigger;add the fail bsp check

bsp/stm32/stm32h750-artpi/rtconfig.py
[
https://github.com/RT-Thread/packages/pull/1646
在软件包测试时发现问题，无法使用rt_slist_for_each_entry。
原因是rt_slist_for_each_entry使用了typeof关键字，typeof是GNU C的关键字
bsp编译选项需要替换为-std=gnu99
在bsp上使用typeof关键字，并进行了编译。
]
=> [bsp][stm32h750_artpi] use gnu99.

bsp/renesas/ra6m3-hmi-board/board/ports/touch/gt911/src/gt911.c
board/ports/touch/gt911/src/gt911.c: warning: operation on '*(config + 8)' may be undefined [-Wsequence-point]
config[8] = config[8] ^= (1 << 3);
~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
[
avoid warning message of sequence-point when build 
verify with RT-Thread HMI Board
use 'scons -j12' to build and check build message 
]
- [*] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [*] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [*] …
=> [bsp][ra6m3-hmi-board][touch] avoid warning message of sequence-point

components/libc/compilers/common/ctime.c
[
不同编译工具链自带的结构体有些不一样，例如在Keil下，其定义为无符号类型，如果判断>=0会被警告行为无意义
在另一些工具链的结构体下，会被定义为long 有符号类型，该判断是有意义的。
]
=> [libc][time] silence the incorrect type warning

libcpu/risc-v/common/interrupt_gcc.S
- Fixed the issue that t0 was modified unexpectedly before being saved
[
修复 RSIC-V 中断处理逻辑里在t0寄存器未保存之前被修改的问题
避免使用t0来做mstatus.mie的关操作
先楫HPM6750EVK2开发板上通过lvgl 的sample做了新改动的测试
]
=> [libcpu][risc-v][common] Avoid using t0 before being saved

bsp/stm32/stm32l475-atk-pandora/board/ports/lcd/drv_lcd.c
[
解决“stm32l475-atk-pandora” BSP 的LCD example屏幕不亮的问题，经过分析是由于LCD驱动初始化背光引脚时，而PWM驱动还没初始化
related: https://gitee.com/rtthread/rt-thread/pulls/641
]
=> [stm32][pandora] fix LCD init ahead PWM

components/net/sal/src/sal_socket.c
[SAL] fix the IPv4&v6 compiling issue.
=> [SAL] fix the IPv4&v6 compiling issue.

libcpu/risc-v/common/cpuport.h
enabled
- Defined ARCH_RISCV_FPU once the __riscv_flen macro was detected
[
解决 RISC-V SoC上当开启FPU后程序 crash问题
当`__riscv_flen` 宏被toolchain定义（即abi为ilp32f/ilp32d/lp64d)，需要同时定义 `ARCH_RISCV_FPU`
基于先楫HPM6750EVKMINI开发板的lvgl例程做了stress测试
]
=> [libcpu][risc-v][common] Fix application crash on risc-v soc if FPU is enabled

components/dfs/dfs_v2/src/dfs_posix.c
[
修复mkdir对已存在的目录时的返回值，不正确的返回值会导致应用对逻辑的处理。
]
=> fix mkdir error code.

components/drivers/rtc/rtc.c, components/libc/Kconfig, components/libc/compilers/common/Kconfig, components/libc/compilers/common/ctime.c, components/libc/compilers/common/include/sys/time.h
=> [libc][timezone] implement lightweith timezone configuration

components/mm/mm_page.c
[
msh list_page computing has a mistake
don't add _high_pages_nr
]
=> fix list_page

bsp/gd32/arm/gd32470z-lckfb/board/Kconfig, bsp/gd32/arm/gd32470z-lckfb/board/board.c, bsp/gd32/arm/libraries/GD32F4xx_Firmware_Library/SConscript, bsp/gd32/arm/libraries/gd32_drivers/SConscript, bsp/gd32/arm/libraries/gd32_drivers/drv_sdram.c, bsp/gd32/arm/libraries/gd32_drivers/sdram_port.h
[
增加立创 梁山派开发板的SDRAM驱动
从仿造ART-PI的SDRAM驱动添加SDRAM驱动
实际开发板测试通过
]
=> [bsp][gd32]添加 立创开发板 GD32F470 的 SDRAM驱动，从STM32的drv_sdram.c修改而来

bsp/renesas/ra6m3-hmi-board/SConscript, bsp/renesas/ra6m3-hmi-board/ra/SConscript, bsp/renesas/ra6m3-hmi-board/ra_cfg/SConscript, bsp/renesas/ra6m3-hmi-board/ra_gen/SConscript, components/drivers/spi/SConscript, components/libc/cplusplus/SConscript, tools/gcc.py
GCC like means the toolchains which are compatible with GCC
related: https://github.com/RT-Thread/rt-thread/issues/7554
[
]
=> [tools] add GetGCCLikePLATFORM

.github/workflows/manual_dist.yml
[
config 只有一个，不太方便
添加5个config，并且添加config设置的自由度
手动测试通过
]
=> [CI] add more config for manual trigger

src/ipc.c
[
bug fixups
In _rt_mutex_take(),
- clear pending object before exit if failure,
- fix thread error number to negative value,
- and test if owner existed after recover of failure.
QEMU aarch64, bst a1000
]
=> [src] bug fix in ipc.c

components/drivers/sdio/sd.c, components/libc/compilers/common/ctime.c, components/lwp/lwp_signal.c
=> fix build warning.

libcpu/aarch64/cortex-a/entry_point.S
[
修正多核时，没有为其它核分配栈空间的问题，这会导致其它核自动向下分配，造成写穿或向下溢出。
现自动根据CPU核心数来自动分配栈大小
在qemu-virt64-aarch64上进行测试
]
=> fixed stack setup when using SMP.

bsp/ESP32_C3/README_ZH.md
=> [bsp][esp32] update readme

components/libc/compilers/common/ctime.c
=> [ctime] 避免时区为负数时引入的隐式转换问题

components/lwp/lwp_syscall.c
=> [smart][fix] lwp fork with data copy

components/dfs/Kconfig, components/dfs/dfs_v2/filesystems/cromfs/dfs_cromfs.c
=> [smart][dfs v2] add cromfs

components/lwp/lwp_signal.c, components/lwp/lwp_syscall.c, components/mm/mm_page.c, include/rtdef.h
[
related: https://github.com/RT-Thread/rt-thread/pull/7960#issuecomment-1685573437
]
=> [rtdef] rename RT_CTASSERT to RT_STATIC_ASSERT

.github/workflows/action.yml
=> [ci] use env install script

bsp/airm2m/air32f103/board/linker_scripts/link.icf, bsp/airm2m/air32f103/board/linker_scripts/link.lds, bsp/airm2m/air32f103/board/linker_scripts/link.sct
[
原厂参数 
air32f103cbt6  96kbram  128kbrom
air32f103cct6  96kbram  256kbrom
修改链接文件RAM大小
scons 测试编译正常
]
=> fix(air links): 对应厂家手册将RAM容量改为96kb

components/libc/posix/ipc/mqueue.c, examples/utest/testcases/kernel/messagequeue_tc.c, include/rtthread.h, src/ipc.c
=> [posix]修复消息队列返回长度异常

.github/workflows/action.yml
=> [ci]change cmd to install.sh

components/lwp/lwp_pid.c
[
add waitpid(-1) support from POSIX.1
> If pid is equal to (pid_t)-1, status is requested for any child process. In this respect, waitpid() is then equivalent to wait().
Busybox ash
]
=> [smart] add waitpid(-1) support

components/dfs/dfs_v1/src/dfs_file.c, components/dfs/dfs_v2/src/dfs_file.c
=> [fix] copyfile dest file empty first

libcpu/aarch64/common/trap.c
[
调整backtrace和coredump的先后顺序。
修复backtrace用户态、内核态触发逻辑
]
=> change aarch64 trap backtrace & coredump priority rating.

components/drivers/rtc/alarm.c
[
使用alarm闹钟功能时，单次触发模式下，首次闹钟可以正常工作，修改闹钟时间重新启动后，回调函数未被调用。通过控制台list_timer查询定时器状态，可以发现alarm定时器未被激活
闹钟首次回调中会关闭定时器，在alarm_update函数中查询当前alarm是否处于为启动状态，未启动则将_container.current设置为NULL，这样可允许下次启动闹钟时可重新启动定时器
在qemu、STM32平台测试通过
]
=> 修复单次触发alarm，重复使用不启动定时器的bug

components/dfs/dfs_v1/filesystems/tmpfs/dfs_tmpfs.c, components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c, components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.h
=> fix dfsv2 tmpfs lock fault.

components/net/sal/src/sal_socket.c
[
There is an error when ifconfig querying after ifconfig setting.
When querying a network card that is not the currently used network card, use 'netdev'.
A1000
]
=> fix ifconfig

components/drivers/include/drivers/rtc.h, components/drivers/rtc/alarm.c
=> [修改]：alarm 将年月日也传给驱动层

components/dfs/dfs_v2/src/dfs_file.c
[
When creating a symbolic link, the target parameter is given as a file name, then error happens.
The order of extraction for symbolic links and files is not fixed. 
When a symbolic link is extracted first, the file has not yet been extracted, then error happens.
Use 'parent' as the file path prefix. and do not check if the file exists.
qemu aarch64
]
=> fix tar -xzvf symbol link

src/thread.c
=> [src] remove useless codes in kernel

libcpu/aarch64/common/context_gcc.S
[
RELATED #7982 
- Compilation error on aarch64 board due to undefined macro `SAVE_USER_CTX`
- Move macro to general code section
QEMU AArch64 virt board
]
=> [libcpu/aarch64] fix compile error

include/rtdef.h
=> [rtdef] add RT_USING_LIBC_ISO_ONLY macro

.github/workflows/pkgs_test.yml
[
当rt-thread更新后自动对一些软件包进行测试。
使用pkgs-test工具当rt-thread更新后对一些软件包进行测试。
在fork的rt-thread仓库上进行了测试。
]
- [x 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
=> [CI] Add pkgs-test

bsp/rockchip/rk3568/driver/board.c
[
In RT-Smart, `rt_hw_interrupt_init` will call `rt_ioremap` to map GIC's MMIO registers. There is a `rt_malloc` called in rt_ioremap, that will fail if we not init the mem heap yet.
]
=> [BSP/rockchip/rk3568] fixup heapmem init flow

include/rtdef.h
=> [rtdef] adjust RT_USING_SIGNALS defination

components/libc/compilers/common/include/dirent.h, components/libc/posix/Kconfig, components/libc/posix/io/epoll/epoll.c, components/libc/posix/io/eventfd/eventfd.c, components/libc/posix/io/signalfd/signalfd.c, components/lwp/lwp_ipc.c
适配 rt_channel 、 增加 rt_channel 在 dfs v2上一些功能的通用性，以及标准化 signalfd
=> Adapt rt_channel, increase the generality of some rt_channel functionality on dfs v2, and standardize signalfd

libcpu/arm/common/atomic_arm.c
related: https://github.com/RT-Thread/rt-thread/issues/7381
[
]
=> [iar]修复__LDREX 和 __STREX 报 declared implicitly 警告

src/kservice.c
=> [kservice]Improve rt_strerror function compatibility

examples/utest/testcases/kernel/thread_tc.c
=> [utest] 更改 thread_tc 线程栈的大小，避免 64 位机器导致的栈异常

include/rtdef.h, src/kservice.c
this code will not be used in here, but will be used in other user apps
related:
8e6f9cf1be2b08704ff02992dc57d3022bfb073a
ecf2d8215961ca7c539132b62a72df6072cc3e14
[
]
=> [rtdef] attach RT_ETRAP errno

components/lwp/lwp.h, components/lwp/lwp_syscall.c, components/lwp/lwp_user_mm.c, components/lwp/lwp_user_mm.h
=> [smart] Updated the API for kernel access to user address issues and for calculating string length

components/drivers/rtc/soft_rtc.c
=> 🐞 fix(soft_rtc): fix unsupported TIMEVAL and GET_TIMERES

components/libc/posix/Kconfig, components/libc/posix/io/signalfd/SConscript, components/libc/posix/io/timerfd/SConscript, components/libc/posix/io/timerfd/timerfd.c, components/lwp/lwp_syscall.c
添加 ` timerfd ` 系统调用，并更新 ` signalfd `  的编译文件 ` SConscript `
=> Add the system call timerfd and update SConscript for signalfd

bsp/allwinner/libraries/drivers/drv_lcd.c, bsp/allwinner/libraries/drivers/drv_lcd.h, components/drivers/include/drivers/lcd.h
[
为了移植ffmpeg和sdl2到d1s开发板上，并能播放视频，需要实现framebuffer的对拷，然而在d1s的bsp中并没有实现framebuffer设备。
完成framebuffer设备，并注册到/dev/fb0，使得用户态sdl2可以实现对拷
真实开发板环境
]
=> feat: support sdl2

examples/utest/testcases/kernel/Kconfig
=> [utest] 添加 signal 依赖项

bsp/stm32/stm32f407-rt-spark/board/linker_scripts/link.lds
[
添加 rt-spark 在 gcc 下运行 utest 链接代码段
]
=> [bsp][utest] 添加 rt-spark 在 gcc 下运行 utest 链接代码段

bsp/qemu-virt64-aarch64/qemu-debug.sh, bsp/qemu-virt64-aarch64/qemu-graphic.sh, bsp/qemu-virt64-aarch64/qemu.sh, bsp/qemu-virt64-riscv/qemu-nographic.sh, bsp/qemu-virt64-riscv/qemu-v-nographic.sh
=> 修复 qemu 挂载 elm 文件系统失败

examples/utest/testcases/kernel/atomic_tc.c, examples/utest/testcases/kernel/event_tc.c, examples/utest/testcases/kernel/mailbox_tc.c, examples/utest/testcases/kernel/messagequeue_tc.c, examples/utest/testcases/kernel/mutex_tc.c, examples/utest/testcases/kernel/thread_tc.c
=> [utest] 更改线程栈的大小，避免栈异常

bsp/stm32/stm32f407-rt-spark/board/ports/spi_flash_init.c, libcpu/arm/cortex-a/backtrace.h, libcpu/arm/cortex-a/cpuport.h
[
做测试的时候发现两个小问题
在qemu，rt-spark1测试通过
]
=> Fixup some problem

components/finsh/Kconfig, components/finsh/cmd.c, components/finsh/finsh.h, components/finsh/msh.c, components/finsh/msh.h, components/finsh/shell.c
[
新增msh自动补全子选项特性， 关闭旧的pr #7304，重新整理提交
]
=> 【msh】新增msh自动补全子选项特性

bsp/stm32/stm32h750-artpi/board/Kconfig, bsp/stm32/stm32h750-artpi/board/board.h
[
原本的串口缓冲区buffer定义放在board.h中，不太方便用户查找和修改，在menuconfig中用户可直接进行配置
]
=> [bsp] Optimize the kconfig structure of ART-PI board about serial port

bsp/raspberry-pico/drivers/drv_uart.c, bsp/raspberry-pico/drivers/drv_uart.h
Integrate with RT-Thread driver framework. Add Kconfig support for pins and devices selection.
[
优化 Pico 的 UART 驱动。
与 RT-Thread 驱动框架集成。添加对引脚和设备选择的 Kconfig 支持。
编译后在树莓派 Pico 上测试无问题。
]
=> [bsp][pico] Improve UART driver

bsp/lpc55sxx/Libraries/drivers/drv_adc.c, bsp/lpc55sxx/Libraries/drivers/drv_gt911.c, bsp/lpc55sxx/Libraries/drivers/drv_st7796.c, bsp/lpc55sxx/Libraries/drivers/drv_wdt.c
=> [bsp][lpc55sxx]: update debug log

.github/workflows/manual_dist.yml, .github/workflows/manual_trigger_scons_STM32_all.yml, .github/workflows/manual_trigger_scons_except_STM32_all.yml, .github/workflows/manual_trigger_scons_fail_bsp_all.yml
[
pkgs update 执行命令需要安装其他软件，根据action，更新其他手动脚本
]
=> [acition] update pkgs update script

bsp/raspberry-pico/board/board.c
[
添加一个直接重启到 BOOTSEL 模式的命令，方便快速烧录代码。
添加一个直接重启到 BOOTSEL 模式的命令，方便快速烧录代码。
在 Pico 上编译测试通过。
]
=> [bsp][pico] Add msh cmd to reset pico to BOOTSEL mode

ChangeLog.md
=> [log] rt-thread主线v5.0.2日志发布

tools/building.py
[
In some envs, the Env['CPPDEFINES'] returns deque data type. And the list can not add with a deque variable.
]
=> [building] Fix the deque issue for Env['CPPDEFINES']

components/lwp/lwp_syscall.c
=> add sys_setitimer syscall

components/dfs/dfs_v2/filesystems/elmfat/dfs_elm.c
=> 🐞 fix(dfs_v2/filesystems/elmfat): fix elm can not exec

bsp/renesas/libraries/HAL_Drivers/SConscript, bsp/renesas/libraries/HAL_Drivers/drv_sci.c, bsp/renesas/libraries/HAL_Drivers/drv_sci.h, bsp/renesas/ra6m3-hmi-board/board/Kconfig
**为什么提交这份PR (why to submit this PR)**
增加瑞萨SCI驱动，支持SPI、I2C和UART
**你的解决方案是什么 (what is your solution)**
增加drv_sci.c/h，修改HAL_Drivers的SConscript脚本
**在什么测试环境下测试通过 (what is the test environment)**
HMI-Board下测试验证
=> [bsp/renesas]add drv_sci.

bsp/stm32/stm32l431-BearPi/board/Kconfig, bsp/stm32/stm32l431-BearPi/board/ports/mpu6050_meas.c
[
在小熊派上增加一个mqtt demo 方便用户快速接入。
- at_device驱动esp8266
- kawaii-mqtt用于连接华为云服务器
- cJSON：用于解析华为云下发的json数据
- 上传mpu6050的原始数据到mqtt服务器
- mqtt服务器可以发送指令控制数据是否上传
效果如下：
]
=> [bsp][stm32] stm32l431-BearPi 添加mqtt连接华为云综合用例

bsp/at32/libraries/rt_drivers/drv_usbd.c, bsp/at32/libraries/rt_drivers/drv_usbfsd.c, bsp/imx/imx6ull-smart/drivers/drv_usbd.c, bsp/nuvoton/libraries/m031/rtt_port/drv_usbd.c, bsp/nuvoton/libraries/m2354/rtt_port/drv_usbd.c, bsp/nuvoton/libraries/m460/rtt_port/drv_usbd.c, bsp/nuvoton/libraries/m480/rtt_port/drv_usbd.c, bsp/nuvoton/libraries/n9h30/rtt_port/drv_usbd.c, bsp/nuvoton/libraries/nuc980/rtt_port/drv_usbd.c, components/drivers/include/drivers/usb_device.h
rt_ssize_t can give negative error code, which follows the unix style correctly
[
]
=> [fix][usb]return data type as rt_ssize_t

bsp/qemu-vexpress-a9/drivers/secondary_cpu.c
[
Fix smp with smart of vexpress-a9
]
=> [bsp] fix smp with smart of vexpress-a9
