components/dfs/dfs_v2/include/dfs.h
components/dfs/dfs_v2/include/dfs_fs.h
components/dfs/dfs_v2/src/dfs_posix.c
components/lwp/lwp_syscall.c

[
The lack of sys_utimensat implementation results in an error in the 'touch' command
add sys_utimensat
qemu aarch64
]

add sys_utimensat

---

components/lwp/Kconfig
components/lwp/lwp.c
components/lwp/lwp.h
components/lwp/lwp_futex.c
components/lwp/lwp_internal.c
components/lwp/lwp_internal.h
components/lwp/lwp_pid.c
components/lwp/lwp_pmutex.c
components/lwp/lwp_signal.c
components/lwp/lwp_syscall.c
include/rtthread.h

[
- Replace irq disable/enable codes in futex.
Tested on:
- QEMU system AArch64, RISC-V 64, ARM
]

[smart] Replace irq disable/enable codes in futex

---

.github/workflows/action.yml
bsp/mm32f327x/Libraries/MM32F327x/HAL_Lib/Inc/hal_eth.h
bsp/mm32f327x/Libraries/MM32F327x/HAL_Lib/Inc/hal_syscfg.h
bsp/mm32f327x/Libraries/SConscript
bsp/mm32f327x/README.md

[
仓库中 bsp/mm32f327x 目录下 README.md 文件中的参考链接 失效 与 采用 arm-none-eabi-gcc 编译时部分路径大小写错误
灵动微电子官网查询可用链接替换，并规范名词。将文件中错误大小写路径替换为正确路径。
浏览器中使用链接可行。在docker/ubuntu20.04 & arch/garuda 测试编译通过
]

fix:Invalid link and path for mm32f327/README.md

---

components/drivers/virtio/virtio.c

[
- qemu-virt64-aarch64默认情况是开启GPU的，如果使用不开图形化的脚本就没有virtio-gpu设备，导致查找virtio-gpu的设备的断言会把程序终止，将断言改成返回错误码的方式
- 修改图形颜色不对问题
- qemu-virt64-aarch64
]

修改virtio.c存在的问题

---

bsp/raspberry-pico/Kconfig
bsp/raspberry-pico/drivers/SConscript
bsp/raspberry-pico/drivers/drv_flash.c
bsp/raspberry-pico/drivers/drv_flash.h

[bsp][pico] add flash driver

---

components/dfs/dfs_v2/src/dfs_file.c
components/dfs/dfs_v2/src/dfs_pcache.c

[dfs v2] support O_DIRECT and O_SYNC flags

---

include/rtdef.h
include/rthw.h
include/rtthread.h

[
上一次同步内核时对这部分宏定义调整过，没有回复彻底。
]

restore smp macro define.

---

bsp/qemu-virt64-aarch64/rtconfig.py
libcpu/aarch64/SConscript
libcpu/aarch64/common/mmu.c
libcpu/aarch64/cortex-a/entry_point.S
tools/building.py

[
Fix `__start` to `_start` for aarch64 entry point
]

[libcpu] fix symbol of kernel entry point

---

libcpu/aarch64/common/mmu.h
libcpu/arm/cortex-a/mmu.h
libcpu/risc-v/t-head/c906/riscv_mmu.h
libcpu/risc-v/t-head/c906/trap.c
libcpu/risc-v/virt64/riscv_mmu.h
libcpu/risc-v/virt64/trap.c

[
This patch including following fixups/enhancements:
- fix rv64 trap support for mmap
- possible bug that a flag type is defined by enum (1,2,3,...)
]

[smart] fixup: mmap support

---

components/lwp/Kconfig

[
在开启smart/lwp选项后默认自动选择LDSO和pcache选项
]

update ldso pagecache kconfig

---

bsp/cv1800b/drivers/drv_gpio.c
bsp/cv1800b/drivers/drv_gpio.h

[
为cv1800b bsp添加gpio驱动
在milkv duo开发板上测试LED闪烁，以及触发中断注册函数测试通过
]

[bsp][cv1800b] Add gpio driver for cv1800b

---

include/rtdef.h

[
fix   build log  
```
Warning[Pe301]: typedef name has already been declared (with same type) E:\github\rt-thread\include\rtdef.h 1384 
```
Removed
Iar_ 8_ 40 test passed
]

[rtdef] remove duplicated rt_device_t defination

---

bsp/avr32uc3b0/SConscript
bsp/avr32uc3b0/application.c
bsp/avr32uc3b0/board.c
bsp/avr32uc3b0/drv_gpio.c
bsp/avr32uc3b0/drv_gpio.h

[
Dear RT-Thread Community, Greetings!
I just implemented an initial version of the GPIO driver for the
AT32UC3B (AVR32DEV1) target.
I looked around the codebase (specifically, bsp/) to see how the
general structure is. It was simple. I modified the existing (default)
application to use the new GPIO abstraction functions instead. The
GPIOs (from both the application and msh) work as expected.
I am using the AVR32DEV1 (MCUZone) development board for my tests.
]

AT32UC3B: Implement initial GPIO driver and app test function

---

src/clock.c

[
smp模式下，rt_timer_check()多次被调用，关联issue：#8137
smp模式，只让核心0才进行rt_timer_check()
]

fix: only the main core detection rt_timer_check(), in SMP mode

---

tools/building.py

[
rt-thread 目前有编译后执行操作的机制，而没有对应的编译前执行操作的机制，但是一些bsp中需要这种机制，如：
https://github.com/RT-Thread/rt-thread/blob/5d16042765ac989cab9bb4e9b112f1a98e17f4d5/bsp/lpc43xx/M0/SConstruct#L29-L45 
https://github.com/RT-Thread/rt-thread/blob/5d16042765ac989cab9bb4e9b112f1a98e17f4d5/bsp/raspberry-pico/SConstruct#L30-L37 
发现代码库中有写过类似的代码，但一直没有使用，遂直接启用。可能有更好的方案，可以讨论一下。
]

[tools] Enable prebuilding action

---

src/kservice.c

[
https://github.com/RT-Thread/rt-thread/issues/8153
]

[kservice] use C89 format to avoid warning

---

bsp/ESP32_C3/drivers/drv_gpio.c

现在所有 pin 的数据类型都是 rt_base_t ，但此文件有一处还是 rt_int32_t ，导致编译警告。

[bsp][ESP32_C3] 修复数据类型警告 rt_int32_t -> rt_base_t

---

components/net/sal/src/sal_socket.c

[
Add ifconfig updown function.
Add ifconfig updown function.
A1000
]

fix ash ifconfig updown

---

libcpu/avr32/uc3/exception_gcc.S

Dear RT-Thread Community,
[
为什么提交这份PR (why to submit this PR)
In the process of updating the core driver files for the Mizar32-B
target, the exception file needed an update too.
I simply echoed the latest exception file from Microchip's official
latest release (asf-standalone-archive-3.52.0.113) and modified parts
of the assembly which handles RT Thread interrupts.
I have tested the update with the Mizar32-B target. The changes for
this target are yet to be merged. It won't break the compilation for
any other target. The build works great on the VGA console :)
]

AT32UC3B: Rewire _intx for updated exceptions file from Microchip

---

bsp/stm32/stm32f407-rt-spark/board/SConscript
bsp/stm32/stm32f407-rt-spark/board/linker_scripts/link.lds
bsp/stm32/stm32f407-rt-spark/rtconfig.py

[
add llvm-arm toolchain support.
stm32f407-spark1 星火1号
]

[bsp/stm32f407-spark1] add llvm-arm toolchain support.

---

components/dfs/dfs_v1/src/dfs.c
components/dfs/dfs_v2/src/dfs.c
components/mm/mm_aspace.c

[
Fixups of vulnerability in kernel:
- out-of-bound access in dfs
- use-after-free in aspace_traversal
]

[quality] fixup: vulnerability in kernel

---

components/dfs/dfs_v2/filesystems/mqueue/dfs_mqueue.c

[dfs_v2][mqueue] fix No mqueue mounted

---

src/kservice.c

[src] Fix the issue of starting address misalignment

---

components/finsh/cmd.c
components/finsh/msh.c

[
修改后的样子
```
msh />ps
thread   pri  status      sp     stack size max used left tick   error  tcb addr
-------- ---  ------- ---------- ----------  ------  ---------- ------- ----------
tshell    20  running 0x00000168 0x00001000    16%   0x00000009 OK      0x600a37a0
aio      128  suspend 0x00000080 0x00000800    06%   0x0000000a OK      0x600a0cd8
mmcsd_de  22  suspend 0x000000d0 0x00000400    66%   0x00000014 EINTRPT 0x6009f260
sys work  23  suspend 0x00000080 0x00000800    06%   0x0000000a OK      0x600a0248
tidle1   255  ready   0x0000005c 0x00001000    02%   0x00000001 OK      0x6009c098
tidle0   255  ready   0x0000005c 0x00001000    05%   0x00000020 OK      0x6009c008
timer      4  suspend 0x00000078 0x00000400    11%   0x0000000a OK      0x6009eaf0
```
]
必须选择一项 Choose one …

[msh]Optimize list_thread display

---

bsp/airm2m/air32f103/libraries/rt_drivers/drv_gpio.c

[
[bsp/air32f103]:修复外部中断无效
调整配置流程，修复问题
air32f103cct6 iar8_40 测试通过
]

[bsp/airm2m]:修复外部中断无效

---

bsp/msp432e401y-LaunchPad/project.uvprojx
bsp/msp432e401y-LaunchPad/template.uvprojx

[
msp432e401y的bsp在进入mdk5工程时，芯片型号不正确。
更改芯片型号，更新配置文件
ti msp432开发板，mdk5

[bsp] Fixed bug of msp432e401y bsp chip model error after mdk5 open.

---

bsp/ESP32_C3/rtconfig.py

[bsp] [ESP32_C3/rtconfig.py] 支持 EXEC_PATH 路径展开

---

bsp/raspberry-pico/Kconfig
bsp/raspberry-pico/drivers/SConscript
bsp/raspberry-pico/drivers/drv_pwm.c
bsp/raspberry-pico/drivers/drv_pwm.h

[bsp][pico]: add pwm driver

---

components/dfs/dfs_v1/filesystems/mqueue/dfs_mqueue.c
components/dfs/dfs_v2/filesystems/mqueue/dfs_mqueue.c

[dfs][mqueue]Ensure that dev is initialized before mqueue

---

bsp/raspberry-pico/Kconfig
bsp/raspberry-pico/drivers/SConscript
bsp/raspberry-pico/drivers/drv_hwtimer.c
bsp/raspberry-pico/drivers/drv_hwtimer.h

[bsp][pico] add hwtimer driver

---

bsp/allwinner/libraries/drivers/sdmmc/drv_sdmmc.h
bsp/allwinner/libraries/sunxi-hal/hal/source/sdmmc/blkpart.c
libcpu/risc-v/t-head/c906/cpuport.h

🐞 fix: fix d1s smart build

---

components/net/lwip/port/sys_arch.c

[
修复smp下可能死锁的问题
如果是自旋锁的话，在lwip中就会在自旋锁中调用malloc或者free等接口，从而调用mutex这样的接口，造成线程切换从而死锁
]

🐞 fix(lwip/port/sys_arch): fix spinlock`s deadlock

---

include/rtdef.h

[rtdef] add comment for RT_USING_LIBC_ISO_ONLY

---

components/lwp/lwp_pid.c

✨ feat: fix pid recycling

---

bsp/raspberry-pico/Kconfig
bsp/raspberry-pico/drivers/drv_spi.c

[bsp][pico] Add spi pin selection

---

components/drivers/core/dm.c
documentation/basic/basic.md
include/rtdef.h
libcpu/sim/win32/startup.c
src/Kconfig
src/components.c

[debug] rename RT_DEBUGING_INIT as RT_DEBUGING_AUTO_INIT

---

components/lwp/lwp.c
components/lwp/lwp_ipc.c
components/lwp/lwp_ipc.h
include/rtdef.h

fix rt_channel lock.

---

src/idle.c

[
修复线程无法回收的错误，(线程资源被回收后调用ipc会再也回不来了)
]

🐞 fix(src/idle.c): fix thread exit

---

tools/gcc.py

[tools/gcc.py]fix scons error.

---

components/drivers/rtc/alarm.c

[drivers/rtc] 修复 alarm.c 少写分号

---

.github/PULL_REQUEST_TEMPLATE.md

[
添加PR的用户提供action编译成功的action链接，可以尽量避免编译不成功的代码合入。
添加链接
]

[github] Add PR check action

---

bsp/renesas/libraries/HAL_Drivers/config/drv_config.h
bsp/renesas/libraries/HAL_Drivers/config/ra8/adc_config.h
bsp/renesas/libraries/HAL_Drivers/config/ra8/dac_config.h
bsp/renesas/libraries/HAL_Drivers/config/ra8/pwm_config.h
bsp/renesas/libraries/HAL_Drivers/drv_sci_spi.c
bsp/renesas/libraries/HAL_Drivers/drv_sci_spi.h
bsp/renesas/libraries/HAL_Drivers/drv_spi.c
bsp/renesas/libraries/HAL_Drivers/drv_spi.h
bsp/renesas/ra8m1-ek/board/Kconfig
bsp/renesas/ra8m1-ek/board/ports/wifi/SConscript
bsp/renesas/ra8m1-ek/board/ports/wifi/drv_rw007.c
bsp/renesas/ra8m1-ek/configuration.xml

[
ra8 add adc、dac、pwm、spi configs
- BSP: 
- bsp\renesas\ra8m1-ek
- .config:
- CONFIG_BSP_USING_PWM
- CONFIG_BSP_USING_DAC
- CONFIG_BSP_USING_ADC
- action:
]

[bsp] ra8 add adc、dac、pwm、spi configs

---

components/libc/compilers/common/ctime.c

[libc] update ctime.c compatible with old drivers

---

bsp/renesas/libraries/HAL_Drivers/drv_sci_spi.c

[
- BSP:
- .config:
- action:
]

[bsp/renesas] update drv_sci_spi.c 修复 ci 报错

---

components/libc/compilers/common/extension/sys/stat.h
components/net/sal/src/sal_socket.c

[
mdk ac6 开启rw007 联网，编译报错
- BSP: ra8-ek
- .config:
- action:
]

[fix] sal build error.

---

bsp/renesas/libraries/HAL_Drivers/drv_flash.c
bsp/renesas/ra8m1-ek/board/ports/fal_cfg.h

[
添加 ra8m1 fal 配置文件，修改flash驱动
]

[bsp][renesas]添加fal配置文件，修改flash驱动

---

bsp/at32/libraries/rt_drivers/config/f402_405/dma_config.h
bsp/at32/libraries/rt_drivers/config/f402_405/uart_config.h
bsp/at32/libraries/rt_drivers/drv_usart_v2.c
bsp/at32/libraries/rt_drivers/drv_usbotgh.c
bsp/at32/libraries/usbotg_library/inc/usb_core.h

[
[bsp/at32] fixed usb/usart drivers
]

[bsp/at32] fixed usb/usart drivers

---

bsp/renesas/ra6m3-hmi-board/board/Kconfig

[
Add a DAC entry for ra6m3-hmi-board. This solves a problem that you cannot find DAC && DAC0 options when you create a project with RT-Thread Studio by default according to the [document ](https://docs.qq.com/doc/DQmVYUEN1dHVyd0hi?_t=1699797902805&u=3966a00c681449d7bed3362d4e91d48c)chapter 6.
Change Kconfig file in bsp renesas, add a menuconfig.
- BSP: bsp/renesas/ra6m3-hmi-board
- .config: BSP_USING_DAC
Please provide the link of action triggered by your own …

[bsp][renesas] add a DAC entry for ra6m3-hmi-board

---

components/libc/Kconfig

[
- BSP:
- .config:
- action:
]

[libc] add comment for RT_USING_EXTERNAL_LIBC

---

components/libc/Kconfig
components/libc/compilers/SConscript
include/rtdef.h
include/rtthread.h

This option is for RT-Thread Nano version.
If select this option, it will not compile components/libc folder and only use tool chain internal libc. Normally, the tool chain internal is only cover ISO standard (e.g. armcc), but some tool chains' internal libc will cover more than ISO standard (e.g. newlib).
[
- BSP:
- .config:
https://github.com/RT-Thread/rt-thread/actions/workflows/manual_dist.y …

[libc] add RT_USING_INTERNAL_LIBC_ONLY macro

---

.github/PULL_REQUEST_TEMPLATE.md
components/drivers/Kconfig
src/object.c

[
完善一些细节
- BSP:
- .config:
- action:
]

Improve some details

---

components/drivers/wlan/wlan_mgnt.c

[
结合上下文及函数作用，此处应该复制bssid以进行值传递，而不是再次进行校对
将 rt_memcmp 改为 rt_memcpy
- BSP:
- .config:
- action:
]

[components][wlan]: update rt_wlan_join_scan_callback

---

components/dfs/dfs_v2/filesystems/romfs/dfs_romfs.c

fix dfsv2 romfs dfs_romfs_getdents buffer overflow.

---

bsp/stm32/libraries/HAL_Drivers/drv_soft_spi.c
bsp/stm32/libraries/HAL_Drivers/drv_soft_spi.h

[
使用多路 soft SPI时发现异常
独立每个spi 的ops
- BSP:
- .config:
- action:
]

fix(spi):多个SPI公用一个ops.data

---

.github/workflows/action.yml

[
- BSP:
- .config:
- action:
]

[ci] add workflow_dispatch

---

bsp/ESP32_C3/drivers/Kconfig
bsp/ESP32_C3/drivers/drv_adc.c
bsp/ESP32_C3/drivers/drv_adc.h

[
- BSP:
- .config:
- action:
]

[bsp][esp32c3]: add adc driver

---

components/drivers/i2c/soft_i2c.c

Dear RT-Thread Community, Greetings!
I trust you're all doing so well.
[
I am working on a soft-i2c device driver support for the Mizar32
(at32uc3b) target. I had compilation problems because of the iterator
variable.
This PR will move the iterator outside the loop itself. It conforms to
C89.
- BSP: 
Here is the path to the BSP: bsp/avr32/at32uc3a0256
- .config:
CONFIG_RT_USING_SOFT_I2C=y
CONFIG_RT_USING_SOFT_I2C1=y
CONFIG_RT_SOFT_I2C1_SCL_PIN=1
CONFIG_RT_SOFT_I2C1_SDA_PIN=2
CONFIG_RT_SOFT_I2C1_BUS_NAME="i2c1"
CONFIG_RT_SOFT_I2C1_TIMING_DELAY=10
CONFIG_RT_SOFT_I2C1_TIMING_TIMEOUT=10
- action:
This is not applicable for now. The AVR32 target hasn't been added to
CI actions. But rest assured, this won't break the build for any other
target.
]
我在这个拉取/合并请求中已经考虑了 …

soft_i2c: Loop iteration variable: Conform to C89

---

.github/workflows/bsp_buildings.yml

[
- BSP:
- .config:
- action:
]

[ci] trigger building CI every midnight

---

bsp/avr32/at32uc3b0256/README.md

Dear RT-Thread Community,
[
I recently found the the pdf document for the AVR32 (MCUZone) dev board around at32uc3b0256. I had much difficulty in finding it. A friend (Alan) from another community helped me with a reference. This is useful for all AVR32UC3B users.
Save reference pdf into bsp/documents
- BSP: /bsp/avr32/at32uc3b0256
- .config: Not applicable.
- action: Not applicable.
]

User manual for a AT32UC3B0256 target from MCUZone

---

bsp/simulator/drivers/dfs_win32.c
components/dfs/dfs_v1/filesystems/elmfat/dfs_elm.c
components/dfs/dfs_v1/filesystems/nfs/dfs_nfs.c
components/dfs/dfs_v1/filesystems/romfs/dfs_romfs.c
components/dfs/dfs_v2/filesystems/elmfat/dfs_elm.c
components/dfs/dfs_v2/filesystems/tmpfs/dfs_tmpfs.c
components/dfs/dfs_v2/include/dfs.h
components/dfs/dfs_v2/src/dfs.c
components/dfs/dfs_v2/src/dfs_file.c
components/finsh/msh_file.c
components/lwp/lwp_syscall.c

[
1. 修改最大路径长度为4096字节(单个dname名字长度256字节)
2. 修改路径长度和dname长度混用的问题
3. 修改拷贝路径长度溢出的问题
fixup: /issues/8282
]

fix dfs path name overflow.

---

bsp/stm32/libraries/HAL_Drivers/SConscript
bsp/stm32/stm32f103-blue-pill/Kconfig
bsp/stm32/stm32f103-blue-pill/applications/main.c
bsp/stm32/stm32f103-blue-pill/board/Kconfig
bsp/stm32/stm32f103-blue-pill/board/board.c
bsp/stm32/stm32f103-blue-pill/board/board.h
components/Kconfig
components/drivers/Kconfig
components/finsh/Kconfig
components/libc/Kconfig
components/libc/SConscript
components/libc/compilers/SConscript
include/rtdef.h
src/Kconfig

[
增加RT_USING_NANO宏，可以一键选定，在不改变主线任何代码的情况下，让BSP变成nano版本。
增加此功能后，RT-Thread主线即可实现标准版、Smart版、Nano版在menuconfig任意切换
- BSP:
- .config:
- action:
]

RT-Thread BSP support Nano version

---

bsp/ESP32_C3/drivers/Kconfig
bsp/ESP32_C3/drivers/SConscript

[
更新Kconfig和Sconscript文件
对drivers中的文件添加相应的宏控制
- BSP: ESP32C3
- .config: CONFIG_RT_USING_ADC=y CONFIG_BSP_USING_ADC=y CONFIG_RT_USING_HWTIMER=y CONFIG_BSP_USING_TIMER0=y CONFIG_BSP_USING_HWTIMER=y
- action: https://github.com/Z8MAN8/rt-thread/actions/runs/7035515957/job/19146059470
]

[bsp][c3]: Add macro control to sconscript

---

bsp/renesas/ra8m1-ek/README.md

[
[bsp][renesas]更新ra8m1驱动支持列表
]

[bsp][renesas]更新ra8m1驱动支持列表

---

bsp/renesas/ra8m1-ek/.config
bsp/renesas/ra8m1-ek/board/Kconfig
bsp/renesas/ra8m1-ek/rtconfig.h

[
- BSP:
- .config:
- action:
]

[bsp][renesas]添加软件i2c配置

---

components/libc/posix/io/eventfd/eventfd.c
components/lwp/lwp_syscall.c
components/net/sal/include/sal_msg.h
components/net/sal/include/sal_socket.h
components/net/sal/socket/net_sockets.c
components/net/sal/src/sal_socket.c

修复问题
更新uds相关内容和因工具链更新导致的eventfd中的宏重定义的问题以及使用formatting工具统一格式
- BSP:
- .config: RT_USING_POSIX_EVENTFD、SAL_USING_AF_UNIX
- action:
]

Updated issues related to uds capacity and eventfd macro redefinition

---

tools/ci/file_check.py

[
CI增加检查返回rtt错误是否返回正值错误码的问题。
https://github.com/RT-Thread/rt-thread/issues/7510
- BSP:
- .config:
- action:
]

[ci] add error code check

---

src/thread.c

release mutex when thread delete

---

tools/building.py
tools/options.py

- format command options
- rename the --add_rtconfig as --global-macros
[
- BSP:
- .config:
- action:
]

[tools] format the options

---

components/dfs/dfs_v2/src/dfs_file.c

[
- BSP:
- .config:
- action:
]

fix #8305, symlink bug.

---

components/net/lwip/port/lwipopts.h

[
- BSP:
- .config:
- action:
]

fix netif name length config.

---

src/kservice.c

[
- BSP:
- .config:
- action:
]

[nano] add rt-thread nano title when startup

---

bsp/stm32/stm32f407-atk-explorer/applications/lvgl/lv_port_disp.c

[
stm32f407-atk-explorer这个bsp自带了lcd与lvgl移植，但是lvgl移植有bug，在未执行lcd驱动初始化时就尝试直接操作lcd对应的内存，造成busfault。
在lvgl初始化时，同时完成lcd驱动的初始化。
- BSP:
bsp\stm32\stm32f407-atk-explorer
- .config:
- action:
]

[bsp] 修复bsp自带的lvgl移植

---

bsp/qemu-virt64-aarch64/drivers/board.c
bsp/qemu-virt64-aarch64/drivers/board.h
bsp/qemu-virt64-aarch64/drivers/drv_gpio.c
bsp/qemu-virt64-aarch64/drivers/drv_rtc.c
bsp/qemu-virt64-aarch64/drivers/drv_virtio.c
components/mm/ioremap.c
components/mm/mm_page.c
libcpu/aarch64/common/interrupt.c
libcpu/aarch64/common/mmu.c
libcpu/aarch64/common/mmu.h
libcpu/aarch64/common/setup.c
libcpu/aarch64/cortex-a/entry_point.S

[
使用设备树对内存进行初始化
- BSP: qemu-virt64-aarch64
- .config:
- action:
]

[libcpu][aarch64] 使用设备树对内存进行初始化

---

bsp/stm32/libraries/Kconfig
bsp/stm32/stm32f401-st-nucleo/Kconfig
bsp/stm32/stm32f411-st-nucleo/Kconfig
bsp/stm32/stm32f412-st-nucleo/Kconfig
bsp/stm32/stm32f413-st-nucleo/Kconfig

[
为STM32 Nucleo系列增加板卡级识别宏
参考：https://www.st.com/en/evaluation-tools/stm32-nucleo-boards.html
- BSP:
- .config:
- action:
]

[bsp][stm32] add board identification macros

---

components/drivers/include/drivers/rtc.h
components/drivers/rtc/soft_rtc.c

[
修复 rt_soft_rtc_sync() 函数使用已弃用的声明方式所引发的警告
warning:  # 1295-D: Deprecated declaration rt_soft_rtc_sync - give arg types
将 rt_soft_rtc_sync() 改成 rt_soft_rtc_sync(void)
- BSP:
- .config:
- action:
]

[components][drivers][rtc] fix warning # 1295-D Deprecated declaration rt_soft_rtc_sync - give arg types

---

components/dfs/Kconfig

[
- BSP:
- .config:
- action:
]

update smart kernel default select dfsv2.

---

include/rtdef.h

[
- BSP:
- .config:
- action:
]

✨ feat(rtdef.h): add rt_always_inline

---

include/rtdef.h
src/ipc.c

[
添加rt_sem 支持control配置sem的最大值。例如当需要二值信号量的时候，可以保持当前IPC代码最小化改动。
]

add semaphore max value control.

---

components/libc/posix/io/timerfd/timerfd.c

优化epoll和timerfd
- BSP:
- .config:RT_USING_POSIX_EPOLL

Update epoll and timerfd

---

src/timer.c

[
修复 #8375 在smp模式下rt_timer里 timer check与timer start重复获取自旋锁而死锁的问题。
]

fix smp rt_timer deadlock.

---

include/rtthread.h
src/clock.c
src/cpu.c
src/scheduler_mp.c
tools/ci/cpp_check.py

[
标准spinlock需要关闭调度器，对外的spinlock全部使用关闭打开调度器方式
- BSP:
- .config:
- action:
]

✨ feat: spinlock should lock sched

---

bsp/stm32/stm32f072-st-nucleo/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32f401-weact-blackpill/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32f407-robomaster-c/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32f410-st-nucleo/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32f411-st-nucleo/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32f411-weact-blackpill/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32f412-st-nucleo/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32f427-robomaster-a/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32g474-st-nucleo/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32h563-st-nucleo/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32l431-BearPi/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/pins_arduino.h
bsp/stm32/stm32l476-st-nucleo/applications/arduino_pinout/pins_arduino.c
bsp/stm32/stm32u575-st-nucleo/applications/arduino_pinout/pins_arduino.c

[
- BSP:
- .config:
- action:
]

[stm32][rtduino] add drv_gpio.h for pins_arduino.c

---

components/drivers/Kconfig
components/drivers/clk/Kconfig
components/drivers/clk/SConscript
components/drivers/clk/clk-fixed-rate.c
components/drivers/clk/clk.c
components/drivers/include/drivers/clk.h
components/drivers/include/rtdevice.h

[
添加clk驱动框架，为全面使用设备树做准备
添加clk驱动框架
rk3568和qemu-aarch64
]

[component][drivers]add clk framework

---

src/thread.c
src/timer.c

[
原softtimer在下一次唤醒前会进入休眠，但是休眠不是原子性的，这期间如果有唤醒操作（新加入的超时节点）将变得不可用。
新的实现方式将休眠-唤醒采用二值信号量的方式，这样能保证每次休眠-唤醒的流程是原子性的。
]

Fix softtimer resume

---

src/mempool.c

[
修复死锁
- BSP:
- .config:
- action:
]

🐞 fix(mempool): fix assert

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_tim.c

[
修复某些TIMx在某些型号里不存在的问题 例如TIM8在stm32f411中不存在
- BSP:
- .config:
- action:
]

[stm32][drv_tim.c] fix errors when TIMx doesn't exist

---

src/thread.c

[
修复线程退出系统函数（有可能无法退出）
- BSP:
- .config:
- action:
]

🐞 fix(thread): fix thread_exit/detach/delete

---

tools/ci/bsp_buildings.py

[
- BSP:
- .config:
- action:
]

[ci][attachconfig] remove pkgs upgrade everytime

---

include/rtdef.h

[
- BSP:
- .config:
- action:
]

[rtdef] remove legacy code

---

tools/ci/bsp_buildings.py

[
1. log日志冗余信息太多，影响阅读。
2. 删除一行注释`pkgs --upgrade-script-force`。(https://github.com/RT-Thread/rt-thread/pull/8409)
不显示编译过程耗时。
- BSP:
- .config:
- action:
]

[ci][attachconfig] del debug time

---

components/drivers/misc/rt_drv_pwm.c

给 finsh 的 pwm 命令添加二级命令补全。
更改后的效果，可以用 tab 触发补全：

[pwm] Add second-level command completion

---

bsp/raspberry-pico/Kconfig

根据芯片文档限制了 menuconfig 中可以选取的引脚。

[bsp][pico] Limit PWM pin selection

---

tools/ci/bsp_buildings.py

[
```
scons -C bsp/{bsp} --pyconfig-silent
scons -c
```
不输出信息，仅输出警告和错误。
改为
```
scons -C bsp/{bsp} --pyconfig-silent > /dev/null
scons -c > /dev/null
```
- BSP:
- .config:
- action:
]

[ci][attachconfig] remove some output

---

components/drivers/Kconfig
components/net/lwip/Kconfig
components/vbus/Kconfig

[
https://github.com/RT-Thread/packages/pull/1714
- BSP:
- .config:
- action:
]

[kconfig] fix Kconfig warnings

---

components/drivers/misc/rt_drv_pwm.c

[pwm] Fix compiler warning

---

.github/actions/spelling/only.txt
.github/workflows/spell_check.yml

[
`spell_check`只检查documentation目录下的文件，以及去除了一些不必要的配置项。
- BSP:
- .config:
- action:
]

[ci][spell_check]change check path

---

.github/workflows/action_tools.yml
.github/workflows/action_utest.yml
.github/workflows/bsp_buildings.yml
.github/workflows/compile_bsp_with_drivers.yml
.github/workflows/doxygen.yml
.github/workflows/file_check.yml
.github/workflows/manual_dist.yml
.github/workflows/manual_trigger_scons_STM32_all.yml
.github/workflows/manual_trigger_scons_except_STM32_all.yml
.github/workflows/manual_trigger_scons_fail_bsp_all.yml
.github/workflows/static_code_analysis.yml

[
- BSP:
- .config:
- action:
]

[ci] actions/checkout upgrade to v4

---

src/ipc.c
src/scheduler_mp.c
src/thread.c

[
使用rt_thread_suspend_with_flag将自己挂起后，这时候中断是可以响应的，如果在中断中切走，那么就永远不会回来了,
必须先判断是否关闭调度器，再拿自旋锁，否则会出现死锁
自旋锁内禁止使用free,  malloc等内嵌阻塞ipc接口
- BSP:
- .config:
- action:
]

🐞 fix: fix rt_thread_delay, assert, deadlock

---

bsp/synwit/swm320-mini/SConstruct
bsp/synwit/swm320-mini/rtconfig.py
bsp/synwit/swm341-mini/SConstruct
bsp/synwit/swm341-mini/rtconfig.py

[
add variant_dir for libraries building，将编译生成的 .o 文件指定到 build 目录下
- BSP: bsp/synwit/swm341-mini
- .config:
- action:
]

[synwit] add variant_dir for libraries building

---

components/libc/compilers/common/include/sys/select.h

[
之前提过一种方案 但是容易引发嵌套包含的风险 https://github.com/RT-Thread/rt-thread/pull/8000 
- BSP:
- .config:
- action:
]

[libc] fix undefined warning of rt_memset

---

components/dfs/dfs_v1/filesystems/elmfat/dfs_elm.c

[
关联这份PR：https://github.com/RT-Thread/rt-thread/pull/6886
]

[components][dfs]修复FATFS文件系统使用cat命令导致断言BUG

---

.github/CODEOWNERS

[
- BSP:
- .config:
- action:
]

[ci] add .attach files' review owner

---

src/kservice.c

[
去掉malloc的大锁，修复memheap 的锁的错误使用
- BSP:
- .config:
- action:
]

🎈 perf(kservice): perf rt_hw_interrupt_disable/enable，fix memheap lock

---

src/cpu.c

[
大锁理应关闭调度器
- BSP:
- .config:
- action:
]

🐞 fix(cpu): cpus_lock should lock scheduler

---

.github/workflows/doxygen.yml
.github/workflows/manual_dist.yml
.github/workflows/pkgs_test.yml

[
- BSP:
- .config:
- action:
]

[ci] workflow only is used for rt-thread org

---

components/finsh/msh.c
components/lwp/lwp.h
components/lwp/lwp_user_mm.c
examples/utest/testcases/kernel/Kconfig
examples/utest/testcases/kernel/SConscript
examples/utest/testcases/kernel/hooklist_tc.c
include/rtdef.h
include/rtservice.h
include/rtthread.h
libcpu/aarch64/common/backtrace.c
libcpu/aarch64/common/cpu.c
libcpu/aarch64/common/cpuport.h
libcpu/aarch64/common/mmu.c
libcpu/aarch64/common/mmu.h
src/Kconfig
src/clock.c
src/ipc.c
src/irq.c
src/kservice.c
src/mempool.c
src/object.c
src/scheduler_mp.c
src/scheduler_up.c
src/thread.c
src/timer.c

[
- adding hooks for malloc service
- support for hook list ( add multiple hookers in a single hook point )
- QEMU aarch64, vexpress-a9
]

[kernel] adding hook for malloc service

---

src/thread.c

[
修复提前开中断导致死锁
- BSP:
- .config:
- action:
]

🐞 fix(thread): fix thread sleep (deadlock)

---

components/drivers/include/ipc/pipe.h
components/finsh/cmd.c
components/finsh/msh.c
components/finsh/shell.c
components/libc/compilers/armlibc/syscalls.c
components/libc/compilers/common/cstdlib.c
components/libc/compilers/common/include/posix/stdlib.h
components/libc/compilers/dlib/syscalls.c
components/libc/compilers/newlib/syscalls.c
components/libc/compilers/picolibc/exit.c

[
- BSP:
- .config:
- action:
]

fix some -Wmissing-prototypes warnings

---

.github/workflows/manual_dist.yml

[
- 修改手动测试权限
- 修改手动测试的config文件为一次性输入的config,
用户可以直接粘贴差异的config即可。
- BSP:
qemu-vexpress-a9
- .config:
- action:
]

[action] Fix manual trigger for others

---

include/rtdef.h
src/clock.c
src/cpu.c
src/idle.c
src/thread.c

[
删除线程引用计数
对应 https://github.com/RT-Thread/rt-thread/pull/8042#discussion_r1335329849
close #8446
- BSP:
- .config:
- action:
]

✨ feat: delete thread ref

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_adc.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_can.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_can.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_crypto.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_dac.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_pwm.c

[
- BSP:
- .config:
- action:
]

[stm32] fix missing headfer files

---

components/finsh/SConscript

增加检查finsh线程实际使用是否超过当前设定的线程大小
[
- BSP:
- .config:
- action:
]

[finsh] support to check static thread size

---

tools/ci/bsp_buildings.py

[
https://github.com/RT-Thread/rt-thread/issues/8427
.attach文件添加如下解析
```
```
如果侦测到scons关键字，则编译时，补充使用冒号后面的参数
- BSP:
- .config:
- action:
]

[ci][bsp_build]attachconfig add scons args parsing

---

include/rtthread.h
libcpu/aarch64/common/context_gcc.S
src/clock.c
src/cpu.c
src/irq.c
src/scheduler_mp.c
src/timer.c

[
- fixup of data racing accessing percpu objects
- BSP: rpi4b, qemu aarch64
- .config:
- action:
]

[kernel] fixup of data racing accessing percpu objects

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_sdram.c

[
- BSP:
- .config:
- action:
]

[bsp][stm32]fix stm32f469 sdram not enable problem.

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart_v2.c

[
- BSP:
- .config:
- action:
]

[bsp][stm32]fix stm32f2 usart driver

---

src/cpu.c

[
- remove assert for recursion on `rt_cpu_self()`, see #8475
- BSP:
- .config:
- action:
]

[cpu] remove assert for recursion for #8475

---

bsp/hc32/libraries/hc32_drivers/drv_common.c
bsp/hc32/libraries/hc32_drivers/drv_gpio.c
bsp/hc32/libraries/hc32_drivers/drv_gpio.h
bsp/hc32/libraries/hc32_drivers/drv_usart.c
bsp/hc32/libraries/hc32_drivers/drv_usart.h
bsp/hc32/libraries/hc32_drivers/drv_usart_v2.c
bsp/hc32/libraries/hc32_drivers/drv_usart_v2.h

[
更正启动顺序
#8480 
#8458 
- BSP:
- .config:
- action:
]

[bsp][hc32]update drivers

---

bsp/raspberry-pico/Kconfig
bsp/raspberry-pico/drivers/SConscript
bsp/raspberry-pico/drivers/drv_rtc.c

[
- BSP: raspberry-pico
- .config: BSP_USING_RTC
- action: https://github.com/Z8MAN8/rt-thread/actions/runs/7535896695
]

[bsp][pico]: add rtc driver

---

bsp/tm4c123bsp/libraries/TivaWare_C_series/tm4c123_driverlib/startup/gcc/startup_gcc.c

Fix entry point in startup_gcc.c

[bsp/tm4c123g] fix: fix startup_gcc.c entry point

---

bsp/raspberry-pico/.ci/attachconfig/rtduino.attach
bsp/raspberry-pico/board/board.c
bsp/raspberry-pico/board/board.h
bsp/raspberry-pico/drivers/drv_gpio.c
bsp/raspberry-pico/drivers/drv_uart.c
bsp/raspberry-pico/drivers/drv_uart.h

[
- BSP:
- .config:
- action:
]

[bsp][pico] remove meaningless dependencies of board.h

---

.github/workflows/manual_trigger_scons_except_STM32_all.yml
bsp/renesas/ebf_qi_min_6m5/SConstruct
bsp/renesas/ebf_qi_min_6m5/ra/fsp/src/bsp/cmsis/Device/RENESAS/Source/startup.c
bsp/renesas/ebf_qi_min_6m5/startup_check.py
bsp/renesas/ra2l1-cpk/SConstruct
bsp/renesas/ra2l1-cpk/startup_check.py
bsp/renesas/ra4m2-eco/SConstruct
bsp/renesas/ra4m2-eco/ra/fsp/src/bsp/cmsis/Device/RENESAS/Source/startup.c
bsp/renesas/ra4m2-eco/startup_check.py
bsp/renesas/ra6m3-ek/SConstruct
bsp/renesas/ra6m3-ek/startup_check.py
bsp/renesas/ra6m3-hmi-board/SConstruct
bsp/renesas/ra6m3-hmi-board/startup_check.py
bsp/renesas/ra6m4-cpk/SConstruct
bsp/renesas/ra6m4-cpk/startup_check.py
bsp/renesas/ra6m4-iot/SConstruct
bsp/renesas/ra6m4-iot/startup_check.py
bsp/renesas/ra8d1-ek/SConstruct
bsp/renesas/ra8d1-ek/ra/fsp/src/bsp/cmsis/Device/RENESAS/Source/startup.c
bsp/renesas/ra8d1-ek/rtconfig.py
bsp/renesas/ra8d1-ek/startup_check.py
bsp/renesas/ra8m1-ek/SConstruct
bsp/renesas/ra8m1-ek/rtconfig.py
bsp/renesas/ra8m1-ek/startup_check.py
bsp/stm32/stm32f407-rt-spark/rtconfig.py

[
说明：
1.新增对startup.c文件变更检测（用户使用不同的fsp重新生成配置文件时可能会覆盖该文件，但事实上该文件不应该被修改），在用户编译前会先检查一遍satrtup.c是否发生变更
2.为几个bsp添加gcc入口函数支持
3.补齐瑞萨bsp编译CI
4.修改星火一号工程为debug模式
ps:瑞萨全系列bsp都已通过编译测试，同时在linux平台下startup.c文件变更检测脚本也已通过测试
测试截图：
]

[bsp][renesas] Added the file change detection script

---

tools/gcc.py

[
#8220 导致 #8499 问题， python2不支持`subprocess.run`
改成`subprocess.Popen`
- BSP:
- .config:
- action:
]

[libc][tools] fix compile error on python2 env

---

bsp/stm32/libraries/HAL_Drivers/drivers/config/g0/dma_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/config/g0/spi_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/config/g0/tim_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/config/g0/uart_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_rtc.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_spi.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_tim.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart_v2.c
bsp/stm32/stm32g071-st-nucleo/board/Kconfig

[
stm32g0系列部分外设共用中断入口，这里将其完善区分；
原有的DMA支持不完整，这里提供一种使用参考。
- BSP:\bsp\stm32\stm32g071-st-nucleo
- .config:
- action:
]

[bsp][stm32]完善stm32g0系列部分外设中断处理

---

bsp/raspberry-pico/Kconfig
bsp/raspberry-pico/applications/arduino_main.cpp
bsp/raspberry-pico/applications/arduino_pinout/README.md
bsp/raspberry-pico/applications/arduino_pinout/pins_arduino.c
bsp/raspberry-pico/applications/arduino_pinout/pins_arduino.h
bsp/raspberry-pico/drivers/drv_adc.h
bsp/raspberry-pico/drivers/drv_pwm.c

[
- BSP:
- .config:
- action:
]

[bsp][pico]: support pwm adc iic for pico rtduino

---

bsp/stm32/stm32l475-atk-pandora/board/ports/wlan/drv_wlan.c
components/drivers/sdio/gpt.c
components/drivers/wlan/wlan_mgnt.c
components/finsh/cmd.c
components/finsh/msh.c

[
- BSP:
- .config:
- action:
]

fix MDK AC5 build warnings

---

libcpu/aarch64/common/mmu.c

[
rk3568平台下发现开启O2编译优化后有概率出现早期映射失败问题
添加volatile防止其优化
- BSP:
rk3588
- .config:
- action:
]

preventing erroneous optimization of rt_ioremap_early

---

components/finsh/cmd.c

[msh] fix the version command

---

bsp/cvitek/c906_little/board/Kconfig
bsp/cvitek/c906_little/board/tick.c
bsp/cvitek/drivers/SConscript
bsp/cvitek/drivers/drv_hw_i2c.c
bsp/cvitek/drivers/drv_hw_i2c.h

[
通过逻辑分析仪测试波形
为milkv-duo小核c906添加硬件i2c驱动
- BSP:
- .config:
- action:
]

[bsp][cvitek]: add c906_little i2c driver

---

bsp/bouffalo_lab/bl808/m0/applications/main.c
bsp/bouffalo_lab/bl808/m0/board/wlan_port/SConscript

[
为 bl808 m0 添加 BSP_USING_WIFI 宏相关约束，以便使能和不使能 WIFI 相关功能时都能正常构建项目
- BSP:
- .config:
- action:
]

添加 BSP_USING_WIFI 宏控制

---

bsp/nxp/mcxn/frdm-mcxn947/board/linker_scripts/MCXN947_cm33_core0_flash.ld
bsp/nxp/mcxn/frdm-mcxn947/rtconfig.py

[
> 修复NXP/MCXN GNU工具链构建及运行错误 (Fix compilation and runtime errors on NXP/MCXN BSP, based on)
> 基于 #8525 修复（Fixed based on #8525)
- BSP:
- .config:
- N/A
- action:
- Please trigger CI run on PR.
]

[bsp][nxp/mcxn] GNU toolchain fixes

---

bsp/gd32/arm/libraries/gd32_drivers/drv_adc.c

[
Test on GD32F303
ADC driver of GD32_ARM have multiple bugs.
1. ADC should use single operation mode, but current version use discontinuous operation mode.
2. When calibration is used after turning on the ADC, it is necessary to wait for 14 CK_ADC(about 350ns in GD32F303).
3. When enabling multiple ADC channels at once and sequentially reading the different channels, the values read are all the same.
1. Make sure ADC enable single operation mode.
2. Add a 1us dely after ADCON.
3. Clear EOC flag before start ADC convert to prevent other bugs.
4. The setting of the regular channel should be done at each reading, rather than at the point of enabling.
- BSP:GD32/ARM
- .config:
- action:
] …

[GD32_ARM] Fix bugs in drv_adc when enable multiple channel.

---

include/rtdef.h
include/rtservice.h
include/rtthread.h
src/components.c
src/idle.c
src/ipc.c
src/kservice.c
src/mem.c
src/memheap.c
src/thread.c
src/timer.c

[
- BSP:
- .config:
- action:
]

[kernel] fix strict compiling warnings

---

bsp/nxp/mcxn/Libraries/drivers/drv_rtc.c
bsp/nxp/mcxn/Libraries/drivers/drv_rtc.h
bsp/nxp/mcxn/frdm-mcxn947/board/board.c

[
> 增加MCXN RTC驱动 (Added MCXN RTC driver)
> N/A
- BSP:
- .config:
- `CONFIG_BSP_USING_RTC=y`
- action:
- Please trigger CI run on PR.
]

[bsp][nxp/mcxn10] Initial support for RTC driver.

---

bsp/phytium/libraries/drivers/drv_dc.c
bsp/phytium/libraries/phytium_standalone_sdk_install.py
bsp/phytium/libraries/port/fdriver_port/fdrivers_port.h

[
修改bsp/phytium中DC驱动接口，利用ops注册相关驱动
- BSP:
- .config:
- action:
]

change phytium dc driver with ops

---

bsp/nxp/mcxa/frdm-mcxa153/board/linker_scripts/MCXA153_flash.ld
bsp/nxp/mcxa/frdm-mcxa153/rtconfig.py

[
> 修复NXP/MCXA GNU工具链构建及运行错误 (Fix compilation and runtime errors on NXP/MCXA BSP)
> 基于 #8525 修复（Fixed based on #8525)
> 增加了缺失的GNU链接文件 (Added missing GNU linker script)
- BSP:
- bsp/nxp/mcxa/frdm-mcxa153
- .config:
- N/A
- action:
- Please trigger CI run on PR.
]

[bsp][nxp/mcxa] GNU toolchain fixes

---

libcpu/aarch64/cortex-a/entry_point.S

[
- 修复当开启 RT_USING_SMP ，并且 RT_CPUS_NR = 1 时编译报错问题
- .config:
- action:
]

fixed entry_point.S

---

.github/workflows/bsp_buildings.yml

[
> CI编译测试中缺少MCX系列相关板卡 (No CI build tests for MCX series boards)
> 在CI测试中添加以下板卡的编译测试： (Added the following boards to CI build tests:)
> * FRDM-MCXN947
> * FRDM-MCXA153
- BSP:
- bsp/nxp/mcxa/frdm-mcxa153
- .config:
- 无配置文件变更 (No configuration file changes)
- action:
- N/A
]

[ci][bsp][nxp] Enable CI build checks on MCXN/MCXA.

---

bsp/allwinner/d1/board/board.c
bsp/allwinner/d1s/board/board.c
bsp/bouffalo_lab/bl808/d0/board/board.c
bsp/cvitek/cv1800b/board/board.c
bsp/k210/board/board.c
bsp/qemu-virt64-riscv/driver/board.c
components/lwp/lwp_arch_comm.h
include/rthw.h
include/rtthread.h
libcpu/aarch64/common/mmu.c
libcpu/aarch64/common/mmu.h
libcpu/arm/cortex-a/mmu.h
libcpu/risc-v/t-head/c906/cpuport.h
libcpu/risc-v/t-head/c906/mmu.h
libcpu/risc-v/t-head/c906/riscv_mmu.c
libcpu/risc-v/t-head/c906/riscv_mmu.h
libcpu/risc-v/virt64/cpuport.h
libcpu/risc-v/virt64/mmu.h
libcpu/risc-v/virt64/riscv_mmu.c
libcpu/risc-v/virt64/riscv_mmu.h
src/SConscript
src/cpu.c

[
- BSP:
- .config:
- action:
]

[ci] open ci check with function declaration warning

---

bsp/nxp/mcxn/Libraries/drivers/drv_hwtimer.c
bsp/nxp/mcxn/Libraries/drivers/drv_hwtimer.h
bsp/nxp/mcxn/frdm-mcxn947/board/Kconfig

[
> 增加 MCXN HWTIMER硬件定时器支持 (Added support for MCXN HWTIMER driver)
> 请查看commit日志 (Please check commit logs)
- BSP:
- .config:
- `CONFIG_BSP_USING_HWTIMER`
- action:
- Please trigger CI run for the PR.
]

[bsp][nxp/mcxn] Add HWTIMER driver support.

---

src/kservice.c

[
- BSP:
- .config:
- action:
]

[kservice] 完善rt_vsnprintf

---

.github/workflows/bsp_buildings.yml

[
其他软件包可以通过CI触发RT-Thread的编译检查，RT-Thread BSP编译检查时会拉取最新的相关软件包进行编译。
- BSP:
- .config:
- action:
]

[ci] add online pkgs trigger event

---

bsp/nxp/mcxn/Libraries/drivers/drv_pwm.c
bsp/nxp/mcxn/Libraries/drivers/drv_pwm.h
bsp/nxp/mcxn/frdm-mcxn947/board/Kconfig
bsp/nxp/mcxn/frdm-mcxn947/board/board.c

[
> 增加 MCXN PWM 驱动 (Adds support for MCXN PWM driver)
> 请查看commit日志 (Please check commit log)
- BSP:
- .config:
- `CONFIG_BSP_USING_PWM`
- action:
- 请运行CI检查 (Please trigger CI action)
]

[bsp][nxp/mcxn] Add support for MCXN CTIMER PWM driver.

---

bsp/at32/libraries/rt_drivers/drv_usbotgh.c

[
[bsp/at32] update usb host driver
]

[bsp/at32] update usb host driver

---

components/drivers/Kconfig
components/drivers/hwtimer/Kconfig
components/drivers/hwtimer/SConscript
components/drivers/hwtimer/hwtimer-arm_arch.c
components/drivers/hwtimer/hwtimer.c
components/drivers/include/drivers/hwtimer.h
components/drivers/include/rtdevice.h
libcpu/aarch64/common/setup.c

[
- BSP:
- .config:
- action:
]

[components/drivers]update hwtimer

---

include/rthw.h

[
- BSP:
- .config:
- action:
]

[kernel] fix incorrect expression in macros

---

components/drivers/ofw/ofw.c
components/drivers/serial/SConscript
components/drivers/serial/serial_dm.c
components/drivers/serial/serial_dm.h
libcpu/aarch64/common/setup.c

[
- 采用设备树方式的 serial 框架
- BSP: rk3568
- .config:
- action:
]

[components/driver] update serial

---

bsp/cvitek/c906_little/board/Kconfig
bsp/cvitek/cv1800b/board/Kconfig
bsp/cvitek/drivers/SConscript
bsp/cvitek/drivers/cv1800b/pwm/cvi_pwm.h
bsp/cvitek/drivers/drv_pwm.c
bsp/cvitek/drivers/drv_pwm.h

[
添加 bsp/cvitek pwm 驱动
- BSP: cvitek
- .config:
- action:
]

[bsp/cvitek]add pwm driver

---

src/ipc.c
src/kservice.c

[
- BSP:
- .config:
- action:
]

[kservice]：修复关闭RT_USING_CONSOLE和RT_USING_FINSH编译有警告的BUG

---

src/SConscript

[
- BSP:
- .config:
- action:
]

[ci][kernel] only GCC use strict checking

---

bsp/cvitek/c906_little/board/Kconfig
bsp/cvitek/drivers/SConscript
bsp/cvitek/drivers/drv_wdt.c
bsp/cvitek/drivers/drv_wdt.h

[
已基于官方wdt例程进行测试，通过
- BSP:
- .config:
- action:
]

[bsp][cvitek] add wdt driver

---

include/rtdef.h
include/rtsched.h

[
- BSP:
- .config:
- action:
]

[kernel] fix warning of rt_thread_t struct

---

src/timer.c

[
- BSP:
- .config:
- action:
]

[kernel][timer] remove _timerhead_idx which is unused

---

bsp/hc32/libraries/hc32_drivers/drv_usart.c

[
函数 hc32_uart_tc_irq_handler() 是 TX 时用的，但使用了 RX 的开关。
- BSP:
- .config:
- action:
]

[BSP][HC32] drv_usart.c fix macro switch error

---

bsp/stm32/libraries/HAL_Drivers/drivers/config/f4/i2c_hard_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_hard_i2c.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_soft_i2c.c

[
- BSP:
- .config:
- action:
]

[bsp][stm32] format code of i2c hardware drivers

---

bsp/renesas/ra8d1-vision-board/README.md
bsp/renesas/ra8d1-vision-board/README_zh.md

[
- BSP:
- .config:
- action:
]

[bsp][renesas] add ra8 en docs

---

bsp/renesas/ra6m3-hmi-board/board/Kconfig
bsp/renesas/ra6m3-hmi-board/board/rtduino/arduino_pinout/pins_arduino.h

[
- BSP:
- .config:
- action:
]

[bsp][HMIBoard] config rtduino peripheral with HMI

---

components/dfs/dfs_v2/include/dfs_dentry.h
components/dfs/dfs_v2/src/dfs_dentry.c
components/dfs/dfs_v2/src/dfs_file.c

[
In `dfs_dentry_lookup`, the relative path is resolved as absolute one. So, if the basename of file has the identical prefix with the mount point, the file cannot be found in dfsv2.
In a simple test, mount tmpfs in /tmp, we can see problems like:
```text
msh />echo hello tmp/tmpfile
msh />cat tmp/tmpfile
Open tmp/tmpfile failed
msh />
```
- BSP:
- .config:
- action:
]

[dfs] fixup bugs in dfs_dentry_lookup

---

components/finsh/SConscript

[
related: https://github.com/RT-Thread/rt-thread/pull/8574
- BSP:
- .config:
- action:
]

[msh][ci]only GCC use strict checking

---

bsp/bouffalo_lab/libraries/rt_drivers/Kconfig
bsp/bouffalo_lab/libraries/rt_drivers/drv_adc.c
bsp/bouffalo_lab/libraries/rt_drivers/drv_adc.h

[
优化博流系列adc基于dma的驱动
- BSP:
- .config:
- action:
]

[bsp][bl]update adc driver

---

bsp/stm32/stm32f103-100ask-pro/board/ports/spi_flash_init.c

fix https://github.com/RT-Thread/rt-thread/issues/8605
[
- BSP:
- .config:
- action:
]

[stm32][stm32f103-100ask-pro] fix missing drv_gpio.h in spi_flash_init.c

---

bsp/essemi/es32f369x/drivers/Kconfig
bsp/essemi/es32vf2264/drivers/Kconfig
bsp/nxp/lpc/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
bsp/renesas/ra6m3-hmi-board/board/Kconfig
bsp/stm32/stm32f103-blue-pill/board/Kconfig
bsp/stm32/stm32f401-weact-blackpill/board/Kconfig
bsp/stm32/stm32f407-robomaster-c/board/Kconfig
bsp/stm32/stm32f410-st-nucleo/board/Kconfig
bsp/stm32/stm32f411-weact-blackpill/board/Kconfig
bsp/stm32/stm32f412-st-nucleo/board/Kconfig
bsp/stm32/stm32f427-robomaster-a/board/Kconfig
bsp/stm32/stm32h503-st-nucleo/board/Kconfig
bsp/stm32/stm32h563-st-nucleo/board/Kconfig
bsp/stm32/stm32l431-BearPi/board/Kconfig
bsp/stm32/stm32l475-atk-pandora/board/Kconfig
bsp/stm32/stm32u575-st-nucleo/board/Kconfig
bsp/wch/risc-v/ch32v208w-r0/board/Kconfig
bsp/wch/risc-v/ch32v307v-r1/board/Kconfig

[
- BSP:
- .config:
- action:
]

[bsp][RTduino] format Kconfig

---

components/net/netdev/src/netdev.c

[
多个netdev 存在时，删除第一个netdev, 原逻辑无法正常删除并更新netdev相关状态。
qemu 环境编译通过。
]

netdev_unreg: modyify netdev remove logical when mutil-netdev exist

---

components/drivers/misc/rt_drv_pwm.c

[
- BSP:
- .config:
- action:
]

[stm32][pwm] fix warning in Keil5

---

src/timer.c

which caused warnings when using Keil5
[
- BSP:
- .config:
- action:
]

[kernel][timer] remove unused _soft_timer_status

---

src/kservice.c

[
- BSP:
- .config:
- action:
]

[kernel] fix marcos warning in Keil5

---

bsp/cvitek/drivers/drv_rtc.c

[
CV1800B中的RTC外设具有Alarm报警的功能，此PR为其添加驱动。
bsp/cvitek/drivers/drv_rtc.c
- BSP:
- .config:
需要启用 RT_USING_ALARM
- action:
]

[bsp][CV1800B] add RTC Alarm function for CV1800B

---

include/rtthread.h
src/scheduler_comm.c
src/scheduler_mp.c
src/scheduler_up.c

[
remove the redundant definition of `_scheduler_stack_check`
Add a common definition `rt_scheduler_stack_check`
- BSP:
- .config:
- action:
]

[src] remove redundant _scheduler_stack_check

---

bsp/Infineon/libraries/HAL_Drivers/drv_hwtimer.c
bsp/Infineon/libraries/IFX_PSOC6_HAL/SConscript

[
- BSP:
- .config:
- action:
]

[bsp][driver][Infineon]Fix timer interrupt callback conflict

---

bsp/cvitek/cv1800b/board/board.c
bsp/cvitek/drivers/SConscript
bsp/cvitek/drivers/drv_por.c

[
现有的reboot的功能只是调用了sbi_shutdown()，不具备真正的reboot功能。
cv1800b中RTC模块下包含一个Power-On-Reset/POR子模块，负责上电复位。此次提交，使用POR模块提供reboot功能。
bsp/cvitek/drivers/SConscript
- BSP:
- .config:
此功能已在配置文件中默认加载。
- action:
]

[bsp][CV1800B] add POR driver which support reboot

---

libcpu/risc-v/virt64/backtrace.c

[
- BSP:
- .config:
- action:
]

[libcpu/rv64] fixup for parameter passing on backtrace

---

README.md
README_de.md
README_es.md

fix dead link to `contribution_guide.md` in
-    `README.md`
-    `README_es.md`
-   `README_de.md`
[
found 3 bad links
fix the links
- BSP:
- .config:
- action:
]

[doc] [fix] dead link in README.md + 2 files

---

components/finsh/shell.c
components/finsh/shell.h

[
To enable the custom extension for features of *finsh*.
Add finsh thread entry hook.
- BSP:
- .config:
- action:
]

[finsh] feat: add finsh thread entry hook

---

bsp/at32/libraries/rt_drivers/drv_adc.c

[
实际使用AT32芯片时，发现ADC多通道采集，存在概率性地错位问题；错位与转换完成标志有关。
软件触发前手动清除完成标志。
- BSP:bsp\at32\at32f403a-start
- .config:RT_USING_ADC
- action:
]

[bsp][at32]修复 由于ADC转换完成标志未清除 导致ADC多通道读取时 概率性地通道错位

---

bsp/nxp/mcx/mcxn/frdm-mcxn947/rtconfig.py

解决 scons 创建独立项目目录报错 `ModuleNotFoundError: No module named 'sdk_dist':`
```txt
$ scons --dist --target=mdk --project-name=rtt_mxcn947_blink --project-path=/e/DIY/FRDM-MCXN947/rtt_mxcn947_blink/
scons: Reading SConscript files ...
Keil5 project is generating...
Keil Version: 0.0
Keil-MDK project has generated successfully!
make distribution....
=> frdm-mcxn947
=> start dist handle
BSP_ROOT={BSP_ROOT}
ModuleNotFoundError: No module named 'sdk_dist':
File "E:\Opensource\rt-thread\master\bsp\nxp\mcx\mcxn\frdm-mcxn947\SConstruct", line 67:
DoBuilding(TARGET, objs)
File "E:\Opensource\rt-thread\master\tools\building.py", line 830:
EndBuilding(target, program)
File "E:\Opensource\rt-thread\master\tools\building.py", line 943:
MkDist(program, BSP_ROOT, Rtt_Root, Env, project_name, project_path) …
```

[bsp][nxp] Fix scons command can not found 'sdk_dist'

---

bsp/nxp/mcx/tools/sdk_dist.py

[
解决 scons 创建的项目目录中，运行 menuconfig 报错： 
```
$ menuconfig
Kconfig:26: can't open file "../Libraries/Kconfig"
```
scons 创建项目过程的最后，修改项目目录的Kconfig文件，
将其中的 `../Libraries/Kconfig` 替换为 `Libraries/Kconfig`。
参考了 nxp/lpc/lpc55sxx/tools/sdk_dist.py ，并进行了精简和美化。
- BSP: bsp/nxp/mcx/mcxn/frdm-mcxn947
- .config: 无关
- action: 暂无
]

[bsp][nxp] Fix menuconfig error in scons created project

---

bsp/renesas/ra6m3-hmi-board/.project

[
修改ra6m3-hmi-board的.project文件，删除其中重复的配置代码
将重复的那行删除
- BSP: bsp/renesas/ra6m3-hmi-board
- .config:无关
- action:暂无
]

[bsp][renesas]Redundant configuration information is removed

---

bsp/nxp/mcx/mcxn/Libraries/drivers/SConscript
bsp/nxp/mcx/mcxn/Libraries/drivers/drv_dac.c
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/Kconfig
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/MCUX_Config/board/pin_mux.c

[
frdm-mcxn947
公版增加dac驱动
增加dac驱动
- BSP: /bsp/nxp/mcx/mcxn/frdm-mcxn947
- .config:
- CONFIG_BSP_USING_DAC --> y
- CONFIG_BSP_USING_DAC0 --> y
-
注： 由于目前pin_mux.c未对相关功能用宏包裹，出于与原工程配置风格一致原则，默认增加一个注释的dac使能配置，验证时需注释已有的PORT4->PCR[2]配置，并将 DAC0的PORT4->PCR[2]解除注释
- action:
]
- [*] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [*] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [*] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not …

frdm-mcxn947 增加dac驱动

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_rtc.c

[
- BSP:
- .config:
- action:
]

[bsp][stm32] 添加board.h中包含drv_common.h 避免找不到 error_handle实现

---

bsp/wch/risc-v/ch32v307v-r1/.cproject
bsp/wch/risc-v/ch32v307v-r1/.project
bsp/wch/risc-v/ch32v307v-r1/.settings/ilg.gnumcueclipse.managedbuild.cross.arm.prefs
bsp/wch/risc-v/ch32v307v-r1/.settings/ilg.gnumcueclipse.managedbuild.cross.riscv.prefs
bsp/wch/risc-v/ch32v307v-r1/.settings/language.settings.xml
bsp/wch/risc-v/ch32v307v-r1/.settings/local_temp_storage.prefs
bsp/wch/risc-v/ch32v307v-r1/.settings/org.eclipse.core.runtime.prefs
bsp/wch/risc-v/ch32v307v-r1/.settings/projcfg.ini
bsp/wch/risc-v/ch32v307v-r1/Kconfig
bsp/wch/risc-v/ch32v307v-r1/rtconfig_preinc.h

[
修复ch32v307 bsp从studio导入后发生的编译错误，同时使能C++后正常编译执行
- BSP:
- .config:
- action:
]

[bsp][ch32] Fixed the issue that importing ch32v307 project into studio would not compile

---

bsp/nxp/imx/imx6ull-smart/.config
bsp/nxp/imx/imx6ull-smart/drivers/board.c
bsp/nxp/imx/imx6ull-smart/drivers/drv_sdio.c
bsp/nxp/imx/imx6ull-smart/rtconfig.py
components/finsh/shell.c

[
更新ART-PI的主线rt-smart模式代码，启动信息如下：
]

[rt-smart][art-pi] update bsp ART-PI rt-smart project

---

bsp/renesas/ra6m3-hmi-board/.cproject
bsp/renesas/ra6m3-hmi-board/.settings/projcfg.ini

[
1.修复hmi-board导入studio后无法显示fsp配置问题
2.删除软件spi中的冗余代码
- BSP:
- .config:
- action:
]

[bsp][renesas] Fixed some problems after importing HMI-Board into studio

---

libcpu/aarch64/common/context_gcc.S

[
Improve performance of IRQ dis/en-able.
Since `rt_hw_interrupt_disable()` is allowed to be nested,
there are many unnecessary operations on the system
register to dis/en-able IRQ. This significantly decreases
system performance on a modern high-performance
platform since it will flush the CPU pipeline.
- In the test base on a quadcore cortex-a55 platform, this patch decrease ~20% of the sem_take latency.
- BSP:
- .config:
- action:
]

[libcpu/aarch64] improve performance of IRQ dis/en-able

---

bsp/essemi/es32f369x/applications/arduino_pinout/SConscript
bsp/essemi/es32vf2264/applications/arduino_pinout/SConscript
bsp/nxp/lpc/lpc55sxx/lpc55s69_nxp_evk/applications/arduino_pinout/SConscript
bsp/raspberry-pico/applications/arduino_pinout/SConscript
bsp/stm32/stm32f072-st-nucleo/applications/arduino_pinout/SConscript
bsp/stm32/stm32f103-blue-pill/applications/arduino_pinout/SConscript
bsp/stm32/stm32f401-st-nucleo/applications/arduino_pinout/SConscript
bsp/stm32/stm32f401-weact-blackpill/applications/arduino_pinout/SConscript
bsp/stm32/stm32f407-robomaster-c/applications/arduino_pinout/SConscript
bsp/stm32/stm32f410-st-nucleo/applications/arduino_pinout/SConscript
bsp/stm32/stm32f411-st-nucleo/applications/arduino_pinout/SConscript
bsp/stm32/stm32f411-weact-blackpill/applications/arduino_pinout/SConscript
bsp/stm32/stm32f412-st-nucleo/applications/arduino_pinout/SConscript
bsp/stm32/stm32f427-robomaster-a/applications/arduino_pinout/SConscript
bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/SConscript
bsp/stm32/stm32g474-st-nucleo/applications/arduino_pinout/SConscript
bsp/stm32/stm32h503-st-nucleo/applications/arduino_pinout/SConscript
bsp/stm32/stm32h563-st-nucleo/applications/arduino_pinout/SConscript
bsp/stm32/stm32l431-BearPi/applications/arduino_pinout/SConscript
bsp/stm32/stm32l475-atk-pandora/applications/arduino_pinout/SConscript
bsp/stm32/stm32l476-st-nucleo/applications/arduino_pinout/SConscript
bsp/stm32/stm32u575-st-nucleo/applications/arduino_pinout/SConscript
bsp/wch/risc-v/ch32v208w-r0/applications/arduino_pinout/Sconscript
bsp/wch/risc-v/ch32v307v-r1/applications/arduino_pinout/Sconscript

[
- BSP:
- .config:
- action:
]

[RTduino] change the pinout group name

---

components/drivers/misc/rt_drv_pwm.c

[
- BSP:
- .config:
- action:
]

[devcie][pwm] fix warnings

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_spi.c

cherry-pick: https://github.com/wdfk-prog/ART-PI/commit/b6f896e9979a4d529fe1ecd6e056fb96fbcf9eb7
[
- BSP:
- .config:
- action:
]

[bsp][stm32][spi] 优化H7 DMA数据非字节对齐的处理流程

---

bsp/renesas/libraries/HAL_Drivers/drv_gpio.c
bsp/renesas/ra6m3-hmi-board/board/rtduino/arduino_pinout/pins_arduino.c

[
1.修改drv_gpio.c：R_IOPORT_Open()函数只需执行一次，修改位置为init时执行
2.默认HMI-Board使能rtduino后支持soft spi，通过switch_pwm可切换为pwm功能
- BSP:
- .config:
- action:
]

[bsp][renesas] rtduino supports the soft spi switch to pwm function

---

components/finsh/finsh.h

[
- BSP:
- .config:
- action:
]

[finsh] remove finsh_syscall_lookup() function declaration

---

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript
bsp/wch/risc-v/Libraries/ch32_drivers/drv_i2c.c
bsp/wch/risc-v/Libraries/ch32_drivers/drv_i2c.h
bsp/wch/risc-v/ch32v307v-r1/board/Kconfig

添加了CH32V30系列适配RT-Thread的硬件I2C驱动。
Added hardware I2C driver for CH32V30 series adapted to RT-Thread.
根据CH32V30数据手册、I2C总线协议和RT-Thread提供的I2C总线接口实现适配
Implement adaptation based on the CH32V30 datasheet, I2C bus protocol and the I2C bus interface provided by RT-Thread.
- BSP:
bsp/wch/risc-v/ch32v307v-r1
- .config:
添加了 drv_i2c.h 和 drv_i2c.c 文件；
修改了 rt-thread/bsp/wch/risc-v/ch32v307v-r1/board 目录下的 Kconfig 文件；
修改了 rt-thread/bsp/wch/risc-v/Libraries/ch32_drivers 目录下的 SConscript 文件。
- action:
https://github.com/IceBear003/rt-thread/actions/runs/8498460155

[bsp][ch32v307v]添加了硬件iic驱动

---

bsp/cvitek/README.md
bsp/cvitek/c906_little/board/Kconfig
bsp/cvitek/cv180x/board/Kconfig
bsp/cvitek/drivers/SConscript
bsp/cvitek/drivers/drv_spi.c
bsp/cvitek/drivers/drv_spi.h

[
为cv180x系列soc添加spi驱动。
- BSP:
- .config:
- action:
]

[bsp][CV1800B] add SPI driver for CV1800B

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_hard_i2c.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_hard_i2c.h

[bsp][stm32] fix hardware i2c driver bug

---

components/drivers/serial/serial.c
libcpu/aarch64/common/context_gcc.S

[
- BSP:
- .config:
- action:
]

fix: code format of serial.c and compile error in aarch64 context_gcc

---

src/signal.c

[
在使用utest进行第二次测试SIGNAL时，测试未通过，但是utest返回测试通过，主要有三个问题。
1. 内核里的rt_signal_kill函数中分配SIGNAL节点失败时打印错误信息后没有返回。
2. 下图中的线程运行1秒后已经退出了，等待2秒后发送SIGNAL给线程是异常操作，该线程的资源已经被回收处理了。
3. 给某个线程发送消息，但是这个线程又没有处理的情况下，会导致该资源无法被回收。
1. 第一个问题只需要返回错误即可。
2. 第二个问题和跟第三个问题需要同时解决，暂时没有好的办法，主要是发送函数这里不知道怎么处理。
- BSP: qemu-vexpress-a9
- .config:
- action:
]

[kernel]SIGNAL节点分配失败应该返回错误

---

tools/install_env.py

添加env安装脚本，在Windows/powershell下验证通过。

[tools] Add install env script

---

bsp/nxp/mcx/mcxn/Libraries/drivers/drv_spi.c
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/Kconfig
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/MCUX_Config/board/pin_mux.c

[
添加 SPI1 引脚配置到FRDM-MCXN947 BSP，为后续提交RW007模块（Arduino接口）驱动做准备。
* 添加了FRDM-MCXN947板子Arduino接口上的D11、D12、D13初始化为FlexCOMM1的P0、P1、P2；
* 修改了drv_spi.c，添加了SPI1配置，用于将FlexCOMM1初始化为SPI1，并设置时钟源；
- BSP: bsp/nxp/mcx/mcxn/frdm-mcxn947
- .config: BSP_USING_SPI1
- action:
]

[bsp][nxp] Add SPI1 config for FRDM-MCXN947 board

---

components/libc/compilers/dlib/SConscript

[
- BSP:
- .config:
- action:
]

[iar] fix legacy macros will be added if cannot get the IAR version

---

components/drivers/i2c/SConscript
components/drivers/i2c/i2c_bus.c
components/drivers/i2c/i2c_core.c
components/drivers/i2c/i2c_dm.c
components/drivers/i2c/i2c_dm.h
components/drivers/include/drivers/i2c.h
components/drivers/include/drivers/i2c_dm.h
components/drivers/include/rtdevice.h

[
- BSP:
- .config:
- action:
]

[components][drivers]add ofw support i2c

---

bsp/renesas/ra6m3-hmi-board/board/rtduino/arduino_pinout/pins_arduino.c

增加switchToPWM不是一个好方案，已经与玉强和阳阳商量过，在软件SPI和IIC设备框架上做修改。
https://github.com/RTduino/RTduino/commit/c73c7b12651cb5ec3e44a024091cd07a5cd49b6c
[
- BSP:
- .config:
- action:
]

[hmi-board][rtduino] remove switchToPWM

---

components/drivers/can/can.c

[
- BSP:
- .config:
- action:
]

[components][drivers]fix compile warning in 64 bits arch cpu

---

components/libc/posix/io/poll/select.c
components/libc/posix/io/signalfd/signalfd.c

[
modified: components/libc/posix/io/signalfd/signalfd.c Add all function comments
modified: components/libc/posix/io/poll/select.c Add all function comments
]

 Add some function comments

---

bsp/nxp/lpc/lpc55sxx/Libraries/drivers/drv_soft_spi.c
bsp/raspberry-pico/drivers/drv_soft_spi.c
bsp/renesas/libraries/HAL_Drivers/drv_soft_spi.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_soft_spi.c
bsp/wch/risc-v/Libraries/ch32_drivers/drv_soft_spi.c
components/drivers/spi/spi-bit-ops.c
components/drivers/spi/spi-bit-ops.h

[
ps：在设备初始化阶段不应该存在对硬件的操作
ps：添加一个pin_init函数，在spi设备使用时调用该函数来完成硬件引脚的状态初始化，而不是在设备初始化阶段对硬件进行操作，已经在瑞萨HMI上通过验证
- BSP:
- .config:
- action:
]

[driver][soft-spi] spi device driver framework adds pin init function function

---

components/dfs/dfs_v2/include/dfs_file.h
components/dfs/dfs_v2/src/dfs_file.c
components/dfs/dfs_v2/src/dfs_posix.c

fix dfs pread/pwrite.

---

src/scheduler_up.c

[
函数 rt_exit_critical_safe 应是没有返回值的，rt_exit_critical() 也是没返回值的
- BSP:
- .config:
- action:
]

[src][scheduler]修复 rt_exit_critical_safe 函数错误地使用了返回

---

include/rttypes.h

[
Fixup #8758
- BSP:
- .config:
- action:
]

[include] using signed atomic types

---

components/drivers/can/can.c

[
- BSP:
- .config:
- action:
]

[components][drivers][can]fix can warning in 64bit cpu

---

bsp/nxp/mcx/mcxn/Libraries/drivers/drv_spi.c
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/MCUX_Config/board/pin_mux.c
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/SConscript
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/ports/drv_spi_sample_rw007.c

[
- BSP:
- .config:
- action:
]

[bsp][nxp] 增加drv_spi_sample_rw007驱动

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_lcd.c

```diff
else if (lcd->lcd_info.pixel_format == RTGRAPHIC_PIXEL_FORMAT_RGB888)
{
pLayerCfg.PixelFormat = LTDC_PIXEL_FORMAT_RGB888;
}
-    else if (lcd->lcd_info.pixel_format == RTGRAPHIC_PIXEL_FORMAT_RGB888)
-    {
-        pLayerCfg.PixelFormat = LTDC_PIXEL_FORMAT_RGB888;
-    }
```

[bsp/stm32] remove duplicate if condition

---

bsp/tm4c123bsp/board/Kconfig
bsp/tm4c123bsp/board/board.c
bsp/tm4c123bsp/board/board.h
bsp/tm4c123bsp/board/tm4c123_config.c
bsp/tm4c123bsp/board/tm4c123_config.h
bsp/tm4c123bsp/libraries/Drivers/SConscript
bsp/tm4c123bsp/libraries/Drivers/config/i2c_config.h
bsp/tm4c123bsp/libraries/Drivers/drv_i2c.c
bsp/tm4c123bsp/libraries/Drivers/drv_i2c.h
bsp/tm4c123bsp/libraries/TivaWare_C_series/SConscript
bsp/tm4c123bsp/libraries/TivaWare_C_series/tm4c123_driverlib/startup/gcc/startup_gcc.c

[bsp/tm4c123] add hardware i2c support

---

src/mem.c

[
- https://github.com/RT-Thread/rt-thread/issues/8761
- BSP: bsp/stm32/stm32h750-artpi
- .config:
CONFIG_RT_USING_SMALL_MEM=y
CONFIG_RT_USING_SMALL_MEM_AS_HEAP=y
PR branch:
- https://github.com/wdfk-prog/ART-PI/commit/8bc4f2cee1b02a9236c6d0c77acd83e2dde5b5e0
]

[mem] Modify macro definitions for better code reading

---

components/drivers/serial/serial_tty.c

[
当使用新device model时，serial的名字由系统分配，id也由系统分配，此时应根据系统分配的serial id来作为serial-tty的id
增加使用dm时的tty名字分配机制
- BSP:
- .config:
- action:
]

[component][driver][serial/tty]using serial name to name tty

---

bsp/stm32/stm32f103-fire-arbitrary/board/ports/spi_flash_init.c

[
- BSP:
- .config:
- action:
]

[bsp][stm32f103-fire-arbitrary] fix missing header file

---

libcpu/aarch64/common/setup.c

[
- BSP:
- .config:
- action:
]

[libcpu][aarch64]fix memheap search in setup of aarch64

---

include/rtdef.h
src/Kconfig

[
- BSP:
- .config:
- action:
]

upgrade RT-Thread version to v5.2.0

---

components/net/sal/include/sal_msg.h

添加AF_UNIX协议的消息数量限制(类似于网络滑动窗口大小)
添加一个计数器对消息读写计数
- BSP:
- .config:
- action:
]

Increased the limit on the number of messages

---

include/rthw.h

[
- BSP:
- .config:
- action:
]

[kernel][include]add rt_hw_interrupt_uninstall declare in rthw

---

components/dfs/dfs_v2/src/dfs_posix.c

[
fix chdir for ash's cd
use rt_set_errno
- BSP:rt-thread/bsp/qemu-virt64-aarch64
- .config:
- action:
]

fix chdir for ash's cd

---

components/utilities/ulog/ulog.c

[
解决LOG_RAW异步输出多条文本的时候会被截断，原因是rt_vsnprintf会在字符串最后添加\0，ulog.c中的do_output()将\0也压入到ulog.async_rb，当LOG_RAW没有及时输出，那么rb中的字符串被\0截断了，导致没法正确输出LOG_RAW信息
修该ulog.c文件，不要将\0压入ulog.async_rb，也就是log_buf_size和fmt_result两个长度不要统计\0
- BSP:  STM32H753，STM32F765
- .config: 没有修改
- action: https://github.com/Later-Comer/rt-thread/actions/runs/8748306763/job/24008140926
]

解决LOG_RAW异步输出多条文本的时候会被截断BUG

---

components/drivers/serial/serial_tty.c

[
Mutex lock should be taken before release the TTY device.
- BSP:
- .config:
- action:
]

[smart] fixup rt_hw_serial_unregister_tty of serial tty

---

bsp/nxp/mcx/mcxn/frdm-mcxn947/board/Kconfig

[
1. 在用户只选中`BSP_USING_SPI`选项时，编译运行会报错；
a. 因为目前FRDM-MCXN947开发板SPI驱动的片选信号（CS）控制使用了rt_pin_xxx接口，但是不手动选中不会打开；
2. 在用户只选中`BSP_USING_RW007`选项时，编译运行会又类似的报错；
a. 因为rw007模组SPI驱动依赖SPI驱动，SPI驱动默认没有自动使能pin驱动，和上面类似；
b. 另外复位控制（RST）和中断信号（INT）也使用了rt_pin_xxx，因此需要给添加`select BSP_USING_PIN`；
1. 给`BSP_USING_SPI`选项添加`select BSP_USING_PIN`； 
2. 给`BSP_USING_RW007`选项添加`select BSP_USING_PIN`；
- BSP: bsp/nxp/mcx/mcxn/frdm-mcxn947
- .config: BSP_USING_RW007
- action:
]

[bsp][nxp] Add select BSP_USING_PIN for BSP_USING_SPI

---

.clang-format
bsp/.clang-format
bsp/acm32/acm32f0x0-nucleo/libraries/HAL_Driver/Src/HAL_RTC.c
bsp/acm32/acm32f4xx-nucleo/libraries/HAL_Driver/Src/HAL_I2S.c
bsp/acm32/acm32f4xx-nucleo/libraries/HAL_Driver/Src/HAL_LPUART.c
bsp/acm32/acm32f4xx-nucleo/libraries/HAL_Driver/Src/HAL_RTC.c
components/dfs/dfs_v1/filesystems/elmfat/.clang-format
components/dfs/dfs_v2/filesystems/elmfat/.clang-format
components/net/lwip/.clang-format
tools/kconfig-frontends/.clang-format
tools/release/README.md
tools/release/run-clang-format.py

[
目前rtt仓库中的代码没有真正意义的格式化，每个人提交的代码风格都有一定差异，但是部分开发者使用的IDE集成了自动格式化工具（比如clang-format），当这部分开发者使用IDE时候会自动格式化代码，但是格式化风格可能不满足RTT的要求，因此会出现调试一个工具，编辑一个工具，格式化还有换成另外一个，会增加提交PR的复杂性。
clang-format目前具有很广泛的应用性，支持绝大部分主流的IDE，且格式化风格定制型很强。
在根目录增加了.clang-format，并尽量配置成当前RTT所使用的风格。在不需要格式化的bsp/lwip/elmfat等目录增加.clang-format并配置为DisableFormat，在不需要格式化的代码片段可以包裹// clang format off/on的方式
开发者使用IDE的话，比如VScode、keil等可以配置为保存的时候自动使用clang-format进行格式化。
官方发布release的时候或者定期，使用tools/run-clang-format.py对仓库中的代码进行格式化。
首次格式化，大概由1000多个文件会被调整，其中部分格式化可能不满意，可能需要对代码进行微调，比如while(true);最好调整为while(true){}
- BSP:
- .config:
- action:
]

添加.clang-format配置，支持IDE或者手动进行代码格式化

---

bsp/renesas/ra8d1-ek/script/fsp.ld
bsp/renesas/ra8d1-vision-board/script/fsp.ld

添加finsh相关段信息
[
- BSP:
- .config:
- action:
]

[bsp][renesas]Link script adds finsh related sections.

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_spi.c

[
- STM32H7的SPI DMA接收会一直读取数据错误
- https://club.rt-thread.org/ask/question/2c0715f7df9fc41e.html
- fix:[DMA SPI]特定条件下接收错误
- BSP: bsp/stm32/stmh750 ART-PI
- 驱动SPI-FLASH无异常,可正常读取
- **但该场景无法进入修改部分,无法验证是否可行**
]

fix:[DMA SPI]特定条件下接收错误

---

components/libc/posix/ipc/semaphore.c

[
Add some comments in components/libc/posix/ipc/semaphore.c
]

Add some comments in components/libc/posix/ipc/semaphore.c

---

.github/workflows/doxygen.yml

[
related: https://github.com/RT-Thread/rt-thread/commit/57d157b8ab8718de1230d071f96af8400195af64
fix: https://github.com/RT-Thread/rt-thread/issues/8851
- BSP:
- .config:
- action:
]

[ci] fix doxygen ci grammar error

---

components/drivers/serial/serial_tty.c

[
- Using param callback to reduce unnecessary call
- BSP:
- .config:
- action:
]

[smart] fix tty serial ioctl

---

components/dfs/dfs_v2/filesystems/devfs/devfs.c

[
- BSP:
- .config:
- action:
]

[components][dfs]remove duplicate lseek in devfs

---

components/lwp/lwp_syscall.c

[
sys_getcwd return a wrong type
modify return type 
- BSP:rt-thread/bsp/nxp/imx/imx6ull-smart
- .config:
- action:
]

fix sys_getcwd

---

components/libc/posix/io/termios/termios.c

[
Add comments for all functions in components/libc/posix/io/termios/termios.c
]

Add comments for all functions in components/libc/posix/io/termios/termios.c

---

src/scheduler_mp.c

[
当线程是ready状态时bindcpu，代码如下
```
/* remove from old ready queue */
rt_sched_remove_thread(thread);
/* change thread bind cpu */
RT_SCHED_CTX(thread).bind_cpu = cpu;
/* add to new ready queue */
rt_sched_insert_thread(thread);
```
但rt_sched_insert_thread中，直接忽略ready状态的线程
```
static void _sched_insert_thread_locked(struct rt_thread *thread)
{
int cpu_id;
int bind_cpu;
rt_uint32_t cpu_mask;
if ((RT_SCHED_CTX(thread).stat & RT_THREAD_STAT_MASK) == RT_THREAD_READY)
{
/* already in ready queue */
return ;
}
```
导致该线程最后不在调度队列里
首先先去除ready状态
- BSP:
- .config:
- action:
]

[src][thread]bind cpu fixup

---

components/dfs/dfs_v2/src/dfs_file_mmap.c
components/dfs/dfs_v2/src/dfs_pcache.c

[
init mmap go wrong
fix file mmap
- BSP:rt-thread/bsp/nxp/imx/imx6ull-smart
- .config:
- action:
]

fix file mmap

---

.github/workflows/bsp_buildings.yml
.github/workflows/bsp_buildings_env15x.yml

[
- BSP:
- .config:
- action:
]

[ci] add workflow to check env 1.5.x stable version

---

bsp/nxp/lpc/lpc55sxx/Libraries/drivers/drv_soft_spi.c
bsp/raspberry-pico/drivers/drv_soft_spi.c
bsp/renesas/libraries/HAL_Drivers/drv_soft_spi.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_soft_spi.c
bsp/stm32/stm32f407-rt-spark/applications/arduino_pinout/pins_arduino.c
bsp/wch/risc-v/Libraries/ch32_drivers/drv_soft_spi.c

…tialized to 0.
[
- BSP:
- .config:
- action:
]

The soft_spi_pin_init loop variable is initialized to 0.

---

components/drivers/include/drivers/sensor_v2.h
components/drivers/sensor/v2/sensor.c
components/libc/posix/io/termios/termios.c

[
通过注册的sensor名称不能找到相应的设备指针
新增rt_sensor_t rt_sensor_device_find(const char *name)函数，该函数在传入的名称前面加入传感器名称，然后遍历所有设备
- BSP:
- .config:
- action:
]

[components][drivers] added sensor device lookup function

---

bsp/Infineon/libraries/HAL_Drivers/drv_soft_i2c.c
bsp/acm32/acm32f0x0-nucleo/drivers/Kconfig
bsp/acm32/acm32f0x0-nucleo/drivers/drv_soft_i2c.c
bsp/acm32/acm32f0x0-nucleo/drivers/drv_soft_i2c.h
bsp/airm2m/air32f103/libraries/rt_drivers/drv_soft_i2c.c
bsp/apm32/libraries/Drivers/drv_soft_i2c.c
bsp/at32/libraries/rt_drivers/drv_soft_i2c.c
bsp/at91/at91sam9260/drivers/at91_i2c_gpio.c
bsp/at91/at91sam9g45/drivers/at91_i2c_gpio.c
bsp/avr32/drivers/drv_soft_i2c.c
bsp/bluetrum/libraries/hal_drivers/drv_soft_i2c.c
bsp/bouffalo_lab/libraries/rt_drivers/drv_soft_i2c.c
bsp/gd32/arm/libraries/gd32_drivers/drv_soft_i2c.c
bsp/gd32/risc-v/libraries/gd32_drivers/drv_soft_i2c.c
bsp/hc32/libraries/hc32_drivers/drv_soft_i2c.c
bsp/hk32/libraries/rt_drivers/drv_soft_i2c.c
bsp/loongson/ls1cdev/drivers/drv_i2c.c
bsp/n32/libraries/n32_drivers/drv_i2c.c
bsp/n32g452xx/Libraries/rt_drivers/drv_soft_i2c.c
bsp/raspberry-pico/drivers/drv_soft_i2c.c
bsp/renesas/libraries/HAL_Drivers/drv_soft_i2c.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_soft_i2c.c
bsp/synwit/libraries/SWM320_drivers/drv_soft_i2c.c
bsp/w60x/drivers/drv_soft_i2c.c
bsp/wch/risc-v/Libraries/ch32_drivers/drv_soft_i2c.c
components/drivers/i2c/i2c-bit-ops.c
components/drivers/include/drivers/i2c-bit-ops.h

[
- BSP:
- .config:
- action:
]

Adjust the timing for I2C initialization.

---

.github/workflows/bsp_buildings.yml

[
[bsp/at32] add at32 bsp to auto ci
]

[bsp/at32] add at32 bsp to auto ci

---

components/libc/posix/libdl/dlmodule.c
include/rtthread.h
src/thread.c

[
This patch introduces a new function `rt_thread_close()` to enhances the usability and maintainability by providing a dedicated mechanism for closing threads.
- A new function `rt_thread_close()` is added to the API, providing a standardized approach for closing threads.
- The `rt_thread_close()` function removes a thread from the thread queue, updates its status to indicate closure, and performs the thread timer detaching which is a embedded timer in thread object.
- Additionally, the `_thread_detach()` function is modified to utilize `rt_thread_close()` internally, streamlining the thread detachment process.
- BSP:
- .config:
- action:
]

[thread] Add rt_thread_close()

---

tools/building.py
tools/options.py
tools/utils.py
tools/vsc.py

添加--cdb命令行参数以产生compile_commands.json文件，同时在vscode配置中也加入这个文件。

[tools] Add --cdb to make compile_commands.json.

---

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript
bsp/wch/risc-v/Libraries/ch32_drivers/drv_usbd.c
bsp/wch/risc-v/Libraries/ch32_drivers/drv_usbd.h
bsp/wch/risc-v/Libraries/ch32_drivers/drv_usbh.c
bsp/wch/risc-v/Libraries/ch32_drivers/drv_usbh.h
bsp/wch/risc-v/Libraries/ch32v30x_libraries/ch32v307_hal/include/ch32v30x_usb.h
bsp/wch/risc-v/ch32v307v-r1/board/Kconfig

添加了CH32V30系列适配RT-Thread的全速USB驱动。
Added full speed usb driver for CH32V30 series adapted to RT-Thread.
注：由于上一pr掺杂了无关的commit，故另开此新pr
- BSP:
bsp/wch/risc-v/ch32v307v-r1
- .config:
添加了 drv_usbd.h、drv_usbd.c、drv_usbh.h、drv_usbh.c 文件；
添加了 rt-thread/bsp/wch/risc-v/Libraries/ch32v307_hal/include 目录下 ch32v30x_usb.h 文件；
修改了 rt-thread/bsp/wch/risc-v/ch32v307v-r1/board 目录下的 Kconfig 文件；
修改了 rt-thread/bsp/wch/risc-v/Libraries/ch32_drivers 目录下的 SConscript 文件。
- action:
https://github.com/IceBear003/rt-thread/actions/runs/8899270620

[bsp][ch32v307]添加了适配RT-Thread的全速USB驱动

---

bsp/stm32/libraries/HAL_Drivers/drivers/config/f4/i2c_hard_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_hard_i2c.c

问题：
在使用硬件 I2C 驱动进行音频模块 WM8978 配置时，发现连续 rt_i2c_transfer 进行 I2C 传输时发现，连续多次调用 rt_i2c_transfer 会出现丢包现象；溯源发现是每次使用 rt_i2c_transfer 传输2字节，传输频率过高导致底层 HAL_I2C_Master_Seq_Transmit_DMA 报错 HAL_BUSY；
现象：
rt_completion_wait超时等待完成之后，I2C仍处于HAL_I2C_STATE_BUSY_TX状态，且后续第二次运行至HAL_I2C_Master_Seq_Transmit_DMA时会直接返回HAL_BUSY，从而直接 goto out; 退出而不会再次进行超时等待；
解决方案：
硬件 I2C 驱动中每次传输均有超时等待时间，原代码中设置为 (传输字节数/8+1)，当传输字节过少时，连续传输无法在超时等待时间（此时为1）内完成传输，因此会出现 HAL_BUSY，因此增加超时等待时间为（传输字节数/8+5），增加超时等待时间后一切均正常；

I2c hard driver fixup：增加硬件I2C传输超时等待时间

---

components/utilities/utest/utest_log.h
include/rtthread.h
src/Kconfig

[
make RT_ASSERT independent of RT_USING_DEUBG
- BSP:
- .config:
- action:
]

[src][Kconfig]make RT_ASSERT independent of RT_USING_DEUBG

---

bsp/stm32/stm32l412-st-nucleo/SConstruct
bsp/stm32/stm32l431-BearPi/SConstruct
bsp/stm32/stm32l431-tencentos-tiny-EVB_MX+/SConstruct
bsp/stm32/stm32l432-st-nucleo/SConstruct
bsp/stm32/stm32l433-ali-startkit/SConstruct
bsp/stm32/stm32l433-st-nucleo/SConstruct
bsp/stm32/stm32l452-st-nucleo/SConstruct
bsp/stm32/stm32l475-atk-pandora/SConstruct
bsp/stm32/stm32l475-st-discovery/SConstruct
bsp/stm32/stm32l476-st-nucleo/SConstruct
bsp/stm32/stm32l496-ali-developer/SConstruct
bsp/stm32/stm32l496-st-discovery/SConstruct
bsp/stm32/stm32l496-st-nucleo/SConstruct
bsp/stm32/stm32l4r5-st-nucleo/SConstruct
bsp/stm32/stm32l4r9-st-eval/SConstruct
bsp/stm32/stm32l4r9-st-sensortile-box/SConstruct

[
- BSP:
- .config:
- action:
]

[stm32l4] export env

---

README.md
README_de.md
README_es.md
README_zh.md

源代码目录结构介绍左侧一栏应该与 rt-thread 源码目录名称一一对应，统一使用小写字母，且不需要翻译。

docs: fix source code catalog Name item

---

components/drivers/serial/serial.c

fix_serial_baudrate_set

---

src/timer.c

[
- BSP:
- .config:
- action:
]

[kernel][timer] remove wordy logs

---

bsp/at32/libraries/rt_drivers/drv_usart_v2.c

[
AT32使用UART设备V2版本时出现编译报错。
修改at32_transmit的返回类型，由rt_size_t改为rt_ssize_t。
- BSP:bsp/at32/at32f425-start
- .config:
- action:
]

[bsp][at32]修复at32_transmit返回类型错误

---

src/kservice.c

[
修复将 assert hook等放入RT_DEBUGING_ASSERT宏中
]

fix RT_DEBUGING_ASSERT

---

components/lwp/arch/arm/cortex-a/lwp_arch.c
components/lwp/lwp_user_mm.c
libcpu/aarch64/common/context_gcc.S
src/thread.c

[
Reduce unnecessary checks to improve efficiency in the context switching process.
- In lwp_user_mm.c, optimized the logic for determining address space switching, reducing unnecessary operations.
- In thread.c, optimized the thread signal checks if it not belongs to process.
- BSP:
- .config:
- action:
]

[smart] fixup arm64 aspace switch

---

components/drivers/pic/pic.c

[
pic中添加各cpu的中断信息
- BSP:
- .config:
- action:
]

[components][drivers]add percpu interrupt info

---

include/rtthread.h

[
未定义RT_USING_HEAP时，thread.c里会出现在声明前调用rt_thread_close的情况，编译器用C89标准编译会报警告，用C99标准编译会报错
- BSP:
- .config:
- action:
]

[include/rtthread.h] rt_thread_close函数声明应当与RT_USING_HEAP无关

---

bsp/cvitek/cv18xx_risc-v/applications/main.c
bsp/cvitek/drivers/SConscript
bsp/cvitek/drivers/drv_gpio.c

[
更新 bsp/cvitek gpio 驱动
- BSP: cvitek
- .config:
- action:
]

[bsp/cvitek]update gpio driver

---

components/drivers/serial/serial_tty.c

[
原先获取串口tty配置时，会将传入的termios结构体清空，然后重新设置，但这会使原先的一些termios配置均删去。
硬件层只用来获取波特率等配置
- BSP:
- .config:
- action:
]

[drivers][serial]fix error in getting serial_tty settings

---

bsp/nxp/imx/imx6ull-smart/drivers/board.c
components/net/netdev/src/netdev.c

[
Specified network card not taking effect with msh's ping.
When isbind is TRUE, use lwip_setsockopt's SO_BINDTODEVICE option to set.
- BSP:rt-thread/bsp/nxp/imx/imx6ull-smart
- .config:
- action:
]

fix specified network card not taking effect with msh's ping error

---

bsp/hc32/libraries/hc32_drivers/drv_flash/drv_flash_f4.c

[ drv_flash_f4.c: Fixed a bug about erase flash. ]
- [ ✔ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [ ✔] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ✔] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ✔] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ✔] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ✔] 代码是高质量的 Code in this PR is of high quality
- [✔ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contri …

[HC32] Fixed a bug about erase flash.

---

tools/cmake.py

[
When generating cmake projects, only `LFLAGS` in `rtconfig.py` added to `CMakeLists.txt`. But some link flags are added by editing `env['LINKFLAGS']` in `Sconscript`, so these link flags are not included in `CMakeLists.txt`.
Simply read `env['LINKFLAGS']` instead of `rtconfig.LFLAGS`.
(Maybe more works can be done there, e.g., deduplicate flags.)
- BSP:
- .config:
- action:
]

[tools/cmake] fix the issue of the missing link flags added in Sconscript

---

components/drivers/include/drivers/mmc.h
components/drivers/include/drivers/mmcsd_card.h
components/drivers/include/drivers/mmcsd_host.h
components/drivers/sdio/mmc.c

- added HS400 supprt (both eMMC5.0 and eMMC5.1 flavor are supported)
[
- add HS400 support according to eMMC5.1 spec
- tested on HPM6800EVK
]

[components][drivers][mmc] add HS400 support to mmc driver

---

components/drivers/include/drivers/pic.h
components/drivers/pic/pic-gic-common.c
components/drivers/pic/pic-gic-common.h
components/drivers/pic/pic-gicv2.c
components/drivers/pic/pic-gicv3.c
components/drivers/pic/pic.c

[
1. Make affinity helper interface
2. Fixup GIC affinity init:
GICv2 is not support affinity config if current CPU is not startup, but RT-Thread SMP is startup after the devices init
in the `main` thread. This patch fixup the cpumask to init once and check the init status in affinity interface.
]

 [PIC] Make affinity helper interface

---

components/lwp/terminal/freebsd/tty_compat.c

[
- BSP:
- .config:
- action:
]

[smart] add FIONREAD ioctl support for tty

---

components/lwp/arch/risc-v/rv64/lwp_gcc.S

[
进入musl前需设置好sp，在qemu已测试过动态和静态程序
]

[lwp/riscv]进入libc前初始化用户态sp

---

components/lwp/lwp_syscall.c

[
mkdir to create existed directory will not report error.
Use _SYS_WRAP to fetch errno on return of mkdir to avoid overriding of it on other system APIs.
- BSP:
- .config:
- action:
]

[smart] fixup errno passing on sys_mkdir()

---

src/idle.c

- 原`delete`误以为是这里不要进行卸载;观察代码后才发现意思是不用`delete`函数而是用`detach`函数卸载
- 修改注释后意思不会造成歧义

[IDLE] 修改注释,避免造成歧义

---

bsp/raspberry-pico/README.md

[
- BSP:
- .config:
- action:
]

[bsp][pico] update README.md

---

bsp/qemu-virt64-riscv/driver/drv_uart.c

[bsp/qemu-riscv]修正打开串口后中断被关闭的问题

---

ChangeLog.md

[
- BSP:
- .config:
- action:
]

[log]Update V5.1.0 Released Changelog.

---

components/drivers/ipc/pipe.c

[
- BSP:
- .config:
- action:
]

[ipc]修复pipe创建失败时的资源异常释放

---

bsp/qemu-vexpress-a9/drivers/drv_smc911x.c

[
[qemu-vexpress-a9/drivers/drv_smc911x.c](https://github.com/RT-Thread/rt-thread/blob/master/bsp/qemu-vexpress-a9/drivers/drv_smc911x.c)中用到udelay和mdelay函数，但是没有包含delay.h头文件。
增加头文件#include "delay.h"
- BSP:
- .config:
- action:
]

[fixed]qemu-vexpress-a9/drv_smc911x.c没有包含相应的头文件

---

components/drivers/ipc/workqueue.c

[
- BSP:
- .config:
- action:
]

[workqueue] add comment

---

src/kservice.c

[
- BSP:
- .config:
- action:
]

[src][kservice]fix shutdown log

---

bsp/stm32/stm32l431-tencentos-tiny-EVB_MX+/SConstruct
bsp/stm32/stm32l431-tencentos-tiny-EVB_MX+/board/Kconfig

Relates to #8907
[
Fixup building failure in bsp.
Modify HAL path of `bsp/stm32/stm32l431-tencentos-tiny-EVB_MX+`
- BSP:
- .config:
- action:
]

fixup: building failure in bsp cause by hal

---

components/drivers/include/ipc/ringbuffer.h

[
ringbuffer.h 使用到`RT_ASSERT`,`RT_ASSERT`在`rtthread.h`中定义
```c
/**
* @brief Get the buffer size of the ring buffer object.
*
* @param rb        A pointer to the ring buffer object.
*
* @return  Buffer size.
*/
rt_inline rt_uint32_t rt_ringbuffer_get_size(struct rt_ringbuffer *rb)
{
RT_ASSERT(rb != RT_NULL);
return rb->buffer_size;
}
```
- BSP:
- .config:
- action:
]

[components][ringbuffer]修复编译错误

---

components/finsh/msh.c

[
- BSP:
- .config:
- action:
]

[components][msh]msh命令失败添加打印日志

---

bsp/stm32/stm32l431-tencentos-tiny-EVB_MX+/.config
bsp/stm32/stm32l431-tencentos-tiny-EVB_MX+/SConstruct
bsp/stm32/stm32l431-tencentos-tiny-EVB_MX+/board/Kconfig
bsp/stm32/stm32l431-tencentos-tiny-EVB_MX+/rtconfig.h
bsp/stm32/stm32l431-tencentos-tiny-EVB_MX+/rtconfig.py

修复 stm32l431 构建 ci 构建失败问题
[
- BSP:
- .config:
- action:
]

[bsp]Fix the problem of stm32l431 build ci failure

---

bsp/stm32/libraries/HAL_Drivers/drivers/SConscript
bsp/stm32/libraries/HAL_Drivers/drivers/drv_flash/drv_flash_l1.c

[
在我使用stm32l151时，想操作chip flash，发现官方没有这个系列的drv_flash_l1.c文件；然后我参照其他系列的写了一份；
已在rt-thread studio环境下，使用stm32l151cct6的开发板进行flash的读写操作验证了；
]

[chip flash] add drv_flash_l1.c for stm32l1xxx

---

bsp/nxp/mcx/mcxn/Libraries/drivers/SConscript
bsp/nxp/mcx/mcxn/Libraries/drivers/drv_soft_i2c.c
bsp/nxp/mcx/mcxn/frdm-mcxn236/board/Kconfig

[
- BSP:
- .config:
- action:
]

[bsp][mcxn236] Add software i2c driver.

---

bsp/nxp/mcx/mcxn/frdm-mcxn236/board/linker_scripts/MCXN236_flash.ld
bsp/nxp/mcx/mcxn/frdm-mcxn236/rtconfig.py
bsp/nxp/mcx/mcxn/frdm-mcxn236/template.uvoptx
bsp/nxp/mcx/mcxn/frdm-mcxn236/template.uvprojx

[
- BSP:
- .config:
- action:
]

[bsp/mcxn236]Port gcc&mdk project.

---

.github/workflows/bsp_buildings.yml

add nxp frdm-mcxn236 bsp to bsp_buildings.yml
[
- BSP:
- .config:
- action:
]

[ci][nxp]add nxp frdm-mcxn236 bsp to bsp_buildings.yml

---

libcpu/aarch64/common/mmu.c

[
- BSP:
- .config:
- action:
]

[libcpu][aarch64]mmu log fixup

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart.h
bsp/stm32/stm32f103-100ask-mini/board/linker_scripts/link.icf
bsp/stm32/stm32f103-100ask-mini/board/linker_scripts/link.lds
bsp/stm32/stm32f103-100ask-mini/board/linker_scripts/link.sct
components/drivers/include/drivers/serial.h
components/drivers/serial/serial.c

[
stm32 uart V1 优化驱动实现
* 增加putc超时处理机制,防止死循环
* 优化TX中断初始化与卸载
* 添加TX中断方式实现
[serial V1]poll tx
* 增加异常退出机制
- BSP:
- .config:
- action:
]

[bsp][stm32][uart V1]优化驱动实现

---

bsp/qemu-vexpress-a9/.vscode/launch.json

[
1. 省略qemu-a9更换launch.json文件的步骤
2. 更换launch.json文件，使得无需更换launch.json文件就可以直接进入a9的调试
- BSP:qemu-vexpress-a9
- .config:
- action:
]

[file]modify a9/launch.json

---

bsp/stm32/stm32f407-lckfb-skystar/.config
bsp/stm32/stm32f407-lckfb-skystar/Kconfig
bsp/stm32/stm32f407-lckfb-skystar/board/Kconfig
bsp/stm32/stm32f407-lckfb-skystar/board/ports/fal/fal_cfg.h
bsp/stm32/stm32f407-lckfb-skystar/board/ports/fal/fal_spi_flash_sfud_port.c
bsp/stm32/stm32f407-lckfb-skystar/board/ports/spi_flash_init.c
bsp/stm32/stm32f407-lckfb-skystar/project.uvoptx
bsp/stm32/stm32f407-lckfb-skystar/project.uvprojx
bsp/stm32/stm32f407-lckfb-skystar/rtconfig.h

[
天空星目前只有青春版（没有贴外部flash），高配版（有贴外部flash）正在生产，所贴的SPI FLASH 从GD25Q32升级为W25Q128。
修改型号
已在实际的天空星高配版上验证，sf bench与在spi flash上使用文件系统均正常。
- BSP:
- .config:
- action:
]

[bsp/stm32f407-lckfb-skystar] 天空星高配版的FLASH从GD25Q32升级为W25Q128

---

bsp/nxp/mcx/mcxn/Libraries/MCXN947/SConscript
bsp/nxp/mcx/mcxn/frdm-mcxn236/rtconfig.py
bsp/nxp/mcx/mcxn/frdm-mcxn947/rtconfig.py

[
- BSP:
- .config:
- action:
]

[bsp][nxp] Update mcxn236/n947 project config. 

---

include/rtthread.h
src/kservice.c

[
修复doxygen
- BSP:
- .config:
- action:
]

[doc][doxygen] Fix hook struct error.

---

components/drivers/ktime/src/hrtimer.c

[
Replace the recursive algorithm with a loop in the HR-timer components
when determining the next timeout event and set up the hardware timer.
- BSP:
- .config:
- action:
]

[ktime] quality: remove recursion on hrtimer

---

bsp/nxp/mcx/mcxn/frdm-mcxn947/board/SConscript
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/ports/wifi_weather_sample.c

[
- BSP:
- .config:
- action:
]

[BSP][nxp]增加wifi_weather_sample.c

---

src/thread.c

[
resume应返回所需唤醒线程是否成功变为可调度状态，但若在临界区的线程唤醒另一线程会返回错误码，即使线程唤醒成功
- BSP:
- .config:
- action:
]

[src][thread]fix rt_thread_resume return value error

---

bsp/cvitek/drivers/libraries/eth/dw_eth_mac.h

[bsp/cvitek]解决eth编译报错

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart.c

增大串口v1发送超时时间，否则一些系列打印会乱码
[
- BSP:
- .config:
- action:
]

[bsp][stm32]Increase the serial_v1 tx timeout.

---

bsp/cvitek/drivers/libraries/eth/cvi_eth_phy.h

[
typedef void *eth_phy_handle_t; //eth_phy_handle_t已经是指针了
]

[bsp/cvitek/eth]解决编译警告

---

components/drivers/ofw/fdt.c

[
- BSP:
- .config:
- action:
]

[components][driver]fix initrd scan err

---

components/drivers/sdio/sdio.c

[
在sdio_init_card中，只要分配了card内存，就会在有任何的请下释放并移除card
但是在sdio_init_card返回错误后，init_sdio中再次执行了card的内存释放导致断言
删除init_sdio函数中的card移除动作，交由sdio_init_card函数内完成card的移除
- BSP:GD32F470
- .config:
- action:
]

fix an issue where repeated remove of card resulted in assertions

---

bsp/qemu-vexpress-a9/drivers/Kconfig
bsp/qemu-vexpress-a9/drivers/drv_clcd.h

修复qemu-a9使能lcd缺失依赖问题.
[
- BSP:
- .config:
- action:
]

[bsp][qemu]修复qemu-a9使能lcd缺失依赖问题.

---

bsp/cvitek/cv18xx_risc-v/README.md
bsp/cvitek/cv18xx_risc-v/README_en.md

[
document: add ref to gpio pinout
- BSP:
- .config:
- action:
]

[bsp/cvitek] document: add ref to gpio pinout

---

bsp/stm32/stm32f407-rt-spark/README_EN.md

[
- BSP:
- .config:
- action:
]

[bsp][stm32_rt_spark]Add README_EN

---

components/drivers/can/can.c

[
修复RX可能导致的内存溢出情况
https://github.com/RT-Thread/rt-thread/issues/8634
完善函数返回类型与传入参数;并在赋值前进行判断
- BSP:
- .config:
- action:
]

[components][driver][can]Fix possible memory overflow caused by RX

---

tools/menukconfig.py

[
由于tools/kconfiglib文件在之前的pr已经删除，另外新版的env会自动安装kconfiglib，但是有些用户可能还是在使用老版本的env，因此导致scons --menuconfig无法正常使用。
在tools/menukconfig.py文件中添加try/except检测kconfig是否安装，如果没有安装则提醒用户使用pip install kconfiglib安装
- BSP:
- .config:
- action:
]

[fixed][kconfiglib]test kconfiglib is installed and info how to install

---

.github/workflows/action_tools.yml
.github/workflows/compile_bsp_with_drivers.yml

[
- BSP:
- .config:
- action:
]

[ci] use env install script to install env

---

tools/keil.py

[
解决论坛中提问[scons命令生成mdk5工程问题请教
](https://club.rt-thread.org/ask/question/05614ff3c11040de.html)，以及issue中提到的[[Bug] env2.0引入的部分python语法不兼容问题](https://github.com/RT-Thread/rt-thread/issues/9141)
修改keil.py中str.decode，使用try/except进行python3和python2兼容
- BSP:
- .config:
- action:
]

解决tools/keil.py中python3不兼容python2的str.decode()

---

bsp/cvitek/drivers/libraries/eth/dw_eth_mac.c

[bsp/cvitek]将eth驱动中地址类型改为指针以适应ioremap

---

components/mm/mm_aspace.h
libcpu/Kconfig
libcpu/risc-v/t-head/c906/mmu.c
libcpu/risc-v/t-head/c906/startup_gcc.S

feat: [libcpu/c906] support ARCH_REMAP_KERNEL
This change was necessary to enable the remapping of the kernel image to a high virtual address region on the c906 platform.
Changes:
- Introduced new configuration options `ARCH_REMAP_KERNEL`, and `ARCH_USING_ASID` under the `ARCH_RISCV64` section.
- Updated MMU initialization and switching functions to incorporate remapping handling.
- Modified page table setup for proper memory attribute settings.
- Added support for early memory setup, kernel remapping
- Added conditional compilation for ASID support in the `rt_aspace` struct, since this is not enable currently for most architecture.
[
- BSP:
- .config:
- action:
]

feat: support ARCH_REMAP_KERNEL on libcpu/c906 (#9123)

---

libcpu/arm/cortex-m7/context_gcc.S

[
因为`rt-thread/libcpu/arm/cortex-m7/context_gcc.S`里的`.cpu`定义为`cortex-m4`看起来很奇怪
把`rt-thread/libcpu/arm/cortex-m7/context_gcc.S`里的`.cpu`定义为`cortex-m7`，与文件名统一
- BSP: 无
- .config: 无
- action: 无
]

Correct ".cpu cortex-m4" to ".cpu cortex-m7"

---

components/drivers/usb/cherryusb/Kconfig
components/drivers/usb/cherryusb/Kconfig.cherryusb
components/drivers/usb/cherryusb/platform/rtthread/usb_check.c

[
- BSP:
- .config:
- action:
]

fix(cherryusb): fix typo

---

components/drivers/virtio/virtio_net.c

[
lwip框架中不可以多个网络包的pbuf串起来，而驱动的eth_rx返回的pbuf是多个网络包pbuf的连接，导致接收方向丢包严重
- BSP:
- .config:
- action:
]

[driver][virtio]fix virtio net rx error

---

components/fal/src/fal_flash.c

[
- BSP:
- .config:
- action:
]

[components][fal]Log warning for block partition exceeding flash length

---

libcpu/aarch64/common/setup.c

[
之前fdt_ptr错误指向设备树的物理地址，此处修正为虚拟地址
- BSP:
- .config:
- action:
]

[libcpu][setup]fix fdt_ptr error

---

components/dfs/dfs_v2/filesystems/cromfs/dfs_cromfs.c

[
使用cromfs时打开kasan工具会出现超出内存的报错，经过调试查看是无符号整型减去一个比自己大的数导致的
强制类型转换
- BSP:
- .config:
- action:
]

[fix] fix cromfs read out of mem range

---

bsp/cvitek/drivers/drv_hw_i2c.c
bsp/cvitek/drivers/drv_hw_i2c.h

Optimize the original i2c driver code.
[
原来的 i2c 驱动写得不好，所以重写了。
参考了 sophgo 的 sdk
- .config: 无修改
- action: N/A
]

bsp: cvitek: re-wrote i2c driver

---

bsp/cvitek/drivers/drv_wdt.c

注意，这个 PR 包含了多个 commit，merge 时请保留，不要 squash，因为这是提交上的设计使然，不是中间过程。具体原因参考  #9136 的 【问题 3】
----
[
修改了多个 wdt driver 中的问题。具体请见 commit 描述。
具体请见 commit 描述。
- .config: 无改动
- action:  N/A
]

bsp: cvitek:  accuulated bugfixes for wdt driver

---

components/drivers/misc/rt_random.c

[
urandom write时返回值固定是机器字长，但可能传入的size小于机器字长
- BSP:
- .config:
- action:
]

[driver][random]fix potential return value discrepancy when writing to urandom

---

components/dfs/dfs_v2/src/dfs_fs.c
components/lwp/lwp_syscall.c

[
- BSP:
- .config:
- action:
]

[components][lwp]fix exec and mount error code

---

bsp/stm32/libraries/HAL_Drivers/drivers/SConscript
bsp/stm32/libraries/HAL_Drivers/drivers/config/h7/lptim_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_config.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_lptim.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_lptim.h
bsp/stm32/libraries/HAL_Drivers/drivers/drv_pm.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_rtc.c
bsp/stm32/stm32h750-artpi/board/Kconfig
bsp/stm32/stm32l476-st-nucleo/.config
bsp/stm32/stm32l476-st-nucleo/rtconfig.h
components/drivers/hwtimer/hwtimer.c
components/drivers/include/drivers/pm.h
components/drivers/pm/pm.c
include/rtsched.h
include/rtthread.h
src/clock.c
src/scheduler_comm.c

[
- 优化PM框架及STM32 drv_pm驱动
- 修复bug:https://github.com/RT-Thread/rt-thread/issues/9043
- BSP:STM32H750
- .config:
- action: https://github.com/wdfk-prog/ART-PI/commit/682f9c2968b708cef0fc2deb04dd994ba045e3c1
]

[pm]PM框架优化

---

.github/workflows/action_runner.yml

[
提交action runner 在本地计算机上keil检验编译情况
- BSP:
- .config:
- action:
https://github.com/supperthomas/rt-thread/actions/runs/10004324991/job/27652802023
]

[action][runner] add the keil ci check for runner

---

bsp/cvitek/cv18xx_aarch64/Kconfig
bsp/cvitek/cv18xx_aarch64/rtconfig.h

[
Fixed https://github.com/RT-Thread/rt-thread/issues/9217
参照 cv18xx_risc-v 调整对应 Kconfig 配置
- .config:
- action:
]

[bsp][cvitek] 修复 cv18xx_aarch64 gpio 驱动相关宏配置

---

.github/CODEOWNERS

[
- BSP:
- .config:
- action:
]

[ci] add bsp/stm32+renesas examples files' review owner

---

examples/utest/testcases/kernel/sched_timed_mtx_tc.c
examples/utest/testcases/kernel/timer_tc.c

[
This is required so the user will not be confused on waiting for test to complete.
Changes:
- notify user that the test is not corrupted
- expand waiting tick on timed mtx test, for compatibility on different hw.
- BSP:
- .config:
- action:
]

[utest] feat: print progress on testing timer

---

components/lwp/arch/aarch64/cortex-a/lwp_arch.c
components/lwp/arch/aarch64/cortex-a/lwp_gcc.S
libcpu/aarch64/common/backtrace.c
libcpu/aarch64/common/include/asm-generic.h
libcpu/aarch64/common/include/context_gcc.h
libcpu/aarch64/common/mp/context_gcc.S
libcpu/aarch64/common/mp/context_gcc.h
libcpu/aarch64/common/mp/vector_gcc.S
libcpu/aarch64/common/stack.c
libcpu/aarch64/common/stack_gcc.S
libcpu/aarch64/common/up/context_gcc.S
libcpu/aarch64/common/up/context_gcc.h
libcpu/aarch64/common/up/vector_gcc.S

[
This patch focuses on the ARM64 general context handling code.
The modifications are aimed at enhancing performance by simplifying
context save/restore operations.
Changes include:
- Adjusted stack alignment in `arch_set_thread_context` function.
- Updated `lwp_gcc.S` to reset frame pointer and link register.
- Refined `rt_hw_backtrace_frame_unwind` to handle user space address checks.
- Added `GET_THREAD_SELF` macro in `asm-generic.h`.
- Simplified context saving/restoring in `context_gcc.h` and related files.
- Optimized `rt_hw_context_switch_interrupt` and related assembly routines.
- BSP:
- .config:
- action:
]

[libcpu] trimming ARM64 general context

---

bsp/cvitek/drivers/drv_ioremap.h

[bsp/cvitek]添加ioremap兼容定义以适应smart运行

---

components/drivers/sensor/v1/sensor_cmd.c
components/drivers/sensor/v2/sensor_cmd.c

[
修复sensor_v2框架第一次probe sensor设备时返回错误值-22的问题
由于msh_exec()函数在执行_msh_exec_cmd时会对cmd_ret参数进行判断，而_msh_exec_cmd()中的cmd_func(argc, argv)返回给cmd_ret(*retp)，此时执行此命令的函数为sensor_v2中的sensor函数，需要给到一个返回值
- BSP:
- .config:
- action:
]

[sensor] Repair an error occurs when sensor cmd probes a sensor device for the first time

---

bsp/cvitek/cv18xx_aarch64/board/board.c

When compiling CV18xx_arch64, have a error:
can not find "rt_fdt_commit_memregion_early"
Analysis: b785ef9 ("[libcpu][aarch64]memory setup using memblock ") no longer support  "rt_fdt_commit_memregion_early", become use "rt_memblock_reserve_memory"
Solution: Refer to the bsp/qemu-virt64-aarch64/drivers/board.c delete "rt_fdt_commit_memregion_early"
[
Fixed https://github.com/RT-Thread/rt-thread/issues/9246
参考qemu-virt64-aarch64删除rt_fdt_commit_memregion_early
- .config:
- action:
]

bsp: cviteK: update board init for aarch64

---

libcpu/aarch64/common/include/armv8.h
libcpu/aarch64/common/include/cpuport.h

[
The rtdef.h is a big header with multiple dependencies inside,
which makes it easier to introduce recursive dependency.
Include the essential header only to avoid recursion.
- BSP:
- .config:
- action:
]

quality: include the essential only to avoid recursion

---

bsp/cvitek/cv18xx_aarch64/.config
bsp/cvitek/cv18xx_aarch64/Kconfig
bsp/cvitek/cv18xx_aarch64/board/Kconfig
bsp/cvitek/cv18xx_aarch64/rtconfig.h

[
Fixed https://github.com/RT-Thread/rt-thread/issues/9220
Fixed https://github.com/RT-Thread/rt-thread/issues/9211
参照 cv18xx_risc-v 调整对应 Kconfig 配置
- .config:
- action:
]

bsp: cvitek: add missing soc type for aarch64

---

components/net/lwip-dhcpd/dhcp_server_raw.c

[dhcp]fix typo in dhcp server

---

bsp/Infineon/libraries/templates/XMC7200D/SConstruct
bsp/Infineon/psoc6-cy8ckit-062-BLE/SConstruct
bsp/Infineon/psoc6-cy8ckit-062-WIFI-BT/SConstruct
bsp/Infineon/psoc6-cy8ckit-062S2-43012/SConstruct
bsp/Infineon/psoc6-cy8ckit-062s4/SConstruct
bsp/Infineon/psoc6-cy8cproto-062S3-4343W/SConstruct
bsp/Infineon/psoc6-evaluationkit-062S2/SConstruct
bsp/Infineon/xmc7200-kit_xmc7200_evk/SConstruct

[
1. SCons 的提示操作与实际需要进行操作不符，大概是由于 Typo 导致的
2. 英语表达存在优化空间
1. 将`--Update`改为`--update`
2. 优化英语表达
]

[bsp/Infineon] 修复 SCons 中的 typo 并优化表达

---

bsp/nxp/mcx/mcxa/Libraries/drivers/SConscript
bsp/nxp/mcx/mcxa/Libraries/drivers/drv_chipflash.c
bsp/nxp/mcx/mcxa/Libraries/drivers/drv_chipflash.h
bsp/nxp/mcx/mcxa/Libraries/drivers/drv_log.h
bsp/nxp/mcx/mcxa/Libraries/drivers/drv_uart.c
bsp/nxp/mcx/mcxa/frdm-mcxa153/applications/main.c
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/Kconfig
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/SConscript
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/drv_filesystem.c
bsp/nxp/mcx/mcxa/frdm-mcxa153/template.uvoptx
bsp/nxp/mcx/mcxa/frdm-mcxa153/template.uvprojx

[
为 NXP MCXA153 添加 MTD驱动
已经在 MCXA153通过测试
- BSP:
- .config:
- action:
]

[NXP]MCXA153添加MTD驱动

---

bsp/wch/risc-v/Libraries/ch32_drivers/SConscript
bsp/wch/risc-v/Libraries/ch32_drivers/drv_eth.c
bsp/wch/risc-v/Libraries/ch32_drivers/drv_eth.h
bsp/wch/risc-v/ch32v307v-r1/.config
bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
bsp/wch/risc-v/ch32v307v-r1/rtconfig.h
bsp/wch/risc-v/ch32v307v-r1/rtconfig.py
libcpu/risc-v/common/context_gcc.S

[
CH32添加以太网驱动
在ch32v307-r1-1v1 开发板测试通过
bsp\wch\risc-v\ch32v307v-r1
试验结果
```
\ | /
- RT -     Thread Operating System
/ | \     5.2.0 build Jul 25 2024 17:12:46
2006 - 2024 Copyright by RT-Thread team
lwIP-2.0.3 initialized!
[I/sal.skt] Socket Abstraction Layer initialize success.
msh >
msh >
msh >ping www.baidu.com
ping: not found specified netif, using default netdev e0.
60 bytes from 180.101.50.242 icmp_seq=0 ttl=52 time=517 ms
60 bytes from 180.101.50.242 icmp_seq=1 ttl=52 time=1018 ms
60 bytes from 180.101.50.242 icmp_seq=2 ttl=52 time=654 ms
60 bytes from 180.101.50.242 icmp_seq=3 ttl=52 time=886 ms
msh >
```
]
我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered …

[bsp][ch32] add eth driver

---

components/net/sal/src/sal_socket.c

[
- BSP:
- .config:
- action:
]

[net][sal]修复开启SAL_TLS编译报错

---

bsp/nxp/mcx/mcxa/Libraries/drivers/drv_adc.c
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/Kconfig

[
- BSP:
- .config:
- action:
]

[bsp][nxp/mcxa153]优化mxca153 adc驱动，支持电压读取

---

tools/env_utility.py

修正env sdk的路径，能够实现env sdk下的工具链自动探测。在arm，riscv64上验证通过

[tools] fix the SDK package path issue

---

bsp/cvitek/drivers/drv_adc.c
bsp/cvitek/drivers/drv_adc.h

Cvitek adc dirver only supports one adc controller now, but the other adc controller RTCSYS_SARADC is missing.
[
Fixed https://github.com/RT-Thread/rt-thread/issues/9025
添加 RTCSYS_SARADC
- .config:
- action:
]

bsp: cvitek: add support for RTCSYS_SARADC

---

bsp/at91/at91sam9g45/.config
bsp/at91/at91sam9g45/rtconfig.h
bsp/loongson/ls1cdev/.config
bsp/loongson/ls1cdev/rtconfig.h
bsp/loongson/ls1cdev/rtconfig.py
bsp/microchip/same54/.config
bsp/microchip/same54/rtconfig.h
bsp/microchip/same70/.config
bsp/microchip/same70/rtconfig.h
components/dfs/dfs_v1/SConscript

修复bsp中的编译报错，缺失RT_USING_RTC依赖导致ci问题。
[
- BSP:
- .config:
- action:
]

[ci][bsp]fix same54&same70&ls1cdev build errors.

---

components/drivers/core/platform_ofw.c
include/rtatomic.h

[
dec_and_test是测试减1后是否为0，但atomic_sub返回值是修改前的值
同时修复ofw中put without get的问题
- BSP:
- .config:
- action:
]

[kernel][atomic]fix rt_atomic_dec_and_test

---

components/libc/compilers/common/ctime.c

Analysis: RT_USING_RTC preprocessing is used in 47cd52d ("修复不 使能 RT_USING_DEVICE 时编译报错") to control the reference of rtdevice.h, as well as the implementation and call of _control_rtc, but there are some omissions.
Solution: Add RT_USING_RTC preprocessing control to missing _control_rtc
[
Fixed https://github.com/RT-Thread/rt-thread/issues/9281
对遗漏的 _control_rtc 添加 RT_USING_RTC 预处理判断
- .config:
- action:
]

Add RT_USING_RTC conditional compilation protection in ctimer.c

---

.github/workflows/bsp_buildings.yml

[
添加机器人comment
- BSP:
- .config:
- action:
]

[action] add robot comment when action is fail

---

bsp/cvitek/c906_little/SConstruct
bsp/cvitek/cv18xx_aarch64/SConstruct
bsp/cvitek/cv18xx_risc-v/SConstruct

Fixed #9230 
For bsp/cvitek, all drivers related files are moved to the directory bsp/cvitek/drivers, so the drivers_path_prefix processing in the SConstruct of the three bsp projects can be simplified.
[
请看 commit 描述
直接定义 `drivers_path_prefix = os.path.dirname(SDK_ROOT) + '/drivers'` 即可
- BSP: bsp/cvitek 下的三个 bsp 都需要优化。
- .config: N/A
- action: N/A
]

bsp: cvitek: SConstruct: optimize drivers_path_prefix

---

bsp/nxp/mcx/mcxa/Libraries/MCXA153/SConscript
bsp/nxp/mcx/mcxa/Libraries/drivers/SConscript
bsp/nxp/mcx/mcxa/Libraries/drivers/drv_pwm.c
bsp/nxp/mcx/mcxa/Libraries/drivers/drv_pwm.h
bsp/nxp/mcx/mcxa/Libraries/drivers/drv_spi.c
bsp/nxp/mcx/mcxa/Libraries/drivers/drv_spi.h
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/Kconfig
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/MCUX_Config/board/pin_mux.c
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/board.c

[
add pwm && spi driver for NXP MCXA153 Board
add pwm && spi driver files in `bsp\nxp\mcx\mcxa\Libraries\drivers`
bsp\nxp\mcx\mcxa\frdm-mcxa153
- BSP: BSP_USING_PWM、BSP_USING_SPI
- .config: BSP_USING_PWM、BSP_USING_SPI
- action:  https://github.com/hywing/rt-thread/commit/fe0b1a332502e34a93f9da7eb55e8747d16a71c0
]

[bsp][nxp][mcxa153] add pwm && spi driver

---

tools/cmake.py

[
Fix CMake compile errors.
修复CMake生成器编译错误
Updated CMakeLists.txt generator to handle private macro definitions for source groups. Individual source groups are added as OBJECT libraries, which does not generate actual archive but will be linked together at final application linking stage. Source groups without source files are added as INTERFACE libraries, which provides library dependencies to the final application.
更新CMakeListst.txt生成器，RT-Thread内核部分代码需要使用私有宏定义，该宏定义在其他工具链/IDE使用源代码组设置添加，通过将每个代码组独立为OBJECT库的方式为CMake增加私有宏定义功能。无源代码的组可以提供静态库依赖，定义为INTERFACE库。OBJECT库在编译期不会产生静态库.a文件，最终链接整个工程时会一并链接。
- BSP:
* FRDM-MCXN947
- .config:
- Use default.
- action:
- Static build check.
]

tools: CMake: Generator re-write and bug fixes.

---

bsp/nxp/mcx/mcxa/Libraries/drivers/drv_spi.c
bsp/nxp/mcx/mcxn/Libraries/drivers/drv_spi.c

[
使用 `rt_spi_device->cs_pin` 标准CS pin成员替换 `user_data` 指针，同时修复`rt_spi_bus_attach_device_cspin()` 。
Replace `user_data` pointer with standard `rt_spi_device->cs_pin`, fix `rt_spi_bus_attach_device_cspin()`.
如上
See above.
- BSP:
- `bsp/nxp/mcx/mcxn/frdm-mcxn947`
- `bsp/nxp/mcx/mcxa/frdm-mcxa153`
- .config:
- `CONFIG_RT_USING_SPI=y`
- action:
- N/A
]

bsp: nxp/mcx: Use standard SPI CS pin.

---

bsp/nxp/mcx/mcxn/frdm-mcxn947/board/ports/drv_filesystem_spi_flash.c
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/ports/drv_spi_sample_rw007.c

[
更新 FRDM-MCXN947 porting 代码：
- 使用标准SPI驱动API
- SPI flash 文件系统在初次挂载失败后会自动格式化，空片时用户不需要手动格式化即可使用
Updated FRDM-MCXN947 porting drivers:
- Use generic SPI driver API
- Format SPI flash filesystem after initial mount failure.
如上。
See above.
- BSP:
- bsp/nxp/mcx/mcxn/frdm-mcxn947
- .config:
- CONFIG_RT_USING_DFS=y
- CONFIG_RT_USING_DFS_ELMFAT=y
- CONFIG_RT_DFS_ELM_MAX_SECTOR_SIZE=4096
- CONFIG_RT_USING_SPI=y
- CONFIG_RT_USING_SFUD=y
- CONFIG_RT_SFUD_USING_SFDP=y
- action:
- N/A
]

ports: nxp/frdm-mcxn947: Porting layer updates

---

src/slab.c

Maybe we forget to print zoneindex here.
[
修改rt_slab_free中部分丢失的debug打印信息
添加上zoneindex对应打印信息
- BSP:N/A
- .config:N/A
- action:N/A
]
- [x ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [x ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x ] 代码是高质量的 Code in this …

mem: fix some log issue in src/slab.c.

---

bsp/nxp/mcx/mcxa/Libraries/drivers/drv_i2c.c
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/Kconfig
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/MCUX_Config/board/pin_mux.c

[
add i2c driver for NXP MCXA153 Board
add i2c driver files in `bsp\nxp\mcx\mcxa\Libraries\drivers`
- BSP: bsp\nxp\mcx\mcxa\frdm-mcxa153
- .config: CONFIG_BSP_USING_I2C0
- action: https://github.com/RT-Thread/rt-thread/commit/dca7b53b40ccb54bdddae1b9e9b61241a537b733
]

[bsp][nxp][mcxa153] add i2c driver

---

bsp/Infineon/libraries/HAL_Drivers/drv_pwm.c
bsp/Infineon/libraries/HAL_Drivers/drv_pwm.h
bsp/Infineon/psoc6-evaluationkit-062S2/applications/SConscript
bsp/Infineon/psoc6-evaluationkit-062S2/applications/arduino_main.cpp
bsp/Infineon/psoc6-evaluationkit-062S2/applications/arduino_pinout/README.md
bsp/Infineon/psoc6-evaluationkit-062S2/applications/arduino_pinout/SConscript
bsp/Infineon/psoc6-evaluationkit-062S2/applications/arduino_pinout/pins_arduino.c
bsp/Infineon/psoc6-evaluationkit-062S2/applications/arduino_pinout/pins_arduino.h
bsp/Infineon/psoc6-evaluationkit-062S2/board/Kconfig
bsp/Infineon/psoc6-evaluationkit-062S2/libs/TARGET_RTT-062S2/config/GeneratedSource/cycfg_pins.c

[
- BSP:
- .config:
- action:
]

[bsp][Infineon][psoc6-evk-062s2]Adapt to RTduino

---

bsp/at32/libraries/rt_drivers/drv_hard_i2c.c
bsp/at32/libraries/rt_drivers/drv_spi.c

[
有两个 dma_isr()。. 一个在 drv_spi.c.中，另一个在 drv_hard_i2c.c中：
```
void dma_isr(struct dma_config *dma_instance)
void dma_isr(struct at32_i2c_handle *handle)
```
把drv_hard_i2c.c 中的 dma isr() 改名。
- BSP: bsp/at32/at32f405-start
- .config: [config.txt](https://github.com/user-attachments/files/16709629/config.txt)
- action:
]
- [] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

[bsp/at32] remove duplicate dma_isr() in hwi2c

---

.devcontainer/Dockerfile
.github/workflows/manual_bsp_build.yml
.github/workflows/manual_trigger_update_all.yml
tools/ci/bsp_buildings.py
tools/ci/manual_bsp_build_all.py

[
添加可以手动trigger， 对所有bsp编译，并且输出出错bsp的log
参考效果：
https://github.com/supperthomas/rt-thread/actions/runs/10538547961
- BSP:
- .config:
- action:
]

[action]  add python script to build all bsp and add action trigger

---

components/lwp/lwp_args.c

[
This patch addresses the potential issue of uninitialized elements in the argument vector returned by `lwp_get_command_line_args()`. The previous implementation could leave `argv` in an inconsistent state if certain errors occurred, leading to possible undefined behavior.
Changes:
- Replaced `rt_malloc()` with `rt_calloc()` to ensure `argv` is properly initialized.
- Added a consistent error handling path using `goto error_exit` to handle memory allocation failures and string copy errors.
- Ensured `lwp_free_command_line_args()` is called before returning on error, preventing potential memory leaks.
- BSP:
- .config:
- action:
]

fixup: uninitialized argument vector element

---

tools/ci/bsp_detail.py
tools/ci/bsp_detail.yml
tools/ci/manual_bsp_build_all.py
tools/ci/toolchain_bsp.yml

[
根据bsp中的信息，生成对应的yml文件和toolchain信息
自动生成ci需要的yml文件
用bsp_detail.py来生成
- BSP:
- .config:
- action:
]

[action/ci] Add bsp detail python script

---

tools/ci/bsp_detail.py

[
- BSP:
- .config:
- action:
]

[action/ci] add cpu and arch

---

components/dfs/dfs_v2/src/dfs_posix.c
components/lwp/lwp_syscall.c

[
修复rmdir系统调用返回值不符合用户预期问题
- BSP:
- .config:
- action:
]

【修复】修复rmdir系统调用返回值不符合用户预期问题

---

components/dfs/dfs_v2/src/dfs_file.c
components/lwp/lwp_syscall.c

[
修复link系统调用返回值问题
- BSP:
- .config:
- action:
]

【修复】修复link系统调用返回值问题

---

bsp/nxp/imx/imxrt/imxrt1170-nxp-evk/m7/.config
bsp/nxp/imx/imxrt/imxrt1170-nxp-evk/m7/board/linker_scripts/link.lds
bsp/nxp/imx/imxrt/imxrt1170-nxp-evk/m7/rtconfig.h

[
scons编译错误
scons编译出错
- BSP:
- .config:
- action:
]

[bsp/nxp] Add fixed lds

---

.github/labeler.yml
.github/workflows/auto_labeler.yml
.github/workflows/manual_trigger_update_all.yml
README.md

[
自动添加label
- BSP:
- .config:
- action:
]

[action] add action auto labeler to label PR

---

.github/labeler.yml

补充部分bsp和组件的标签
[
- BSP:
- .config:
- action:
]

[action]Supplementary part bsp, Component's label.

---

src/thread.c

[
Fixed https://github.com/RT-Thread/rt-thread/issues/9332:
`rt_object_allocate()` will clear memory after new rt_thread allocation in `rt_thread_create()`. However, in `rt_thread_init()` the same behavior is missing, which corrupts the consistency of the API to call `_thread_init()`.
Changes:
- Added `memset()` zero for `rt_thread_init()` in the entry
- BSP:
- .config:
- action:
]

feat: add memset zero for rt_thread_init

---

.github/workflows/bsp_buildings.yml
bsp/ht32/ht32f12366/rtconfig.py
bsp/ht32/ht32f52352/rtconfig.py
bsp/ht32/libraries/HT32_STD_1xxxx_FWLib/SConscript
bsp/ht32/libraries/HT32_STD_5xxxx_FWLib/SConscript
bsp/ht32/tools/sdk_dist.py

[
修复ht32scons不能编译问题 #7764 
添加编译需要的宏
- BSP:
- .config:
- action:
]

[bsp][ht32] 修复编译问题 

---

bsp/nxp/mcx/mcxa/Libraries/drivers/drv_spi.c
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/Kconfig
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/MCUX_Config/board/pin_mux.c

[
add spi1 driver entry for NXP MCXA153 Board
add && modify spi driver files in `bsp\nxp\mcx\mcxa\Libraries\drivers`
- BSP: BSP_USING_SPI1
- .config: BSP_USING_SPI1
- action: https://github.com/hywing/rt-thread/commit/1f9009c5c8f8b277ade412bf0d98467381443f22
]

[bsp][nxp][mcxa153] add spi1 driver entry

---

bsp/nxp/mcx/mcxn/frdm-mcxn947/board/Kconfig
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/SConscript
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/cherryusb_port.c
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/linker_scripts/MCXN947_cm33_core0_flash.ld
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/usb.h
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/usb_config.h
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/usb_phy.c
bsp/nxp/mcx/mcxn/frdm-mcxn947/board/usb_phy.h

update(cherryusb): add config for mcxn947 usbdev and usbhost

---

components/drivers/usb/cherryusb/SConscript
components/drivers/usb/cherryusb/class/msc/usbd_msc.c
components/drivers/usb/cherryusb/port/ehci/usb_glue_ma35d0.c

fix(cherryusb): fix build error

---

bsp/at32/at32f407-start/board/Kconfig
bsp/at32/at32f437-start/board/Kconfig
bsp/at32/libraries/rt_drivers/drv_emac.c
bsp/at32/libraries/rt_drivers/drv_emac.h

[
[bsp/at32] ethernet support phy lan8720 and yt8512
]

[bsp/at32] ethernet support phy lan8720 and yt8512

---

bsp/nxp/mcx/mcxc/frdm-mcxc444/board/linker_scripts/MCXC444_flash.ld
bsp/nxp/mcx/mcxc/frdm-mcxc444/rtconfig.py

[
修复FRDM-MCXC444 GCC编译错误
Fix GCC build support for FRDM-MCXC444.
请查看Commit日志。
Please check commit log.
- BSP:
- bsp/nxp/mcx/mcxc/frdm-mcxc444
- .config:This patch fixes
- N/A
- action:
- N/A
]

bsp: nxp/mcx/mcxc: FRDM-MCXC444: Fix GCC build suport.

---

bsp/nxp/mcx/mcxc/Libraries/drivers/drv_rtc.c
bsp/nxp/mcx/mcxc/Libraries/drivers/drv_rtc.h
bsp/nxp/mcx/mcxc/Libraries/drivers/drv_uart.c
bsp/nxp/mcx/mcxc/Libraries/drivers/drv_wdt.c
bsp/nxp/mcx/mcxc/Libraries/drivers/drv_wdt.h
bsp/nxp/mcx/mcxc/frdm-mcxc444/board/Kconfig
bsp/nxp/mcx/mcxc/frdm-mcxc444/board/MCUX_Config/board/pin_mux.c

[
- BSP:
- .config:
- action:
]

[bsp][mcxc] add rtc/wdog/uart driver

---

bsp/cvitek/drivers/drv_eth.c
bsp/cvitek/drivers/libraries/eth/cvi_eth_phy.c
bsp/cvitek/drivers/libraries/eth/cvi_eth_phy.h
bsp/cvitek/drivers/libraries/eth/dw_eth_mac.c
bsp/cvitek/drivers/libraries/eth/dw_eth_mac.h
bsp/cvitek/drivers/libraries/eth/eth_phy_cvitek.c

Signed-off-by: flyingcys <flyingcys@163.com>
[
修改drv_eth 驱动，支持phy自动检测
- BSP:
bsp/cvitek/cv18xx_risc-v
- .config:
- action:
]

[bsp/cvitek] eth driver support phy link detect

---

components/drivers/core/bus.c
components/drivers/core/platform_ofw.c

[
1. Fixup bus remove device option.
2. Fixup platform not free device in OFW.
]

[DM/Fixup] Fixup bus resource release

---

.github/workflows/static_code_analysis.yml

[
更新cppcheck版本 #9385
- BSP:
- .config:
- action:
]

[action] update cppcheck version

---

bsp/nxp/mcx/mcxc/Libraries/drivers/drv_i2c.c
bsp/nxp/mcx/mcxc/frdm-mcxc444/board/Kconfig

[
添加MCX C I2C驱动
Add I2C driver for MCX C series.
如上。
See above.
- BSP:
- bsp/nxp/mcx/mcxc/frdm-mcxc444
- .config:
- BSP_USING_I2C
- BSP_USING_I2C0
- BSP_USING_I2C1
- action:
- N/A
]

bsp: nxp/mcx/mcxc: Add I2C driver support.

---

.github/workflows/static_code_analysis.yml

[
- BSP:
- .config:
- action:
]

[action][cppcheck] fix the cfg path

---

components/net/at/at_socket/at_socket.c

[
at_socket内部没有设置errno，需要根据errno值做判断的应用无法正常运行
- BSP:
STM32F401RCT6使用webclient和RyanMqtt测试
- .config:
- action:
]

[components][at_socket] 添加errno设置

---

bsp/cvitek/cv18xx_risc-v/SConstruct

CV18xx RISC-V C906L.
Configuration value for CPU and ARCH are already defined in rtconfig.py. Remove these duplication from SConstruct.
[
Fixed #9349 
- BSP:  bsp/cvitek/cv18xx_risc-v
- .config: no update
- action: N/A
]

bsp: cvitek: clean up useless variable assignments in SConstruct

---

.github/workflows/manual_dist.yml

[
添加cppcheck project 根据编译情况进行静态检查
添加github action debug 按钮，方便debug
- BSP:
- .config:
- action:
]

[action] add cppcheck project and action debug

---

.github/workflows/static_code_analysis.yml

[
路径还是不对，修改为makefile形式
- BSP:
- .config:
- action:
]

[action] fix cppcheck build dir 

---

bsp/n32/libraries/n32_drivers/drv_rtc.c

[
默认每次上电都重置备份BKP,导致每次上电RTC时间都会重置为2000年
这个rtc驱动文件, rt-thread/bsp/n32/libraries/n32_drivers/drv_rtc.c的static rt_err_t n32_rtc_init(void)函数,
在PWR_BackupAccessEnable(ENABLE);后面读备份数据并校验是否为首次初始化.
- BSP:
- .config:
- action:
]
- [* ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [* ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [* ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [* ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [* ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [* ] …

[bsp/n32] 修复每次上电都初始化RTC导致上电时间被重置的问题

---

bsp/hpmicro/hpm5300evk/SConstruct
bsp/hpmicro/hpm5300evk/board/linker_scripts/flash_rtt.ld
bsp/hpmicro/hpm5301evklite/SConstruct
bsp/hpmicro/hpm5301evklite/board/linker_scripts/flash_rtt.ld
bsp/hpmicro/hpm6200evk/SConstruct
bsp/hpmicro/hpm6200evk/board/linker_scripts/flash_rtt.ld
bsp/hpmicro/hpm6300evk/SConstruct
bsp/hpmicro/hpm6300evk/board/linker_scripts/flash_rtt.ld
bsp/hpmicro/hpm6750evk/SConstruct
bsp/hpmicro/hpm6750evk/board/linker_scripts/flash_rtt.ld
bsp/hpmicro/hpm6750evk2/SConstruct
bsp/hpmicro/hpm6750evk2/board/linker_scripts/flash_rtt.ld
bsp/hpmicro/hpm6750evkmini/SConstruct
bsp/hpmicro/hpm6750evkmini/board/linker_scripts/flash_rtt.ld
bsp/hpmicro/hpm6800evk/SConstruct
bsp/hpmicro/hpm6800evk/board/linker_scripts/flash_rtt.ld
bsp/hpmicro/hpm6e00evk/SConstruct
bsp/hpmicro/hpm6e00evk/board/linker_scripts/flash_rtt.ld

[
- BSP:
- .config:
- action:
]

[bsp][hpmicro]添加utest相关段信息，修复scons编译问题

---

tools/ci/cpp_check.py

'--check-level=exhaustive'
这个选项可以更深入的在分支中检测，但是会耗时比较久一些。
[
- BSP:
- .config:
- action:
]

[action][ci] add cppcheck new feature

---

bsp/nxp/mcx/mcxc/Libraries/drivers/drv_spi.c
bsp/nxp/mcx/mcxc/Libraries/drivers/drv_spi.h
bsp/nxp/mcx/mcxc/frdm-mcxc444/board/Kconfig

[
增加MCX C444 SPI驱动支持。
Add support for MCX C444 SPI driver.
如上。
See above.
- BSP:
- bsp/nxp/mcx/mcxc/frdm-mcxc444
- .config:
- BSP_USING_SPI=y
- BSP_USING_SPI0=y
- BSP_USING_SPI1=y
- action:
- N/A
]

bsp: nxp/mcx/mcxc/mcxc444: Add SPI driver support.

---

components/lwp/SConscript

此目录中为rv64通用代码
[
方便支持更多rv64 cpu
- BSP:
- .config:
- action:
]

[lwp] 取消脚本中限制rv的具体cpu类别

---

components/net/lwip/lwip-2.1.2/src/include/lwip/sockets.h
components/net/sal/impl/af_inet_lwip.c

[
- BSP:
- .config:
- action:
]

[components][lwip]fix lwip poll macro conflict

---

.github/labeler.yml

[
- BSP:
- .config:
- action:
]

[ci]完善组件中的ci-labels

---

components/net/netdev/include/netdev.h
components/net/netdev/src/netdev.c
components/net/sal/src/sal_socket.c

[
netdev_lo无需单独处理，可以根据协议去找对应的网络设备
- BSP:
- .config:
- action:
]

[component][sal]delete netdev_lo

---

.github/labeler.yml

修正#9441-label路径设置错误问题
[
- BSP:
- .config:
- action:
]

[ci]修正#9441-label路径设置错误

---

components/dfs/dfs_v2/filesystems/devfs/devfs.c

[
The mode permissions for character, block, and pipe devices were previously set to 0777, which is overly permissive and not in line with standard practice (😂 User would never want to execute their device in daily life). This change reduces the permissions to 0666, restricting execute permissions while still allowing read/write access.
Changes:
- Adjusted permissions for character/block/pipe devices from 0777 to 0666.
- BSP:
- .config:
- action:
]

fixup: dfs_v2: correct device mode permissions in devfs

---

libcpu/risc-v/SConscript

[
vendor目录添加其他cpu型号后不用修改脚本
- BSP:
- .config:
- action:
]

[libcpu]优化rv构建脚本中选择vendor目录的判断条件

---

components/drivers/core/device.c

[
Device name may not be terminated by a null character which should be considered during logging.
Reopening a device with a same oflag should do nothing but increase the reference counter. In here no matter what the oflag is it just do the open again. It is not what we want.
fix it
- BSP:
- .config:
- action:
]

[fix]:fix log format and reopen with a different oflag issue

---

components/lwp/arch/aarch64/cortex-a/lwp_gcc.S
libcpu/aarch64/common/include/vector_gcc.h
libcpu/aarch64/common/up/context_gcc.h
libcpu/aarch64/common/up/vector_gcc.S
libcpu/aarch64/common/vector_gcc.S

[
This patch optimizes the user-space context handling in the ARM64 architecture, specifically improving how the context is saved and restored during system calls and interrupts. The changes make the code more efficient and easier to maintain, while ensuring proper preservation of user context during system transitions.
Changes:
- Introduced a parameter for context saving to improve flexibility.
- Replaced hardcoded stack pointer operations with frame-relative references for better readability and code reuse.
- Simplified context restoration, removing redundant operations like loading/storing floating-point registers.
- BSP:
- .config:
- action:
]

feat: smart: user space context optimization

---

src/klibc/kstdio.c

[
- BSP:
- .config:
- action:
]

[klibc] format comments after #9459

---

components/finsh/msh.c

[
#9397 
将 [line 758](https://github.com/RT-Thread/rt-thread/blob/66dd03f6c26caa15adb174e36f11544f60d3dadf/components/finsh/msh.c#L758)的`dir`改为`link_dir`
- BSP:
- .config:
- action:
]

[components]msh_double_name

---

include/rtdef.h

[
Those definitions are presented in rtdef.h until PR #9461 moved them into kerrno.h, which introduced the `unknown definition` error for project building.
Changes:
- Added includes of kerrno.h in rtdef.h
- BSP:
- .config:
- action:
]

feat: includes: included kerrno.h in rtdef.h

---

components/drivers/include/drivers/dac.h

[
#9424 
- BSP:
- .config:
- action:
]

[doxygen][rsoc]add dac driver example for doxygen

---

components/drivers/include/drivers/adc.h
components/drivers/include/drivers/dac.h
components/drivers/include/drivers/dev_rtc.h

[
#9424 
- BSP:
- .config:
- action:
]

[doxygen][rsoc]add rtc devices example for doxygen

---

bsp/at32/libraries/rt_drivers/drv_pwm.c

[
[bsp/at32] update pwm driver
]

[bsp/at32] update pwm driver

---

components/drivers/rtc/Kconfig
components/drivers/rtc/dev_alarm.c

[
sorry for the commit #9488. there are mistakes about the alarm thread parameters.  I realized it this morrning when I woke up but the merge happend so quickly so I have to submit this PR to fix it up asap.
- BSP:
- .config:
- action:
]

[fixup] fix rtc alarm thread parameters issue

---

README.md

[
- BSP:
- .config:
- action:
]

[docs](readme)add hellogithub

---

components/utilities/ulog/ulog.c

[
- BSP:
- .config:
- action:
]

[components][ulog] ULOG_OUTPUT_LEVEL未定义时,level_output_info产生警告

---

components/drivers/i2c/dev_i2c_core.c

[
- BSP:
- .config:
- action:
]

[components][i2c] 修改为debug等级打印

---

components/drivers/include/drivers/pci.h
components/drivers/pci/pci.c

[
add pci api,user maybe need addr of io or memory and remap it so can have a api to return struct which include the mem info that user need
- BSP:
- .config:
- action:
]

[feat]add pci api

---

components/drivers/include/drivers/dev_spi.h
components/drivers/spi/dev_qspi_core.c
components/drivers/spi/dev_spi_core.c

cherry-pick from https://github.com/RT-Thread/rt-thread/pull/9501
[
- BSP:
- .config:
- action:
]

[spi] rt_spi_bus_configure 添加 -RT_EBUSY 返回值

---

bsp/stm32/stm32l475-atk-pandora/board/ports/arduino/SConscript
bsp/stm32/stm32l475-atk-pandora/board/ports/arduino/ST7789_tft_espi_demo.cpp

[
- BSP:
- .config:
- action:
]

[RTduino] support TFT_eSPI demo

---

.github/workflows/manual_dist.yml

[
移除debug 选项，会报错。这个option选项不好用。
- BSP:
- .config:
- action:
]

[action] remove debug option

---

.github/workflows/action_tools.yml

[
- BSP:
- .config:
- action:
]

[action] open action_tools.yml

---

libcpu/risc-v/common64/trap.c

[
When an exception occurs, the printed exception information about the register values includes redundant "0x" .
remove the redundant '0x' print.
- BSP: bsp/qemu-virt64-riscv
- .config:
- action:
]

[libcpu][risc-v]remove the redundant "0x" from the printed information when cpu is in exception

---

components/drivers/spi/dev_spi_core.c

[
修复因spi配置中检测重复配置而导致的互斥锁释放问题
当检测到spi bus已经完成配置后，会返回-RT_EBUSY，需要在此之前释放该bus持有的互斥锁
修复前：
修复后：
- BSP:
- .config:
- action:
]

[drivers][spi] Fixed an issue that caused spi bus deadlock in the spi configuration

---

components/dfs/dfs_v1/src/dfs_file.c

[
- BSP:
- .config:
- action:
]

[components][dfs][dfs_v1]cat输出实际读取的长度

---

components/drivers/smp/smp.c

[
- BSP:
- .config:
- action:
]

[components][smp]remove redundant memset & unlock in smp

---

README.md

图标太大了，改小一些
[
- BSP:
- .config:
- action:
]

[doc]Update README.md

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_gpio.c

[
fix for issue #9398 
- BSP:
- .config:
- action:
]

move `GPIO_InitStruct` variable inside to `PIN_IRQ_ENABLE`

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_gpio.c

fix https://github.com/RT-Thread/rt-thread/pull/9525
[
- BSP:
- .config:
- action:
]

[bsp][stm32] fix variable init

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart.c

[
当超时的时候使用后置--，0就会变成2^32 -1
使得无论是否超时都会被判定成发送成功
使用前置--
`--block_timeout`
- BSP:
- .config:
- action:
]

[bsp][stm32][rsoc]串口超时判断逻辑有问题

---

src/scheduler_up.c

[
- BSP:
- .config:
- action:
]

fix:[src]type of 'rt_interrupt_nest' does not match original declaration

---

components/drivers/include/ipc/completion.h
components/drivers/spi/dev_spi_flash_sfud.h

[
给某些漏掉的地方添加
```c++
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
```
]

add missing extern "C" in header to support cpp

---

.github/PULL_REQUEST_TEMPLATE.md

[
添加PR部分CI提醒
- BSP:
- .config:
- action:
]

[doc] Update PULL_REQUEST_TEMPLATE.md

---

bsp/hc32/libraries/hc32_drivers/drv_spi.c

[
小华SPI驱动中获取cs脚方式似乎有点问题，`rt_spi_bus_attach_device_cspin`只会把cs脚存到`spi_dev_lcd->cs_pin`中而不是`spi_dev_lcd->parent.user_data`
参照st的驱动修改
- BSP:hc32f460
- .config:
- action:
]

[bsp][hc32] 修复SPI驱动的片选脚获取方式

---

src/clock.c

[
- BSP:
- .config:
- action:
]

[src][clock] RT_TICK_PER_SECOND为1000时tick不用进行转换

---

components/libc/compilers/common/ctime.c
components/libc/compilers/musl/fcntl.h
components/lwp/lwp_syscall.h

[
- BSP:
- .config:
- action:
]
- [√] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [√] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [√] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP

[Toolchain] Some modifications made by the toolchain update

---

libcpu/Kconfig

[
m7同样也支持硬件原子指令
[ref](https://developer.arm.com/documentation/dui0646/b/The-Cortex-M7-Processor/Memory-model/Programming-hints-for-the-synchronization-primitives?lang=en)
- BSP: artpi
- .config:
- action:
]

[libcpu][m7]use hw atomic

---

include/rtcompiler.h

[
Origin:
`__ARMCC_VERSION`: 
- https://smtp.keil.com/support/man/docs/armcc/armcc_chr1359124980173.htm
`__IAR_SYSTEMS_ICC__`: 
- Not Found
`__GNUC__`:
- https://gcc.gnu.org/onlinedocs/gcc/Common-Type-Attributes.html#index-packed-type-attribute
`__ADSPBLACKFIN__`:
- Not Found
`_MSC_VER`:
- https://learn.microsoft.com/en-us/cpp/preprocessor/pack?view=msvc-170
`__TI_COMPILER_VERSION__`:
- https://software-dl.ti.com/codegen/docs/tiarmclang/rel1_3_0_LTS/migration_guide/migrating_c_and_cpp_source/pragmas_and_attributes.html
`__TASKING__`:
- https://resources.tasking.com/sites/default/files/2021-02/TASKING_Alignment%20Requirements%20Restrictions_WEB.pdf
Usage:
```c
rt_packed(struct object1
{
int dword;
char byte;
});
typedef struct object1 object1;
rt_packed(struct object2
{
int dword;
char …
```

[COMPILER/FEATURE] Support rt_packed

---

components/net/at/at_socket/at_socket.c

[
#9572 
- BSP:
- .config:
- action:
]

[components/net/at]修复at socket信号量释放异常

---

components/net/lwip/Kconfig
components/net/lwip/port/lwipopts.h

[
Refer：https://www.nongnu.org/lwip/2_1_x/group__lwip__opts__hooks.html
ps：为RT-Thread使能 **LWIP_HOOK_UNKNOWN_ETH_PROTOCOL** 的支持，留出lwip钩子提供给未知以太网协议以处理用户需求
- BSP:
- .config:
- action:
]

[net][lwip] lwip hook functions are provided to provide greater flexibility for unknown Ethernet protocols

---

components/finsh/shell.c

[
使用telnet，并打开RT_USING_POSIX_STDIO时，需使用get_console来get_char，否则不能正确获取输入
get_char时使用get_console获取console描述符
]

[components][finsh]在RT_USING_POSIX_STDIO时，使用get_console获取当前console描述符

---

tools/ci/bsp_buildings.py

[
通过attachconfig.yml添加ci的时候自动递归attachconfig文件夹下所有的yml文件来进行添加ci
- BSP:
- .config:
- action:
]

[action] Recursive folder lookup attachconfig.yml

---

.github/workflows/action_tools.yml
tools/options.py

[
project name默认为'project'，在RTT Studio中导入多个工程时，名字都是一样的，导致不能导入
修改默认project name为当前目录名
]

[tools] use project's dir basename as default project name

---

bsp/nrf5x/nrf52840/.ci/attachconfig/ci.attachconfig.yml
tools/ci/bsp_buildings.py

[
yml file 添加depends参数
另外支持depends的循环嵌套，如果发生depends之间的死循环会报提示
按照yml开启配置顺序来对应.config的开启配置顺序
添加depend_scons_arg参数支持，当父配置开启，子配置一同开启
- BSP:
- .config:
- action:
]

[action] yml file adds the depends parameter

---

.github/workflows/bsp_buildings.yml
bsp/nrf5x/nrf52832/.ci/attachconfig/ci.attachconfig.yml
tools/ci/bsp_buildings.py

[
修复attachconfig 使其适配yml语法特性
另外在bsp_buildings把nordic单独开一个组用来跑ci
使用yml原来语法特性替代depend_scons_arg参数
- BSP:
- .config:
- action:
]

[action] attachconfig adapts yml syntax features

---

bsp/hc32/libraries/hc32_drivers/drv_usart.c
bsp/hc32/libraries/hc32_drivers/drv_usart_v2.c

[
hc32的uart驱动如果打开了gcc优化，dma不能正确传输
寄存器读取宏，加上volatile关键字，阻止被优化
]

[bsp/hc32] fix uart dma if gcc optimization level is not none

---

.github/workflows/bsp_buildings.yml

[
rockchip/rk3568编译时间太长，暂时移除，后续调查原因再上传
- BSP:
- .config:
- action:
]

[action] remove rockchip/rk3568 because of the complie time

---

bsp/nxp/mcx/mcxa/Libraries/drivers/drv_uart.c
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/Kconfig
bsp/nxp/mcx/mcxa/frdm-mcxa153/board/MCUX_Config/board/pin_mux.c

[
add more UART channels in NXP mcxa153 board
add UART1 && UART2 BSP drivers in `bsp\nxp\mcx\mcxa` directory
- BSP: BSP_USING_UART1 BSP_USING_UART2
Please provide the changed config of .config file to how to verify the PR file like CONFIG_BSP_USING_I2C CONFIG_BSP_USING_WDT -->
- .config: CONFIG_BSP_USING_UART1  CONFIG_BSP_USING_UART2
- action: https://github.com/hywing/rt-thread/commit/da6fedbe8289f216263dac998f90f17a45398232
]

[bsp][nxp][mcxa153] add more UART channels

---

bsp/gd32/arm/libraries/gd32_drivers/drv_rtc.c

[
fix #9167 
- BSP:  bsp/gd32/arm/gd32205r-start
- .config: no update
- action:  N/A
]

[bsp][gd32][fix rtc clock selection]

---

components/net/sal/socket/net_sockets.c

[
BSD socket APIs has no comments.
add comments for BSD socket APIs to make the code easier to read.
- BSP:
- .config:
- action:
]

[net][sal]add comments for BSD socket APIs.

---

components/libc/posix/pthreads/pthread.c

[
pthread posix APIs in pthread.c have no comments.
add comments for each api in pthread.c to make it easier to read.
- BSP:
- .config:
- action:
]

[components/libc/posix][pthreads]add comments for thread APIs of pthread.

---

components/libc/compilers/common/include/dirent.h
components/lwp/lwp_syscall.c

[
- BSP:
- .config:
- action:
]

[filesystem]Modify the position of libc_rent definition

---

bsp/stm32/stm32f412-st-nucleo/board/linker_scripts/link.lds

[
- BSP:
- .config:
- action:
]

[utest][stm32f412][gcc] add __rt_utest_tc_tab_start to support utest

---

libcpu/aarch64/common/mmu.c
libcpu/aarch64/common/setup.c

[
- BSP:
- .config:
- action:
]

[libcpu] fix No memory higher than 1 GB is mapped

---

components/libc/posix/pthreads/pthread_mutex.c

[
pthread_mutex APIs have no comments.
add comments for mutex APIs.
- BSP:
- .config:
- action:
]

[components/libc/posix]add comments for mutex APIs.

---

src/Kconfig

[
- BSP:
- .config:
- action:
]

[ci] add RT_USING_CI_ACTION

---

components/drivers/Kconfig.dm
components/drivers/clk/Kconfig
components/drivers/clk/clk.c
components/drivers/include/drivers/clk.h
components/drivers/ofw/ofw.c

[
1. Default return OK when input NULL (if is not necessary in device), have error ptr now.
2. Support object parse in OFW.
3. Support CLK depends fix auto.
4. Fixup rt_clk_array_prepare_enable and rt_clk_array_disable_unprepare.
5. Support import SoC CLK config
Depends on: https://github.com/RT-Thread/rt-thread/pull/9576
- BSP:
1. qemu-virt64-aarch64
2. rockchip/rk3568
]

[DM/FEATURE] Update CLK core

---

components/drivers/pci/msi/irq.c

[
1. Fixup PCI MSI global irq map.
2. Fixup MSI first IRQ read offset
- BSP:
***MSI is no longer commonly used and only emulators can be used***
]

[DM/FIXUP] Fixup MSI setup

---

components/drivers/Kconfig.dm
components/drivers/clk/Kconfig

[
Open Kconfig will not fail if using osource,
This way can make SoC Kconfig to DM easy.
Link: ecb89b1370ec27be650a0a2fae7c6802b4246933
]

[DM/FEATURE] make SoC Kconfig import easy

---

bsp/qemu-virt64-riscv/driver/Kconfig

[
bsp/qemu-virt64-riscv/driver/Kconfig中的BSP_USING_UART1配置没有相应的驱动支持，且qemu中uart不会有PIN的设置，建议删除（该配置与k210 bsp中的BSP_USING_UART1配置完全相同）
- BSP:bsp/qemu-virt64-riscv
- .config:
- action:
]

[bsp][qemu-virt64-riscv]:remove the redundant UART1 configuration

---

libcpu/risc-v/common64/mmu.c

[
- BSP:
- .config:
- action:
]

[libcpu][riscv]纠正pv_offset的对齐检查

---

src/Kconfig
src/klibc/Kconfig
src/klibc/SConscript
src/klibc/kstdio.c
src/klibc/kstring.c
src/klibc/rt_vsnprintf_std.c
src/klibc/rt_vsnprintf_tiny.c

[
- BSP:
- .config:
- action:
]

[klibc] separate klibc Kconfig

---

bsp/nuvoton/libraries/m460/rtt_port/drv_common.c
bsp/nuvoton/libraries/ma35/rtt_port/drv_disp.c
bsp/nuvoton/libraries/ma35/rtt_port/drv_sys.c
bsp/nuvoton/libraries/n9h30/rtt_port/drv_common.c
bsp/nuvoton/libraries/nu_packages/Demo/wormhole_demo.c
components/drivers/phy/ofw.c
components/net/at/at_socket/at_socket.c
examples/test/avl.c

[
- BSP:
- .config:
- action:
]

[sscanf] use rt_sscanf to replace sscanf

---

src/klibc/Kconfig

[
- BSP:
- .config:
- action:
]

[klibc] format Kconfig

---

bsp/hc32/ev_hc32f448_lqfp80/board/ports/drv_spi_flash.c
bsp/hc32/ev_hc32f460_lqfp100_v2/board/ports/drv_spi_flash.c
bsp/hc32/ev_hc32f4a0_lqfp176/board/ports/drv_spi_flash.c
bsp/hc32/lckfb-hc32f4a0-lqfp100/board/ports/drv_spi_flash.c
bsp/hc32/libraries/hc32_drivers/drv_spi.c
bsp/hc32/libraries/hc32_drivers/drv_spi.h
bsp/hc32/platform/sfud/drv_spi_flash.c

[
更新rt_hw_spi_device_attach和相关bsp.  关联#9585 
- BSP:
- .config:
- action:
]

[bsp][hc32][spi]update rt_hw_spi_device_attach

---

components/libc/compilers/common/ctime.c

[
#9745
未使能RTC时使用其它时钟源替代
- BSP:
- .config:
- action:
https://github.com/wycwyhwyq/rt-thread/pull/1
]

[components] When rtc is not enabled, use other clock sources instead

---

src/klibc/Kconfig

[
- BSP:
- .config:
- action:
]

fix:[klib]Kconfig显示文案错误

---

tools/eclipse.py
tools/mkdist.py
tools/utils.py
tools/wizard.py

[
当前c++的文件扩展不支持 .cc
增加 .cc 支持，在 rt thread studio 下测试通过
]

增加c++文件扩展 .cc

---

bsp/wch/risc-v/ch32v103r-evt/Kconfig
bsp/wch/risc-v/ch32v208w-r0/Kconfig
bsp/wch/risc-v/ch32v307v-r1/Kconfig
bsp/wch/risc-v/ch569w-evt/Kconfig
bsp/wch/risc-v/yd-ch32v307vct6/Kconfig

[
在bsp/wch/risc-vch32v307v-r1 下执行scons --menuconfig 时报错：
menuconfig: Kconfig:11: '../libraries/Kconfig' not found (in 'rsource "../libraries/Kconfig"'). 
通过修改Kconfig:49 rsource "../libraries/Kconfig" -> rsource "../Libraries/Kconfig"
- BSP:
- .config:
- action:
]

[bsp][ch32] fix menuconfig error for risc-v

---

components/lwp/terminal/freebsd/tty.c

[
- BSP:
- .config:
- action:
]

[lwp] fix TTYSUP_CFLAG did not include CBAUD flag

---

libcpu/aarch64/common/mmu.c

[
Improves the memory mapping process by dynamically selecting the optimal paging stride (4K or 2M) based on virtual address alignment and mapping size. This eliminates the need for upfront stride determination, enhancing flexibility and maintainability in memory management.
Changes:
- Replaced fixed stride selection logic with a dynamic decision loop.
- Removed `npages` calculation and replaced with `remaining_sz` to track unprocessed memory size.
- Added assertions to ensure `size` is properly aligned to the smallest page size.
- Adjusted loop to dynamically determine and apply the appropriate stride (4K or 2M) for each mapping iteration.
- Updated virtual and physical address increments to use the dynamically selected stride.
- BSP:
- .config:
- action:
] …

feat: arm64: mmu: auto-sensing of best paging stride

---

components/drivers/ofw/base.c

[
strcasecmp is not a weak symbol.It's unnecessarily to keep it.
- BSP:
- .config:
- action:
]

[OFW] Delete redundant strcasecmp function

---

bsp/cvitek/README.md

参考 <https://github.com/RT-Thread-packages/lwext4/issues/26>。
Now lwext4 package has supported ext4. Add description in README to introduce how to create rootfs of type ext4.
[
- BSP:
- .config:
- action:
]

bsp: cvitek: update README for ext4 rootfs

---

src/kservice.c
src/thread.c
tools/building.py
tools/zigbuild.py

[
添加zig编译支持，zig支持使用clang+llvm编译c/c++项目，及原生支持交叉编译。编译出的固件体积相对于gcc也有优势。
- 不过zig对于裸机编译并没有c库支持，所以需要开启mlibc。
- 目前mlibc还不是非常完善，目前基于nano的情况下测试，stm32平台可以正常编译运行。
- zig原生支持交叉编译的优势，只需要一个zig工具，就可以在全平台（linux,win,mac），编译出各种架构的固件（arm,riscv,mips等）。不需要安装各类gcc-xxx工具链。
- 相同代码的情况下，固件体积：gcc+newlib 31K, gcc+mlibc 30K，zig+mlibc 28K。
生成build.zig文件，然后使用命令zig build编译
- BSP:
stm32f407-rt-spark
- .config:
CONFIG_RT_USING_NANO=y
CONFIG_PKG_USING_MLIBC=y
- action:
]

[tools] add zig target

---

bsp/cvitek/drivers/libraries/types.h

Fixed:  #9798
GPL is conflict with Apache, which is used by RTT.
See <https://www.apache.org/licenses/GPL-compatibility.html>
Also clean up and remove some words such "LINUX".
[
- BSP:
- .config:
- action:
]

bsp: cvitek: remove GPL license declaration

---

components/drivers/sdio/Kconfig
components/drivers/sdio/SConscript
components/drivers/sdio/sdhci/fit-mmc.c
components/drivers/sdio/sdhci/include/sdhci-platform.h
components/drivers/sdio/sdhci/include/sdhci.h
components/drivers/sdio/sdhci/include/sdhci_host.h
components/drivers/sdio/sdhci/include/sdhci_misc.h
components/drivers/sdio/sdhci/sdhci-platform.c
components/drivers/sdio/sdhci/sdhci.c

[
add general sdhci driver and it support pio&&sdma
- BSP:
rk3568
- .config:
- action:
]

[dm2.0] add general sdhci driver it support pio&&sdma

---

bsp/cvitek/README.md

Updated README for cvitek.
[
- BSP:
- .config:
- action:
]

bsp: cvitek: doc update

---

bsp/stm32/stm32l496-st-nucleo/.ci/attachconfig/ci.attachconfig.yml
bsp/stm32/stm32l496-st-nucleo/.ci/attachconfig/nano.attach

[
添加on-chip config
- BSP:
- .config:
- action:
]

[bsp][stm32l496zg] add onchip config

---

components/dfs/dfs_v2/filesystems/romfs/dfs_romfs.c

[
dfs_v2 romfs fops 里面的 ioctl 没有赋值
- BSP:
- .config:
- action:
]

dfs_v2 romfs fops ioctl 赋值

---

src/klibc/rt_vsscanf.c
src/klibc/utest/TC_rt_sscanf.c

旧版rt_vsscanf有部分格式不支持。
从libphoenix移植了其vsscanf实现。兼容Apache2.0协议。
https://github.com/phoenix-rtos/libphoenix/blob/master/stdio/scanf.c
并补充rt_vsscanf测试用例。测试用例均通过。
并修复：https://github.com/RT-Thread/rt-thread/issues/9853
[
- BSP: 
- .config:
- action:
]

[rt_vsscanf] upgrade version and add test case

---

.github/workflows/action_tools.yml
.github/workflows/action_utest.yml
.github/workflows/auto_labeler.yml
.github/workflows/bsp_buildings.yml
.github/workflows/compile_bsp_with_drivers.yml
.github/workflows/format_check.yml
.github/workflows/manual_bsp_build.yml
.github/workflows/manual_dist.yml
.github/workflows/manual_trigger_scons_STM32_all.yml
.github/workflows/manual_trigger_scons_except_STM32_all.yml
.github/workflows/manual_trigger_scons_fail_bsp_all.yml
.github/workflows/manual_trigger_update_all.yml
.github/workflows/spell_check.yml
.github/workflows/static_code_analysis.yml

[
action CI 环境改变，导致ci不过。
- BSP:
- .config:
- action:
]

[action] set runner to ubuntu22.04

---

bsp/hpmicro/libraries/drivers/drv_sdio.c

- corrected the alignement check logic
- optimized the cache maintenance logic
[
Fix alignement check logic issue (see #9784)
Optimize the cache maintenance logic for the buffer which  crosses cacheline 
Verified on HPM6800EVK
]

[bsp][hpmicro] fix the alignement check logic and the cache-maintenance logic

---

bsp/qemu-virt64-riscv/driver/board.h

[
opensbi占据了一部分内存需要减掉
- BSP:
- .config:
- action:
]

[bsp][qemu-virt64-riscv]修正内存大小超限制的问题

---

components/lwp/lwp.c
libcpu/arm/cortex-a/backtrace.c
libcpu/arm/cortex-r52/backtrace.c
src/kservice.c

[
- BSP:
- .config:
- action:
]

fix: add \n for addr2line hint

---

components/dfs/dfs_v2/filesystems/devfs/devfs.c

[
dfs_devfs_open存在memory leak
添加rt_free
- BSP:
K230
- .config:
- action:
https://github.com/wycwyhwyq/rt-thread/pull/3
]

[components][dfs_v2]: Fix dfs_devfs_open memory leak

---

tools/ci/cpp_check.py

#9906 
- BSP:
- .config:
- action:
]

fix cppcheck in lwp.c will fail if no define RT_USING_DFS

---

components/utilities/utest/TC_uassert.c
components/utilities/utest/utest_assert.h

部分uassert会操作操作数两次，这并不符合用户预期。
[
- BSP:
- .config:
- action:
]

[utest] fix twice operation of uassert

---

components/lwp/lwp_pid.c

[
msh中killall无法终结进程
原来的cmd域存储的名称太短，换为使用exe_file
- BSP:
k230
- .config:
- action:
]

[lwp]修正无法通过文件名查找pid的问题

---

bsp/hc32/ev_hc32f448_lqfp80/board/board.c
bsp/hc32/ev_hc32f460_lqfp100_v2/board/board.c
bsp/hc32/ev_hc32f472_lqfp100/board/board.c
bsp/hc32/ev_hc32f4a0_lqfp176/board/board.c
bsp/hc32/lckfb-hc32f4a0-lqfp100/board/board.c
bsp/hc32/libraries/hc32_drivers/drv_pm.c
bsp/hc32/libraries/hc32_drivers/drv_pm.h
bsp/hc32/tests/test_pm.c

[
Add pm driver for F472 and add lVD unlock in board_init.
]
- [✔ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo
- [✔ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [✔ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [✔ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [✔ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [✔ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [✔ ] 代码是高质量的 Code in this PR is of high quality
- [✔ ] …

Add pm driver for F472 and add lVD unlock in board_init.

---

.github/workflows/bsp_buildings.yml
bsp/cvitek/c906_little/rtconfig.py

[
- BSP:
- .config:
- action:
]

[action] add cvitek/c906_little ci

---

tools/requirements.txt

Add requirements.txt for python packages installation.
[
在linux上使用rt-thread，准备环境时需要安装必要的python包。
添加 requirements.txt 文件。
- BSP:
N/A
- .config:
N/A
- action:
]

[tools] Add requirements.txt for python packages

---

bsp/stm32/stm32f407-rt-spark/.ci/attachconfig/ci.attachconfig.yml

添加 [llmchat ](https://github.com/Rbb666/llm_chat) 软件包检查到星火1号BSP.
[
- BSP:
- .config:
- action:
]

[action]add online packages checking in rt-spark.

---

bsp/nxp/lpc/lpc55sxx/lpc55s69_nxp_evk/board/Kconfig
bsp/raspberry-pico/board/Kconfig
bsp/renesas/ra6m3-hmi-board/board/Kconfig
bsp/stm32/libraries/HAL_Drivers/drivers/SConscript
bsp/stm32/libraries/HAL_Drivers/drivers/drv_soft_spi.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_spi.c
bsp/stm32/stm32f407-atk-explorer/board/Kconfig
bsp/stm32/stm32f407-fk407m2-zgt6/board/Kconfig
bsp/stm32/stm32f407-lckfb-skystar/board/Kconfig
bsp/stm32/stm32f407-rt-spark/board/Kconfig
bsp/wch/risc-v/ch32v208w-r0/board/Kconfig
bsp/wch/risc-v/ch32v307v-r1/board/Kconfig
bsp/wch/risc-v/yd-ch32v307vct6/board/Kconfig
components/drivers/spi/Kconfig
components/drivers/spi/SConscript

[
- BSP:
- .config:
- action:
]

[drivers/spi]统一软件SPI配置

---

components/dfs/dfs_v2/include/dfs.h
components/dfs/dfs_v2/src/dfs.c
components/dfs/dfs_v2/src/dfs_file_mmap.c

[
- BSP:
- .config:
- action:
]

[dfs]mmap的文件在关闭后释放file指针

---

bsp/qemu-vexpress-a9/.ci/attachconfig/ci.attachconfig.yml

[
- BSP:
- .config:
- action:
]

ci: add qemua9 yml file

---

components/utilities/ulog/backend/file_be.c

file_buf 被错误释放了
[
- BSP:
- .config:
- action:
]

[ulog]Fix the problem of file_buf being released incorrectly

---

bsp/nxp/mcx/mcxa/frdm-mcxa156/board/linker_scripts/MCXA156_flash.ld

[
修复FRDM-MCXA156 GCC编译后运行问题
Fix run-time issue for FRDM-MCXA156 compiled by GCC.
在原厂链接脚本增加RT-Thread常量表section。
This patch modifies the original linker script provided by NXP by adding RT-Thread related constant tables to flash.
- BSP:
-  bsp/nxp/mcx/mcxa/frdm-mcxa156
- .config:
- N/A
- action:
]

ports: nxp/mcx/mcxa/frdm-mcxa156: Fix GNU toolchain builds.

---

documentation/run.sh

Github CI doc_doxygen is very strict in checking the build results, and will output failure even if there are warnings.
In order to match CI's checks, local build scripts are also checked more strictly to detect potential errors and even warnings as early as possible.
[
See commit comment please.
- BSP:
- .config:
- action:
]

doxygen: More strict checks on build results

---

bsp/hpmicro/hpm5300evk/rtconfig.py
bsp/hpmicro/hpm5301evklite/rtconfig.py
bsp/hpmicro/hpm6200evk/rtconfig.py
bsp/hpmicro/hpm6300evk/rtconfig.py
bsp/hpmicro/hpm6750evk/rtconfig.py
bsp/hpmicro/hpm6750evk2/rtconfig.py
bsp/hpmicro/hpm6750evkmini/rtconfig.py
bsp/hpmicro/hpm6800evk/rtconfig.py
bsp/hpmicro/hpm6e00evk/rtconfig.py
bsp/hpmicro/tools/sdk_dist.py

- added tools and dist_handle function
[
Fix the issue  #10012
- add sdk_dist.py to tools fonder under bsp/hpmicro
- add dist_handle function to rtconfig.py in each hpmicro bsp
- BSP:
- .config:
- action:
]

[bsp][hpmicro] fix 'scons -dist' issue in the hpmicro bsps.

---

documentation/run.sh

Previously, you had to enter the documentation directory before executing the run.sh script, which was not very convenient during development, especially when you needed to execute other commands in the source code root directory at the same time, such as git commands.
Now you can directly run script in the source code root directory as below:
```shell
$ cd $RTT
$ ./documentation/run.sh
```
No need to switch the working path any more after entering the source code root directory.
[
See commit comment please.
- BSP:
- .config:
- action:
]

doxygen: support running from the root directory

---

include/rtthread.h

[
fixed: https://github.com/kurisaW/rt-thread/actions/runs/13403668868/job/37439518261
- BSP:
- .config:
- action:
]

fix: clear the error message from the function declaration of signal in qemu-a9 smp mode

---

bsp/nxp/mcx/mcxa/frdm-mcxa156/rtconfig.py

[
- BSP:
- .config:
- action:
]

[bsp][nxp]:fix frdm-mcxa156 scons --dist err

---

bsp/nxp/mcx/mcxa/frdm-mcxa156/template.uvoptx

[
FRDM-MCXA156
1. MCXA156 模板工程实际上是FRDM-MCXA153的工程，虽说不影响使用，但是从git diff上看，就会发现，默认的156在运行scons --target=mdk5后会变成153.
2. 模板功臣默认的调试器未ulink，但实际上板载的调试器未cmsisdap，需要更改过来，否则每次生成工程都需要再次配置调试器
针对性修复问题
- BSP:
- bsp\nxp\mcx\mcxa\frdm-mcxa156
- .config:
不需要修改
- action:
]
- [*] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [*] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [*] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [*] …

mcxa156模板工程从mcxa153更新成mcxa156，且默认调试器改为cmsisdap，因为板载调试器为cmsisdap

---

bsp/nxp/mcx/mcxa/frdm-mcxa156/board/Kconfig

[
需要此 https://github.com/RT-Thread/packages/pull/1861 pr 合并
- BSP:
- .config:
- action:
]

[bsp][nxp]:add p3t1754 sensor

---

.github/workflows/bsp_buildings.yml
tools/ci/bsp_buildings.py

[
pkgs --update 重新下载太耗时间，改为强制
- BSP:
- .config:
- action:
]

[action/ci] pkgs --update-force instead of pkgs --update

---

bsp/nxp/mcx/mcxa/frdm-mcxa156/.ci/attachconfig/ci.attachconfig.yml
bsp/nxp/mcx/mcxa/frdm-mcxa156/board/SConscript
bsp/nxp/mcx/mcxa/frdm-mcxa156/board/ports/SConscript
bsp/nxp/mcx/mcxa/frdm-mcxa156/board/ports/cherryusb/SConscript
bsp/nxp/mcx/mcxa/frdm-mcxa156/board/ports/cherryusb/cherryusb.c
bsp/nxp/mcx/mcxa/frdm-mcxa156/board/ports/cherryusb/usb_config.h
components/drivers/usb/cherryusb/port/kinetis/README.md
components/drivers/usb/cherryusb/port/kinetis/usb_glue_mcx.c

[
添加mcxa156的cherryusb config文件进行适配，同时添加一个mcxa156的cherryusb的小demo
- BSP:bsp\nxp\mcx\mcxn\frdm-mcxn947
- .config:
- action:
]

[bsp][nxp] add cherryusb config for mcxa156

---

.github/workflows/action_tools.yml
bsp/stm32/tools/sdk_dist.py

[
scons --dist 在l4平台有问题  BSP_LIBRARY_TYPE 是None
- BSP:
- .config:
- action:
]

[action/tool] 验证l4平台, 修复scons --dist

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_lcd.c

[
* Optimize the lcd_test function to call it in thread to prevent the CLI environment from being unavailable after execution.
- BSP: [STM32H750/ART-PI](https://github.com/wdfk-prog/ART-PI)
- .config:[.config](https://github.com/wdfk-prog/ART-PI/commit/3d16d58fda041da7eeb977b66c35395e070f5ee4#diff-f0d022ac9475e1107028b8c6b61b7a058398400b4e5b11eb5aec7af15533b5dc)
- action:
]

fix:[stm32][lcd]Error in control call of lcd test function

---

components/drivers/spi/dev_spi.c

[
`chip_select` is array now, should use index of value.
]

Fixup device rename by chip_select

---

components/drivers/misc/rt_drv_pwm.c

[
- BSP:
- .config:
- action:
]

[components][pwm]:修复pwm msh 命令错误提示

---

tools/cmake.py

[
https://github.com/RT-Thread/rt-thread/blob/3fdb94096794be237e52abff0fb4ee150efeee79/tools/cmake.py#L35
这句话蛮耗时，但倒腾出了个env就有的玩意🤦‍♂️
相关PR和测试 https://github.com/RT-Thread/rt-thread/pull/10021
- BSP: ch32v208
- .config:
- action:
]

[tools][cmake] get some info from env to save time

---

bsp/stm32/stm32f723-st-disco/board/Kconfig
bsp/stm32/stm32f746-st-disco/board/Kconfig
bsp/stm32/stm32f746-st-nucleo/board/Kconfig
bsp/stm32/stm32f767-atk-apollo/board/Kconfig
bsp/stm32/stm32f767-fire-challenger-v1/board/Kconfig
bsp/stm32/stm32f767-st-nucleo/board/Kconfig
bsp/stm32/stm32f769-st-disco/board/Kconfig
bsp/stm32/stm32h503-st-nucleo/board/Kconfig
bsp/stm32/stm32h563-st-nucleo/board/Kconfig
bsp/stm32/stm32h723-st-nucleo/board/Kconfig
bsp/stm32/stm32h730-esphosted-evb/board/Kconfig
bsp/stm32/stm32h743-armfly-v7/board/Kconfig
bsp/stm32/stm32h743-atk-apollo/board/Kconfig
bsp/stm32/stm32h743-openmv-h7plus/board/Kconfig
bsp/stm32/stm32h743-st-nucleo/board/Kconfig
bsp/stm32/stm32h747-st-discovery/board/Kconfig
bsp/stm32/stm32h750-armfly-h7-tool/board/Kconfig
bsp/stm32/stm32h750-artpi/board/Kconfig
bsp/stm32/stm32h750-fk750m1-vbt6/board/Kconfig
bsp/stm32/stm32h750-weact-ministm32h7xx/board/Kconfig
bsp/stm32/stm32h7s7-st-disco/board/Kconfig

[
#10022 
- BSP:
- .config:
- action:
]

[bsp][stm32][uartv1]:adjust uart time out

---

.github/workflows/bsp_buildings.yml
.github/workflows/compile_bsp_with_drivers.yml
.github/workflows/format_check.yml
.github/workflows/static_code_analysis.yml

[
添加cache机制，优化下载toolchain的时间。
调整一下bsp_buildings.yml中的bsp结构，优化一下。
driver.yml暂时没用到，先关掉。
- BSP:
- .config:
- action:
]

[action/ci] 添加cache机制，整理ci_action的一些流程，暂时去掉drivers.yml

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_wdt.c

[
- BSP:
- .config:
- action:
]

fix: 修复星火一号看门狗驱动使能失败问题

---

bsp/at32/at32a423-start/SConstruct
bsp/at32/at32f402-start/SConstruct
bsp/at32/at32f405-start/SConstruct
bsp/at32/at32f415-start/SConstruct

[
[bsp/at32] fixed usb type library
]

[bsp/at32] fixed usb type library

---

components/mm/mm_anon.c

[
修正 https://github.com/RT-Thread/rt-thread/issues/9902
- BSP:
- .config:
- action:
]

[mm]修复unmap内存时遗漏刷新地址转换表的问题，避免dcache(PIPT)出错

---

components/drivers/include/drivers/dev_audio.h

[
**请先等待 #10094 合并后再合并当前pr**
#10065 
- BSP:
- .config:
- action:
]

[doxygen][audio] Naming anonymous enumeration type audio_stream

---

documentation/0.doxygen/example/include/groups.h

Fixes: 94afe6a4f1 ("doxygen: improve howto")
改正一个错误的 @ref 。
[
见 PR 描述。
- BSP:
- .config:
- action:
]

doxygen: fix wrong ref for group examples

---

bsp/stm32/stm32f103-atk-warshipv3/README.md

[
update README.md to correct the picture name for stm32f103-atk-warshipv3 board
correct the picture name
- BSP:
- .config:
- action:
]

[bsp][stm32][stm32f103-atk-warshipv3] update README.md to correct the picture name

---

include/rttypes.h

[
rttypes.h中，rt_intptr_t和rt_uintptr_t如下，应该正好反了
```
typedef rt_ubase_t                      rt_intptr_t;    /**< Type for signed pointer length integer */
typedef rt_base_t                       rt_uintptr_t;   /**< Type for unsigned pointer length integer */
```
修改如下：
```
typedef rt_base_t                      rt_intptr_t;    /**< Type for signed pointer length integer */
typedef rt_ubase_t                       rt_uintptr_t;   /**< Type for unsigned pointer length integer */
```
- BSP:
- .config:
- action:
]

rttypes.h中rt_intptr_t和rt_uintptr_t定义反了

---

components/drivers/dma/dma.c

[
The first arg is src, then dst.
]

[DM/DMA] DMA src and dst is wrong.

---

ChangeLog.md

[
- BSP:
- .config:
- action:
]

log: Release Log of rtthread v5.2.0

---

bsp/README.md

[
修复链接问题
- BSP:
- .config:
- action:
]

[bsp/readme]Update README.md

---

libcpu/arm/cortex-m33/cpuport.h

Fix compilation problem when block is turned on, remove RT_HW_INCLUDE_CPUPORT definition
[
- BSP:
- .config:
- action:
]

[fix]Fix compilation problem when block is turned on

---

bsp/at32/tools/sdk_dist.py

[bsp][at32]Update AT32 sdk_dist.py

---

bsp/stm32/stm32h723-st-nucleo/.config
bsp/stm32/stm32h723-st-nucleo/board/SConscript
bsp/stm32/stm32h723-st-nucleo/project.uvoptx
bsp/stm32/stm32h723-st-nucleo/project.uvprojx
bsp/stm32/stm32h723-st-nucleo/rtconfig.h

[
fix bug#[9995](https://github.com/RT-Thread/rt-thread/issues/9995) : startup file names change to H723
correct the startup file names
- BSP: bsp/stm32/stm32h723-st-nucleo
- .config: CONFIG_BOARD_STM32H723_NUCLEO / CONFIG_SOC_STM32H723ZG
- action:
]

[bsp][stm32][stm32h723-st-nucleo] fix bug#9995 : startup file names change to H723

---

bsp/cvitek/README.md

Fixed #10139 
Add description on how to configure pinmux in menuconfig for cvitek products.
Add myself to maintainer list in README.md.
[
请看 PR 描述。
- BSP:
- .config:
- action:
]

bsp: cvitek: add howto configure pinmux in README

---

bsp/cvitek/drivers/drv_spi.c
bsp/cvitek/drivers/libraries/spi/dw_spi.c

Fixed #10138 
See https://github.com/RT-Thread/rt-thread/issues/10138.
解决编译中的告警问题。
[
- BSP:
- .config:
- action:
]

bsp: cvitek: fix build warnings for spi

---

bsp/stm32/stm32h750-artpi/.ci/attachconfig/ci.attachconfig.yml

[
- BSP:
- .config:
- action:
]

[bsp/stm32-h750-art-pi] 添加zephyr_polling Kconfig

---

include/rtdef.h
src/Kconfig

[
- BSP:
- .config:
- action:
]

Update include/rtdef.h  version to 5.2.1

---

bsp/raspberry-pi/raspi2/cpu/cpuport.h

Add support for spinlock 
Address raspi2's lack of cpuport.h in version 5.1.0 and later of Code
[
- BSP: bsp/raspberry-pi/raspi2
- .config:
- action:
]

[BSP][raspberry-pi/raspi2]Add cpuport.h

---

bsp/gd32/arm/gd32103c-eval/board/Kconfig
bsp/gd32/arm/gd32105c-eval/board/Kconfig
bsp/gd32/arm/gd32105r-start/board/Kconfig
bsp/gd32/arm/gd32107c-eval/board/Kconfig
bsp/gd32/arm/gd32205r-start/board/Kconfig
bsp/gd32/arm/gd32207i-eval/board/Kconfig
bsp/gd32/arm/gd32303c-start/board/Kconfig
bsp/gd32/arm/gd32303e-eval/board/Kconfig
bsp/gd32/arm/gd32305r-start/board/Kconfig
bsp/gd32/arm/gd32307e-start/board/Kconfig
bsp/gd32/arm/gd32407v-lckfb/board/Kconfig
bsp/gd32/arm/gd32407v-start/board/Kconfig
bsp/gd32/arm/gd32450z-eval/board/Kconfig
bsp/gd32/arm/gd32470z-lckfb/board/Kconfig
bsp/gd32/arm/gd32e503v-eval/board/Kconfig
bsp/gd32/arm/gd32h759i-start/board/Kconfig
bsp/gd32/risc-v/gd32vf103r-start/board/Kconfig
bsp/gd32/risc-v/gd32vf103v-eval/board/Kconfig

[
* GD32的BSP中使用scons --dist生成的project无法使用menuconfig命令。
* 在每个BSP/board/Kconfig中将rsource "../../libraries/gd32_drivers/Kconfig"替换为source "$(BSP_DIR)/../libraries/gd32_drivers/Kconfig"。
- BSP: gd32303c-start
- .config: none
- action:
]

[bsp][gd32]修复了GD32目录下BSP使用dist后生成的工程无法使用menuconfig的问题

---

include/rtdef.h

[
RT_TIMER_CTRL_SET_PARM注释错误
- BSP:
- .config:
- action:
]

【修改】timer parameter注释

---

bsp/gd32/arm/libraries/gd32_drivers/drv_rtc.c

[
其语法错误:#elifdef BSP_RTC_USING_LSI
修改为 #elif def BSP_RTC_USING_LSI
- BSP:
- .config:
- action:
]

[bsp/gd32/arm/libraries] Repair naming

---

bsp/gd32/arm/libraries/gd32_drivers/drv_rtc.c

[
修复条件编译判断语句的语法
采用 
#if defined(xxx) 
#elif defined(xxx)
#endif
语法
- BSP:
- .config:
- action:
]

[bsp/gd32/libraries] Repair naming

---

libcpu/aarch64/common/mmu.c

[
- BSP:
- .config:
- action:
]

libcpu: aarch64: Fix NORMAL_NOCACHE_MEM attr

---

bsp/gd32/arm/gd32e503v-eval/.ci/attachconfig/ci.attachconfig.yml
bsp/gd32/arm/libraries/gd32_drivers/drv_adc.c

[
使用armclang编译drv_adc.c失败，提示incompatible function pointer types initializing.
修改类型
- BSP:
- .config:
- action:
]

[bsp/gd32/arm/drv_adc] incompatible function pointer types initializing.

---

.github/ALL_BSP_COMPILE.json

[
- BSP:
- .config:
- action:
]

[action/ci] add qemu-virt64-riscv

---

documentation/3.kernel/INDEX.md

Fixed one minor bug pointed out by Copilot: <https://github.com/RT-Thread/rt-thread/pull/10197#discussion_r2049938949>.
[
- BSP:
- .config:
- action:
]

doxygen: fix one typo issue

---

bsp/at32/tools/sdk_dist.py

[
[bsp/at32] fixed 'scons --dist' error
]

[bsp/at32] fixed 'scons --dist' error

---

bsp/Infineon/libraries/HAL_Drivers/drv_gpio.c

[
英飞凌drv_gpio.c中的ifx_pin_irq_enable中，当enabled = PIN_IRQ_DISABLE情况下，irqmap未赋值导致程序进入hardfault，同时Cy_GPIO_Port_Deinit(CYHAL_GET_PORTADDR(gpio_pin));我认为是无必要的，关中断原有的引脚配置不应被改变。
在enabled == PIN_IRQ_DISABLE情况中添加irqmap = &pin_irq_map[gpio_port];，删除Cy_GPIO_Port_Deinit(CYHAL_GET_PORTADDR(gpio_pin));
- BSP:bsp/Infineon/libraries/HAL_Drivers
- .config:无
- action: 修改的非bsp文件
]

修改ifx_pin_irq_enable函数

---

bsp/k210/drivers/drv_i2c.c

[
k210的i2c驱动文件少了sdk的i2c.h导致Packages仓库那边的ci编译不过
添加上就好了
- BSP:
- .config:
- action:
]

bsp: k210: fix drv_i2c's include file

---

bsp/stm32/docs/STM32系列外设驱动添加指南.md

The link pointed to by (bsp/stm32/docs/STM32系列驱动介绍.md) is invalid and updated again.
[
- BSP:
- .config:
- action:
]

[Docs] Modify invalid links

---

bsp/gd32/arm/libraries/gd32_drivers/drv_can.c

[
- BSP: bsp/gd32/arm/gd32f450z-eval
- .config:
CONFIG_RT_USING_CAN=y
CONFIG_BSP_USING_CAN=y
CONFIG_BSP_USING_CAN0=y
CONFIG_BSP_CAN0_TX_PB9=y
CONFIG_BSP_CAN0_RX_PB8=y
CONFIG_BSP_USING_CAN1=y
CONFIG_BSP_CAN1_TX_PB6=y
CONFIG_BSP_CAN1_RX_PB5=y
- action:
]

GD32 CAN hdr_bank set in filter initialization

---

.github/workflows/auto-assign-reviewers.yml

[
当 PR 修改的文件不属于 MAINTAINERS 文件中定义的路径时，不生成机器人评论，同时跳过不必要的文件执行步骤
- BSP:
- .config:
- action:
]

ci: optimize the logic for generating comments for the maintainer robot

---

.github/workflows/auto-assign-reviewers.yml

[
取消maintainer yml脚本中对MAINTAINER文件的过滤，以便能够正常检测到该文件的修改
- BSP:
- .config:
- action:
]

ci: cancel the filtering rules for the MAINTAINER file

---

MAINTAINERS

我申请作为 documentation 的维护人员。请批准，谢谢。
[
- BSP:
- .config:
- action:
]

MAINTAINERS: add myself as owner of documentation

---

.github/ALL_BSP_COMPILE.json

[
https://github.com/RT-Thread/rt-thread/issues/10268
先删除，等后续修改gitee链接为github再放上去
- BSP:
- .config:
- action:
]

[action] Remove phytium because of gitee link sdk

---

MAINTAINERS

请见标题
[
- BSP:
- .config:
- action:
]

MAINTAINERS: add myself as owner of bsp/cvitek & bsp/k230

---

bsp/k230/board/board.c

原先的 reboot 实现有问题，无法重启。
现加入 sysctl 驱动后，可以使用sysctl 提供的 reset 接口 reboot 系统。
[
- BSP:
- .config:
- action:
]

bsp: k230: use sysctl to reboot the board

---

bsp/k230/SConstruct

以前执行 scons -c 时不会清理 build 目录和自动生成的 link.lds.generated。现在补上。
[
- BSP:
- .config:
- action:
]

bsp: k230: improve cleanup

---

bsp/k230/README.md
bsp/k230/flashsd.sh
bsp/k230/utils.sh

添加一个脚本 `flashsd.sh` 来调用 rttpkgtool 的 `sdcard.sh`。该脚本封装了对 rttpkgtool 的检查和下载功能，并调用 `./script/sdcard.sh`。新脚本避免打印 `sdcard.sh` 的输出，而是根据封装后的逻辑进行输出，因此用户无需学习如何使用 `sdcard.sh`。
新建一个 `utils.sh` 脚本，将公共的函数提取到这里。
更新 `README.md`。
[
- BSP:
- .config:
- action:
]

bsp: k230: add flashsd script

---

MAINTAINERS

[
- BSP:
- .config:
- action:
]

MAINTAINERS: serial_v2 按照字母顺序进行排序

---

bsp/stm32/README.md

[
update STM32 README.md doc
add descriptions of 2 board in README.md doc
- BSP:
- .config:
- action:
]

[bsp][stm32] add descriptions of 2 board in README.md doc

---

bsp/k230/drivers/utest/test_wdt.c

为 watchdog 的 utest 代码改用 utest 的 assert API，精简代码。
[
- BSP:
- .config:
- action:
]

bsp: k230: use utest asset api

---

src/scheduler_comm.c
src/scheduler_mp.c
src/scheduler_up.c

[
完善内核scheduler部分的doxygen注释。
补充内核scheduler部分的doxygen注释。
- BSP:
- .config:
- action:
]

[kernel]add doxygen comments for scheduler.

---

bsp/k230/drivers/interdrv/gpio/SConscript
bsp/k230/drivers/interdrv/gpio/drv_gpio.c
bsp/k230/drivers/interdrv/gpio/drv_gpio.h
bsp/k230/drivers/utest/SConscript
bsp/k230/drivers/utest/test_gpio.c
bsp/k230/drivers/utest/test_gpio_irq.c

K230 supports 3 GPIO groups:
group0: GPIO0  ~ GPIO31, support i/o and irq
group1: GPIO32 ~ GPIO63, support i/o and irq
group2: GPIO64 ~ GPIO71, only support i/o.
同时添加 GPIO 驱动的 utest 测试用例。
[
- BSP:
- .config:
- action:
]

bsp: k230: add gpio driver

---

MAINTAINERS

[
new reviewer applies to join.
new reviewer applies to join.
- BSP:
- .config:
- action:
]

Maintainer: new reviewer applies to join.

---

.vscode/workspace.json

[
使用vscode smart扩展打开rt-thread目录时，需要在.vscode下有一份workspace.json来激活插件。
添加一个最简单的示例性文件。
- BSP:
- .config:
- action:
]

[vscode] add sample workspace.json

---

bsp/k230/README.md

bsp 文档改进。
[
- BSP:
- .config:
- action:
]

bsp: k230: imprvove README

---

MAINTAINERS

[
add more MAINTAINERS lists
update MAINTAINERS doc
- BSP:
- .config:
- action:
]

[MAINTAINERS] add more MAINTAINERS lists

---

bsp/xuantie/smartl/e902/SConscript
bsp/xuantie/smartl/e902/rtconfig.py
bsp/xuantie/smartl/e906/SConscript
bsp/xuantie/smartl/e906/rtconfig.py
bsp/xuantie/smartl/e907/SConscript
bsp/xuantie/smartl/e907/rtconfig.py
bsp/xuantie/tools/sdk_dist.py
bsp/xuantie/xiaohui/c906/SConscript
bsp/xuantie/xiaohui/c906/rtconfig.py
bsp/xuantie/xiaohui/c907/SConscript
bsp/xuantie/xiaohui/c907/rtconfig.py
bsp/xuantie/xiaohui/c908/SConscript
bsp/xuantie/xiaohui/c908/rtconfig.py
bsp/xuantie/xiaohui/c910/SConscript
bsp/xuantie/xiaohui/c910/rtconfig.py
bsp/xuantie/xiaohui/r908/SConscript
bsp/xuantie/xiaohui/r908/rtconfig.py
bsp/xuantie/xiaohui/r910/SConscript
bsp/xuantie/xiaohui/r910/rtconfig.py
bsp/xuantie/xiaohui/r920/SConscript
bsp/xuantie/xiaohui/r920/rtconfig.py

[
修复xuantie系列bsp的dist功能
添加dist脚本与修正bsp的脚本
]

[bsp/xuantie] 修复bsp的dist功能

---

bsp/renesas/libraries/HAL_Drivers/drv_hwtimer.c

[
修复硬件定时器获取计数值异常的问题
- BSP:
- .config:
- action:
]

bsp/renesas: fix the problem of abnormal timer count

---

MAINTAINERS

[
添加lizhen9880为bsp_stm32f429-atk-apollo和at组件的维护者
- BSP:
- .config:
- action:
]

maintainers: 添加lizhen9880为bsp_stm32f429-atk-apollo和at组件的维护者

---

MAINTAINERS

[
- 本提交不涉及代码，只更改MAINTAINERS文件，把用户名更改为GitHub id；
]

[MAINTAINERS] Change user name Chasel to Maihuanyi(github id)

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_pwm.c

[
- pulse无法设置为0,导致无法输出0%占空比
- BSP:
- .config:
- action:
]

[stm32] Modify MIN_PERIOD and MIN_PULSE to Allow PWM Duty Cycle of 0%

---

components/drivers/include/drivers/dev_serial_v2.h

[
- 修改 RT_SERIAL_CONFIG_DEFAULT 结构的默认配置，以支持 没有DMA 情况下的 dma_ping_bufsz 参数
- BSP:
- .config:
- action:
]

[serial_v2]modify the default configuration of the RT_SERIAL_CONFIG_DEFAULT structure to support parameters in the absence of DMA configuration.

---

MAINTAINERS

…o，driver_spi
[
- BSP:
- .config:
- action:
]

[MAINTAINERS]  增加Liang He为bsp_stm32， bsp_stm32f103-blue-pill，bsp_stm32f412 维护者

---

MAINTAINERS

规范 tag 的写法
更新 Note 中对 tag 的编写要求，建议 tag 的命名直接参考模块在代码树种的路径，譬如如果模块路径是 'bsp/cvitek'，那么 tag 的名字就用 'bsp_cvitek'。而且命名用小写。这样便于统一大家的 tag 的命名，否则目前看上去比较混乱。
根据以上规则，调整了现有 entry 的 tag 名字。其他不变。
其他一些文本的修改主要是限制了每行的宽度，尽量不要超过 80 列。
[
- BSP:
- .config:
- action:
]

MAINTAINER: standardize tag writing

---

.github/workflows/auto-assign-reviewers.yml
.github/workflows/bsp_buildings.yml

[
1.修复对于不同TAG同一路径的reviewer异常问题
2.优化评论@机制
3.优化缓存机制，确保正确找到缓存list
4.修改参考时间为中国/上海时间
5.修改不必要的bsp_building ci触发条件
6.修复maintainer ci因git rebase/git reset导致API获取异常问题
- BSP:
- .config:
- action:
]

ci/maintainer: merge same tag with different paths, remove Path display from CI comment

---

bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart_v2.c
bsp/stm32/libraries/HAL_Drivers/drivers/drv_usart_v2.h

同步V1版本的兼容方法，h5平台验证过
[
- BSP:
- .config:
- action:
]

[bsp][stm32][usart_v2] 优化usart_2驱动兼容性

---

components/drivers/serial/dev_serial_v2.c

[
- BSP:
- .config:
- action:
]

[drivers][serial_v2] 修复dma下rx_flush的bug

---

bsp/gd32/arm/gd32527I-eval/board/Kconfig

[
- BSP:
- .config:
- action:
]

fix gd32 dist bug

---

components/dfs/dfs_v2/src/dfs_file.c

[
add doxygen comments for dfs_file.c in dfs_v2.
add doxygen comments for dfs_file.c in dfs_v2.
- BSP:
- .config:
- action:
]

[components/dfs]add doxygen comments for dfs_file.c in dfs_v2.

---

include/rtdef.h

[
- BSP:
- .config:
- action:
]

Update RT_VERSION to 5.2.2

---

components/net/sal/src/sal_socket.c

[
- BSP:
- .config:
- action:
]

[fix][ci]Fixed CI compilation failure in sal/src/sal_socket.c

---

components/finsh/cmd.c

[
这段代码多余操作
清理删除
- BSP:
- .config:
- action:
]

[components][finsh] 清理掉无用的拷贝操作

---

.github/CODEOWNERS

[
重点维护renesas及GD32 bsp
- BSP:
- .config:
- action:
]

maintainer: add new code owner for renesas and gd32(arm)

---

bsp/gd32/arm/libraries/gd32_drivers/drv_usart.c

[
修正GD32H7 BSP UART驱动管脚配置不正确的问题
在GD32H759与GD32H737上验证通过
]

[gd32][fix] 修正UART驱动管脚配置不正确的问题
